import type { Modulo } from "./tipos";

export const M1: Modulo = {
  id: "m1", nivel: 1, titulo: "Fundamentos do vendedor de máquinas pesadas", tema: "Base", cor: "#60a5fa",
  descricao: "Mentalidade, funil, comunicação, rotina e domínio do produto e do território. Sem essa base, nenhuma técnica avançada segura.",
  objetivos: [
    "Entender por que a venda de máquina pesada é uma decisão de investimento e como isso muda a sua postura.",
    "Dominar o funil de vendas e a matemática de atividades que gera uma venda por semana.",
    "Falar de produto em termos de resultado, não de ficha técnica.",
    "Conhecer cada perfil de comprador do sul do ES e o calendário de cada um.",
    "Comunicar-se com profissionalismo no WhatsApp e no campo.",
    "Organizar a semana para produzir contatos, visitas e propostas de forma constante.",
  ],
  leituras: [
    "Neil Rackham — SPIN Selling (a base da venda consultiva de alto valor).",
    "Matthew Dixon e Brent Adamson — A Venda Desafiadora (The Challenger Sale).",
    "Jeb Blount — Fanatical Prospecting (rotina e disciplina de prospecção).",
  ],
  aulas: [
    {
      id: "m1a1", titulo: "A mentalidade de quem vende máquina de R$ 500 mil", minutos: 12,
      resumo: "Venda consultiva de alto valor é decisão de investimento, não compra por impulso. Quem entende isso vende com calma e autoridade.",
      blocos: [
        { tipo: "p", texto: "Uma retroescavadeira B95C ou uma escavadeira E215C não é comprada como se compra um celular. É uma decisão que envolve fluxo de caixa, financiamento, obra no prazo e, muitas vezes, o patrimônio da família do dono. O seu papel não é “empurrar” — é ser o profissional que ajuda o cliente a tomar uma decisão de investimento com segurança. Quem age assim é procurado; quem age como tirador de pedido é evitado." },
        { tipo: "lista", titulo: "As 5 crenças do vendedor de alta performance", itens: [
          "Eu resolvo problema de produção, não vendo ferro. O cliente quer a obra andando, a pedreira produzindo, o cafezal preparado.",
          "Preço é a última conversa, nunca a primeira. Quem começa por preço vira commodity e perde para o mais barato.",
          "Cada “não” é informação. Anoto o motivo, marco retorno e sigo — a maioria das vendas acontece depois do 4º contato.",
          "Meu diferencial sou eu: presença na obra, resposta rápida, palavra cumprida. Isso o concorrente não copia com desconto.",
          "Eu controlo atividades (visitas, propostas, contatos); o resultado é consequência da rotina, não da sorte.",
        ] },
        { tipo: "tabela", titulo: "Tirador de pedido x consultor de investimento", colunas: ["Situação", "Tirador de pedido", "Consultor"], linhas: [
          ["Cliente pergunta preço", "Manda a tabela na hora", "Pergunta a aplicação e a frota antes; apresenta valor, depois preço"],
          ["Cliente diz “vou pensar”", "“Tá bom, qualquer coisa me chama”", "“Claro. O que precisa ficar claro pra você decidir? Quinta eu passo aí?”"],
          ["Concorrente mais barato", "Pede desconto pro gerente", "Mostra a conta de 5 anos e o custo da máquina parada"],
          ["Depois da venda", "Some", "Entrega técnica, marcos de 30/60/180/365 dias, indicação"],
          ["Semana fraca", "Espera o telefone tocar", "Aumenta prospecção e revisa o funil"],
        ] },
        { tipo: "destaque", titulo: "Regra de ouro", texto: "Na venda de alto valor, confiança vale mais que argumento. Cumpra o combinado (hora, retorno, informação) e você já está na frente de 80% dos vendedores." },
        { tipo: "p", titulo: "O ciclo real da venda no seu mercado", texto: "Do primeiro contato ao faturamento passam, em média, várias semanas: contato → visita à obra → proposta → análise de crédito/financiamento → negociação → fechamento → faturamento → entrega técnica. Cada etapa tem um objetivo claro e você deve saber em qual etapa cada cliente está (é para isso que existe o funil de Negociações do CRM). Vendedor sem funil vende no escuro." },
        { tipo: "caso", titulo: "Caso: a retro que “estava cara”", situacao: "Empreiteiro de Alegre pediu preço de uma B95C por WhatsApp. O vendedor mandou o valor na hora. Resposta: “nossa, tá caro, a chinesa é 100 mil a menos”. Conversa morreu.", acao: "Duas semanas depois, o vendedor foi à obra sem falar de preço. Descobriu que a retro antiga parava 3 dias por mês e que ele alugava outra para cobrir (R$ 1.100/dia). Fez a conta na frente dele: R$ 3.300/mês de aluguel + operador parado + atraso na medição da prefeitura.", resultado: "O cliente pediu a proposta de novo — e fechou com entrada da usada. A “chinesa mais barata” nunca mais foi citada.", licao: "Preço sem contexto vira comparação. Contexto (a dor em reais) transforma preço em investimento." },
        { tipo: "erros", titulo: "Erros que matam o iniciante", itens: [
          "Responder preço antes de entender aplicação, frota e forma de pagamento.",
          "Prometer prazo de entrega ou condição sem confirmar — perde a confiança na primeira falha.",
          "Falar mal do concorrente. No interior a fama corre; seja o profissional que respeita.",
          "Não registrar no CRM. O que não está registrado não é acompanhado — e some.",
          "Desistir depois do segundo “não”. A maioria das vendas de máquina acontece entre o 4º e o 8º contato.",
        ] },
        { tipo: "exercicio", titulo: "Exercício de reflexão", texto: "Escreva, em uma frase cada, o que o seu cliente de café, o seu cliente de pedreira e a prefeitura realmente compram quando compram uma máquina (não é “uma retro”; é “a estrada pronta antes da chuva”, “a produção sem parar”, “o cafezal preparado a tempo”). Cole essas frases no seu celular." },
      ],
      missao: "Abra o funil de Negociações e, para cada negociação em aberto, escreva em uma frase qual é o PRÓXIMO PASSO concreto (não “acompanhar”: “ligar quinta para confirmar visita”, “enviar proposta da B95C até sexta”). Salve no campo de próxima ação.",
      quiz: [
        { pergunta: "Qual é a primeira coisa a fazer quando um cliente novo pergunta “quanto custa a retro?”", opcoes: ["Passar o preço na hora, para não perder o cliente", "Entender a obra/aplicação antes de falar de preço", "Dizer que o preço depende e encerrar"], correta: 1, explicacao: "Preço sem contexto vira comparação com o mais barato. Aplicação e dor primeiro; preço depois, já com valor construído." },
        { pergunta: "O que o vendedor controla de verdade?", opcoes: ["O resultado do mês", "As atividades: visitas, propostas, contatos", "O humor do cliente"], correta: 1, explicacao: "Resultado é consequência. Atividade é escolha diária." },
        { pergunta: "Cliente disse “não” duas vezes. O que fazer?", opcoes: ["Excluir do CRM", "Registrar o motivo, marcar retorno e continuar a cadência", "Ligar todo dia até ele ceder"], correta: 1, explicacao: "O “não” de hoje costuma ser “ainda não”. A cadência certa, com motivo registrado, é o que traz a venda depois." },
      ],
    },
    {
      id: "m1a2", titulo: "O funil e a matemática da venda: quantas atividades geram uma máquina vendida", minutos: 11,
      resumo: "Vendedor de elite conhece seus números. Aprenda a calcular quantos contatos, visitas e propostas você precisa para bater a meta.",
      blocos: [
        { tipo: "p", texto: "Vender máquina é um jogo de números com qualidade. Se você sabe que a cada 10 propostas fecha 2, e que a cada 3 visitas sai 1 proposta, então uma venda exige 5 propostas e 15 visitas. Meta de 4 máquinas no mês? 20 propostas ativas e 60 visitas. Sem esses números, você trabalha no achismo e culpa o mercado." },
        { tipo: "tabela", titulo: "Funil de referência para máquinas pesadas no interior", colunas: ["Etapa", "Conversão típica", "Para 1 venda"], linhas: [
          ["Contato novo → conversa qualificada", "50%", "10 contatos"],
          ["Conversa qualificada → visita/diagnóstico", "60%", "5 conversas → 3 visitas"],
          ["Visita → proposta", "65%", "3 visitas → 2 propostas"],
          ["Proposta → negociação (crédito, usada)", "70%", "2 propostas → 1,4 negociações"],
          ["Negociação → faturamento", "70%", "≈ 1 venda"],
        ] },
        { tipo: "p", titulo: "Como achar os SEUS números", texto: "No Dashboard e no funil de Negociações do CRM, conte: quantas negociações abriu nos últimos 90 dias, quantas viraram proposta, quantas fecharam. Divida. Esses são os seus índices reais — e é neles que você trabalha. Se a conversão de proposta para fechamento está abaixo de 25%, o problema é objeção/fechamento (módulos 7 e 8). Se faltam propostas, o problema é prospecção e diagnóstico (módulos 4 e 5)." },
        { tipo: "lista", titulo: "As etapas do funil no CRM e o objetivo de cada uma", itens: [
          "Contato / Lead: descobrir se tem aplicação e quem decide. Objetivo: marcar a visita.",
          "Visita / Diagnóstico: entender frota, dor, prazo e forma de pagamento. Objetivo: autorização para montar a proposta.",
          "Proposta enviada: valor com retorno em reais e validade. Objetivo: reunião de revisão marcada.",
          "Em negociação: objeções, crédito, usada na troca. Objetivo: o “sim” pequeno (documentos, reserva).",
          "Ganha / Faturada: nota emitida. Objetivo: entrega técnica e pós-venda.",
          "Perdida: motivo registrado e data de reengajamento. Objetivo: voltar na hora certa.",
        ] },
        { tipo: "destaque", titulo: "Regra do funil cheio", texto: "Para cada máquina que você quer vender no mês, mantenha pelo menos 5 propostas vivas e 10 negociações em andamento. Funil magro é ansiedade na semana 3 e desconto na semana 4." },
        { tipo: "caso", titulo: "Caso: o mês de 6 máquinas", situacao: "Em agosto o vendedor fechou 6 máquinas — recorde. Em setembro, 0. Em outubro, 1.", acao: "Ao revisar o CRM, viu que em agosto passou o mês inteiro fechando e não abriu nenhuma negociação nova. O funil esvaziou. Em outubro voltou a prospectar 5 contatos por semana, sem parar mesmo nas semanas de fechamento.", resultado: "De dezembro em diante, média estável de 3 a 4 máquinas/mês, sem picos e vales.", licao: "Prospecção não para nunca — nem no mês recorde. O resultado de hoje é a prospecção de 60 dias atrás." },
        { tipo: "checklist", titulo: "Revisão semanal do funil (toda segunda, 30 minutos)", itens: [
          "Quantas negociações novas abri na semana? (meta: 5)",
          "Quantas visitas fiz? (meta: 12 a 15)",
          "Quantas propostas enviei? (meta: 4 a 5)",
          "Quais negociações estão paradas há mais de 7 dias sem próxima ação?",
          "Quais estão há 30+ dias sem contato? (o Dashboard mostra)",
          "Qual é a próxima ação concreta de cada negociação quente?",
        ] },
      ],
      missao: "Calcule os seus índices reais dos últimos 90 dias usando o funil do CRM (contatos → visitas → propostas → fechamentos). Descubra quantas visitas por semana você precisa para a sua meta e escreva o número na agenda.",
      quiz: [
        { pergunta: "Você fecha 1 a cada 5 propostas e faz 1 proposta a cada 3 visitas. Para vender 2 máquinas no mês precisa de:", opcoes: ["10 propostas e 30 visitas", "5 propostas e 10 visitas", "2 propostas e 6 visitas"], correta: 0, explicacao: "2 vendas × 5 propostas = 10 propostas; 10 propostas × 3 visitas = 30 visitas." },
        { pergunta: "Faltam propostas no funil. Onde está o gargalo?", opcoes: ["Fechamento", "Prospecção e diagnóstico", "Pós-venda"], correta: 1, explicacao: "Sem visitas e diagnóstico não há proposta. Trabalhe a entrada do funil." },
      ],
    },
    {
      id: "m1a3", titulo: "Domínio de produto: fale de resultado, não de ficha técnica", minutos: 12,
      resumo: "Ninguém compra 97 cv ou 8,5 toneladas. Compram obra no prazo, diesel a menos e máquina que não para.",
      blocos: [
        { tipo: "p", texto: "Ficha técnica é para você saber; benefício é para o cliente ouvir. Cada característica precisa virar uma frase de resultado no mundo do cliente. O vendedor que decora dados impressiona; o que traduz dados em dinheiro vende." },
        { tipo: "tabela", titulo: "Tradução característica → resultado (New Holland)", colunas: ["Característica", "O que o cliente ouve"], linhas: [
          ["Motor FPT com gerenciamento eletrônico", "Menos diesel por hora. Numa retro que roda 150 h/mês, 0,5 L/h a menos são cerca de R$ 450/mês só de combustível."],
          ["Rede de concessionárias e peças na região", "Máquina parada por peça custa mais de R$ 3 mil por dia. Aqui você tem estoque e assistência em Cachoeiro."],
          ["Cabine com ar e visibilidade", "Operador rende mais à tarde e erra menos. Operador bom fica com quem tem máquina boa."],
          ["Valor de revenda alto", "Daqui a 5 anos essa máquina vale 50–55% do que você pagou. A de marca fraca vale 30%. A diferença é a sua entrada na próxima."],
          ["Retro 4x4 com caçamba 4 em 1", "Uma máquina faz o serviço de duas na obra pequena: escava, carrega, nivela, agarra."],
          ["Escavadeira E215C com modo ECO", "Mais toneladas por litro na pedreira. Produtividade medida em caçambas por hora, não em cavalo."],
        ] },
        { tipo: "tabela", titulo: "Tradução característica → resultado (Dynapac)", colunas: ["Característica", "O que o cliente ouve"], linhas: [
          ["Tambor com amplitude dupla (CA2500/CA3500)", "Compacta em menos passadas: menos diesel, menos hora-máquina, trecho liberado mais cedo."],
          ["Sistema de compactação inteligente / medidor", "Você prova ao fiscal que atingiu o grau de compactação. Menos ensaio reprovado, menos retrabalho."],
          ["Tambor pé-de-carneiro para solo coesivo", "Argila do sul do ES compacta de verdade — sem “borrachudo” que estoura o asfalto em 6 meses."],
          ["Rolo tandem CC1200/CC2200", "Acabamento de asfalto sem marca e sem trinca; a prefeitura aceita na primeira medição."],
        ] },
        { tipo: "destaque", titulo: "Ferramenta do CRM", texto: "As Fichas Técnicas e o Comparativo têm os dados verificados de cada modelo. Antes de uma visita, releia a ficha do modelo que vai apresentar e escolha 3 traduções para aquele cliente." },
        { tipo: "p", titulo: "Custo da máquina parada", texto: "Aprenda a fazer esta conta com o cliente: operador (diária) + máquina alugada para cobrir (diária) + atraso no prazo (multa ou perda de medição) = custo por dia parado. Em obra pública ou pedreira, um dia parado passa fácil de R$ 3 mil. Isso muda a conversa sobre “a marca X é mais barata”." },
        { tipo: "script", titulo: "Três traduções na prática", itens: [
          "“Essa retro tem tração 4x4 e caçamba 4 em 1. Na sua obra isso quer dizer que uma máquina só abre a vala, carrega o caminhão e nivela o terreno — você para de pagar hora de pá-carregadeira de terceiro.”",
          "“O motor dela consome em média 0,5 litro a menos por hora que a sua antiga. Rodando 150 horas no mês, é uns R$ 450 por mês só de diesel — em 5 anos, R$ 27 mil que ficam com você.”",
          "“A diferença de preço pra marca X é R$ 60 mil. Só que daqui a 5 anos a New Holland vale uns R$ 90 mil a mais na revenda. Quem sai na frente?”",
        ] },
        { tipo: "erros", titulo: "Erros de quem “sabe tudo de máquina”", itens: [
          "Despejar ficha técnica em cima do cliente D (direto) — ele quer resultado em uma frase.",
          "Comparar só cavalo e peso. Compare consumo por tonelada, disponibilidade e revenda.",
          "Inventar dado. Se não sabe, diga “vou confirmar e te mando hoje” — e mande.",
          "Falar de tecnologia que o cliente não vai usar. Escolha as 3 que resolvem a dor dele.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue a Ficha Técnica de um modelo que você vende pouco (ex.: W130B ou CC1200). Escreva 5 traduções “característica → resultado em reais” para o cliente que mais compra esse modelo. Use no próximo contato desse nicho." },
      ],
      missao: "Antes de cada visita desta semana, anote 3 traduções “característica → resultado em dinheiro” para o cliente. Use pelo menos uma na conversa e registre no CRM qual funcionou.",
      quiz: [
        { pergunta: "Cliente de pedreira pergunta sobre a escavadeira E215C. Melhor abordagem:", opcoes: ["Ler a ficha técnica completa", "Falar de caçambas por hora, consumo por tonelada e assistência", "Mostrar a cor da cabine"], correta: 1, explicacao: "Pedreira vive de produção e disponibilidade. Traduza a máquina em toneladas por dia e em dias parados evitados." },
        { pergunta: "O que faz a diferença de preço para a marca mais barata “sumir”?", opcoes: ["Um desconto", "Consumo, disponibilidade e valor de revenda em 5 anos", "A cor da máquina"], correta: 1, explicacao: "Custo total de propriedade: é a conta de 5 anos que decide, não o preço de entrada." },
        { pergunta: "Você não sabe um dado que o cliente perguntou. O que faz?", opcoes: ["Inventa um valor aproximado", "Diz que vai confirmar e manda no mesmo dia", "Muda de assunto"], correta: 1, explicacao: "Dado inventado quebra a confiança quando descoberto. Confirmar e cumprir constrói autoridade." },
      ],
    },
    {
      id: "m1a4", titulo: "O seu território: quem compra máquina no sul do ES", minutos: 11,
      resumo: "Construtora, empreiteira, prefeitura, pedreira, cafeicultor, locadora: cada um decide diferente. Conheça os perfis e o calendário.",
      blocos: [
        { tipo: "tabela", titulo: "Perfis, o que move cada um e a máquina típica", colunas: ["Perfil", "O que move", "Máquinas", "Ciclo"], linhas: [
          ["Construtora / empreiteira", "Prazo da obra, medição, custo por hora, financiamento", "Retro B95C/B110B, escavadeira E145C/E215C, rolo CA2500", "4–10 semanas"],
          ["Prefeitura", "Licitação, orçamento anual, visibilidade política, assistência", "Retro, motoniveladora RG140B/RG170B, pá W130B, rolo", "2–8 meses"],
          ["Pedreira / granito", "Produção (t/h), disponibilidade, consumo, peças", "E215C/E245C, pá W170B/W190B", "4–12 semanas"],
          ["Produtor / cooperativa de café", "Safra, crédito rural, terraceamento, estradas internas", "Retro, mini/escavadeira E145C, RG140B", "Sazonal (2º semestre)"],
          ["Locadora", "Retorno por hora locada, revenda, manutenção", "Retro, mini, rolo", "2–6 semanas"],
          ["Pequeno terraplenador", "Parcela que cabe, trabalho para fechar, troca da usada", "Retro usada/nova, mini", "1–4 semanas"],
        ] },
        { tipo: "p", titulo: "Calendário do território", texto: "Café: crédito rural e decisão de compra concentram entre a colheita e o plantio (segundo semestre). Prefeituras: início e fim de mandato mexem com compras; evite contar com fechamento em período eleitoral. Construção: começo de ano é planejamento; obras arrancam de março em diante. Pedreiras: compram quando fecham contrato grande de brita (obras rodoviárias, portos). Use o letreiro e as notícias do Dashboard para pegar o sinal (preço do café, crédito, obras anunciadas)." },
        { tipo: "lista", titulo: "Regiões do sul do ES (como estão no CRM) e o que domina em cada uma", itens: [
          "Região do Granito (Cachoeiro, Vargem Alta, Castelo, Mimoso): pedreiras, serrarias, transportadores — escavadeira e pá.",
          "Caparaó (Guaçuí, Alegre, Iúna, Ibitirama, Irupi, Divino): café de montanha, prefeituras pequenas, estradas de terra — retro, motoniveladora.",
          "Litorânea (Marataízes, Itapemirim, Presidente Kennedy, Piúma, Anchieta): construção civil, porto, obras de saneamento — retro, escavadeira, rolo.",
          "Serrana sul (Muniz Freire, Ibatiba, Brejetuba, Venda Nova): café e agricultura familiar — retro, mini, crédito rural.",
          "Das Santas (Rio Novo do Sul, Iconha, Vargem Alta): banana, café, obras municipais — retro, pá pequena.",
        ] },
        { tipo: "destaque", titulo: "Mapa de oportunidades", texto: "No Dashboard, o mapa do ES mostra onde você já vendeu. As cidades sem cifrão perto das que têm são o seu próximo alvo: mesmo perfil de cliente, sem concorrência de referência." },
        { tipo: "caso", titulo: "Caso: a cidade sem cifrão", situacao: "Vendedor tinha 4 vendas em Cachoeiro e nenhuma em Vargem Alta, a 20 minutos, com o mesmo perfil de cliente (pedreira e serraria).", acao: "Pegou as duas pedreiras de Cachoeiro que compraram, pediu indicação e permissão para citar. Foi a Vargem Alta com fotos das máquinas trabalhando e a frase “a pedreira do fulano, aqui do lado, trocou por E215C”.", resultado: "Duas visitas viraram uma proposta em 10 dias e um fechamento em 45.", licao: "Prova social de vizinho é a porta mais fácil de abrir. O mapa mostra onde ela ainda não foi usada." },
        { tipo: "exercicio", titulo: "Exercício", texto: "Abra o mapa do Dashboard. Liste 3 cidades sem venda que fazem fronteira com cidades onde você já vendeu. Para cada uma, escreva o perfil dominante e um cliente satisfeito da cidade vizinha que pode servir de referência." },
      ],
      missao: "Cadastre no CRM 5 novos clientes potenciais de uma cidade onde você ainda não vendeu (use o mapa do Dashboard para escolher). Marque a região e o perfil de cada um.",
      quiz: [
        { pergunta: "Produtor de café com máquina cansada em março. Quando ele tende a decidir?", opcoes: ["Imediatamente", "Depois da colheita, com crédito da safra", "Nunca"], correta: 1, explicacao: "O calendário do café concentra decisão e crédito no segundo semestre. Plante agora para colher o fechamento na safra." },
        { pergunta: "Onde está o próximo alvo de prospecção mais fácil?", opcoes: ["Numa cidade distante e grande", "Na cidade vizinha de onde já vendi, com o mesmo perfil de cliente", "Só em Cachoeiro"], correta: 1, explicacao: "Mesmo perfil + prova social do vizinho = porta aberta." },
        { pergunta: "O que mais pesa na decisão de uma pedreira?", opcoes: ["Cor e conforto", "Produção por hora, disponibilidade e peças", "Nome do vendedor"], correta: 1, explicacao: "Pedreira vive de tonelada produzida. Máquina parada é a maior dor." },
      ],
    },
    {
      id: "m1a5", titulo: "Comunicação profissional: WhatsApp, telefone e presencial", minutos: 10,
      resumo: "O cliente decide se você é profissional nos primeiros 30 segundos. Tempo de resposta, linguagem, áudio x texto e presença na obra.",
      blocos: [
        { tipo: "lista", titulo: "Regras do WhatsApp profissional", itens: [
          "Responda em até 15 minutos em horário comercial. Se não puder resolver, responda mesmo assim: “vi aqui, te retorno até as 16h”.",
          "Texto para informação (preço, condição, dados): fica registrado e o cliente encaminha para o sócio. Áudio para emoção e relação (parabéns, agradecimento, explicação de conta) — máximo 40 segundos.",
          "Uma ideia por mensagem. Bloco enorme de texto não é lido.",
          "Termine sempre com uma pergunta ou próximo passo: “Posso passar aí quinta às 9h?”.",
          "Nada de “bom dia” solto esperando resposta. Mande o conteúdo junto.",
          "Foto e vídeo da máquina trabalhando na região valem mais que catálogo em PDF.",
        ] },
        { tipo: "p", titulo: "Ao telefone", texto: "Ligue quando a conversa por texto travou (duas mensagens sem avanço), quando há emoção envolvida (financiamento negado, reclamação) e para fechar. Abra com o motivo em 10 segundos: “Edy da New Holland, te ligo por causa da proposta da retro: o banco aprovou. Tem 2 minutos?”. Nunca ligue só para “dar um alô”." },
        { tipo: "p", titulo: "Presencial", texto: "Chegue na hora. Calça, bota e camisa da marca. Cumprimente o operador e o encarregado, não só o dono. Olhe a obra antes de falar de máquina. Anote em caderno ou no CRM na frente do cliente — isso mostra que o que ele diz importa. Saia sempre com um próximo passo combinado (data e hora)." },
        { tipo: "script", titulo: "Mensagens modelo", itens: [
          "Retorno rápido: “Vi a sua mensagem, estou em visita. Às 16h te mando a condição completa da B95C. Combinado?”",
          "Confirmação de visita: “Confirmando nossa visita amanhã às 9h na obra do Loteamento Sol. Vou levar o comparativo que você pediu. Precisa de mais alguma informação antes?”",
          "Depois da visita: “Obrigado pelo tempo hoje. Resumo do que combinamos: proposta da E215C com entrada da sua usada até sexta, revisão juntos na segunda às 10h. Qualquer ajuste me avisa.”",
        ] },
        { tipo: "erros", titulo: "Erros de comunicação que custam venda", itens: [
          "Áudio de 3 minutos com informação de preço no meio — o cliente não acha depois.",
          "Responder “kkk” ou emoji sozinho para cliente formal (perfil C ou prefeitura).",
          "Demorar 2 dias para responder e abrir com “desculpa a demora”.",
          "Mandar proposta sem mensagem pessoal e sem marcar a hora de revisar.",
          "Escrever com erro de português em proposta e mensagem formal. Releia antes de enviar.",
        ] },
        { tipo: "destaque", titulo: "A IA do CRM é sua assistente, não sua voz", texto: "O Orientador de Vendas sugere respostas rápidas e o Cérebro rascunha mensagens. Revise sempre: a mensagem tem que soar como você, com os dados certos daquele cliente." },
      ],
      missao: "Revise as 10 últimas conversas do WhatsApp no CRM. Marque quais terminaram sem próximo passo e mande hoje uma mensagem curta com pergunta e proposta de data para cada uma.",
      quiz: [
        { pergunta: "Cliente pergunta a condição de pagamento por WhatsApp. Melhor formato:", opcoes: ["Áudio de 2 minutos explicando tudo", "Texto curto com os números e uma pergunta de próximo passo", "Ligar e não responder por texto"], correta: 1, explicacao: "Informação em texto fica registrada e é encaminhável ao sócio. Áudio é para relação, não para dado." },
        { pergunta: "Quando ligar em vez de mandar mensagem?", opcoes: ["Sempre", "Quando o texto travou, há emoção envolvida ou é hora de fechar", "Nunca"], correta: 1, explicacao: "Ligação resolve o que o texto não resolve: emoção, impasse e fechamento." },
      ],
    },
    {
      id: "m1a6", titulo: "Rotina e gestão do tempo do vendedor de campo", minutos: 10,
      resumo: "Vendedor sem rotina vive apagando incêndio. Blocos fixos de prospecção, campo, propostas e pós-venda — e energia para sustentar.",
      blocos: [
        { tipo: "p", texto: "O maior inimigo do vendedor externo não é o concorrente: é o dia que “acontece” em vez de ser planejado. Sem blocos fixos, a prospecção é a primeira coisa que some, e 60 dias depois o funil está vazio. A rotina protege a prospecção de você mesmo." },
        { tipo: "tabela", titulo: "Semana modelo", colunas: ["Dia", "Manhã", "Tarde"], linhas: [
          ["Segunda", "Revisão do funil no CRM (30 min) + 10 contatos de prospecção", "Propostas pendentes + cobrança de bancos"],
          ["Terça", "Rota região 1: 3 visitas (1 prospecto novo, 1 negociação, 1 pós-venda)", "Rota região 1: 2 visitas + registro no CRM"],
          ["Quarta", "Rota região 2: 3 visitas", "Rota região 2: 2 visitas + registro"],
          ["Quinta", "Rota região 3: 3 visitas", "Rota região 3: 2 visitas + registro"],
          ["Sexta", "Reuniões de revisão de proposta + fechamentos", "Financiamento, documentos, planejamento da próxima semana"],
          ["Sábado (2 h)", "Pós-venda: marcos do CRM, indicações, mensagens de relacionamento", "—"],
        ] },
        { tipo: "lista", titulo: "Princípios de produtividade em campo", itens: [
          "Prospecção primeiro, antes de abrir o WhatsApp — de manhã, com energia.",
          "Agrupe visitas por região (o CRM tem a região de cada cliente). Deslocamento é o maior desperdício.",
          "Registre no CRM na hora, no carro, antes de sair para a próxima. À noite você não lembra.",
          "Uma lista de 3 prioridades por dia. Se fez as 3, o dia foi bom, mesmo sem fechar.",
          "Bloqueie 20 minutos diários de estudo (uma aula desta trilha). Vendedor que para de estudar para de crescer.",
          "Durma, coma e treine: venda de campo é físico. Energia baixa vira desconto fácil e follow-up esquecido.",
        ] },
        { tipo: "checklist", titulo: "Checklist diário (5 minutos antes de sair)", itens: [
          "Sei quais 3 a 5 visitas vou fazer e o objetivo de cada uma?",
          "Tenho a ficha/comparativo do modelo de cada visita?",
          "Respondi todas as mensagens pendentes do CRM?",
          "Tem alguma negociação quente sem próxima ação marcada?",
          "Tenho 2 contatos de prospecção para fazer nos intervalos?",
        ] },
        { tipo: "caso", titulo: "Caso: a agenda que dobrou as visitas", situacao: "Vendedor fazia 6 visitas por semana, espalhadas em 4 regiões, e passava 3 horas por dia dirigindo.", acao: "Passou a dedicar um dia a cada região e a marcar as visitas em sequência geográfica. Prospectos novos foram encaixados entre visitas já marcadas.", resultado: "14 visitas por semana com o mesmo tempo de estrada. Propostas passaram de 2 para 5 por semana.", licao: "Produtividade em campo é rota. O CRM por região existe para isso." },
      ],
      missao: "Monte a sua semana modelo na agenda do celular com blocos fixos (prospecção, rotas por região, propostas, pós-venda, estudo). Cumpra por 2 semanas e compare as visitas e propostas no Dashboard.",
      quiz: [
        { pergunta: "Qual atividade deve ser protegida primeiro na rotina?", opcoes: ["Responder WhatsApp", "Prospecção", "Reunião de fechamento"], correta: 1, explicacao: "Prospecção é a primeira a sumir quando o dia aperta — e é a que alimenta o funil de 60 dias à frente." },
        { pergunta: "Quando registrar a visita no CRM?", opcoes: ["No fim do dia", "Na hora, antes da próxima visita", "No fim da semana"], correta: 1, explicacao: "Detalhe e próximo passo se perdem em horas. Registro imediato é o que faz o CRM trabalhar por você." },
      ],
    },
  ],
  prova: [
    { pergunta: "Qual é a postura do consultor quando o cliente diz “vou pensar”?", opcoes: ["“Qualquer coisa me chama”", "Perguntar o que precisa ficar claro e propor data de retorno", "Oferecer desconto para decidir agora"], correta: 1, explicacao: "Consultor conduz o processo: entende a dúvida e combina o próximo passo." },
    { pergunta: "Você fecha 1 a cada 4 propostas. Para 3 máquinas no mês precisa manter quantas propostas vivas?", opcoes: ["3", "12", "6"], correta: 1, explicacao: "3 × 4 = 12 propostas." },
    { pergunta: "A melhor forma de apresentar “motor com gerenciamento eletrônico” para um empreiteiro é:", opcoes: ["Explicar a injeção eletrônica", "Traduzir em litros e reais por mês", "Dizer que é tecnologia de ponta"], correta: 1, explicacao: "Característica vira resultado em dinheiro no mundo do cliente." },
    { pergunta: "Qual perfil tem o ciclo de compra mais longo e depende de licitação?", opcoes: ["Locadora", "Prefeitura", "Pequeno terraplenador"], correta: 1, explicacao: "Compra pública tem orçamento anual, pregão e prazos próprios." },
    { pergunta: "Cliente formal (prefeitura) manda uma dúvida sobre garantia. Você responde com:", opcoes: ["Áudio de 2 minutos", "Texto objetivo com os termos e uma pergunta de próximo passo", "Emoji de positivo"], correta: 1, explicacao: "Informação formal em texto, registrada e encaminhável." },
    { pergunta: "Por que agrupar visitas por região?", opcoes: ["Para conhecer a cidade", "Para dobrar visitas com o mesmo tempo de estrada", "Não faz diferença"], correta: 1, explicacao: "Deslocamento é o maior desperdício do vendedor externo." },
  ],
};
