import type { Modulo } from "./tipos";

export const M1: Modulo = {
  id: "m1", nivel: 1, titulo: "Fundamentos e a economia da máquina", tema: "Base", cor: "#60a5fa",
  descricao: "O que o vendedor de máquina pesada realmente vende, a matemática do funil, o custo por hora e o TCO, como o cliente paga (FINAME, CDC, consórcio, licitação) e quem compra no sul do ES. Sem essa base, técnica avançada é enfeite.",
  objetivos: [
    "Assumir o papel de consultor de investimento: o cliente compra produção, prazo e patrimônio — não ferro.",
    "Calcular os próprios índices de funil e a cobertura de pipeline necessária para a meta.",
    "Montar, de cabeça, o custo por hora e o TCO de 5 anos de uma máquina com os números do cliente.",
    "Conhecer cada caminho de pagamento (FINAME, CDC, consórcio, Banco CNH, usada na troca, licitação) e quando cada um serve.",
    "Traduzir ficha técnica em resultado em reais para cada modelo que você vende.",
    "Ler o território: perfis de comprador, calendário de cada um e como pontuar um cliente ideal.",
  ],
  leituras: [
    "Neil Rackham — SPIN Selling: a origem da venda consultiva de alto valor, com pesquisa em 35 mil visitas.",
    "Matthew Dixon e Brent Adamson — A Venda Desafiadora: por que o vendedor que ensina vence o que só se relaciona.",
    "Jeb Blount — Fanatical Prospecting: a disciplina de encher o funil todos os dias.",
    "Cartilha FINAME/BNDES (site do BNDES) e o regulamento do Plano Safra vigente: leia uma vez por ano, com a mudança de taxas.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m1a1", titulo: "O que você vende quando vende uma máquina de R$ 600 mil", minutos: 14,
      resumo: "Uma escavadeira não é comprada como um celular. É uma decisão de investimento com fluxo de caixa, financiamento, obra no prazo e patrimônio de família em jogo. Quem entende isso vende com calma e autoridade.",
      blocos: [
        { tipo: "p", texto: "Quando um empreiteiro de Cachoeiro compra uma E215C, ele não está comprando 22 toneladas de aço. Ele está comprando a medição da prefeitura no fim do mês, o caminhão carregado em 4 minutos e não em 7, o operador que não pede demissão porque a cabine tem ar, e a revenda daqui a cinco anos que vira entrada da próxima. O vendedor mediano vende a máquina. O consultor vende a decisão de investimento — e é por isso que o consultor é chamado de volta e o vendedor é comparado por preço." },
        { tipo: "framework", nome: "Os 4 papéis do vendedor consultivo", origem: "Síntese de Rackham (SPIN Selling), Dixon & Adamson (Challenger) e da prática de bens de capital", passos: [
          "Diagnosticador: descobre a aplicação, a frota, a dor em reais e quem decide — antes de falar de produto. Sem diagnóstico não há proposta, há chute.",
          "Professor: traz um insight que o cliente não tinha (custo da máquina parada, consumo por tonelada, valor de revenda) e muda o critério de decisão de 'preço' para 'custo total'.",
          "Engenheiro financeiro: monta o caminho de pagamento que cabe no caixa do cliente (FINAME, CDC, consórcio, usada na troca) — resolver o dinheiro é parte da venda.",
          "Gestor da conta: entrega técnica, marcos de pós-venda, indicação. A primeira venda custa caro; a segunda e a terceira pagam a carreira.",
        ] },
        { tipo: "tabela", titulo: "Tirador de pedido × consultor de investimento", colunas: ["Situação", "Tirador de pedido", "Consultor"], linhas: [
          ["Cliente pergunta preço no WhatsApp", "Manda a tabela na hora", "Pergunta aplicação, horas/mês e forma de pagamento; marca visita; preço vem com a conta"],
          ["Cliente diz 'vou pensar'", "'Tá bom, qualquer coisa me chama'", "'Claro. O que precisa ficar claro pra você decidir? Quinta eu passo na obra?'"],
          ["Concorrente 15% mais barato", "Pede desconto pro gerente", "Mostra custo por hora, disponibilidade e revenda em 5 anos; oferece a conta lado a lado"],
          ["Banco negou o crédito", "'Então não dá'", "Consórcio com lance, entrada com a usada, outro banco, classe abaixo — resolve ou pausa com data"],
          ["Depois da venda", "Some", "Entrega técnica, 30/60/180/365 dias, pede indicação"],
          ["Semana fraca", "Espera o telefone tocar", "Aumenta prospecção e revisa o funil (é o que o Dashboard mostra)"],
        ] },
        { tipo: "p", titulo: "O ciclo real da venda no seu mercado", texto: "Do primeiro contato ao faturamento passam, em média, de 3 a 10 semanas: contato → visita à obra → diagnóstico → proposta com a conta → análise de crédito → negociação (usada, prazo, implementos) → fechamento → faturamento → entrega técnica. Cada etapa tem um objetivo único — e o funil de Negociações do CRM existe para você saber em qual etapa cada cliente está. Vendedor sem funil vende no escuro e descobre o mês perdido no dia 25." },
        { tipo: "dialogo", titulo: "Mesma pergunta, dois vendedores", falas: [
          { quem: "cliente", texto: "Boa tarde. Quanto tá a retro B95C?" },
          { quem: "vendedor", texto: "Boa tarde! Tá R$ 480 mil à vista, posso te mandar a tabela." },
          { quem: "nota", texto: "Preço sem contexto. Nos próximos 30 segundos o cliente vai abrir o WhatsApp do concorrente e comparar só número. Você virou commodity." },
          { quem: "cliente", texto: "Boa tarde. Quanto tá a retro B95C?" },
          { quem: "vendedor", texto: "Boa tarde, Renato! Te passo com a condição certa, não só o número da tabela. Me ajuda em duas coisas: ela vai pra qual serviço — vala, carregamento, obra de rede? E roda mais ou menos quantas horas por mês?" },
          { quem: "cliente", texto: "Rede de água pra prefeitura, umas 160 horas." },
          { quem: "vendedor", texto: "Então o que pesa pra você é disponibilidade e consumo, porque medição atrasada é multa. Amanhã de manhã eu passo na obra 20 minutos, vejo o terreno e te levo a proposta com a parcela e a conta de diesel. Às 8h ou às 10h fica melhor?" },
          { quem: "nota", texto: "Duas perguntas, um insight (medição atrasada = multa) e um próximo passo com alternativa de horário. Preço vai vir — mas com valor na frente." },
        ] },
        { tipo: "caso", titulo: "Caso: a retro que 'estava cara'", situacao: "Empreiteiro de Alegre pediu preço de uma B95C por WhatsApp. O vendedor mandou o valor na hora. Resposta: 'nossa, tá caro, a chinesa é 100 mil a menos'. A conversa morreu.", acao: "Duas semanas depois, o vendedor foi à obra sem falar de preço. Descobriu que a retro antiga parava 3 dias por mês e que ele alugava outra para cobrir (R$ 1.100/dia). Fez a conta na frente dele: R$ 3.300/mês de aluguel + operador parado + medição da prefeitura atrasada.", resultado: "O cliente pediu a proposta de novo e fechou com a usada como entrada. A 'chinesa mais barata' nunca mais foi citada.", licao: "Preço sem contexto vira comparação. Contexto — a dor em reais — transforma preço em investimento." },
        { tipo: "destaque", titulo: "Regra de ouro", texto: "Na venda de alto valor, confiança vale mais que argumento. Cumpra o combinado (hora, retorno, informação) e você já está na frente de 80% dos vendedores. O resto desta trilha ensina a ser melhor que os outros 20%." },
        { tipo: "erros", titulo: "Erros que matam o iniciante", itens: [
          "Responder preço antes de entender aplicação, horas por mês e forma de pagamento.",
          "Prometer prazo de entrega ou condição sem confirmar com a fábrica ou o banco — perde a confiança na primeira falha.",
          "Falar mal do concorrente. No interior a fama corre; seja o profissional que respeita.",
          "Não registrar no CRM. O que não está registrado não é acompanhado — e some no meio do mês.",
          "Desistir depois do segundo 'não'. A maioria das vendas de máquina acontece entre o 4º e o 8º contato.",
        ] },
        { tipo: "exercicio", titulo: "Exercício de reflexão", texto: "Escreva, em uma frase cada, o que o seu cliente de café, o seu cliente de pedreira e a prefeitura realmente compram quando compram uma máquina (não é 'uma retro'; é 'a estrada pronta antes da chuva', 'a produção sem parar', 'o cafezal preparado a tempo'). Cole essas frases no celular e leia antes de cada visita." },
      ],
      missao: "Abra o funil de Negociações e, para cada negociação em aberto, escreva no campo de próxima ação um passo concreto com data (não 'acompanhar': 'ligar quinta 9h para confirmar visita', 'enviar proposta da B95C com a conta de diesel até sexta'). Negociação sem próximo passo datado é negociação morrendo.",
      quiz: [
        { pergunta: "Um cliente novo manda no WhatsApp: 'quanto custa a E145C?'. Qual é a resposta que melhor protege o valor e ainda assim respeita o cliente?", opcoes: [
          "Mandar o preço de tabela na hora, com o desconto à vista, porque cliente que pergunta preço quer agilidade e transparência",
          "Responder que o preço depende de muitos fatores e pedir que ele ligue na concessionária para uma conversa mais completa",
          "Dizer que vai passar a condição certa e fazer duas perguntas (aplicação e horas por mês), já propondo uma visita à obra",
          "Perguntar primeiro qual é o orçamento disponível, para oferecer o modelo que cabe e não gastar o tempo dele com opções fora",
        ], correta: 2, explicacao: "Preço sem contexto vira comparação com o mais barato. Duas perguntas curtas (aplicação e horas/mês) mostram profissionalismo, dão o insight que reenquadra e levam a um próximo passo. 'Depende, me liga' soa como fuga; perguntar orçamento de cara é invasivo e ancora o cliente no valor mais baixo que ele imaginou." },
        { pergunta: "Qual dos quatro papéis do vendedor consultivo está faltando quando o cliente gosta da máquina, mas a negociação trava porque o banco negou o crédito e você respondeu 'então não dá'?", opcoes: [
          "O diagnosticador, porque sem a dor em reais o cliente não tem motivo para insistir no crédito depois do primeiro não",
          "O engenheiro financeiro, porque resolver o caminho de pagamento (outro banco, usada, consórcio) é parte da venda",
          "O professor, porque faltou o insight de custo total que faria o banco enxergar a máquina como geradora de receita",
          "O gestor da conta, porque uma relação de pós-venda bem construída teria dado histórico para a aprovação do crédito",
        ], correta: 1, explicacao: "Crédito negado não é fim: é hora de montar outro caminho (consórcio com lance, entrada com a usada, outro banco, classe abaixo). Quem para no 'não' do banco deixa a venda para o concorrente que conhece financiamento." },
        { pergunta: "O empreiteiro diz que a máquina antiga 'quebra de vez em quando'. Para transformar isso em argumento de investimento, o que o consultor faz primeiro?", opcoes: [
          "Pergunta quantos dias por mês ela para e quanto custa cobrir (aluguel, operador parado, medição), e soma na frente dele",
          "Oferece um desconto proporcional ao prejuízo que ele teve com a máquina velha, para compensar e criar reciprocidade",
          "Explica que toda máquina quebra e que o que diferencia as marcas é a assistência, apresentando a rede da região",
          "Apresenta a garantia estendida como solução direta para o problema de quebras, com o custo dela dentro da parcela",
        ], correta: 0, explicacao: "'Quebra de vez em quando' é dor vaga; 'R$ 3.300/mês de aluguel mais medição atrasada' é dor em reais. Só com o número o cliente compara o preço da máquina nova com o custo de ficar como está. Garantia e assistência entram depois, como prova." },
        { pergunta: "Você prometeu entrega em 20 dias sem confirmar com a fábrica. A máquina chega em 35. Qual é a consequência mais provável para a relação?", opcoes: [
          "O cliente pede um desconto proporcional ao atraso e, resolvida a compensação, a relação volta ao normal em poucas semanas",
          "A fábrica assume a responsabilidade pelo prazo e o cliente entende que o atraso não foi decisão do vendedor",
          "Nenhuma relevante para a relação, porque quinze dias de atraso são comuns no setor e o cliente já conta com isso",
          "O cliente perde a confiança na sua palavra, e cada promessa seguinte (consumo, revenda, assistência) passa a ser descontada",
        ], correta: 3, explicacao: "Na venda de alto valor, a moeda é a palavra cumprida. Um prazo prometido e furado contamina tudo o que você disser depois (consumo, revenda, assistência). Confirme antes de prometer; se não souber, diga que vai confirmar e cumpra o retorno." },
        { pergunta: "Por que o consultor pergunta 'quantas horas por mês' antes de falar em preço?", opcoes: [
          "Para saber se o cliente é grande o suficiente para merecer uma visita ou se deve ficar em contato por mensagem",
          "Porque horas por mês definem consumo, custo por hora e payback, os números que transformam preço em investimento",
          "Para estimar quando a máquina vai precisar da primeira revisão e já incluir o plano de manutenção na proposta",
          "Porque a fábrica exige a estimativa de uso no pedido para definir a configuração e o prazo de garantia da máquina",
        ], correta: 1, explicacao: "Com 160 h/mês, 2 L/h de diferença de consumo viram R$ 2.000/mês. Sem as horas, não há custo por hora, não há TCO e a conversa volta para 'quanto custa'. As horas são o primeiro número do diagnóstico." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m1a2", titulo: "A matemática do funil: quantas atividades geram uma máquina vendida", minutos: 13,
      resumo: "Vendedor de elite conhece os próprios números: conversão por etapa, cobertura de pipeline e atividades por semana. Sem isso você trabalha no achismo e culpa o mercado.",
      blocos: [
        { tipo: "p", texto: "Vender máquina é um jogo de números com qualidade. Se você fecha 2 a cada 10 propostas e faz 1 proposta a cada 3 visitas, então uma venda exige 5 propostas e 15 visitas. Meta de 4 máquinas no mês? 20 propostas e 60 visitas. Isso não é motivação, é aritmética — e é a única coisa que você controla de verdade. O resultado é consequência da atividade de 60 dias atrás." },
        { tipo: "conta", titulo: "Meta reversa: de 3 máquinas/mês para atividades por semana", linhas: [
          ["Meta do mês", "3 máquinas"],
          ["Conversão proposta → fechamento (seu histórico)", "25% → 12 propostas"],
          ["Conversão visita → proposta", "50% → 24 visitas"],
          ["Conversão conversa qualificada → visita", "60% → 40 conversas"],
          ["Conversão contato novo → conversa qualificada", "50% → 80 contatos novos"],
          ["Por semana (4,3 semanas)", "19 contatos · 9 conversas · 6 visitas · 3 propostas"],
        ], conclusao: "Seis visitas e três propostas por semana — todas as semanas, inclusive na de fechamento. Esse é o número que vai na agenda, não a meta." },
        { tipo: "framework", nome: "Cobertura de pipeline (3x)", origem: "Prática padrão de gestão comercial B2B (pipeline coverage)", passos: [
          "Some o valor ponderado das negociações abertas (o funil do CRM já pondera pela probabilidade da coluna).",
          "Divida pela meta do período. Abaixo de 3x, você vai faltar; entre 3x e 4x, saudável; acima de 5x, há negociação morta inflando o número.",
          "Cobertura baixa no dia 1 do mês só se resolve com prospecção HOJE — proposta leva 3 a 6 semanas para virar venda.",
          "Revise toda segunda: o que entrou, o que avançou, o que está parado há mais de 7 dias sem próxima ação.",
        ] },
        { tipo: "tabela", titulo: "Funil de referência para máquinas pesadas no interior", colunas: ["Etapa", "Conversão típica", "Objetivo da etapa"], linhas: [
          ["Contato novo → conversa qualificada", "40–55%", "Descobrir se há aplicação e quem decide; marcar a visita"],
          ["Conversa → visita/diagnóstico", "55–65%", "Ver a obra, a frota, a dor e a forma de pagamento; autorização para a proposta"],
          ["Visita → proposta", "50–65%", "Proposta com a conta (custo/hora, diesel, revenda) e validade; reunião de revisão marcada"],
          ["Proposta → negociação", "60–70%", "Crédito aprovado, usada avaliada, objeções tratadas; o 'sim' pequeno (documentos, reserva)"],
          ["Negociação → faturamento", "65–75%", "Nota emitida; entrega técnica agendada"],
        ] },
        { tipo: "p", titulo: "Como achar os SEUS números", texto: "No funil de Negociações do CRM, conte os últimos 90 dias: quantas negociações abriu, quantas viraram proposta, quantas fecharam. Divida. Esses são os seus índices — e é neles que você trabalha. Conversão proposta→fechamento abaixo de 25%? O problema é diagnóstico raso ou objeção mal tratada (módulos 4 e 7). Faltam propostas? O gargalo é prospecção (módulo 3). Muita proposta parada? Fechamento e follow-up (módulo 8). O funil diz onde estudar." },
        { tipo: "caso", titulo: "Caso: o mês de 6 máquinas", situacao: "Em agosto o vendedor fechou 6 máquinas — recorde. Em setembro, zero. Em outubro, uma.", acao: "Ao revisar o CRM, viu que em agosto passou o mês inteiro fechando e não abriu nenhuma negociação nova. O funil esvaziou. Em outubro voltou a prospectar 20 contatos por semana, inclusive nas semanas de fechamento, e passou a olhar a cobertura toda segunda.", resultado: "De dezembro em diante, média estável de 3 a 4 máquinas por mês, sem picos e vales. A comissão anual subiu 40% sem nenhum mês recorde.", licao: "Prospecção não para nunca — nem no mês recorde. O resultado de hoje é a prospecção de 60 dias atrás." },
        { tipo: "checklist", titulo: "Revisão semanal do funil (toda segunda, 30 minutos)", itens: [
          "Cobertura: valor ponderado aberto ÷ meta do mês ≥ 3x?",
          "Quantas negociações novas abri na semana? (meta: 5)",
          "Quantas visitas fiz? (meta: 6 a 8) Quantas propostas enviei? (meta: 3)",
          "Quais negociações estão paradas há mais de 7 dias sem próxima ação? Resolver hoje.",
          "Quais clientes estão há 30+ dias sem contato? (a Central de Alertas lista)",
          "Três perdas do mês: qual foi o motivo real de cada uma? (win/loss, módulo 8)",
        ] },
        { tipo: "erros", titulo: "Erros de quem 'não gosta de número'", itens: [
          "Contar proposta enviada como venda quase certa. Proposta sem reunião de revisão marcada tem 30% de chance, não 70%.",
          "Deixar negociação morta no funil para o número parecer bonito. Cobertura falsa é ansiedade na semana 4.",
          "Medir só resultado (máquinas). Resultado chega 60 dias atrasado; atividade avisa na hora.",
          "Mudar a meta em vez da atividade quando o mês vai mal.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue a sua meta anual, divida por 12 e monte a meta reversa como na conta acima, com os SEUS índices dos últimos 90 dias. Escreva o resultado em atividades por semana num papel colado na mesa: contatos, visitas, propostas. Esse papel vale mais que a meta." },
      ],
      missao: "Calcule os seus índices reais dos últimos 90 dias no funil do CRM (contatos → visitas → propostas → fechamentos) e a cobertura de pipeline de hoje (valor ponderado aberto ÷ meta do mês). Se estiver abaixo de 3x, abra cinco negociações novas ainda esta semana e registre cada uma com próxima ação datada.",
      quiz: [
        { pergunta: "Seu histórico: 1 fechamento a cada 4 propostas e 1 proposta a cada 2 visitas. Para vender 3 máquinas no mês, quantas propostas e visitas você precisa?", opcoes: [
          "12 propostas e 24 visitas",
          "6 propostas e 12 visitas",
          "12 propostas e 6 visitas",
          "3 propostas e 12 visitas",
        ], correta: 0, explicacao: "3 vendas × 4 propostas = 12 propostas; 12 propostas × 2 visitas = 24 visitas. A meta reversa multiplica as taxas de trás para a frente — e são essas 24 visitas (6 por semana) que vão na agenda." },
        { pergunta: "É dia 3 do mês, a meta é R$ 1,8 milhão e o funil ponderado do CRM mostra R$ 2,1 milhão. O que isso diz?", opcoes: [
          "Que o funil está inflado com negociações antigas e precisa ser limpo antes de qualquer conclusão sobre o mês",
          "Que o mês está garantido, porque o valor ponderado já supera a meta e basta acompanhar as negociações abertas",
          "Que a cobertura é de 1,2x, muito abaixo de 3x, e o problema só se resolve com prospecção imediata, não com fechamento",
          "Que é hora de acelerar as negociações abertas com desconto, porque o valor está perto da meta e falta pouco para fechar",
        ], correta: 2, explicacao: "Cobertura saudável é 3x a 4x a meta, porque nem tudo fecha e propostas levam semanas. Com 1,2x, apertar as negociações existentes rende pouco; abrir negociações novas hoje é o que salva o mês seguinte — e talvez este." },
        { pergunta: "Sua conversão de proposta para fechamento caiu de 30% para 15% em três meses, mas o volume de propostas se manteve. Em qual etapa do processo você deve procurar o problema primeiro?", opcoes: [
          "Na tabela de preços da fábrica, porque uma queda de conversão com o mesmo volume indica que o preço saiu do mercado",
          "Na prospecção, porque leads de pior qualidade entrando no funil chegam à proposta sem condições reais de fechar",
          "No pós-venda, porque a falta de indicações reduz a confiança dos novos clientes e derruba o fechamento",
          "No diagnóstico e no tratamento de objeções, porque propostas feitas sem valor construído chegam ao fim e não fecham",
        ], correta: 3, explicacao: "Quando o topo está normal e o fim do funil piora, a qualidade da proposta e do diagnóstico que a antecede é a suspeita número um: proposta enviada sem dor quantificada e sem próximo passo marcado vira 'vou pensar'. O funil aponta o módulo a estudar." },
        { pergunta: "Você fechou 5 máquinas em julho, o melhor mês do ano. Qual é o risco real de agosto e setembro?", opcoes: [
          "Nenhum relevante, porque cinco entregas técnicas bem feitas geram indicações que repõem o funil naturalmente",
          "O funil esvaziar, porque em julho você passou o mês fechando e não prospectou; o resultado de setembro é a prospecção de julho",
          "O gerente subir a meta com base no recorde, o que reduz o comissionamento relativo nos meses seguintes",
          "Os cinco clientes de julho entrarem no período de arrependimento ao mesmo tempo e consumirem todo o seu pós-venda",
        ], correta: 1, explicacao: "O ciclo de venda é de 3 a 10 semanas. Se a prospecção parou no mês recorde, o vale chega 60 dias depois. Por isso a atividade de entrada (contatos e visitas) tem meta semanal fixa, inclusive nas semanas de fechamento." },
        { pergunta: "Uma proposta foi enviada há 12 dias, sem reunião de revisão marcada e sem resposta. Como ela deve contar na sua cobertura de pipeline?", opcoes: [
          "Com probabilidade reduzida e próxima ação datada hoje, ou vai para 'perdida com motivo' para não inflar o funil",
          "Como venda quase certa, porque proposta enviada e não recusada em 12 dias é sinal de que o cliente está analisando",
          "Deve ser apagada do CRM, porque uma proposta sem resposta polui o histórico e distorce as métricas do vendedor",
          "Com a probabilidade cheia da coluna 'proposta', porque o cliente ainda não disse não e a regra do funil é por etapa",
        ], correta: 0, explicacao: "Proposta sem reunião marcada e sem resposta tem chance baixa; contar com probabilidade cheia cria cobertura falsa e ansiedade no fim do mês. O certo é agir (próxima ação datada) ou registrar a perda com motivo — o histórico serve para aprender, nunca se apaga." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m1a3", titulo: "Economia da máquina I: custo por hora e TCO de 5 anos", minutos: 16,
      resumo: "A ferramenta mais poderosa do vendedor de máquina pesada é uma conta simples feita na frente do cliente. Aprenda a montar o custo por hora e o custo total de propriedade — e a usar a Calculadora do CRM.",
      blocos: [
        { tipo: "p", texto: "O cliente olha o preço porque é o único número que ele tem. Seu trabalho é dar a ele os outros: quanto a máquina custa por hora rodando, quanto custa parada e quanto sobra na revenda. Quando esses números aparecem, a diferença de R$ 80 mil no preço vira R$ 12 por hora — e a conversa muda de 'qual é mais barata' para 'qual me custa menos'. Isso é TCO (custo total de propriedade), e é a base de toda a trilha." },
        { tipo: "framework", nome: "Custo por hora (CPH) em 5 parcelas", origem: "Método clássico de custo de equipamento (usado por construtoras e órgãos como o DNIT/SICRO), simplificado para a conversa de venda", passos: [
          "Depreciação: (preço de compra − valor de revenda) ÷ horas de vida no período. Ex.: (600.000 − 330.000) ÷ 9.000 h = R$ 30/h.",
          "Custo do capital: juros do financiamento (ou custo de oportunidade) ÷ horas. Ex.: R$ 90.000 de juros em 5 anos ÷ 9.000 h = R$ 10/h.",
          "Combustível: consumo (L/h) × preço do diesel. Ex.: 12 L/h × R$ 6,20 = R$ 74/h — o maior item em escavadeira.",
          "Manutenção e pneus/esteiras: revisões, filtros, óleo, material rodante, reparos. Regra de bolso: 60 a 100% da depreciação em máquina de esteira. Ex.: R$ 25/h.",
          "Operador e encargos: salário + encargos ÷ horas. Ex.: R$ 6.500 ÷ 176 h ≈ R$ 37/h. (Igual para qualquer marca — mas operador parado continua custando.)",
        ] },
        { tipo: "conta", titulo: "E215C × concorrente 'mais barata': a conta de 5 anos (180 h/mês, 10.800 h)", linhas: [
          ["Preço de compra: NH R$ 620 mil × conc. R$ 540 mil", "diferença de R$ 80 mil na entrada"],
          ["Revenda em 5 anos: NH 55% (R$ 341 mil) × conc. 35% (R$ 189 mil)", "depreciação NH R$ 279 mil × conc. R$ 351 mil"],
          ["Diesel: NH 12 L/h × conc. 13,5 L/h × R$ 6,20 × 10.800 h", "NH R$ 803 mil × conc. R$ 904 mil"],
          ["Máquina parada: NH 3 dias/ano × conc. 9 dias/ano × R$ 2.800/dia × 5 anos", "NH R$ 42 mil × conc. R$ 126 mil"],
          ["Manutenção (estimativa): NH R$ 250 mil × conc. R$ 290 mil", "diferença de R$ 40 mil"],
          ["TCO 5 anos (sem operador)", "NH R$ 1,374 mi × conc. R$ 1,671 mi"],
        ], conclusao: "A máquina R$ 80 mil mais barata custa R$ 297 mil a mais em cinco anos — R$ 27,50 por hora. É essa conta, com os números DO CLIENTE, que a Calculadora do CRM monta em 2 minutos." },
        { tipo: "p", titulo: "De onde tirar cada número (sem inventar)", texto: "Consumo: ficha técnica do CRM e, melhor ainda, a telemetria de um cliente seu com a mesma máquina (peça autorização para citar). Revenda: anúncios reais de usadas com 5 anos — mostre o print. Dias parados: pergunte ao cliente quantos dias a máquina atual ficou parada no último ano; ele sabe. Custo do dia parado: operador + máquina de aluguel para cobrir + atraso na medição. Diesel: o preço que ELE paga, não a média nacional. Número inventado quebra a conta inteira quando descoberto." },
        { tipo: "dialogo", titulo: "A conta na obra, em 4 minutos", falas: [
          { quem: "cliente", texto: "A XCMG tá 80 mil mais barata. Difícil justificar." },
          { quem: "vendedor", texto: "É uma diferença real, e eu não vou fingir que não existe. Posso te mostrar em quanto tempo ela some? Preciso de dois números seus: quantas horas por mês essa máquina vai rodar e quanto você paga no diesel." },
          { quem: "cliente", texto: "Umas 180 horas. Diesel tá 6,20." },
          { quem: "vendedor", texto: "Então: 1,5 litro por hora a menos vezes 6,20 vezes 180 horas dá R$ 1.674 por mês só de diesel — R$ 20 mil por ano. Em 5 anos, R$ 100 mil. Só aí os 80 mil já voltaram. E ainda tem a revenda: daqui a 5 anos essa aqui vale uns 340 mil; a outra, uns 190. Quer que eu monte isso num papel pra você levar pro seu sócio?" },
          { quem: "nota", texto: "Reconheceu a diferença (credibilidade), pediu os números do cliente (a conta é dele, não sua), fez a conta em voz alta e ofereceu o documento para o outro decisor. Nunca disse que o concorrente é ruim." },
        ] },
        { tipo: "tabela", titulo: "O que o cliente pergunta × a resposta em custo por hora", colunas: ["Pergunta do cliente", "Resposta fraca", "Resposta em CPH"], linhas: [
          ["'Por que ela é mais cara?'", "'Porque é New Holland, qualidade'", "'Ela custa R$ 12/h a mais na depreciação e R$ 15/h a menos no diesel e na parada. Líquido, você economiza R$ 3/h — aqui a conta.'"],
          ["'Vale a pena a versão com mais tecnologia?'", "'Vale, é mais moderna'", "'O modo ECO tira 8% do consumo: R$ 6/h. Em 5 anos são R$ 65 mil por um opcional de R$ 18 mil.'"],
          ["'E se eu comprar usada?'", "'Usada é risco'", "'Usada de 6 mil horas tem depreciação menor, mas parada e manutenção sobem. Vamos ver em qual hora o gráfico cruza — para sua obra pode fazer sentido.'"],
        ] },
        { tipo: "caso", titulo: "Caso: o rolo que se pagou em 14 meses", situacao: "Empreiteira de Guaçuí alugava um rolo CA25 por R$ 14 mil/mês, 8 meses por ano, para obras de pavimentação da prefeitura.", acao: "O vendedor somou: R$ 112 mil/ano de aluguel, sem patrimônio. Um CA2500 novo com FINAME saía em parcela de R$ 9.800/mês, e ao fim de 5 anos valia R$ 180 mil. Mostrou as duas colunas lado a lado, com a hipótese conservadora de 8 meses de uso.", resultado: "Fechou. A empresa passou a alugar o rolo para terceiros nos 4 meses parados e ainda faturou com ele.", licao: "Aluguel é despesa; máquina própria é patrimônio que gera receita. A conta lado a lado, sem retórica, decide." },
        { tipo: "erros", titulo: "Erros na conta", itens: [
          "Usar consumo de catálogo em vez do consumo real na aplicação do cliente (pedreira consome mais que vala).",
          "Esquecer o custo da máquina parada — em obra pública é o item que mais pesa e o que o cliente menos calcula.",
          "Comparar revenda de 5 anos com preço de máquina zero — compare com anúncio real de usada.",
          "Fazer a conta a favor demais. Se o cliente corrige um número e a conta vira, você perdeu a credibilidade. Use hipótese conservadora e diga isso.",
        ] },
        { tipo: "checklist", titulo: "Antes de apresentar uma conta", itens: [
          "Horas por mês e preço do diesel informados pelo cliente (não estimados por mim).",
          "Consumo de referência com fonte (ficha, telemetria, cliente que autorizou citar).",
          "Revenda com prova (anúncio ou avaliação de usada).",
          "Dias parados no último ano da máquina atual (perguntado ao cliente).",
          "Hipóteses conservadoras e ditas em voz alta ('estou sendo pessimista aqui de propósito').",
          "A conta impressa ou no CRM para o cliente levar ao sócio/financeiro.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Abra a Calculadora de combustível do CRM e monte três cenários para a E145C contra o concorrente que você mais enfrenta: 120, 160 e 200 horas por mês. Anote em quantos meses a diferença de preço volta em cada cenário. Esses três números você vai usar de cabeça na obra." },
      ],
      missao: "Escolha uma negociação aberta em que o cliente citou preço do concorrente. Levante os números dele (horas/mês, diesel, dias parados no último ano) — por WhatsApp se precisar — e monte a conta de 5 anos na Calculadora. Envie ao cliente com uma frase: 'fiz a conta com os seus números, hipótese conservadora'. Registre a reação na negociação.",
      quiz: [
        { pergunta: "Uma escavadeira custa R$ 600 mil, vale R$ 330 mil após 9.000 horas e consome 12 L/h com diesel a R$ 6,20. Sem contar manutenção, capital e operador, qual é o custo por hora aproximado?", opcoes: [
          "R$ 104/h de depreciação apenas, porque o diesel é despesa da obra e não entra no custo da máquina",
          "R$ 36/h, porque a revenda de R$ 330 mil cobre mais da metade do preço e dilui o custo por hora",
          "R$ 30/h de depreciação e R$ 74/h de diesel, cerca de R$ 104/h no total",
          "R$ 67/h de depreciação e R$ 12/h de diesel, cerca de R$ 79/h no total",
        ], correta: 2, explicacao: "Depreciação: (600.000 − 330.000) ÷ 9.000 = R$ 30/h. Diesel: 12 × 6,20 = R$ 74,40/h. O diesel é o maior item do custo por hora de uma escavadeira — por isso 1 L/h de diferença vale tanto quanto dezenas de milhares de reais no preço." },
        { pergunta: "O concorrente é R$ 80 mil mais barato. Com 180 h/mês, diesel a R$ 6,20 e consumo 1,5 L/h menor na New Holland, em aproximadamente quanto tempo só o diesel devolve a diferença?", opcoes: [
          "Em cerca de 8 meses",
          "Nunca, o diesel não cobre isso",
          "Em cerca de 2 anos",
          "Em cerca de 4 anos",
        ], correta: 3, explicacao: "1,5 × 6,20 × 180 = R$ 1.674/mês → R$ 20.088/ano. R$ 80.000 ÷ 20.088 ≈ 4 anos só com diesel. Somando revenda e dias parados, o cruzamento vem bem antes — mas a honestidade de dizer '4 anos só no diesel' é o que dá credibilidade à conta completa." },
        { pergunta: "Na conta de TCO, qual item costuma ser o mais subestimado pelo cliente e o que mais favorece a máquina com melhor assistência?", opcoes: [
          "O custo do operador, porque varia com a região e o cliente raramente inclui encargos e horas extras na conta",
          "O custo da máquina parada: operador ocioso, máquina de aluguel para cobrir e medição atrasada, tudo somado",
          "O seguro da máquina exigido pelo banco, que o cliente esquece de incluir e que pesa mais na máquina mais barata",
          "O custo de transporte até a obra, que muda a cada mobilização e costuma ficar fora da conta do cliente",
        ], correta: 1, explicacao: "Dias parados raramente entram na conta do cliente, mas em obra pública um dia pode passar de R$ 2.500 (operador + aluguel + atraso). É o item em que a rede de assistência local e a confiabilidade da máquina viram dinheiro contável." },
        { pergunta: "O cliente contesta o valor de revenda que você usou. Qual é a fonte que sustenta o número sem discussão?", opcoes: [
          "A sua experiência de anos no mercado, porque ninguém conhece a revenda regional melhor do que quem vende as usadas",
          "A tabela de preço da máquina nova com desconto de 50%, que é a regra de bolso usada pelos bancos na garantia",
          "Anúncios reais de usadas do mesmo modelo e idade, ou uma avaliação formal de usada, mostrados na hora",
          "A opinião do gerente da concessionária, que autoriza as avaliações de troca e conhece o valor de retomada",
        ], correta: 2, explicacao: "Revenda é o número mais fácil de comprovar e o mais fácil de perder credibilidade se for chute. Print de anúncio ou avaliação de usada encerra a discussão; 'experiência' e 'opinião' não." },
        { pergunta: "Você apresentou uma conta com hipóteses favoráveis; o cliente corrigiu o consumo e a vantagem sumiu. O que deveria ter sido feito desde o início?", opcoes: [
          "Usar hipóteses conservadoras, dizer isso em voz alta e deixar a conta fechar a favor mesmo no cenário pessimista",
          "Não mostrar conta nenhuma antes da proposta escrita, porque números apresentados cedo geram discussão e desconfiança",
          "Manter o consumo de catálogo como referência oficial e explicar que a medição do cliente tem variação de operador",
          "Compensar a diferença de consumo com um desconto no preço, para a vantagem financeira voltar a aparecer na conta",
        ], correta: 0, explicacao: "Uma conta que só fecha no cenário otimista é frágil. Ao usar o pior caso razoável e anunciar isso, você transfere a credibilidade para o cliente: se até no pessimismo a New Holland vence, não há o que corrigir. Desconto como remendo confirma que o valor não estava sustentado." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m1a4", titulo: "Economia da máquina II: como o cliente paga", minutos: 15,
      resumo: "FINAME, CDC de banco, consórcio, Banco CNH, leasing, usada na troca, Plano Safra e licitação. Quem domina o mapa de crédito fecha negócios que o vendedor comum perde no 'banco negou'.",
      blocos: [
        { tipo: "p", texto: "Em bens de capital, metade das vendas perdidas não morre no preço: morre no dinheiro. Cliente aprovado com parcela que não cabe, cliente reprovado sem alternativa, produtor que não sabia que tinha direito a taxa subsidiada, prefeitura que precisava de empenho antes do fim do exercício. O vendedor que entende financiamento é o único na mesa que consegue dizer 'tem outro caminho' — e é por isso que ele fecha." },
        { tipo: "tabela", titulo: "Mapa de crédito para máquinas pesadas", colunas: ["Caminho", "Para quem serve", "Como funciona", "Atenção"], linhas: [
          ["FINAME (BNDES via banco/Banco CNH)", "Empresa com CNPJ e faturamento regular; máquina nova nacional credenciada", "Prazo longo (até 5–10 anos), carência, taxa referenciada; o banco repassa recursos do BNDES", "Exige documentação completa e enquadramento da máquina (FINAME code); demora mais que CDC"],
          ["CDC bancário", "Cliente com relacionamento e limite no banco", "Aprovação rápida, prazo 36–60 meses, taxa de mercado", "Parcela mais alta; compare o CET, não só a taxa"],
          ["Banco CNH Industrial", "Cliente da marca que quer velocidade e prazo", "Financiamento da própria fabricante, campanhas por modelo, análise em dias", "Campanhas mudam por mês — pergunte antes de prometer"],
          ["Consórcio", "Quem não tem urgência ou não tem crédito bancário agora", "Parcelas sem juros (taxa de administração), contemplação por sorteio ou lance; lance com a usada", "Não serve para obra que começa mês que vem; serve para planejar frota"],
          ["Leasing / locação com opção", "Locadora e empresa que quer manter capital de giro", "Paga pelo uso; ativo fora do balanço em alguns casos", "Ler contrato: quilometragem/horas, manutenção, residual"],
          ["Usada na troca", "Quase todo cliente com máquina própria", "Avaliação → valor como entrada → reduz parcela e resolve o 'o que faço com a antiga'", "Avaliação realista; máquina com problema derruba a proposta"],
          ["Plano Safra / crédito rural (Moderfrota etc.)", "Produtor rural e cooperativa com DAP/CAF ou enquadramento", "Taxa subsidiada, prazo longo, carência; janela anual (julho a junho)", "Máquina e uso precisam se enquadrar (ex.: estrada da propriedade, terraplenagem agrícola); consulte o banco"],
          ["Licitação (pregão/registro de preços)", "Prefeituras e autarquias", "Edital, especificação técnica, proposta, empenho, entrega e liquidação", "O trabalho começa meses antes do edital: especificação e atestados"],
        ] },
        { tipo: "framework", nome: "Diagnóstico de pagamento em 5 perguntas", origem: "Prática de vendas financiadas de bens de capital", passos: [
          "'Como você costuma comprar máquina — financiado, à vista, consórcio?' (histórico revela caminho e limite).",
          "'Tem máquina para entrar como parte?' (a usada é a entrada mais comum e a que mais destrava).",
          "'Qual parcela cabe no seu caixa hoje sem apertar?' (a parcela manda; o preço é consequência de prazo e entrada).",
          "'Você é pessoa física, MEI, empresa? Tem CNPJ com faturamento?' (define FINAME, CDC ou consórcio).",
          "'Tem obra/contrato que justifique a compra para o banco?' (contrato assinado aprova crédito).",
        ] },
        { tipo: "conta", titulo: "Mesma máquina, três parcelas (E145C R$ 560 mil, ilustrativo)", linhas: [
          ["CDC 48 meses, sem entrada, taxa 1,6% a.m.", "≈ R$ 16.900/mês"],
          ["FINAME 60 meses, 20% de entrada (usada R$ 112 mil), taxa ≈ 1,1% a.m.", "≈ R$ 10.300/mês"],
          ["Consórcio 80 meses, lance de 25% com a usada", "≈ R$ 7.400/mês (sem juros; taxa adm. inclusa) — contemplação a combinar"],
          ["Receita da máquina a 160 h/mês × R$ 180/h de locação equivalente", "≈ R$ 28.800/mês"],
        ], conclusao: "A parcela FINAME com a usada como entrada representa 36% do que a máquina gera. É esse quociente — parcela ÷ receita gerada — que o cliente precisa ver. (Taxas ilustrativas: confirme as vigentes antes de apresentar.)" },
        { tipo: "dialogo", titulo: "'O banco negou'", falas: [
          { quem: "cliente", texto: "Meu gerente disse que não tenho limite pra essa parcela. Vou deixar pra o ano que vem." },
          { quem: "vendedor", texto: "Entendi. Antes de deixar pra o ano que vem, me deixa ver três caminhos que costumam resolver isso. Primeiro: a sua retro antiga entra como entrada — com 20% de entrada a parcela cai uns 35% e a análise muda. Segundo: pelo Banco CNH a análise é da fábrica, com outro apetite. Terceiro: se a obra da prefeitura já está assinada, o contrato entra como garantia de receita. Você tem esse contrato em mãos?" },
          { quem: "cliente", texto: "Tenho, é de 14 meses." },
          { quem: "vendedor", texto: "Então me manda o contrato e o CNPJ que eu monto duas propostas hoje: FINAME com a usada e CNH com a usada. Amanhã até as 17h você tem as duas parcelas na mão." },
          { quem: "nota", texto: "O 'não' do banco virou três alternativas concretas e um prazo. Nada de 'vou ver o que consigo'." },
        ] },
        { tipo: "p", titulo: "Prefeitura: o dinheiro tem calendário", texto: "A prefeitura compra por licitação, e a licitação começa muito antes do edital: quando o secretário de obras escreve a especificação técnica. Se a especificação sai copiada do catálogo do concorrente (potência, peso, itens que só ele tem), você já perdeu. O trabalho do vendedor é estar na secretaria antes — apresentando a máquina, entregando atestados de capacidade técnica de outras prefeituras, explicando o que é ficha 'aberta' (que aceita mais de uma marca). Depois vem o pregão, o empenho e o prazo de entrega; a máquina precisa estar em estoque ou com prazo de fábrica confirmado. Ano eleitoral tem restrição de compra em parte do ano — anote no calendário." },
        { tipo: "caso", titulo: "Caso: o consórcio que virou frota", situacao: "Locadora de Marataízes queria uma retro, mas o banco só aprovava parcela de CDC que apertava o caixa.", acao: "O vendedor propôs um consórcio de duas cotas com lance embutido da usada. A primeira cota foi contemplada em 4 meses; a segunda em 11. Enquanto isso, a locadora seguiu com a retro antiga.", resultado: "Em um ano, duas máquinas novas com parcela total menor que a do CDC de uma só. A locadora virou cliente de frota planejada — quatro máquinas em três anos.", licao: "Quando não há urgência, consórcio com lance planeja frota. O vendedor que oferece só CDC vende uma vez; o que planeja frota vende por anos." },
        { tipo: "erros", titulo: "Erros com financiamento", itens: [
          "Prometer taxa ou aprovação antes de o banco analisar. Diga 'a condição que está em campanha hoje é X, sujeita à análise'.",
          "Comparar taxas sem comparar o CET (custo efetivo total, com seguros e tarifas).",
          "Ignorar a usada. Ela é entrada, é o 'o que faço com a antiga' e muitas vezes é a diferença entre reprovado e aprovado.",
          "Não saber o calendário: Plano Safra (julho), fim do exercício da prefeitura (dezembro), restrição eleitoral.",
          "Mandar o cliente 'ver com o banco dele'. Você monta a proposta e acompanha a análise; isso é a venda.",
        ] },
        { tipo: "checklist", titulo: "Pasta de crédito pronta antes de propor", itens: [
          "Cartão CNPJ, contrato social, faturamento dos últimos 12 meses (ou DAP/CAF do produtor).",
          "Contrato de obra ou de prestação de serviço que justifique a máquina.",
          "Fotos e horímetro da usada para avaliação.",
          "Duas simulações: com e sem entrada da usada; dois prazos.",
          "Campanha vigente do Banco CNH conferida nesta semana.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para os três tipos de cliente que você mais atende (ex.: empreiteiro, produtor de café, prefeitura), escreva qual é o caminho de pagamento mais provável, o documento que destrava a análise e a janela do calendário. Confira as taxas vigentes hoje com o Banco CNH e um banco parceiro." },
      ],
      missao: "Liste no CRM as negociações paradas nos últimos 60 dias por motivo de crédito ou parcela. Para cada uma, monte uma alternativa concreta (usada como entrada, Banco CNH, consórcio com lance, contrato como garantia) e mande ao cliente uma mensagem de três linhas com a nova parcela. Registre quantas voltaram a conversar.",
      quiz: [
        { pergunta: "Um produtor de café de Iúna quer uma retro para estradas internas e conservação de terreiro. Qual caminho de pagamento você deve investigar primeiro?", opcoes: [
          "Consórcio com lance, porque produtor rural raramente tem urgência e o consórcio não cobra juros",
          "Leasing operacional, porque mantém o capital de giro da fazenda livre para a safra e tem vantagem fiscal",
          "CDC bancário comum no banco em que ele já tem conta, porque é o caminho mais rápido e sem burocracia rural",
          "Crédito rural do Plano Safra (linhas de investimento), se produtor e uso se enquadrarem: taxa subsidiada e prazo longo",
        ], correta: 3, explicacao: "Para produtor enquadrado, as linhas de investimento do crédito rural têm taxa e prazo que nenhum CDC alcança — mas há janela anual e regras de enquadramento da máquina e do uso. Quem não pergunta isso vende parcela cara ou perde para quem perguntou." },
        { pergunta: "O gerente do banco negou o limite para a parcela de uma E145C. O cliente tem uma escavadeira usada de 7.000 horas e um contrato de obra assinado. Qual é a melhor sequência?", opcoes: [
          "Aceitar o 'não' do banco, manter a relação e agendar retorno para o próximo exercício, quando o limite for revisto",
          "Oferecer um modelo de classe abaixo, que cabe no limite aprovado e resolve parte da necessidade da obra assinada",
          "Avaliar a usada como entrada, apresentar o contrato como receita e submeter ao Banco CNH e a outro banco, com prazo",
          "Pedir ao gerente que reconsidere com um desconto no preço, reduzindo o valor financiado até caber no limite",
        ], correta: 2, explicacao: "Entrada com a usada reduz a parcela em torno de um terço e muda a análise; contrato assinado justifica a compra; a fábrica tem outro apetite de crédito. Trocar de modelo antes de esgotar esses caminhos entrega menos máquina do que o cliente precisa." },
        { pergunta: "Duas propostas de financiamento: taxa de 1,3% a.m. com seguro obrigatório e tarifas, e 1,5% a.m. sem tarifas. Como você orienta o cliente?", opcoes: [
          "Comparar o CET (custo efetivo total) das duas, que inclui seguros e tarifas, e a parcela final que o cliente paga",
          "Escolher a do banco em que o cliente já tem conta, porque o relacionamento facilita a aprovação e futuras renegociações",
          "Recomendar a de 1,3%, porque a taxa nominal menor sempre resulta em menos juros ao longo dos 60 meses",
          "Recomendar a de 1,5% sem tarifas, porque seguros e tarifas embutidos costumam custar mais do que a diferença de taxa",
        ], correta: 0, explicacao: "Taxa nominal engana: seguros e tarifas podem inverter a comparação. O CET é o número que a lei obriga o banco a informar e o único que compara maçã com maçã. Orientar pelo CET é o que faz o cliente confiar em você para a próxima máquina." },
        { pergunta: "Você quer vender uma motoniveladora para uma prefeitura. Em que momento a venda realmente se decide?", opcoes: [
          "No dia do pregão, pelo menor preço, porque a lei obriga a prefeitura a comprar da proposta mais barata que se habilitar",
          "Meses antes, quando a secretaria escreve a especificação técnica do edital e reúne os atestados de capacidade",
          "Na entrega, quando o prefeito vê a máquina e decide se a próxima compra do município será da mesma marca",
          "No momento do empenho, quando o dinheiro é reservado e o secretário define qual fornecedor será chamado",
        ], correta: 1, explicacao: "Se a especificação sai copiada do catálogo do concorrente, o pregão já está perdido antes de começar. O trabalho do vendedor é estar na secretaria antes: apresentar a máquina, garantir ficha aberta e entregar atestados de outras prefeituras. Pregão e empenho são consequência." },
        { pergunta: "Uma locadora não tem urgência e o CDC aperta o caixa. Que solução tende a gerar não uma, mas várias vendas ao longo do tempo?", opcoes: [
          "Desconto agressivo para fechamento à vista, porque locadora com caixa apertado valoriza preço acima de tudo",
          "Locação da máquina pela própria concessionária, com opção de compra, para entrar na frota sem comprometer o caixa",
          "Esperar a locadora ganhar um contrato maior, porque sem urgência qualquer proposta vira referência de preço",
          "Consórcio em mais de uma cota com lance da usada, planejando a renovação da frota ao longo dos anos",
        ], correta: 3, explicacao: "Sem urgência, o consórcio elimina juros e permite planejar contemplações escalonadas; a usada entra como lance. O vendedor que monta esse plano deixa de vender uma máquina e passa a gerir a frota do cliente." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m1a5", titulo: "Domínio de produto: fale de resultado, não de ficha técnica", minutos: 14,
      resumo: "Ninguém compra 97 cv ou 8,5 toneladas. Compram obra no prazo, diesel a menos e máquina que não para. Aprenda a traduzir cada característica em dinheiro e a escolher as três que importam para aquele cliente.",
      blocos: [
        { tipo: "p", texto: "Ficha técnica é para você saber; benefício é para o cliente ouvir. Cada característica precisa virar uma frase de resultado no mundo do cliente — de preferência com número. O vendedor que decora dados impressiona; o que traduz dados em dinheiro vende. E a regra é: três traduções por visita, escolhidas para a dor daquele cliente, não vinte." },
        { tipo: "framework", nome: "CVB — Característica, Vantagem, Benefício em reais", origem: "Feature-Advantage-Benefit (FAB), da escola clássica de vendas, com a exigência de fechar em número", passos: [
          "Característica: o fato técnico (motor FPT com gerenciamento eletrônico).",
          "Vantagem: o que isso faz de diferente (menos diesel por hora, na mesma produção).",
          "Benefício em reais: o que sobra no bolso do cliente com os números dele (0,8 L/h × R$ 6,20 × 160 h = R$ 794/mês; R$ 47 mil em 5 anos).",
          "Prova: de onde vem o número (telemetria de cliente, ficha, teste na obra). Sem prova é opinião.",
        ] },
        { tipo: "tabela", titulo: "Tradução característica → resultado (New Holland)", colunas: ["Característica", "O que o cliente ouve"], linhas: [
          ["Retro B95C 4x4 com caçamba 4 em 1", "Uma máquina abre a vala, carrega o caminhão, nivela e agarra tronco: você para de pagar hora de pá-carregadeira de terceiro na obra pequena."],
          ["Motor FPT com gerenciamento eletrônico", "Menos diesel por hora na mesma produção. Numa retro que roda 150 h/mês, 0,5 L/h a menos são cerca de R$ 460/mês só de combustível."],
          ["Escavadeira E145C/E215C com modos de trabalho (ECO/Power)", "Mais toneladas por litro na pedreira; no serviço leve, o modo ECO corta consumo sem perder ciclo. Produtividade medida em caçambas por hora, não em cavalo."],
          ["Pá-carregadeira W130B/W190B com transmissão e balde adequados à densidade", "Ciclo de carregamento mais curto: caminhão sai em 4 minutos, não em 6 — mais viagens por dia com a mesma frota."],
          ["Motoniveladora RG140B/RG170B com controle de lâmina preciso", "Estrada pronta em menos passadas e com acabamento que passa na vistoria: menos hora-máquina por quilômetro."],
          ["Rede de concessionárias e peças na região", "Máquina parada por peça custa mais de R$ 2.500 por dia. Estoque e mecânico em Cachoeiro reduzem dias parados — e isso entra no custo por hora."],
          ["Cabine com ar, visibilidade e ergonomia", "Operador rende mais à tarde e erra menos. Operador bom fica com quem tem máquina boa — e a rotatividade custa treinamento e produção."],
          ["Valor de revenda alto", "Daqui a 5 anos essa máquina vale 50–55% do que você pagou; a de marca fraca, 30–35%. A diferença é a sua entrada na próxima."],
        ] },
        { tipo: "tabela", titulo: "Tradução característica → resultado (Dynapac)", colunas: ["Característica", "O que o cliente ouve"], linhas: [
          ["Rolo CA2500/CA3500 com amplitude dupla", "Compacta em menos passadas: menos diesel, menos hora-máquina, trecho liberado mais cedo."],
          ["Medidor de compactação (DCM/analisador)", "Você prova ao fiscal que atingiu o grau de compactação. Menos ensaio reprovado, menos retrabalho, medição liberada."],
          ["Tambor pé-de-carneiro para solo coesivo", "A argila do sul do ES compacta de verdade — sem 'borrachudo' que estoura o asfalto em 6 meses."],
          ["Tandem CC1200/CC2200", "Acabamento de asfalto sem marca e sem trinca; a prefeitura aceita na primeira medição."],
        ] },
        { tipo: "dialogo", titulo: "Três traduções, um cliente D (direto)", falas: [
          { quem: "cliente", texto: "Me diz rápido por que eu pagaria mais nessa E215C." },
          { quem: "vendedor", texto: "Três coisas, em reais. Um: na sua pedreira ela carrega o caminhão em 4 ciclos de 20 segundos; a que você tem faz em 6 — são 30% mais viagens por dia. Dois: 1,5 litro a menos por hora, R$ 20 mil por ano. Três: daqui a 5 anos vale 150 mil a mais na revenda. Quer que eu prove a primeira com um teste na sua frente de lavra na quinta?" },
          { quem: "nota", texto: "Cliente D não quer a ficha: quer três números e uma decisão. O teste na obra é o próximo passo e a prova ao mesmo tempo." },
        ] },
        { tipo: "p", titulo: "Custo da máquina parada, de novo", texto: "Aprenda a fazer esta conta com o cliente: operador (diária) + máquina alugada para cobrir (diária) + atraso no prazo (multa ou perda de medição) = custo por dia parado. Em obra pública ou pedreira, um dia parado passa fácil de R$ 2.500. Esse número muda a conversa sobre 'a marca X é mais barata' — e é onde a rede de assistência vira característica que vale dinheiro." },
        { tipo: "caso", titulo: "Caso: a pá-carregadeira 'pequena demais'", situacao: "Pedreira em Vargem Alta usava uma pá de 3 m³ do concorrente e reclamava do caminhão esperando na pista. O gerente queria 'uma máquina maior'.", acao: "O vendedor mediu o ciclo: 6 passadas para encher o caminhão de 12 m³. Mostrou que a W190B com balde de 3,3 m³ e ciclo mais curto fazia em 4 passadas — sem subir de classe. Levou a máquina para um dia de teste com cronômetro.", resultado: "Caminhões carregados em 4 minutos em vez de 6,5: a pedreira ganhou 38% de viagens/dia com a mesma frota. Comprou duas.", licao: "Vender resultado exige medir. Cronômetro na obra vale mais que qualquer catálogo." },
        { tipo: "erros", titulo: "Erros de quem 'sabe tudo de máquina'", itens: [
          "Despejar ficha técnica no cliente D — ele quer resultado em uma frase.",
          "Comparar só cavalo e peso. Compare consumo por tonelada, ciclo, disponibilidade e revenda.",
          "Inventar dado. Se não sabe, diga 'vou confirmar e te mando hoje' — e mande.",
          "Falar de tecnologia que o cliente não vai usar. Escolha as 3 que resolvem a dor dele.",
          "Prometer produtividade sem medir a aplicação dele. Teste na obra, com cronômetro.",
        ] },
        { tipo: "checklist", titulo: "Preparação de produto antes da visita (10 minutos)", itens: [
          "Reli a Ficha Técnica do modelo no CRM e o Comparativo com o concorrente que ele tem.",
          "Escolhi 3 traduções CVB para a dor deste cliente, com número.",
          "Tenho a fonte de cada número (telemetria, ficha, cliente autorizado).",
          "Sei o que o concorrente faz melhor — e como respondo sem depreciar.",
          "Levei o que prova: vídeo de cliente, print de revenda, calculadora no celular.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue a Ficha Técnica de um modelo que você vende pouco (ex.: W130B ou CC1200). Escreva 5 traduções CVB com número para o cliente que mais compra esse modelo. Use no próximo contato desse nicho e anote qual delas fez o cliente perguntar mais." },
      ],
      missao: "Antes de cada visita desta semana, anote no CRM (na negociação) três traduções 'característica → resultado em reais' para aquele cliente, com a fonte do número. Use pelo menos uma na conversa e registre qual gerou pergunta ou objeção — isso vira o seu banco de argumentos por nicho.",
      quiz: [
        { pergunta: "Um gerente de pedreira, perfil direto e apressado, pergunta por que pagaria mais na E215C. Qual resposta tem mais chance de avançar?", opcoes: [
          "Ler as principais especificações do catálogo (potência, peso operacional, força de escavação) em comparação direta",
          "Explicar a história da marca, a origem dos componentes e o controle de qualidade da fábrica para justificar o valor",
          "Dar três resultados em reais (ciclo de carregamento, diesel por ano, revenda) e propor um teste cronometrado na lavra",
          "Perguntar qual é o orçamento disponível para a compra e ajustar a configuração até chegar no valor esperado",
        ], correta: 2, explicacao: "Perfil direto quer número e decisão. Três benefícios quantificados e um próximo passo que ao mesmo tempo prova (teste com cronômetro) respeitam o ritmo dele. Catálogo e história da marca são características, não resultados." },
        { pergunta: "'Motor FPT com gerenciamento eletrônico' é uma característica. Qual das opções é o benefício em reais corretamente construído para uma retro que roda 150 h/mês com diesel a R$ 6,20 e consome 0,5 L/h a menos?", opcoes: [
          "Motor mais moderno e confiável, com menos emissão, que atende às normas ambientais exigidas nas licitações",
          "Cerca de R$ 465 por mês a menos em diesel, R$ 28 mil em cinco anos, com a mesma produção",
          "Menos consumo de diesel, o que reduz a pegada de carbono da obra e é bom para a imagem da empreiteira",
          "Economia de aproximadamente R$ 3.000 por mês em combustível, o suficiente para pagar parte da parcela",
        ], correta: 1, explicacao: "0,5 × 6,20 × 150 = R$ 465/mês; × 60 meses = R$ 27.900. A opção de R$ 3.000/mês está inflada (quebra a credibilidade quando o cliente faz a conta); as outras duas param na vantagem, sem chegar ao bolso do cliente." },
        { pergunta: "O cliente pergunta um dado técnico que você não tem certeza. O que fazer?", opcoes: [
          "Dizer que vai confirmar na ficha técnica e mandar ainda hoje, com hora, e cumprir o que combinou",
          "Mudar de assunto para um ponto forte que você domina, porque dúvida na visita passa insegurança ao cliente",
          "Responder com o dado equivalente do concorrente, que você conhece melhor, e prometer o da sua máquina depois",
          "Dar um valor aproximado com confiança, para não parecer despreparado, e corrigir na proposta escrita se for o caso",
        ], correta: 0, explicacao: "Dado inventado é descoberto — e quando é, derruba todos os outros números que você apresentou. Confirmar e cumprir o retorno no mesmo dia constrói exatamente a autoridade que a venda de alto valor exige." },
        { pergunta: "Por que 'rede de concessionárias e peças na região' deve ser apresentada em reais e não como 'tranquilidade'?", opcoes: [
          "Porque a fábrica exige que a rede de concessionárias seja apresentada em toda visita como diferencial padrão",
          "Porque o concorrente não tem assistência nenhuma na região e esse é o ponto mais fácil de vencer na comparação",
          "Porque o cliente não valoriza assistência como conceito, só preço, e por isso tudo precisa virar dinheiro",
          "Porque 'tranquilidade' é subjetivo, enquanto dias parados vezes custo do dia parado entram no custo por hora e se comparam",
        ], correta: 3, explicacao: "Assistência vira argumento quando é traduzida: 6 dias parados a menos por ano × R$ 2.500 = R$ 15 mil/ano. Isso entra na conta de TCO; 'tranquilidade' não entra em conta nenhuma. E depreciar a rede do concorrente é erro, não argumento." },
        { pergunta: "Na pedreira, o gerente quer 'uma pá maior' porque o caminhão espera na pista. Qual é a postura do consultor?", opcoes: [
          "Vender a máquina de classe acima, já que o cliente pediu e sabe da própria operação melhor do que o vendedor",
          "Medir o ciclo atual (passadas por caminhão, tempo) e verificar se a mesma classe com balde adequado resolve, com teste",
          "Explicar que o problema é do operador, não da máquina, e oferecer treinamento antes de qualquer troca",
          "Oferecer duas máquinas da classe atual para dobrar a capacidade de carregamento e eliminar a fila de caminhões",
        ], correta: 1, explicacao: "O cliente descreve o sintoma e propõe uma solução; o consultor diagnostica com medição. Muitas vezes o ciclo, o balde e a densidade do material explicam a fila — e a prova com cronômetro na obra vale mais que subir de classe (e de preço) sem necessidade." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m1a6", titulo: "O seu território: quem compra, quando compra e como pontuar o cliente ideal", minutos: 14,
      resumo: "Construtora, empreiteira, prefeitura, pedreira, cafeicultor, locadora, terraplenador: cada um decide diferente e tem calendário próprio. Aprenda os perfis, a sazonalidade do sul do ES e um sistema de pontuação para saber onde gastar a semana.",
      blocos: [
        { tipo: "p", texto: "Território é um portfólio, não um mapa. Em Cachoeiro, Alegre, Guaçuí, Iúna, Castelo, Marataízes, Itapemirim, Presidente Kennedy, Mimoso do Sul e vizinhas há perto de mil possíveis compradores de máquina — mas não ao mesmo tempo. Quem sabe o calendário de cada perfil chega uma semana antes do concorrente; quem não sabe chega no dia em que a máquina do outro já está na obra." },
        { tipo: "tabela", titulo: "Perfis de comprador no sul do ES", colunas: ["Perfil", "Máquinas típicas", "Quem decide", "O que pesa", "Calendário"], linhas: [
          ["Construtora / empreiteira de obras públicas", "Retro, escavadeira 14–22 t, rolo, motoniveladora", "Dono + engenheiro; financeiro no crédito", "Disponibilidade, prazo de entrega, parcela × medição", "Assinatura de contratos com prefeituras/DER; fim de ano e início de exercício"],
          ["Prefeitura / autarquia", "Retro, motoniveladora, pá, rolo, caminhão", "Secretário de obras, pregoeiro, prefeito", "Especificação, atestados, prazo, assistência local", "Orçamento anual, emendas parlamentares, restrição em ano eleitoral"],
          ["Pedreira / mineração de granito", "Escavadeira 20–25 t, pá 3–4 m³, rompedor", "Gerente de lavra + dono", "Toneladas/hora, consumo por tonelada, dias parados", "Contratos de fornecimento; período seco (abr–set) de maior produção"],
          ["Produtor / cooperativa de café", "Retro, mini/escavadeira 14 t, motoniveladora leve", "Produtor (família), cooperativa", "Estradas internas antes da chuva, terreiro, taxa de crédito rural", "Pós-safra (ago–out) com caixa; Plano Safra (julho); antes das chuvas (out–nov)"],
          ["Locadora de máquinas", "Retro, escavadeira, rolo — o que aluga mais", "Dono, muito sensível a parcela × diária", "Taxa de utilização, revenda, custo/hora, assistência", "Contratos ganhos; aquecimento de obras; troca de frota por horímetro"],
          ["Terraplenador / pequeno empreiteiro", "Retro, escavadeira 14 t, rolo pequeno", "Dono-operador", "Parcela que cabe, usada na troca, confiança pessoal", "Obra fechada, loteamentos, período seco"],
          ["Agro não-café e outros (pecuária, cana no litoral)", "Retro, pá, motoniveladora", "Produtor/gerente", "Barragem, estrada, curral; crédito rural", "Seca (barragem/estrada), Plano Safra"],
        ] },
        { tipo: "framework", nome: "ICP — Pontuação do cliente ideal (0 a 10)", origem: "Ideal Customer Profile, prática de gestão de território B2B, adaptada ao seu mercado", passos: [
          "Aplicação real (0–2): tem serviço contínuo para a máquina? Obra assinada ou produção constante = 2; 'talvez ano que vem' = 0.",
          "Capacidade de pagar (0–2): CNPJ com faturamento, crédito rural, usada para entrada = 2; sem caminho visível = 0.",
          "Acesso ao decisor (0–2): você fala com quem assina = 2; só com o operador = 0.",
          "Momento (0–2): dor ativa agora (máquina parando, contrato começando) = 2; sem gatilho = 0.",
          "Encaixe de produto (0–2): a máquina que ele precisa é uma que você vende bem e entrega no prazo = 2.",
          "Regra: 8–10 = trabalhar esta semana; 5–7 = cadência quinzenal; 0–4 = nutrir a cada 60 dias. A pontuação vai no cadastro do CRM.",
        ] },
        { tipo: "p", titulo: "Sazonalidade que vale dinheiro", texto: "Período seco (abril a setembro): obra anda, pedreira produz, prefeitura pavimenta — é quando a máquina precisa estar na obra, então a venda acontece de fevereiro a maio. Pós-safra do café (agosto a outubro): produtor com caixa e estrada para arrumar antes da chuva de novembro. Plano Safra: julho abre a janela de crédito rural. Prefeitura: empenhos até dezembro; ano eleitoral restringe compras e transferência voluntária em parte do ano. Locadora: troca frota quando o horímetro passa de 6–8 mil horas. Coloque essas datas no calendário de eventos do CRM — o Orientador já sugere visitas por proximidade." },
        { tipo: "dialogo", titulo: "Qualificando em duas mensagens", falas: [
          { quem: "cliente", texto: "Tô pesquisando uma retro. Me manda o preço." },
          { quem: "vendedor", texto: "Claro, Ademir. Pra te mandar a condição certa: é pra serviço contínuo ou pra uma obra específica? E você tem alguma máquina que entraria na troca?" },
          { quem: "cliente", texto: "Serviço contínuo, ganhei um contrato de rede em Itapemirim de 18 meses. Tenho uma retro velha de 9 mil horas." },
          { quem: "nota", texto: "Aplicação 2, capacidade 2 (contrato + usada), momento 2 (contrato começando). Faltam decisor e encaixe. ICP provável 8+: prioridade da semana — visita amanhã, não 'te mando a proposta'." },
        ] },
        { tipo: "caso", titulo: "Caso: a semana gasta com o cliente errado", situacao: "O vendedor passou três dias com um produtor que 'ia comprar uma escavadeira no ano que vem, talvez'. Enquanto isso, uma empreiteira de Castelo assinou contrato com o DER e comprou duas escavadeiras do concorrente na mesma semana.", acao: "Depois disso, passou a pontuar todo contato (ICP) no cadastro e a abrir a semana pela lista de 8+. A empreiteira de Castelo entrou na cadência quinzenal de 'quem assina contrato público'.", resultado: "Quatro meses depois, vendeu a terceira escavadeira da mesma empreiteira — a primeira com New Holland — porque estava na lista quando o contrato seguinte saiu.", licao: "Sem pontuação, o vendedor atende quem responde, não quem compra. O ICP devolve a semana para quem tem aplicação, dinheiro e momento." },
        { tipo: "lista", titulo: "Onde estão os sinais de compra no seu território", itens: [
          "Diário Oficial e portais de licitação: contratos assinados de pavimentação, drenagem, rede de água — o vencedor vai precisar de máquina em 30 a 60 dias.",
          "Placas de obra e canteiros novos nas rodovias (ES-482, BR-101, ES-181): foto, endereço, contato no CRM.",
          "Cooperativas e sindicatos rurais: reuniões pós-safra, dia de campo, feiras regionais.",
          "Mecânicos e locadores de máquina: sabem antes de todo mundo quem está com máquina quebrando.",
          "Anúncios de máquina usada à venda na região: quem vende a antiga está comprando a nova — ligue.",
          "Clientes atuais: 'quem mais está com obra nova por aí?' (módulo 9).",
        ] },
        { tipo: "erros", titulo: "Erros de território", itens: [
          "Tratar todo contato igual. Sem ICP você gasta a semana com quem responde rápido, não com quem compra.",
          "Ignorar o calendário. Chegar na prefeitura em novembro para vender no exercício seguinte é tarde demais para a especificação.",
          "Não cadastrar cidade e perfil no CRM: sem isso não há roteiro, nem abordagem por cidade, nem mapa.",
          "Visitar sempre os mesmos 20 clientes 'amigos'. Conforto não é prospecção.",
        ] },
        { tipo: "checklist", titulo: "Cadastro mínimo de um cliente no CRM", itens: [
          "Nome e telefone corretos (o pipeline do ZEUS liga o WhatsApp a esse cadastro).",
          "Cidade (roteiro, mapa e mensagem por cidade dependem disso).",
          "Perfil (empreiteiro, prefeitura, pedreira, café, locadora…) e frota atual com horímetro aproximado.",
          "Pontuação ICP e o gatilho do momento (contrato, máquina parando, safra).",
          "Próxima ação com data.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pontue os seus 30 clientes mais recentes pelo ICP. Separe os 8+ e monte a rota da semana que vem no CRM só com eles. Para os 0–4, escreva a data do próximo toque (60 dias) e o gatilho que você vai esperar." },
      ],
      missao: "Pontue pelo ICP (0–10) todas as negociações abertas e os 20 clientes sem negociação com quem você falou nos últimos 30 dias. Registre a pontuação e o gatilho nas observações do cadastro. Monte a agenda da semana que vem começando pelos 8+, e coloque no calendário do CRM as três datas de sazonalidade que mais afetam o seu território.",
      quiz: [
        { pergunta: "Você tem uma tarde livre e dois contatos: um produtor que 'talvez compre no ano que vem' (ICP 3) e uma empreiteira que acabou de assinar contrato de drenagem de 14 meses e tem uma usada de 8 mil horas (ICP 9). O que fazer?", opcoes: [
          "Visitar a empreiteira hoje e colocar o produtor em cadência de 60 dias com o gatilho anotado no CRM",
          "Mandar proposta por WhatsApp para os dois e visitar quem responder primeiro, para não decidir no escuro",
          "Dividir a tarde entre os dois, porque o produtor pode virar cliente de longo prazo e a empreiteira é venda pontual",
          "Visitar o produtor, porque relacionamento rural se constrói cedo e a empreiteira com contrato assinado vai comprar de alguém",
        ], correta: 0, explicacao: "Aplicação, dinheiro (contrato + usada) e momento estão na empreiteira agora; em 30 dias a máquina do concorrente pode estar na obra. O produtor não é descartado: entra na cadência longa com o gatilho (safra, crédito) registrado." },
        { pergunta: "Qual é a melhor época para estar na secretaria de obras de uma prefeitura que deve comprar uma motoniveladora no próximo exercício?", opcoes: [
          "Em dezembro, quando o orçamento é aprovado e a secretaria sabe quanto vai ter para investir em frota",
          "Na semana do pregão, com a melhor proposta de preço, porque é o único momento em que a compra realmente acontece",
          "Meses antes do edital, quando a especificação técnica é escrita e os atestados de capacidade são reunidos",
          "Logo após a posse do prefeito, para apresentar o portfólio antes que outro fornecedor ocupe o espaço",
        ], correta: 2, explicacao: "A compra pública se decide na especificação: ficha 'aberta' ou copiada do concorrente. Estar na secretaria antes, com atestados de outras prefeituras e a máquina apresentada, é o que faz o pregão ser disputável. Depois do edital só resta preço." },
        { pergunta: "Um produtor de café de Iúna acaba de vender a safra e comenta que as estradas internas estão ruins. Que combinação de fatores torna este o momento de propor uma retro?", opcoes: [
          "O preço do diesel estar baixo neste mês, o que melhora a conta de custo por hora da máquina própria",
          "A fábrica estar com estoque alto de retros e condições de fim de ano, o que permite entrega imediata",
          "A vizinhança ter comprado máquina do concorrente, o que cria pressão social para o produtor se equipar",
          "Caixa da safra, dor ativa (estrada) e chuva chegando em novembro, mais a janela do crédito rural aberta",
        ], correta: 3, explicacao: "Sazonalidade é a soma de dinheiro (pós-safra), dor (estrada antes da chuva) e crédito (Plano Safra). Os três juntos formam o gatilho de momento do ICP. Preço do diesel e estoque da fábrica são argumentos, não gatilhos." },
        { pergunta: "Qual sinal de compra indica que um cliente está prestes a comprar máquina nova, mesmo sem ter falado com você?", opcoes: [
          "Ele curtiu uma publicação da marca nas redes sociais e comentou perguntando sobre modelos",
          "Ele anunciou a máquina antiga à venda em um grupo da região, com fotos e preço",
          "Ele pediu um catálogo há seis meses e não voltou a entrar em contato desde então",
          "Ele mudou o horário de funcionamento da empresa para atender a uma obra nova",
        ], correta: 1, explicacao: "Quem vende a antiga já decidiu comprar a nova — e provavelmente já está conversando com alguém. Anúncio de usada é o sinal mais forte e mais barato de captar no território; ligue no mesmo dia." },
        { pergunta: "Por que cidade e perfil são campos obrigatórios no cadastro do cliente?", opcoes: [
          "Porque roteiro, mapa, abordagem por cidade e sazonalidade do CRM dependem deles; sem isso o cliente some do planejamento",
          "Porque o envio de mensagens em lote por cidade exige o endereço validado, senão o WhatsApp bloqueia a campanha",
          "Porque a emissão da nota fiscal e do contrato de financiamento exige o município correto do comprador",
          "Porque a fábrica pede relatórios de vendas por cidade e perfil para definir as cotas de cada concessionária",
        ], correta: 0, explicacao: "O CRM monta rotas, mapas, mensagens por cidade e sugestões de visita a partir da cidade e do perfil. Cadastro sem esses campos é um cliente invisível para o seu próprio sistema de prospecção." },
      ],
    },
  ],
  prova: [
    { pergunta: "Um cliente pergunta o preço da retro por WhatsApp. Você responde com duas perguntas (aplicação e horas por mês) e propõe uma visita. Ele insiste: 'só me diz o valor'. Qual é a melhor conduta?", opcoes: [
      "Dizer que a política da empresa não permite passar preço por mensagem sem uma visita técnica prévia",
      "Manter a recusa com educação até ele responder às duas perguntas, porque ceder ensina que insistir funciona",
      "Dar uma faixa de valor com a condição ('entre X e Y conforme entrada e prazo') e manter a visita como próximo passo",
      "Mandar a tabela completa com todas as configurações e encerrar o assunto, deixando ele escolher a que serve",
    ], correta: 2, explicacao: "Recusar duas vezes vira arrogância; mandar a tabela vira commodity. A faixa com condição respeita a pergunta, mostra que o preço depende de variáveis que ele controla (entrada, prazo, usada) e mantém a visita como próximo passo." },
    { pergunta: "Você fecha 1 em cada 5 propostas e faz 1 proposta a cada 3 visitas. A meta é 2 máquinas por mês. Quantas visitas por semana (4 semanas) isso exige?", opcoes: [
      "Cerca de 15 visitas por semana",
      "Cerca de 2 visitas por semana",
      "Cerca de 4 visitas por semana",
      "Cerca de 8 visitas por semana",
    ], correta: 3, explicacao: "2 × 5 = 10 propostas; 10 × 3 = 30 visitas por mês; 30 ÷ 4 ≈ 7,5 visitas por semana. A meta reversa transforma 'vender 2' em um número de agenda." },
    { pergunta: "Cobertura de pipeline de 6x no dia 1 do mês. O que provavelmente está acontecendo?", opcoes: [
      "Você está muito bem coberto e pode reduzir a prospecção este mês para se concentrar em fechar o que já está aberto",
      "Há negociações mortas inflando o funil; é preciso limpar (perdida com motivo) para a cobertura ser real",
      "A meta foi definida baixa demais para o tamanho da carteira e deve ser revista com o gerente",
      "Os clientes estão demorando mais para decidir por causa da economia, e o funil acumula sem converter",
    ], correta: 1, explicacao: "Cobertura acima de 5x quase sempre significa negociação sem próxima ação há semanas contando como viva. Cobertura falsa esconde o problema até a semana 4. Limpar com motivo registrado é higiene, não pessimismo." },
    { pergunta: "Máquina de R$ 500 mil, revenda de R$ 275 mil em 9.000 h, consumo 10 L/h a R$ 6,00, manutenção estimada em R$ 20/h. Qual é o custo por hora sem operador e sem capital?", opcoes: [
      "R$ 105/h",
      "R$ 80/h",
      "R$ 125/h",
      "R$ 60/h",
    ], correta: 0, explicacao: "Depreciação (500.000 − 275.000) ÷ 9.000 = R$ 25/h; diesel 10 × 6 = R$ 60/h; manutenção R$ 20/h. Total R$ 105/h. Fazer essa conta de cabeça na obra é o que separa o consultor do tirador de pedido." },
    { pergunta: "Na conta de TCO, o cliente diz que a máquina dele 'nunca para'. Como tratar o item 'dias parados' sem parecer que está forçando a conta?", opcoes: [
      "Substituir por um valor simbólico de um dia por mês, explicando que é a média mínima de qualquer máquina em operação",
      "Retirar o item da conta para não gerar atrito, porque o cliente conhece a própria máquina melhor do que você",
      "Perguntar quantos dias parou no último ano, usar o número dele e, se for zero, dizer que a conta fica conservadora",
      "Insistir que toda máquina para e usar uma média de mercado por idade, porque o cliente tende a subestimar",
    ], correta: 2, explicacao: "A conta é do cliente, com os números dele. Perguntar 'no último ano' quase sempre revela paradas que ele esqueceu; se não revelar, a conta segue conservadora e a sua credibilidade sobe. Impor média de mercado é o que faz a conta parecer forçada." },
    { pergunta: "Cliente com CNPJ, faturamento regular, contrato de obra assinado e uma usada de valor. Que combinação de caminho de pagamento tende a dar a menor parcela e a melhor chance de aprovação?", opcoes: [
      "Pagamento à vista com desconto, porque elimina juros e usa o valor da usada vendida por fora como parte do dinheiro",
      "CDC sem entrada, pela rapidez de aprovação, mantendo a usada na frota como reserva para as paradas",
      "Consórcio sem lance, pela ausência de juros, aproveitando que o contrato de obra dá tempo até a contemplação",
      "FINAME (ou Banco CNH) com a usada como entrada e o contrato apresentado como justificativa de receita",
    ], correta: 3, explicacao: "Prazo longo e taxa referenciada do FINAME, entrada reduzindo a parcela em torno de um terço e contrato justificando a compra: é a combinação que aprova e cabe no caixa. Consórcio não serve para obra que começa agora." },
    { pergunta: "Duas propostas de banco: taxa nominal 1,2% com seguro e tarifas embutidos, e 1,4% sem custos adicionais. O que você faz?", opcoes: [
      "Recomenda a de 1,2%, porque a taxa nominal menor prevalece ao longo de 60 meses mesmo com seguro embutido",
      "Compara o custo efetivo total (CET) e a parcela final das duas e orienta pelo CET, não pela taxa nominal",
      "Recomenda a de 1,4%, porque a ausência de custos adicionais torna a proposta mais transparente e previsível",
      "Deixa o cliente escolher sozinho com as duas propostas na mão, para não se comprometer com a decisão financeira",
    ], correta: 1, explicacao: "Taxa nominal não é custo; CET é. Orientar pelo CET protege o cliente de uma parcela maior disfarçada e constrói a confiança que traz a segunda compra." },
    { pergunta: "Você quer entrar numa prefeitura que sempre comprou do concorrente. O que fazer nos próximos 90 dias?", opcoes: [
      "Apresentar a máquina à secretaria, entregar atestados de outras prefeituras e trabalhar para a especificação ser aberta",
      "Procurar o prefeito diretamente e pedir a compra, porque na prefeitura pequena a decisão política vem antes da técnica",
      "Oferecer uma máquina em demonstração gratuita por um mês na frota do município, para o operador se acostumar",
      "Esperar o próximo edital e dar o menor preço, porque no pregão o histórico com o concorrente não conta",
    ], correta: 0, explicacao: "A venda pública se ganha na especificação e nos atestados, meses antes do pregão. Menor preço em ficha fechada não adianta; atalhos políticos e 'demonstração grátis' sem processo são risco, não estratégia." },
    { pergunta: "'Cabine com ar-condicionado e boa visibilidade' precisa virar qual tipo de argumento para um dono de empreiteira?", opcoes: [
      "Item obrigatório pela legislação trabalhista, com risco de multa e embargo para máquinas sem climatização",
      "Conforto do operador como questão de bem-estar, que o dono valoriza por cuidar bem da equipe",
      "Produtividade e retenção: operador rende mais à tarde, erra menos e fica na empresa; rotatividade custa produção",
      "Diferencial de design da marca, que valoriza a máquina na revenda e transmite modernidade ao cliente da obra",
    ], correta: 2, explicacao: "O dono compra resultado. Conforto vira argumento quando é traduzido em produção à tarde, menos acidentes e menos rotatividade — custos reais que ele reconhece." },
    { pergunta: "Um contato responde rápido, é simpático e pede catálogo, mas não tem obra, não tem usada e 'quer ver o mercado'. Pelo ICP, o que fazer?", opcoes: [
      "Excluir do CRM para não gastar tempo com quem 'quer ver o mercado' e não tem nenhum sinal de compra",
      "Oferecer um desconto por tempo limitado para transformar a curiosidade em decisão antes que ele esfrie",
      "Visitar esta semana, porque contato engajado e simpático é oportunidade e a visita pode revelar uma obra",
      "Pontuar baixo, mandar o material, registrar o gatilho a esperar e colocar em cadência de 60 dias",
    ], correta: 3, explicacao: "Simpatia e resposta rápida não são aplicação, dinheiro nem momento. O ICP protege a sua semana: nutrir com cadência longa e voltar quando o gatilho aparecer (obra, safra, crédito). Excluir joga fora uma venda futura." },
    { pergunta: "Qual é o sinal de compra mais forte entre os abaixo?", opcoes: [
      "O cliente seguiu a página da concessionária e reagiu às publicações de máquinas novas",
      "O cliente anunciou a máquina antiga à venda em um grupo da região, com preço",
      "O cliente pediu um adesivo da marca e uma camiseta para o operador da frota",
      "O cliente elogiou a máquina nova de um vizinho durante a reunião da associação",
    ], correta: 1, explicacao: "Vender a antiga significa que a decisão de comprar a nova já foi tomada. É o momento de ligar no mesmo dia, avaliar a usada como entrada e entrar antes do concorrente." },
    { pergunta: "Por que o vendedor deve comparar consumo por tonelada (ou por caminhão carregado) em vez de potência do motor ao falar com uma pedreira?", opcoes: [
      "Porque a pedreira vive de toneladas por hora e diesel por tonelada, o que aparece na planilha dela; potência não paga conta",
      "Porque o concorrente sempre tem mais potência nominal e a comparação por motor coloca a New Holland em desvantagem",
      "Porque consumo por tonelada é mais fácil de medir na pedreira do que potência, que exige dinamômetro",
      "Porque potência de motor é um dado que a fábrica não autoriza comparar em material comercial",
    ], correta: 0, explicacao: "O critério de decisão do cliente é a métrica dele. Toneladas por hora e diesel por tonelada são o que a pedreira mede; potência é característica sem tradução. Falar na métrica do cliente é o primeiro ato do consultor." },
    { pergunta: "Em agosto você fechou o recorde do ano e não abriu negociações novas. Qual é a ação correta em setembro?", opcoes: [
      "Concentrar-se em pós-venda dos clientes de agosto, porque cinco entregas seguidas exigem presença e geram indicação",
      "Reduzir o ritmo, porque a meta anual já está encaminhada e o desgaste do mês recorde pede recuperação",
      "Voltar imediatamente à meta semanal de contatos e visitas, aceitando que o vale de outubro é consequência de agosto",
      "Pedir para a gerência redistribuir a meta de setembro, porque o funil vazio não se recupera em quatro semanas",
    ], correta: 2, explicacao: "O funil de outubro se constrói em setembro. Pós-venda dos novos clientes é obrigatório, mas não substitui a entrada do funil; a atividade de prospecção tem meta fixa em todas as semanas." },
    { pergunta: "O que caracteriza uma proposta 'viva' no funil, para efeito de cobertura?", opcoes: [
      "Foi feita para um cliente antigo, que já comprou antes e tem histórico de decisão dentro do prazo",
      "Foi enviada nos últimos 30 dias e ainda está dentro da validade escrita na proposta",
      "O cliente disse que gostou e pediu para o sócio analisar, o que indica que a decisão está em andamento",
      "Tem próxima ação datada e reunião ou retorno combinados com o cliente, registrados no CRM",
    ], correta: 3, explicacao: "Sem próximo passo combinado, a proposta está no limbo — e contar com probabilidade cheia infla a cobertura. Vivo é o que tem data e compromisso do outro lado." },
  ],
};
