import type { Modulo } from "./tipos";

export const M10: Modulo = {
  id: "m10", nivel: 10, titulo: "Mestre: pós-venda, carteira, inteligência e escala", tema: "Mestre", cor: "#ffd23f",
  descricao: "Como transformar clientes em vendedores, vender peças e implementos na carteira, usar inteligência de mercado, montar a rotina de alta performance, crescer a carteira todo ano e sustentar a carreira no longo prazo.",
  objetivos: [
    "Sistematizar o pós-venda como máquina de recompra e indicação.",
    "Aumentar a participação na carteira com peças, serviços, implementos e segunda máquina.",
    "Usar o CRM, notícias, mapa e concorrência para antecipar demanda.",
    "Operar uma rotina semanal de alta performance com métricas.",
    "Escalar por parcerias, presença digital local e clientes-âncora.",
    "Sustentar resiliência, ética e plano de carreira no longo prazo.",
  ],
  leituras: [
    "Fred Reichheld — A Pergunta Definitiva (NPS e indicação).",
    "Jeb Blount — Fanatical Prospecting (rotina) e Sales EQ (resiliência).",
    "Jim Collins — Empresas Feitas para Vencer (disciplina e volante).",
  ],
  aulas: [
    {
      id: "m10a1", titulo: "Pós-venda como máquina de vendas", minutos: 10,
      resumo: "O cliente que comprou é o seu melhor prospecto: compra de novo, compra peça e indica. Sistematize.",
      blocos: [
        { tipo: "tabela", titulo: "Marcos do pós-venda (o CRM avisa cada um)", colunas: ["Marco", "Objetivo", "Ação", "Oportunidade"], linhas: [
          ["Entrega técnica", "Começar bem", "Treinamento, foto com a equipe, contatos da assistência", "Prova social futura"],
          ["30 dias", "Adaptação", "Ligação: horas, dúvidas, primeira manutenção, operador satisfeito?", "Resolver qualquer atrito antes que vire reclamação"],
          ["60 dias", "Satisfação", "Visita rápida; pergunta de satisfação (0–10)", "Peças de desgaste, consumíveis, implemento"],
          ["180 dias", "Manutenção", "Agendar revisão preventiva; conferir horímetro", "Contrato de manutenção, segunda máquina se a obra cresceu"],
          ["365 dias", "Relação", "Aniversário da compra; sondar frota e planos", "Indicação formal, plano de renovação, garantia estendida"],
        ] },
        { tipo: "p", titulo: "Cliente que indica", texto: "Peça indicação no momento de satisfação (entrega bem feita, problema resolvido rápido). Seja específico: “você conhece alguém em Alegre que esteja com máquina cansada?”. Registre a indicação no CRM (campo “indicado por”) e agradeça com algo real (visita, brinde, prioridade na assistência)." },
        { tipo: "script", titulo: "Pedindo indicação", itens: [
          "“Fulano, de 0 a 10, quanto você recomendaria a New Holland e o meu atendimento? [9] O que faltou pro 10? [nada, tá ótimo] Então me ajuda: quem você conhece que está passando o que você passava com a máquina antiga?”",
          "“Posso usar uma foto da sua E215C trabalhando aqui pra mostrar pros vizinhos de Vargem Alta? Com o seu nome ou sem, como preferir.”",
        ] },
        { tipo: "lista", titulo: "Reclamação é oportunidade", itens: [
          "Responda em 1 hora, mesmo que só para dizer “estou cuidando”.",
          "Vá pessoalmente se for grave. Presença resolve 80% da irritação.",
          "Seja o elo com a assistência: acompanhe até a solução, não repasse.",
          "Depois de resolvido: ligue para confirmar e peça a indicação — cliente cujo problema foi resolvido rápido indica mais que cliente sem problema.",
        ] },
        { tipo: "caso", titulo: "Caso: a bomba hidráulica", situacao: "E215C com 400 h apresentou vazamento na bomba. Cliente furioso, ameaçando falar mal na região.", acao: "O vendedor foi à pedreira no mesmo dia, ligou para a assistência na frente do cliente, conseguiu técnico em 24 h e uma máquina reserva por 3 dias.", resultado: "Resolvido em 4 dias. O cliente virou o maior indicador da região: 3 vendas em 2 anos vieram dele.", licao: "Não é o problema que define a relação; é a resposta." },
      ],
      missao: "Abra o Pós-venda do CRM, resolva todos os marcos pendentes esta semana e peça uma indicação para cada cliente satisfeito que contatar.",
      quiz: [
        { pergunta: "Quando pedir indicação?", opcoes: ["No dia da venda", "Num momento de satisfação comprovada (entrega, problema resolvido)", "Nunca, incomoda"], correta: 1, explicacao: "Indicação nasce da satisfação. Peça específico, na hora certa, e registre." },
        { pergunta: "Cliente reclama de vazamento. Primeira ação:", opcoes: ["Repassar para a assistência e esperar", "Responder em 1 h, ir pessoalmente e acompanhar até a solução", "Dizer que é normal"], correta: 1, explicacao: "Resposta rápida e presença transformam reclamação em indicação." },
      ],
    },
    {
      id: "m10a2", titulo: "Participação na carteira: peças, serviços, implementos e a segunda máquina", minutos: 10,
      resumo: "Cliente que comprou uma máquina gasta todo ano em peças, revisão e implementos — com alguém. Como fazer esse alguém ser você.",
      blocos: [
        { tipo: "p", texto: "Uma retro gera, ao longo de 5 anos, gastos com peças, filtros, pneus, revisões e implementos que somam uma fração relevante do preço da máquina. Se o cliente compra isso da loja de peças paralela, você perde receita, perde contato e perde a informação de quando ele vai trocar. Vender na carteira é mais barato que prospectar e mantém você presente." },
        { tipo: "tabela", titulo: "O que vender e quando", colunas: ["Item", "Momento", "Argumento"], linhas: [
          ["Kit de filtros e lubrificantes", "30 e 180 dias; a cada revisão", "Original mantém garantia e consumo; entrega na obra"],
          ["Pneus / material rodante", "Quando o desgaste chega a 30%", "Planejar a troca evita parada; condição de frota"],
          ["Dentes, lâminas, caçambas", "Conforme aplicação (pedreira: mensal)", "Produtividade e proteção da estrutura"],
          ["Implementos (rompedor, garfo, caçamba 4 em 1, braço extensível)", "Quando aparece serviço novo", "Uma máquina, mais serviços, mais faturamento"],
          ["Contrato de manutenção / revisões programadas", "Na entrega ou nos 60 dias", "Custo previsível e disponibilidade; parada zero"],
          ["Garantia estendida", "Antes do fim da garantia de fábrica", "Proteção e revenda"],
          ["Segunda máquina", "Quando horas altas ou obra nova (o CRM mostra)", "Plano de frota; condição de frota"],
          ["Telemetria / monitoramento", "Frotas com 3+ máquinas", "Controle de horas, consumo e localização"],
        ] },
        { tipo: "lista", titulo: "Rotina de carteira", itens: [
          "A cada marco do pós-venda, uma oferta de carteira relevante (não empurrar: perguntar o que está precisando).",
          "Horímetro registrado no CRM a cada contato: ele dispara a revisão e a troca.",
          "Campanhas de peças da concessionária enviadas para quem tem o modelo (o CRM filtra por máquina).",
          "Parceria com o balcão de peças: eles avisam quando o seu cliente compra; você avisa quando o cliente vai precisar.",
        ] },
        { tipo: "script", titulo: "Ofertas de carteira", itens: [
          "“Fulano, sua E215C deve estar chegando nas 500 h. Vou deixar o kit da revisão separado e o técnico agendado pra quinta — assim ela não para na semana da entrega da brita. Pode ser?”",
          "“Vi que vocês pegaram a demolição do galpão. Com o rompedor na E215C você faz sem alugar máquina. Financio junto no contrato atual.”",
        ] },
        { tipo: "caso", titulo: "Caso: o rompedor e a segunda escavadeira", situacao: "Cliente com uma E215C em pedreira pequena. Vendedor visitava só quando o CRM lembrava.", acao: "Passou a registrar horímetro a cada contato e a perguntar de serviços novos. Vendeu rompedor quando surgiu demolição; contrato de manutenção aos 60 dias; e, quando as horas passaram de 2.000/ano, propôs a segunda máquina com condição de frota.", resultado: "Em 2 anos, a receita do cliente triplicou a da primeira venda.", licao: "Carteira bem cuidada rende mais que prospecção — e ainda gera a prospecção (indicação)." },
      ],
      missao: "Liste os 10 clientes com máquinas faturadas há mais de 6 meses. Para cada um, registre o horímetro atual e faça uma oferta de carteira relevante (revisão, implemento, garantia estendida, segunda máquina).",
      quiz: [
        { pergunta: "Por que vender peças e revisões na carteira?", opcoes: ["Só pela receita", "Receita, presença constante e informação de quando o cliente vai trocar", "Não vale a pena"], correta: 1, explicacao: "Carteira é receita barata e inteligência para a próxima máquina." },
        { pergunta: "O que dispara a oferta de revisão e a troca?", opcoes: ["O aniversário", "O horímetro registrado no CRM", "O concorrente"], correta: 1, explicacao: "Horas são o relógio da máquina. Registre a cada contato." },
      ],
    },
    {
      id: "m10a3", titulo: "Inteligência de mercado: antecipar demanda com CRM, notícias, mapa e concorrência", minutos: 10,
      resumo: "O vendedor mestre não espera o cliente ligar: lê os sinais do mercado e chega antes. Como usar o que o CRM já mostra.",
      blocos: [
        { tipo: "tabela", titulo: "Sinais e ação", colunas: ["Sinal", "Onde ver", "Ação na mesma semana"], linhas: [
          ["Preço do café subindo", "Letreiro do Dashboard", "Contatar produtores e cooperativas: crédito da safra, renovação de frota"],
          ["Obra ou licitação anunciada", "Notícias do setor (Dashboard), diário oficial", "Visitar a empreiteira e o secretário; dimensionar frota"],
          ["Campanha de financiamento / taxa", "Concessionária, banco parceiro", "Disparar para negociações mornas com urgência real"],
          ["Cidade sem venda ao lado de cidade com venda", "Mapa do Dashboard", "Prospecção com prova social do vizinho"],
          ["Máquinas com 8+ anos na base", "Cadastro de máquinas do CRM", "Plano de renovação e avaliação da usada"],
          ["Cliente 30+ dias sem contato", "Dashboard › termômetro", "Toque de valor (não cobrança)"],
          ["Concorrente entregando na região", "Observação em campo, redes", "Visitar clientes próximos com comparativo e TCO; aprender o que o concorrente ofereceu"],
          ["Chuva chegando / período seco", "Calendário, notícias", "Prefeituras (patrolamento antes da chuva), compactação (seco)"],
        ] },
        { tipo: "lista", titulo: "Rotina de inteligência (30 minutos, toda segunda)", itens: [
          "Ler o letreiro e as notícias do Dashboard; anotar 2 sinais e 2 ações.",
          "Olhar o mapa: uma cidade-alvo para a semana.",
          "Filtrar clientes 30+ dias sem contato e negociações paradas: uma ação para cada.",
          "Conferir o Orientador de Vendas: quem a IA marcou como quente e qual é a próxima ação sugerida.",
          "Anotar o que a concorrência fez na semana (preço, entrega, promoção) no CRM.",
        ] },
        { tipo: "p", titulo: "Concorrência como fonte", texto: "Cada máquina que o concorrente entrega na região é informação: o cliente precisava, a especificação, a condição que ganhou. Pergunte (ao cliente, ao operador, ao balcão de peças). Registre no CRM. Em 3 meses você conhece o padrão do concorrente melhor que o próprio vendedor dele — e chega antes na próxima." },
        { tipo: "caso", titulo: "Caso: a notícia da BR", situacao: "Notícia no Dashboard: duplicação de trecho da BR-101 no sul do ES com contrato assinado.", acao: "Na mesma semana, o vendedor visitou as 3 empreiteiras locais que costumam ser subcontratadas e as 2 pedreiras que forneceriam brita.", resultado: "Duas escavadeiras e um rolo vendidos nos 4 meses seguintes, antes de a concorrência aparecer.", licao: "Notícia lida na segunda vira visita na terça. Quem espera o cliente ligar chega depois." },
      ],
      missao: "Faça a rotina de inteligência nesta segunda: 2 sinais, 2 ações, 1 cidade-alvo, 1 anotação sobre a concorrência. Registre tudo no CRM e execute até sexta.",
      quiz: [
        { pergunta: "Preço do café sobe. Ação da semana:", opcoes: ["Esperar o produtor ligar", "Contatar produtores e cooperativas sobre renovação e crédito da safra", "Nada, é agricultura"], correta: 1, explicacao: "Sinal de mercado é gatilho de prospecção." },
        { pergunta: "O concorrente entregou uma escavadeira na cidade vizinha. Você:", opcoes: ["Ignora", "Descobre condição e especificação, registra no CRM e visita os clientes próximos com TCO", "Reclama"], correta: 1, explicacao: "Concorrência é informação. Use para chegar antes na próxima." },
      ],
    },
    {
      id: "m10a4", titulo: "Rotina de alta performance e métricas", minutos: 9,
      resumo: "O vendedor mestre não depende de motivação: depende de rotina, números e revisão semanal.",
      blocos: [
        { tipo: "lista", titulo: "Semana modelo", itens: [
          "Segunda: planejamento — funil, próximas ações, rota da semana, 5 prospectos novos cadastrados, rotina de inteligência.",
          "Terça a quinta: campo — 4 a 5 visitas/dia por região, WhatsApp respondido nos intervalos (a IA do CRM adianta).",
          "Sexta: propostas e financiamento — enviar, revisar com clientes, cobrar bancos; fechar o que está maduro.",
          "Sábado de manhã (2 h): pós-venda e indicações — ligações curtas, marcos do CRM, ofertas de carteira.",
          "Diário: 20 minutos de estudo (uma aula desta trilha ou a biblioteca) e treino com IA antes de visita importante.",
        ] },
        { tipo: "tabela", titulo: "Métricas semanais e o que corrigir", colunas: ["Métrica", "Meta de referência", "Se estiver abaixo, revise"], linhas: [
          ["Contatos novos", "5/semana", "Módulo 4 (prospecção)"],
          ["Visitas", "12–15/semana", "Módulo 1 (rotina) e 4 (rota)"],
          ["Propostas enviadas", "4–5/semana", "Módulo 5 (diagnóstico) e 6 (valor)"],
          ["Conversão proposta → fechamento", "≥ 25%", "Módulos 7, 8 e 9"],
          ["Ciclo médio (contato → faturamento)", "≤ 60 dias", "Módulo 9 (financiamento, velocidade)"],
          ["Ticket médio", "Crescente", "Módulo 5 (dimensionamento) e 10 (carteira)"],
          ["Indicações recebidas", "2/mês", "Módulo 10 (pós-venda)"],
          ["Negociações sem próxima ação", "0", "Disciplina de CRM"],
        ] },
        { tipo: "p", titulo: "Revisão semanal", texto: "O Dashboard mostra vendas, visitas e novos negócios; compare toda segunda com a semana anterior. Uma métrica abaixo da meta = uma ação de correção escrita. Não tente corrigir tudo: escolha a métrica mais atrasada e ataque só ela por 2 semanas." },
        { tipo: "destaque", titulo: "Meta anual", texto: "40 máquinas no ano = 3,3 por mês = 1 por semana em média. Uma venda por semana precisa de ~5 propostas ativas e ~15 visitas semanais. Trabalhe a atividade; o número vem." },
        { tipo: "caso", titulo: "Caso: a métrica única", situacao: "Vendedor tinha todas as métricas medianas e tentava melhorar tudo ao mesmo tempo. Nada mudava.", acao: "Escolheu só “propostas enviadas” por 4 semanas: cada visita terminava com autorização para propor, e a proposta saía em 48 h.", resultado: "Propostas dobraram; 6 semanas depois, os fechamentos também.", licao: "Uma métrica por vez. Foco muda número; dispersão não." },
      ],
      missao: "Monte sua semana modelo na agenda do celular com blocos fixos. Na próxima segunda, compare as métricas do Dashboard com a semana anterior e escolha UMA métrica para atacar por 2 semanas.",
      quiz: [
        { pergunta: "Conversão de proposta para fechamento caiu. Onde revisar?", opcoes: ["Prospecção (módulo 4)", "Objeções, fechamento e financiamento (módulos 7–9)", "Ficha técnica"], correta: 1, explicacao: "Propostas existem, fechamento não vem: o gargalo está na fase final do funil." },
        { pergunta: "Várias métricas abaixo da meta. Você:", opcoes: ["Ataca todas", "Escolhe a mais atrasada e trabalha só ela por 2 semanas", "Espera melhorar"], correta: 1, explicacao: "Foco em uma métrica gera mudança real." },
      ],
    },
    {
      id: "m10a5", titulo: "Escala: território, parcerias e marca pessoal", minutos: 9,
      resumo: "Como crescer a carteira todo ano sem trabalhar o dobro: parcerias locais, presença digital e método replicável.",
      blocos: [
        { tipo: "lista", titulo: "Alavancas de escala", itens: [
          "Parcerias: contadores, agrônomos, engenheiros, lojas de peças, cooperativas — quem atende seu cliente antes de você (módulo 4). Combine indicação mútua.",
          "Presença digital local: fotos de entregas e máquinas trabalhando na região (com permissão), nos grupos e redes onde o seu cliente está. Prova social contínua.",
          "Clientes-âncora por cidade: um cliente satisfeito e visível em cada município (o mapa do Dashboard mostra onde falta).",
          "Eventos próprios: dia de campo na pedreira de um cliente, café da manhã técnico para empreiteiros, palestra na cooperativa.",
          "Método replicável: tudo registrado no CRM — se você adoecer uma semana, a IA e os registros seguram o funil.",
          "Estudo contínuo: refazer esta trilha uma vez por ano; as objeções e os concorrentes mudam.",
        ] },
        { tipo: "tabela", titulo: "Marca pessoal do vendedor de máquinas (o que postar)", colunas: ["Conteúdo", "Frequência", "Por quê"], linhas: [
          ["Entrega com a equipe do cliente (com permissão)", "Toda entrega", "Prova social e orgulho do cliente"],
          ["Máquina trabalhando em aplicação real (vídeo 30 s)", "1x/semana", "O cliente se vê na cena"],
          ["Dica técnica curta (compactação, consumo, manutenção)", "1x/semana", "Autoridade"],
          ["Caso com número (“zerou o aluguel”)", "2x/mês", "Retorno em reais"],
          ["Bastidor humano (visita, café, estrada)", "1x/semana", "Calor e proximidade"],
        ] },
        { tipo: "p", titulo: "Cliente-âncora", texto: "Em cada cidade, escolha o cliente mais respeitado que já comprou e trate-o como embaixador: prioridade absoluta na assistência, convite para eventos, foto e depoimento. Quando um prospecto da cidade pergunta “quem mais tem?”, o nome do âncora responde por você." },
        { tipo: "caso", titulo: "Caso: o dia de campo", situacao: "Vendedor organizou um dia de campo na pedreira de um cliente-âncora em Vargem Alta, com demonstração da E215C e do CA2500 e café da manhã.", acao: "Convidou 12 empreiteiros e donos de pedreira da região via parceiros (contador, loja de peças).", resultado: "9 compareceram, 4 viraram negociação, 2 fecharam em 60 dias.", licao: "Um evento com cliente-âncora vale um mês de visitas frias." },
      ],
      missao: "Feche 3 parcerias de indicação mútua nos próximos 30 dias e escolha um cliente-âncora em cada cidade onde já vendeu. Registre os parceiros e âncoras como contatos no CRM.",
      quiz: [
        { pergunta: "Qual parceria gera indicação de compra de máquina com mais frequência?", opcoes: ["Posto de gasolina", "Contador/agrônomo/engenheiro que atende o cliente antes de você", "Concorrente"], correta: 1, explicacao: "Quem já é consultor de confiança do cliente abre porta que anúncio nenhum abre." },
        { pergunta: "O que é um cliente-âncora?", opcoes: ["O maior cliente", "O cliente respeitado de cada cidade que serve de referência e embaixador", "Um cliente que compra âncoras"], correta: 1, explicacao: "Ele responde ao “quem mais tem?” por você." },
      ],
    },
    {
      id: "m10a6", titulo: "Longo prazo: resiliência, ética e plano de carreira", minutos: 9,
      resumo: "Meses ruins acontecem. Como manter a cabeça, proteger a reputação (o ativo que não se compra) e planejar os próximos 5 anos.",
      blocos: [
        { tipo: "p", texto: "Vender máquina de R$ 500 mil no interior é uma carreira de reputação. Um cliente enganado fala para 20; um cliente bem atendido fala para 5. A conta é cruel, e é por isso que ética não é discurso: é estratégia de sobrevivência. E os meses ruins vão vir — safra fraca, eleição, juros altos. O vendedor mestre tem um sistema para atravessá-los sem desespero e sem desconto." },
        { tipo: "lista", titulo: "Resiliência prática", itens: [
          "Meça atividade, não só resultado. Num mês ruim, se as visitas e propostas estão em dia, você fez o seu trabalho — o resultado vem defasado.",
          "Separe o “não” de você. Cada não é sobre a proposta, o momento, o caixa do cliente.",
          "Rotina protege do humor. Nos dias ruins, siga a agenda; não decida nada grande.",
          "Cuide do corpo: sono, comida, exercício. Vendedor cansado dá desconto e esquece follow-up.",
          "Tenha 3 pessoas para conversar: um mentor, um colega e alguém de fora do mercado.",
          "Reveja as vitórias: o CRM tem o histórico. Nos meses ruins, releia as ganhas.",
        ] },
        { tipo: "tabela", titulo: "Ética como vantagem competitiva", colunas: ["Situação", "Caminho curto (errado)", "Caminho longo (certo)"], linhas: [
          ["Cliente vai comprar máquina maior do que precisa", "Vender", "Recomendar a certa: perde R$ 200 mil hoje, ganha 3 indicações"],
          ["Usada avaliada alta fecha a venda", "Avaliar alto", "Avaliar certo e dar a escolha"],
          ["Urgência que não existe fecharia hoje", "Inventar", "Urgência só com fato; ou fechar por valor"],
          ["Concorrente teve problema com um cliente", "Espalhar", "Ficar quieto; deixar o cliente perguntar"],
          ["Erro seu (prazo, condição)", "Culpar a fábrica", "Assumir, avisar antes, compensar"],
        ] },
        { tipo: "lista", titulo: "Plano de carreira em 5 anos", itens: [
          "Ano 1–2: dominar a trilha, bater a meta de atividades, montar rede de parceiros e âncoras em cada cidade.",
          "Ano 2–3: carteira que recompra (peças, segunda máquina), 30% das vendas por indicação, ticket médio subindo.",
          "Ano 3–5: referência regional (o nome que o cliente lembra), possível liderança de equipe ou território maior, método documentado no CRM.",
          "Sempre: reputação impecável, estudo contínuo, números conhecidos de cor.",
        ] },
        { tipo: "destaque", titulo: "Você chegou ao fim da trilha", texto: "Faça a prova final deste módulo. Depois, volte aos módulos onde o quiz foi mais difícil e refaça as missões com clientes novos. O treino com IA (cenários) está disponível em todos os módulos — use antes das visitas importantes. E refaça a trilha inteira daqui a um ano: você vai ler cada aula com outros olhos." },
      ],
      missao: "Escreva seu plano de 5 anos em uma página (metas de atividade, carteira, indicação e reputação). Guarde no celular e releia no primeiro dia de cada mês.",
      quiz: [
        { pergunta: "Mês ruim, mas visitas e propostas em dia. Diagnóstico:", opcoes: ["Você falhou", "Você fez o trabalho; o resultado vem defasado — mantenha a rotina", "Mude tudo"], correta: 1, explicacao: "Atividade é o que você controla. Resultado é consequência com atraso." },
        { pergunta: "Por que ética é estratégia neste mercado?", opcoes: ["Porque é bonito", "Porque a reputação corre no interior e é o ativo que não se compra", "Não é"], correta: 1, explicacao: "Um cliente enganado fala para 20. A conta decide." },
      ],
    },
  ],
  prova: [
    { pergunta: "Cliente cujo problema foi resolvido rápido tende a:", opcoes: ["Nunca mais comprar", "Indicar mais do que cliente sem problema", "Reclamar de novo"], correta: 1, explicacao: "A resposta define a relação." },
    { pergunta: "O que dispara oferta de revisão e troca na carteira?", opcoes: ["A idade do dono", "O horímetro registrado no CRM", "O concorrente"], correta: 1, explicacao: "Horas são o relógio da máquina." },
    { pergunta: "Notícia de obra grande na região. Ação:", opcoes: ["Esperar contato", "Visitar empreiteiras e pedreiras da cadeia na mesma semana", "Postar nas redes"], correta: 1, explicacao: "Sinal de mercado vira visita." },
    { pergunta: "Várias métricas abaixo da meta. Você ataca:", opcoes: ["Todas", "Uma por vez, a mais atrasada", "Nenhuma"], correta: 1, explicacao: "Foco muda número." },
    { pergunta: "Cliente-âncora serve para:", opcoes: ["Comprar mais caro", "Responder ao “quem mais tem?” em cada cidade", "Nada"], correta: 1, explicacao: "Embaixador local." },
    { pergunta: "Recomendar a máquina menor quando é a certa:", opcoes: ["Perde venda", "Constrói a reputação que gera dezenas de vendas", "É proibido"], correta: 1, explicacao: "Ética é vantagem competitiva." },
  ],
};
