import type { Modulo } from "./tipos";

export const M10: Modulo = {
  id: "m10", nivel: 10, titulo: "Gestão de si e alta performance", tema: "Carreira", cor: "#94a3b8",
  descricao: "O último módulo é sobre o vendedor, não sobre o cliente: os indicadores que você controla, o planejamento anual e trimestral com meta reversa, a rotina semanal e a gestão de energia e foco na estrada, a ética e a reputação como patrimônio, o aprendizado contínuo (win/loss, treino com IA, revisão espaçada) e o seu playbook pessoal. Técnica sem disciplina é talento desperdiçado.",
  objetivos: [
    "Acompanhar os indicadores de atividade e de conversão que antecipam o resultado em 60 dias, e agir sobre eles.",
    "Montar o plano anual e o trimestral com meta reversa, por nicho e por rota, e revisá-lo mensalmente.",
    "Desenhar a semana ideal: blocos de prospecção, campo, propostas e revisão, com proteção contra a urgência alheia.",
    "Gerir energia, sono, alimentação e foco na rotina de estrada, e reconhecer os sinais de desgaste antes de virar queda de resultado.",
    "Tratar a reputação como o ativo mais valioso da carreira: promessas, transparência, concorrência e dinheiro.",
    "Manter um sistema de aprendizado contínuo: win/loss, treino com IA, revisão espaçada e leitura, com metas próprias.",
    "Escrever e atualizar o playbook pessoal: o que funciona para você, no seu território, com os seus números.",
  ],
  leituras: [
    "James Clear — Hábitos Atômicos: sistemas em vez de metas, e o ambiente que decide o comportamento.",
    "Cal Newport — Trabalho Focado (Deep Work): blocos de atenção sem interrupção.",
    "Jim Loehr e Tony Schwartz — O Poder do Engajamento Total: gerir energia, não tempo.",
    "Stephen Covey — Os 7 Hábitos das Pessoas Altamente Eficazes: importante × urgente e o afiar o machado.",
    "Anders Ericsson — Peak: a prática deliberada, o que separa quem melhora de quem só repete.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m10a1", titulo: "Os números que você controla: KPIs de atividade e de conversão", minutos: 13,
      resumo: "Máquinas vendidas é resultado, e resultado chega 60 dias atrasado. O que você controla hoje são contatos, visitas, propostas e a qualidade de cada etapa. Sete indicadores, olhados toda semana, dizem o que vai acontecer no fim do próximo mês, e o que fazer para mudar.",
      blocos: [
        { tipo: "p", texto: "O Módulo 1 apresentou a matemática do funil; aqui ela vira painel de controle. Um vendedor de máquinas tem dois tipos de número: os de atividade (quantos contatos novos, visitas, propostas, follow-ups com valor, marcos de pós-venda) e os de conversão (contato → visita, visita → proposta, proposta → fechamento, tempo médio de ciclo, desconto médio). Os primeiros são decisão sua e mudam hoje; os segundos são o efeito do seu método e mudam com estudo e treino. Quem olha só o resultado (máquinas, comissão) descobre o problema quando já é tarde; quem olha os sete indicadores toda semana ajusta antes." },
        { tipo: "tabela", titulo: "Os sete indicadores do vendedor de máquinas", colunas: ["Indicador", "Tipo", "Referência", "O que fazer se cair"], linhas: [
          ["Contatos novos por semana (com sinal)", "Atividade", "15–20", "Bloco de prospecção; radar (Módulo 3)"],
          ["Visitas de diagnóstico por semana", "Atividade", "6–8", "Roteiro por rota; cadência; ligação fria"],
          ["Propostas entregues por semana (com reunião marcada)", "Atividade", "2–3", "Diagnóstico completo; MEDDICC antes da proposta"],
          ["Conversão visita → proposta", "Conversão", "50–65%", "SPIN e gap (Módulo 4)"],
          ["Conversão proposta → fechamento", "Conversão", "25–35%", "Proposta que se defende; objeções; fechamento (5, 7, 8)"],
          ["Desconto médio", "Conversão", "≤ 2%", "Negociação e estrutura (Módulo 6)"],
          ["Marcos de pós-venda no prazo", "Atividade", "100%", "Central de Alertas; defesa da carteira (Módulo 9)"],
        ] },
        { tipo: "framework", nome: "Painel semanal em 10 minutos (sexta à tarde)", origem: "Prática de gestão por indicadores (KPI) em vendas de campo", passos: [
          "Anote os sete números da semana (o CRM tem os dados: Dashboard, funil, Central).",
          "Compare com a referência e com a média das últimas 4 semanas. Marque em vermelho o que caiu duas semanas seguidas.",
          "Um vermelho de atividade: a correção é agenda (bloco de prospecção, rota). Um vermelho de conversão: a correção é método (qual módulo trata dele?).",
          "Escreva uma única ação para a semana seguinte, ligada ao pior indicador. Uma. Quem tenta corrigir cinco não corrige nenhum.",
          "Previsão: com as conversões atuais e a atividade desta semana, quantas máquinas em 60 dias? Se for abaixo da meta, o problema é hoje, não daqui a 60 dias.",
        ] },
        { tipo: "conta", titulo: "Previsão de 60 dias a partir da atividade de hoje", linhas: [
          ["Contatos novos com sinal nesta semana", "18"],
          ["× conversão contato → visita (45%)", "8 visitas"],
          ["× conversão visita → proposta (55%)", "4,4 propostas"],
          ["× conversão proposta → fechamento (30%)", "1,3 máquinas"],
          ["× 4 semanas iguais", "≈ 5 máquinas em 60 dias"],
          ["Se os contatos caírem para 10 por semana", "≈ 3 máquinas em 60 dias"],
        ], conclusao: "A diferença entre 5 e 3 máquinas daqui a dois meses é decidida nesta semana, no número de contatos. O painel mostra o futuro enquanto ele ainda pode ser mudado." },
        { tipo: "dialogo", titulo: "Lendo o painel", falas: [
          { quem: "cliente", texto: "(gerente) Como foi a semana?" },
          { quem: "vendedor", texto: "Fechei uma W130B. Mas o painel está com um vermelho: contatos novos caíram para 9, segunda semana seguida. Eu passei a semana fechando e não prospectei." },
          { quem: "cliente", texto: "E a conversão?" },
          { quem: "vendedor", texto: "Proposta → fechamento em 33%, acima da referência. O método está bem; a atividade caiu. A ação da semana que vem é um bloco de prospecção de duas horas na terça e outro na quinta, antes de qualquer visita." },
          { quem: "nota", texto: "O vendedor não comemora a máquina e ignora o vermelho: lê o painel, distingue atividade de conversão, escreve uma ação. É a diferença entre quem tem mês bom e quem tem ano bom." },
        ] },
        { tipo: "caso", titulo: "Caso: o desconto médio invisível", situacao: "Vendedor com resultado bom em máquinas, mas margem abaixo dos colegas. Nunca tinha olhado o desconto médio: achava que 'dava o normal'.", acao: "Calculou: 4,1% de desconto médio nas 14 vendas do semestre. A referência era 2%. Estudou o Módulo 6, preparou fichas de negociação e passou a trocar variáveis antes de preço.", resultado: "Semestre seguinte: 1,7% de desconto médio nas 15 vendas. Quase R$ 190 mil de margem a mais para a concessionária, e a comissão sobre margem subiu junto.", licao: "O que não se mede parece normal. O desconto médio é o indicador que mais vale dinheiro e o que menos vendedores olham." },
        { tipo: "checklist", titulo: "Sexta, 10 minutos", itens: [
          "Sete números anotados (contatos, visitas, propostas, três conversões, marcos).",
          "Comparados com a referência e a média de 4 semanas.",
          "Vermelhos identificados: atividade (agenda) ou conversão (método)?",
          "Uma ação para a semana seguinte, escrita e na agenda.",
          "Previsão de 60 dias calculada; se abaixo da meta, a ação é prospecção.",
        ] },
        { tipo: "erros", titulo: "Erros com indicadores", itens: [
          "Olhar só máquinas e comissão. Resultado chega atrasado; atividade avisa na hora.",
          "Medir dez coisas. Sete bastam; mais que isso, ninguém olha.",
          "Corrigir cinco vermelhos de uma vez. Uma ação por semana, no pior indicador.",
          "Nunca calcular o desconto médio. É onde a margem vaza sem barulho.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Calcule os seus sete indicadores das últimas 4 semanas com os dados do CRM. Compare com a referência. Qual é o pior? É atividade ou conversão? Escreva a única ação da próxima semana e coloque na agenda com dia e hora." },
      ],
      missao: "Instale o painel de sexta: 10 minutos, sete números, uma ação. Faça por quatro semanas seguidas e registre a evolução. Calcule o seu desconto médio do semestre e compare com a referência de 2%.",
      quiz: [
        { pergunta: "Você fechou uma máquina esta semana, mas os contatos novos caíram para 9 pela segunda semana seguida. Qual é a leitura correta?", opcoes: [
          "Semana boa: a máquina fechada compensa a queda de contatos, e o funil se recompõe naturalmente com as indicações da entrega",
          "Vermelho de atividade: a máquina de hoje veio da prospecção de 60 dias atrás e a queda de contatos é a queda de daqui a dois meses; ação é bloco de prospecção",
          "Problema de método: a queda de contatos indica que a abordagem está desgastada e é hora de estudar objeções e primeira mensagem",
          "Sem problema: contatos novos variam naturalmente conforme a rota da semana, e duas semanas são pouco para uma tendência",
        ], correta: 1, explicacao: "Resultado é atrasado; atividade é adiantada. Duas semanas de queda em contatos antecipam um mês fraco em 60 dias. A correção de atividade é agenda (bloco de prospecção), não método." },
        { pergunta: "Qual é a diferença entre um indicador de atividade e um de conversão, e por que importa?", opcoes: [
          "Atividade se mede por mês e conversão por ano, porque conversão precisa de volume para ser estatisticamente confiável e útil",
          "Não há diferença prática: ambos medem produtividade do vendedor e se corrigem com mais esforço, mais horas de campo e disciplina",
          "Atividade é medida pelo gerente, que controla a agenda; conversão é medida pelo vendedor, que conhece cada negociação em detalhe",
          "Atividade é o que você decide hoje (contatos, visitas) e se corrige com agenda; conversão é efeito do método e se corrige com treino",
        ], correta: 3, explicacao: "Um vermelho em contatos pede bloco de prospecção na terça; um vermelho em proposta → fechamento pede o Módulo 7 ou 8 e treino. Confundir os dois leva a estudar quando falta agenda, ou a correr quando falta método." },
        { pergunta: "Por que o desconto médio é o indicador 'que mais vale dinheiro e que menos vendedores olham'?", opcoes: [
          "Porque a fábrica não divulga a referência de desconto médio, e cada vendedor acha que o seu número é o normal do mercado",
          "Porque não aparece no resultado em máquinas: o vendedor 'vende bem' enquanto a margem vaza 2 pontos por venda, o que em 15 máquinas passa de R$ 100 mil",
          "Porque é difícil de calcular sem um relatório específico, e a maioria dos vendedores não tem acesso aos números de margem",
          "Porque o cliente não percebe o desconto como ganho depois de uma semana, e o vendedor conclui que ele não fez diferença",
        ], correta: 1, explicacao: "No caso da aula, 4,1% contra 2% de referência significou quase R$ 190 mil de margem num semestre, sem nenhuma máquina a menos. O que não se mede parece normal; medido, vira o Módulo 6 aplicado." },
        { pergunta: "O painel de sexta mostra três vermelhos. O que o método manda fazer?", opcoes: [
          "Corrigir os três na semana seguinte com um plano para cada um, porque deixar um vermelho sem ação é aceitar a queda",
          "Ignorar até que um deles caia três semanas seguidas, porque duas semanas ainda podem ser variação normal da rota",
          "Escolher o pior, escrever uma única ação para a semana e colocá-la na agenda; os outros esperam",
          "Pedir ao gerente que redistribua a carteira, porque três indicadores em queda indicam território grande demais",
        ], correta: 2, explicacao: "Quem tenta corrigir três não corrige nenhum. Uma ação, no pior indicador, na agenda com dia e hora. Na sexta seguinte, o painel diz se funcionou e qual é o próximo." },
        { pergunta: "Qual é a utilidade da previsão de 60 dias calculada a partir da atividade da semana?", opcoes: [
          "Mostrar o resultado futuro enquanto ele ainda pode ser mudado: se a previsão está abaixo da meta, o problema é hoje, na atividade",
          "Calcular a comissão prevista para os próximos dois meses e planejar as finanças pessoais do vendedor com antecedência",
          "Definir a meta do trimestre seguinte com base na capacidade real demonstrada pela atividade das últimas semanas",
          "Informar o gerente sobre a expectativa de vendas, para a concessionária planejar estoque e fila de produção",
        ], correta: 0, explicacao: "18 contatos por semana viram ≈ 5 máquinas em 60 dias; 10 contatos viram ≈ 3. A previsão transforma a matemática do funil em decisão de agenda para a semana que vem." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m10a2", titulo: "Plano anual e trimestral: meta reversa por nicho e rota", minutos: 14,
      resumo: "Meta anual sem plano é desejo. O plano divide a meta por trimestre (com a sazonalidade do seu mercado), por nicho (café, pedreira, prefeitura, locação, terraplenagem) e por rota, e transforma tudo em atividades semanais. Revisado todo mês, ele é o mapa que você segue quando a semana desanda.",
      blocos: [
        { tipo: "p", texto: "Um vendedor de máquinas no sul do ES tem um ano com relevo: safra do café (maio a setembro) muda o caixa dos produtores; chuva (novembro a março) freia terraplenagem e pavimentação; orçamento das prefeituras e o Plano Safra têm calendário; o fim do ano da fábrica tem condições. Meta anual dividida por 12 ignora tudo isso e gera meses impossíveis e meses folgados. O plano anual respeita a sazonalidade por nicho, distribui a meta por trimestre, define de onde vem cada máquina (nicho e rota) e desce até a atividade semanal via meta reversa. E é revisado mensalmente, porque a realidade muda." },
        { tipo: "framework", nome: "Plano em 5 camadas (anual → semana)", origem: "Planejamento comercial por território (territory planning) + meta reversa (Módulo 1)", passos: [
          "Meta anual em máquinas e em margem (não só em unidades): ex.: 36 máquinas, desconto médio ≤ 2%.",
          "Por trimestre, com sazonalidade: T1 (chuva) 6; T2 (pré-safra, obras começando) 10; T3 (safra, caixa rural) 12; T4 (fim de ano da fábrica, prefeituras empenhando) 8.",
          "Por nicho, com base no histórico e na carteira: café 8, terraplenagem/construtoras 12, pedreiras 5, prefeituras 5, locadoras 6. Cada nicho tem o seu calendário e a sua lista de contas-alvo.",
          "Por rota: quantas contas-alvo em cada uma das 4 rotas e o dia fixo de cada uma. Rota sem contas-alvo suficientes precisa de prospecção de radar.",
          "Meta reversa semanal por trimestre: com as conversões do painel, quantos contatos, visitas e propostas por semana em cada trimestre. T3 exige mais atividade rural em abril e maio (antes do caixa entrar).",
        ] },
        { tipo: "tabela", titulo: "Calendário do território (exemplo — ajuste ao seu)", colunas: ["Mês", "Café", "Terraplenagem / construtoras", "Prefeituras", "Pedreiras / locadoras", "Ação de planejamento"], linhas: [
          ["Jan–Mar", "Pós-colheita; caixa baixo; planejamento de carreador", "Chuva; obras paradas; planejamento", "Início de orçamento; poucos pregões", "Produção regular", "Diagnósticos e propostas para abril; radar de editais"],
          ["Abr–Jun", "Pré-safra; Plano Safra abre; crédito", "Obras começam; demanda de retro e escavadeira", "Pregões saindo", "Alta com obras", "Visitas rurais intensas; entregas antes da colheita"],
          ["Jul–Set", "Safra; caixa alto; compra", "Pico de obra", "Empenhos", "Pico", "Fechamentos rurais; defesa de carteira; pós-venda"],
          ["Out–Dez", "Pós-safra; planejamento do ano", "Corrida antes da chuva", "Empenho de fim de ano", "Regular", "Condições de fim de ano; propostas para prefeituras; plano do ano seguinte"],
        ] },
        { tipo: "conta", titulo: "Meta reversa do T3 (12 máquinas em 13 semanas)", linhas: [
          ["Máquinas no trimestre", "12"],
          ["÷ conversão proposta → fechamento (30%)", "40 propostas"],
          ["÷ conversão visita → proposta (55%)", "73 visitas"],
          ["÷ conversão contato → visita (45%)", "162 contatos"],
          ["Por semana (13 semanas)", "12–13 contatos · 6 visitas · 3 propostas"],
          ["Mas: as propostas de julho vêm das visitas de maio/junho", "A atividade do T3 tem que começar no T2"],
        ], conclusao: "Um trimestre de 12 máquinas se decide nas 6 visitas semanais de maio e junho. Quem espera julho para 'atacar a safra' vende em outubro, quando o caixa já foi." },
        { tipo: "dialogo", titulo: "Revisão mensal do plano", falas: [
          { quem: "cliente", texto: "(gerente) Abril fechou com 2 máquinas; o plano dizia 3. E agora?" },
          { quem: "vendedor", texto: "O plano do T2 era 10. Estou com 2 em abril e 4 propostas rurais maduras para maio, mais 2 de terraplenagem. Se as conversões se mantiverem, maio e junho fazem 7, e o trimestre fecha em 9. Falta uma." },
          { quem: "cliente", texto: "De onde vem a que falta?" },
          { quem: "vendedor", texto: "Prefeitura: o pregão de Muniz Freire sai em maio e eu trabalhei o termo com o engenheiro. E, para garantir, dobro a prospecção rural em maio antes de o Plano Safra fechar." },
          { quem: "nota", texto: "A revisão mensal não é lamentação nem otimismo: é recontar o trimestre com o funil real e decidir de onde vem o que falta." },
        ] },
        { tipo: "caso", titulo: "Caso: o ano dividido por 12", situacao: "Vendedor com meta de 36 máquinas dividiu por 12: 3 por mês. Em fevereiro (chuva) vendeu 1 e entrou em pânico; em agosto (safra) vendeu 6 e relaxou. Terminou o ano com 29.", acao: "No ano seguinte, planejou por trimestre e nicho: T1 6, T2 10, T3 12, T4 8. Em fevereiro fez diagnósticos e propostas para abril sem ansiedade; em maio dobrou visitas rurais; em agosto colheu.", resultado: "Fechou 38. Mesmo mercado, mesma carteira, mesma pessoa. O que mudou foi o plano respeitar o calendário do território.", licao: "Meta linear em mercado sazonal gera pânico no mês fraco e relaxamento no forte. O plano por trimestre coloca o esforço onde ele rende." },
        { tipo: "checklist", titulo: "Revisão mensal do plano (1ª segunda do mês, 45 min)", itens: [
          "Máquinas do mês × plano; acumulado do trimestre × plano.",
          "Funil real: propostas maduras para os próximos 60 dias, por nicho.",
          "De onde vem o que falta? (nicho, conta, rota) Ação concreta.",
          "Calendário: o que muda no próximo mês (safra, edital, chuva, condição da fábrica)?",
          "Meta reversa da semana ajustada.",
          "Margem: desconto médio do mês × meta de ≤ 2%.",
        ] },
        { tipo: "erros", titulo: "Erros de planejamento", itens: [
          "Meta dividida por 12 em mercado sazonal.",
          "Plano sem nicho: 'vender 36 máquinas' não diz onde prospectar.",
          "Começar a atacar a safra na safra. O caixa entra em julho; a decisão se constrói em maio.",
          "Fazer o plano em janeiro e nunca mais abrir. Revisão mensal ou não é plano.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte o seu plano dos próximos 12 meses nas cinco camadas: meta anual (máquinas e desconto médio), por trimestre com a sazonalidade do seu território, por nicho com contas-alvo nomeadas, por rota, e a meta reversa semanal de cada trimestre. Cadastre no CRM as contas-alvo com o mês previsto." },
      ],
      missao: "Escreva o plano do próximo trimestre com meta por nicho e rota, contas-alvo nomeadas no CRM com mês previsto, e a meta reversa semanal. Marque a revisão mensal na agenda (primeira segunda do mês, 45 minutos).",
      quiz: [
        { pergunta: "Por que dividir a meta anual por 12 é um erro no mercado de máquinas do sul do ES?", opcoes: [
          "Porque 12 não divide 36 de forma prática, e a meta mensal fracionada gera confusão no acompanhamento semanal",
          "Porque os clientes preferem comprar no fim do ano, quando as condições da fábrica são melhores, e a meta linear ignora isso",
          "Porque a fábrica define metas trimestrais para as concessionárias, e a divisão mensal não conversa com o ciclo de faturamento",
          "Porque o mercado é sazonal (safra, chuva, orçamento público): a meta linear gera pânico no mês fraco e relaxamento no forte",
        ], correta: 3, explicacao: "No caso da aula, o mesmo vendedor passou de 29 para 38 máquinas apenas mudando o plano de linear para trimestral com nicho e calendário. A sazonalidade não é obstáculo: é o mapa de onde colocar o esforço." },
        { pergunta: "Um trimestre de safra (julho a setembro) com meta de 12 máquinas rurais se decide em qual período?", opcoes: [
          "Em julho, quando o caixa da colheita começa a entrar e os produtores passam a responder às propostas com decisão",
          "Em setembro, no fim da safra, quando o produtor já sabe quanto colheu e pode comprometer parte do resultado",
          "Em maio e junho, com as visitas de diagnóstico e as propostas que vão fechar quando o caixa entrar",
          "Em janeiro, no planejamento anual, quando as contas-alvo rurais são definidas e a rota da safra é desenhada",
        ], correta: 2, explicacao: "O ciclo de venda leva de 3 a 10 semanas. Propostas que fecham em julho vêm de visitas de maio. Quem 'ataca a safra' em julho vende em outubro, com o caixa já comprometido. A meta reversa do T3 começa no T2." },
        { pergunta: "O que a camada 'por nicho' acrescenta ao plano que 'vender 36 máquinas' não tem?", opcoes: [
          "Uma justificativa estruturada para o gerente, que precisa entender de onde o vendedor espera tirar cada máquina",
          "Onde prospectar: cada nicho tem calendário, lista de contas-alvo, argumento e rota próprios, e a soma dos nichos é a meta com endereço",
          "Uma divisão de comissão por tipo de cliente, porque cada nicho tem margem e ciclo de venda diferentes",
          "Um relatório de mix de vendas para a fábrica, que acompanha a penetração de cada linha por segmento",
        ], correta: 1, explicacao: "Meta sem nicho é número solto. 'Café 8, terraplenagem 12, pedreira 5, prefeitura 5, locação 6' diz quem visitar em cada mês, com que argumento e em que rota, e aparece no CRM como contas-alvo com mês previsto." },
        { pergunta: "Na revisão mensal, abril fechou com 2 máquinas contra 3 planejadas. Qual é a conduta correta?", opcoes: [
          "Recontar o trimestre com o funil real (propostas maduras por nicho), identificar de onde vem o que falta e agir na atividade",
          "Esperar maio para ver se a tendência se mantém, porque um mês abaixo do plano ainda não é sinal de problema",
          "Aumentar a meta de maio para 4 e trabalhar mais horas, porque a máquina que faltou em abril precisa ser recuperada logo",
          "Reduzir a meta do trimestre para o que é 'realista' com o ritmo atual, para não carregar uma cobrança impossível",
        ], correta: 0, explicacao: "A revisão não é lamentação nem otimismo: é recontar com o funil real e decidir. No diálogo da aula, o vendedor localizou as propostas maduras, a máquina que falta (pregão trabalhado) e a ação (dobrar prospecção rural antes do Plano Safra fechar)." },
        { pergunta: "Por que a meta anual deve incluir margem (desconto médio) e não só unidades?", opcoes: [
          "Porque a fábrica exige relatório de margem por vendedor e a meta precisa refletir o que será cobrado no fim do ano",
          "Porque o desconto médio é mais fácil de controlar do que as unidades, que dependem do mercado, da safra e da sazonalidade",
          "Porque a comissão é calculada sobre a margem em todas as concessionárias, e a meta em unidades não reflete o ganho real",
          "Porque unidades sem margem podem ser 'compradas' com desconto; a meta em margem obriga a vender com método, que é o que importa",
        ], correta: 3, explicacao: "Vender 36 máquinas com 5% de desconto médio pode valer menos do que 32 com 1,5%. A meta em margem alinha o vendedor ao negócio e mantém o Módulo 6 vivo o ano inteiro." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m10a3", titulo: "A semana ideal: blocos, rotas e proteção contra a urgência alheia", minutos: 13,
      resumo: "Sem desenho, a semana é preenchida por quem grita mais alto: o cliente que 'precisa hoje', o grupo de WhatsApp, o gerente, a assistência. A semana ideal tem blocos fixos para o que rende (prospecção, campo, propostas, revisão) e regras para o que interrompe.",
      blocos: [
        { tipo: "p", texto: "Cal Newport chama de trabalho focado o que produz valor e exige atenção: para o vendedor, é a ligação de prospecção, a visita de diagnóstico, a proposta bem escrita, a preparação da negociação. O resto (responder o grupo, 'dar uma passada' sem âncora, reencaminhar catálogo) é trabalho raso: parece ocupado e não move o funil. Covey separa o importante do urgente: a prospecção é importante e nunca urgente, por isso é a primeira coisa que some da semana sem desenho. A semana ideal protege o importante com blocos fixos e trata o urgente com regras, não com reflexo." },
        { tipo: "tabela", titulo: "Semana ideal (modelo — adapte às suas rotas)", colunas: ["Dia", "7h30–9h", "9h–12h", "13h–16h", "16h–18h"], linhas: [
          ["Segunda", "Painel e higiene do funil (30 min); Diário Oficial", "Escritório: propostas, simulações, banco", "Ligações de follow-up com valor", "Preparação da rota de terça"],
          ["Terça", "Bloco de 10 ligações frias", "Rota 1: âncoras", "Rota 1: âncoras + 'passei aqui'", "Registro no CRM; visita fria de 30 min"],
          ["Quarta", "Bloco de 10 ligações", "Rota 2: âncoras", "Rota 2: âncoras + marcos de pós-venda", "Registro; preparação de quinta"],
          ["Quinta", "Bloco de ligações (indicações)", "Rota 3: âncoras", "Rota 3: entregas técnicas / demos", "Registro; propostas para sexta"],
          ["Sexta", "Rota 4 (meio período) ou escritório", "Rota 4 / propostas e negociações", "Win/loss; treino com IA; revisão espaçada", "Painel de sexta (10 min); plano da semana seguinte"],
        ] },
        { tipo: "framework", nome: "Regras de proteção do bloco", origem: "Deep Work (Newport) e a matriz importante × urgente (Covey), aplicadas ao vendedor de campo", passos: [
          "Bloco de prospecção é inegociável: 7h30–9h, terça a quinta, celular só para ligar. Nenhuma visita marcada antes das 9h, exceto entrega técnica.",
          "Urgência alheia passa por uma pergunta: 'o que acontece se eu fizer isso amanhã no meu dia da sua rota?'. Máquina parada na safra: hoje. 'Passa aqui rapidinho' sem motivo: agrupa.",
          "WhatsApp em janelas: 9h, 12h, 16h, 18h. Fora delas, silencioso. Cliente com urgência real liga; o resto espera 3 horas sem prejuízo.",
          "Propostas se escrevem na segunda e na sexta, no escritório, com foco. Proposta escrita no estacionamento entre visitas é proposta que não se defende.",
          "Sexta à tarde é sagrada para aprender: win/loss, treino com IA, revisão espaçada, painel. É a hora em que o vendedor mediano 'fecha a semana mais cedo' e o de elite afia o machado.",
        ] },
        { tipo: "dialogo", titulo: "Protegendo o bloco sem perder o cliente", falas: [
          { quem: "cliente", texto: "(8h10, terça, mensagem) Edy, passa aqui hoje de manhã pra gente ver aquela proposta? Coisa rápida." },
          { quem: "vendedor", texto: "(às 9h, no fim do bloco) Bom dia, seu Marcos! Hoje de manhã estou com a agenda fechada. Quinta é o meu dia em Guaçuí: passo aí às 9h com a simulação nova de carência, que muda a proposta a seu favor. Se for algo que não pode esperar quinta, me liga que eu ajusto." },
          { quem: "nota", texto: "Respondeu na janela, ofereceu dia e hora com valor novo, e deixou a porta da urgência real aberta (ligação). Nove em dez 'coisa rápida' cabem na quinta." },
          { quem: "cliente", texto: "Quinta tá ótimo. Era só pra ver a parcela mesmo." },
        ] },
        { tipo: "caso", titulo: "Caso: a semana que 'não tinha tempo para prospectar'", situacao: "Vendedor reclamava de não ter tempo para prospecção. O gerente pediu um registro de uma semana, hora a hora.", acao: "Resultado: 11 horas de deslocamento sem rota (idas e voltas à mesma cidade), 9 horas de WhatsApp fragmentado, 6 'passa aqui rapidinho' sem âncora, zero horas de prospecção. A semana seguinte foi redesenhada com blocos e rotas.", resultado: "Mesmas 50 horas: 6 horas de prospecção (30 ligações, 8 visitas marcadas), 4 rotas com 22 visitas, propostas escritas no escritório. Dois meses depois, o funil tinha dobrado.", licao: "Ninguém 'não tem tempo'. Tem semana sem desenho. O registro hora a hora é o espelho que ninguém quer olhar e todo mundo precisa." },
        { tipo: "checklist", titulo: "Domingo à noite (15 minutos)", itens: [
          "Blocos de prospecção na agenda (terça a quinta, 7h30–9h) com a lista de ligações preparada.",
          "Rotas com 3 âncoras cada, marcadas com hora e objetivo.",
          "Propostas a escrever na segunda e sexta listadas.",
          "Marcos de pós-venda da semana (Central de Alertas) encaixados nas rotas.",
          "Sexta à tarde reservada: win/loss, treino com IA, revisão espaçada, painel.",
          "Janelas de WhatsApp definidas; notificações silenciadas fora delas.",
        ] },
        { tipo: "erros", titulo: "Erros de semana", itens: [
          "Deixar a agenda em branco 'para ter flexibilidade'. O branco é preenchido por urgência alheia.",
          "Responder cada mensagem na hora. Fragmenta o dia e treina o cliente a esperar resposta imediata para tudo.",
          "Prospectar 'quando sobrar tempo'. Nunca sobra.",
          "Escrever proposta no carro. A proposta que se defende precisa de mesa e foco.",
          "Usar a sexta à tarde para 'fechar mais cedo'. É a hora que separa a carreira do emprego.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Registre a próxima semana hora a hora (o que você realmente fez). No domingo, some: horas de prospecção, de campo com âncora, de deslocamento sem rota, de WhatsApp fragmentado, de proposta com foco, de aprendizado. Redesenhe a semana seguinte com blocos e compare em 30 dias." },
      ],
      missao: "Desenhe a sua semana ideal com blocos fixos (prospecção, rotas, propostas, aprendizado, painel) e janelas de WhatsApp. Execute por quatro semanas e registre, a cada sexta, quantos blocos foram protegidos e quantos foram invadidos, e por quê.",
      quiz: [
        { pergunta: "Por que a prospecção é a primeira atividade a desaparecer de uma semana sem desenho?", opcoes: [
          "Porque é a atividade mais difícil tecnicamente, e o vendedor tende a adiar o que exige mais preparo",
          "Porque é importante e nunca urgente: ninguém cobra hoje, e o urgente (mensagem, 'passa aqui') ocupa o espaço sem resistência",
          "Porque o gerente prioriza o fechamento nas reuniões semanais, e a prospecção fica em segundo plano na cobrança",
          "Porque os clientes não atendem ligação de manhã, e o único horário viável para prospectar coincide com as visitas",
        ], correta: 1, explicacao: "Covey: o importante-não-urgente só sobrevive com bloco protegido. A prospecção de hoje é a venda de daqui a 60 dias, e nada nem ninguém vai cobrá-la hoje. Por isso o bloco de 7h30–9h é inegociável." },
        { pergunta: "Um cliente manda mensagem às 8h10, durante o bloco de prospecção, pedindo para você 'passar hoje de manhã, coisa rápida'. Qual é a conduta com método?", opcoes: [
          "Interromper o bloco e ir, porque cliente em primeiro lugar e uma proposta em andamento vale mais que dez ligações frias",
          "Ignorar a mensagem até o fim do dia, para o cliente aprender que o horário da manhã não é para 'coisa rápida'",
          "Responder na janela das 9h, propor o dia da rota dele com hora e um valor novo, e deixar a ligação aberta para urgência real",
          "Responder na hora explicando que está em bloco de prospecção e que retorna assim que terminar as ligações",
        ], correta: 2, explicacao: "Nove em dez 'coisa rápida' cabem no dia da rota; o um em dez liga. A resposta na janela com dia, hora e valor novo (simulação de carência) mantém o cliente atendido e o bloco intacto. Ir na hora ensina que o bloco não existe." },
        { pergunta: "O registro hora a hora da semana do vendedor que 'não tinha tempo para prospectar' revelou o quê?", opcoes: [
          "Que 11 horas de deslocamento sem rota, 9 de WhatsApp fragmentado e 6 'passa aqui' sem âncora ocupavam o tempo; redesenhada, sobraram 6 horas",
          "Que o CRM tomava tempo demais com registros e relatórios, e a solução foi simplificar o preenchimento e delegar parte ao administrativo",
          "Que ele realmente estava sobrecarregado com a carteira e precisava de um assistente para as tarefas administrativas e o follow-up",
          "Que a carteira era grande demais para uma pessoa cobrir com qualidade, e parte dela precisava ser redistribuída para outro vendedor",
        ], correta: 0, explicacao: "Ninguém 'não tem tempo'; tem semana sem desenho. O espelho hora a hora mostra onde as horas vão, e o redesenho com blocos e rotas devolve a prospecção sem trabalhar mais." },
        { pergunta: "Por que propostas devem ser escritas no escritório em blocos, e não no carro entre visitas?", opcoes: [
          "Porque a política comercial exige revisão do gerente antes do envio, e a proposta precisa estar no sistema da concessionária para valer",
          "Porque o cliente percebe quando a proposta foi feita às pressas e desconta a credibilidade do vendedor na hora de analisar o valor",
          "Porque o notebook e a impressora não funcionam bem no carro, e a proposta sai com formatação ruim e erros que o sócio vai notar",
          "Porque a proposta que se defende sozinha (dor, gap, prova, investimento ao lado da economia) exige foco; às pressas vira tabela",
        ], correta: 3, explicacao: "Trabalho focado (Newport): a proposta é o documento que o sócio lê sem você. Escrita fragmentada, ela perde a estrutura NOSE e vira número solto. Segunda e sexta, mesa, sem WhatsApp." },
        { pergunta: "O que diferencia a sexta à tarde do vendedor de elite da do vendedor mediano?", opcoes: [
          "O de elite faz mais visitas na sexta à tarde, porque é quando os clientes estão no escritório fechando a semana",
          "O de elite usa a sexta à tarde para aprender (win/loss, treino com IA, revisão espaçada, painel), enquanto o mediano 'fecha mais cedo'",
          "O de elite responde todas as mensagens acumuladas da semana na sexta à tarde, para começar a segunda sem pendências",
          "Não há diferença relevante: sexta à tarde é improdutiva para todos, e o de elite compensa com a segunda-feira",
        ], correta: 1, explicacao: "Covey chama de 'afiar o machado'. Duas horas por semana de aprendizado deliberado, ao longo de um ano, são 100 horas de método. É a rotina que faz as conversões subirem e que ninguém cobra." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m10a4", titulo: "Energia, foco e a vida na estrada", minutos: 12,
      resumo: "O vendedor de máquinas roda 1.500 km por mês, almoça em posto, dorme pouco na semana de fechamento e chega à visita das 16h sem a energia que tinha às 8h. Loehr e Schwartz mostraram que o recurso escasso não é tempo: é energia. Gerir energia é técnica de vendas.",
      blocos: [
        { tipo: "p", texto: "A visita das 16h de sexta, depois de 300 km, vale a mesma comissão que a das 8h de terça, mas costuma ser feita por um vendedor pior: cansado, impaciente, com menos escuta e mais pressa de apresentar. Loehr e Schwartz estudaram atletas e executivos e concluíram que alta performance sustentada depende de gerir quatro energias (física, emocional, mental, de propósito) em ciclos de esforço e recuperação. Para o vendedor de campo, isso vira sono, alimentação na estrada, pausas entre visitas, o que se ouve no carro, e o reconhecimento dos sinais de desgaste antes de virarem queda de resultado ou acidente." },
        { tipo: "framework", nome: "Quatro energias na rotina de campo", origem: "Loehr & Schwartz — O Poder do Engajamento Total, adaptado ao vendedor de máquinas", passos: [
          "Física: 7 horas de sono como regra (não como exceção da semana de fechamento); água no carro; almoço de verdade (não salgado de posto) entre 12h e 13h; 10 minutos de caminhada a cada 2 horas de estrada; exame anual.",
          "Emocional: o 'não' é estatística, não julgamento (Módulo 3). Ritual de fechamento do dia: registrar no CRM e encerrar; não levar a negociação perdida para o jantar. Uma pessoa com quem falar da semana sem filtro.",
          "Mental: uma coisa por vez. Na visita, o celular no bolso. No carro, ou silêncio para pensar na próxima visita, ou um livro em áudio, nunca o grupo de WhatsApp em áudio.",
          "Propósito: lembrar o que você vende (a obra no prazo, a safra colhida, a família do cliente com patrimônio) e para quem você trabalha (a sua família, o seu plano). É o que segura a semana ruim.",
          "Ciclos: 90 minutos de foco, 10 de pausa. Não marque 5 visitas seguidas sem intervalo; a quinta é feita por um vendedor pior.",
        ] },
        { tipo: "tabela", titulo: "Sinais de desgaste e resposta", colunas: ["Sinal", "O que costuma indicar", "Resposta"], linhas: [
          ["Irritação com cliente que pergunta preço", "Energia emocional baixa", "Pausa; reler o propósito; reduzir visitas do dia"],
          ["Apresentar antes de perguntar (você sabe que não devia)", "Energia mental baixa; pressa", "Voltar ao roteiro de perguntas; visita mais curta e bem feita"],
          ["Sono ruim 3 noites seguidas", "Ansiedade de meta; cafeína tarde", "Cortar café após 14h; caminhada; painel para trocar ansiedade por ação"],
          ["Dirigir no automático, quase acidente", "Fadiga física", "Parar 20 minutos; não dirigir mais de 2 h seguidas; dormir antes de voltar"],
          ["Vontade de sumir da negociação difícil", "Evitação emocional", "Ligar primeiro para a difícil, de manhã, com a ficha preparada"],
          ["Desconto rápido para 'acabar logo'", "Exaustão; BATNA emocional fraca", "Adiar a negociação para o dia seguinte; preparar a ficha"],
        ] },
        { tipo: "dialogo", titulo: "A visita das 16h", falas: [
          { quem: "nota", texto: "Sexta, 16h, depois de 280 km e quatro visitas. O vendedor chega à quinta visita, um diagnóstico com um empreiteiro novo." },
          { quem: "cliente", texto: "Então, quanto tá a E145C?" },
          { quem: "vendedor", texto: "(cansado) Tá em 890 com a caçamba padrão. Posso te mandar a tabela." },
          { quem: "nota", texto: "Preço sem diagnóstico: exatamente o erro da aula 1 do Módulo 1, cometido por um vendedor que sabe melhor. Não é falta de técnica; é falta de energia." },
          { quem: "nota", texto: "Versão com gestão de energia: o vendedor teria marcado essa visita para a terça às 8h, com um bloco de 10 minutos de pausa antes, e feito as duas perguntas de diagnóstico. A visita das 16h de sexta, se inevitável, seria curta: 'vim só conhecer a obra e marcar uma conversa com calma na terça'." },
        ] },
        { tipo: "caso", titulo: "Caso: o trimestre recorde e o mês zerado", situacao: "Vendedor fez o trimestre recorde: 14 máquinas. Dormiu 5 horas por noite, almoçou no carro, 2.100 km por mês. Em outubro, teve um princípio de burnout: irritado, sem escuta, dois quase-acidentes. Vendeu zero.", acao: "Com o gerente, redesenhou a rotina: sono como regra, rotas com no máximo 4 visitas por dia com pausa, almoço sentado, sexta à tarde sem campo. Reduziu 300 km por mês.", resultado: "No ano seguinte, sem nenhum trimestre recorde, fechou 41 máquinas (contra 36 no ano do recorde e do mês zerado). Sem quase-acidentes.", licao: "Performance é média sustentada, não pico. O trimestre recorde que cobra um mês zerado e a saúde não é recorde; é dívida." },
        { tipo: "checklist", titulo: "Rotina mínima de energia na estrada", itens: [
          "Sono: 7 horas, inclusive na semana de fechamento.",
          "Água no carro; almoço sentado entre 12h e 13h.",
          "Máximo de 4 visitas de diagnóstico por dia; pausa de 10 minutos entre elas.",
          "Não dirigir mais de 2 horas seguidas; 20 minutos de parada.",
          "Celular no bolso durante a visita; grupos silenciados no carro.",
          "Ritual de fim do dia: CRM registrado, dia encerrado.",
          "Uma noite por semana e o domingo sem trabalho.",
        ] },
        { tipo: "erros", titulo: "Erros de energia", itens: [
          "Tratar o sono como variável de ajuste da meta. É a variável que ajusta a sua escuta.",
          "Cinco diagnósticos seguidos. O quinto é feito por um vendedor pior que você.",
          "Café e salgado de posto como almoço. A visita das 15h paga a conta.",
          "Levar a negociação perdida para casa. Registre, encerre, volte amanhã com a ficha.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Por uma semana, anote antes de cada visita a sua energia de 1 a 5 e, depois, se fez diagnóstico antes de apresentar. Cruze os dados no domingo: em quantas visitas com energia 1–2 você apresentou antes de perguntar? Esse número é o custo do cansaço em vendas." },
      ],
      missao: "Adote a rotina mínima de energia por quatro semanas (sono, almoço sentado, máximo 4 diagnósticos por dia, pausas, celular no bolso). Registre no painel de sexta a energia média da semana e compare com a conversão visita → proposta.",
      quiz: [
        { pergunta: "Na visita das 16h de sexta, depois de 280 km, o vendedor experiente responde preço sem diagnóstico. O que isso demonstra?", opcoes: [
          "Que ele não domina de fato a técnica de diagnóstico, porque quem domina executa em qualquer condição de cansaço",
          "Que o cliente era perfil D e queria o preço na hora, e a resposta direta foi a leitura correta do perfil",
          "Que técnica sem energia não se executa: o cansaço reverte o vendedor ao erro mais básico, e gerir energia é técnica de vendas",
          "Que visitas de diagnóstico na sexta à tarde devem ser evitadas, porque o cliente também está cansado e desatento",
        ], correta: 2, explicacao: "O vendedor sabe melhor e não faz porque não tem energia para a escuta. A resposta não é 'mais técnica': é sono, pausa, no máximo 4 diagnósticos por dia e a quinta visita marcada para terça de manhã." },
        { pergunta: "Segundo Loehr e Schwartz, qual é o recurso escasso da alta performance?", opcoes: [
          "Energia (física, emocional, mental, de propósito), gerida em ciclos de esforço e recuperação",
          "Motivação, que deve ser renovada com metas maiores e reconhecimento público dos resultados",
          "Talento, que define o teto de cada vendedor e determina até onde o treino pode levá-lo",
          "Tempo, que é o único recurso que não volta; por isso a gestão de agenda é o centro da performance",
        ], correta: 0, explicacao: "Duas visitas de uma hora no mesmo dia podem ter qualidade totalmente diferente conforme a energia de quem as faz. A agenda organiza o tempo; a rotina de sono, alimentação, pausas e propósito organiza a energia que dá qualidade ao tempo." },
        { pergunta: "O trimestre recorde de 14 máquinas foi seguido de um mês zerado e um princípio de burnout. Qual é a lição?", opcoes: [
          "Que o vendedor deveria ter pedido férias em outubro, logo depois do recorde, para recuperar a energia antes de cair no mês seguinte",
          "Que recordes devem ser evitados, porque o esforço extra sempre cobra um preço no mês seguinte e o resultado anual não compensa",
          "Que a meta trimestral estava alta demais para a carteira, e o recorde foi obtido à custa da saúde e da segurança por causa dela",
          "Que performance é média sustentada, não pico: o ano seguinte, sem recorde e com rotina de energia, rendeu mais máquinas",
        ], correta: 3, explicacao: "41 máquinas com rotina sustentável contra 36 no ano do recorde e do colapso. O pico que cobra saúde e um mês zerado é dívida, não resultado. Sono, pausas e limite de visitas por dia são decisões de carreira." },
        { pergunta: "Você percebe que está oferecendo desconto rápido 'para acabar logo' numa negociação. Qual sinal é esse e o que fazer?", opcoes: [
          "Sinal de que o cliente é difícil demais para a energia disponível; encerrar a negociação com elegância e seguir",
          "Sinal de exaustão e BATNA emocional fraca; adiar a negociação para o dia seguinte e preparar a ficha (Módulo 6)",
          "Sinal de que o preço está alto para o mercado e a resistência é real; pedir autorização ao gerente para uma condição",
          "Sinal normal de fim de mês, quando a pressão da meta aperta; seguir em frente e compensar a margem na próxima",
        ], correta: 1, explicacao: "Desconto para 'acabar logo' é a margem pagando o cansaço. Negociação importante se faz descansado, de manhã, com BATNA, ZOPA e variáveis preparadas. Adiar 24 horas custa nada; ceder 3% custa R$ 27 mil." },
        { pergunta: "Qual prática protege a energia mental durante a visita?", opcoes: [
          "Celular no bolso, uma coisa por vez, caderno e olho no cliente; grupos silenciados no carro antes de chegar",
          "Ouvir o grupo de WhatsApp em áudio no carro para chegar atualizado sobre o mercado e a concorrência",
          "Marcar cinco visitas seguidas para manter o ritmo e aproveitar a energia do começo do dia até o fim",
          "Anotar tudo no celular durante a conversa, para o registro no CRM sair completo e imediato",
        ], correta: 0, explicacao: "Atenção fragmentada antes e durante a visita reduz escuta, e escuta é o que vende (Módulo 4). O carro em silêncio ou com um livro em áudio prepara; o grupo em áudio dispersa; cinco visitas seguidas esgotam." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m10a5", titulo: "Ética e reputação: o único ativo que você leva", minutos: 12,
      resumo: "Carteira é da concessionária; comissão acaba no mês; a reputação vai com você para qualquer marca, qualquer cidade, o resto da carreira. No interior, ela é construída ou destruída em público. Quatro áreas onde ela se decide: promessas, transparência, concorrência e dinheiro.",
      blocos: [
        { tipo: "p", texto: "Num território onde os empreiteiros se encontram na associação, os produtores na cooperativa e os engenheiros no encontro da AMUNES, a informação sobre um vendedor circula mais rápido do que qualquer proposta. 'Ele cumpre o que fala', 'ele te fala a verdade mesmo quando perde a venda', 'ele nunca falou mal de ninguém' são frases que valem mais que qualquer desconto — e que levam anos para construir e uma semana para destruir. A ética aqui não é um capítulo à parte da técnica: cada módulo desta trilha tem uma versão honesta e uma versão barata da mesma ferramenta, e a honesta é a que dura." },
        { tipo: "framework", nome: "Quatro áreas da reputação", origem: "Síntese dos princípios éticos aplicados ao longo da trilha (Cialdini, Voss, Fisher & Ury) e da prática em territórios pequenos", passos: [
          "Promessas: só prometa o que confirmou (prazo, condição, atendimento). Se não sabe, diga que vai confirmar, dê hora e cumpra. Uma promessa furada contamina todas as seguintes.",
          "Transparência: a conta com os números do cliente, inclusive quando não fecha. A avaliação da usada com critério, inclusive quando é menor do que ele espera. O que a máquina não faz bem, dito antes da venda.",
          "Concorrência: nunca depreciar, nunca inventar proposta, nunca repetir boato. Compare com fato; reconheça o que eles fazem bem. O cliente que ouve você respeitar o concorrente confia no resto.",
          "Dinheiro: nada por fora, nada de comissão escondida na avaliação da usada, nada de 'ajuda' ao comprador da construtora, nada de favor ao pregoeiro. Em licitação, o que parece esperteza é crime. A margem honesta é a única que não tem prazo de validade.",
        ] },
        { tipo: "tabela", titulo: "Situações-limite e a decisão correta", colunas: ["Situação", "Tentação", "Decisão que preserva a reputação"], linhas: [
          ["Cliente pede prazo de 20 dias; fábrica diz 35", "'Vinte dá' para fechar", "'Consigo 35 confirmados; se 20 for essencial, olho uma usada revisada para cobrir o começo'"],
          ["Conta do gap não fecha para a máquina nova", "Ajustar premissas", "'Não fecha; usada ou consórcio. Volto quando o gap virar'"],
          ["Comprador da construtora insinua 'ajuda' pessoal", "'É o padrão do mercado'", "Recusar com elegância; oferecer valor visível para ele mostrar à diretoria; registrar"],
          ["Cliente quer que a usada seja avaliada acima do real 'para o banco financiar mais'", "'Todo mundo faz'", "Não. Explicar o risco para ele (parcela maior, fraude) e montar estrutura legítima"],
          ["Concorrente espalha que 'a assistência da New Holland fechou'", "Retaliar com boato", "Responder com fato (técnico, endereço, tempo médio) e nunca com boato"],
          ["Cliente pede para 'esquecer' de mencionar um defeito da usada dele na troca", "Aceitar para fechar", "Laudo honesto; o próximo comprador da usada é também seu cliente"],
        ] },
        { tipo: "dialogo", titulo: "A promessa que não se faz", falas: [
          { quem: "cliente", texto: "Se você garantir 20 dias eu fecho agora. A obra começa dia 25." },
          { quem: "vendedor", texto: "Eu quero muito fechar com você, e é por isso que não vou garantir 20. A fábrica me confirmou 35 por escrito. O que eu posso fazer: te entregar uma B95C revisada do pátio em 5 dias para cobrir os primeiros 30 dias de obra, sem custo de aluguel, e a sua nova chega em 35. Assim a obra começa dia 25 de qualquer jeito." },
          { quem: "nota", texto: "Não prometeu o que não controla; resolveu o problema real (a obra no dia 25) com uma alternativa honesta. O cliente compra a máquina e a confiança." },
          { quem: "cliente", texto: "O outro vendedor garantiu 20." },
          { quem: "vendedor", texto: "Pode ser que ele consiga. Eu só te falo o que eu tenho por escrito. Se ele cumprir, ótimo; se não, a sua obra atrasa e ninguém te devolve os dias. Você decide com quem prefere correr o risco." },
        ] },
        { tipo: "caso", titulo: "Caso: 'ele me falou pra não comprar'", situacao: "Ao longo de dois anos, o vendedor disse a quatro clientes que a máquina nova não fazia sentido para o caso deles (gap não fechava). Perdeu quatro vendas no curto prazo.", acao: "Manteve contato com os quatro, com nutrição e sem pressão. Três voltaram quando o gap fechou (arrendamento de fazenda, contrato novo, crescimento da frota).", resultado: "Os quatro viraram a sua principal fonte de indicação: 11 clientes novos em 3 anos chegaram com a frase 'ele me falou pra não comprar quando não fazia sentido'. Nenhuma campanha de prospecção rendeu tanto.", licao: "A honestidade que custa uma venda hoje é o investimento com maior retorno da carreira. E é impossível de copiar pelo concorrente que não a tem." },
        { tipo: "destaque", titulo: "O teste da associação", texto: "Antes de qualquer decisão em zona cinzenta, pergunte: 'se isso fosse contado na reunião da associação de empreiteiros, com o meu nome, eu ficaria tranquilo?'. Se a resposta for não, a decisão está tomada. No interior, tudo é contado." },
        { tipo: "erros", titulo: "Erros que destroem reputação", itens: [
          "Prometer prazo, condição ou atendimento que não confirmou.",
          "Inflar a conta ou a avaliação para fechar. Descoberto em meses.",
          "Falar mal do concorrente ou repetir boato. Circula em dias.",
          "Qualquer 'ajuda' fora da nota. Além de crime, é o fim do nome na região.",
          "Sumir depois de vender. A reputação de pós-venda é a que gera a segunda compra.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escreva as três frases que você gostaria que os clientes dissessem sobre você na associação daqui a dez anos. Depois liste, para cada uma, uma decisão que você tomou no último mês que reforça e uma que enfraquece. A segunda lista é o seu plano de correção." },
      ],
      missao: "Identifique uma promessa em aberto que você não confirmou (prazo, condição, atendimento) e confirme-a hoje, avisando o cliente do resultado real. Depois, escreva no seu playbook as suas regras pessoais para as quatro áreas (promessas, transparência, concorrência, dinheiro).",
      quiz: [
        { pergunta: "O cliente diz 'se você garantir 20 dias eu fecho agora' e a fábrica confirmou 35 por escrito. Qual é a resposta correta?", opcoes: [
          "Recusar a venda com elegância, porque o prazo não é possível e prometer o que não se cumpre é pior do que perder o negócio",
          "Garantir 20 dias, porque a fábrica costuma antecipar a entrega, a chance de cumprir é alta e o cliente precisa de segurança",
          "Dizer que consegue 35 confirmados e resolver o problema real (a obra no dia 25) com uma alternativa honesta, como uma usada",
          "Garantir 20 dias e, se atrasar, oferecer desconto proporcional como compensação, o que protege o cliente e mantém a venda",
        ], correta: 2, explicacao: "Prometer o que não controla é a forma mais rápida de destruir a reputação. O consultor não promete; resolve. A obra começa no dia 25 com a usada do pátio, e a nova chega em 35. O cliente compra a máquina e a confiança." },
        { pergunta: "Por que 'ele me falou pra não comprar' virou a maior fonte de indicações do vendedor?", opcoes: [
          "Porque ele passou a oferecer uma comissão informal por indicação a esses quatro clientes, que se tornaram parceiros",
          "Porque os quatro clientes se sentiram em dívida por não terem comprado e compensaram indicando conhecidos",
          "Porque os clientes do interior gostam de vendedores que vendem pouco e não pressionam, e indicam por simpatia",
          "Porque a honestidade contra o próprio interesse é a prova mais forte de confiança, e confiança é o que se indica; é impossível de copiar",
        ], correta: 3, explicacao: "Quatro vendas perdidas no curto prazo renderam 11 clientes novos em três anos, com uma frase que nenhuma campanha produz. A reputação de honestidade é ativo de carreira: vai com você para qualquer marca e qualquer cidade." },
        { pergunta: "O comprador da construtora insinua que 'uma ajuda pessoal' facilitaria a aprovação. Qual é a conduta?", opcoes: [
          "Aceitar discretamente, porque é padrão do mercado de construção e recusar significa perder a conta para quem aceita",
          "Aceitar e registrar como despesa comercial de relacionamento, o que a concessionária pode absorver dentro da margem",
          "Recusar com elegância, oferecer ao comprador uma vitória visível e legítima para mostrar à diretoria (treinamento, kit, revisão) e registrar",
          "Denunciar imediatamente ao dono da construtora, porque a insinuação configura tentativa de corrupção e precisa ser exposta",
        ], correta: 2, explicacao: "Qualquer valor fora da nota é o fim do nome na região e, em muitos casos, crime. A recusa elegante mantém a porta aberta; o valor legítimo para o comprador atende à necessidade real dele (mostrar resultado). O registro protege você. A denúncia imediata pode ser necessária em casos graves, mas a primeira resposta é a recusa com alternativa." },
        { pergunta: "Um concorrente espalha que 'a assistência da New Holland fechou'. Qual é a resposta que preserva a reputação?", opcoes: [
          "Espalhar que a assistência do concorrente é pior, com relatos de clientes que ficaram parados esperando peça",
          "Responder com fato verificável (nome do técnico, endereço, tempo médio de atendimento) e nunca com boato sobre o outro",
          "Ignorar o boato, porque responder dá importância à mentira e o cliente sério vai checar por conta própria",
          "Reclamar formalmente à fábrica do concorrente, exigindo que o vendedor seja advertido pela concorrência desleal",
        ], correta: 1, explicacao: "Boato se combate com fato, não com boato. O cliente que vê você responder com nome, endereço e número, sem atacar ninguém, conclui quem é confiável. Retaliar iguala você ao boateiro; ignorar deixa a dúvida no ar." },
        { pergunta: "O que é o 'teste da associação'?", opcoes: [
          "A pergunta, antes de qualquer decisão em zona cinzenta: 'se isso fosse contado na associação, com o meu nome, eu ficaria tranquilo?'",
          "Uma pesquisa de satisfação feita pela associação de empreiteiros com os fornecedores de máquinas da região, publicada todo ano",
          "Um ranking de vendedores publicado pelas cooperativas e sindicatos rurais com base nas indicações e nas reclamações dos associados",
          "Uma reunião mensal dos vendedores da região na associação comercial, para alinhar práticas, condutas de mercado e preços de referência",
        ], correta: 0, explicacao: "No interior, tudo é contado. O teste antecipa a consequência pública da decisão privada e resolve a maioria das zonas cinzentas em cinco segundos. Se a resposta for não, a decisão está tomada." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m10a6", titulo: "Aprendizado contínuo e o seu playbook pessoal", minutos: 14,
      resumo: "Ericsson mostrou que o que separa quem melhora de quem só repete é a prática deliberada: treinar o ponto fraco com feedback, fora da zona de conforto. Para o vendedor: win/loss que aponta o módulo, treino com IA no cenário difícil, revisão espaçada do que esquece, e um playbook pessoal que registra o que funciona com os seus números.",
      blocos: [
        { tipo: "p", texto: "Vinte anos de experiência podem ser vinte anos de aprendizado ou um ano repetido vinte vezes. A diferença, segundo a pesquisa de Anders Ericsson sobre especialistas, é a prática deliberada: identificar o ponto fraco específico, treinar exatamente ele com feedback imediato, um pouco além do confortável, e repetir. Esta Academia foi construída para isso: o win/loss aponta o módulo; o Treino com IA cria o cenário difícil e dá a nota por critério; a Revisão espaçada traz de volta o que você esqueceu antes de esquecer de vez; a Certificação mede o conjunto. E o playbook pessoal transforma tudo em método seu, com os seus números e o seu território." },
        { tipo: "framework", nome: "Ciclo semanal de prática deliberada (sexta, 90 minutos)", origem: "Ericsson (Peak) aplicado às ferramentas da Academia e do CRM", passos: [
          "Diagnóstico (15 min): win/loss da semana e o painel apontam o ponto fraco específico (ex.: 'não isolo a objeção antes de responder'; 'perco acesso ao sócio'). Um ponto, não cinco.",
          "Estudo dirigido (20 min): reler a aula do módulo correspondente, não o módulo inteiro. Anotar uma frase para usar na próxima situação real.",
          "Treino com IA (30 min): três cenários do módulo, dificuldade 2 ou 3, no perfil DISC que você pior atende. Ler a rubrica: onde perdeu ponto? Refazer o pior cenário até tirar 8+.",
          "Revisão espaçada (15 min): a sessão do dia. As perguntas que voltam são o que a memória está perdendo; errar aqui é barato, errar na obra é caro.",
          "Playbook (10 min): registrar o que aprendeu na semana em uma linha, na seção do módulo. Uma frase que funcionou, um número seu, um erro que não vai repetir.",
        ] },
        { tipo: "tabela", titulo: "Estrutura do playbook pessoal (um documento vivo)", colunas: ["Seção", "O que registrar", "Exemplo"], linhas: [
          ["Meus números", "Conversões, ciclo, desconto médio, custo por visita, atualizados por trimestre", "'Visita → proposta: 58%. Proposta → fechamento: 31%. Desconto médio: 1,8%'"],
          ["Meu território", "Nichos, calendário, rotas, comunidades, referências por nicho", "'Café: Plano Safra abre em julho; cooperativa de Iúna: dia de campo em maio'"],
          ["Minhas frases", "Aberturas, reenquadres, rótulos, pedidos de indicação que funcionaram COM VOCÊ", "'Você já paga a máquina nova todo mês em aluguel; só não tem ela na obra'"],
          ["Minhas contas", "TCO, gap, custo da inação por nicho com premissas da região", "'Retro em rede: 3 dias parados = R$ 5.700/mês'"],
          ["Meus erros", "O que não repetir, com a situação", "'Não apresentar antes do resumo. Perdi a Vale Verde por isso em março'"],
          ["Meus casos", "Histórias de cliente em 4 tempos, autorizadas, por situação", "'Roberto, pedreira: comprou a mais barata, 11 dias parado, voltou'"],
          ["Meu plano", "Trimestre atual, metas reversas, contas-alvo", "'T3: 12 máquinas; 6 visitas rurais/semana em maio e junho'"],
        ] },
        { tipo: "dialogo", titulo: "Treino com IA como prática deliberada", falas: [
          { quem: "nota", texto: "Sexta, 15h. O win/loss da semana apontou: duas negociações esfriaram depois de 'vou pensar'. Ponto fraco: não explorar antes de aceitar." },
          { quem: "vendedor", texto: "(no Treino com IA, Módulo 7, dificuldade 3, cliente perfil S) Rodada 1: 'Claro, seu Antônio, é uma decisão grande. Só pra eu te ajudar a pensar: o que ainda não está claro — a parcela, a entrega, ou tem alguém que precisa opinar?'" },
          { quem: "cliente", texto: "(IA, como o cliente) 'É mais a minha esposa. Ela cuida do dinheiro e acha que a gente devia esperar.'" },
          { quem: "vendedor", texto: "Rodada 2: 'Faz sentido; ela precisa ver a conta como você viu. Posso passar aí quinta às 16h e mostrar pra ela a parcela ao lado do que vocês gastam hoje com a máquina velha? Se ela ainda achar cedo, tudo bem, a gente marca pra depois da safra.'" },
          { quem: "nota", texto: "Rubrica: acolhimento 2, valor 1 (não citou o número do gap), condução 2, tom 2, estratégia 2. Nota 9. Melhoria apontada: trazer o número da inação já na segunda fala. Registrado no playbook: 'no vou pensar, citar o custo mensal da inação ao propor a reunião com o ratificador'." },
        ] },
        { tipo: "caso", titulo: "Caso: dois vendedores, cinco anos", situacao: "Dois vendedores entraram na mesma concessionária no mesmo ano, com resultados parecidos no primeiro ano. Um 'aprendia na prática'; o outro reservava a sexta à tarde para win/loss, treino e playbook.", acao: "Cinco anos depois, o primeiro tinha as mesmas conversões do segundo ano e o mesmo desconto médio. O segundo tinha subido a conversão proposta → fechamento de 24% para 39% e reduzido o desconto médio de 3,5% para 1,4%.", resultado: "Com o mesmo número de visitas, o segundo vendia 60% a mais e com margem maior. Virou gerente; o primeiro continuou 'experiente'.", licao: "Experiência é o que acontece com você; aprendizado é o que você faz com ela. Duas horas por semana, cinco anos, e a diferença é uma carreira." },
        { tipo: "checklist", titulo: "O sistema de aprendizado da Academia (o que usar e quando)", itens: [
          "Trilha: uma aula por semana até certificar todos os módulos; reler a aula do ponto fraco quando o win/loss apontar.",
          "Quiz de cada aula: refazer com ordem nova até acertar tudo; a prova do módulo com 70% ou mais.",
          "Revisão espaçada: a sessão do dia, sempre que a Academia mostrar perguntas vencidas (5 minutos).",
          "Treino com IA: três cenários por semana, no módulo do ponto fraco, dificuldade crescente, perfil DISC que você pior atende.",
          "Certificação final: quando todos os módulos estiverem certificados; refazer a cada 12 meses.",
          "Playbook: uma linha por semana, revisado no fim de cada trimestre.",
        ] },
        { tipo: "erros", titulo: "Erros de aprendizado", itens: [
          "'Aprender na prática' sem feedback. A prática sem feedback consolida o erro.",
          "Treinar o que já faz bem. É confortável e inútil; treine o ponto fraco.",
          "Fazer o treino com IA na dificuldade 1 para tirar 10. A nota é diagnóstico, não troféu.",
          "Playbook genérico copiado de livro. O playbook é seu: suas frases, seus números, seu território.",
          "Parar de estudar depois de certificar. A certificação é o começo; a revisão espaçada existe porque a memória esvazia.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Crie hoje o seu playbook com as sete seções (um documento no celular serve). Preencha 'Meus números' com o painel atual, 'Meus erros' com as três últimas perdas e 'Minhas frases' com as cinco que você mais usa e que funcionam. Marque a sexta à tarde na agenda das próximas 12 semanas." },
      ],
      missao: "Execute o ciclo de sexta completo (diagnóstico, estudo dirigido, três cenários no Treino com IA no seu ponto fraco, revisão espaçada, uma linha no playbook) por quatro semanas seguidas. Ao fim, compare as notas do treino da semana 1 com as da semana 4 e registre o que mudou na obra.",
      quiz: [
        { pergunta: "Segundo Ericsson, o que diferencia quem melhora de quem só acumula anos de experiência?", opcoes: [
          "O número de horas trabalhadas ao longo dos anos, porque a repetição consolida o método e reduz os erros",
          "A qualidade dos produtos que vende, porque quem vende máquina boa aprende com clientes satisfeitos e cresce",
          "O talento natural para vendas, que define o ritmo de aprendizado e o teto que cada vendedor pode alcançar",
          "A prática deliberada: treinar o ponto fraco específico com feedback imediato, um pouco além do confortável, e repetir",
        ], correta: 3, explicacao: "Vinte anos podem ser um ano repetido vinte vezes. O caso dos dois vendedores mostra: mesmo talento e mesmas visitas, mas quem treinava o ponto fraco com feedback (win/loss, treino com IA, playbook) vendia 60% a mais em cinco anos." },
        { pergunta: "O win/loss apontou que você não explora antes de responder ao 'vou pensar'. Como deve ser o treino com IA dessa semana?", opcoes: [
          "Módulo 7, dificuldade 1, para consolidar a confiança com notas altas antes de enfrentar cenários mais duros e perfis difíceis",
          "Qualquer módulo, dificuldade 3, para se desafiar ao máximo e descobrir outros pontos fracos além do 'vou pensar' que o win/loss apontou",
          "Módulo 7, dificuldade 2 ou 3, no perfil DISC que você pior atende, três cenários, refazendo o pior até 8 ou mais, e uma linha no playbook",
          "Reler o Módulo 7 inteiro com calma em vez de treinar, porque o erro indica que a teoria não foi absorvida e o treino viria cedo demais",
        ], correta: 2, explicacao: "Prática deliberada é específica (o ponto fraco), com feedback (rubrica), além do confortável (dificuldade 2–3, perfil difícil) e com registro (playbook). Dificuldade 1 para tirar 10 é troféu, não treino; reler tudo sem treinar não muda comportamento." },
        { pergunta: "O que o playbook pessoal tem que um livro de vendas não tem?", opcoes: [
          "Teoria mais atualizada do que a dos livros, porque incorpora as mudanças recentes do mercado e das linhas de crédito",
          "Os seus números, o seu território, as frases que funcionaram com você, as suas contas com premissas da região e os seus erros",
          "A autorização e a revisão da concessionária, o que o torna um documento oficial de treinamento da equipe",
          "Um formato padronizado pela fábrica, que permite comparar o método de cada vendedor com o das outras regiões",
        ], correta: 1, explicacao: "O livro dá o método; o playbook registra a sua execução do método. 'Você já paga a máquina nova em aluguel' funcionou com o seu cliente; '3 dias parados = R$ 5.700/mês' é a conta da sua região. É o documento que faz a experiência virar aprendizado." },
        { pergunta: "Por que a revisão espaçada continua necessária depois de certificar todos os módulos?", opcoes: [
          "Porque a memória esvazia o que não é usado; as perguntas que voltam são exatamente o que você está esquecendo, e errar na revisão é barato",
          "Porque o gerente acompanha o número de revisões feitas por vendedor e usa isso na avaliação de desempenho",
          "Porque a Academia adiciona perguntas novas toda semana, e a revisão é a forma de acompanhar o conteúdo atualizado",
          "Porque a certificação expira formalmente em 12 meses, e a revisão espaçada é o que mantém o certificado válido",
        ], correta: 0, explicacao: "Os intervalos (1, 3, 7, 14, 30 dias) crescem quando você acerta e voltam quando erra, trazendo cada conceito à tona um pouco antes de ele sumir. Cinco minutos por dia mantêm dez módulos vivos. A certificação é o começo do uso, não o fim do estudo." },
        { pergunta: "No caso dos dois vendedores, o que explica a diferença de 60% nas vendas em cinco anos com o mesmo número de visitas?", opcoes: [
          "O segundo tinha uma carteira melhor, com mais pedreiras e construtoras grandes, que compram máquinas maiores",
          "O segundo recebeu mais treinamento formal da fábrica, com cursos técnicos e comerciais ao longo dos cinco anos",
          "O primeiro teve azar com o mercado na região dele, com menos obras e safras mais fracas no período",
          "O segundo subiu a conversão proposta → fechamento de 24% para 39% e reduziu o desconto médio de 3,5% para 1,4% com duas horas semanais",
        ], correta: 3, explicacao: "Mesma concessionária, mesmo ano de entrada, resultados parecidos no início. A diferença foi a sexta à tarde: win/loss, treino, playbook. Conversão e margem são efeito do método, e método se treina." },
      ],
    },
  ],
  prova: [
    { pergunta: "Os contatos novos caíram duas semanas seguidas, mas você fechou uma máquina. Qual é a leitura?", opcoes: [
      "Semana boa; a máquina fechada compensa a queda de contatos e o funil se recompõe sozinho",
      "Vermelho de atividade que antecipa um mês fraco em 60 dias; a ação é bloco de prospecção",
      "Problema de método; estudar objeções e primeira mensagem, porque a abordagem está desgastada",
      "Variação normal da rota; duas semanas ainda não formam uma tendência que exija ação",
    ], correta: 1, explicacao: "Resultado chega atrasado; atividade avisa na hora. A máquina de hoje veio da prospecção de dois meses atrás; a queda de contatos é o mês fraco de daqui a dois meses." },
    { pergunta: "Um vermelho em 'proposta → fechamento' se corrige com:", opcoes: [
      "Estudo e treino do método (proposta, objeções, fechamento), porque conversão é efeito do método",
      "Mais ligações frias por semana, porque o volume maior compensa a conversão menor",
      "Redução da meta do trimestre, porque a conversão atual não sustenta o número planejado",
      "Mais visitas de diagnóstico, porque o problema está na entrada do funil e não na saída",
    ], correta: 0, explicacao: "Atividade se corrige com agenda; conversão se corrige com método. Confundir os dois leva a correr mais quando o que falta é fazer melhor." },
    { pergunta: "Por que a meta anual deve incluir desconto médio?", opcoes: [
      "Porque a fábrica exige relatório de margem por vendedor e a meta precisa refletir isso",
      "Porque é mais fácil de medir e controlar do que unidades, que dependem do mercado",
      "Porque unidades sem margem podem ser 'compradas' com desconto; a meta em margem obriga a vender com método",
      "Porque a comissão é calculada sobre a margem em todas as concessionárias, e a meta precisa acompanhar",
    ], correta: 2, explicacao: "36 máquinas com 5% de desconto podem valer menos que 32 com 1,5%. A meta em margem mantém o Módulo 6 vivo o ano inteiro." },
    { pergunta: "Um trimestre de safra com 12 máquinas rurais se decide:", opcoes: [
      "No planejamento de janeiro, quando as contas-alvo rurais e a rota da safra são definidas",
      "Em julho, quando o caixa da colheita começa a entrar e os produtores decidem",
      "Em setembro, no fim da safra, quando o produtor sabe quanto colheu e pode investir",
      "Em maio e junho, com as visitas e propostas que fecham quando o caixa entrar",
    ], correta: 3, explicacao: "O ciclo leva de 3 a 10 semanas. A atividade do T3 começa no T2. Quem ataca a safra na safra vende depois dela." },
    { pergunta: "Qual é o erro de planejamento mais comum em mercado sazonal?", opcoes: [
      "Meta dividida por 12, que gera pânico no mês fraco e relaxamento no forte",
      "Planejar por nicho, que fragmenta a meta e dificulta o acompanhamento mensal",
      "Revisar o plano mensalmente, que gera ajustes demais e tira a estabilidade da meta",
      "Definir contas-alvo com mês previsto, que engessa a prospecção e ignora as oportunidades",
    ], correta: 0, explicacao: "O mesmo vendedor passou de 29 para 38 máquinas apenas trocando a meta linear por trimestral com nicho e calendário." },
    { pergunta: "Um cliente pede 'passa aqui hoje, coisa rápida' durante o bloco de prospecção. Qual é a conduta?", opcoes: [
      "Interromper o bloco e ir, porque proposta em andamento vale mais que ligações frias e o cliente lembra de quem apareceu",
      "Ignorar a mensagem até o fim do dia, para o cliente aprender o horário do bloco e parar de pedir 'coisa rápida' de manhã",
      "Responder na hora explicando que está ocupado com prospecção e que retorna assim que terminar as ligações do bloco",
      "Responder na janela, propor o dia da rota dele com hora e valor novo, e deixar a ligação aberta para urgência real",
    ], correta: 3, explicacao: "Nove em dez 'coisa rápida' cabem no dia da rota. O bloco protegido é a venda de daqui a 60 dias; a urgência real liga." },
    { pergunta: "Por que a prospecção some da semana sem desenho?", opcoes: [
      "Porque é a atividade mais difícil e o vendedor adia o que exige mais preparo",
      "Porque é importante e nunca urgente: ninguém cobra hoje e o urgente ocupa o espaço",
      "Porque os clientes não atendem de manhã e o horário coincide com as visitas",
      "Porque o gerente prioriza o fechamento na cobrança semanal e a prospecção fica de lado",
    ], correta: 1, explicacao: "Covey: o importante-não-urgente só sobrevive com bloco protegido. Por isso 7h30–9h, terça a quinta, é inegociável." },
    { pergunta: "O vendedor experiente responde preço sem diagnóstico às 16h de sexta, após 280 km. O que isso mostra?", opcoes: [
      "Falta de técnica de diagnóstico, porque quem domina executa em qualquer condição",
      "Que o cliente era perfil D e queria o preço, e a resposta direta foi a leitura certa",
      "Que técnica sem energia não se executa; gerir energia (sono, pausas, limite de visitas) é técnica de vendas",
      "Que visitas de sexta à tarde são inúteis, porque o cliente também está cansado e desatento",
    ], correta: 2, explicacao: "O cansaço reverte o vendedor ao erro mais básico. A quinta visita do dia é feita por um vendedor pior. Máximo de 4 diagnósticos por dia, com pausa." },
    { pergunta: "O trimestre recorde seguido de mês zerado e burnout ensina que:", opcoes: [
      "Performance é média sustentada, não pico; o ano com rotina de energia rendeu mais máquinas e nenhum quase-acidente",
      "Recordes devem ser evitados, porque o esforço extra sempre cobra um preço no mês seguinte",
      "A meta trimestral estava alta demais, e o recorde foi obtido à custa da saúde por causa dela",
      "Férias em outubro, logo depois do recorde, teriam evitado o mês zerado e o princípio de burnout",
    ], correta: 0, explicacao: "41 máquinas com rotina sustentável contra 36 no ano do recorde e do colapso. Pico que cobra saúde e um mês zerado é dívida." },
    { pergunta: "A fábrica confirmou 35 dias; o cliente fecha 'se garantir 20'. O que fazer?", opcoes: [
      "Garantir 20 dias, porque a fábrica costuma antecipar e a chance de cumprir é alta o bastante para o risco valer",
      "Garantir 20 dias com desconto proporcional se atrasar, o que protege o cliente do risco e mantém a venda fechada",
      "Dizer 35 confirmados e resolver a obra do dia 25 com uma alternativa honesta (usada do pátio para cobrir o início)",
      "Recusar a venda com elegância, porque o prazo pedido não é possível e não vale o risco de furar a promessa",
    ], correta: 2, explicacao: "Não prometer o que não controla; resolver o problema real. Uma promessa furada contamina todas as seguintes." },
    { pergunta: "O comprador insinua 'ajuda pessoal'. Qual é a conduta?", opcoes: [
      "Aceitar discretamente, porque é padrão do mercado e recusar significa perder a conta",
      "Recusar com elegância, oferecer valor legítimo e visível para ele mostrar à diretoria, e registrar",
      "Aceitar e lançar como despesa comercial de relacionamento, dentro da margem da venda",
      "Ignorar a insinuação, seguir a negociação normalmente e não registrar nada para não criar atrito",
    ], correta: 1, explicacao: "Qualquer valor fora da nota é o fim do nome na região e, muitas vezes, crime. A recusa elegante com alternativa legítima atende à necessidade real do comprador." },
    { pergunta: "Qual é a pergunta que o vendedor faz a si mesmo antes de qualquer decisão em zona cinzenta, segundo a aula de ética?", opcoes: [
      "'Isso está dentro da política comercial da concessionária e da fábrica?'",
      "'O gerente aprovaria essa decisão se soubesse de todos os detalhes?'",
      "'Se isso fosse contado na associação, com o meu nome, eu ficaria tranquilo?'",
      "'O cliente tem como descobrir isso nos próximos meses ou anos?'",
    ], correta: 2, explicacao: "No interior, tudo é contado. O teste antecipa a consequência pública e resolve a zona cinzenta em segundos." },
    { pergunta: "Qual é a sequência do ciclo semanal de prática deliberada?", opcoes: [
      "Diagnóstico do ponto fraco (win/loss e painel), estudo dirigido da aula, treino com IA no ponto fraco, revisão espaçada e uma linha no playbook",
      "Reler todos os módulos da trilha e refazer as provas, para consolidar a teoria antes de qualquer treino prático",
      "Treino com IA na dificuldade 1 até tirar 10 em todos os módulos, para construir confiança antes de subir o nível",
      "Copiar as melhores frases e roteiros dos livros de vendas para o playbook, para ter um material completo de consulta",
    ], correta: 0, explicacao: "Ericsson: específico, com feedback, além do confortável, repetido e registrado. A nota do treino é diagnóstico, não troféu; o playbook é seu, não do livro." },
    { pergunta: "O que explica, no caso dos dois vendedores, a diferença de 60% em vendas com o mesmo número de visitas após cinco anos?", opcoes: [
      "Carteira melhor, com mais pedreiras e construtoras grandes que compram máquinas maiores e renovam a frota com frequência",
      "Sorte com o mercado, com mais obras públicas e safras mais fortes na região do segundo vendedor durante os cinco anos",
      "Duas horas semanais de aprendizado deliberado que subiram a conversão de 24% para 39% e reduziram o desconto de 3,5% para 1,4%",
      "Treinamento formal da fábrica, com cursos técnicos e comerciais ao longo dos cinco anos, que o primeiro vendedor não fez",
    ], correta: 2, explicacao: "Experiência é o que acontece com você; aprendizado é o que você faz com ela. Conversão e margem são efeito do método, e método se treina na sexta à tarde." },
  ],
};
