import type { Modulo } from "./tipos";

export const M2: Modulo = {
  id: "m2", nivel: 2, titulo: "Psicologia do comprador de máquinas", tema: "Psicologia", cor: "#a78bfa",
  descricao: "Como o dono de obra, o produtor e o gestor público decidem de verdade — perfis DISC, vieses, motivadores profundos, escuta ativa e construção de confiança.",
  objetivos: [
    "Identificar o perfil DISC do cliente em 2 minutos e ajustar abordagem, ritmo e argumento.",
    "Usar ancoragem, prova social e aversão à perda com ética e precisão.",
    "Mapear e vender para o comitê invisível: sócio, cônjuge, contador, operador.",
    "Descobrir o motivador profundo por trás do pedido de preço.",
    "Dominar escuta ativa, rótulos e silêncio para o cliente se abrir.",
    "Construir credibilidade rápida: competência + calor humano + consistência.",
  ],
  leituras: [
    "Robert Cialdini — As Armas da Persuasão e Pré-suasão.",
    "Daniel Kahneman — Rápido e Devagar.",
    "Chris Voss — Negocie como se sua vida dependesse disso.",
    "Jeb Blount — Inteligência Emocional em Vendas (Sales EQ).",
  ],
  aulas: [
    {
      id: "m2a1", titulo: "DISC na prática: leia o cliente em 2 minutos", minutos: 12,
      resumo: "Dominante, Influente, Estável, Cauteloso: cada perfil compra por um motivo e odeia uma abordagem. Aprenda a reconhecer e adaptar.",
      blocos: [
        { tipo: "p", texto: "O DISC não é rótulo, é bússola. Ninguém é 100% um perfil, mas todo comprador tem um dominante que dita ritmo, vocabulário e o que precisa ouvir para dizer sim. Errar o perfil é falar grego: o D acha você lento, o C acha você raso, o S acha você agressivo, o I acha você frio." },
        { tipo: "tabela", titulo: "Como identificar e como falar", colunas: ["Perfil", "Sinais", "Quer ouvir", "Evite"], linhas: [
          ["D — Dominante (dono de pedreira, empreiteiro grande)", "Fala curto, interrompe, pergunta preço logo, decide rápido", "Resultado, prazo, retorno. “Essa máquina produz X a mais. Entrego em 15 dias.”", "Enrolação, detalhes, falar de sentimento"],
          ["I — Influente (empreiteiro comunicativo, dono de locadora)", "Manda áudio longo, conta histórias, pergunta de você, gosta de gente", "Reconhecimento, status, quem mais comprou. “Vai ser a primeira E215C da região.”", "Frieza, planilha sem conversa, apressar"],
          ["S — Estável (produtor de café, empresa familiar)", "Demora, pede para pensar, cita o cunhado, valoriza tradição", "Segurança, garantia, assistência, tempo. “A gente vai junto, sem pressa.”", "Pressão, mudança brusca, ameaça de perder"],
          ["C — Cauteloso (engenheiro, comprador de prefeitura, contador)", "Pede PDF, pergunta consumo com decimais, compara tudo", "Dados, comparativo, custo total, referências técnicas", "Achismo, exagero, falta de documento"],
        ] },
        { tipo: "p", titulo: "Sinais rápidos", texto: "Responde mensagem com uma palavra e pergunta preço logo = D. Manda áudio longo e pergunta como você está = I. Demora a responder, pede para “pensar” e cita o cunhado que entende = S. Pede PDF, pergunta de garantia e consumo com casas decimais = C. O CRM registra o perfil DISC no cadastro do cliente — preencha depois de cada conversa." },
        { tipo: "script", titulo: "Mesma máquina, quatro aberturas", itens: [
          "D: “Fulano, direto ao ponto: a E215C carrega 30% mais por hora que a sua atual e eu entrego em 20 dias. Quer ver a conta?”",
          "I: “Fulano, lembrei de você na entrega da pedreira do Zé — a equipe dele adorou a máquina. Você vai ser o próximo com a E215C na região, e ainda entra no vídeo.”",
          "S: “Fulano, sem pressa nenhuma. Quero só te mostrar como fica a assistência e a garantia da E215C, pra você ter segurança. Posso passar aí semana que vem e conversar com calma?”",
          "C: “Fulano, segue o comparativo técnico da E215C com consumo, ciclo e custo por hora medidos. Marquei os dados que diferenciam. Me diga quais critérios pesam mais pra você avaliar.”",
        ] },
        { tipo: "tabela", titulo: "Fechamento por perfil", colunas: ["Perfil", "Fechamento que funciona", "Ritmo"], linhas: [
          ["D", "Alternativo e assumido: “60 ou 48 meses? Fecho hoje.”", "Rápido, na primeira ou segunda conversa"],
          ["I", "Prova social + assumido: “Vou reservar a sua e agendar a entrega com foto pra equipe.”", "Médio, precisa de relação"],
          ["S", "Resumo de segurança + passo pequeno: “Vamos só mandar os documentos pro banco, sem compromisso, pra ver a condição?”", "Lento, com garantias"],
          ["C", "Balanço (prós e contras) + condicional documentado", "Lento, exige dados"],
        ] },
        { tipo: "caso", titulo: "Caso: o produtor S que “ia pensar”", situacao: "Produtor de café em Iúna, perfil S, ouviu a apresentação da retro e disse que ia pensar. O vendedor insistiu com urgência (“a tabela sobe dia 30”). O cliente sumiu.", acao: "Um mês depois, o vendedor voltou sem falar de preço. Levou o mecânico da concessionária para explicar a assistência e a garantia, e deixou o cliente falar da família e da lavoura. Propôs só mandar os documentos ao banco “para ver a condição”.", resultado: "Duas semanas depois o cliente fechou — em consórcio, com lance na safra.", licao: "Perfil S precisa de segurança e tempo. Pressão de D em cliente S mata a venda." },
        { tipo: "erros", titulo: "Erros de leitura", itens: [
          "Tratar o comprador da prefeitura (C) com conversa de I — ele quer documento, não amizade.",
          "Achar que o D grosso “não gostou de você”. Ele só quer resultado; entregue e ele fecha.",
          "Vender para o S como se ele fosse D: pressa e urgência quebram a confiança.",
          "Ignorar que o SEU perfil também pesa. Se você é I e o cliente é C, fale menos e mostre mais.",
        ] },
      ],
      missao: "Identifique e registre no CRM o perfil DISC dos 10 clientes com quem mais conversou este mês. Para os 3 mais quentes, reescreva a próxima mensagem no tom do perfil.",
      quiz: [
        { pergunta: "Cliente responde tudo com uma palavra e já perguntou o preço duas vezes. Perfil e abordagem:", opcoes: ["S — dê tempo e garantias", "D — vá direto ao resultado e ao prazo", "I — conte uma história"], correta: 1, explicacao: "Dominante quer resultado e velocidade. Enrolação o irrita." },
        { pergunta: "Produtor de café que “vai pensar” e cita o cunhado. Melhor caminho:", opcoes: ["Pressionar com urgência", "Dar segurança (garantia, assistência, tempo) e propor um passo pequeno", "Mandar mais ficha técnica"], correta: 1, explicacao: "Perfil S compra segurança e relação. Pressão gera fuga." },
        { pergunta: "Comprador da prefeitura pede consumo por hora com decimais. Você:", opcoes: ["Diz “é econômica”", "Manda o comparativo técnico com dados e fontes", "Conta uma história de cliente"], correta: 1, explicacao: "Perfil C decide com dados. Achismo é o que ele mais rejeita." },
      ],
    },
    {
      id: "m2a2", titulo: "Vieses que decidem a compra: ancoragem, prova social e aversão à perda", minutos: 11,
      resumo: "O cérebro decide com atalhos. Conheça os principais vieses do comprador de máquinas e use-os com ética.",
      blocos: [
        { tipo: "p", titulo: "Ancoragem", texto: "O primeiro número mencionado vira referência. Se o cliente ancora em “a chinesa custa 300”, tudo fica caro. Ancore você primeiro no valor total de propriedade: “uma máquina dessas produz cerca de R$ 40 mil por mês; a diferença de preço entre as marcas se paga em poucos meses de disponibilidade”. Depois apresente o preço." },
        { tipo: "p", titulo: "Prova social", texto: "Ninguém quer ser o primeiro a errar. Cite clientes da mesma cidade e do mesmo nicho (com permissão): “a pedreira de Cachoeiro trocou por E215C e reduziu o consumo”. Fotos e vídeos de máquina trabalhando na região valem mais que catálogo. Peça depoimento no pós-venda e guarde no celular." },
        { tipo: "p", titulo: "Aversão à perda", texto: "Perder dói mais que ganhar. Em vez de “você vai ganhar produtividade”, diga “você está perdendo R$ 3 mil por dia cada vez que a máquina antiga para”. Em fechamento: “a tabela sobe dia 1º; depois disso esse valor não existe mais” (só se for verdade)." },
        { tipo: "tabela", titulo: "Outros vieses que aparecem toda semana", colunas: ["Viés", "Como aparece", "Como usar / neutralizar"], linhas: [
          ["Status quo", "“A minha antiga ainda funciona”", "Quantifique o custo de manter (manutenção crescente, consumo, paradas). Mostre que ficar parado também é decisão com custo."],
          ["Custo afundado", "“Acabei de gastar 30 mil na retífica”", "“Entendo. O que já foi gasto não volta. A pergunta é o que custa daqui pra frente.” Use a usada como entrada."],
          ["Reciprocidade", "Você entrega valor antes (análise de custo, visita técnica, avaliação da usada)", "O cliente se sente em dívida e retribui com atenção e abertura."],
          ["Compromisso e consistência", "Pequenos “sins” (visita, teste, documentos)", "Cada sim pequeno cria inércia para o sim grande. Peça-os em sequência."],
          ["Autoridade", "Cliente confia em quem demonstra domínio", "Comparativo, dados verificados, mecânico junto na visita, histórico de entregas."],
          ["Contraste", "Proposta apresentada depois de uma opção maior", "Apresente a E245C antes da E215C: a segunda parece acessível."],
          ["Escassez", "Uma unidade no pátio, campanha até dia 30", "Só com fatos reais. Escassez falsa destrói confiança para sempre."],
        ] },
        { tipo: "script", titulo: "Ancorando antes do preço", itens: [
          "“Antes de falar de valor, deixa eu te mostrar o que essa máquina produz: numa obra como a sua, uns R$ 35 a 40 mil por mês de serviço. Guarda esse número.”",
          "“A diferença pra marca mais barata é uns R$ 80 mil. Só que em 5 anos ela vale R$ 90 mil a mais na revenda e para menos. Quem está pagando caro de verdade?”",
        ] },
        { tipo: "destaque", titulo: "Ética", texto: "Esses gatilhos funcionam porque são verdade. Inventar escassez ou depoimento destrói a confiança que é o seu maior ativo. Use fatos reais, sempre." },
        { tipo: "caso", titulo: "Caso: contraste na pedreira", situacao: "Pedreira em Vargem Alta queria trocar a escavadeira, mas achava a E215C “muito cara”.", acao: "O vendedor levou primeiro a proposta da E245C (a máquina ideal para o volume deles em 3 anos). Depois apresentou a E215C como “a que resolve hoje com folga”.", resultado: "A E215C, antes “cara”, virou a opção sensata. Fecharam em 3 semanas.", licao: "Sem referência, todo preço é alto. Você escolhe a referência." },
      ],
      missao: "Liste 3 clientes satisfeitos por nicho (café, construção, pedreira, prefeitura) e peça permissão para citá-los. Grave um vídeo curto de uma máquina trabalhando com o depoimento do dono.",
      quiz: [
        { pergunta: "O cliente já ancorou no preço da marca mais barata. O que fazer?", opcoes: ["Baixar o preço", "Reancorar no custo total e no valor produzido antes de falar de preço", "Aceitar a comparação"], correta: 1, explicacao: "Ancoragem se combate com outra âncora: valor produzido e custo em 5 anos." },
        { pergunta: "Qual frase usa aversão à perda corretamente?", opcoes: ["“Você vai ganhar produtividade”", "“Cada dia de máquina parada você perde R$ 3 mil”", "“A máquina é muito boa”"], correta: 1, explicacao: "Perda concreta em reais move mais que ganho abstrato." },
        { pergunta: "Cliente gastou R$ 30 mil na retífica e não quer trocar. Viés e resposta:", opcoes: ["Escassez — crie urgência", "Custo afundado — o que foi gasto não volta; olhe o custo daqui pra frente", "Autoridade — mostre a ficha"], correta: 1, explicacao: "Reconheça o gasto e mude o foco para o futuro. A usada vira entrada." },
      ],
    },
    {
      id: "m2a3", titulo: "O comitê invisível: sócio, cônjuge, contador e operador", minutos: 10,
      resumo: "Quem está na sua frente raramente decide sozinho. Descubra o comitê e venda para cada membro.",
      blocos: [
        { tipo: "p", texto: "Você apresenta para o dono, ele adora, e na semana seguinte diz “conversei aqui e vamos esperar”. Alguém que você nunca viu matou a venda: o sócio conservador, a esposa que cuida do caixa, o contador que tem medo da parcela, o operador que prefere a marca que conhece. Mapear o comitê é parte do diagnóstico, não do fechamento." },
        { tipo: "tabela", titulo: "Membros do comitê e o que cada um precisa", colunas: ["Quem", "Medo", "O que entregar"], linhas: [
          ["Sócio", "Endividar a empresa, parcela alta", "Conta de retorno e fluxo de caixa: a parcela cabe no que a máquina produz"],
          ["Cônjuge / família", "Risco ao patrimônio", "Segurança: garantia, assistência, revenda, histórico da marca"],
          ["Contador / financeiro", "Impacto fiscal e no caixa", "Simulação de Finame/consórcio, depreciação, prazo e carência"],
          ["Operador", "Máquina difícil, sem peça, perder o emprego", "Demonstração com ele na cabine, treinamento incluso, conforto"],
          ["Engenheiro / fiscal (prefeitura)", "Especificação errada, máquina reprovada", "Ficha técnica, atendimento ao edital, ensaios"],
          ["Agrônomo / cooperativa (café)", "Máquina inadequada ao terreno", "Aplicação correta, casos de outros produtores"],
        ] },
        { tipo: "script", titulo: "Mapeando o decisor", itens: [
          "“Além de você, quem mais participa da decisão? Quero que ninguém fique com dúvida.”",
          "“Quando você comprou a última máquina, como foi o processo? Quem opinou?”",
          "“Posso apresentar a conta pro seu sócio também? Assim vocês decidem com a mesma informação.”",
          "“Seu operador pode vir na demonstração? A opinião dele vai pesar, e eu prefiro que ele veja com os próprios olhos.”",
        ] },
        { tipo: "lista", titulo: "Como vender para o comitê", itens: [
          "Peça a reunião com todos os decisores desde o início. Uma apresentação para 3 pessoas vale mais que três separadas.",
          "Prepare material para cada medo: uma página de retorno (sócio), uma de segurança (família), uma de financiamento (contador).",
          "Transforme o mais cético em aliado: dê a ele a informação que ele pediria antes de pedir.",
          "Nunca deixe o cliente “apresentar por você”. Ele não vai lembrar dos argumentos nem responder às objeções.",
          "Registre no CRM quem é quem e o que cada um disse.",
        ] },
        { tipo: "caso", titulo: "Caso: a esposa que cuidava do caixa", situacao: "Empreiteiro de Marataízes adorou a retro na demonstração. Duas semanas depois: “minha esposa achou a parcela pesada”.", acao: "O vendedor pediu para apresentar a conta para os dois. Levou a simulação com a receita mensal da retro, a carência de 90 dias e o valor da usada na entrada. Respondeu as perguntas dela sobre garantia e revenda.", resultado: "Ela mesma sugeriu o prazo de 48 meses. Fechou na reunião.", licao: "Quem cuida do caixa precisa da conta, não do entusiasmo. Descubra quem é e apresente para essa pessoa." },
      ],
      missao: "Para as 5 negociações mais quentes do CRM, escreva quem é o comitê de cada uma (sócio, cônjuge, contador, operador) e o que cada membro precisa ouvir. Marque uma reunião com pelo menos um comitê completo.",
      quiz: [
        { pergunta: "Cliente disse “vou conversar com meu sócio”. Melhor ação:", opcoes: ["Esperar ele conversar", "Propor apresentar a conta para o sócio junto", "Mandar a proposta de novo"], correta: 1, explicacao: "O cliente não vai apresentar por você. Esteja na sala quando a decisão for tomada." },
        { pergunta: "O operador é contra a troca de marca. O que fazer?", opcoes: ["Ignorar, quem decide é o dono", "Colocar o operador na cabine na demonstração e incluir treinamento", "Falar mal da marca que ele conhece"], correta: 1, explicacao: "Operador contra sabota a venda e o pós-venda. Operador a favor vira defensor." },
      ],
    },
    {
      id: "m2a4", titulo: "O porquê por trás do porquê: motivadores profundos", minutos: 10,
      resumo: "“Quero preço” nunca é o motivo real. Medo, status, segurança, orgulho, ganância, liberdade: descubra o que move a compra e fale com isso.",
      blocos: [
        { tipo: "p", texto: "Toda compra de máquina tem um motivo declarado (preciso de uma retro) e um motivo real (não quero mais passar vergonha com a máquina quebrando na frente do cliente; quero pegar a obra grande; quero que meu filho assuma um negócio sólido; quero parar de depender de aluguel). O vendedor mediano responde ao motivo declarado. O de elite descobre e fala com o motivo real." },
        { tipo: "tabela", titulo: "Motivadores e como identificar", colunas: ["Motivador", "Sinais na fala", "Como falar com ele"], linhas: [
          ["Medo (de parar, de perder contrato, de errar)", "“Não posso ficar na mão”, “se parar eu perco a medição”", "Segurança, disponibilidade, assistência, garantia, casos de quem resolveu"],
          ["Status / orgulho", "Fala da frota, mostra fotos, quer ser referência", "“Primeira E215C da região”, foto na entrega, reconhecimento público"],
          ["Ganância / crescimento", "Fala de contratos maiores, de crescer, de comprar a segunda", "Retorno em reais, capacidade de pegar obra maior, plano de frota"],
          ["Segurança da família", "Cita filhos, sucessão, “deixar a empresa arrumada”", "Patrimônio, revenda, marca sólida, relação de longo prazo"],
          ["Liberdade / controle", "Cansado de depender de aluguel, de terceiro, de prazo dos outros", "Autonomia: “a máquina é sua, no seu horário, no seu ritmo”"],
          ["Reconhecimento da equipe", "Fala do operador, do encarregado", "Conforto, treinamento, a equipe vai render mais e reclamar menos"],
        ] },
        { tipo: "script", titulo: "Perguntas que revelam o motivo real", itens: [
          "“O que te fez pensar em trocar agora, e não no ano passado?”",
          "“O que acontece se você passar mais um ano com a máquina atual?”",
          "“Se essa máquina resolver, o que muda na sua empresa daqui a um ano?”",
          "“Qual foi a última vez que a máquina te deixou na mão? Como foi?”",
          "“Além do serviço, tem alguma coisa que te incomoda hoje na operação?”",
        ] },
        { tipo: "p", titulo: "Como usar", texto: "Depois de descobrir o motivador, ele vira a espinha dorsal da apresentação e do fechamento. Para quem tem medo: “com a E215C e a assistência aqui do lado, você nunca mais liga pro cliente dizendo que parou”. Para quem quer crescer: “com essa máquina você concorre na obra da BR, que hoje você nem cota”. O preço passa a ser o custo de resolver o que dói de verdade." },
        { tipo: "caso", titulo: "Caso: a vergonha na frente do cliente", situacao: "Empreiteiro dizia que só queria “uma retro em conta”. Três propostas de vários vendedores, nenhuma fechada.", acao: "Na visita, o vendedor perguntou quando a máquina o deixou na mão pela última vez. Ele contou que a retro quebrou na obra de um cliente grande e ele teve que alugar às pressas, com o cliente assistindo. Motivo real: nunca mais passar por aquilo.", resultado: "A apresentação foi toda sobre disponibilidade e assistência em 24 h. Fechou a B110B nova — mais cara que as “em conta” que ele cotava.", licao: "O motivo real muda o produto, o argumento e o preço aceito." },
      ],
      missao: "Nas próximas 3 visitas, faça a pergunta “o que te fez pensar em trocar agora?” e “o que acontece se ficar mais um ano assim?”. Registre o motivo real de cada cliente no resumo do CRM.",
      quiz: [
        { pergunta: "Cliente diz “só quero uma retro em conta”. O que fazer?", opcoes: ["Mandar a mais barata", "Descobrir o motivo real por trás com perguntas de história", "Dar desconto"], correta: 1, explicacao: "O motivo declarado esconde o real. Perguntas de história revelam." },
        { pergunta: "Cliente fala o tempo todo da frota e mostra fotos. Motivador provável:", opcoes: ["Medo", "Status / orgulho", "Liberdade"], correta: 1, explicacao: "Quem se orgulha da frota compra reconhecimento: primeira da região, foto na entrega." },
      ],
    },
    {
      id: "m2a5", titulo: "Escuta ativa, rótulos e silêncio: fazer o cliente se abrir", minutos: 10,
      resumo: "Quem fala mais perde. Técnicas de escuta de negociadores de elite aplicadas à obra e ao WhatsApp.",
      blocos: [
        { tipo: "p", texto: "O cliente só compra depois de se sentir compreendido. E ele só se sente compreendido se falar — e se perceber que você ouviu. Vendedor que fala 70% do tempo está apresentando; o que ouve 70% está diagnosticando. A regra do vendedor de elite: 30% de fala, 70% de escuta, e cada frase sua é uma pergunta ou um resumo do que ele disse." },
        { tipo: "lista", titulo: "Técnicas (de Chris Voss e da venda consultiva)", itens: [
          "Espelho: repita as 2 ou 3 últimas palavras do cliente em tom de pergunta. “…parou três vezes?” Ele continua falando e detalha.",
          "Rótulo: nomeie a emoção. “Parece que você está cansado de ficar na mão.” / “Parece que a preocupação é a parcela.” O cliente corrige ou confirma — e se abre.",
          "Resumo: “Deixa eu ver se entendi: a máquina para, você aluga, atrasa a medição e ainda paga operador parado. É isso?” Um “é isso” do cliente vale mais que 10 argumentos.",
          "Silêncio: depois de uma pergunta importante, conte até 5 em silêncio. O cliente preenche o vazio com a informação que faltava.",
          "Perguntas calibradas (“como” e “o que”): “Como você está resolvendo hoje quando a máquina para?” em vez de “você tem problema com parada?”.",
          "Acusação preventiva: “Você deve estar pensando que vendedor sempre fala que a dele é a melhor…” Desarma a defesa antes dela aparecer.",
        ] },
        { tipo: "script", titulo: "Escuta ativa no WhatsApp", itens: [
          "Cliente: “Tô vendo umas opções aí, mas tá tudo caro.” → Você: “Tudo caro… O que você viu até agora que te assustou mais: o valor total ou a parcela?”",
          "Cliente: “Meu sócio não quer gastar agora.” → Você: “Parece que o receio dele é comprometer o caixa num momento incerto. É isso? O que ele precisaria ver pra ficar tranquilo?”",
          "Cliente: “Vou pensar.” → Você: “Claro. Pra eu não te atrapalhar com informação errada: o que ainda está pesando na decisão?”",
        ] },
        { tipo: "erros", titulo: "Erros de escuta", itens: [
          "Interromper para responder a objeção antes de o cliente terminar.",
          "Pensar na próxima frase enquanto ele fala (você não ouviu).",
          "Perguntas fechadas em sequência (“você tem retro? é velha? quebra?”) — parece interrogatório.",
          "Responder “entendo” sem resumir. Entender de verdade é conseguir repetir com as suas palavras.",
          "Preencher o silêncio. Quem aguenta o silêncio recebe a informação que decide a venda.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Na próxima conversa por WhatsApp, responda às 3 primeiras mensagens do cliente apenas com espelho ou rótulo (sem apresentar nada). Observe quanto ele conta a mais. Registre no CRM o que descobriu que não sabia." },
      ],
      missao: "Grave (com permissão) ou anote uma conversa de visita. Conte quantos minutos você falou e quantos o cliente falou. Se você passou de 40%, planeje 5 perguntas calibradas para a próxima.",
      quiz: [
        { pergunta: "O que é um “rótulo”?", opcoes: ["Chamar o cliente pelo apelido", "Nomear a emoção ou preocupação dele (“parece que…”)", "Classificar o cliente no CRM"], correta: 1, explicacao: "Rotular a emoção faz o cliente se sentir compreendido e falar mais." },
        { pergunta: "Depois de perguntar “o que ainda pesa na decisão?”, o cliente fica em silêncio. Você:", opcoes: ["Responde por ele com um argumento", "Espera em silêncio", "Muda de assunto"], correta: 1, explicacao: "O silêncio é do cliente. Quem espera recebe a resposta verdadeira." },
        { pergunta: "Proporção ideal de fala na visita de diagnóstico:", opcoes: ["70% você, 30% cliente", "30% você, 70% cliente", "50/50"], correta: 1, explicacao: "Diagnóstico é escuta. Apresentação vem depois, e curta." },
      ],
    },
    {
      id: "m2a6", titulo: "Confiança e credibilidade: como o cliente decide confiar em você", minutos: 9,
      resumo: "O cérebro julga competência e calor humano em segundos e confirma com consistência. Como construir os três — e como perder em um deslize.",
      blocos: [
        { tipo: "p", texto: "Pesquisas em psicologia social mostram que julgamos os outros em dois eixos: calor (essa pessoa está do meu lado?) e competência (essa pessoa sabe o que faz?). O vendedor precisa dos dois. Calor sem competência é o “gente boa que não resolve”; competência sem calor é o “sabe tudo mas eu não confio”. E os dois só se mantêm com consistência: fazer o que disse, sempre." },
        { tipo: "tabela", titulo: "Os três pilares e como construir cada um", colunas: ["Pilar", "Como se constrói", "Como se perde"], linhas: [
          ["Calor", "Interesse genuíno (pergunta da família, da obra, do operador), lembrar detalhes, agradecer, presença na obra sem vender", "Pressão fora de hora, ignorar mensagem, falar só de venda"],
          ["Competência", "Dados verificados, comparativo, resposta rápida com fonte, conhecer a obra e o mercado local, trazer o mecânico", "Inventar dado, errar prazo, não saber a própria máquina"],
          ["Consistência", "Cumprir horário, prazo e promessa; avisar antes quando algo muda; mesma postura com dono e operador", "Prometer e não entregar, sumir depois da venda, mudar versão"],
        ] },
        { tipo: "lista", titulo: "Ações de confiança que custam pouco", itens: [
          "Chegar 5 minutos antes. Sempre.",
          "Mandar o que prometeu no mesmo dia, mesmo que seja “ainda não tenho a resposta, mas estou em cima”.",
          "Admitir quando a sua máquina não é a melhor para aquela aplicação — e indicar a certa (às vezes uma menor). Você vira consultor para sempre.",
          "Lembrar e citar o que ele disse na visita anterior (está no CRM).",
          "Resolver um problema de pós-venda de um cliente antigo com prioridade — na frente do cliente novo, se possível.",
        ] },
        { tipo: "destaque", titulo: "Credibilidade emprestada", texto: "Enquanto a sua ainda está em construção, use a da marca (anos no mercado, rede, garantia), a dos clientes (depoimentos, fotos) e a do técnico (mecânico na visita). Depois de 2 ou 3 entregas bem feitas na região, a credibilidade passa a ser sua." },
        { tipo: "caso", titulo: "Caso: a máquina menor", situacao: "Produtor de café queria uma escavadeira E145C para terraceamento. Na visita, o vendedor viu que a lavoura era pequena e o terreno permitia uma retro com braço extensível.", acao: "Disse ao cliente que a escavadeira era mais máquina do que ele precisava e recomendou a retro, R$ 200 mil mais barata.", resultado: "O cliente comprou a retro — e no ano seguinte indicou 3 vizinhos, um deles comprou uma E215C.", licao: "Recomendar a máquina certa, mesmo menor, é o investimento de credibilidade com maior retorno." },
      ],
      missao: "Escolha 3 clientes em negociação e faça, para cada um, uma ação de calor (sem vender) e uma de competência (dado, comparativo ou mecânico) nesta semana. Registre no CRM.",
      quiz: [
        { pergunta: "O cliente acha você “gente boa” mas não fecha. O que provavelmente falta?", opcoes: ["Mais calor", "Competência demonstrada (dados, domínio, resolução)", "Desconto"], correta: 1, explicacao: "Calor sem competência não gera segurança para uma decisão de R$ 500 mil." },
        { pergunta: "A sua máquina não é a ideal para a aplicação do cliente. Você:", opcoes: ["Vende mesmo assim", "Diz a verdade e recomenda a certa", "Não responde"], correta: 1, explicacao: "Honestidade em uma venda constrói credibilidade para dezenas de outras." },
      ],
    },
  ],
  prova: [
    { pergunta: "Cliente manda áudios longos, pergunta da sua família e fala da frota com orgulho. Perfil e argumento:", opcoes: ["C — comparativo técnico", "I — reconhecimento e prova social", "S — tempo e garantias"], correta: 1, explicacao: "Influente compra relação e status." },
    { pergunta: "Para neutralizar uma âncora de preço baixo do concorrente, você:", opcoes: ["Baixa o preço", "Ancora primeiro em valor produzido e custo de 5 anos", "Fala mal do concorrente"], correta: 1, explicacao: "Âncora se combate com âncora melhor." },
    { pergunta: "Quem costuma travar a venda sem nunca aparecer?", opcoes: ["O operador e quem cuida do caixa", "O concorrente", "O banco"], correta: 0, explicacao: "O comitê invisível decide. Mapeie e apresente para cada um." },
    { pergunta: "“Parece que a sua preocupação é ficar na mão de novo.” Isso é:", opcoes: ["Espelho", "Rótulo", "Resumo"], correta: 1, explicacao: "Rótulo nomeia a emoção e abre o cliente." },
    { pergunta: "O cliente diz “só quero preço”. O vendedor de elite:", opcoes: ["Manda a tabela", "Pergunta o que o fez pensar em trocar agora", "Encerra"], correta: 1, explicacao: "O motivo real está atrás do motivo declarado." },
    { pergunta: "Qual pilar da confiança se perde ao prometer prazo e não avisar do atraso?", opcoes: ["Calor", "Consistência", "Competência"], correta: 1, explicacao: "Consistência é fazer o que disse e avisar antes quando muda." },
  ],
};
