import type { Modulo } from "./tipos";

export const M2: Modulo = {
  id: "m2", nivel: 2, titulo: "Psicologia e neurociência da decisão", tema: "Comportamento", cor: "#a78bfa",
  descricao: "Como o cérebro do comprador decide de verdade: os dois sistemas de Kahneman, os perfis DISC na obra e na prefeitura, aversão à perda e custo da inação, os gatilhos de Cialdini usados com ética, confiança e rapport (Voss) e por que a história vende mais que a planilha — e a planilha justifica.",
  objetivos: [
    "Reconhecer quando o cliente está decidindo com o Sistema 1 (rápido, emocional) ou com o Sistema 2 (lento, analítico) e adaptar a conversa.",
    "Identificar o perfil DISC do comprador em 3 minutos de conversa e ajustar ritmo, profundidade e argumento.",
    "Usar a aversão à perda e o custo da inação para tirar o cliente do status quo sem pressão artificial.",
    "Aplicar os seis princípios de Cialdini com ética: prova social, reciprocidade, autoridade, escassez real, coerência e afinidade.",
    "Construir confiança rápida com rótulos, espelhamento e perguntas calibradas (Chris Voss).",
    "Contar uma história de cliente que ancora a decisão e, em seguida, entregar a conta que a justifica.",
  ],
  leituras: [
    "Daniel Kahneman — Rápido e Devagar: os dois sistemas do pensamento e os vieses que decidem compras de R$ 600 mil.",
    "Robert Cialdini — As Armas da Persuasão: os seis princípios (e a edição nova com o sétimo, unidade).",
    "Chris Voss — Negocie como se sua vida dependesse disso: rótulos, espelhamento, perguntas calibradas e o 'não' que abre a conversa.",
    "Dan Ariely — Previsivelmente Irracional: ancoragem, custo zero e por que 'grátis' distorce a decisão.",
    "William Marston / DISC: qualquer manual prático de DISC aplicado a vendas (o modelo tem 90 anos e continua funcionando na obra).",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m2a1", titulo: "Dois cérebros compram a máquina: Sistema 1 e Sistema 2", minutos: 14,
      resumo: "O cliente decide com a emoção e justifica com a razão. Se você só fala com a planilha, perde o coração; se só fala com o coração, perde o sócio e o banco. O consultor fala com os dois, na ordem certa.",
      blocos: [
        { tipo: "p", texto: "Daniel Kahneman ganhou o Nobel mostrando que o cérebro tem dois modos. O Sistema 1 é rápido, automático, emocional: é ele que faz o empreiteiro sentir que 'essa máquina é boa' ao ver a cabine limpa e o vendedor que chegou na hora. O Sistema 2 é lento, analítico, cansa fácil: é ele que compara custo por hora e lê a proposta. A maioria das decisões de compra de máquina é tomada pelo Sistema 1 e depois ratificada — ou vetada — pelo Sistema 2 (quase sempre na figura do sócio, da esposa, do contador ou do banco). Vender bem é conquistar o Sistema 1 e municiar o Sistema 2." },
        { tipo: "framework", nome: "Sequência Emoção → Razão → Segurança", origem: "Kahneman (Rápido e Devagar) aplicado à venda de bens de capital", passos: [
          "Emoção (Sistema 1): primeiros 3 minutos — pontualidade, aparência, interesse genuíno pela obra, uma história de cliente parecido. O cliente decide se gosta de você antes de ouvir qualquer número.",
          "Razão (Sistema 2): a conta na frente dele — custo por hora, consumo, revenda, parcela × faturamento da obra. Curta e visual: o Sistema 2 cansa e desliga em 10 minutos de planilha.",
          "Segurança (os dois): garantia, assistência a X km, cliente de referência para ligar, prazo confirmado por escrito. É o que o Sistema 2 vai usar para defender a compra para o sócio.",
          "Fechamento no Sistema 1: 'Te vejo entregando na terça?' — a decisão final é emocional; a proposta escrita é a justificativa que fica.",
        ] },
        { tipo: "tabela", titulo: "Sinais de qual sistema está no comando", colunas: ["O cliente…", "Sistema no comando", "O que fazer"], linhas: [
          ["Pergunta 'e a cabine tem ar?', olha a máquina, sobe nela", "Sistema 1", "Deixe sentir: teste, operador dele na máquina, história de cliente parecido"],
          ["Pede planilha de consumo e comparativo por escrito", "Sistema 2", "Entregue números curtos e verificáveis; ofereça cliente de referência"],
          ["Diz 'preciso ver com meu sócio'", "Sistema 2 (de outra pessoa)", "Prepare o material que o sócio vai pedir: parcela, custo/hora, garantia; peça para estar na conversa"],
          ["Decide rápido e depois fica quieto", "Sistema 2 chegando atrasado (arrependimento)", "Reforce com fato: ligue no dia seguinte com a confirmação do prazo e o contato da assistência"],
          ["Discute cada linha da proposta", "Sistema 2 cansado ou perfil C", "Simplifique: três números que importam e uma referência"],
        ] },
        { tipo: "dialogo", titulo: "Falando com os dois sistemas", falas: [
          { quem: "cliente", texto: "Gostei da máquina. Mas 620 mil… meu sócio vai me matar." },
          { quem: "vendedor", texto: "Ele vai perguntar se a conta fecha, e é justo. Deixa eu te dar o que você vai mostrar pra ele: com 180 horas por mês, a parcela do FINAME fica em R$ 11.900 e a máquina produz uns R$ 38 mil de serviço. A antiga parou 4 dias no mês passado — foram R$ 4.400 de aluguel e uma medição atrasada." },
          { quem: "nota", texto: "O cliente já decidiu (Sistema 1: 'gostei'). O vendedor não tenta convencê-lo de novo; ele arma o Sistema 2 do sócio com três números." },
          { quem: "cliente", texto: "Isso ele entende. Manda por escrito?" },
          { quem: "vendedor", texto: "Mando hoje, numa página. E se ele quiser ligar pro Marcos, da Terraplenagem Rio Novo, que tem uma E215C há dois anos, eu passo o contato. Quinta às 10h eu passo aí pra ver com vocês dois?" },
          { quem: "nota", texto: "Segurança (referência) e próximo passo com o decisor presente. A venda não é 'convencer o cliente'; é dar ao cliente o material para ele convencer o sócio." },
        ] },
        { tipo: "caso", titulo: "Caso: a planilha de 14 páginas", situacao: "Vendedor preparou um comparativo de 14 páginas entre a W170B e a concorrente para um dono de pedreira perfil D. Apresentou linha por linha, 50 minutos.", acao: "O cliente cortou aos 15 minutos: 'Me diz só: quanto carrega por hora e quanto gasta'. O vendedor se perdeu voltando páginas. Perdeu a venda para um concorrente que chegou com uma folha de uma página e uma visita à pedreira vizinha.", resultado: "Na venda seguinte, o mesmo vendedor entrou com uma folha: 3 números, 1 foto da máquina trabalhando numa pedreira parecida e 1 contato de referência. Fechou em duas visitas.", licao: "O Sistema 2 cansa. Quem entrega 14 páginas para um perfil D não parece preparado; parece inseguro. Três números certos valem mais que quarenta." },
        { tipo: "destaque", titulo: "O ponto que muda tudo", texto: "O cliente não compra porque entendeu a conta. Ele compra porque confiou em você e a conta deu a ele a permissão de comprar. Por isso a ordem importa: confiança primeiro, conta depois, segurança para o sócio por último." },
        { tipo: "erros", titulo: "Erros de quem ignora os dois sistemas", itens: [
          "Começar a visita pela planilha: o Sistema 1 ainda não decidiu se gosta de você; o número entra em ouvido fechado.",
          "Achar que 'gostou da máquina' é venda fechada e não preparar o material para o sócio/contador.",
          "Apresentar 14 páginas para quem só quer três números — e três números para quem (perfil C) quer a memória de cálculo.",
          "Sumir depois do 'sim' emocional. O arrependimento (Sistema 2 chegando) mata vendas entre a assinatura e o faturamento.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue as três últimas negociações perdidas no CRM. Para cada uma, responda: o cliente tinha decidido emocionalmente (gostou de você/da máquina)? Quem era o Sistema 2 que vetou (sócio, banco, contador, esposa)? Você preparou material para essa pessoa? Anote o padrão." },
      ],
      missao: "Na próxima visita, aplique a sequência: 3 minutos de conexão sem falar de produto, depois a conta em três números, depois a segurança (referência + assistência + prazo escrito). Registre na negociação do CRM quem é o 'Sistema 2' da conta (sócio, financeiro, contador) e o que essa pessoa vai pedir.",
      quiz: [
        { pergunta: "O dono da empreiteira subiu na E145C, testou os comandos e disse 'essa máquina é boa'. Ainda não perguntou preço. Qual é o próximo passo mais inteligente?", opcoes: [
          "Aproveitar o entusiasmo e apresentar a tabela completa com implementos, porque o cliente aberto absorve mais informação",
          "Pedir o fechamento na hora, porque a decisão emocional está tomada e cada dia a mais é espaço para a dúvida voltar",
          "Perguntar quem mais participa da decisão e preparar os três números que essa pessoa vai pedir",
          "Mostrar o comparativo detalhado com a concorrente enquanto ele está na máquina, para reforçar a escolha com dados",
        ], correta: 2, explicacao: "O Sistema 1 já decidiu. O risco agora é o Sistema 2 de outra pessoa (sócio, contador, banco) vetar. O consultor descobre quem é e municia o cliente com parcela, custo por hora e referência. Tabela completa e comparativo longo cansam o Sistema 2 e diluem o entusiasmo." },
        { pergunta: "Por que um comparativo de 14 páginas costuma perder para uma folha de uma página com três números e uma referência?", opcoes: [
          "Porque o cliente do interior não tem o hábito de ler planilhas técnicas e prefere decidir pela conversa e pela visita",
          "Porque o Sistema 2 cansa rápido e excesso de dado é lido como insegurança, não como preparo",
          "Porque comparativos longos expõem detalhes que a política comercial das fábricas prefere não divulgar",
          "Porque números detalhados dão munição para o cliente pedir desconto item por item na negociação",
        ], correta: 1, explicacao: "Kahneman mostra que o pensamento analítico é caro e se esgota. Três números verificáveis mais uma prova social falam com os dois sistemas; 14 páginas só falam com um deles, e mal. Não é sobre capacidade do cliente: é sobre economia de atenção." },
        { pergunta: "O cliente fechou na sexta com entusiasmo. Na segunda está frio e não responde. O que provavelmente aconteceu e qual a melhor ação?", opcoes: [
          "O Sistema 2 chegou (arrependimento ou pressão de alguém); ligue com um fato novo: prazo confirmado, técnico, referência",
          "Ele está ocupado com a obra; mande uma mensagem objetiva pedindo a documentação para não perder a fila da fábrica",
          "Ele encontrou um preço menor no fim de semana; ofereça um desconto imediato para segurar a venda antes que ele mude",
          "Ele mudou de ideia por impulso; espere ele voltar, porque cobrar agora passa ansiedade e enfraquece a sua posição",
        ], correta: 0, explicacao: "O intervalo entre o 'sim' emocional e o faturamento é onde o arrependimento age. A resposta é reforçar com fatos que o Sistema 2 usa para se acalmar, não descontar (que confirma que o preço estava errado) nem cobrar (que aumenta a tensão)." },
        { pergunta: "Um contador (perfil analítico) pede a memória de cálculo do custo por hora que você apresentou ao dono. A melhor conduta é:", opcoes: [
          "Explicar que os números são estimativas de mercado já aprovadas pelo dono, e que a memória detalhada vem com o pedido",
          "Resumir em três números, como fez com o dono, porque detalhe demais atrapalha e o contador não decide a compra",
          "Pedir ao dono que intermedeie a conversa, para não abrir a conta com terceiros e manter a relação centralizada",
          "Enviar a planilha completa com as premissas explícitas e se colocar à disposição para revisar linha a linha",
        ], correta: 3, explicacao: "Cada sistema quer o seu alimento. O dono decidiu com três números; o contador é o Sistema 2 da conta e precisa das premissas para aprovar. Negar ou resumir para ele é criar um veto. Transparência com quem analisa é o que protege a venda." },
        { pergunta: "Qual afirmação descreve corretamente a relação entre emoção e razão na compra de uma máquina pesada?", opcoes: [
          "Compra de alto valor é essencialmente racional; a emoção só atrapalha o cliente sério e deve ser neutralizada com dados",
          "A emoção decide e a razão justifica; o vendedor precisa alimentar as duas, na ordem certa",
          "A razão decide e a emoção justifica; por isso a proposta escrita e a conta devem vir antes da visita à obra",
          "Emoção pesa só para o cliente pequeno; prefeitura, pedreira e construtora compram exclusivamente por planilha",
        ], correta: 1, explicacao: "Kahneman e décadas de pesquisa em compra B2B mostram que a preferência se forma rápido e emocionalmente, e a análise vem depois para ratificar. Até no pregão da prefeitura o engenheiro que escreve o termo de referência tem preferências formadas em visitas e conversas." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m2a2", titulo: "DISC na obra, na pedreira e na prefeitura", minutos: 15,
      resumo: "Quatro perfis, quatro maneiras de comprar. O D quer resultado e rapidez; o I quer relação e história; o S quer segurança e tempo; o C quer dado e memória de cálculo. Vender do seu jeito para todos é errar em três de cada quatro.",
      blocos: [
        { tipo: "p", texto: "O modelo DISC (Marston, 1928) divide o comportamento em quatro tendências: Dominância, Influência, eStabilidade e Conformidade. Ninguém é só uma letra, mas todo comprador tem uma dominante que aparece nos primeiros minutos: no ritmo da fala, no que pergunta primeiro, no que o irrita. O vendedor que reconhece a letra e ajusta o próprio comportamento vende para os quatro. O que não reconhece vende bem só para quem é parecido com ele." },
        { tipo: "tabela", titulo: "Os quatro perfis no seu mercado", colunas: ["Perfil", "Como reconhecer", "O que quer ouvir", "O que o irrita", "Exemplo típico"], linhas: [
          ["D — Dominante", "Fala curto, interrompe, pergunta 'quanto e quando', olha o relógio", "Resultado, produção por hora, prazo, 'resolvo isso'", "Rodeio, história longa, indecisão sua", "Dono de pedreira, empreiteiro grande"],
          ["I — Influente", "Fala muito, conta histórias, pergunta de quem você é", "Quem mais comprou, história de sucesso, reconhecimento", "Frieza, planilha sem conversa, ser ignorado", "Locador, produtor de café expansivo"],
          ["S — Estável", "Calmo, evita conflito, 'vou ver com calma', fiel ao fornecedor antigo", "Segurança, garantia, assistência, tempo para decidir", "Pressão, mudança brusca, 'só hoje'", "Empreiteiro familiar, cooperativa"],
          ["C — Conforme", "Pergunta detalhe técnico, pede por escrito, desconfia de elogio", "Dado, memória de cálculo, ficha técnica, comparativo honesto", "Chute, 'confia em mim', exagero", "Engenheiro da prefeitura, gerente de frota, contador"],
        ] },
        { tipo: "framework", nome: "Ajuste em 3 alavancas: Ritmo, Profundidade, Argumento", origem: "Prática de venda consultiva com DISC (Marston; adaptação de Bonnstetter/TTI)", passos: [
          "Ritmo: D e I decidem rápido — vá direto e proponha o passo. S e C decidem devagar — dê tempo, marque o próximo contato, não force.",
          "Profundidade: D quer 3 números; C quer a memória de cálculo; I quer a história; S quer a garantia e quem vai atender quando quebrar.",
          "Argumento: D = produção e prazo; I = prova social e reconhecimento; S = segurança e continuidade; C = dado verificável e comparativo honesto.",
          "Regra: o perfil é do CLIENTE, não seu. Se você é I e o cliente é C, fale menos e escreva mais. Se você é C e o cliente é D, corte a apresentação pela metade.",
        ] },
        { tipo: "dialogo", titulo: "Mesma objeção, dois perfis", falas: [
          { quem: "cliente", texto: "(perfil D, dono de pedreira) Tá caro. A Sany tá 90 mil a menos. Me dá um motivo." },
          { quem: "vendedor", texto: "Dois. Carrega 20% a mais por hora — na sua produção é um caminhão a mais por hora. E revende por 30% a mais em 5 anos. Quer ver na balança da pedreira do Zé na terça?" },
          { quem: "nota", texto: "Curto, número, desafio, ação. Nada de 'entendo sua preocupação' — o D lê isso como enrolação." },
          { quem: "cliente", texto: "(perfil S, empreiteiro familiar) Achei um pouco caro… a gente sempre comprou da outra marca, o pessoal de lá é conhecido." },
          { quem: "vendedor", texto: "Faz sentido, seu Antônio, 20 anos com o mesmo fornecedor é uma relação que vale muito. Não estou pedindo pra trocar tudo de uma vez. Que tal a gente olhar juntos como seria a assistência aqui em Alegre — quem atende, em quanto tempo — e você conversa com a família com calma? Posso voltar na outra semana?" },
          { quem: "nota", texto: "Validação da lealdade, zero pressão, foco em segurança (assistência) e tempo. Com um S, 'só hoje' mata a venda." },
        ] },
        { tipo: "caso", titulo: "Caso: o engenheiro que 'não gostava' do vendedor", situacao: "Vendedor perfil I, simpático e falante, visitava o engenheiro da prefeitura de Guaçuí (perfil C) há meses. Contava casos, elogiava, levava café. O engenheiro respondia seco e nunca avançava.", acao: "Depois de estudar DISC, o vendedor mudou: levou um comparativo técnico de duas páginas com fontes, parou de elogiar, respondeu por e-mail em vez de WhatsApp e ofereceu uma visita técnica com o operador do município na máquina.", resultado: "Em 5 semanas o engenheiro escreveu o termo de referência com especificação que a RG140B atendia com folga. A relação nunca virou 'amizade' — e não precisava.", licao: "O C não 'não gosta de você'. Ele não confia em quem não traz dado. Adaptar não é fingir: é dar ao cliente o que ele precisa para decidir." },
        { tipo: "script", titulo: "Aberturas por perfil (primeiros 60 segundos)", itens: [
          "D: 'Vou ser direto: vim ver a obra pra te dizer se a máquina que você pediu preço é a certa ou se tem uma que produz mais pelo mesmo dinheiro. Vinte minutos.'",
          "I: 'Antes de falar de máquina, me conta como começou aqui — o Marcos, de Rio Novo, me disse que você foi o primeiro a asfaltar a estrada da cooperativa.'",
          "S: 'Sem pressa nenhuma hoje. Queria entender como vocês trabalham e o que dá dor de cabeça na frota. Se fizer sentido, a gente vê um próximo passo no seu tempo.'",
          "C: 'Trouxe os dados de consumo medidos em duas obras parecidas, com a fonte. Queria que você olhasse e me dissesse o que falta para uma comparação justa.'",
        ] },
        { tipo: "erros", titulo: "Erros clássicos de perfil", itens: [
          "Vendedor I com cliente C: fala demais, promete demais, envia áudio de 3 minutos. O C some.",
          "Vendedor D com cliente S: pressiona por decisão, usa 'só até sexta'. O S diz 'vou pensar' e nunca mais atende.",
          "Vendedor C com cliente D: apresentação de 40 minutos. O D corta na metade e compra de quem foi direto.",
          "Tratar o perfil como rótulo fixo: o mesmo dono é D na obra e S quando fala do dinheiro da família. Observe o momento.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Classifique os seus 10 clientes mais importantes por letra dominante. Para cada um, escreva em uma linha: ritmo (rápido/lento), profundidade (3 números/memória de cálculo/história/garantia) e argumento principal. Cadastre a letra nas observações do cliente no CRM." },
      ],
      missao: "Nas próximas cinco conversas (WhatsApp ou visita), identifique a letra dominante do cliente nos primeiros 3 minutos e ajuste conscientemente uma alavanca (ritmo, profundidade ou argumento). Anote no CRM a letra e o que mudou na reação do cliente.",
      quiz: [
        { pergunta: "O dono de uma pedreira olha o relógio, interrompe sua apresentação e diz 'me diz só quanto carrega por hora'. Qual é o comportamento mais eficaz?", opcoes: [
          "Responder o número na hora, acrescentar o segundo número que importa (revenda) e propor uma prova prática com data",
          "Explicar que produção por hora depende do material, do caminhão e do operador, e que a visita técnica vai medir",
          "Contar o caso de um cliente parecido antes de entrar em números, para criar conexão e reduzir a impaciência",
          "Pedir dois minutos para terminar o contexto, porque o dado sem contexto pode ser mal interpretado e virar comparação",
        ], correta: 0, explicacao: "Perfil D quer resultado, rapidez e ação. Número direto, um segundo dado curto e uma proposta de prova com data falam a língua dele. Pedir mais tempo, relativizar ou contar história são leituras de 'enrolação' para o D." },
        { pergunta: "Um empreiteiro familiar (perfil S) diz que sempre comprou da outra marca porque 'o pessoal de lá é conhecido'. A resposta que mais aumenta a chance de avançar é:", opcoes: [
          "Mostrar que a outra marca perdeu participação na região e que a assistência deles piorou, com dados de mercado",
          "Oferecer uma condição especial válida só esta semana para compensar o custo emocional de trocar de fornecedor",
          "Validar a lealdade, tirar a pressão, focar em segurança (assistência, quem atende) e propor voltar na semana seguinte",
          "Apresentar um comparativo técnico detalhado, com fontes, provando a superioridade da New Holland na aplicação dele",
        ], correta: 2, explicacao: "O S valoriza relação, segurança e tempo. Atacar o fornecedor antigo é atacar a lealdade dele; 'só esta semana' é pressão, que o S evita fugindo; comparativo técnico é linguagem de C. Validar, garantir assistência e dar tempo é o caminho." },
        { pergunta: "Você é comunicativo e gosta de contar casos. O engenheiro da prefeitura responde seco, pede tudo por escrito e nunca avança. O que provavelmente está acontecendo?", opcoes: [
          "Ele não tem autonomia real na compra; procure o secretário ou o prefeito e trate o engenheiro como formalidade",
          "Ele precisa de mais relacionamento pessoal; aumente a frequência das visitas e leve o técnico para um café",
          "Ele tem um fornecedor preferido e o termo de referência já está encaminhado; a conta não vale mais o tempo",
          "Ele é perfil C e não confia em quem traz simpatia em vez de dado; ajuste para comparativo com fontes e escrita",
        ], correta: 3, explicacao: "O perfil C desconfia de elogio e chute e confia em dado verificável. Não é antipatia nem direcionamento: é linguagem errada. Trocar áudio por e-mail, caso por comparativo com fonte e visita social por visita técnica costuma destravar. Pular o engenheiro para o prefeito costuma custar a conta." },
        { pergunta: "Qual é o erro de aplicação do DISC mais comum entre vendedores experientes?", opcoes: [
          "Achar que cliente de prefeitura é sempre C e cliente de pedreira é sempre D, decidindo o perfil pelo setor",
          "Usar o DISC só na primeira visita para escolher a abertura e esquecer o perfil nas reuniões seguintes",
          "Confundir o perfil do cliente com o próprio e vender do jeito que gostaria de comprar, sem perceber",
          "Tratar o perfil como rótulo fixo, quando a mesma pessoa muda de letra conforme o assunto (obra × dinheiro da família)",
        ], correta: 3, explicacao: "Todas são armadilhas, mas a mais sutil e frequente entre experientes é rotular: 'o Zé é D' e não perceber que o mesmo Zé vira S quando o assunto é financiar com a casa como garantia. O DISC descreve o comportamento do momento, não a pessoa inteira. Observe o momento." },
        { pergunta: "Um locador expansivo (perfil I) pergunta logo de quem você é e quem já comprou. Qual abertura aproveita melhor esse perfil?", opcoes: [
          "Entregar a ficha técnica e o comparativo de consumo logo na abertura, para demonstrar preparo e ganhar respeito",
          "Ir direto ao preço e à condição, porque quem pergunta 'quem já comprou' quer decidir rápido e sem rodeio",
          "Contar quem indicou, citar clientes conhecidos dele que compraram e deixar ele falar da própria história antes do produto",
          "Evitar conversa pessoal nos primeiros minutos para manter a postura profissional e não parecer vendedor 'amigo'",
        ], correta: 2, explicacao: "O I compra relação e reconhecimento. Prova social com nomes que ele conhece e espaço para ele contar a própria história constroem a ponte. Ficha técnica é para C; direto ao preço é para D; frieza afasta o I." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m2a3", titulo: "Aversão à perda, status quo e o custo da inação", minutos: 14,
      resumo: "Perder R$ 100 dói duas vezes mais do que ganhar R$ 100 alegra. O cliente não troca de máquina porque 'ficar como está' parece grátis. Seu trabalho é mostrar, com número, que ficar como está é a opção mais cara — sem teatro.",
      blocos: [
        { tipo: "p", texto: "Kahneman e Tversky mediram: a dor de uma perda é cerca de duas vezes maior que o prazer de um ganho equivalente. Por isso o cliente que 'está se virando' com a retro de 12 anos não compra a nova: trocar tem uma perda certa (a parcela) e um ganho incerto (produção). O viés do status quo faz a situação atual parecer segura e gratuita. O vendedor amador tenta vender o ganho ('a nova produz mais'). O consultor mostra a perda que já está acontecendo: cada mês com a máquina velha custa aluguel, diesel a mais, medição atrasada e operador parado. A inação tem preço — e ele é a sua maior alavanca." },
        { tipo: "conta", titulo: "O custo de ficar como está: retro de 12 anos × B95C nova (mês)", linhas: [
          ["Paradas: 3 dias/mês × aluguel de cobertura R$ 1.100/dia", "R$ 3.300"],
          ["Operador parado nos 3 dias (salário + encargos ÷ 22 dias × 3)", "R$ 750"],
          ["Consumo: 2,5 L/h a mais × 160 h × R$ 6,20", "R$ 2.480"],
          ["Manutenção corretiva média (histórico do cliente, 12 meses ÷ 12)", "R$ 2.900"],
          ["Multa/atraso de medição (1 a cada 4 meses, R$ 6.000 ÷ 4)", "R$ 1.500"],
          ["Custo mensal da inação", "R$ 10.930"],
          ["Parcela FINAME da B95C (60 meses, com a usada de entrada)", "R$ 8.700"],
        ], conclusao: "Ficar como está custa R$ 10.930 por mês. Trocar custa R$ 8.700 e ainda gera patrimônio (revenda) e produção maior. A 'opção grátis' é a mais cara — e o cliente só vê isso quando você soma na frente dele, com os números dele." },
        { tipo: "framework", nome: "Enquadre de perda em 4 passos", origem: "Teoria da perspectiva (Kahneman & Tversky) e Gap Selling (Keenan)", passos: [
          "Descubra a situação atual com número: dias parados, aluguel de cobertura, consumo, corretivas, atrasos — pergunte, não chute.",
          "Some o custo mensal da inação com o cliente segurando a calculadora (a Calculadora de custo/hora do CRM faz isso).",
          "Coloque a parcela da nova AO LADO do custo da inação, nunca sozinha. Sozinha ela é perda; ao lado, é economia.",
          "Projete 12 meses: 'em um ano, ficar como está custa R$ 131 mil — e você continua sem a máquina'. Deixe o silêncio trabalhar.",
        ] },
        { tipo: "dialogo", titulo: "De 'está se virando' a 'está perdendo'", falas: [
          { quem: "cliente", texto: "A minha retro tá velha, mas tá se virando. Não vejo motivo pra gastar 400 mil agora." },
          { quem: "vendedor", texto: "Entendo. Ela parou quantos dias no mês passado?" },
          { quem: "cliente", texto: "Uns três. Aluguei uma da locadora pra cobrir." },
          { quem: "vendedor", texto: "Mil e cem por dia, mais ou menos? Então foram R$ 3.300 só de aluguel. Mais o diesel a mais e a corretiva… posso somar aqui com você?" },
          { quem: "nota", texto: "Pergunta, não afirma. O número sai da boca do cliente — e o que o cliente diz, ele não discute." },
          { quem: "cliente", texto: "Dá quase 11 mil por mês? Eu não tinha somado." },
          { quem: "vendedor", texto: "Ninguém soma, porque vem picado. A parcela da nova, com a sua usada de entrada, fica em 8.700. Ou seja: você já paga a máquina nova todo mês, só não tem ela na obra. Quer que eu simule os 12 meses pra você mostrar pro seu irmão?" },
          { quem: "nota", texto: "'Você já paga a máquina nova, só não tem ela' é a frase que transforma status quo em perda. Depois, próximo passo com o segundo decisor." },
        ] },
        { tipo: "caso", titulo: "Caso: o consórcio que 'não era prioridade'", situacao: "Produtor de café em Iúna contratava terraplenagem de terceiros para o carreador todo ano, R$ 28 mil por safra, e 'não tinha pressa' de ter uma máquina própria.", acao: "O vendedor somou 5 anos de terceirização (R$ 140 mil), mais os dias em que o terceiro não veio na época certa e a colheita atrasou. Mostrou que uma B95C usada de 3 anos, via consórcio contemplado, custava menos que a terceirização e ainda prestava serviço para o vizinho.", resultado: "O produtor entrou no consórcio na mesma semana, deu lance com a venda de um caminhão parado e foi contemplado em 4 meses. Hoje presta serviço para três fazendas vizinhas.", licao: "Sem enquadre de perda, 'não é prioridade' vence sempre. Com o custo da inação somado em 5 anos, a mesma compra virou urgência." },
        { tipo: "destaque", titulo: "Ética do enquadre", texto: "Aversão à perda é poderosa — e por isso exige honestidade. Use os números reais do cliente, nunca inflados. Se a conta não fechar, diga: 'com esses números, mantém a sua máquina mais um ano e a gente conversa na safra que vem'. Esse cliente vai comprar de você quando fechar — e indicar." },
        { tipo: "erros", titulo: "Erros com aversão à perda", itens: [
          "Vender o ganho ('produz 20% a mais') sem antes mostrar a perda atual. O ganho é incerto; a parcela é certa; o cliente escolhe a certeza.",
          "Chutar os números do cliente. Se ele corrigir um, desconfia de todos.",
          "Fazer a conta em casa e mandar por WhatsApp. A soma tem que acontecer na frente dele, com ele falando os números.",
          "Usar 'escassez' falsa ('último da fábrica') para forçar a perda. Funciona uma vez e queima o nome.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escolha um cliente do CRM com máquina antiga. Sem falar com ele, monte a conta do custo da inação com os dados que você tem (ou estimativas marcadas como tal). Depois ligue e confirme cada número perguntando — e veja o quanto a estimativa errou. Corrija e guarde a versão do cliente." },
      ],
      missao: "Use a Calculadora de custo por hora do CRM com um cliente real, na frente dele, preenchendo os números que ele fala. Registre na negociação o custo mensal da inação e a parcela da nova lado a lado. Se a conta não fechar, registre isso também e uma data para reabrir.",
      quiz: [
        { pergunta: "O empreiteiro diz que a retro velha 'está se virando' e que não vê motivo para gastar agora. Qual abordagem tem mais chance de mover a decisão?", opcoes: [
          "Mostrar quanto a máquina nova produz a mais por hora, com a ficha técnica na mão, para o ganho ficar evidente",
          "Perguntar quantos dias ela parou no mês, quanto custou cobrir, e somar o custo mensal da inação com ele",
          "Explicar que a tabela sobe no mês que vem e que a janela de preço atual é o melhor momento para decidir",
          "Oferecer uma avaliação generosa da usada para a troca ficar atraente e o 'gastar agora' pesar menos",
        ], correta: 1, explicacao: "O cérebro pesa perdas duas vezes mais que ganhos. 'Produz mais' é ganho incerto; a parcela é perda certa. O que move é revelar a perda que já acontece, com números que o próprio cliente fala. Aumento de preço é pressão artificial; avaliação generosa é desconto disfarçado." },
        { pergunta: "Na conta do custo da inação, por que os números devem sair da boca do cliente e não da sua estimativa?", opcoes: [
          "Porque, se o cliente corrigir um número seu, ele desconfia de toda a conta; o que ele mesmo disse ele não discute",
          "Porque a fábrica exige que as simulações comerciais usem dados fornecidos e assinados pelo próprio cliente",
          "Porque perguntar demonstra humildade e escuta, e o cliente que se sente ouvido fica mais aberto à proposta",
          "Porque o vendedor não tem acesso aos dados reais de consumo e paradas, e qualquer estimativa seria um chute",
        ], correta: 0, explicacao: "A credibilidade da conta é a credibilidade da venda. Um chute errado contamina tudo. Quando o número é do cliente, a conclusão é dele também, e ele a defende para o sócio. Não é humildade nem regra de fábrica: é estratégia de convencimento." },
        { pergunta: "A conta mostrou custo da inação de R$ 6.000 por mês e a parcela da nova seria R$ 9.500. O que o consultor faz?", opcoes: [
          "Ajusta as premissas de consumo e paradas para cima, porque o cliente costuma subestimar o que a máquina velha custa",
          "Insiste na revenda e na garantia da nova para compensar a diferença de R$ 3.500 e sustentar a proposta",
          "Diz com honestidade que, com esses números, vale manter a máquina mais um tempo, e marca data para reabrir",
          "Sugere uma máquina de classe maior, que produz mais e gera receita suficiente para justificar a parcela",
        ], correta: 2, explicacao: "Aversão à perda é ferramenta de clareza, não de manipulação. Se a conta não fecha, forçar queima a confiança e gera uma venda arrependida. Dizer a verdade e agendar a reabertura constrói o cliente que compra depois e indica agora." },
        { pergunta: "Qual é o principal motivo pelo qual o 'status quo' vence tantas negociações de máquina?", opcoes: [
          "Ficar como está parece gratuito porque o custo vem picado (aluguel aqui, diesel ali) e ninguém soma",
          "Os clientes do interior são naturalmente conservadores e preferem o conhecido, mesmo quando custa mais",
          "As máquinas antigas realmente custam menos do que as parcelas das novas na maioria dos casos de uso leve",
          "Os concorrentes oferecem peças e manutenção baratas para manter a máquina antiga funcionando por mais tempo",
        ], correta: 0, explicacao: "O viés do status quo se apoia na invisibilidade do custo atual. Aluguel de cobertura, corretivas e diesel extra aparecem em contas separadas e meses diferentes. Quem soma na frente do cliente derruba a ilusão de gratuidade. Não é conservadorismo: é falta de soma." },
        { pergunta: "Por que a parcela da máquina nova nunca deve ser apresentada sozinha?", opcoes: [
          "Porque a parcela depende da aprovação de crédito e pode mudar, e apresentá-la sozinha cria uma expectativa falsa",
          "Porque, isolada, a parcela é lida como perda certa; ao lado do custo da inação vira economia",
          "Porque a política comercial recomenda apresentar o valor à vista primeiro e a parcela como alternativa",
          "Porque o cliente pode encaminhar a parcela ao concorrente e transformar a negociação em guerra de preço",
        ], correta: 1, explicacao: "A mesma parcela muda de significado conforme o enquadre. Sozinha: 'vou gastar R$ 8.700 por mês'. Ao lado do custo da inação: 'vou economizar R$ 2.200 por mês e ainda ter a máquina nova'. O enquadre é o trabalho do consultor." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m2a4", titulo: "Cialdini com ética: os seis princípios na venda de máquina", minutos: 14,
      resumo: "Prova social, reciprocidade, autoridade, escassez, coerência e afinidade. Cada princípio tem uma versão honesta que fecha venda e uma versão barata que queima reputação no interior em uma semana.",
      blocos: [
        { tipo: "p", texto: "Robert Cialdini passou três anos infiltrado em equipes de vendas para descobrir por que as pessoas dizem sim. Encontrou seis princípios universais. Eles funcionam porque são atalhos do Sistema 1: quando não dá para analisar tudo, a gente segue quem é parecido, retribui favor, obedece quem sabe, quer o que é raro, mantém a coerência com o que já disse e diz sim para quem gosta. No sul do ES, onde todo mundo conhece todo mundo, a versão ética desses princípios é a mais forte que existe — e a versão manipuladora é a mais cara." },
        { tipo: "tabela", titulo: "Seis princípios: a versão ética e a versão barata", colunas: ["Princípio", "Versão ética (funciona por anos)", "Versão barata (funciona uma vez)"], linhas: [
          ["Prova social", "'A Terraplenagem Rio Novo tem duas E215C; liga pro Marcos e pergunta do consumo'", "'Todo mundo tá comprando' sem nome nem contato"],
          ["Reciprocidade", "Visita técnica na obra, avaliação gratuita da usada, dica de licitação — antes de pedir algo", "Brinde para 'amolecer' na hora do desconto"],
          ["Autoridade", "Saber a aplicação, medir a obra, citar a norma da prefeitura, trazer o técnico da assistência", "Falar difícil, exagerar a ficha técnica, 'sou o melhor da região'"],
          ["Escassez", "'Tenho duas na fábrica com entrega em 20 dias; depois disso é 60' — verdade verificável", "'Último da fábrica, só até sexta' toda semana"],
          ["Coerência", "'Você me disse que o que mais pesa é parada. Essa máquina resolve parada. Faz sentido seguir?'", "Fazer o cliente dizer 'sim' a perguntas bobas para 'aquecer'"],
          ["Afinidade", "Interesse genuíno pela obra, elogio específico e verdadeiro, pontualidade, lembrar do que ele contou", "Elogio vazio, 'amigo' na terceira mensagem, forçar intimidade"],
        ] },
        { tipo: "framework", nome: "Prova social que fecha: o método NNC", origem: "Cialdini (As Armas da Persuasão) — prova social é mais forte quando é de gente parecida", passos: [
          "Nome: cite um cliente com nome e empresa (com autorização) — 'o Marcos, da Rio Novo'. Sem nome não é prova, é slogan.",
          "Nicho e vizinhança: o cliente parecido (mesma aplicação, mesma cidade ou vizinha) pesa 10x mais que uma grande construtora de São Paulo.",
          "Contato: ofereça o telefone. Cliente que pode ligar raramente liga — mas o fato de poder é o que convence.",
          "Mantenha uma lista viva de 10 referências por nicho (café, pedreira, prefeitura, locação, terraplenagem) e cuide delas no pós-venda: referência mal atendida vira antipropaganda.",
        ] },
        { tipo: "dialogo", titulo: "Reciprocidade de verdade", falas: [
          { quem: "vendedor", texto: "Seu Jorge, vi no Diário Oficial que Muniz Freire abriu pregão pra pavimentação. Você faz esse serviço, né? Te mandei o edital. O prazo de proposta é dia 28." },
          { quem: "cliente", texto: "Opa, não tinha visto. Valeu mesmo." },
          { quem: "nota", texto: "Valor entregue sem pedir nada. Isso é reciprocidade: o cliente sente a vontade de retribuir — e, quando precisar de máquina, lembra de quem ajudou." },
          { quem: "cliente", texto: "(duas semanas depois) Ganhei o pregão. Vou precisar de um rolo. Você tem?" },
          { quem: "vendedor", texto: "Tenho um CA2500 pra entrega em 15 dias. Antes de falar de preço: qual a espessura da camada e quantos km? Isso muda o rolo certo." },
          { quem: "nota", texto: "O cliente chegou sozinho. Repare: mesmo assim o vendedor diagnostica antes de precificar." },
        ] },
        { tipo: "caso", titulo: "Caso: a escassez que virou piada", situacao: "Vendedor de concorrente usava 'último da fábrica, só até sexta' em toda proposta. Os empreiteiros de Cachoeiro trocavam prints entre si no grupo da associação.", acao: "Nosso vendedor fez o oposto: informava a fila de produção real ('tenho 2 com entrega em 20 dias, a próxima leva 60') e, quando não tinha, dizia 'não tenho pra esse prazo, mas consigo uma usada revisada'.", resultado: "Em um ano, três clientes citaram espontaneamente 'com você eu sei que a informação é de verdade' como motivo de compra. O concorrente virou apelido no grupo.", licao: "No interior, a escassez falsa é descoberta em dias. A verdadeira — informada com precisão — é uma das ferramentas mais fortes que você tem." },
        { tipo: "script", titulo: "Coerência sem manipulação: fechando com o que o cliente disse", itens: [
          "'Você me falou que o que mais dói é a parada, mais do que o preço. Essa máquina tem assistência a 40 km e disponibilidade acima de 95%. Faz sentido a gente seguir?'",
          "'Na primeira conversa você disse que queria ter a máquina antes da chuva. A entrega em 20 dias cumpre isso. O que falta para decidir?'",
          "'Você me disse que o seu sócio olha a parcela × faturamento. A parcela ficou em 22% do faturamento da obra. Está dentro do que ele considera?'",
        ] },
        { tipo: "erros", titulo: "Erros que queimam o nome", itens: [
          "Prova social sem nome: 'muita gente compra' é ruído; 'o Marcos comprou' é prova.",
          "Reciprocidade com condição: 'te fiz a avaliação de graça, agora fecha' — o favor deixa de ser favor.",
          "Autoridade emprestada: 'a fábrica diz que…' sem saber explicar. Perfil C testa e derruba.",
          "Afinidade forçada: chamar de amigo no terceiro contato, elogio genérico ('que obra linda') — soa a vendedor.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte a sua lista de referências: 2 clientes por nicho (café, pedreira, prefeitura, locação, terraplenagem, construtora) com nome, máquina, ano de compra e telefone — e peça a autorização de cada um para citá-los. Cadastre como observação no CRM. Sem essa lista, sua prova social é slogan." },
      ],
      missao: "Entregue valor antes de pedir, para três clientes do funil, esta semana: um edital do Diário Oficial, uma avaliação da usada, uma informação de fila de produção ou uma dica técnica. Registre no CRM o que entregou e a reação. Não peça nada em troca nesta semana.",
      quiz: [
        { pergunta: "Qual das formas de prova social tem mais peso para um empreiteiro de Alegre que está em dúvida entre a B110B e uma concorrente?", opcoes: [
          "O depoimento por escrito de um cliente satisfeito na proposta comercial, com a frase dele e a máquina comprada",
          "Um vídeo institucional da fábrica mostrando a máquina em operação numa grande obra, com dados de produção",
          "A informação de que a New Holland é líder de vendas de retroescavadeira no Brasil há vários anos seguidos",
          "O nome e o telefone de um empreiteiro de Guaçuí que comprou a mesma máquina há dois anos para o mesmo serviço",
        ], correta: 3, explicacao: "Cialdini mostra que a prova social é mais forte quando vem de gente parecida e próxima. Nome, cidade vizinha, mesma aplicação e contato verificável derrotam liderança nacional e vídeo de fábrica. Depoimento sem nome não é prova: é slogan." },
        { pergunta: "Você fez uma avaliação gratuita da usada do cliente e, na hora de negociar o preço, ele pede desconto. Qual uso da reciprocidade é ético e eficaz?", opcoes: [
          "Lembrar com leveza que a avaliação foi de graça e que agora é a vez dele de ceder um pouco na negociação",
          "Não mencionar o favor; a reciprocidade age sozinha, e a negociação se apoia em valor e condições",
          "Oferecer outro favor (frete, brinde, revisão) para aumentar a dívida psicológica antes de responder ao desconto",
          "Informar que a avaliação será cobrada caso ele não feche, deixando isso claro na proposta para valorizar o serviço",
        ], correta: 1, explicacao: "Reciprocidade funciona porque o favor foi genuíno. No momento em que você cobra, ele deixa de ser favor e vira troca, e a boa vontade evapora. O princípio já trabalhou em silêncio; a negociação deve se apoiar em valor (módulo 6), não em 'você me deve'." },
        { pergunta: "O que diferencia a escassez ética da escassez manipuladora na venda de máquinas?", opcoes: [
          "A ética é verificável e específica (fila de produção real, unidades); a manipuladora é vaga, repetida e não se confirma",
          "A ética é comunicada por escrito na proposta; a manipuladora é dita por telefone ou WhatsApp, sem registro",
          "Não há diferença prática: escassez sempre pressiona e deve ser evitada em qualquer venda consultiva séria",
          "A ética usa prazos maiores, compatíveis com a decisão; a manipuladora usa prazos curtos como 'até sexta'",
        ], correta: 0, explicacao: "Escassez é um dos gatilhos mais fortes e, quando verdadeira, é informação útil ao cliente (ele precisa saber se a entrega cabe no prazo da obra). O problema não é o prazo curto nem o canal: é a mentira, que no interior é descoberta em dias e destrói a confiança." },
        { pergunta: "Você é vendedor há dois meses e o cliente pergunta algo técnico que você não sabe. Qual conduta preserva a autoridade?", opcoes: [
          "Mudar de assunto para a condição comercial, onde você domina o tema, e retomar o ponto técnico na proposta escrita",
          "Dizer que 'a fábrica garante' aquele ponto e seguir a apresentação, porque o cliente confia mais na marca que no vendedor",
          "Dizer que vai confirmar com o técnico da assistência e voltar com a resposta em hora combinada, e cumprir",
          "Responder com o que parece mais provável, com segurança, porque hesitar na frente do cliente passa despreparo",
        ], correta: 2, explicacao: "Autoridade, para Cialdini, é competência percebida e honestidade. 'Vou confirmar e volto às 14h' e cumprir constrói mais autoridade do que um chute que o perfil C vai testar. Autoridade emprestada ('a fábrica garante') sem explicação derruba a credibilidade." },
        { pergunta: "Como usar o princípio da coerência sem cair na manipulação de 'fazer o cliente dizer sim a perguntas bobas'?", opcoes: [
          "Fazer três perguntas fáceis de resposta positiva no início da reunião, para criar clima e ritmo de concordância",
          "Evitar totalmente o princípio, porque qualquer uso de coerência é manipulação e o cliente percebe",
          "Pedir ao cliente que assine uma carta de intenção antes de ver a proposta, formalizando o compromisso",
          "Retomar critérios que o próprio cliente definiu ('você disse que o que mais pesa é a parada') e checar se a solução atende",
        ], correta: 3, explicacao: "Coerência ética é lembrar o cliente do que ele mesmo priorizou e verificar se a proposta cumpre. É diagnóstico bem feito virando fechamento. Perguntas bobas para 'aquecer' são percebidas como truque; carta de intenção antes da proposta é pressão." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m2a5", titulo: "Confiança rápida: rótulos, espelhamento e perguntas calibradas", minutos: 15,
      resumo: "Chris Voss negociava com sequestradores. As ferramentas dele — rotular a emoção, espelhar as últimas palavras, perguntar 'como' em vez de 'por quê' — fazem o cliente sentir-se entendido em minutos. Cliente que se sente entendido conta a verdade. E a verdade é o que você precisa para vender.",
      blocos: [
        { tipo: "p", texto: "Confiança não se pede; se constrói com sinais que o Sistema 1 do cliente lê sem perceber: você entendeu o que eu disse? Você está me julgando? Você tem pressa de me vender? Chris Voss, ex-negociador do FBI, sistematizou técnicas de empatia tática que respondem a essas perguntas em segundos. Elas não são truques: são maneiras de ouvir de verdade e mostrar que ouviu. Na obra, com um empreiteiro cansado de vendedor, isso vale mais que qualquer argumento." },
        { tipo: "framework", nome: "Empatia tática (Voss)", origem: "Chris Voss — Negocie como se sua vida dependesse disso (FBI)", passos: [
          "Espelhamento: repita as 2–3 últimas palavras do cliente em tom de pergunta e cale-se. 'A chinesa é 90 mil a menos.' — 'Noventa mil a menos?' Ele explica, e você descobre o que está por trás.",
          "Rótulo: nomeie a emoção sem dizer 'eu entendo'. 'Parece que você ficou queimado com a última máquina que comprou.' Se acertar, ele confirma e alivia; se errar, ele corrige — e você aprende.",
          "Pergunta calibrada: troque 'por quê' (acusa) por 'como' e 'o quê' (convida). 'Como você vê o pagamento cabendo no caixa?' 'O que precisaria acontecer para fazer sentido?'",
          "Acuse-se antes (accusation audit): liste o que ele deve estar pensando de você. 'Você deve estar achando que vendedor só quer empurrar máquina.' Desarma antes de começar.",
          "O 'não' que abre: 'Seria loucura pensar em trocar a máquina esse ano?' — dizer 'não' dá controle ao cliente e o faz falar.",
        ] },
        { tipo: "dialogo", titulo: "Cliente queimado com a marca anterior", falas: [
          { quem: "cliente", texto: "Já comprei máquina nova uma vez. Ficou 40 dias parada esperando peça. Nunca mais." },
          { quem: "vendedor", texto: "Quarenta dias parada?" },
          { quem: "nota", texto: "Espelhamento. Sem 'entendo', sem defender a marca. Só devolve e espera." },
          { quem: "cliente", texto: "Quarenta. A assistência ficava em Vitória, o técnico vinha uma vez por semana. Perdi uma obra por causa disso." },
          { quem: "vendedor", texto: "Parece que o problema não foi a máquina. Foi ter ficado sozinho com ela parada, sem ninguém dando resposta." },
          { quem: "nota", texto: "Rótulo. Nomeia a emoção (abandono) e separa a máquina da assistência." },
          { quem: "cliente", texto: "Exatamente isso. Ninguém me ligava." },
          { quem: "vendedor", texto: "Faz sentido você não querer passar por isso de novo. Como seria uma assistência que te deixaria tranquilo? O que precisaria ter?" },
          { quem: "nota", texto: "Pergunta calibrada com 'como' e 'o que'. O cliente vai descrever a solução — e o vendedor só precisa mostrar o que da assistência local atende a isso." },
        ] },
        { tipo: "tabela", titulo: "Troque a pergunta que fecha pela que abre", colunas: ["Pergunta que fecha (evite)", "Pergunta calibrada (use)"], linhas: [
          ["Por que você não fechou com a gente da outra vez?", "O que faltou da outra vez para fazer sentido?"],
          ["Você tem orçamento para isso?", "Como você costuma encaixar um investimento desse no caixa?"],
          ["Vai fechar essa semana?", "O que precisa acontecer do seu lado para a gente avançar?"],
          ["O preço é o problema?", "O que, além do valor, está pesando na decisão?"],
          ["Posso te ligar amanhã?", "Como fica melhor pra você: te ligo amanhã às 9h ou passo na obra na quinta?"],
        ] },
        { tipo: "caso", titulo: "Caso: o 'não' que virou visita", situacao: "Prospect de Mimoso do Sul não respondia a mensagens de 'posso te apresentar a linha?' há três semanas.", acao: "O vendedor mudou a mensagem: 'Seu Paulo, seria loucura pensar em trocar a pá-carregadeira antes da safra?' Em 20 minutos veio a resposta: 'Loucura não, mas o dinheiro tá curto'. O vendedor rotulou: 'Parece que o problema não é a máquina, é o caixa nessa época'. Resposta: 'É isso. Se fosse depois da colheita…'.", resultado: "Visita marcada para o mês seguinte com o consórcio como caminho. Fechou na safra seguinte.", licao: "Pergunta que exige 'sim' é pressão; pergunta que permite 'não' devolve o controle ao cliente. E controle gera conversa." },
        { tipo: "script", titulo: "Rótulos prontos para o seu mercado", itens: [
          "'Parece que você já ouviu muita promessa de vendedor e quer ver na prática.'",
          "'Dá a impressão de que o que mais te preocupa não é o preço, é ficar na mão se quebrar.'",
          "'Parece que trocar de marca depois de tantos anos não é uma decisão só sua.'",
          "'Sinto que você está ponderando se é o momento certo, com a obra nova ainda não confirmada.'",
        ] },
        { tipo: "erros", titulo: "Erros de escuta", itens: [
          "Dizer 'eu entendo' e emendar um argumento. 'Entendo' sem rótulo é sinal de que você não ouviu.",
          "Perguntar 'por quê': soa a acusação e coloca o cliente na defensiva.",
          "Preencher o silêncio. Depois do espelhamento ou do rótulo, cale-se por 4 segundos. Quem fala primeiro entrega informação.",
          "Rotular e discutir o rótulo. Se ele corrigir ('não é bem isso'), agradeça e pergunte 'o que é, então?'.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Reescreva as cinco últimas mensagens de WhatsApp que você enviou pedindo uma decisão ao cliente. Troque cada pergunta de 'sim' por uma pergunta calibrada ('como', 'o que') ou por uma pergunta orientada a 'não'. Envie a versão nova para o próximo cliente que estiver em silêncio." },
      ],
      missao: "Em três conversas esta semana, use pelo menos um espelhamento e um rótulo antes de apresentar qualquer argumento. Depois, registre na negociação do CRM o que o cliente revelou que você não sabia (objeção real, decisor oculto, prazo).",
      quiz: [
        { pergunta: "O cliente diz: 'Já comprei máquina nova uma vez, ficou 40 dias parada esperando peça. Nunca mais.' Qual resposta aplica melhor a empatia tática?", opcoes: [
          "'Entendo perfeitamente, mas a nossa assistência é diferente: temos técnico em Cachoeiro e estoque de peças'",
          "'Quarenta dias parada?', seguido de silêncio, esperando ele contar o que aconteceu",
          "'Por que você não acionou a garantia na época? Isso é responsabilidade da fábrica, não do cliente'",
          "'Isso é raro de acontecer; deve ter sido um problema específico daquela marca ou daquele modelo'",
        ], correta: 1, explicacao: "Espelhar as últimas palavras e calar-se faz o cliente contar a história inteira, e nela está o que ele realmente teme (abandono, não a máquina). 'Entendo, mas…' anula a escuta; 'por quê' acusa; minimizar ('é raro') invalida a experiência dele." },
        { pergunta: "Qual é a diferença essencial entre 'Por que você não fechou com a gente da outra vez?' e 'O que faltou da outra vez para fazer sentido?'", opcoes: [
          "A primeira é mais direta e funciona melhor com perfil D; a segunda é mais suave e serve para perfil S",
          "Não há diferença relevante; ambas buscam a mesma informação e o cliente responde conforme o humor do dia",
          "A primeira soa como acusação e coloca o cliente na defensiva; a segunda convida a explicar e dá controle a ele",
          "A segunda é mais longa e por isso menos eficaz no WhatsApp, onde perguntas curtas recebem mais resposta",
        ], correta: 2, explicacao: "Voss mostra que 'por quê' é lido como cobrança em qualquer idioma. 'O que' e 'como' pedem ajuda para resolver, e o cliente responde com informação em vez de justificativa. Vale para todos os perfis, inclusive o D." },
        { pergunta: "Você rotula: 'Parece que o que mais te preocupa é ficar na mão se quebrar'. O cliente responde: 'Não é bem isso'. O que fazer?", opcoes: [
          "Insistir no rótulo com outro exemplo concreto, porque o cliente costuma negar a emoção na primeira vez",
          "Pedir desculpas pela suposição e voltar para a apresentação do produto, sem forçar a conversa emocional",
          "Trocar para um argumento de preço, já que a preocupação não é assistência e o valor é o que sobra",
          "Agradecer a correção e perguntar 'o que é, então?', deixando o cliente definir a preocupação real",
        ], correta: 3, explicacao: "Um rótulo errado é uma oportunidade: o cliente corrige e revela a verdade. Insistir vira discussão; pedir desculpas e mudar de assunto perde a informação; pular para preço é chute. 'O que é, então?' é a pergunta calibrada que completa a técnica." },
        { pergunta: "Um prospect não responde há três semanas a mensagens do tipo 'posso te apresentar a linha?'. Qual mensagem tem mais chance de reabrir a conversa?", opcoes: [
          "'Seria loucura pensar em trocar a máquina antes da safra?'",
          "'Última tentativa: ainda tem interesse ou posso encerrar o contato por aqui?'",
          "'Consegui uma condição especial que vale só esta semana. Posso te explicar?'",
          "'Bom dia! Só passando para saber se teve chance de ver a apresentação'",
        ], correta: 0, explicacao: "Pergunta orientada a 'não' devolve o controle ao cliente e é fácil de responder; ele responde 'não é loucura, mas…' e a conversa reabre com a objeção real. 'Só passando' é cobrança disfarçada; 'última tentativa' é ultimato; 'condição só esta semana' é escassez barata." },
        { pergunta: "Depois de um espelhamento ou de um rótulo, qual é a conduta correta do vendedor?", opcoes: [
          "Explicar imediatamente por que a New Holland resolve aquele problema, aproveitando a abertura que o rótulo criou",
          "Ficar em silêncio alguns segundos e deixar o cliente preencher; quem fala primeiro entrega informação",
          "Fazer uma segunda pergunta logo em seguida para manter o ritmo da conversa e não deixar o clima esfriar",
          "Anotar a objeção e mudar de assunto para não pressionar, retomando o ponto na proposta escrita",
        ], correta: 1, explicacao: "O silêncio é parte da técnica. O rótulo abre a porta; o silêncio convida o cliente a atravessá-la. Emendar argumento ou pergunta fecha a porta de novo. Quatro segundos de silêncio são desconfortáveis para o vendedor e produtivos para a venda." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m2a6", titulo: "História vende, planilha justifica: storytelling na obra", minutos: 13,
      resumo: "O cérebro lembra de histórias 20 vezes mais do que de dados soltos. Uma história de cliente parecido, contada em 60 segundos, ancora a decisão. A conta vem depois e dá ao cliente a justificativa para o que ele já quer fazer.",
      blocos: [
        { tipo: "p", texto: "Jerome Bruner, psicólogo de Harvard, estimou que um fato embalado em história é lembrado até 22 vezes mais do que o fato sozinho. Não é por acaso que o empreiteiro lembra do 'caso do Marcos que perdeu uma obra com a máquina parada' e esquece a tabela de disponibilidade. Histórias falam com o Sistema 1: têm personagem parecido com o cliente, um problema que ele reconhece, uma decisão e um resultado. O consultor tem um repertório de 10 histórias reais, uma por situação — e sabe contar cada uma em um minuto, sem enfeite." },
        { tipo: "framework", nome: "História de cliente em 4 tempos (60 segundos)", origem: "Estrutura clássica de narrativa aplicada a vendas (Paul Smith, Lead with a Story)", passos: [
          "Personagem parecido: 'O Marcos, de Rio Novo, faz rede de água pra prefeitura igual você' — o cliente precisa se ver na história.",
          "Problema reconhecível: 'A retro dele parava 3 dias por mês e ele alugava pra cobrir. Perdeu uma medição por causa disso.'",
          "Decisão e obstáculo: 'Ele achou a B110B cara. A gente fez a conta juntos e ele viu que já pagava a máquina nova em aluguel. Entrou com a usada e o FINAME.'",
          "Resultado concreto e verificável: 'Dois anos, 3.400 horas, nenhuma medição atrasada. Se quiser ligar pra ele, eu passo o número.' — o número no fim devolve a história ao Sistema 2.",
        ] },
        { tipo: "dialogo", titulo: "História primeiro, conta depois", falas: [
          { quem: "cliente", texto: "Vocês são mais caros que a Case. Por que eu pagaria mais?" },
          { quem: "vendedor", texto: "Deixa eu te contar o que aconteceu com o Roberto, da pedreira de Vargem Alta. Ele fez a mesma pergunta há dois anos e comprou a mais barata. Seis meses depois, a máquina parou na safra da pedreira, e a assistência mais perta ficava a 180 km. Ficou 11 dias sem carregar caminhão. Ele mesmo me chamou depois e comprou a W170B. Hoje ele diz que a diferença de preço ele pagou em duas semanas de máquina parada." },
          { quem: "nota", texto: "Personagem parecido, problema reconhecível, obstáculo (preço), resultado. Sessenta segundos. Sem falar mal da Case: a história fala." },
          { quem: "cliente", texto: "E quanto foi essa diferença, na prática?" },
          { quem: "vendedor", texto: "Boa pergunta — é a conta que o Roberto fez. Posso te mostrar com os seus números? Quantas toneladas por dia você carrega?" },
          { quem: "nota", texto: "A história abriu a porta para o Sistema 2: o cliente PEDIU a conta. Agora a planilha entra como justificativa, não como argumento." },
        ] },
        { tipo: "tabela", titulo: "Repertório mínimo: 8 histórias que todo consultor precisa ter", colunas: ["Situação", "A história que você precisa ter pronta"], linhas: [
          ["'Tá caro / a chinesa é mais barata'", "Cliente que comprou o mais barato e pagou a diferença em máquina parada"],
          ["'Vou pensar / não é o momento'", "Cliente que adiou e perdeu a safra/obra, ou que decidiu e ganhou o contrato"],
          ["'Sempre comprei da outra marca'", "Cliente fiel a outra marca que testou uma e trocou a frota aos poucos"],
          ["'O banco não aprova'", "Cliente que fechou via consórcio com lance ou com a usada de entrada"],
          ["'Não conheço a assistência'", "Chamado atendido em X horas, com nome do técnico e do cliente"],
          ["Prefeitura / licitação", "Município que especificou bem e recebeu máquina que durou; ou o inverso"],
          ["'Vou alugar em vez de comprar'", "Locatário que somou 18 meses de aluguel e viu que já tinha pago uma usada"],
          ["Pós-venda / indicação", "Cliente que indicou três vizinhos depois da entrega técnica bem feita"],
        ] },
        { tipo: "caso", titulo: "Caso: a história que o cliente contou de volta", situacao: "Vendedor contou ao dono de uma locadora em Cachoeiro a história do Roberto (pedreira, máquina parada 11 dias). Não fechou naquele dia.", acao: "Três meses depois, ao visitar de novo, ouviu o próprio cliente contando a história do Roberto para o sócio, com os detalhes certos, como argumento para comprar a New Holland.", resultado: "Fechou duas W130B. O sócio nunca viu uma planilha: viu a história, e a planilha depois só confirmou.", licao: "Uma boa história é o argumento que o cliente leva para dentro da empresa e conta por você quando você não está lá." },
        { tipo: "destaque", titulo: "Regras da história honesta", texto: "Só conte o que aconteceu. Peça autorização para usar nomes. Inclua o obstáculo (o cliente também achou caro, também teve dúvida) — história sem obstáculo é propaganda. Termine com um número verificável e a oferta de contato. E nunca conte a mesma história duas vezes para o mesmo cliente." },
        { tipo: "erros", titulo: "Erros de quem 'conta caso'", itens: [
          "História longa: mais de 90 segundos vira palestra. Corte para o essencial.",
          "Personagem diferente do cliente: grande construtora de São Paulo não convence produtor de café de Iúna.",
          "História sem número no fim: fica no Sistema 1 e não sobrevive ao sócio.",
          "Inventar ou 'melhorar' detalhes. No interior, o cliente conhece o personagem — e vai checar.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escreva as suas 8 histórias (tabela acima) no formato de 4 tempos, cada uma em até 80 palavras, com nome (autorizado), problema, obstáculo, resultado numérico. Grave-se contando cada uma em voz alta com cronômetro: nenhuma pode passar de 60 segundos. Guarde no celular." },
      ],
      missao: "Na próxima vez que ouvir 'está caro', responda primeiro com uma história de cliente parecido em até 60 segundos e só depois ofereça a conta. Registre na negociação do CRM qual história usou e se o cliente pediu a conta em seguida.",
      quiz: [
        { pergunta: "O cliente pergunta 'por que eu pagaria mais do que na Case?'. Qual sequência tem mais poder de convencimento?", opcoes: [
          "Abrir o comparativo técnico e mostrar as diferenças de motor, hidráulico e garantia, item por item, com fontes",
          "Explicar os diferenciais da assistência local e da rede de peças, que são o que pesa no custo total da máquina",
          "Contar em 60 segundos a história de um cliente parecido que comprou o mais barato e pagou em máquina parada; depois a conta",
          "Perguntar qual foi o preço da Case e o que está incluso, para poder igualar ou justificar a diferença com precisão",
        ], correta: 2, explicacao: "A história fala com o Sistema 1 e faz o cliente se ver na situação; ela abre a porta para ele PEDIR a conta, que então entra como justificativa. Comparativo e lista de diferenciais são argumentos que o cérebro esquece; perguntar o preço da Case transforma a conversa em leilão." },
        { pergunta: "Por que uma história de cliente precisa incluir o obstáculo (ele também achou caro, também teve dúvida)?", opcoes: [
          "Porque sem obstáculo a história soa a propaganda e o cliente não se reconhece nela",
          "Porque o obstáculo torna a história mais longa e detalhada, e histórias longas são mais memoráveis",
          "Porque a política comercial recomenda apresentar riscos junto com benefícios em qualquer material",
          "Porque o obstáculo permite introduzir o desconto como solução no fim da história, fechando o ciclo",
        ], correta: 0, explicacao: "Histórias funcionam por identificação. O cliente que está achando caro se reconhece no personagem que também achou caro e mesmo assim decidiu. História só de glória é propaganda, e o Sistema 1 a rejeita como rejeita o comercial de TV." },
        { pergunta: "Qual é o papel do número no fim da história ('dois anos, 3.400 horas, nenhuma medição atrasada')?", opcoes: [
          "Comparar indiretamente com a concorrência sem citar nomes, mostrando a durabilidade pela quantidade de horas",
          "Substituir a necessidade de apresentar a conta depois, porque o número já prova o resultado",
          "Impressionar o cliente com a durabilidade da máquina e a experiência acumulada do vendedor",
          "Devolver a história ao Sistema 2, dando ao cliente algo verificável para levar ao sócio",
        ], correta: 3, explicacao: "A história ancora a emoção; o número no fim é a ponte para a razão. Sem ele, a história fica no 'gostei' e morre na conversa com o sócio. O número não substitui a conta: ele faz o cliente pedi-la." },
        { pergunta: "Um produtor de café de Iúna ouve a história de uma grande construtora de São Paulo que comprou 12 escavadeiras. Qual o efeito mais provável?", opcoes: [
          "Forte: mostra que empresas grandes confiam na marca, o que tranquiliza o produtor pequeno na decisão",
          "Fraco: o personagem não se parece com ele e a história não gera identificação; um vizinho de Iúna pesaria mais",
          "Neutro: histórias funcionam só com perfil I; produtores rurais são em geral perfil S e preferem garantia",
          "Negativo: o produtor conclui que a marca é para grandes frotas e que ele não receberá atenção depois da venda",
        ], correta: 1, explicacao: "Prova social e história dependem de semelhança. O cérebro do produtor pergunta 'isso aconteceu com alguém como eu?'. Doze escavadeiras em São Paulo não respondem. Um vizinho com uma B95C no carreador responde. Perfil não anula isso: todos os perfis se identificam com gente parecida." },
        { pergunta: "Você contou a história do Roberto para o dono da locadora há três meses. Na visita seguinte, o que indica que a história funcionou?", opcoes: [
          "O cliente pede a planilha comparativa que você tinha oferecido na primeira visita, sinal de interesse ativo",
          "O cliente lembra do nome da máquina, do modelo e do preço apresentado três meses antes, sem consultar nada",
          "O cliente pergunta sobre condições de financiamento e prazo de entrega logo no início da conversa",
          "O cliente conta a história do Roberto para o sócio, com os detalhes certos, como argumento próprio",
        ], correta: 3, explicacao: "O sinal máximo de uma história eficaz é ser reproduzida pelo cliente para outro decisor. Ela virou argumento dele, e argumento próprio não se discute. Pedir planilha ou financiamento são sinais positivos, mas indicam interesse, não a apropriação da narrativa." },
      ],
    },
  ],
  prova: [
    { pergunta: "Um cliente decidiu emocionalmente pela máquina, mas o sócio (que não estava na visita) vetou por 'não fechar a conta'. Qual erro do vendedor mais provavelmente causou isso?", opcoes: [
      "Não ter identificado o sócio como o Sistema 2 da decisão e não ter preparado os três números que ele pediria",
      "Ter deixado o cliente testar a máquina antes de discutir preço, criando entusiasmo sem base financeira",
      "Ter falado de financiamento antes de fechar o valor à vista, o que confundiu a conta apresentada ao sócio",
      "Não ter apresentado o comparativo completo com a concorrência, que daria ao cliente argumentos para o sócio",
    ], correta: 0, explicacao: "A venda tem dois momentos: a preferência (Sistema 1, do cliente) e a ratificação (Sistema 2, muitas vezes de outra pessoa). Quem não mapeia o ratificador e não prepara parcela, custo/hora e referência para ele perde a venda depois do 'sim'." },
    { pergunta: "Qual perfil DISC tende a reagir pior a 'condição válida só até sexta'?", opcoes: [
      "D (Dominante), porque não aceita ser pressionado e reage rompendo a negociação na hora",
      "I (Influente), porque prefere conversar mais antes de decidir e sente o prazo como frieza",
      "S (Estável), porque evita pressão e mudança brusca, e responde fugindo ('vou pensar')",
      "C (Conforme), porque desconfia de qualquer prazo sem justificativa técnica por escrito",
    ], correta: 2, explicacao: "O S valoriza segurança e tempo; pressão explícita o faz recuar e sumir. O D pode até responder bem a um prazo real; o I negocia; o C pede a justificativa do prazo. Com o S, 'só até sexta' costuma encerrar a conversa." },
    { pergunta: "O que faz o 'status quo' parecer gratuito para o cliente com máquina antiga?", opcoes: [
      "O custo da situação atual vem picado em contas separadas e ninguém soma",
      "As máquinas antigas já estão pagas e por isso não geram parcela, o que o cliente lê como custo zero",
      "Os clientes preferem não saber quanto gastam com manutenção para não se sentirem obrigados a trocar",
      "O vendedor da marca antiga mantém o cliente informado e tranquilo sobre os custos de manutenção",
    ], correta: 0, explicacao: "Aluguel de cobertura num mês, corretiva noutro, diesel a mais todo dia: nada disso aparece somado. O viés do status quo vive dessa invisibilidade. A soma feita na frente do cliente, com os números dele, é o antídoto." },
    { pergunta: "Um vendedor apresenta a parcela de R$ 9.800 da máquina nova e o cliente recua. Qual correção de enquadre é a mais eficaz?", opcoes: [
      "Alongar o prazo do financiamento de 48 para 72 meses, para a parcela cair e caber no caixa",
      "Apresentar o valor à vista com desconto, que parece menor do que a soma das parcelas",
      "Colocar a parcela ao lado do custo mensal da inação calculado com os números do cliente",
      "Explicar que a parcela é dedutível no imposto de renda da empresa e que o custo real é menor",
    ], correta: 2, explicacao: "Sozinha, a parcela é perda certa. Ao lado do custo da inação (aluguel, corretivas, diesel, atrasos), ela vira economia. Alongar prazo ou destacar o à vista mexem no número, não no enquadre; o cliente continua vendo perda." },
    { pergunta: "Qual das opções é prova social forte segundo Cialdini, para um empreiteiro do sul do ES?", opcoes: [
      "A New Holland é a marca mais vendida do Brasil na categoria, segundo os dados da associação do setor",
      "Um vídeo da fábrica mostrando a máquina em operação numa mineradora em Minas, com números de produção",
      "A frase 'todos os meus clientes estão satisfeitos' na proposta, assinada pelo gerente da concessionária",
      "O nome e o contato de um empreiteiro de cidade vizinha, na mesma aplicação, com a mesma máquina há dois anos",
    ], correta: 3, explicacao: "Prova social pesa pela semelhança e pela verificabilidade. Vizinho, mesma aplicação, nome e telefone: o cliente pode checar (e raramente checa, mas o fato de poder é o que convence). Liderança nacional e vídeos são propaganda para o Sistema 1 cansado." },
    { pergunta: "Você entregou ao cliente o edital de um pregão que ele não tinha visto. Duas semanas depois ele ganhou e pediu preço de um rolo. Qual princípio de Cialdini trabalhou, e como continuar?", opcoes: [
      "Reciprocidade; agora lembre-o do favor com leveza para obter uma margem melhor na proposta do rolo",
      "Reciprocidade; não mencione o favor e faça o diagnóstico normal antes de precificar",
      "Autoridade; você demonstrou conhecer licitações e pode precificar acima da tabela por esse serviço",
      "Escassez; avise que o rolo é o último em estoque para a decisão sair antes do início da obra",
    ], correta: 1, explicacao: "O favor genuíno gerou a vontade de retribuir, e o cliente voltou sozinho. Cobrar o favor destrói o princípio. O trabalho agora é o de sempre: diagnosticar (camada, extensão, prazo) antes de precificar, com a boa vontade jogando a favor em silêncio." },
    { pergunta: "O cliente diz: 'A Sany tá 90 mil a menos'. Qual resposta aplica o espelhamento de Voss?", opcoes: [
      "'Noventa mil a menos?', seguido de silêncio",
      "'Entendo, mas a Sany não tem assistência aqui na região'",
      "'Por que você está considerando uma máquina chinesa?'",
      "'Se eu igualar o preço, você fecha hoje comigo?'",
    ], correta: 0, explicacao: "O espelhamento devolve as últimas palavras em tom de pergunta e deixa o cliente explicar: de onde veio o número, se inclui implementos, se o sócio prefere a Sany. 'Entendo, mas' anula a escuta; 'por que' acusa; igualar preço é render-se sem informação." },
    { pergunta: "Qual pergunta é calibrada no sentido de Voss (convida em vez de acusar)?", opcoes: [
      "'Por que você não respondeu a minha proposta da semana passada?'",
      "'Você tem verba aprovada para essa máquina ou ainda não?'",
      "'O que precisaria acontecer do seu lado para a gente avançar?'",
      "'Vai fechar essa semana ou vou perder a cota da fábrica?'",
    ], correta: 2, explicacao: "Perguntas com 'o que' e 'como' pedem ajuda ao cliente para resolver e devolvem informação. 'Por que' é cobrança; 'tem verba ou não' é confronto; 'vou perder a cota' é pressão com escassez duvidosa." },
    { pergunta: "Um cliente que está em silêncio há três semanas recebe a mensagem 'Seria loucura pensar em trocar a máquina antes da safra?'. Por que essa mensagem tende a funcionar?", opcoes: [
      "Porque cria urgência ligada à safra, um prazo real do cliente, sem parecer pressão do vendedor",
      "Porque permite responder 'não' com facilidade, devolvendo controle ao cliente e reabrindo com a objeção real",
      "Porque usa a palavra 'loucura', que chama a atenção no meio das outras notificações do WhatsApp",
      "Porque é curta, cabe na notificação do celular e não exige que o cliente abra a conversa para entender",
    ], correta: 1, explicacao: "Voss mostra que as pessoas se sentem seguras dizendo 'não'. A pergunta orientada a 'não' tira a pressão do 'sim' e faz o cliente responder 'não é loucura, mas o caixa está curto', o que é a objeção real e o caminho para a venda." },
    { pergunta: "O cliente diz 'está caro'. Você responde com a história de um cliente parecido que comprou o mais barato e pagou a diferença em dias parados. O cliente pergunta 'e quanto foi essa diferença?'. O que aconteceu?", opcoes: [
      "O cliente quer comparar a diferença com o desconto que pretende pedir e está preparando a negociação",
      "A história foi longa demais e o cliente está tentando encurtar a conversa com uma pergunta objetiva",
      "O cliente desviou do assunto principal, que era o preço da sua máquina, e precisa ser trazido de volta",
      "A história ativou o Sistema 1 e o cliente agora pede a conta: o Sistema 2 está pronto para a justificativa",
    ], correta: 3, explicacao: "Esse é o momento ideal: a emoção decidiu que vale ouvir e a razão pede o número. A conta apresentada agora entra como justificativa de algo que o cliente já quer, não como argumento contra uma resistência." },
    { pergunta: "Qual combinação de perfil DISC e formato de material está correta?", opcoes: [
      "Perfil D: comparativo técnico de dez páginas com todas as premissas, porque ele quer controle total",
      "Perfil C: uma folha com três números e uma história de cliente, porque ele valoriza objetividade",
      "Perfil S: folha com garantia, assistência (quem atende e em quanto tempo) e tempo para decidir",
      "Perfil I: e-mail formal com ficha técnica e sem conversa pessoal, porque ele respeita profissionalismo",
    ], correta: 2, explicacao: "O S quer segurança e continuidade: garantia, nome de quem atende, sem pressa. D quer três números (não dez páginas); C quer as premissas (não só três números); I quer relação e história (não e-mail frio)." },
    { pergunta: "Qual afirmação sobre ética e persuasão é verdadeira no mercado do interior?", opcoes: [
      "As versões éticas (prova social com nome, escassez verificável, reciprocidade genuína) são as mais eficazes, porque a reputação circula",
      "A ética limita a eficácia: o vendedor honesto vende menos no curto prazo, mas constrói uma carteira mais fiel ao longo dos anos",
      "Técnicas de persuasão são sempre manipulação e devem ser substituídas por apresentação técnica neutra e proposta escrita",
      "A escassez falsa funciona bem no interior porque os clientes não têm como checar a fila de produção da fábrica",
    ], correta: 0, explicacao: "Onde todo mundo conhece todo mundo, o truque é descoberto em dias e a honestidade vira diferencial citado pelo cliente. Os princípios de Cialdini são atalhos legítimos do cérebro; usá-los com verdade é vender melhor, não vender menos." },
    { pergunta: "Um engenheiro de prefeitura responde seco, pede tudo por escrito e não avança há meses com um vendedor simpático e falante. Qual diagnóstico e ajuste são corretos?", opcoes: [
      "Cliente perfil D impaciente com visitas longas; encurtar as reuniões e ir direto ao preço e ao prazo",
      "Cliente perfil C recebendo linguagem de perfil I; ajustar para dados com fonte, escrita e visita técnica",
      "Licitação direcionada para outro fornecedor; encerrar a conta e concentrar o tempo em clientes privados",
      "Falta de relacionamento pessoal; aumentar as visitas sociais, os cafés e os presentes institucionais",
    ], correta: 1, explicacao: "Seco, escrito, detalhista: perfil C. Ele não desconfia de você; desconfia de simpatia sem dado. Trocar caso por comparativo com fonte e áudio por e-mail costuma destravar. Abandonar ou 'aumentar o social' erram o diagnóstico." },
    { pergunta: "Depois de fazer um rótulo ('parece que o que te preocupa é ficar na mão'), qual é o passo mais importante?", opcoes: [
      "Mudar de assunto para não parecer que está pressionando, e retomar a preocupação na proposta escrita",
      "Emendar imediatamente a solução ('e por isso temos assistência em Cachoeiro') enquanto a emoção está viva",
      "Confirmar com uma pergunta fechada ('é isso mesmo, não é?') para garantir que o rótulo foi aceito",
      "Silêncio de alguns segundos para o cliente confirmar, corrigir ou aprofundar",
    ], correta: 3, explicacao: "O rótulo abre; o silêncio faz o cliente entrar. Emendar a solução fecha a porta e mostra que o rótulo era só uma ponte para o pitch. Pergunta fechada tira a liberdade de corrigir. O silêncio é a parte mais difícil e mais rentável da técnica." },
  ],
};
