import type { Modulo } from "./tipos";

export const M3: Modulo = {
  id: "m3", nivel: 3, titulo: "Neurociência aplicada às vendas", tema: "Neurociência", cor: "#2ee6ff",
  descricao: "O cérebro decide antes de a razão justificar. Emoção, rapport, dopamina, os dois sistemas de pensamento, medo e memória — aplicados à venda de máquina pesada.",
  objetivos: [
    "Estruturar a apresentação na ordem em que o cérebro decide: emoção → imagem → razão.",
    "Criar rapport rápido com espelhamento e neurônios-espelho.",
    "Construir antecipação (dopamina) e reconhecer o pico para fechar.",
    "Adequar a quantidade de informação ao Sistema 1 e ao Sistema 2 do cliente.",
    "Reduzir o medo e o risco percebido que travam decisões grandes.",
    "Usar histórias para ser lembrado e decidir a favor.",
  ],
  leituras: [
    "Daniel Kahneman — Rápido e Devagar: duas formas de pensar.",
    "Patrick Renvoisé e Christophe Morin — Neuromarketing.",
    "Antonio Damasio — O Erro de Descartes (emoção e decisão).",
    "Chip e Dan Heath — Ideias que Colam.",
  ],
  aulas: [
    {
      id: "m3a1", titulo: "Decisão emocional, justificativa racional", minutos: 11,
      resumo: "O sistema límbico decide; o córtex explica depois. Sua apresentação precisa falar com os dois, nessa ordem.",
      blocos: [
        { tipo: "p", texto: "Pacientes com lesão nas áreas emocionais do cérebro, mesmo com raciocínio intacto, não conseguem decidir nem o que almoçar — mostram os estudos de Antonio Damasio. Decisão é emoção; a razão vem depois para justificar. O cliente que compra a E215C decide pelo alívio de não ficar na mão, pelo orgulho da máquina nova no pátio, pelo medo de perder a obra — e depois explica para o sócio com a planilha de consumo." },
        { tipo: "lista", titulo: "Emoções que compram máquina", itens: [
          "Alívio: “nunca mais ficar na mão”. Máquina nova = fim da dor de cabeça.",
          "Orgulho: a máquina nova no pátio, a foto, o vizinho olhando.",
          "Segurança: marca, assistência, garantia — para a família e o patrimônio.",
          "Medo de perder: a obra, o contrato, a safra, o operador bom.",
          "Ambição: crescer, pegar obra maior, comprar a segunda.",
          "Pertencimento: ser cliente da marca que os grandes da região usam.",
        ] },
        { tipo: "p", titulo: "Como estruturar a fala", texto: "Abra com a dor emocional (o que a máquina antiga custa em dor de cabeça), mostre a solução com imagem concreta (a máquina trabalhando na obra dele), e só então entregue os dados que justificam. Emoção → imagem → razão. Inverter a ordem deixa a decisão fria." },
        { tipo: "tabela", titulo: "A mesma apresentação nas duas ordens", colunas: ["Ordem errada (razão primeiro)", "Ordem certa (emoção → imagem → razão)"], linhas: [
          ["“A E215C tem 160 cv, consumo de 18 L/h e caçamba de 1,2 m³.”", "“Lembra da semana que a sua parou e você teve que ligar pro cliente? Isso acaba.”"],
          ["“O financiamento é em 60 meses com carência.”", "“Imagina segunda-feira: a E215C chegando na sua pedreira, o operador subindo com ar-condicionado, e o caminhão saindo carregado em 6 caçambas em vez de 9.”"],
          ["“Ela é mais produtiva que a atual.”", "“Pra isso fechar a conta: 30% a mais por hora, 2 litros a menos, assistência em 24 h, e a parcela cabe no que ela produz. Aqui os números.”"],
        ] },
        { tipo: "destaque", titulo: "Imagem mental", texto: "“Imagina segunda-feira: a E215C chegando na sua obra, o operador subindo na cabine com ar-condicionado, e você fechando a fundação até quinta em vez de na outra semana.” Frases assim ativam áreas visuais e motoras do cérebro — o cliente “vive” a compra antes de assinar." },
        { tipo: "script", titulo: "Aberturas emocionais por nicho", itens: [
          "Pedreira: “Quantas toneladas você deixou de vender no último mês por máquina parada? Esse número é o que a gente vai zerar.”",
          "Café: “Você já perdeu prazo de preparo por causa de máquina emprestada? Com a sua própria, a lavoura anda no seu tempo.”",
          "Prefeitura: “Estrada ruim na época de chuva é reclamação na porta da prefeitura. Com a motoniveladora certa, o prefeito vira notícia boa.”",
          "Construtora: “Obra atrasada é multa e cliente irritado. Vamos falar de como entregar antes do prazo.”",
        ] },
        { tipo: "erros", titulo: "Erros que esfriam a decisão", itens: [
          "Começar pela ficha técnica ou pela condição de pagamento.",
          "Falar em termos abstratos (“produtividade”, “eficiência”) em vez de cenas concretas.",
          "Dar todos os dados antes de o cliente sentir a dor.",
          "Confundir emoção com sentimentalismo: emoção aqui é alívio, orgulho, medo, ambição — coisas de negócio.",
        ] },
      ],
      missao: "Reescreva a sua apresentação padrão da máquina que mais vende na ordem emoção → imagem → razão. Use com 2 clientes esta semana e registre a reação no CRM.",
      quiz: [
        { pergunta: "Qual é a ordem que respeita como o cérebro decide?", opcoes: ["Dados → preço → benefício", "Emoção → imagem → razão", "Preço → emoção → dados"], correta: 1, explicacao: "O cérebro decide emocionalmente e justifica racionalmente. Dados no fim, para o sócio e o contador." },
        { pergunta: "“Imagina segunda-feira a máquina chegando na sua obra…” ativa:", opcoes: ["Só a razão", "Áreas visuais e motoras — o cliente vive a compra", "Nada"], correta: 1, explicacao: "Imagem mental concreta é a ponte entre emoção e decisão." },
      ],
    },
    {
      id: "m3a2", titulo: "Rapport, espelhamento e neurônios-espelho", minutos: 10,
      resumo: "O cérebro confia em quem parece com ele. Como criar sintonia rápida sem parecer imitação.",
      blocos: [
        { tipo: "p", texto: "Neurônios-espelho fazem o cérebro simular o que vê no outro: postura, ritmo, tom. Quando você espelha o cliente com naturalidade, ele sente “esse cara é como eu” — e baixa a guarda. Rapport não é técnica de manipulação: é a base biológica da confiança. Sem ele, o melhor argumento bate na parede." },
        { tipo: "lista", titulo: "Espelhamento prático", itens: [
          "Ritmo: cliente fala rápido, você acelera; fala devagar, você desacelera. Nunca o contrário.",
          "Vocabulário: ele fala “retro”, você fala “retro”; ele fala “máquina”, não fale “equipamento”.",
          "Postura: na obra, em pé e apontando para a máquina; no escritório, sentado na mesma altura, sem a mesa no meio se possível.",
          "Canal: ele responde por áudio, você responde por áudio; ele escreve curto, você escreve curto.",
          "Energia: cliente sério e contido, você contido; cliente brincalhão, você solta uma piada — uma.",
          "Interesse real: pergunte da obra, do café, da família, do time. E ouça. Rapport falso é percebido em segundos.",
        ] },
        { tipo: "script", titulo: "Abertura de rapport na visita", itens: [
          "“Antes de falar de máquina, me mostra a obra? Quero entender o que vocês estão fazendo aqui.”",
          "“Quantos anos você tem essa retro? Ela já te acompanhou em muita obra, né?” (valorize a história dele).",
          "“Seu operador é o Zé? Zé, como é que ela tá se comportando? Você conhece ela melhor que todo mundo.”",
        ] },
        { tipo: "p", titulo: "Rapport pelo WhatsApp", texto: "Responda no mesmo formato e tamanho do cliente. Use o nome dele. Cite algo específico da última conversa (“como ficou o serviço da ponte?”). Reaja ao que ele manda (foto da obra, áudio) antes de puxar assunto de venda. Mensagem que só vende, sem relação, é lida como spam — mesmo vinda de você." },
        { tipo: "caso", titulo: "Caso: o vendedor que falava rápido demais", situacao: "Vendedor de perfil D e fala acelerada visitava produtores de café no Caparaó (perfil S, ritmo lento). As visitas eram educadas e não avançavam.", acao: "Passou a chegar sem pressa, aceitar o café, perguntar da lavoura e da família, e desacelerar a fala. Só puxava o assunto máquina depois de 15 minutos.", resultado: "Mesmos produtores, mesma máquina: 3 propostas em um mês, contra zero nos dois anteriores.", licao: "Ritmo é rapport. Quem impõe o próprio ritmo ao cliente perde o cliente." },
        { tipo: "erros", titulo: "Erros de rapport", itens: [
          "Imitar sotaque ou gestos de forma óbvia — vira deboche.",
          "Falar de futebol ou política sem saber a posição do cliente.",
          "Rapport só no início e depois “modo vendedor”. A relação tem que atravessar a conversa toda.",
          "Cumprimentar só o dono. O operador e o encarregado percebem — e influenciam.",
        ] },
      ],
      missao: "Na próxima visita, espelhe conscientemente ritmo, vocabulário e canal do cliente durante toda a conversa. Anote no CRM o que mudou na abertura dele.",
      quiz: [
        { pergunta: "Cliente fala devagar e pausado. Você:", opcoes: ["Acelera para ganhar tempo", "Desacelera para o ritmo dele", "Mantém o seu ritmo"], correta: 1, explicacao: "Ritmo é o espelhamento mais poderoso. Descompasso gera desconforto inconsciente." },
        { pergunta: "Cliente manda áudio. A melhor resposta é:", opcoes: ["Texto longo", "Áudio no mesmo tom e tamanho", "Ignorar até a visita"], correta: 1, explicacao: "Espelhar o canal cria sintonia até no WhatsApp." },
      ],
    },
    {
      id: "m3a3", titulo: "Dopamina, antecipação e o momento certo de fechar", minutos: 10,
      resumo: "O desejo tem pico e vale. Construa antecipação e feche no pico — esperar “o cliente pensar” é fechar no vale.",
      blocos: [
        { tipo: "p", texto: "A dopamina não é o prazer de ter; é a antecipação de ter. O cérebro do cliente libera mais dopamina imaginando a máquina no pátio do que no dia da entrega. Esse pico é o momento de decisão. Se você deixa o cliente “ir para casa pensar”, a dopamina cai, o cunhado fala, o concorrente liga, e a decisão volta ao vale." },
        { tipo: "lista", titulo: "Como construir a antecipação", itens: [
          "Demonstração com o operador dele na cabine: o corpo sente antes da mente decidir.",
          "Foto e vídeo da máquina no pátio com o nome dele (“reservei essa pra você”).",
          "Fale da entrega como se fosse certa: data, treinamento, quem vai receber.",
          "Pequenas conquistas ao longo da negociação: “o banco pré-aprovou”, “consegui a cor”, “segurei a unidade”.",
          "Deixe ele escolher algo: cor, implemento, data. Escolher gera posse psicológica.",
        ] },
        { tipo: "lista", titulo: "Sinais de que o pico chegou (hora de fechar)", itens: [
          "Pergunta de entrega, prazo ou treinamento.",
          "Chama o sócio/operador para ver.",
          "Começa a falar da máquina como se fosse dele (“ela vai ficar ali no galpão”).",
          "Pergunta de parcela ou entrada depois de ter dito que “era só uma olhada”.",
          "Pede desconto (quem pede desconto quer comprar).",
          "Relaxa a postura, sorri, faz brincadeira sobre a compra.",
        ] },
        { tipo: "destaque", titulo: "Regra", texto: "Sinal de compra recebido = pergunta de fechamento na hora. Não “deixe o cliente pensar”; ajude-o a decidir enquanto o desejo está no pico." },
        { tipo: "script", titulo: "Transformando o sinal em fechamento", itens: [
          "Sinal: “Quanto tempo leva pra entregar?” → “Se fecharmos hoje, 15 dias. Quer que eu reserve a unidade do pátio no seu nome agora?”",
          "Sinal: “Chama o Zé aqui pra ver.” → (depois do Zé) “Zé aprovou. O que falta pra ela ficar aqui?”",
          "Sinal: “Ela ia ficar bonita no galpão, hein.” → “Vai. Vamos combinar a data que ela chega? Prefere antes ou depois do dia 15?”",
        ] },
        { tipo: "caso", titulo: "Caso: o pico desperdiçado", situacao: "Na demonstração, o cliente operou a retro, sorriu, chamou o filho para ver e perguntou da entrega. O vendedor respondeu “15 dias” e disse “pensa com calma e me avisa”.", acao: "Uma semana depois, o cliente estava frio: o cunhado disse que a marca X era mais barata. O vendedor precisou de mais 3 visitas e um desconto para fechar.", resultado: "Fechou, mas com margem menor e 40 dias de atraso.", licao: "Pico de desejo é para fechar, não para “dar tempo”. A hesitação custa margem e tempo." },
      ],
      missao: "Na próxima demonstração ou visita quente, liste os sinais de compra que aparecerem e faça a pergunta de fechamento no primeiro sinal claro. Registre no CRM o sinal e a resposta.",
      quiz: [
        { pergunta: "O cliente pergunta “quanto tempo pra entregar?”. Isso é:", opcoes: ["Uma dúvida técnica", "Um sinal de compra — hora de fechar", "Um sinal de que ele quer ir embora"], correta: 1, explicacao: "Quem pergunta de entrega já se vê com a máquina. Pergunte o fechamento." },
        { pergunta: "Por que “deixar o cliente pensar” costuma esfriar a venda?", opcoes: ["Porque ele esquece", "Porque a antecipação (dopamina) cai e outras vozes entram", "Não esfria"], correta: 1, explicacao: "Desejo tem pico. Fora dele, o medo e o concorrente ganham espaço." },
      ],
    },
    {
      id: "m3a4", titulo: "Sistema 1 e Sistema 2: quanta informação dar, e quando", minutos: 10,
      resumo: "O cérebro tem um modo rápido e intuitivo e um modo lento e analítico. Cada um exige uma apresentação diferente — e errar a dose trava a decisão.",
      blocos: [
        { tipo: "p", texto: "Kahneman descreve dois sistemas: o Sistema 1 é rápido, automático, emocional (decide em segundos por impressão e atalho); o Sistema 2 é lento, esforçado, analítico (compara planilhas). O Sistema 2 cansa rápido e, quando cansa, o cérebro adia a decisão (“vou pensar”). Excesso de informação não convence — paralisa." },
        { tipo: "tabela", titulo: "Quando falar com cada sistema", colunas: ["Situação", "Sistema dominante", "Como apresentar"], linhas: [
          ["Primeiro contato, WhatsApp, obra", "Sistema 1", "Uma ideia, uma imagem, um número forte. “30% mais caçambas por hora.”"],
          ["Perfil D ou I decidindo", "Sistema 1", "Resultado, prazo, prova social. Três pontos, não dez."],
          ["Perfil C, comprador de prefeitura, contador", "Sistema 2", "Comparativo completo, custo total, fontes. Mas organizado: resumo em cima, detalhe embaixo."],
          ["Comitê com sócio", "Os dois", "Abertura emocional (S1), uma página de conta (S2), fechamento com imagem (S1)."],
          ["Cliente cansado, fim de dia", "S2 esgotado", "Não apresente. Marque para de manhã. Decisão grande com S2 esgotado vira “não”."],
        ] },
        { tipo: "lista", titulo: "Regras de carga cognitiva", itens: [
          "Regra de 3: três benefícios, três diferenciais, três opções de pagamento. Mais que isso, o cliente esquece e adia.",
          "Uma página: a proposta cabe em uma página com o retorno em cima. O detalhe vai em anexo para quem quiser.",
          "Escolha simples: “Finame em 60 ou consórcio?” é decidível. “Temos 7 formas de pagamento” não é.",
          "Número redondo e comparável: “R$ 3 mil por dia parado” em vez de “R$ 2.874,32”.",
          "Decisões grandes de manhã, em ambiente calmo, com o cliente alimentado. Parece detalhe; é biologia.",
        ] },
        { tipo: "script", titulo: "Resumo de uma frase (Sistema 1) para cada máquina", itens: [
          "B95C: “A retro que faz o serviço de duas na obra pequena e não para.”",
          "E215C: “Mais toneladas por litro na pedreira, com peça em Cachoeiro.”",
          "W170B: “Carrega o caminhão em menos ciclos e gasta menos por tonelada.”",
          "RG140B: “Estrada nivelada em uma passada; prefeitura vira notícia boa na chuva.”",
          "CA2500: “Compacta em menos passadas e prova o grau pro fiscal.”",
        ] },
        { tipo: "caso", titulo: "Caso: o comparativo de 12 páginas", situacao: "Vendedor mandou comparativo de 12 páginas para um empreiteiro (perfil D). Resposta: “vou olhar com calma”. Nunca olhou.", acao: "Refez em uma página: 3 diferenças em reais, a parcela e a data de entrega. Mandou com a pergunta “faz sentido conversar quinta?”.", resultado: "Resposta em 10 minutos. Reunião na quinta, fechamento na semana seguinte.", licao: "Mais informação não é mais convencimento. Para o Sistema 1, é ruído." },
      ],
      missao: "Pegue a sua proposta padrão e crie uma versão de uma página (retorno, 3 diferenciais, parcela, entrega, validade). Use-a como capa em todas as propostas desta semana.",
      quiz: [
        { pergunta: "Cliente perfil D pede “manda a proposta”. Você manda:", opcoes: ["O comparativo completo de 12 páginas", "Uma página com retorno, 3 diferenciais, parcela e entrega", "Só o preço"], correta: 1, explicacao: "Sistema 1 decide com pouca informação bem escolhida." },
        { pergunta: "Excesso de opções de pagamento tende a:", opcoes: ["Facilitar a decisão", "Paralisar e gerar “vou pensar”", "Não ter efeito"], correta: 1, explicacao: "Carga cognitiva alta esgota o Sistema 2 e adia a decisão." },
      ],
    },
    {
      id: "m3a5", titulo: "Medo, cortisol e risco percebido: por que decisões grandes travam", minutos: 10,
      resumo: "A amígdala vê uma parcela de R$ 9 mil como ameaça. Como reduzir o risco percebido e usar a pressão certa sem disparar o alarme.",
      blocos: [
        { tipo: "p", texto: "Uma compra de R$ 500 mil ativa o circuito de medo do cérebro: e se a obra acabar? E se o banco não aprovar? E se eu errar de máquina? Sob cortisol, o cliente não decide — foge (“vou pensar”) ou luta (objeção agressiva). Pressão errada nesse momento aumenta o medo. O trabalho do vendedor é reduzir o risco percebido até a decisão ficar segura, e só então aplicar ritmo." },
        { tipo: "tabela", titulo: "Medos típicos e redutores de risco", colunas: ["Medo", "Redutor"], linhas: [
          ["Errar de máquina", "Diagnóstico bem feito, demonstração na obra dele, casos do mesmo nicho"],
          ["Parcela não caber", "Conta com os números dele, carência, prazo, usada na entrada, plano B se a obra acabar (revenda alta)"],
          ["Ficar sem assistência", "Visita com o mecânico, contato direto da oficina, prazo de atendimento por escrito"],
          ["Banco negar", "Pré-análise antes da proposta; alternativas (consórcio, outro banco) já mapeadas"],
          ["Ser enganado", "Transparência: o que está e o que não está incluso, validade real, sem letra miúda"],
          ["Arrependimento", "Garantia, valor de revenda, “se em 30 dias algo não estiver como combinado, eu resolvo”"],
        ] },
        { tipo: "lista", titulo: "Segurança psicológica na negociação", itens: [
          "Diga o que vai acontecer antes de acontecer: “hoje eu mostro, quinta revisamos, você decide sexta”. Previsibilidade reduz cortisol.",
          "Dê um caminho de saída: “se o banco não aprovar, a gente tenta consórcio; você não fica preso”.",
          "Passos pequenos: reservar a unidade, mandar documentos, pré-análise. Cada passo pequeno é decidível sem medo.",
          "Não puxe o tapete: urgência falsa é percebida como ameaça e dispara defesa.",
          "Valide o medo antes de responder: “é natural pensar nisso, é muito dinheiro”. Medo validado diminui; medo rebatido cresce.",
        ] },
        { tipo: "script", titulo: "Reduzindo o risco na fala", itens: [
          "“Antes de qualquer proposta, eu faço uma pré-análise de crédito. Assim você só decide sabendo que o banco aprova.”",
          "“Se a obra acabar antes do previsto, essa máquina tem revenda de 55% em 5 anos. Você não fica com um peso; fica com um ativo.”",
          "“Vamos fazer em etapas: primeiro a demonstração, depois a conta, depois o banco. Você só assina quando tudo estiver claro.”",
        ] },
        { tipo: "destaque", titulo: "Pressão certa x pressão errada", texto: "Pressão certa é ritmo e clareza depois de o risco estar baixo: “está tudo resolvido, vamos assinar?”. Pressão errada é urgência antes de o cliente se sentir seguro. A primeira fecha; a segunda espanta." },
        { tipo: "caso", titulo: "Caso: a pré-análise que destravou", situacao: "Empreiteiro pequeno adiava a proposta há dois meses. Dizia que “não era a hora”.", acao: "O vendedor percebeu o medo do banco negar (ele já tinha sido negado uma vez). Ofereceu pré-análise sem compromisso e trouxe as duas alternativas caso desse errado.", resultado: "Aprovado na pré-análise, o cliente fechou na semana seguinte. O medo era o banco, não a máquina.", licao: "Descubra qual medo está travando e reduza esse. O resto se resolve." },
      ],
      missao: "Para cada negociação parada há mais de 15 dias, identifique o medo provável e faça uma ação redutora de risco (pré-análise, visita com mecânico, plano B por escrito). Registre no CRM.",
      quiz: [
        { pergunta: "Cliente com medo de o banco negar. Melhor ação:", opcoes: ["Pressionar com validade da tabela", "Pré-análise de crédito e alternativas mapeadas", "Esperar ele resolver"], correta: 1, explicacao: "Reduza o risco percebido; só depois aplique ritmo." },
        { pergunta: "O cliente diz “é muito dinheiro, tenho medo de errar”. Você:", opcoes: ["Rebate: “não tem erro, é a melhor máquina”", "Valida: “é natural, é muito dinheiro” e propõe passos pequenos", "Muda de assunto"], correta: 1, explicacao: "Medo validado diminui. Medo rebatido cresce." },
      ],
    },
    {
      id: "m3a6", titulo: "Memória e storytelling: como ser lembrado e decidir a seu favor", minutos: 10,
      resumo: "O cérebro guarda histórias, não dados. Estrutura da história de venda, efeitos de primazia e recência, e como grudar na memória do cliente.",
      blocos: [
        { tipo: "p", texto: "Uma semana depois da visita, o cliente não lembra do consumo por hora. Lembra da história da pedreira que parou de alugar máquina, do vídeo do operador sorrindo, e de como você começou e terminou a conversa. Histórias ativam mais áreas do cérebro que dados e são lembradas até 20 vezes mais. Vendedor de elite tem um repertório de histórias reais, curtas e do nicho do cliente." },
        { tipo: "lista", titulo: "Estrutura da história de venda (60 a 90 segundos)", itens: [
          "Personagem parecido com o cliente: “um empreiteiro de Alegre, do seu tamanho…”",
          "Problema concreto: “…a retro parava toda semana e ele alugava pra cobrir.”",
          "Virada: “…fez a conta comigo e viu que pagava uma máquina nova em aluguel.”",
          "Resultado com número: “…trocou por uma B110B, zerou o aluguel e pegou a obra da prefeitura que não conseguia atender.”",
          "Ponte: “…a sua situação me lembrou a dele. Quer fazer a mesma conta?”",
        ] },
        { tipo: "tabela", titulo: "Efeitos de memória e como usar", colunas: ["Efeito", "O que é", "Aplicação"], linhas: [
          ["Primazia", "Lembramos do começo", "Abra com a frase mais forte (dor ou resultado), não com “tudo bem?”"],
          ["Recência", "Lembramos do fim", "Termine com o próximo passo e a imagem da máquina na obra dele"],
          ["Pico", "Lembramos do momento mais intenso", "Crie um: a demonstração, a conta na folha, o vídeo do cliente vizinho"],
          ["Concretude", "Lembramos do específico", "“Seis caçambas em vez de nove” em vez de “mais produtiva”"],
          ["Repetição espaçada", "Lembramos do que revemos", "Follow-up com a mesma ideia central em formatos diferentes (mensagem, foto, visita)"],
        ] },
        { tipo: "script", titulo: "Três histórias para ter prontas", itens: [
          "A do aluguel (construtora): quem pagava máquina alugada sem ficar com nada e trocou por parcela.",
          "A da parada (pedreira): quem perdeu contrato por máquina parada e resolveu com assistência local.",
          "A da safra (café): quem preparou a lavoura no tempo certo com máquina própria e colheu mais.",
        ] },
        { tipo: "erros", titulo: "Erros de storytelling", itens: [
          "História longa demais. Mais de 90 segundos vira palestra.",
          "História de outro nicho. O produtor de café não se vê na pedreira.",
          "Sem número no final. Resultado vago não convence.",
          "Inventar. Histórias reais têm detalhes que só a verdade tem — e podem ser checadas.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escreva as 3 histórias acima com clientes reais da sua carteira (peça permissão). Cada uma em 5 frases, com um número no final. Treine em voz alta até caber em 60 segundos." },
      ],
      missao: "Use uma história real do mesmo nicho em cada visita desta semana. Termine cada conversa com o próximo passo e uma imagem concreta da máquina na obra do cliente. Anote no CRM qual história usou.",
      quiz: [
        { pergunta: "O que o cliente mais lembra uma semana depois da visita?", opcoes: ["O consumo por hora", "A história, o começo e o fim da conversa", "O preço com centavos"], correta: 1, explicacao: "Histórias, primazia e recência. Dados vão para o anexo." },
        { pergunta: "Uma boa história de venda termina com:", opcoes: ["“E foi isso”", "Um resultado com número e uma ponte para o cliente", "Uma piada"], correta: 1, explicacao: "Número dá credibilidade; a ponte transforma a história em próximo passo." },
      ],
    },
  ],
  prova: [
    { pergunta: "Na ordem emoção → imagem → razão, onde entra o comparativo de consumo?", opcoes: ["No começo", "No fim, para justificar", "Nunca"], correta: 1, explicacao: "Razão justifica a decisão emocional já tomada." },
    { pergunta: "Cliente responde por áudio curto e fala devagar. Espelhamento correto:", opcoes: ["Texto longo e rápido", "Áudio curto e no ritmo dele", "Ligar imediatamente"], correta: 1, explicacao: "Canal, tamanho e ritmo espelhados." },
    { pergunta: "Qual é o sinal de compra mais claro?", opcoes: ["Pergunta de entrega ou treinamento", "Silêncio", "Pedido de catálogo"], correta: 0, explicacao: "Quem pergunta de entrega já se vê dono." },
    { pergunta: "Perfil C pede detalhes. Você entrega:", opcoes: ["Uma frase", "Comparativo completo, com resumo em cima", "Nada, ele vai cansar"], correta: 1, explicacao: "Sistema 2 quer dados — organizados para não esgotar." },
    { pergunta: "Cliente travado por medo de o banco negar. Primeira ação:", opcoes: ["Urgência de tabela", "Pré-análise e alternativas", "Desconto"], correta: 1, explicacao: "Reduza o risco antes de aplicar ritmo." },
    { pergunta: "Uma história de venda precisa de:", opcoes: ["Personagem parecido, problema, virada, resultado com número, ponte", "Muitos detalhes técnicos", "Pelo menos 5 minutos"], correta: 0, explicacao: "Curta, real, do mesmo nicho, com número e ponte." },
  ],
};
