import type { Modulo } from "./tipos";

export const M3: Modulo = {
  id: "m3", nivel: 3, titulo: "Prospecção e território", tema: "Funil cheio", cor: "#34d399",
  descricao: "Encher o funil todos os dias com método: cliente ideal e radar de sinais (Diário Oficial, licitações, usadas à venda, obras iniciando), cadência multicanal de 7 toques em 21 dias, a primeira mensagem que recebe resposta, ligação fria sem medo, indicação como sistema e o roteiro de campo que faz cada quilômetro render.",
  objetivos: [
    "Definir o cliente ideal por nicho e pontuar cada lead antes de gastar tempo com ele.",
    "Montar um radar semanal de sinais de compra: editais, obras, usadas anunciadas, contratos vencendo, safra.",
    "Executar uma cadência de 7 toques em 21 dias por WhatsApp, ligação, visita e indicação, sem parecer insistente.",
    "Escrever a primeira mensagem com pertinência, valor e uma pergunta fácil de responder.",
    "Fazer ligação fria com abertura de 20 segundos e objetivo único: a visita.",
    "Transformar indicação de evento aleatório em sistema com gatilho, pedido e retorno.",
    "Planejar o roteiro de campo por rota e prioridade, com custo por visita conhecido.",
  ],
  leituras: [
    "Jeb Blount — Fanatical Prospecting: a disciplina diária e a lei da familiaridade.",
    "Aaron Ross e Marylou Tyler — Receita Previsível: separar prospecção de fechamento e medir a cadência.",
    "Mike Weinberg — New Sales. Simplified.: a história de vendas (sales story) e a lista de alvos.",
    "Diário Oficial dos Municípios do ES (AMUNES) e Portal de Compras Públicas: leitura semanal obrigatória.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m3a1", titulo: "Cliente ideal e radar de sinais de compra", minutos: 14,
      resumo: "Prospectar sem perfil é gastar sola com quem nunca vai comprar. Prospectar com radar é chegar antes do concorrente, no momento em que o cliente começou a precisar.",
      blocos: [
        { tipo: "p", texto: "A maioria dos vendedores prospecta 'quem aparece'. O consultor prospecta quem tem sinal. Sinal é um fato observável que indica que o cliente vai precisar de máquina nos próximos 90 dias: ganhou uma licitação, anunciou a usada na OLX, abriu uma obra na BR, comprou terra nova, tem contrato de locação vencendo, entrou na safra. Quem lê os sinais chega antes; quem espera o telefone chega junto com outros quatro vendedores — e aí a conversa é preço." },
        { tipo: "framework", nome: "Pontuação de lead (ICP 0–10)", origem: "Prática de qualificação B2B (ideal customer profile), adaptada ao mercado de máquinas do sul do ES", passos: [
          "Aplicação (0–3): tem serviço contínuo para a máquina? Pedreira, prefeitura com frota, terraplenador com contrato = 3; serviço eventual = 1.",
          "Capacidade de pagar (0–3): faturamento, crédito no banco, usada para dar de entrada, consórcio contemplado. Sem caminho de pagamento = 0.",
          "Momento (0–2): sinal recente (edital, obra, usada anunciada, safra) = 2; 'algum dia' = 0.",
          "Acesso (0–2): você chega no decisor (ou em quem indica)? Indicação quente = 2; só o site da prefeitura = 0.",
          "Regra: 8–10, prioridade máxima (visita esta semana); 5–7, cadência; abaixo de 5, e-mail/WhatsApp de nutrição a cada 60 dias.",
        ] },
        { tipo: "tabela", titulo: "Radar semanal: onde os sinais aparecem", colunas: ["Fonte", "Sinal", "O que fazer em 24 h"], linhas: [
          ["Diário Oficial (AMUNES) / Portal de Compras", "Pregão de máquina, obra de pavimentação, contrato de locação de frota", "Ligar para a empreiteira que costuma ganhar; ligar para o engenheiro do município"],
          ["OLX / Mercado Livre / grupos de WhatsApp", "Usada da região anunciada", "Ligar: 'vi que está vendendo a retro — vai trocar ou reduzir a frota?'"],
          ["Rodovia e obras visíveis", "Placa de obra nova, terraplenagem começando, usina de asfalto", "Parar, apresentar-se ao encarregado, pegar o nome de quem decide"],
          ["Cooperativas e sindicatos rurais", "Safra, crédito rural liberado, projeto de carreador", "Palestra ou dia de campo; lista de produtores com área acima de 30 ha"],
          ["Clientes atuais", "Máquina com 8.000+ horas, contrato novo, sócio novo", "Visita de pós-venda com a pergunta 'e a próxima obra?'"],
          ["Locadoras", "Locatário recorrente há 12+ meses", "Conta do aluguel acumulado × parcela"],
        ] },
        { tipo: "dialogo", titulo: "O sinal da usada anunciada", falas: [
          { quem: "vendedor", texto: "Seu Gilson, é o Edy, da New Holland de Cachoeiro. Vi o anúncio da sua 580 no Mercado Livre. Está trocando ou reduzindo a frota?" },
          { quem: "cliente", texto: "Trocando. Ela tá com 11 mil horas, não compensa mais." },
          { quem: "vendedor", texto: "Faz sentido. Já decidiu pela próxima ou ainda está olhando?" },
          { quem: "cliente", texto: "Tô olhando. Vou ver uma da JCB semana que vem." },
          { quem: "vendedor", texto: "Então deixa eu te ajudar com duas coisas antes de você decidir: avalio a sua 580 pra entrada, sem compromisso, e te mostro a conta da B110B com ela na troca. Quinta de manhã eu passo na obra? Vinte minutos." },
          { quem: "nota", texto: "Sinal (usada anunciada) → ligação no mesmo dia → pergunta de diagnóstico → valor antes de pedir (avaliação) → visita com horário. O concorrente ainda vai ver o anúncio." },
        ] },
        { tipo: "caso", titulo: "Caso: o edital que ninguém leu", situacao: "A prefeitura de Muniz Freire publicou pregão para locação de frota com opção de compra. Três empreiteiras da região concorreram; nenhuma tinha rolo compactador próprio.", acao: "O vendedor leu o Diário na segunda, ligou para as três na terça oferecendo a simulação do rolo CA2500 para a proposta e o custo/hora para a planilha do pregão.", resultado: "A vencedora comprou o rolo e uma motoniveladora; as duas perdedoras pediram proposta 'para o próximo'. Três negociações de um edital.", licao: "O Diário Oficial é a maior fonte de sinais do interior — e a menos lida. Trinta minutos toda segunda-feira." },
        { tipo: "checklist", titulo: "Rotina de radar (segunda, 30 min + terça, 30 min)", itens: [
          "Diário Oficial dos municípios da carteira: pregões, contratos, obras (segunda).",
          "OLX, Mercado Livre e grupos de máquinas: usadas da região anunciadas nos últimos 7 dias (segunda).",
          "Clientes com máquina acima de 8.000 horas ou contrato vencendo (relatório do CRM).",
          "Obras vistas na estrada durante a semana: nome do encarregado anotado.",
          "Cinco leads novos pontuados e cadastrados no CRM com o sinal registrado nas observações (terça).",
        ] },
        { tipo: "erros", titulo: "Erros de prospecção", itens: [
          "Prospectar por lista fria de CNPJ sem sinal: taxa de resposta abaixo de 3%.",
          "Pontuar depois de visitar. A pontuação serve para decidir SE visita e quando.",
          "Ignorar o cliente atual como fonte: 40% das vendas novas vêm de conta existente ou indicação dela.",
          "Ver a usada anunciada e não ligar no mesmo dia. Sinal envelhece em 72 horas.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pontue de 0 a 10 os 20 últimos leads que você cadastrou no CRM usando o ICP. Quantos têm 8 ou mais? Quantos abaixo de 5 receberam visita? Redistribua seu tempo da próxima semana conforme a pontuação." },
      ],
      missao: "Monte o seu radar: leia o Diário Oficial dos municípios da sua carteira e os anúncios de usadas da região. Cadastre cinco leads novos no CRM com a pontuação ICP e o sinal que motivou o cadastro. Ligue para os dois de maior nota hoje.",
      quiz: [
        { pergunta: "Você tem uma tarde livre e dois leads: um produtor de café que 'pode comprar algum dia' (ICP 4) e um empreiteiro que anunciou a usada ontem (ICP 8). Qual a decisão correta e por quê?", opcoes: [
          "Visitar o produtor, porque relação de longo prazo com café vale mais que uma venda pontual e o empreiteiro vai ligar de volta",
          "Dividir a tarde entre os dois, porque cada um tem um sinal diferente e nenhum deles pode esperar a semana seguinte",
          "Mandar mensagem com a conta para os dois e visitar quem responder primeiro, para decidir com base no interesse real",
          "Ligar e visitar o empreiteiro hoje, porque sinal envelhece em 72 horas e o concorrente vê o anúncio; o produtor entra em nutrição",
        ], correta: 3, explicacao: "A pontuação existe para decidir onde o tempo rende. Momento (sinal recente) vale pontos porque a janela é curta: em três dias outro vendedor liga. O lead de nota baixa não é descartado: recebe contato leve e periódico até aparecer sinal." },
        { pergunta: "Qual é a principal razão de o Diário Oficial ser tão valioso como fonte de prospecção no interior?", opcoes: [
          "Ele é gratuito, público e poucos vendedores o leem, então você chega antes com informação que o cliente ainda não tem",
          "Ele lista os contatos dos engenheiros e secretários das prefeituras, o que elimina a etapa de descobrir quem decide",
          "Ele publica os preços praticados pelos concorrentes nas licitações anteriores, o que permite calibrar a proposta",
          "Ele garante prioridade à marca que ajudou a montar o termo de referência, porque o edital sai com a especificação dela",
        ], correta: 0, explicacao: "Pregões, contratos de obra e locação de frota são sinais de compra publicados com antecedência. Como quase ninguém lê, quem lê vira fonte de valor para empreiteiras e engenheiros. Não há telefone nem garantia de compra: há antecedência." },
        { pergunta: "Um empreiteiro anuncia a retro na OLX. Qual primeira frase ao telefone tem mais chance de abrir conversa?", opcoes: [
          "'Vi o anúncio e queria apresentar a linha New Holland de retroescavadeiras'",
          "'Vi o anúncio da sua retro. Está trocando ou reduzindo a frota?'",
          "'Vi o anúncio. Quanto você quer por ela? Talvez a gente pegue na troca'",
          "'Bom dia, posso te enviar um catálogo das nossas retroescavadeiras?'",
        ], correta: 1, explicacao: "A pergunta de diagnóstico ('trocando ou reduzindo?') mostra que você leu o sinal e quer entender, não empurrar. Apresentar linha e catálogo é monólogo; perguntar o preço da usada de cara pula o diagnóstico e ancora a conversa na troca." },
        { pergunta: "Por que o critério 'Momento' vale pontos separados na pontuação de lead, mesmo quando aplicação e capacidade de pagar são altas?", opcoes: [
          "Porque um sinal recente (edital, usada anunciada) costuma vir acompanhado de crédito pré-aprovado e a análise sai mais rápido",
          "Porque leads sem sinal recente raramente compram, e separá-los evita que o funil fique cheio de contas que nunca vão fechar",
          "Porque o momento define a urgência da ação: o cliente perfeito sem sinal fica em nutrição, e o médio com sinal é visitado esta semana",
          "Porque a data prevista de compra registrada no lead alimenta a previsão do trimestre e o planejamento de entregas da concessionária",
        ], correta: 2, explicacao: "Aplicação e capacidade dizem SE o cliente pode comprar; momento diz QUANDO. Sem separar os dois, o vendedor gasta visitas com contas boas fora de hora e perde a janela das contas médias em hora certa. Nutrição mantém a boa conta quente até o sinal aparecer." },
        { pergunta: "Qual fonte de prospecção é mais subestimada e responde por perto de 40% das vendas novas em bens de capital?", opcoes: [
          "Feiras e eventos do setor, onde os decisores se concentram e chegam com orçamento definido para renovar a frota",
          "Listas de CNPJ compradas de empresas de dados, filtradas por porte e atividade, que permitem escala de contatos",
          "Clientes atuais e as indicações que eles fazem, com máquina envelhecendo ou contrato novo",
          "Redes sociais e anúncios patrocinados por região, que alcançam empreiteiros e produtores com custo por contato baixo",
        ], correta: 2, explicacao: "A base atual já confiou uma vez, tem máquinas que envelhecem e conhece vizinhos com a mesma dor. A visita de pós-venda com a pergunta 'e a próxima obra?' é prospecção de altíssima conversão. Listas frias respondem abaixo de 3%." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m3a2", titulo: "Cadência multicanal: 7 toques em 21 dias", minutos: 14,
      resumo: "Uma mensagem não é prospecção. Sete contatos, em quatro canais, com valor em cada um, em três semanas: essa é a cadência que faz o prospect responder sem achar você um chato.",
      blocos: [
        { tipo: "p", texto: "Jeb Blount chama de 'lei da familiaridade': quanto mais o prospect vê o seu nome associado a algo útil, mais ele responde. Estudos de cadência em B2B mostram que 80% das respostas vêm entre o 4º e o 8º contato, e que 90% dos vendedores desistem antes do 3º. Ou seja: a maior parte do mercado está esperando no toque em que o seu concorrente parou. A diferença entre cadência e insistência é uma só: valor em cada toque." },
        { tipo: "framework", nome: "Cadência 7×21 (sete toques, quatro canais, três semanas)", origem: "Blount (Fanatical Prospecting) e Ross (Receita Previsível), adaptado ao WhatsApp e à obra", passos: [
          "Dia 1 — WhatsApp: mensagem de pertinência (o sinal) + valor (um dado, um edital, uma avaliação) + pergunta fácil.",
          "Dia 3 — Ligação: 20 segundos de abertura, objetivo único: marcar a visita. Sem resposta, deixe áudio de 15 s no WhatsApp.",
          "Dia 6 — WhatsApp com valor novo: um caso de cliente parecido (60 s em texto), foto da máquina na aplicação dele.",
          "Dia 9 — Visita ou 'passei aqui': se está na rota, apareça na obra com um motivo (mostrar a conta, avaliar a usada).",
          "Dia 13 — Indicação: peça a um cliente em comum que mencione você; ou envie mensagem citando o cliente em comum.",
          "Dia 17 — Ligação 2: 'falei com o Marcos, ele comentou que você está com obra em Alegre…'.",
          "Dia 21 — Mensagem de fechamento de ciclo: 'Não quero ser inconveniente. Faz sentido a gente conversar em 60 dias, na época da safra/obra?' — pergunta orientada a 'não'. Depois, nutrição a cada 60 dias.",
        ] },
        { tipo: "tabela", titulo: "Canal certo para cada momento", colunas: ["Canal", "Força", "Fraqueza", "Quando usar"], linhas: [
          ["WhatsApp texto", "Assíncrono, fica registrado, permite foto/vídeo", "Fácil de ignorar; áudio longo irrita", "Primeiro toque, envio de valor, confirmação"],
          ["Ligação", "Voz cria relação; permite diagnóstico rápido", "Interrompe; prospect na obra não atende", "Dia 3 e dia 17; 8h–9h ou 17h–18h"],
          ["Visita", "Ver a obra e a frota; presença física gera confiança", "Cara (R$ 80–150 por visita); exige rota", "Leads ICP ≥ 7 ou já em conversa"],
          ["Indicação / cliente em comum", "Prova social instantânea; abre porta fechada", "Depende de cuidar da base", "Quando o prospect não responde aos toques diretos"],
          ["E-mail", "Formal; serve para engenheiro e compras", "Interior lê pouco e-mail", "Prefeituras, construtoras com setor de compras"],
        ] },
        { tipo: "dialogo", titulo: "O toque 4: 'passei aqui'", falas: [
          { quem: "vendedor", texto: "(na obra) Seu Nelson? Edy, da New Holland. Te mandei mensagem semana passada sobre a obra do loteamento. Tava passando pra Alegre e resolvi parar dois minutos: trouxe a conta da B95C pra vala que você está abrindo aqui. Não vou tomar seu tempo, só deixo com você." },
          { quem: "cliente", texto: "Ah, você que mandou o negócio do consumo. Vi sim, só não respondi. Deixa eu ver isso aí." },
          { quem: "nota", texto: "A presença física com um motivo concreto (a conta) e a promessa de brevidade tiram a barreira. O prospect lembra dos toques anteriores: a familiaridade trabalhou." },
          { quem: "vendedor", texto: "Isso aqui é com 150 horas por mês; se você me disser quantas horas roda, eu ajusto. Quantas está rodando a que você tem?" },
          { quem: "cliente", texto: "Umas 180. E ela tá dando dor de cabeça." },
          { quem: "vendedor", texto: "Então vale a pena eu voltar com calma. Terça às 7h30, antes de você sair pra obra?" },
        ] },
        { tipo: "caso", titulo: "Caso: o vendedor que desistia no segundo toque", situacao: "Ao revisar o CRM, o gerente viu que o vendedor cadastrava 25 leads por mês, mas 70% tinham só um ou dois contatos registrados e status 'sem retorno'.", acao: "Implantou a cadência 7×21 com tarefas automáticas no CRM: cada lead novo recebia sete próximas ações datadas, cada uma com o conteúdo de valor a enviar.", resultado: "A taxa de resposta dos leads subiu de 11% para 38% em dois meses. As visitas dobraram sem aumentar o número de leads cadastrados.", licao: "O problema não era falta de leads: era desistir no toque em que a maioria das respostas ainda não veio. Cadência é disciplina, e disciplina se agenda." },
        { tipo: "script", titulo: "Os sete toques prontos (adapte o sinal)", itens: [
          "T1 (WhatsApp): 'Seu Nelson, Edy da New Holland Cachoeiro. Vi que vocês começaram o loteamento na ES-181. Fiz a conta de custo/hora de uma B95C pra vala nesse tipo de solo — te mando? É uma página.'",
          "T2 (ligação): 'Seu Nelson, Edy. Vinte segundos: te mandei a conta da retro pra vala do loteamento. Queria passar aí quinta 20 minutos pra ver o solo e ajustar os números. Às 8h ou às 16h?'",
          "T3 (WhatsApp): 'O Marcos, da Rio Novo, fez rede de água igual à sua com a B110B: 3.400 h em 2 anos sem parar. Foto dela na vala segue aqui. Se quiser, passo o contato dele.'",
          "T4 (visita): 'passei aqui' com a conta impressa e a promessa de dois minutos.",
          "T5 (indicação): 'Comentei com o Marcos que você está no loteamento; ele disse que te conhece da associação. Ele ficou de te mandar mensagem.'",
          "T6 (ligação): 'O Marcos comentou com você? Queria fechar aquela visita: terça 7h30?'",
          "T7 (WhatsApp): 'Seu Nelson, não quero ser inconveniente. Seria melhor a gente conversar depois que o loteamento estiver na fase de pavimentação? Me diz quando e eu volto.'",
        ] },
        { tipo: "erros", titulo: "Erros de cadência", itens: [
          "Sete toques com o mesmo conteúdo ('só passando pra saber'). Isso é insistência; valor novo em cada toque é cadência.",
          "Áudio de 2 minutos no WhatsApp para quem não te conhece. Máximo 15 segundos, e só depois de uma tentativa de ligação.",
          "Pular a ligação por medo. Voz converte 3x mais que texto no segundo toque.",
          "Não registrar os toques no CRM. Sem registro, você não sabe em qual toque está — e repete ou desiste.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escolha três leads do CRM sem resposta. Para cada um, escreva os sete toques com conteúdo específico (o sinal dele, um dado, um caso, um cliente em comum) e cadastre as sete próximas ações com data. Execute a primeira hoje." },
      ],
      missao: "Coloque cinco leads novos na cadência 7×21 esta semana, com as sete próximas ações datadas no CRM e o conteúdo de valor definido em cada uma. Registre no fim de 21 dias quantos responderam e em qual toque.",
      quiz: [
        { pergunta: "Um lead recebeu duas mensagens e uma ligação sem resposta em 6 dias. O vendedor conclui que 'não tem interesse' e para. Qual é o erro?", opcoes: [
          "A maioria das respostas vem entre o 4º e o 8º toque; parar no 3º é parar onde a concorrência também para, antes de a familiaridade agir",
          "Ele deveria ter enviado uma condição especial no terceiro toque, porque promoção é o que faz o lead silencioso responder",
          "Nenhum: três tentativas sem retorno em seis dias indicam falta de interesse, e insistir queima a relação para o futuro",
          "Ele deveria ter ligado três vezes em vez de mandar mensagem, porque texto é ignorado e só a voz obtém resposta no interior",
        ], correta: 0, explicacao: "Silêncio até o terceiro toque é a regra, não a exceção: o prospect ainda não sabe quem você é. Os toques seguintes, com valor diferente em cada um, constroem familiaridade. Desistir cedo é o erro mais caro da prospecção, e promoção sem relação é ruído." },
        { pergunta: "O que transforma sete contatos em três semanas de 'insistência' em 'cadência'?", opcoes: [
          "Espaçar mais os contatos, para no máximo um por semana, dando ao prospect tempo para responder sem se sentir cobrado",
          "Alternar os horários de envio das mensagens ao longo do dia, para encontrar o momento em que o prospect está disponível",
          "Usar sempre o mesmo canal, para o cliente se acostumar com o seu nome e reconhecer a sequência de contatos",
          "Entregar algo de valor diferente em cada toque (um dado, um caso, uma avaliação, um contato em comum) e variar o canal",
        ], correta: 3, explicacao: "O prospect tolera e até agradece contatos frequentes quando cada um traz algo útil e vem por caminhos diferentes. 'Só passando para saber' repetido sete vezes é insistência, independentemente do espaçamento. Valor e canal variado são a diferença." },
        { pergunta: "Qual é o papel do toque 5 (indicação / cliente em comum) na cadência?", opcoes: [
          "Confirmar, por meio de alguém que o conhece, se o prospect é realmente o decisor antes de gastar os toques seguintes",
          "Abrir a porta com prova social instantânea quando os contatos diretos ainda não obtiveram resposta",
          "Substituir a ligação, que o cliente do interior costuma não atender, por uma apresentação feita por um conhecido",
          "Pedir ao cliente em comum que sonde o preço que o prospect espera, para a proposta chegar já dentro do orçamento",
        ], correta: 1, explicacao: "Um nome conhecido do prospect faz o Sistema 1 dele baixar a guarda: 'se o Marcos conhece, posso ouvir'. É o toque que costuma destravar leads silenciosos, e depende de você cuidar da base para ter quem indique. Não substitui a ligação nem serve para negociar." },
        { pergunta: "Você está na rota e passa pela obra de um lead que não respondeu aos três primeiros toques. Qual conduta é a mais eficaz?", opcoes: [
          "Não parar, porque aparecer sem aviso depois de três toques sem resposta parece perseguição e pode queimar o lead",
          "Parar, apresentar-se em dois minutos com um motivo concreto (a conta impressa, a avaliação da usada) e propor visita com horário",
          "Parar e fazer a apresentação completa da máquina, porque ele está ali e a chance de encontrá-lo de novo é pequena",
          "Parar só para deixar um cartão com o encarregado e seguir viagem, mantendo o próximo toque da cadência por mensagem",
        ], correta: 1, explicacao: "A presença física com motivo e brevidade prometida derruba a barreira do silêncio e ativa a familiaridade dos toques anteriores. Apresentação completa sem hora marcada irrita; cartão com encarregado não chega ao decisor; não parar desperdiça o quilômetro já rodado." },
        { pergunta: "No toque 7 (dia 21) o prospect ainda não respondeu. Qual mensagem encerra o ciclo sem queimar a conta?", opcoes: [
          "'Vou entender seu silêncio como falta de interesse e encerrar o contato. Obrigado pela atenção'",
          "'Última chance: tenho uma condição especial que expira hoje. Depois disso volta a tabela'",
          "'Não quero ser inconveniente. Faz mais sentido a gente conversar na época da safra? Me diz quando e eu volto'",
          "'Vou continuar mandando novidades toda semana, quando tiver um tempo você me responde'",
        ], correta: 2, explicacao: "Pergunta orientada a 'não' e sem pressão devolve o controle ao prospect e costuma gerar a primeira resposta ('agora não, mas em setembro sim'). Ultimato e escassez falsa queimam; prometer mensagens semanais vira spam. O lead entra em nutrição a cada 60 dias." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m3a3", titulo: "A primeira mensagem: pertinência, valor e uma pergunta fácil", minutos: 13,
      resumo: "A primeira mensagem tem um objetivo só: receber resposta. Não vende máquina, não apresenta empresa, não manda catálogo. Mostra que você sabe algo sobre ele, entrega algo útil e faz uma pergunta que se responde em cinco segundos.",
      blocos: [
        { tipo: "p", texto: "Abra o WhatsApp de qualquer empreiteiro e você vai ver dez mensagens iguais: 'Bom dia, sou fulano da marca tal, gostaria de apresentar nossa linha de máquinas'. Nenhuma respondida. Elas falam do vendedor, não do cliente; pedem tempo sem dar nada; e a 'pergunta' ('posso apresentar?') exige um compromisso. A primeira mensagem que funciona inverte tudo: começa pelo mundo do cliente (o sinal), entrega algo que vale (dado, edital, avaliação, foto de máquina parecida trabalhando) e termina com uma pergunta que se responde com uma palavra." },
        { tipo: "framework", nome: "PVP — Pertinência, Valor, Pergunta fácil", origem: "Síntese das melhores práticas de cold outreach B2B (Weinberg, Blount) aplicada ao WhatsApp", passos: [
          "Pertinência (1 frase): o sinal específico. 'Vi que vocês começaram o loteamento na ES-181.' / 'O Marcos, da Rio Novo, comentou que você está com a pá parada.' Sem sinal, não envie.",
          "Valor (1–2 frases): algo útil agora. Uma conta de custo/hora para a aplicação dele, um edital, uma avaliação da usada, um dado de consumo, uma foto de máquina igual trabalhando em obra parecida.",
          "Pergunta fácil (1 frase): que se responde com sim/não/um número. 'Te mando? É uma página.' / 'Ela roda mais de 150 h por mês?' / 'Vale eu passar aí quinta?' Nunca 'posso apresentar a linha?'.",
          "Formato: 3 a 5 linhas, nome do cliente, seu nome e empresa, sem emoji em excesso, sem catálogo anexado, sem áudio.",
        ] },
        { tipo: "tabela", titulo: "Antes e depois", colunas: ["Mensagem que não recebe resposta", "Mensagem PVP"], linhas: [
          ["'Bom dia! Sou o Edy da New Holland, gostaria de apresentar nossa linha de escavadeiras. Posso te ligar?'", "'Seu Carlos, Edy da New Holland Cachoeiro. Vi que a Rocha Forte ganhou a pavimentação de Guaçuí. Fiz a conta de rolo CA2500 × aluguel pra 14 km de base — dá uma diferença que vale olhar. Te mando? É uma página.'"],
          ["'Olá, tudo bem? Segue nosso catálogo com toda a linha. Qualquer dúvida estou à disposição!'", "'Dona Rita, Edy da New Holland. O Sr. Osmar, da cooperativa, comentou do carreador novo do sítio. Tenho uma B95C usada revisada, 2.900 h, que os produtores de Iúna estão usando pra isso. Quer que eu mande a foto e o preço?'"],
          ["'Bom dia, alguma novidade sobre a proposta que enviei?'", "'Seu Jorge, uma coisa que pode mudar a conta que te mandei: saiu a linha do Plano Safra com juros menores esta semana. Vale eu refazer a parcela? Responde só sim que eu mando hoje.'"],
        ] },
        { tipo: "dialogo", titulo: "O que acontece depois do 'manda'", falas: [
          { quem: "cliente", texto: "Manda aí." },
          { quem: "vendedor", texto: "(envia a conta em uma página, com os números marcados como estimativa) Pronto. Usei 160 h/mês e diesel a R$ 6,20. Se me disser as horas reais, ajusto. Quantas está rodando?" },
          { quem: "nota", texto: "Entregou o prometido em minutos, admitiu as premissas e fez a próxima pergunta fácil (um número). Cada resposta do cliente é um passo do diagnóstico." },
          { quem: "cliente", texto: "Umas 200. Mas a minha tá boa ainda." },
          { quem: "vendedor", texto: "Com 200 h a diferença de consumo sozinha passa de R$ 2 mil por mês. Não precisa trocar agora; quando for pensar, vale ter esse número. Posso te chamar de novo perto da fase de aterro?" },
          { quem: "nota", texto: "Sem pressão: valor entregue, próximo contato combinado. O prospect passa a atender." },
        ] },
        { tipo: "caso", titulo: "Caso: 40 mensagens, 2 respostas → 40 mensagens, 17 respostas", situacao: "O vendedor mandava a mesma mensagem institucional para todos os leads. Em um mês: 40 envios, 2 respostas, nenhuma visita.", acao: "Passou a só enviar com sinal (edital, usada, obra vista, indicação), com valor (conta ou foto) e pergunta de sim/não. Cada mensagem levava 5 minutos para escrever em vez de 5 segundos para colar.", resultado: "Mês seguinte: 40 envios, 17 respostas, 6 visitas, 2 propostas. Mesmo esforço de envio, cinco vezes mais retorno.", licao: "Mensagem em massa é rápida de mandar e cara em resultado. Cinco minutos por mensagem é o melhor investimento de tempo da semana." },
        { tipo: "checklist", titulo: "Antes de apertar enviar", itens: [
          "Tem o nome do cliente e um sinal específico dele na primeira frase?",
          "Entrega algo que ele pode usar mesmo que não compre de mim?",
          "A pergunta se responde com sim/não/um número em 5 segundos?",
          "Cabe na tela do celular sem rolar (3 a 5 linhas)?",
          "Nada de catálogo anexado, áudio, 'gostaria de apresentar', 'à disposição'?",
        ] },
        { tipo: "erros", titulo: "Palavras e hábitos que matam a resposta", itens: [
          "'Gostaria de apresentar' / 'à disposição' / 'qualquer dúvida': linguagem de vendedor genérico.",
          "Catálogo em PDF na primeira mensagem: o cliente lê como propaganda e arquiva.",
          "Áudio para quem não te conhece: exige tempo e atenção que ele ainda não te deu.",
          "Perguntas abertas na primeira mensagem ('como está a frota?'): dão trabalho para responder.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue as cinco últimas primeiras mensagens que você enviou a leads (o histórico do CRM tem). Reescreva cada uma no formato PVP, com um sinal real do cliente e uma pergunta de sim/não. Compare o tamanho e o foco: quantas vezes aparecia 'eu/nós' antes e depois?" },
      ],
      missao: "Envie cinco primeiras mensagens PVP esta semana, uma por lead com sinal, sem catálogo e sem áudio. Registre no CRM o texto enviado e se houve resposta em 48 h. Meta: pelo menos duas respostas.",
      quiz: [
        { pergunta: "Qual das mensagens tem a maior chance de resposta de um empreiteiro que acabou de ganhar uma pavimentação?", opcoes: [
          "'Seu Carlos, Edy da New Holland. Vi que vocês ganharam a pavimentação de Guaçuí. Fiz a conta de rolo próprio × aluguel pros 14 km. Te mando? É uma página.'",
          "'Seu Carlos, parabéns pela licitação de Guaçuí! Segue nosso catálogo completo de rolos e motoniveladoras para a sua avaliação, com as condições vigentes.'",
          "'Olá Carlos, tudo bem? Vi a notícia da pavimentação. Como está o planejamento de frota para a obra nova? Fico à disposição para ajudar no que precisar.'",
          "'Bom dia, Carlos! Sou o Edy da New Holland de Cachoeiro e gostaria de apresentar nossa linha de rolos compactadores para a obra de Guaçuí. Posso te ligar?'",
        ], correta: 0, explicacao: "Pertinência (o edital ganho), valor (uma conta feita para a obra dele) e pergunta fácil ('te mando?'). As outras falam do vendedor, anexam propaganda ou fazem pergunta aberta que dá trabalho. A resposta 'manda' é o começo do diagnóstico." },
        { pergunta: "Por que 'posso te apresentar a linha?' é uma pergunta ruim para a primeira mensagem?", opcoes: [
          "Porque uma pergunta desse tipo deveria ser feita por ligação, onde o vendedor pode explicar o motivo, e não por texto",
          "Porque é curta demais e parece impessoal, e o prospect não tem como saber quem está perguntando nem por quê",
          "Porque não menciona a marca com clareza, e o prospect não consegue avaliar se vale a pena responder",
          "Porque pede um compromisso de tempo do cliente sem que ele tenha recebido nada, e responder 'sim' custa mais que ignorar",
        ], correta: 3, explicacao: "A primeira mensagem tem que ser mais fácil de responder do que de ignorar. 'Posso apresentar?' pede 30 minutos da agenda do cliente para ouvir sobre você. 'Te mando a conta? É uma página' pede uma palavra e dá algo em troca." },
        { pergunta: "O cliente respondeu 'manda aí' à sua conta de custo/hora. Qual é o próximo passo correto?", opcoes: [
          "Enviar a conta em minutos, explicitar as premissas e fazer a próxima pergunta fácil (as horas reais dele)",
          "Aproveitar a abertura e ligar imediatamente para agendar a visita, porque o 'manda aí' é o momento de maior receptividade",
          "Enviar a conta junto com o catálogo e a tabela de preços, porque ele demonstrou interesse e vai querer comparar",
          "Pedir os dados completos da frota antes de enviar, para fazer a conta exata e não correr o risco de mandar número errado",
        ], correta: 0, explicacao: "Cumprir o prometido rápido gera confiança; admitir as premissas gera credibilidade; a pergunta seguinte (um número) avança o diagnóstico sem pesar. Ligar na hora ou anexar tabela quebra o ritmo; condicionar o envio a dados quebra a promessa." },
        { pergunta: "Um vendedor manda 40 mensagens iguais por mês e recebe 2 respostas. O que mais provavelmente muda esse resultado?", opcoes: [
          "Aumentar para 120 mensagens por mês, porque com 5% de resposta o volume triplicado entrega seis respostas em vez de duas",
          "Escrever cada mensagem com sinal, valor e pergunta fácil, mesmo que leve cinco minutos cada",
          "Trocar o WhatsApp por e-mail, que é mais profissional e não se perde no meio das conversas pessoais do cliente",
          "Enviar as mensagens em horários diferentes ao longo do dia, para descobrir a janela em que o cliente costuma responder",
        ], correta: 1, explicacao: "O problema é o conteúdo, não o volume nem o horário. Mensagem genérica em massa é lida como spam; mensagem específica com valor é lida como ajuda. No caso real, o mesmo volume passou de 2 para 17 respostas ao trocar a cola pelo PVP." },
        { pergunta: "Qual elemento é obrigatório na primeira frase de uma mensagem de prospecção eficaz?", opcoes: [
          "O nome da marca e o cargo do vendedor, para o cliente saber de imediato com quem está falando",
          "Um cumprimento cordial e uma pergunta sobre como estão as coisas, para abrir a conversa com calor humano",
          "A promessa de que não vai tomar muito tempo, para reduzir a resistência de quem está ocupado na obra",
          "Um sinal específico do cliente que mostre que você sabe algo sobre a situação dele",
        ], correta: 3, explicacao: "A pertinência é o que faz o cliente continuar lendo: 'ele sabe da minha obra, então não é mensagem em massa'. Marca e cargo vêm depois, em meia linha. Cumprimentos genéricos e promessas de brevidade são preenchimento." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m3a4", titulo: "Ligação fria sem medo: 20 segundos para a visita", minutos: 13,
      resumo: "A ligação é o canal que mais converte e o que mais assusta. Uma abertura de 20 segundos, um único objetivo (a visita) e três respostas prontas para as três objeções que sempre aparecem.",
      blocos: [
        { tipo: "p", texto: "Texto é fácil de ignorar; voz, não. Por isso a ligação converte 3x mais que a mensagem no segundo toque, e por isso a maioria dos vendedores foge dela. O medo vem de não saber o que dizer nos primeiros segundos e de tentar vender a máquina ao telefone. Ligação fria não vende máquina: vende a visita. Vinte segundos de abertura, uma pergunta, uma proposta de horário. Se ele disser 'não', você aprendeu algo; se disser 'sim', você tem uma visita que valeria dez mensagens." },
        { tipo: "framework", nome: "Abertura de 20 segundos (4 partes)", origem: "Blount (telephone prospecting) e Weinberg (sales story), adaptado ao interior", passos: [
          "Identificação curta: 'Seu Nelson? Edy, da New Holland de Cachoeiro.' Sem 'tudo bem?', sem 'você tem um minutinho?'.",
          "Motivo pertinente: 'Vi o anúncio da sua retro' / 'O Marcos, da Rio Novo, me passou seu contato' / 'Vocês começaram o loteamento na 181'.",
          "Valor em uma frase: 'Estou avaliando usadas da região pra entrada em máquina nova e fazendo a conta de custo por hora pra quem está trocando.'",
          "Pedido único com alternativa de horário: 'Queria passar aí 20 minutos pra ver a máquina e te deixar a conta. Quinta 8h ou sexta 16h fica melhor?'",
        ] },
        { tipo: "script", titulo: "As três objeções da ligação e as respostas", itens: [
          "'Manda por WhatsApp' → 'Mando sim. Só que a conta muda com o solo e as horas, e eu prefiro ver antes pra não te mandar número errado. São 20 minutos. Quinta cedo?'",
          "'Não tô pensando em trocar agora' → 'Perfeito, não é pra trocar agora. É pra você ter o número na mão quando pensar. Você roda mais de 150 horas por mês com ela?' (diagnóstico continua)",
          "'Já tenho fornecedor' → 'Imaginei, e não vim tirar ninguém. Vim te dar uma segunda referência de preço e de assistência, que não custa nada ter. Se eu passar quinta às 8h, atrapalho?'",
        ] },
        { tipo: "dialogo", titulo: "Ligação de 90 segundos que virou visita", falas: [
          { quem: "vendedor", texto: "Seu Nelson? Edy, da New Holland de Cachoeiro. O Marcos, da Rio Novo, me passou seu contato — ele disse que você pegou o loteamento em Alegre." },
          { quem: "cliente", texto: "Peguei. Mas tô cheio de coisa, fala rápido." },
          { quem: "vendedor", texto: "Vinte segundos. Estou fazendo a conta de custo por hora pra quem está abrindo vala em solo igual ao daí, e avaliando usada pra entrada. Queria passar 20 minutos na obra e te deixar isso na mão. Quinta 8h ou sexta 16h?" },
          { quem: "cliente", texto: "Manda por WhatsApp que eu vejo." },
          { quem: "vendedor", texto: "Mando. Só que a conta muda com o solo e as horas, e eu prefiro ver antes pra não te mandar número errado. Quinta às 8h eu chego antes de você sair pro campo. Fechado?" },
          { quem: "cliente", texto: "Quinta às 8 então. Mas é rápido." },
          { quem: "nota", texto: "Perfil D ('fala rápido'): o vendedor cortou o rodeio, deu o motivo, o valor e o pedido com alternativa. Na objeção 'manda por WhatsApp', não discutiu: aceitou e insistiu na visita com um motivo técnico." },
        ] },
        { tipo: "caso", titulo: "Caso: o bloco de 10 ligações", situacao: "O vendedor fazia 'uma ou outra ligação' quando lembrava, quase sempre no meio da tarde, e desanimava a cada 'não'.", acao: "Passou a fazer um bloco fixo: terça e quinta, das 8h às 9h, 10 ligações seguidas, sem WhatsApp aberto, com a lista preparada no dia anterior e o script na mesa.", resultado: "Em quatro semanas: 80 ligações, 31 atendidas, 9 visitas marcadas, 2 propostas. O 'não' parou de doer porque virou estatística: 1 visita a cada 3,5 atendidas.", licao: "Ligação fria é um número, não um julgamento. Em bloco, com lista e script, o medo vira rotina — e a rotina vira visita." },
        { tipo: "tabela", titulo: "Horários e taxas típicas no interior", colunas: ["Horário", "Taxa de atendimento", "Por quê"], linhas: [
          ["7h30–9h", "Alta (35–45%)", "Dono ainda no escritório/casa, antes de ir para a obra"],
          ["9h–12h", "Baixa (15–20%)", "Na obra, barulho, não atende número desconhecido"],
          ["12h–13h30", "Média (25%)", "Almoço; atende, mas quer conversa curta"],
          ["17h–18h30", "Alta (30–40%)", "Voltando da obra, fechando o dia"],
          ["Segunda de manhã / sexta à tarde", "Baixa", "Segunda é planejamento; sexta é fim"],
        ] },
        { tipo: "erros", titulo: "Erros de ligação", itens: [
          "Abrir com 'tudo bem? tem um minutinho?': dá ao cliente a chance de dizer 'não' antes de saber o motivo.",
          "Tentar vender a máquina ao telefone: o objetivo é a visita; a conta se faz na obra.",
          "Aceitar 'manda por WhatsApp' como fim: é a objeção padrão, não um não.",
          "Ligar sem lista e sem script, 'quando dá': o bloco de 10 é o que faz o número funcionar.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Grave-se fazendo a abertura de 20 segundos para três leads diferentes (usada anunciada, indicação, obra vista). Cronometre. Ouça e corte tudo que não é identificação, motivo, valor ou pedido. Repita até caber em 20 segundos sem correr." },
      ],
      missao: "Faça um bloco de 10 ligações na terça e outro na quinta, entre 7h30 e 9h, com lista preparada na véspera. Registre no CRM cada ligação (atendida ou não, objeção, resultado). Meta: 3 visitas marcadas na semana.",
      quiz: [
        { pergunta: "Qual é o objetivo único de uma ligação fria para um empreiteiro?", opcoes: [
          "Apresentar a linha de produtos e as condições de financiamento em resumo",
          "Descobrir o orçamento disponível e o prazo de compra do cliente",
          "Marcar a visita à obra com dia e hora, e nada mais",
          "Enviar a proposta por WhatsApp logo depois da conversa",
        ], correta: 2, explicacao: "Tudo o que exige diagnóstico e conta se faz na obra. Ao telefone, cada minuto a mais tentando vender reduz a chance da visita. Abertura de 20 segundos, uma pergunta, uma proposta de horário com alternativa." },
        { pergunta: "O cliente diz 'manda por WhatsApp que eu vejo'. Qual resposta mantém a chance da visita sem ser inconveniente?", opcoes: [
          "'Claro, mando agora e depois te ligo para saber o que achou. Assim você vê com calma antes de a gente conversar.'",
          "'Mando sim. Só que a conta muda com o solo e as horas, e prefiro ver antes pra não te passar número errado. Quinta às 8h?'",
          "'Prefiro não mandar por mensagem, porque a proposta é personalizada e precisa ser explicada pessoalmente para não gerar dúvida.'",
          "'Tudo bem, mando por WhatsApp e fico no aguardo do seu retorno. Qualquer dúvida é só me chamar por aqui mesmo.'",
        ], correta: 1, explicacao: "'Manda por WhatsApp' é a objeção padrão, não uma recusa. Aceitar e dar um motivo técnico real para a visita (o número depende do que você vai ver) mantém o pedido com horário. Recusar o envio soa a arrogância; 'fico no aguardo' entrega o controle." },
        { pergunta: "Por que abrir a ligação com 'tudo bem? tem um minutinho?' reduz a taxa de sucesso?", opcoes: [
          "Porque dá ao cliente uma saída ('não tenho') antes de ele saber o motivo da ligação e soa a vendedor genérico",
          "Porque é informal demais para clientes de prefeitura e construtora, que esperam um tratamento mais protocolar",
          "Porque aumenta a duração da chamada em um momento em que o cliente ainda não decidiu se vai ouvir",
          "Porque o cliente do interior prefere ser tratado por 'senhor' e a abertura casual reduz o respeito pelo vendedor",
        ], correta: 0, explicacao: "As primeiras palavras definem se o cliente ouve o resto. Identificação curta e motivo pertinente ('o Marcos me passou seu contato') prendem a atenção; 'tem um minutinho?' é a deixa para desligar. Formalidade e custo não são o ponto." },
        { pergunta: "Qual prática torna a ligação fria sustentável e reduz o medo do 'não'?", opcoes: [
          "Delegar as ligações a um assistente ou ao setor administrativo e concentrar o tempo do vendedor nas visitas",
          "Ligar apenas para leads que já responderam a uma mensagem, o que evita rejeição e mantém a moral alta",
          "Fazer blocos fixos de 10 ligações, com lista preparada na véspera e script, em horários de alta taxa de atendimento",
          "Alternar cada ligação com uma pausa curta para recuperar a energia e não transmitir cansaço ao próximo cliente",
        ], correta: 2, explicacao: "Em bloco, o 'não' vira estatística (1 visita a cada 3 a 4 atendidas) e não julgamento pessoal. Lista e script eliminam a hesitação; horários de 7h30–9h e 17h–18h30 dobram o atendimento. Ligar só para quem respondeu joga fora o canal que mais converte." },
        { pergunta: "O cliente diz 'não estou pensando em trocar agora'. Qual resposta mantém o diagnóstico vivo sem pressionar?", opcoes: [
          "'Posso saber por que não? Sua máquina já tem muitas horas e a manutenção deve estar pesando.'",
          "'Entendo perfeitamente. Quando estiver pensando em trocar, me chama que eu venho com a proposta.'",
          "'Mas o preço vai subir na tabela nova do mês que vem, vale a pena antecipar a conversa.'",
          "'Sem problema, e nem precisa trocar agora. Só para você ter o número na mão: ela roda mais de 150 horas por mês?'",
        ], correta: 3, explicacao: "Concordar tira a pressão; 'ter o número na mão' oferece valor sem compromisso; a pergunta de diagnóstico (um número) mantém a conversa e revela se há caso. 'Me chama' entrega o controle; 'preço vai subir' é pressão; 'por que não?' acusa." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m3a5", titulo: "Indicação como sistema, não como sorte", minutos: 13,
      resumo: "Indicação é o lead mais barato e o que mais converte. Mas quase ninguém pede — e quem pede, pede errado. Gatilho, pedido específico, facilitação e retorno: quatro passos que transformam cliente satisfeito em fonte permanente.",
      blocos: [
        { tipo: "p", texto: "Um lead indicado fecha de 3 a 5 vezes mais do que um lead frio e custa perto de zero. Ainda assim, pesquisas com vendedores B2B mostram que menos de 20% pedem indicação de forma sistemática. O motivo é o desconforto: parece pedir favor. O consultor entende diferente: cliente satisfeito GOSTA de indicar — é reciprocidade e é status ('fui eu que indiquei o Edy'). O que falta não é vontade do cliente; é um pedido claro, no momento certo, com facilitação." },
        { tipo: "framework", nome: "Sistema de indicação em 4 passos (GPFR)", origem: "Prática de referral selling (Bill Cates) adaptada ao pós-venda de máquinas", passos: [
          "Gatilho: peça em momentos de satisfação medida — entrega técnica bem feita, marco de 30 dias sem problema, chamado de assistência resolvido rápido, revisão em dia. Nunca no meio de um problema.",
          "Pedido específico: não 'conhece alguém?' (resposta: 'vou pensar'). Sim: 'Você conhece algum empreiteiro em Alegre que esteja com máquina velha ou pegando obra nova?' — nicho + cidade + sinal.",
          "Facilitação: 'Posso mandar uma mensagem citando você, ou prefere me apresentar num grupo?' Tire o trabalho do cliente; a apresentação de 1 linha basta.",
          "Retorno: avise o resultado ('falei com o Zé, marquei visita, obrigado') e agradeça de forma proporcional — um jantar, uma revisão com desconto, um reconhecimento público. Cliente que vê o retorno indica de novo.",
        ] },
        { tipo: "dialogo", titulo: "O pedido na revisão de 30 dias", falas: [
          { quem: "vendedor", texto: "Seu Ari, 30 dias com a E145C. Como está o consumo?" },
          { quem: "cliente", texto: "Tá dando 14 litros por hora. Melhor que eu esperava." },
          { quem: "vendedor", texto: "Que bom que fechou com o que a gente calculou. Aproveitando: você conhece alguém em Vargem Alta ou Castelo que esteja com escavadeira velha ou pegando obra nova? Tô procurando exatamente esse tipo de situação." },
          { quem: "nota", texto: "Gatilho (30 dias, resultado confirmado) e pedido específico (nicho, cidades, sinal)." },
          { quem: "cliente", texto: "O Paulinho, de Castelo. Ele tá com uma Hyundai velha e reclama toda semana." },
          { quem: "vendedor", texto: "Perfeito. Posso mandar uma mensagem pra ele dizendo que você me indicou, ou prefere falar antes com ele?" },
          { quem: "cliente", texto: "Manda que eu falo com ele hoje também." },
          { quem: "vendedor", texto: "Obrigado. Te aviso como foi." },
          { quem: "nota", texto: "Facilitação e promessa de retorno. Na semana seguinte, o vendedor liga: 'marquei com o Paulinho, valeu'. Seu Ari vai indicar de novo." },
        ] },
        { tipo: "tabela", titulo: "Gatilhos de indicação no ciclo do cliente", colunas: ["Momento", "Por que funciona", "Como pedir"], linhas: [
          ["Entrega técnica", "Máquina nova, operador treinado, dono orgulhoso", "'Quem mais da sua turma está com máquina pra trocar?'"],
          ["30 dias / primeiro resultado", "Resultado confirmado (consumo, produção)", "Pedido com nicho + cidade + sinal"],
          ["Chamado resolvido rápido", "Alívio; percepção de assistência", "'Se conhecer alguém queimado com assistência, me apresenta'"],
          ["Revisão de 500 h / 1.000 h", "Contato de rotina, sem venda na mesa", "'E os vizinhos, alguém pegando obra?'"],
          ["Segunda compra", "Confiança máxima", "Pedir apresentação em grupo/associação"],
        ] },
        { tipo: "caso", titulo: "Caso: a cooperativa que virou canal", situacao: "Vendedor vendeu uma B95C para um produtor influente de uma cooperativa em Iúna. Fez a entrega técnica com capricho e visitou aos 30 dias.", acao: "No 30º dia, pediu uma apresentação no grupo de WhatsApp da cooperativa — não uma venda, uma apresentação: 'o Edy é quem fez a conta do meu carreador'. O produtor postou e marcou o vendedor.", resultado: "Onze produtores pediram a conta em duas semanas; quatro compraram em 8 meses (duas novas, duas usadas). O custo de prospecção dessas quatro vendas foi um almoço.", licao: "Uma indicação em grupo vale trinta ligações frias. Mas só existe se a entrega e o pós-venda forem impecáveis — indicação é o dividendo da confiança." },
        { tipo: "script", titulo: "Pedidos específicos por nicho", itens: [
          "Pedreira: 'Você conhece outra pedreira ou mineração que esteja aumentando produção ou reclamando de máquina parada?'",
          "Prefeitura (engenheiro): 'Você conhece o engenheiro de algum município vizinho que esteja montando termo de referência de frota?'",
          "Locação: 'Algum cliente seu que aluga há mais de um ano e talvez devesse comprar?'",
          "Café: 'Quem na sua cooperativa está abrindo carreador ou reformando estrada de sítio?'",
        ] },
        { tipo: "erros", titulo: "Erros de indicação", itens: [
          "Pedir 'conhece alguém?': genérico, gera 'vou pensar' e nunca volta.",
          "Pedir no meio de um problema (máquina parada, peça atrasada). Resolva primeiro, peça depois.",
          "Não dar retorno ao cliente que indicou. Ele fica sem saber se ajudou — e não indica mais.",
          "Não registrar a origem no CRM. Sem saber quem indica, você não sabe quem cuidar.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste seus 10 clientes mais satisfeitos (entregas sem problema, revisões em dia). Para cada um, escreva o pedido específico (nicho + cidade + sinal) e o gatilho mais próximo (revisão, marco, chamado). Cadastre como próxima ação no CRM." },
      ],
      missao: "Faça três pedidos de indicação específicos esta semana, nos gatilhos certos (marco de 30 dias, revisão, chamado resolvido). Registre no CRM cada lead indicado com a origem e dê retorno ao cliente que indicou em até 7 dias.",
      quiz: [
        { pergunta: "Qual é o pedido de indicação com maior chance de gerar um nome na hora?", opcoes: [
          "'Se você conhecer alguém que precise de máquina, me indica? Pode ser qualquer segmento.'",
          "'Você conhece algum empreiteiro em Alegre com máquina velha ou pegando obra nova?'",
          "'Você poderia me passar a lista dos seus contatos do setor para eu entrar em contato?'",
          "'Você me indicaria para os seus amigos se eu te desse um desconto na próxima revisão?'",
        ], correta: 1, explicacao: "Nicho, cidade e sinal fazem o cliente varrer a memória por um caso concreto; o cérebro responde a pergunta específica com nome específico. 'Alguém que precise' gera 'vou pensar'. Lista de contatos é invasivo; indicação comprada vira favor pago e perde o valor social." },
        { pergunta: "O cliente está com a máquina parada há dois dias esperando uma peça. Você tem a visita de rotina marcada. Qual conduta sobre indicação é correta?", opcoes: [
          "Pedir a indicação mesmo assim, porque a visita já está marcada, o roteiro deve ser cumprido e o problema é da assistência",
          "Pedir a indicação como forma de mostrar confiança na relação, demonstrando que o problema atual não abala a parceria",
          "Oferecer um desconto na peça atrasada em troca de uma indicação, compensando o transtorno e aproveitando a visita",
          "Não pedir; resolver o problema, acompanhar até a máquina voltar e pedir no gatilho seguinte (chamado resolvido, marco de 30 dias)",
        ], correta: 3, explicacao: "Indicação é dividendo de satisfação; pedir no meio de um problema é cobrar dividendo de prejuízo. O gatilho certo vem logo depois: chamado resolvido rápido gera alívio e vontade de retribuir. Trocar por desconto transforma reciprocidade em barganha." },
        { pergunta: "Por que dar retorno ao cliente que indicou é parte obrigatória do sistema?", opcoes: [
          "Porque o cliente que vê o resultado da indicação sente que ajudou e indica de novo; sem retorno, a fonte seca",
          "Porque o retorno cria a oportunidade natural de pedir uma segunda indicação na mesma conversa, dobrando o rendimento",
          "Porque o cliente que indicou pode esperar uma comissão ou vantagem pela venda gerada, e o retorno esclarece isso",
          "Porque o programa de relacionamento da fábrica exige registrar a origem de cada venda e informar o indicador",
        ], correta: 0, explicacao: "Indicar é um ato social; o indicador quer saber se valeu. 'Marquei com o Paulinho, obrigado' fecha o ciclo e reforça o comportamento. Quem não dá retorno recebe uma indicação só. O retorno não é para pedir outra na hora: é para manter a fonte viva." },
        { pergunta: "Um produtor influente postou no grupo da cooperativa 'o Edy é quem fez a conta do meu carreador'. O que esse tipo de apresentação tem de diferente de uma indicação individual?", opcoes: [
          "É menos eficaz, porque mensagens em grupo são ignoradas e ninguém responde em público sobre compra de máquina",
          "É equivalente a uma indicação individual, porque o que conta é a confiança em quem indica, não o número de pessoas",
          "Multiplica a prova social para dezenas de pares ao mesmo tempo, com o peso de alguém que eles conhecem, a custo zero",
          "Funciona só em cooperativas de café, porque empreiteiros e pedreiras não usam grupos para assuntos de negócio",
        ], correta: 2, explicacao: "Uma apresentação pública por alguém respeitado no grupo é prova social em escala: onze produtores pediram a conta em duas semanas no caso real. Empreiteiros, locadores e pedreiras também têm grupos e associações. O pré-requisito é entrega e pós-venda impecáveis." },
        { pergunta: "Qual é o gatilho mais forte para pedir indicação a um cliente de máquina nova?", opcoes: [
          "O dia da assinatura do contrato, quando o entusiasmo é máximo e o cliente ainda não teve tempo de encontrar defeitos",
          "Um marco com resultado confirmado (30 dias, consumo dentro do calculado) ou um chamado resolvido rápido",
          "Seis meses depois da compra, quando o cliente já esqueceu o preço pago e a máquina virou parte da rotina",
          "Qualquer momento em que houver contato, desde que o pedido seja específico e educado, porque o gatilho importa pouco",
        ], correta: 1, explicacao: "Satisfação MEDIDA é o que sustenta a indicação: 'deu 14 litros por hora, como você calculou'. Na assinatura ainda não há resultado; seis meses depois o entusiasmo esfriou. O pedido específico é necessário, mas o momento importa tanto quanto a forma." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m3a6", titulo: "Roteiro de campo: cada quilômetro tem que render", minutos: 14,
      resumo: "Uma visita custa entre R$ 80 e R$ 150 em combustível, tempo e desgaste. Roteiro por rota, prioridade por ICP, visita fria com método e a regra de nunca voltar de mãos vazias: é assim que 400 km viram três propostas.",
      blocos: [
        { tipo: "p", texto: "O vendedor de máquinas do interior vive na estrada: Cachoeiro a Guaçuí são 60 km; a Iúna, 100; a Mimoso, 50. Sem roteiro, ele faz 400 km para duas visitas e volta com a sensação de dia cheio e a agenda vazia. Com roteiro, os mesmos 400 km rendem seis visitas, duas 'passei aqui', três obras novas vistas e um edital lido no posto. A diferença não é esforço; é planejamento na noite anterior e a disciplina de tratar cada quilômetro como investimento com retorno medido." },
        { tipo: "conta", titulo: "Custo real de uma visita (carro próprio, 120 km ida e volta)", linhas: [
          ["Combustível: 120 km ÷ 11 km/L × R$ 6,20", "R$ 68"],
          ["Desgaste, pneu, manutenção (R$ 0,45/km)", "R$ 54"],
          ["Tempo: 2h de estrada + 1h de visita = 3h × valor da sua hora (R$ 40)", "R$ 120"],
          ["Custo por visita", "R$ 242"],
          ["Se o dia rende 2 visitas (400 km)", "R$ 480 por visita"],
          ["Se o dia rende 6 visitas em rota (400 km)", "R$ 160 por visita"],
        ], conclusao: "Mesmos 400 km, mesma gasolina: a visita custa três vezes menos quando o dia é roteirizado. E cada visita com ICP alto vale muito mais que R$ 160 em probabilidade de proposta." },
        { tipo: "framework", nome: "Roteiro semanal por rota e prioridade", origem: "Gestão de território em vendas de campo (territory management), adaptada às rotas do sul do ES", passos: [
          "Divida a carteira em 4 rotas (ex.: Guaçuí/Alegre; Iúna/Ibatiba; Castelo/Vargem Alta; Mimoso/Muqui/Atílio). Cada rota tem um dia fixo na semana; o quinto dia é escritório, ligações e propostas.",
          "Na noite anterior: liste os leads ICP ≥ 7 e clientes com marco de pós-venda da rota. Marque 3 visitas com hora (âncoras) e liste 3 'passei aqui' entre elas.",
          "Ordene por geografia (ida numa estrada, volta por outra) e por horário do cliente (dono no escritório às 7h30; engenheiro na prefeitura das 13h às 16h).",
          "Reserve 30 minutos no fim para a visita fria: obra nova vista na estrada, placa de terraplenagem, pátio de locadora.",
          "No retorno, antes de chegar em casa: registre tudo no CRM (o que viu, quem decide, próxima ação datada). Memória de estrada dura 24 horas.",
        ] },
        { tipo: "dialogo", titulo: "Visita fria: a obra vista da estrada", falas: [
          { quem: "vendedor", texto: "(no canteiro, para o encarregado) Bom dia. Edy, da New Holland de Cachoeiro. Vi a terraplenagem da estrada e parei. Obra é de quem?" },
          { quem: "cliente", texto: "Da Construtora Vale Verde, de Guaçuí. O engenheiro vem de tarde." },
          { quem: "vendedor", texto: "Que máquinas estão aqui? Vi uma escavadeira e um rolo." },
          { quem: "cliente", texto: "A escavadeira é nossa, o rolo é alugado. O rolo dá problema direto." },
          { quem: "nota", texto: "Duas perguntas ao encarregado e você já sabe: dono, um problema (rolo alugado quebrando) e quando o decisor aparece. Nada de vender para o encarregado." },
          { quem: "vendedor", texto: "Qual o nome do engenheiro? Vou deixar meu cartão com você e passo às 15h. Se ele estiver, ótimo; se não, mando mensagem." },
        ] },
        { tipo: "caso", titulo: "Caso: 1.800 km por mês, 4 propostas → 1.500 km, 11 propostas", situacao: "Vendedor rodava 1.800 km/mês 'atendendo quem chamava', voltando para a mesma cidade três vezes na semana.", acao: "Adotou rotas fixas por dia, âncoras marcadas na véspera, 'passei aqui' entre âncoras e a regra dos 30 minutos de visita fria. Passou a registrar no CRM no estacionamento antes de sair.", resultado: "Rodou 300 km a menos e quase triplicou as propostas. O número de obras novas descobertas passou de 1 para 7 por mês.", licao: "Rota não é rigidez: é a estrutura que deixa espaço para o inesperado (a obra nova) sem sacrificar o planejado (as âncoras)." },
        { tipo: "checklist", titulo: "Antes de sair (noite anterior) e ao voltar", itens: [
          "3 âncoras marcadas com hora e objetivo de cada uma (diagnóstico, proposta, avaliação, marco de pós-venda).",
          "3 'passei aqui' listados com motivo concreto (a conta impressa, a foto, o edital).",
          "Material no carro: calculadora do CRM no celular, fita métrica, cartões, folha da conta em branco, ficha de avaliação de usada.",
          "Diário Oficial da rota lido no café da manhã.",
          "Ao voltar: cada visita registrada no CRM com próxima ação datada; obras novas cadastradas como lead com pontuação.",
        ] },
        { tipo: "erros", titulo: "Erros de campo", itens: [
          "Sair sem âncora: dia 'de prospecção' que vira dia de café e conversa.",
          "Voltar à mesma cidade três vezes na semana porque 'o cliente chamou'. Agrupe: 'passo aí quinta, que é meu dia de Guaçuí'.",
          "Passar por obra nova e não parar 'porque estava atrasado'. Cinco minutos com o encarregado valem um lead.",
          "Registrar no CRM 'depois'. Depois é nunca; a próxima ação não datada morre.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue o seu mês passado: some os km rodados e conte visitas e propostas no CRM. Calcule o custo por visita. Depois desenhe as 4 rotas da sua carteira no mapa, atribua um dia a cada uma e liste, por rota, os leads ICP ≥ 7 e os clientes com marco de pós-venda. Esse é o seu roteiro do mês que vem." },
      ],
      missao: "Planeje a próxima semana por rota: um dia por rota, três âncoras com hora e três 'passei aqui' por dia, na véspera. Registre cada visita no CRM antes de sair do local. No fim da semana, calcule km rodados ÷ visitas e compare com o mês anterior.",
      quiz: [
        { pergunta: "Você rodou 400 km e fez duas visitas. Qual é a principal consequência econômica desse dia, segundo a conta da aula?", opcoes: [
          "O custo por visita triplica em relação a um dia roteirizado com seis visitas, e cada proposta fica proporcionalmente mais cara",
          "O custo é compensado pelo relacionamento construído em duas visitas longas, que vale mais que seis conversas apressadas",
          "O prejuízo se limita ao combustível e ao desgaste do carro, porque o tempo do vendedor é um custo fixo já pago",
          "Nenhuma relevante: o custo do dia é o mesmo, independentemente do número de visitas, e o que importa é a qualidade",
        ], correta: 0, explicacao: "Os 400 km custam o mesmo; o que muda é quanto cada visita carrega desse custo (R$ 480 contra R$ 160). Tempo do vendedor é o recurso mais caro da conta. Relacionamento importa, mas seis visitas em rota constroem mais relacionamento que duas." },
        { pergunta: "Qual é a função das 'âncoras' no roteiro diário?", opcoes: [
          "São os clientes mais antigos da rota, que devem ser visitados a cada passagem por lealdade e para defender a conta",
          "São visitas de cortesia para manter presença na cidade e ser lembrado quando alguém decidir comprar máquina",
          "São as três visitas marcadas com hora e objetivo, que estruturam o dia e garantem que ele não vire 'dia de café'",
          "São os pontos fixos de parada para registrar o CRM e revisar a rota, normalmente no posto ou na concessionária",
        ], correta: 2, explicacao: "Sem âncoras o dia de campo vira improviso. Três compromissos com hora e objetivo (diagnóstico, proposta, marco) definem a rota e o ritmo; os 'passei aqui' e a visita fria se encaixam entre eles. Lealdade e cortesia não são critérios: ICP e marco são." },
        { pergunta: "Você vê uma terraplenagem nova na estrada e está com 15 minutos de folga antes da próxima âncora. O que fazer?", opcoes: [
          "Parar e fazer a apresentação da linha ao encarregado, que costuma influenciar o engenheiro na escolha da marca",
          "Seguir viagem, porque a âncora tem prioridade, a obra estará lá na semana que vem e a rota já está planejada",
          "Fotografar a placa da obra e pesquisar o CNPJ depois, para chegar ao decisor com informação e sem improviso",
          "Parar, apresentar-se ao encarregado, perguntar de quem é a obra, que máquinas estão lá e quando o decisor aparece, sem vender",
        ], correta: 3, explicacao: "Cinco minutos com o encarregado rendem dono, problema atual (o rolo alugado que quebra) e horário do decisor: um lead com sinal. Vender ao encarregado é desperdício; deixar para depois é perder a janela (outros vendedores passam na mesma estrada)." },
        { pergunta: "Por que registrar a visita no CRM antes de sair do estacionamento do cliente, e não à noite ou no dia seguinte?", opcoes: [
          "Porque o CRM registra a data e a hora do lançamento e o gerente usa isso para conferir o cumprimento da rota",
          "Porque a memória dos detalhes (quem decide, o que viu, o que prometeu) se perde em horas, e a próxima ação sem data morre",
          "Porque a Central de Alertas processa os registros em tempo real e um atraso no lançamento adia os avisos do dia",
          "Porque o cliente pode ver o registro na linha do tempo e valoriza a agilidade com que o vendedor anota o combinado",
        ], correta: 1, explicacao: "Depois de três visitas os detalhes se misturam: qual cliente disse que o sócio decide? Qual prometeu ligar? O registro imediato, com próxima ação datada, é o que transforma a visita em negociação viva. 'Registro depois' é a principal causa de negociação abandonada." },
        { pergunta: "Um cliente de Guaçuí liga na segunda pedindo que você passe lá na terça 'rapidinho'. Sua rota de Guaçuí é quinta. Qual é a conduta que equilibra atendimento e território?", opcoes: [
          "Ir na terça, porque cliente que chama tem prioridade absoluta e a rota existe para servir o cliente, não o contrário",
          "Atender só por WhatsApp fora do dia da rota, explicando a política de território, para educar o cliente sobre os dias",
          "Ir na terça e cancelar as âncoras da rota de terça, remarcando para a semana seguinte, porque quem chama está mais quente",
          "Qualificar o motivo; sem urgência real, propor quinta com hora; com urgência (máquina parada, prazo), ir na terça e agrupar visitas",
        ], correta: 3, explicacao: "Rota é estrutura, não rigidez. A pergunta é: o que ele precisa e quando de verdade? A maioria dos 'rapidinho' cabe na quinta com hora marcada; a urgência real justifica quebrar a rota, e aí você agrupa para não desperdiçar os 120 km. Prioridade absoluta a quem chama destrói o território." },
      ],
    },
  ],
  prova: [
    { pergunta: "Um lead tem aplicação contínua, crédito aprovado e o dono é seu conhecido, mas não há nenhum sinal recente de compra. Qual é a pontuação e a ação corretas?", opcoes: [
      "ICP médio (falta 'momento'); nutrição a cada 60 dias com valor, até aparecer sinal, sem gastar visita agora",
      "ICP baixo; retirar do CRM, porque uma conta boa sem sinal ocupa espaço no funil e distorce a cobertura",
      "ICP alto; enviar proposta por WhatsApp para adiantar, porque crédito aprovado e aplicação contínua bastam",
      "ICP alto; visita esta semana, porque a conta é perfeita e o sinal vai aparecer durante a conversa",
    ], correta: 0, explicacao: "Aplicação, capacidade e acesso dizem que a conta é boa; a ausência de momento diz que ainda não é hora. Visita agora gasta o recurso mais caro sem urgência; excluir joga fora uma conta ótima. Nutrição mantém a familiaridade até o sinal." },
    { pergunta: "Qual das ações é a melhor resposta a uma usada anunciada ontem na OLX por um empreiteiro da sua região?", opcoes: [
      "Salvar o anúncio e ligar na semana seguinte, quando o anúncio já tiver esfriado e o cliente estiver mais aberto a negociar",
      "Enviar o catálogo de retroescavadeiras por WhatsApp com uma mensagem cordial, para ele conhecer a linha antes da conversa",
      "Ligar hoje perguntando se está trocando ou reduzindo a frota, oferecer avaliação da usada e propor visita com horário",
      "Perguntar no próprio anúncio quanto ele aceita pela máquina, para abrir a conversa pelo assunto que ele mesmo levantou",
    ], correta: 2, explicacao: "Sinal envelhece em 72 horas e o concorrente vê o mesmo anúncio. A pergunta de diagnóstico abre a conversa; a avaliação entrega valor; a visita com horário é o objetivo. Catálogo e pergunta de preço pulam o diagnóstico." },
    { pergunta: "Em qual faixa de toques costuma vir a maior parte das respostas em prospecção B2B, e onde a maioria dos vendedores para?", opcoes: [
      "Respostas no 1º e 2º toque; vendedores param no 5º",
      "Respostas entre o 4º e o 8º toque; vendedores param antes do 3º",
      "Respostas só depois do 10º toque; vendedores param no 7º",
      "Respostas concentradas no 3º toque; vendedores param no 3º",
    ], correta: 1, explicacao: "Esse descompasso é a maior oportunidade da prospecção: a maioria do mercado está esperando exatamente no toque em que a concorrência desistiu. Por isso a cadência 7×21, com valor em cada toque, é disciplina e não insistência." },
    { pergunta: "O que diferencia uma primeira mensagem PVP de uma mensagem institucional?", opcoes: [
      "A PVP é mais longa e detalha a linha de produtos, para o cliente ter tudo o que precisa numa mensagem só",
      "A PVP usa áudio em vez de texto, porque a voz cria proximidade e o cliente do interior prefere ouvir",
      "A PVP começa com um cumprimento, a apresentação da empresa e o motivo do contato, na ordem clássica",
      "A PVP começa por um sinal do cliente, entrega algo útil e faz uma pergunta que se responde em cinco segundos",
    ], correta: 3, explicacao: "Pertinência, valor e pergunta fácil. A mensagem fala do mundo do cliente, não do vendedor; dá antes de pedir; e pede uma palavra, não meia hora. Tudo em 3 a 5 linhas, sem catálogo nem áudio." },
    { pergunta: "Na ligação fria, o cliente diz 'já tenho fornecedor'. Qual resposta mantém a porta aberta?", opcoes: [
      "'Imaginei, e não vim tirar ninguém. Vim te dar uma segunda referência de preço e assistência, que não custa ter. Passo quinta às 8h?'",
      "'Tudo bem, então não vou insistir. Se algum dia precisar de uma segunda opção, guarda o meu contato. Obrigado pela atenção.'",
      "'Qual fornecedor? Me passa a última proposta dele que eu vejo se consigo cobrir com uma condição melhor ainda esta semana.'",
      "'Entendo, mas o nosso produto é superior em consumo e assistência; deixa eu te explicar por que vale a pena comparar.'",
    ], correta: 0, explicacao: "Concordar desarma; 'segunda referência' é valor sem ameaça à relação atual; o pedido de visita com horário mantém o objetivo. Atacar o fornecedor ativa a lealdade; desistir entrega o lead; cobrir proposta transforma a conversa em leilão antes do diagnóstico." },
    { pergunta: "Qual é o horário com maior taxa de atendimento para ligações a donos de empreiteira no interior?", opcoes: [
      "Entre 9h e 12h, quando o expediente está a pleno e o escritório da empreiteira já abriu",
      "Entre 14h e 16h, depois do almoço, quando o dono volta ao escritório para resolver pendências",
      "Entre 7h30 e 9h ou entre 17h e 18h30, antes de ir ou depois de voltar da obra",
      "Sexta à tarde, quando a semana está fechando e o dono está mais disponível para conversar",
    ], correta: 2, explicacao: "O dono atende quando está no escritório ou em casa, não no canteiro com barulho e número desconhecido na tela. O bloco de 10 ligações às 7h30 de terça e quinta é a rotina que faz o canal render." },
    { pergunta: "Qual formulação de pedido de indicação segue o método correto?", opcoes: [
      "'Se souber de alguém precisando de máquina, lembra de mim. Qualquer indicação ajuda muito.'",
      "'Você conhece alguma pedreira na região que esteja aumentando a produção ou reclamando de máquina parada?'",
      "'Pode me passar o contato de todos os seus fornecedores e clientes? Eu mesmo faço a abordagem.'",
      "'Se você me indicar três pessoas, eu te dou desconto na próxima revisão. É o nosso programa de indicação.'",
    ], correta: 1, explicacao: "Nicho + sinal + geografia faz o cliente lembrar de um nome concreto. Pedido genérico gera 'vou pensar'; pedir a agenda é invasivo; indicação comprada perde o valor social e vira barganha." },
    { pergunta: "Um cliente indicou um vizinho. Você visitou o vizinho e marcou uma proposta. Qual é o passo que a maioria pula e que garante a próxima indicação?", opcoes: [
      "Enviar um brinde institucional ao cliente que indicou, para reforçar a relação sem precisar ligar",
      "Pedir imediatamente outra indicação ao mesmo cliente, aproveitando que a primeira deu certo",
      "Avisar o cliente que indicou como foi e agradecer de forma proporcional",
      "Registrar a origem da indicação no CRM e seguir com a proposta, sem incomodar o indicador",
    ], correta: 2, explicacao: "O retorno fecha o ciclo: o indicador vê que ajudou e sente vontade de repetir. Registro no CRM é necessário, mas não substitui o retorno ao cliente. Brinde sem conversa e pedido imediato de outra indicação erram o tom." },
    { pergunta: "Por que a visita fria ao canteiro deve ser feita com o encarregado, e não como apresentação de produto?", opcoes: [
      "Porque o objetivo é coletar dono, problema atual, máquinas presentes e horário do decisor em cinco minutos, para prospectar quem decide",
      "Porque apresentar produto no canteiro sem autorização é vedado pelas normas de segurança do trabalho e pode gerar advertência",
      "Porque o encarregado pode recomendar a marca ao engenheiro em troca de um brinde ou de um treinamento para a equipe",
      "Porque o encarregado é o decisor de compra na maioria das obras pequenas e médias, e o dono só assina o que ele indica",
    ], correta: 0, explicacao: "O encarregado é fonte de informação, não comprador. Duas ou três perguntas rendem um lead com sinal (rolo alugado que quebra, engenheiro que vem à tarde). Vender a ele é desperdício e pode soar a tentativa de influência indevida." },
    { pergunta: "Um dia de campo roteirizado costuma ter qual estrutura?", opcoes: [
      "Uma cidade por dia, sem compromissos marcados, para ter flexibilidade e aproveitar o que aparecer no caminho",
      "Apenas visitas marcadas com antecedência, sem paradas não planejadas, para cumprir a agenda e respeitar os horários",
      "Visitar primeiro quem chamou, depois quem estiver no caminho, e registrar tudo à noite para não perder tempo em campo",
      "Três âncoras com hora e objetivo, 'passei aqui' entre elas, 30 minutos de visita fria e registro no CRM antes de sair de cada local",
    ], correta: 3, explicacao: "Âncoras dão estrutura; 'passei aqui' aproveita os toques da cadência; a visita fria captura obras novas; o registro imediato preserva a informação. Só marcadas perde o inesperado; só improviso perde o planejado." },
    { pergunta: "Qual é o custo por visita quando um dia de 400 km rende seis visitas, contra duas, segundo a conta da aula?", opcoes: [
      "Aproximadamente o mesmo, porque a gasolina e o desgaste do carro são iguais e o tempo do vendedor é custo fixo",
      "Cerca de três vezes menor (perto de R$ 160 contra R$ 480), porque tempo e desgaste se dividem por mais visitas",
      "Maior, porque seis visitas exigem mais tempo de conversa e o dia acaba custando horas extras do vendedor",
      "Impossível de calcular sem saber o valor das máquinas vendidas, porque o custo só faz sentido em relação ao resultado",
    ], correta: 1, explicacao: "O custo do dia (combustível, desgaste, tempo) é fixo; dividido por seis em vez de dois, cai para um terço por visita. E visita com ICP alto tem probabilidade maior de proposta, o que reduz ainda mais o custo por proposta." },
    { pergunta: "No toque 7 da cadência, sem resposta, o prospect recebe 'faz mais sentido a gente conversar na época da safra? me diz quando'. Ele responde 'em setembro'. O que fazer?", opcoes: [
      "Considerar o lead perdido, porque 'em setembro' é a forma educada de dizer não, e retirá-lo do CRM",
      "Insistir em uma visita agora, porque ele finalmente respondeu e o momento de maior receptividade é esse",
      "Registrar a próxima ação para agosto, com nutrição a cada 60 dias até lá, e voltar com um sinal (Plano Safra, caso de vizinho)",
      "Enviar a proposta imediatamente, para ele ter o número em mãos e comparar com calma até setembro",
    ], correta: 2, explicacao: "A resposta é um compromisso do prospect e uma data. O trabalho agora é manter a familiaridade com valor leve até lá e reaparecer um pouco antes com um motivo concreto. Insistir queima; proposta sem diagnóstico vira número frio." },
    { pergunta: "Qual é o maior erro de quem prospecta por lista fria de CNPJ sem sinal?", opcoes: [
      "Taxa de resposta abaixo de 3%, porque a mensagem não tem pertinência e o momento é aleatório",
      "Risco de violar regras de privacidade ao contatar empresas que não autorizaram o uso dos dados",
      "Dificuldade de registrar e qualificar centenas de leads no CRM sem informação sobre cada um",
      "Custo de compra da lista, que raramente se paga com o número de vendas geradas",
    ], correta: 0, explicacao: "Sem sinal não há pertinência, e sem pertinência a mensagem é spam. O mesmo tempo gasto lendo o Diário Oficial, olhando usadas anunciadas e visitando a base atual produz leads com momento, que respondem dez vezes mais." },
  ],
};
