import type { Modulo } from "./tipos";

export const M4: Modulo = {
  id: "m4", nivel: 4, titulo: "Prospecção e abertura de portas", tema: "Prospecção", cor: "#3dffa0",
  descricao: "Como encher o funil com os clientes certos: mapeamento, WhatsApp que gera resposta, visita fria, rede de indicação, compras públicas e cadência de follow-up.",
  objetivos: [
    "Mapear nichos e montar rotas que dobram as visitas.",
    "Escrever o primeiro contato de WhatsApp que gera resposta em 24 h.",
    "Abrir porta na obra, na pedreira e na lavoura sem parecer vendedor de porta em porta.",
    "Construir uma rede de indicação com quem atende o seu cliente antes de você.",
    "Entender como a prefeitura compra e como se posicionar antes do edital.",
    "Executar uma cadência de follow-up de 7 toques sem ser chato.",
  ],
  leituras: [
    "Jeb Blount — Fanatical Prospecting.",
    "Mike Weinberg — New Sales. Simplified.",
    "Lei 14.133/2021 (nova Lei de Licitações) — capítulos sobre pregão e registro de preços.",
  ],
  aulas: [
    {
      id: "m4a1", titulo: "Mapeamento de nichos e rota inteligente", minutos: 10,
      resumo: "Prospecção sem mapa é desperdício. Onde estão os compradores que você ainda não visita e como organizar a rota.",
      blocos: [
        { tipo: "lista", titulo: "Onde estão os compradores que você não visita", itens: [
          "Obras públicas anunciadas (diário oficial, site das prefeituras, notícias do Dashboard): quem ganhou a licitação precisa de máquina.",
          "Loteamentos e condomínios novos: terraplenagem, drenagem, pavimentação — retro, escavadeira, rolo.",
          "Pedreiras e serrarias de granito: escavadeira e pá para carregamento; troca quando o contrato de brita cresce.",
          "Cooperativas e sindicatos rurais: acesso a dezenas de produtores de uma vez; crédito rural na safra.",
          "Locadoras: compram em lote e trocam por hora rodada.",
          "Postos de combustível e lojas de peças: sabem quem tem máquina velha e quem está crescendo.",
          "Clientes da concorrência com máquina com 8+ anos: o cadastro de máquinas do CRM mostra a idade da frota.",
        ] },
        { tipo: "p", titulo: "Rota", texto: "Agrupe visitas por região (Granito, Caparaó, Litorânea, Serrana, Das Santas — como no CRM) e dedique um dia por semana a cada uma. Em cada rota, inclua 2 clientes ativos, 2 prospectos novos e 1 pós-venda. Prospectar sozinho cansa; misturar com atendimento mantém o dia produtivo." },
        { tipo: "tabela", titulo: "Fontes de prospecção e o que extrair", colunas: ["Fonte", "Sinal de compra", "Ação"], linhas: [
          ["Diário oficial / portal da prefeitura", "Licitação de obra ganha, ata de registro de preço de máquinas", "Visitar a empreiteira vencedora e o secretário de obras"],
          ["Notícias do setor (Dashboard)", "Obra anunciada, crédito liberado, preço do café subindo", "Contatar clientes do nicho beneficiado na mesma semana"],
          ["Cadastro de máquinas do CRM", "Máquina com 8+ anos ou horas altas", "Oferecer avaliação da usada e plano de renovação"],
          ["Grupos de WhatsApp de operadores e empreiteiros", "Quem pede máquina de aluguel com frequência", "Abordar com a conta aluguel x parcela"],
          ["Cooperativa de café", "Calendário de crédito da safra", "Palestra/visita técnica em conjunto com o agrônomo"],
        ] },
        { tipo: "destaque", titulo: "Meta de prospecção", texto: "5 novos contatos qualificados por semana enchem o funil o ano inteiro. Registre todos no CRM, mesmo os que disserem “agora não” — o painel de 30+ dias sem contato do Dashboard vai lembrar você." },
        { tipo: "caso", titulo: "Caso: o loteamento que virou 3 vendas", situacao: "Vendedor viu placa de loteamento novo em Marataízes. Não conhecia ninguém envolvido.", acao: "Foi à obra, conversou com o encarregado, descobriu a empreiteira e o engenheiro. Cadastrou os três no CRM. Ofereceu uma visita técnica gratuita para dimensionar a frota da terraplenagem.", resultado: "A empreiteira comprou uma retro e um rolo; o engenheiro indicou a pá para outro loteamento em Itapemirim.", licao: "Uma placa de obra é um funil inteiro. Entre, pergunte, cadastre." },
      ],
      missao: "Monte a rota das próximas 3 semanas por região no CRM: em cada dia de campo, 2 clientes ativos, 2 prospectos novos (de fontes diferentes) e 1 pós-venda.",
      quiz: [
        { pergunta: "Qual fonte indica um comprador quase certo de máquina nos próximos 60 dias?", opcoes: ["Anúncio de máquina usada à venda", "Empreiteira que acabou de ganhar licitação de obra", "Posto de gasolina"], correta: 1, explicacao: "Obra ganha exige máquina; o prazo da obra cria a urgência." },
        { pergunta: "Como organizar o dia de campo?", opcoes: ["Visitas espalhadas por 3 regiões", "Uma região por dia, misturando ativos, prospectos e pós-venda", "Só prospectos novos"], correta: 1, explicacao: "Rota por região dobra visitas; a mistura mantém energia e resultado." },
      ],
    },
    {
      id: "m4a2", titulo: "Primeiro contato pelo WhatsApp que gera resposta", minutos: 10,
      resumo: "A maioria das mensagens de prospecção é ignorada. Estrutura, gatilhos e modelos por nicho para receber resposta em 24 h.",
      blocos: [
        { tipo: "lista", titulo: "Anatomia da mensagem que funciona", itens: [
          "Quem você é em 5 palavras + de onde vem o contato (indicação, obra, evento). Contato sem origem é spam.",
          "Um motivo específico dele: a obra, a máquina antiga, a licitação, a safra. Mostra que você pesquisou.",
          "Uma oferta de valor sem venda: avaliação da usada, conta de custo por hora, comparativo, visita técnica.",
          "Uma pergunta fechada e fácil: “posso passar aí quinta de manhã?” Não “quando você pode?”.",
          "Máximo de 5 linhas. Sem PDF na primeira mensagem. Sem preço.",
        ] },
        { tipo: "script", titulo: "Modelos por nicho", itens: [
          "Construtora (indicação): “Fulano, aqui é o Edy, da New Holland em Cachoeiro. O Zé da Construtora X me passou seu contato — ele disse que vocês pegaram a obra do loteamento. Eu faço uma conta rápida de custo por hora da frota pra saber se compensa retro própria ou aluguel. Posso passar aí quinta às 9h?”",
          "Pedreira: “Fulano, Edy da New Holland. Vi que a pedreira está carregando com uma escavadeira de 2012. Eu faço avaliação da usada e uma conta de consumo por tonelada com a E215C — sem compromisso. Quarta de tarde dá?”",
          "Café (cooperativa): “Fulano, Edy da New Holland. O agrônomo Beltrano comentou do terraceamento que você quer fazer antes da safra. Tenho retro com braço extensível que resolve isso sem escavadeira. Quer que eu passe na lavoura sexta pra ver o terreno?”",
          "Prefeitura: “Secretário, Edy da New Holland Construction. Vi a ata de registro de preços de motoniveladora publicada. Posso apresentar a RG140B e o atendimento de assistência em 24 h na região? Tenho quinta ou sexta de manhã.”",
          "Locadora: “Fulano, Edy da New Holland. Sei que a locadora está com fila pra retro. Tenho condição de frota (2+ unidades) e valor de revenda que segura o seu retorno por hora. Te ligo amanhã às 10h ou prefere outro horário?”",
        ] },
        { tipo: "tabela", titulo: "Antes e depois", colunas: ["Mensagem fraca", "Por que falha", "Versão forte"], linhas: [
          ["“Bom dia! Tudo bem? Sou vendedor da New Holland, temos ótimas condições. Posso te apresentar?”", "Sem origem, sem motivo dele, sem oferta, pergunta aberta", "“Fulano, Edy da New Holland — o Zé me indicou. Vi a obra da ponte. Faço a conta de retro própria x aluguel em 10 min. Quinta 9h?”"],
          ["“Segue nosso catálogo em anexo.”", "PDF sem conversa é lixo", "“Te mando o comparativo depois que eu entender a sua aplicação. Que tipo de material vocês movimentam?”"],
          ["“Qual o melhor dia pra você?”", "Pergunta aberta = sem resposta", "“Quinta 9h ou sexta 14h?”"],
        ] },
        { tipo: "lista", titulo: "Regras do primeiro contato", itens: [
          "Sem resposta em 48 h: segunda mensagem curta com um dado novo (foto de máquina trabalhando na região, notícia, condição). Nunca “viu minha mensagem?”.",
          "Sem resposta na segunda: ligue. Sem atender: terceira mensagem em 7 dias com outro ângulo.",
          "Respondeu “não”: agradeça, pergunte se pode manter contato e registre a data de retorno no CRM.",
          "Respondeu “manda preço”: “Mando sim — só me diz a aplicação e se tem usada na troca pra eu mandar a condição certa, não uma genérica.”",
        ] },
        { tipo: "destaque", titulo: "CRM", texto: "Registre cada tentativa (mensagem, ligação, visita) na conversa do cliente. O Orientador de Vendas mostra quem não respondeu e sugere o próximo toque." },
      ],
      missao: "Escreva 5 mensagens de primeiro contato para 5 prospectos reais de nichos diferentes, seguindo a anatomia. Envie e registre no CRM as respostas em 48 h.",
      quiz: [
        { pergunta: "Qual elemento não pode faltar no primeiro contato?", opcoes: ["Preço", "Origem do contato e um motivo específico do cliente", "Catálogo em PDF"], correta: 1, explicacao: "Sem origem e sem motivo, a mensagem é spam. Preço e PDF vêm depois do diagnóstico." },
        { pergunta: "Cliente não respondeu em 48 h. Você manda:", opcoes: ["“Viu minha mensagem?”", "Uma mensagem curta com um dado novo (foto, notícia, condição)", "A mesma mensagem de novo"], correta: 1, explicacao: "Cada toque precisa de valor novo. Cobrança irrita." },
        { pergunta: "Cliente responde só “manda preço”. Melhor resposta:", opcoes: ["Manda a tabela", "Pede aplicação e usada na troca para mandar a condição certa", "Ignora"], correta: 1, explicacao: "Transforme o pedido de preço em diagnóstico curto. Condição certa fecha; genérica compara." },
      ],
    },
    {
      id: "m4a3", titulo: "Visita fria e abertura no campo", minutos: 9,
      resumo: "Chegar numa obra, pedreira ou lavoura sem convite e sair com um contato qualificado: postura, abertura e o que levar.",
      blocos: [
        { tipo: "script", titulo: "Na obra", itens: [
          "Ao encarregado: “Bom dia, sou o Edy da New Holland. Não vim vender nada agora — estou passando pelas obras da região pra conhecer as frotas. Quem cuida das máquinas aqui?”",
          "Ao operador: “Essa retro tá com quantas horas? Ela tá dando conta? O que você mudaria nela?” (o operador conta tudo — e influencia o dono).",
          "Ao dono/engenheiro (por telefone, se não estiver): “Estive na obra hoje, conversei com o Zé. Vocês estão com a retro de 2011 pesando na manutenção. Faço uma avaliação dela e uma conta de troca sem compromisso. Posso te ligar amanhã às 10h?”",
        ] },
        { tipo: "lista", titulo: "Saindo com resultado", itens: [
          "Nome e telefone de quem decide (não só do encarregado).",
          "Frota atual: modelos, ano, horas, problemas (fotos com permissão).",
          "Tipo de obra e prazo.",
          "Um próximo passo combinado: ligação, avaliação da usada, visita técnica.",
          "Cadastro completo no CRM antes de sair do estacionamento.",
        ] },
        { tipo: "tabela", titulo: "Abertura por ambiente", colunas: ["Ambiente", "Com quem falar primeiro", "Gancho"], linhas: [
          ["Obra de construção", "Encarregado / mestre de obras", "Frota, prazo, aluguel de máquina"],
          ["Pedreira / serraria", "Gerente de produção ou mecânico", "Horas da escavadeira, ciclo de carregamento, peças"],
          ["Lavoura de café", "O próprio produtor ou o gerente", "Terraceamento, estrada interna, preparo pré-safra"],
          ["Prefeitura", "Secretário de obras ou chefe da garagem", "Estado da frota, período de chuva, ata de registro"],
          ["Locadora", "Dono", "Fila de locação, taxa de ocupação, revenda"],
        ] },
        { tipo: "erros", titulo: "Erros da visita fria", itens: [
          "Chegar vendendo. Chegue perguntando.",
          "Ignorar o operador. Ele é o informante e o influenciador.",
          "Deixar cartão e ir embora. Saia com telefone do decisor e próximo passo.",
          "Entrar em área de risco sem EPI. Bota, capacete e colete no carro sempre.",
          "Não registrar no CRM. A visita que não é registrada nunca existiu.",
        ] },
        { tipo: "caso", titulo: "Caso: o operador que vendeu a máquina", situacao: "Vendedor parou numa obra de drenagem em Piúma. O dono não estava.", acao: "Conversou 15 minutos com o operador da retro antiga: ela superaquecia, o ar não funcionava, e ele já tinha reclamado ao dono. O vendedor pediu o contato do dono e ligou citando o que o operador disse (com a permissão dele).", resultado: "O dono marcou a visita na hora: “se o Zé está reclamando, é sério”. Fechou uma B110B em 30 dias.", licao: "O operador é o melhor argumento que você pode levar ao dono." },
      ],
      missao: "Faça 4 visitas frias esta semana (uma por tipo de ambiente). Saia de cada uma com o contato do decisor e um próximo passo registrado no CRM.",
      quiz: [
        { pergunta: "Ao chegar numa obra sem conhecer ninguém, a melhor abertura é:", opcoes: ["“Vim apresentar as condições da New Holland”", "“Estou conhecendo as frotas da região; quem cuida das máquinas aqui?”", "Deixar o cartão na portaria"], correta: 1, explicacao: "Chegar perguntando abre porta; chegar vendendo fecha." },
        { pergunta: "O que é obrigatório para a visita fria ter valido a pena?", opcoes: ["Ter falado de preço", "Ter o contato do decisor e um próximo passo combinado", "Ter deixado um catálogo"], correta: 1, explicacao: "Sem decisor e próximo passo, foi um passeio." },
      ],
    },
    {
      id: "m4a4", titulo: "Rede de indicação: quem atende o seu cliente antes de você", minutos: 10,
      resumo: "Contador, agrônomo, engenheiro, mecânico, loja de peças, cooperativa, banco: como transformar quem já é consultor do seu cliente em fonte constante de indicação.",
      blocos: [
        { tipo: "p", texto: "Antes de comprar uma máquina, o cliente conversa com o contador (parcela), o agrônomo (aplicação), o engenheiro (obra), o mecânico (a antiga), o gerente do banco (crédito) e a loja de peças (custo de manutenção). Cada um desses profissionais atende dezenas de clientes seus. Uma parceria bem feita com cinco deles vale mais que 100 visitas frias." },
        { tipo: "tabela", titulo: "Parceiros e o que oferecer em troca", colunas: ["Parceiro", "O que ele sabe", "O que você oferece"], linhas: [
          ["Contador", "Quem vai bem, quem precisa investir, quem tem crédito", "Indicação mútua, simulação de financiamento pronta para os clientes dele, palestra sobre Finame/depreciação"],
          ["Agrônomo / cooperativa", "Quem vai preparar terreno, calendário de crédito rural", "Visita técnica conjunta, conteúdo sobre mecanização, participação em dia de campo"],
          ["Engenheiro / projetista", "Obras que vão começar e a frota necessária", "Dimensionamento gratuito de frota, ficha técnica para projeto, prioridade de atendimento"],
          ["Mecânico / oficina", "Quem tem máquina cansada e cara de manter", "Indicação de serviço, peças originais, treinamento; e você indica a oficina para revisões fora de garantia"],
          ["Loja de peças / posto", "Quem gasta muito em manutenção e diesel", "Indicação mútua, ficar com o cartão no balcão, brindes"],
          ["Gerente de banco / cooperativa de crédito", "Quem tem limite aprovado e busca investimento", "Cliente com documentação pronta; parceria em campanhas de crédito"],
        ] },
        { tipo: "script", titulo: "Propondo a parceria", itens: [
          "“Contador, boa parte dos meus clientes é sua também. Quando um deles for investir em máquina, me manda que eu monto a simulação com Finame e depreciação do jeito que você precisa. E quando um cliente meu precisar de contador, eu indico você. Faz sentido?”",
          "“Doutor, eu dimensiono a frota das obras dos seus projetos sem custo — retro, escavadeira, rolo, com o custo por hora. Isso ajuda o seu cliente a orçar certo. Posso fazer pro próximo?”",
        ] },
        { tipo: "lista", titulo: "Como manter a rede viva", itens: [
          "Cadastre cada parceiro no CRM como contato e registre cada indicação recebida e dada.",
          "Retribua rápido: indicação recebida = agradecimento no mesmo dia e retorno sobre o resultado.",
          "Visite cada parceiro uma vez por mês, sem pedir nada — leve uma novidade (campanha, lançamento).",
          "Reconheça publicamente (com permissão): “o agrônomo Beltrano me apresentou o Fulano”.",
          "Nunca deixe um parceiro mal: atenda o indicado com prioridade máxima.",
        ] },
        { tipo: "caso", titulo: "Caso: o contador de 7 clientes", situacao: "Vendedor conheceu um contador em Guaçuí que atendia 40 empreiteiros e produtores.", acao: "Ofereceu montar simulações de Finame com impacto fiscal para os clientes dele, e passou a indicar o contador para clientes novos.", resultado: "Em 18 meses, 7 máquinas vendidas por indicação direta desse contador.", licao: "Um parceiro certo é um funil que trabalha sem você." },
      ],
      missao: "Escolha 5 parceiros potenciais (um de cada tipo), faça a proposta de parceria pessoalmente esta semana e cadastre-os no CRM com o campo de origem de indicação.",
      quiz: [
        { pergunta: "Qual parceiro sabe primeiro quem vai investir em máquina?", opcoes: ["O posto de gasolina", "O contador e o gerente do banco", "O concorrente"], correta: 1, explicacao: "Quem cuida do dinheiro do cliente sabe quando ele pode e vai investir." },
        { pergunta: "O que mantém uma parceria de indicação viva?", opcoes: ["Só pedir indicação", "Retribuir rápido, dar retorno e atender o indicado com prioridade", "Brindes"], correta: 1, explicacao: "Parceria é troca. Quem só recebe é esquecido." },
      ],
    },
    {
      id: "m4a5", titulo: "Compras públicas: como a prefeitura compra e como se posicionar antes do edital", minutos: 12,
      resumo: "Pregão, ata de registro de preços, orçamento anual, emendas: entenda o ciclo e influencie a especificação antes de ela ser publicada.",
      blocos: [
        { tipo: "p", texto: "Prefeitura não compra por impulso nem por relação: compra por processo. Mas o processo começa muito antes do edital — no planejamento anual, no termo de referência escrito pelo secretário e na especificação técnica. Quem chega quando o edital sai, chega atrasado. Quem ajuda a escrever o termo de referência com a especificação correta (sem direcionar ilegalmente) chega na frente." },
        { tipo: "lista", titulo: "O ciclo da compra pública de máquinas", itens: [
          "Demanda: secretário de obras/agricultura identifica a necessidade (estrada, patrolamento, frota velha).",
          "Orçamento: precisa estar previsto (LOA) ou vir de emenda parlamentar, convênio (estado/federal) ou financiamento.",
          "Termo de referência: descrição técnica da máquina, garantia, assistência, prazo de entrega. É aqui que a venda se decide.",
          "Pesquisa de preços: a prefeitura pede orçamentos para formar o valor de referência — responda rápido e certo.",
          "Edital (pregão eletrônico na maioria dos casos) ou adesão a ata de registro de preços existente.",
          "Disputa, habilitação, homologação, empenho, entrega e recebimento.",
        ] },
        { tipo: "tabela", titulo: "Como se posicionar em cada fase", colunas: ["Fase", "Sua ação"], linhas: [
          ["Antes (demanda)", "Visite o secretário de obras e o chefe da garagem a cada 60 dias. Conheça a frota, o período de chuva, as estradas críticas. Leve casos de municípios vizinhos."],
          ["Orçamento", "Informe sobre linhas de financiamento para município, consórcios públicos e prazos de emenda. Entregue material que o vereador/deputado possa usar para justificar a emenda."],
          ["Termo de referência", "Ofereça a ficha técnica completa e as exigências de garantia/assistência que protegem o município (e que a concorrência mais fraca não atende). Sempre dentro da lei."],
          ["Pesquisa de preços", "Responda em 24 h, com a especificação exata, validade e condições reais. Preço fora da realidade prejudica o processo."],
          ["Edital", "Leia inteiro. Veja prazo de entrega, garantia, assistência, treinamento. Participe com a equipe da concessionária."],
          ["Depois", "Entrega técnica impecável e assistência rápida: o secretário vira referência para os municípios vizinhos."],
        ] },
        { tipo: "script", titulo: "Abordagem ao secretário", itens: [
          "“Secretário, não vim falar de licitação. Vim entender a situação da frota antes do período de chuva. Quais estradas mais dão problema? Como está a motoniveladora?”",
          "“Posso deixar com o senhor a especificação técnica completa da RG140B com os itens de garantia e assistência que os municípios vizinhos exigiram? Serve de base para o termo de referência do jeito que proteger a prefeitura.”",
        ] },
        { tipo: "destaque", titulo: "Ética e lei", texto: "Ajudar a especificar bem é legítimo e serve ao município. Direcionar edital com exigência sem justificativa técnica é ilegal e destrói a sua reputação. Sempre trabalhe com a equipe da concessionária e dentro da Lei 14.133." },
        { tipo: "caso", titulo: "Caso: a ata do vizinho", situacao: "Prefeitura de um município do Caparaó precisava de retro, mas não tinha tempo para licitar antes da chuva.", acao: "O vendedor mostrou que a prefeitura vizinha tinha ata de registro de preços vigente com a B95C, e que era possível aderir (carona) com a documentação certa. Ajudou o setor de compras com os documentos.", resultado: "Adesão em 30 dias, entrega antes da chuva. Dois municípios viraram referência um do outro.", licao: "Conhecer os instrumentos (ata, adesão, consórcio) é vender para prefeitura sem esperar edital." },
      ],
      missao: "Liste as prefeituras da sua região com o nome do secretário de obras e do chefe da garagem. Agende uma visita de relacionamento (sem edital) com 3 delas neste mês e registre a frota atual no CRM.",
      quiz: [
        { pergunta: "Quando a venda para a prefeitura se decide de verdade?", opcoes: ["No dia do pregão", "No termo de referência e no relacionamento antes do edital", "Na entrega"], correta: 1, explicacao: "A especificação é escrita antes. Quem chega no edital chega tarde." },
        { pergunta: "A prefeitura precisa de máquina antes da chuva e não tem tempo de licitar. Caminho possível:", opcoes: ["Compra direta sem processo", "Adesão a ata de registro de preços vigente de outro município", "Esperar o próximo ano"], correta: 1, explicacao: "A adesão (carona) a ata é instrumento legal e rápido quando bem documentado." },
        { pergunta: "Ajudar a escrever a especificação técnica é:", opcoes: ["Sempre ilegal", "Legítimo quando tecnicamente justificado e sem direcionamento", "Inútil"], correta: 1, explicacao: "Especificação boa protege o município. Direcionamento sem justificativa é crime." },
      ],
    },
    {
      id: "m4a6", titulo: "Cadência de follow-up: 7 toques sem ser chato", minutos: 10,
      resumo: "80% das vendas precisam de 5+ contatos e 90% dos vendedores param no 2º. A sequência, o conteúdo de cada toque e quando parar.",
      blocos: [
        { tipo: "p", texto: "Follow-up não é cobrar. É entregar valor em doses, em canais diferentes, até o momento certo do cliente chegar. Cada toque precisa de um motivo que interesse a ele: um dado, uma foto, uma notícia, uma condição, uma pergunta nova. “Passando pra saber se você viu a proposta” não é toque — é ruído." },
        { tipo: "tabela", titulo: "Cadência de 7 toques (30 dias)", colunas: ["Toque", "Quando", "Canal", "Conteúdo"], linhas: [
          ["1", "Dia 0", "WhatsApp", "Primeiro contato com origem, motivo e pergunta fechada"],
          ["2", "Dia 2", "WhatsApp", "Foto/vídeo de máquina trabalhando no mesmo nicho na região"],
          ["3", "Dia 5", "Ligação", "“Te liguei pra entender a aplicação e não te mandar coisa errada.” Se não atender, mensagem de 2 linhas"],
          ["4", "Dia 9", "WhatsApp", "Notícia ou dado do setor (preço do café, obra anunciada, campanha de financiamento) com uma frase ligando a ele"],
          ["5", "Dia 14", "Visita", "Passar na obra/lavoura “porque estava na região” — com um material de valor (comparativo, avaliação da usada)"],
          ["6", "Dia 21", "WhatsApp", "Caso de cliente parecido com número no final"],
          ["7", "Dia 30", "WhatsApp ou ligação", "Mensagem de encerramento: “vou parar de te incomodar; se fizer sentido no futuro, me chama. Posso te mandar novidades a cada 2 meses?”"],
        ] },
        { tipo: "lista", titulo: "Regras", itens: [
          "Cada toque tem valor novo. Nunca repita o anterior.",
          "Alterne canais: texto, áudio, ligação, visita. O cérebro responde a variedade.",
          "Toque curto: 3 linhas ou 30 segundos.",
          "Pergunta fechada no fim de cada um.",
          "Respondeu “não agora”: pergunte quando e registre a data no CRM. Volte no dia.",
          "Encerramento educado (toque 7) gera mais resposta que a maioria dos toques anteriores — o cliente sente a perda.",
          "Depois do encerramento: contato de relacionamento a cada 60 dias (novidade, campanha, aniversário da máquina).",
        ] },
        { tipo: "script", titulo: "Toques prontos", itens: [
          "Toque 2: “Fulano, essa é a B95C da Construtora X carregando em Cachoeiro ontem [vídeo]. A aplicação é parecida com a sua obra. Vale 10 minutos na quinta?”",
          "Toque 4: “Fulano, saiu hoje: campanha de Finame com taxa reduzida até dia 30. Pra retro é a melhor condição do ano. Quer que eu simule com a sua usada na entrada?”",
          "Toque 7: “Fulano, não quero ser inconveniente. Vou parar por aqui — se em algum momento a máquina virar prioridade, me chama que eu resolvo rápido. Posso te mandar uma novidade a cada 2 meses?”",
        ] },
        { tipo: "caso", titulo: "Caso: a venda do toque 7", situacao: "Empreiteiro de Castelo não respondeu 6 toques em 30 dias.", acao: "O vendedor mandou a mensagem de encerramento educada.", resultado: "Resposta em 20 minutos: “desculpa, estava numa obra em Minas. Semana que vem posso. Manda a condição da usada.” Fechou em 25 dias.", licao: "Silêncio nem sempre é “não”. A cadência completa, com encerramento, é o que separa o vendedor que colhe do que desiste." },
      ],
      missao: "Escolha 10 prospectos do CRM sem resposta e aplique a cadência de 7 toques por 30 dias, registrando cada toque. Compare a taxa de resposta com a sua média anterior.",
      quiz: [
        { pergunta: "O que define um bom toque de follow-up?", opcoes: ["Perguntar se viu a proposta", "Entregar um valor novo (dado, foto, notícia, caso) com uma pergunta fechada", "Repetir a mensagem anterior"], correta: 1, explicacao: "Sem valor novo, é cobrança. Com valor novo, é serviço." },
        { pergunta: "Cliente não respondeu 6 toques. O 7º deve ser:", opcoes: ["Mais insistente", "Um encerramento educado pedindo permissão para contato esporádico", "Nada, desista em silêncio"], correta: 1, explicacao: "O encerramento educado ativa a aversão à perda e costuma gerar resposta." },
        { pergunta: "Por que alternar canais?", opcoes: ["Para gastar menos", "Porque variedade chama atenção e alcança o cliente onde ele está", "Não faz diferença"], correta: 1, explicacao: "Texto, áudio, ligação e visita atingem o cliente em momentos e humores diferentes." },
      ],
    },
  ],
  prova: [
    { pergunta: "Qual é a meta mínima semanal de contatos novos qualificados?", opcoes: ["1", "5", "20"], correta: 1, explicacao: "5 por semana enchem o funil o ano todo." },
    { pergunta: "O que torna a mensagem de primeiro contato aceitável e não spam?", opcoes: ["Preço e catálogo", "Origem do contato, motivo específico dele, oferta de valor e pergunta fechada", "Emoji e bom dia"], correta: 1, explicacao: "Anatomia da mensagem que gera resposta." },
    { pergunta: "Na visita fria, com quem você conversa primeiro se o dono não está?", opcoes: ["Ninguém, volta depois", "Encarregado e operador", "Vizinho"], correta: 1, explicacao: "Eles informam e influenciam. Saia com o contato do decisor." },
    { pergunta: "Qual parceiro tende a gerar mais indicações de compra de máquina?", opcoes: ["Contador, agrônomo e engenheiro", "Posto de gasolina", "Rádio local"], correta: 0, explicacao: "Quem já é consultor de confiança do cliente." },
    { pergunta: "O momento decisivo da venda para prefeitura é:", opcoes: ["O pregão", "O termo de referência e o relacionamento anterior", "A entrega"], correta: 1, explicacao: "A especificação é escrita antes do edital." },
    { pergunta: "Cada toque de follow-up precisa de:", opcoes: ["Cobrança educada", "Valor novo e pergunta fechada", "Desconto"], correta: 1, explicacao: "Valor em doses até o momento do cliente chegar." },
  ],
};
