import type { Modulo } from "./tipos";

export const M4: Modulo = {
  id: "m4", nivel: 4, titulo: "Diagnóstico consultivo", tema: "Perguntas", cor: "#fbbf24",
  descricao: "A venda se ganha no diagnóstico, não na apresentação. SPIN por nicho, o gap entre a situação atual e a desejada em reais, MEDDICC adaptado à máquina pesada, perguntas calibradas e escuta, o mapa dos decisores (dono, sócio, financeiro, operador, engenheiro, pregoeiro) e a coragem de desqualificar.",
  objetivos: [
    "Conduzir uma visita de diagnóstico com as quatro camadas do SPIN, adaptadas a pedreira, prefeitura, café, locação e terraplenagem.",
    "Quantificar o gap entre a situação atual e a desejada em reais por mês, com os números do cliente.",
    "Qualificar cada negociação com o MEDDICC adaptado: métrica, comprador econômico, critérios, processo, dor, campeão e concorrência.",
    "Fazer perguntas calibradas que revelam a objeção real e o decisor oculto, e ouvir mais do que falar (regra 70/30).",
    "Mapear os decisores e influenciadores de cada conta e o que cada um precisa ouvir.",
    "Desqualificar cedo as negociações sem gap, sem dinheiro ou sem acesso, e liberar o tempo para as que fecham.",
  ],
  leituras: [
    "Neil Rackham — SPIN Selling: a pesquisa que separou perguntas que vendem de perguntas que irritam.",
    "Keenan — Gap Selling: a venda acontece na diferença entre onde o cliente está e onde quer estar.",
    "Jack Napoli / MEDDIC: qualquer guia prático do MEDDICC (origem na PTC, anos 1990) — o checklist de qualificação das grandes vendas.",
    "Chris Voss — Negocie como se sua vida dependesse disso: perguntas calibradas e escuta ativa.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m4a1", titulo: "SPIN na obra: situação, problema, implicação, necessidade", minutos: 15,
      resumo: "Rackham analisou 35 mil visitas e descobriu que os vendedores de alto valor fazem menos perguntas de situação e muito mais de implicação. Quem pergunta 'e o que isso causa?' vende; quem pergunta 'quantas máquinas você tem?' dez vezes irrita.",
      blocos: [
        { tipo: "p", texto: "SPIN é a espinha dorsal do diagnóstico consultivo. Situação: fatos (frota, horas, serviço). Problema: o que dói (paradas, consumo, atraso). Implicação: o que a dor causa em cadeia (multa, aluguel, obra perdida, operador que sai). Necessidade de solução: o cliente descrevendo, com as próprias palavras, o que resolveria. O erro do amador é ficar nas perguntas de situação (que ele podia ter descoberto antes) e pular direto para a apresentação. O erro do intermediário é achar o problema e apresentar. O consultor cava a implicação até o cliente sentir o tamanho do buraco — e só então deixa o cliente pedir a solução." },
        { tipo: "framework", nome: "SPIN (Rackham) com proporção certa", origem: "Neil Rackham — SPIN Selling (Huthwaite, pesquisa em 35.000 visitas em 23 países)", passos: [
          "Situação (10% do tempo): só o que você não conseguiu descobrir antes. 'Quantas horas por mês a escavadeira roda?' — o resto (frota, obras, cidade) você pesquisou no CRM, no Diário Oficial e com o encarregado.",
          "Problema (20%): 'O que mais dá dor de cabeça nela?' 'Onde a produção trava?' 'O que o operador reclama?' Ouça; anote a palavra exata que ele usa.",
          "Implicação (50%): 'Quando ela para, o que acontece com o caminhão? E com a medição? Quanto custa cobrir com aluguel? O que o cliente de vocês diz?' Cada implicação aumenta o custo da inação na cabeça dele.",
          "Necessidade de solução (20%): 'Se ela não parasse, o que mudaria no mês?' 'O que uma máquina com assistência a 40 km resolveria pra você?' — o cliente vende para si mesmo; você só confirma.",
        ] },
        { tipo: "tabela", titulo: "Banco de perguntas por nicho", colunas: ["Nicho", "Problema", "Implicação", "Necessidade"], linhas: [
          ["Pedreira", "Quantos caminhões ficam esperando na pá?", "Cada caminhão parado 10 min custa quanto? E na safra, quando o frete sobe?", "Se carregasse um caminhão a mais por hora, o que mudaria no faturamento?"],
          ["Prefeitura", "Quantos dias por mês a patrol fica parada?", "O que acontece com a estrada da zona rural na chuva? Quantas reclamações chegam?", "Se a frota tivesse 95% de disponibilidade, o que a secretaria entregaria?"],
          ["Café", "Quanto custa terceirizar o carreador por safra?", "Quando o terceiro atrasa, o que acontece com a colheita? E com o preço do café molhado?", "Ter máquina própria na fazenda resolveria o quê, na época certa?"],
          ["Locação", "Quantos dias por mês a máquina alugada fica ociosa ou quebrada?", "Cliente que fica na mão volta? Quanto custa perder um contrato de 12 meses?", "Se a disponibilidade fosse 95%, quantos contratos a mais você atenderia?"],
          ["Terraplenagem", "Quanto sai de aluguel de cobertura quando a retro para?", "Medição atrasada gera multa? Quanto? Quantas obras você perdeu por prazo?", "Com a máquina sem parar, quantas obras a mais dá para pegar?"],
        ] },
        { tipo: "dialogo", titulo: "Cavando a implicação", falas: [
          { quem: "vendedor", texto: "O que mais te dá dor de cabeça na escavadeira hoje?" },
          { quem: "cliente", texto: "Ela para de vez em quando. Coisa de mangueira, bomba… normal de máquina velha." },
          { quem: "vendedor", texto: "Quando ela para, o que acontece com o caminhão que está esperando?" },
          { quem: "cliente", texto: "Fica parado. Às vezes mando embora e o frete eu pago do mesmo jeito." },
          { quem: "vendedor", texto: "E a obra? A medição da prefeitura é por etapa, né? Um dia parado atrasa a etapa?" },
          { quem: "cliente", texto: "Atrasa. Mês passado perdi a medição de maio por dois dias. Só entrou em junho." },
          { quem: "nota", texto: "Três perguntas de implicação e o 'normal de máquina velha' virou frete pago à toa mais um mês de caixa atrasado. O vendedor ainda não falou de máquina." },
          { quem: "vendedor", texto: "Se ela não parasse, o que mudaria no seu mês?" },
          { quem: "cliente", texto: "Eu pegava a obra de Alegre também. Hoje não pego porque não confio nela." },
          { quem: "nota", texto: "Necessidade de solução, dita pelo cliente: uma obra a mais. Agora a máquina nova tem um valor com nome." },
        ] },
        { tipo: "caso", titulo: "Caso: 22 perguntas de situação", situacao: "Vendedor novo gravou (com autorização) uma visita de diagnóstico. Contagem: 22 perguntas de situação, 3 de problema, 0 de implicação, 0 de necessidade. Apresentação: 25 minutos.", acao: "Com o gerente, reescreveu a visita: pesquisou situação antes (CRM, Diário, encarregado), levou 4 perguntas de problema e 8 de implicação. Apresentação: 5 minutos, só o que respondia às implicações levantadas.", resultado: "Na visita seguinte, o cliente disse 'nunca tinha parado pra somar isso' e pediu a proposta. A conversão visita → proposta do vendedor subiu de 30% para 55% em três meses.", licao: "Perguntas de situação servem para você; perguntas de implicação servem para o cliente. Ele decide com as segundas." },
        { tipo: "checklist", titulo: "Preparação da visita de diagnóstico (15 min antes)", itens: [
          "Situação já levantada: frota, cidade, obras em andamento, quem decide, histórico no CRM.",
          "Três perguntas de problema escritas para o nicho dele.",
          "Cinco perguntas de implicação encadeadas (parada → caminhão → medição → multa → obra perdida).",
          "Uma pergunta de necessidade ('se isso não acontecesse, o que mudaria?').",
          "Calculadora do CRM aberta para somar na frente dele quando a implicação virar número.",
        ] },
        { tipo: "erros", titulo: "Erros de diagnóstico", itens: [
          "Interrogatório de situação: 'quantas máquinas, de que ano, quantos operadores…' por 15 minutos. O cliente sente que está trabalhando para você.",
          "Apresentar assim que ouve o primeiro problema. O problema sem implicação ainda é pequeno na cabeça dele.",
          "Fazer a implicação por ele ('isso deve custar caro, né?'). A implicação tem que sair da boca do cliente.",
          "Não anotar as palavras exatas. 'Não confio nela' é a frase que você vai usar na proposta e no fechamento.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para o seu principal nicho, escreva 3 perguntas de problema, 8 de implicação encadeadas e 2 de necessidade. Leia em voz alta: parecem perguntas de amigo que entende do assunto ou de vendedor que quer vender? Ajuste até soarem como as primeiras." },
      ],
      missao: "Na próxima visita de diagnóstico, leve as perguntas prontas e conte: quantas de situação, problema, implicação e necessidade você fez. Registre no CRM as palavras exatas do cliente na implicação e na necessidade. Meta: mais implicação do que situação.",
      quiz: [
        { pergunta: "O cliente diz que a escavadeira 'para de vez em quando, normal de máquina velha'. Qual é a próxima pergunta mais valiosa?", opcoes: [
          "'Quantos anos ela tem e quantas horas marca? E qual foi a última grande manutenção?'",
          "'Você já pensou em trocar por uma nova com garantia, para acabar com essa preocupação?'",
          "'Qual é o modelo, quem faz a manutenção e de onde vêm as peças quando ela para?'",
          "'Quando ela para, o que acontece com o caminhão que está esperando e com a medição?'",
        ], correta: 3, explicacao: "O cliente minimizou o problema ('normal'). A pergunta de implicação faz ele mesmo descobrir a cadeia: frete pago à toa, medição atrasada, obra não pega. Perguntas de situação (anos, modelo) não mudam nada; oferecer a nova agora apresenta antes de o buraco ter tamanho." },
        { pergunta: "Segundo a pesquisa de Rackham, o que distingue os vendedores de alto desempenho em vendas de alto valor?", opcoes: [
          "Fazem muito mais perguntas de implicação e necessidade e menos de situação",
          "Fazem mais perguntas de situação para demonstrar interesse e conhecer a operação",
          "Usam técnicas de fechamento com mais frequência e em momentos mais precisos",
          "Apresentam o produto mais cedo para aproveitar o tempo curto da visita",
        ], correta: 0, explicacao: "A pesquisa em 35 mil visitas mostrou que perguntas de situação em excesso irritam, técnicas de fechamento reduzem o sucesso em vendas grandes e a apresentação precoce é o erro clássico. O que vende é a implicação que faz o cliente sentir o custo do problema." },
        { pergunta: "Por que a implicação deve sair da boca do cliente e não ser afirmada pelo vendedor ('isso deve custar caro, né?')?", opcoes: [
          "Porque o vendedor não conhece os números do cliente e qualquer afirmação seria um chute que ele pode contestar",
          "Porque afirmar implicações é uma forma de pressão que os códigos de ética comercial recomendam evitar",
          "Porque o que o cliente diz ele acredita e defende; o que o vendedor afirma ele desconta como argumento de venda",
          "Porque o cliente pode se ofender com uma estimativa de prejuízo feita por alguém de fora da empresa",
        ], correta: 2, explicacao: "É o mesmo princípio da conta com os números do cliente: a conclusão dita por ele é dele. 'Perdi a medição de maio' tem peso; 'você deve perder medição' é chute de vendedor. Conhecimento dos números e ofensa não são o ponto: é propriedade da conclusão." },
        { pergunta: "Um vendedor fez 22 perguntas de situação em uma visita. Qual é o efeito mais provável no cliente?", opcoes: [
          "Ele se sente ouvido e valoriza o interesse genuíno do vendedor pela operação da empresa",
          "Ele fornece todos os dados necessários para uma proposta precisa e sem retrabalho",
          "Ele confia mais no vendedor, porque a quantidade de perguntas demonstra método e preparo",
          "Ele sente que está trabalhando para o vendedor e perde o interesse antes de chegar ao que importa",
        ], correta: 3, explicacao: "Perguntas de situação servem ao vendedor, não ao cliente. Em excesso, viram interrogatório. Rackham mediu: quanto mais perguntas de situação, menor o sucesso. Frota, obras e cidade se pesquisam antes; na visita, pergunte o que dói e o que isso causa." },
        { pergunta: "O cliente responde à pergunta de necessidade: 'se ela não parasse, eu pegava a obra de Alegre também'. O que o consultor faz com essa frase?", opcoes: [
          "Sugere que ele alugue uma segunda máquina para pegar a obra de Alegre agora, enquanto a compra da nova é decidida",
          "Registra as palavras exatas e as usa como o valor central da proposta e do fechamento ('a máquina que deixa você pegar Alegre')",
          "Pergunta qual é o valor da obra de Alegre e o prazo de execução, para dimensionar a máquina e a proposta",
          "Passa a apresentar a máquina, porque a necessidade foi identificada e o cliente está pronto para ouvir a solução",
        ], correta: 1, explicacao: "A necessidade dita pelo cliente é o argumento mais forte da venda, porque é dele. Ela vai para a proposta escrita, para a conversa com o sócio e para o fechamento. Apresentar agora ainda é cedo: falta quantificar o gap (próxima aula) e mapear quem decide." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m4a2", titulo: "Gap Selling: o buraco entre hoje e o desejado, em reais", minutos: 14,
      resumo: "Keenan resume: sem gap, não há venda. O cliente compra a diferença entre onde está e onde quer estar. Seu trabalho é medir esse buraco em reais por mês, com ele, e mostrar que a máquina é a ponte — ou dizer que não é.",
      blocos: [
        { tipo: "p", texto: "Depois do SPIN você tem a dor e as implicações. O Gap Selling transforma isso em uma conta com três colunas: estado atual (com número), estado desejado (com número) e o gap (a diferença mensal em reais). O gap é o tamanho do problema, e o tamanho do problema define o quanto o cliente aceita investir. Gap de R$ 2 mil por mês não justifica uma parcela de R$ 9 mil; gap de R$ 15 mil justifica com folga e ainda sobra argumento para o sócio. Quem não mede o gap negocia preço; quem mede negocia retorno." },
        { tipo: "conta", titulo: "Gap mensal: pá-carregadeira na pedreira (estado atual × desejado)", linhas: [
          ["Atual: 38 caminhões/dia × 22 dias, 3 paradas/mês de 1 dia", "836 caminhões/mês"],
          ["Desejado: 44 caminhões/dia (pá 20% mais rápida), 0,5 parada/mês", "946 caminhões/mês"],
          ["Diferença: 110 caminhões × R$ 380 de margem por carga", "R$ 41.800/mês"],
          ["Consumo: 3 L/h a menos × 200 h × R$ 6,20", "R$ 3.720/mês"],
          ["Aluguel de cobertura nas paradas evitadas (2,5 dias × R$ 1.800)", "R$ 4.500/mês"],
          ["Gap total", "R$ 50.020/mês"],
          ["Parcela da W170B (FINAME 60 meses, usada de entrada)", "R$ 17.400/mês"],
        ], conclusao: "O gap é quase três vezes a parcela. A conversa deixa de ser 'a W170B custa R$ 890 mil' e vira 'a pedreira deixa R$ 50 mil por mês na mesa enquanto não troca'. Se o gap fosse R$ 10 mil, a resposta honesta seria: mantém a máquina atual e reforça a manutenção." },
        { tipo: "framework", nome: "Gap em 5 passos", origem: "Keenan — Gap Selling", passos: [
          "Estado atual com número: produção, horas, paradas, consumo, custos de cobertura. Pergunte e anote; não estime.",
          "Impacto do atual: o que esses números causam (frete perdido, multa, obra não pega, cliente insatisfeito). Vem do SPIN.",
          "Estado desejado com número: 'quanto você precisaria carregar por dia para pegar o contrato da usina?' O cliente define a meta.",
          "Gap em reais por mês: desejado menos atual, em dinheiro. Some com ele, na Calculadora do CRM.",
          "Ponte e veredito: a máquina fecha o gap? Se sim, a parcela ao lado do gap. Se não, diga — e ganhe a próxima venda pela honestidade.",
        ] },
        { tipo: "dialogo", titulo: "Definindo o estado desejado", falas: [
          { quem: "vendedor", texto: "Hoje você carrega 38 caminhões por dia. Pra pegar o contrato da usina, quanto precisaria?" },
          { quem: "cliente", texto: "Uns 45. Hoje eu não consigo, por isso ainda não fechei com eles." },
          { quem: "vendedor", texto: "E cada caminhão deixa quanto de margem, mais ou menos?" },
          { quem: "cliente", texto: "Uns 380 reais." },
          { quem: "vendedor", texto: "Então sete caminhões a mais por dia, em 22 dias, são 154 cargas… R$ 58 mil por mês que hoje ficam na mesa. Pode conferir aqui na calculadora." },
          { quem: "nota", texto: "O estado desejado veio do cliente (45 caminhões, contrato da usina). O gap foi somado na frente dele. A parcela ainda não apareceu — e quando aparecer, vai parecer pequena." },
          { quem: "cliente", texto: "Nunca tinha feito essa conta. E a máquina dá 45?" },
          { quem: "vendedor", texto: "A W170B, com caçamba de 3,5 m³, carrega um basculante em 4 ciclos e meio. Vamos medir na sua pedreira com o seu operador antes de eu te prometer qualquer número." },
        ] },
        { tipo: "caso", titulo: "Caso: o gap que não fechou", situacao: "Produtor de café pediu proposta de uma B95C nova. O vendedor mediu: terceirização de carreador custava R$ 22 mil por safra; máquina própria pouparia R$ 14 mil por ano e teria 300 horas de uso.", acao: "Mostrou o gap (R$ 1.200/mês) ao lado da parcela (R$ 7.800/mês) e disse: 'não fecha; não compra nova. Se quiser máquina própria, uma usada de R$ 120 mil ou o consórcio em 4 anos.'", resultado: "O produtor entrou no consórcio, indicou dois vizinhos ('o Edy me falou pra NÃO comprar') e, três anos depois, comprou uma nova quando arrendou a fazenda vizinha e o gap passou a fechar.", licao: "Dizer que o gap não fecha custa uma venda hoje e rende três amanhã. No interior, o vendedor que manda não comprar vira referência." },
        { tipo: "tabela", titulo: "Gap × parcela: como ler o resultado", colunas: ["Relação gap ÷ parcela", "Leitura", "Ação"], linhas: [
          ["Abaixo de 1", "A máquina não se paga com a produção atual", "Não vender nova; usada, consórcio, ou esperar sinal (nova obra)"],
          ["Entre 1 e 1,5", "Fecha apertado; sensível a diesel e a paradas", "Vender com cautela; entrada maior, prazo mais longo, garantia de recompra"],
          ["Entre 1,5 e 3", "Saudável; caso típico de troca de máquina velha", "Proposta com a conta lado a lado; sócio convence-se"],
          ["Acima de 3", "Gap grande; o cliente está perdendo dinheiro todo mês", "Urgência real: 'cada mês sem decidir custa R$ X'; entrega rápida vale mais que desconto"],
        ] },
        { tipo: "erros", titulo: "Erros no gap", itens: [
          "Estimar o estado atual sem perguntar. O gap com número seu é argumento; com número dele é decisão.",
          "Definir o estado desejado pelo vendedor ('você poderia carregar 50'). O desejado é do cliente.",
          "Esconder o gap quando não fecha, empurrando a venda. O cliente descobre em 6 meses e você perde a conta e a região.",
          "Apresentar a parcela antes do gap. A ordem é: gap, depois parcela ao lado.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue três negociações abertas no CRM. Para cada uma, escreva estado atual (números), estado desejado (números do cliente) e gap mensal em reais. Se não tiver os números, é sinal de que o diagnóstico ficou raso: marque a visita para levantá-los." },
      ],
      missao: "Em uma negociação em aberto, faça o gap completo com o cliente: atual, desejado, diferença em reais por mês, na Calculadora do CRM, na frente dele. Registre a relação gap ÷ parcela na negociação. Se ficar abaixo de 1, diga ao cliente e registre a alternativa.",
      quiz: [
        { pergunta: "O gap mensal calculado com o cliente é R$ 12 mil e a parcela da máquina nova seria R$ 8 mil. Como o consultor lê e usa esse resultado?", opcoes: [
          "Relação 1,5: saudável; apresenta a parcela ao lado do gap e prepara a conversa com o sócio",
          "Relação 1,5: apertada; recomenda uma máquina de classe abaixo para a parcela cair e a folga aumentar",
          "Relação irrelevante; o que importa é o valor total da máquina em comparação com o faturamento anual",
          "Relação 1,5: só fecha com desconto de pelo menos 10%, porque a folga de R$ 4 mil não cobre imprevistos",
        ], correta: 0, explicacao: "Gap 1,5 vezes a parcela é o caso típico de troca de máquina velha: a compra se paga e sobra. A leitura correta orienta a apresentação (gap primeiro, parcela ao lado) e o material para o ratificador. Desconto e máquina menor são respostas a um gap que não existe." },
        { pergunta: "Quem deve definir o 'estado desejado' na conta do gap?", opcoes: [
          "O vendedor, com base na capacidade nominal da máquina que pretende vender e nos dados de outros clientes",
          "A fábrica, com base nos dados de produtividade do modelo medidos em condições padronizadas",
          "O cliente, com a meta dele ('preciso carregar 45 para pegar a usina'), perguntada e anotada",
          "O sócio ou o financeiro, que aprova o investimento e define quanto de retorno é necessário",
        ], correta: 2, explicacao: "O estado desejado do vendedor é argumento de venda; o do cliente é meta dele. Quando ele diz '45 caminhões pelo contrato da usina', o gap tem um dono e um motivo. Dados de fábrica entram depois, na prova de que a máquina alcança a meta." },
        { pergunta: "O gap ficou abaixo da parcela: a máquina nova não se paga com a produção atual do produtor. Qual conduta constrói mais valor de longo prazo?", opcoes: [
          "Ajustar as premissas de horas e consumo até o gap superar a parcela, porque o produtor tende a subestimar o uso",
          "Oferecer um desconto agressivo para fechar mesmo assim, porque a máquina nova gera valor que o gap não captura",
          "Apresentar a parcela sem mostrar o gap, deixando o cliente decidir com a própria percepção de valor",
          "Dizer que não fecha, propor a alternativa que cabe (usada, consórcio) e marcar a reabertura quando surgir sinal",
        ], correta: 3, explicacao: "O vendedor que manda não comprar vira referência e recebe indicações ('ele me falou pra não comprar'). Forçar a venda gera cliente arrependido, que fala para toda a região. Alternativa que cabe hoje mais a reabertura no sinal certo é a jogada de carreira." },
        { pergunta: "Por que a parcela deve aparecer somente depois de o gap ter sido calculado com o cliente?", opcoes: [
          "Porque a aprovação de crédito só sai depois do diagnóstico e a parcela real depende do que o banco aprovar",
          "Porque sem o gap a parcela é lida como custo isolado; ao lado do gap ela é lida como investimento com retorno",
          "Porque a política comercial recomenda não apresentar preço na primeira visita para preservar a margem",
          "Porque o cliente pode usar a parcela para negociar com a concorrência antes de ver o valor completo",
        ], correta: 1, explicacao: "A mesma parcela muda de significado conforme o que está ao lado dela. R$ 8 mil sozinhos assustam; R$ 8 mil ao lado de R$ 12 mil de gap tranquilizam. Ordem é enquadre, e enquadre é o trabalho do consultor." },
        { pergunta: "O cliente pergunta 'e a máquina dá mesmo 45 caminhões por dia?'. Qual resposta preserva a credibilidade do gap?", opcoes: [
          "'Dá com folga; a ficha técnica mostra capacidade acima disso, e o material da sua pedreira é mais leve'",
          "'Depende muito do operador e do caminhão, mas em geral sim, os clientes relatam esse número'",
          "'Vamos medir na sua pedreira, com o seu operador, antes de eu te prometer qualquer número'",
          "'Se não der, a gente troca por uma maior sem custo de transporte, isso eu garanto por escrito'",
        ], correta: 2, explicacao: "O gap foi construído com números do cliente; a promessa da máquina precisa do mesmo rigor. Uma medição na aplicação dele, com o operador dele, é prova que sobrevive ao sócio. Ficha técnica e 'em geral sim' são chute; 'troca por maior' é promessa que você não controla." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m4a3", titulo: "MEDDICC adaptado: qualificar antes de gastar a semana", minutos: 14,
      resumo: "Sete perguntas que dizem se a negociação é real ou é esperança. Métrica, comprador econômico, critérios de decisão, processo de decisão, dor identificada, campeão e concorrência. Negociação sem três dessas é negociação que vai consumir seu mês e não fechar.",
      blocos: [
        { tipo: "p", texto: "O MEDDICC nasceu nos anos 1990 na PTC, uma empresa de software que precisava prever quais das centenas de negociações realmente fechariam. Funciona igual para uma E215C: a negociação que tem métrica clara, comprador econômico identificado, critérios conhecidos, processo mapeado, dor quantificada, um campeão dentro do cliente e a concorrência conhecida fecha em 70% dos casos. A que tem só 'o cliente gostou' fecha em 15% e ocupa o mesmo tempo. Qualificar não é pessimismo; é escolher onde a semana rende." },
        { tipo: "framework", nome: "MEDDICC para máquina pesada", origem: "Jack Napoli e Dick Dunkel (PTC, 1996), adaptado ao mercado de bens de capital", passos: [
          "M — Métrica: o gap em reais/mês, dito e aceito pelo cliente. Sem número, não há métrica.",
          "E — Comprador econômico: quem assina o cheque ou o contrato de financiamento. Dono, sócio majoritário, prefeito/secretário. Você já falou com ele?",
          "D — Critérios de decisão: preço, parcela, assistência, prazo de entrega, revenda, operador que já conhece a marca. Quais e em que ordem?",
          "D — Processo de decisão: quem opina, quem aprova, que documentos, quanto tempo. Na prefeitura: termo de referência, pregão, empenho. Na empresa: sócio, banco, contador.",
          "I — Identificar a dor: a frase do cliente ('não confio nela', 'perdi a medição'). Se você não tem a frase, o diagnóstico ficou raso.",
          "C — Campeão: alguém dentro do cliente que ganha com a compra e vende por você quando você não está (operador, gerente de frota, engenheiro). Ele tem poder e motivo?",
          "C — Concorrência: quem mais está cotando, com quê, e o que o cliente acha deles. 'Só eu' quase sempre é engano.",
        ] },
        { tipo: "tabela", titulo: "Placar de qualificação (0–2 por letra, máximo 14)", colunas: ["Pontuação", "Leitura", "Ação"], linhas: [
          ["0–5", "Esperança, não negociação", "Voltar ao diagnóstico ou desqualificar; não enviar proposta"],
          ["6–9", "Real, mas com buracos (normalmente E, D-processo ou C-campeão)", "Próxima ação focada no buraco: reunião com o econômico, mapear o processo, cultivar o campeão"],
          ["10–14", "Negociação madura", "Proposta com a conta, reunião de revisão marcada, fechamento"],
        ] },
        { tipo: "dialogo", titulo: "Descobrindo o comprador econômico sem constranger", falas: [
          { quem: "vendedor", texto: "Seu Marcos, pra eu montar a proposta do jeito certo: além de você, quem mais costuma olhar um investimento desse antes de fechar?" },
          { quem: "cliente", texto: "Meu irmão. A empresa é dos dois. E o contador dá o pitaco no financiamento." },
          { quem: "nota", texto: "Pergunta calibrada ('quem mais costuma olhar') em vez de 'quem decide?' (que soa a 'você não manda?'). Dois nomes: comprador econômico compartilhado e um influenciador." },
          { quem: "vendedor", texto: "Perfeito. O seu irmão olha mais o quê: parcela, produção, assistência?" },
          { quem: "cliente", texto: "Parcela. Ele é o pé no chão da dupla." },
          { quem: "vendedor", texto: "Então quando eu trouxer a proposta, vale os dois estarem. Eu levo a conta do jeito que ele gosta: parcela ao lado do que a máquina velha custa hoje. Quinta às 17h vocês dois conseguem?" },
          { quem: "nota", texto: "Critério do econômico (parcela) descoberto e reunião com os dois marcada. Sem isso, a proposta chegaria ao irmão por WhatsApp, sem contexto, e morreria em 'tá caro'." },
        ] },
        { tipo: "caso", titulo: "Caso: as três propostas 'quentes' que não fecharam", situacao: "Vendedor tinha três propostas de E145C 'quase fechadas' há 45 dias. O gerente pediu o MEDDICC de cada uma.", acao: "Placar: 4, 5 e 6. Em nenhuma o vendedor tinha falado com o comprador econômico; em duas não sabia quem mais cotava; em uma a 'dor' era 'ele quer uma máquina nova'. Redirecionou: reunião com os sócios em duas, desqualificou a terceira.", resultado: "Uma fechou em 3 semanas (com o sócio na mesa); a segunda foi perdida para a Komatsu, que já tinha proposta na mesa há um mês; a terceira foi arquivada e o tempo foi para prospecção.", licao: "'Quase fechada' sem MEDDICC é sensação. O placar mostrou o buraco em cada uma antes de mais 45 dias de espera." },
        { tipo: "checklist", titulo: "MEDDICC rápido antes de enviar qualquer proposta", itens: [
          "Tenho o gap em reais, aceito pelo cliente? (M)",
          "Falei pessoalmente com quem assina? Sei o critério dele? (E)",
          "Sei os 3 critérios de decisão em ordem? (D)",
          "Sei as etapas e o prazo do processo (sócio, banco, contador, pregão)? (D)",
          "Tenho a frase da dor anotada? (I)",
          "Tenho alguém lá dentro que ganha com a compra e sabe disso? (C)",
          "Sei quem mais cota e o que o cliente acha deles? (C)",
        ] },
        { tipo: "erros", titulo: "Erros de qualificação", itens: [
          "Confundir contato simpático com campeão. Campeão tem poder e motivo; simpático só tem simpatia.",
          "Perguntar 'quem decide?' — soa a diminuição. Use 'quem mais costuma olhar um investimento desse?'.",
          "Acreditar em 'só estou cotando com vocês'. Pergunte de outro jeito: 'como você está comparando as opções?'.",
          "Enviar proposta com placar abaixo de 6 'pra ver o que acontece'. Proposta prematura vira âncora de preço para o concorrente.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pontue de 0 a 2 cada letra do MEDDICC nas cinco maiores negociações do seu funil. Para cada uma abaixo de 10, escreva a próxima ação que fecha o maior buraco (reunião com o econômico, mapear o processo, cultivar o campeão). Cadastre no CRM com data." },
      ],
      missao: "Aplique o placar MEDDICC a todas as negociações em etapa de proposta ou negociação no CRM. Registre a nota na negociação. Para as abaixo de 6, decida hoje: voltar ao diagnóstico ou desqualificar. Para as entre 6 e 9, cadastre a ação que fecha o buraco.",
      quiz: [
        { pergunta: "Uma negociação tem gap calculado, dor anotada e o cliente 'adorou a máquina', mas você nunca falou com o sócio que assina e não sabe quem mais cota. Qual é a leitura MEDDICC e a ação?", opcoes: [
          "Negociação madura, porque gap, dor e entusiasmo cobrem o essencial; enviar a proposta e aguardar o retorno",
          "Negociação com buracos em E e C; próxima ação é a reunião com o sócio e a pergunta sobre como estão comparando",
          "Negociação em risco, porque um sócio que nunca apareceu indica que o interesse real é menor do que parece",
          "Negociação madura, porque o entusiasmo do cliente e o gap calculado compensam a falta de acesso ao sócio",
        ], correta: 1, explicacao: "M, I e parte de D estão bem; E (comprador econômico) e C (concorrência) estão vazios, e são exatamente os buracos por onde as vendas 'quase fechadas' escapam. Proposta agora chega ao sócio sem contexto. A ação é fechar o buraco, não esperar." },
        { pergunta: "Qual pergunta descobre o comprador econômico sem soar que o interlocutor 'não manda'?", opcoes: [
          "'Você tem autonomia para fechar sozinho ou precisa passar por alguém?'",
          "'Quem é o dono da empresa e como funciona a aprovação por aqui?'",
          "'Quem decide a compra aqui, você ou o financeiro?'",
          "'Além de você, quem mais costuma olhar um investimento desse antes de fechar?'",
        ], correta: 3, explicacao: "A pergunta calibrada pressupõe que ele participa e pergunta quem MAIS olha. As outras três colocam em dúvida o poder dele e geram resposta defensiva ('eu decido') que esconde o sócio. O sócio escondido aparece depois, no veto." },
        { pergunta: "O que caracteriza um 'campeão' no MEDDICC, diferente de um contato simpático?", opcoes: [
          "Alguém dentro do cliente que ganha com a compra, tem influência real e defende a solução quando você não está na sala",
          "O primeiro contato da empresa que te atendeu e passou a centralizar a comunicação com a concessionária",
          "Alguém que responde rápido às mensagens, gosta da marca e demonstra entusiasmo pela máquina apresentada",
          "O operador que elogiou a cabine durante o teste e comentou com os colegas que a máquina é boa",
        ], correta: 0, explicacao: "Campeão tem poder e motivo: o gerente de frota que vai parar de ser cobrado por máquina parada, o engenheiro que quer a obra no prazo. Simpatia sem influência não vende por você na reunião dos sócios. Cultivar o campeão é dar a ele os argumentos e o material." },
        { pergunta: "O cliente afirma 'só estou cotando com vocês'. Qual é a conduta correta?", opcoes: [
          "Acreditar e reduzir a urgência da proposta, porque sem pressão concorrencial há tempo para um diagnóstico mais completo",
          "Perguntar de outro jeito ('como você está comparando as opções?') e tratar como se houvesse concorrente até prova em contrário",
          "Pedir que ele confirme por mensagem que está cotando só com você, para registrar e ajustar a estratégia de preço",
          "Manter o preço de tabela sem concessões, porque sem comparação o cliente não tem referência para pedir desconto",
        ], correta: 1, explicacao: "'Só vocês' quase sempre é cortesia ou estratégia. A pergunta calibrada revela o critério de comparação (e, muitas vezes, o concorrente). Negociação de máquina sem concorrente é raríssima; preparar-se para ele custa pouco e evita a surpresa do 'a Komatsu já tinha proposta'." },
        { pergunta: "Por que enviar proposta com placar MEDDICC abaixo de 6 'para ver o que acontece' é um erro?", opcoes: [
          "Porque a concessionária limita o número de propostas formais por mês e cada uma passa pela aprovação do gerente",
          "Porque o cliente pode se sentir pressionado a decidir antes de ter todas as informações e recuar",
          "Porque a proposta prematura vira âncora de preço para o concorrente e consome tempo de acompanhamento sem chance real",
          "Porque uma proposta enviada cedo demais fixa a configuração e dificulta ajustes quando o diagnóstico avançar",
        ], correta: 2, explicacao: "Sem métrica, econômico e processo, a proposta é só um número, e número circula: o concorrente recebe e cobre. Além disso, cada proposta aberta gera follow-up, e follow-up de esperança consome o tempo que deveria ir para negociações reais e prospecção." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m4a4", titulo: "Perguntas calibradas e escuta: a regra 70/30", minutos: 13,
      resumo: "Na visita de diagnóstico o cliente fala 70% do tempo. Perguntas abertas com 'como' e 'o quê', silêncio depois da pergunta, resumo do que ouviu antes de avançar. Quem fala demais descobre de menos.",
      blocos: [
        { tipo: "p", texto: "Gravações de visitas de venda mostram um padrão: vendedores medianos falam 65% do tempo; os melhores, 30%. Não é timidez, é método. Cada minuto que o cliente fala é um minuto de diagnóstico grátis: ele conta a dor, o decisor, o concorrente, o prazo, o que já deu errado. Cada minuto que você fala é apresentação — e apresentação antes da hora é a principal causa de proposta perdida. A técnica tem três partes: a pergunta certa, o silêncio depois e o resumo que confirma." },
        { tipo: "framework", nome: "PSR — Pergunta, Silêncio, Resumo", origem: "Escuta ativa (Carl Rogers) combinada às perguntas calibradas de Chris Voss", passos: [
          "Pergunta calibrada: começa com 'como', 'o que', 'qual'. Nunca 'por que' (acusa) nem pergunta fechada (mata a conversa). 'Como vocês decidiram a última compra de máquina?' 'O que precisaria mudar pra você pegar mais obra?'",
          "Silêncio de 4 segundos: depois da resposta, conte até quatro. O cliente completa com a parte que importa ('…e o meu irmão também não gosta da marca antiga').",
          "Resumo: 'Deixa eu ver se entendi: a máquina para 3 dias por mês, você aluga pra cobrir, e o que mais pesa é a medição atrasar. É isso?' Ele corrige ou confirma — e você tem a dor nas palavras dele.",
          "Só depois do resumo confirmado você tem licença para falar de solução — e só da parte que responde ao resumo.",
        ] },
        { tipo: "tabela", titulo: "Troque a pergunta", colunas: ["Pergunta fraca", "Por que é fraca", "Pergunta calibrada"], linhas: [
          ["'Você está satisfeito com a máquina atual?'", "Fechada; 'sim' encerra", "'O que você mudaria na máquina atual se pudesse?'"],
          ["'Por que vocês compraram da outra marca?'", "'Por que' soa a acusação", "'Como foi a decisão da última compra? O que pesou?'"],
          ["'Vocês têm orçamento pra isso?'", "Constrange; gera 'não'", "'Como vocês costumam encaixar um investimento desse no caixa?'"],
          ["'Posso te mandar uma proposta?'", "Pede compromisso sem valor", "'O que precisaria estar numa proposta pra ela fazer sentido pra vocês?'"],
          ["'O preço é o problema?'", "Sugere a objeção", "'Além do valor, o que mais está pesando?'"],
        ] },
        { tipo: "dialogo", titulo: "Silêncio que vale uma venda", falas: [
          { quem: "vendedor", texto: "Como foi a decisão da última compra de máquina de vocês? O que pesou?" },
          { quem: "cliente", texto: "Foi o preço. A gente pegou a mais barata." },
          { quem: "nota", texto: "Vendedor mediano responderia agora ('mas o barato sai caro…'). O consultor conta até quatro." },
          { quem: "cliente", texto: "…e me arrependi. Ficou parada 40 dias esperando peça. Meu irmão até hoje joga na minha cara." },
          { quem: "vendedor", texto: "Deixa eu ver se entendi: a última decisão foi por preço, a máquina parou 40 dias, e o seu irmão hoje vai olhar muito mais a assistência do que o valor. É isso?" },
          { quem: "cliente", texto: "É isso. Se você resolver a assistência pra ele, o preço a gente conversa." },
          { quem: "nota", texto: "O silêncio revelou o arrependimento, o critério do sócio (assistência) e a ordem de negociação. Três informações que o vendedor falante nunca teria." },
        ] },
        { tipo: "caso", titulo: "Caso: a visita gravada", situacao: "Um vendedor experiente gravou (com autorização) três visitas e mediu com o cronômetro: falava 68% do tempo. Achava que 'conduzia bem'.", acao: "Treinou o PSR por um mês: lista de 10 perguntas calibradas na mão, regra dos 4 segundos, resumo obrigatório antes de qualquer frase sobre produto. Regravou.", resultado: "Passou a 35% do tempo falando. Descobriu decisor oculto em 2 das 3 visitas seguintes e o concorrente real em todas. A conversão visita → proposta subiu de 40% para 60%.", licao: "Você não sabe quanto fala até medir. E o que você descobre quando cala é o que fecha a venda." },
        { tipo: "script", titulo: "Dez perguntas calibradas para levar na visita", itens: [
          "'Como está o dia a dia com a máquina atual? O que mais incomoda?'",
          "'O que acontece quando ela para?'",
          "'Como vocês decidiram a última compra? O que pesou e o que vocês fariam diferente?'",
          "'Quem mais costuma olhar um investimento desse?'",
          "'O que essa pessoa olha primeiro?'",
          "'Como vocês estão comparando as opções?'",
          "'O que precisaria estar numa proposta pra ela fazer sentido?'",
          "'Como o pagamento costuma ser encaixado no caixa de vocês?'",
          "'Qual é o prazo que faz diferença pra vocês (obra, safra, licitação)?'",
          "'O que faria vocês NÃO comprarem, mesmo gostando da máquina?'",
        ] },
        { tipo: "erros", titulo: "Erros de escuta", itens: [
          "Preencher o silêncio. Os 4 segundos são desconfortáveis para você e reveladores para a venda.",
          "Ouvir para responder, não para entender. Se você está montando a resposta enquanto ele fala, não está ouvindo.",
          "Pular o resumo. Sem resumo, você apresenta para a dor que imaginou, não para a que ele tem.",
          "Perguntar e olhar o celular. Escuta é também o corpo: caderno, olho, postura.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Grave a sua próxima visita (peça autorização) ou uma ligação de diagnóstico. Cronometre quanto você fala. Conte quantas vezes preencheu um silêncio antes de 4 segundos e quantas fez o resumo antes de falar de produto. Meta: menos de 40% do tempo, zero silêncios preenchidos, um resumo antes de cada proposta." },
      ],
      missao: "Leve as dez perguntas calibradas impressas para as próximas três visitas. Aplique a regra dos 4 segundos e faça o resumo antes de falar de qualquer máquina. Registre no CRM o que você descobriu que não sabia (decisor, concorrente, critério, prazo).",
      quiz: [
        { pergunta: "O cliente responde 'foi o preço, a gente pegou a mais barata' à sua pergunta sobre a última compra. Qual é a conduta do consultor?", opcoes: [
          "Explicar na hora por que comprar pelo preço sai caro, aproveitando que o cliente abriu o assunto",
          "Perguntar imediatamente qual foi a marca e o valor pago, para entender a referência de preço dele",
          "Anotar a informação e mudar de assunto com tato, para não constranger o cliente com a decisão anterior",
          "Contar até quatro em silêncio e deixar o cliente completar; depois resumir o que ouviu",
        ], correta: 3, explicacao: "O silêncio revelou, no diálogo da aula, o arrependimento, o critério do sócio e a ordem de negociação. Responder na hora encerra a revelação; perguntar marca e valor devolve a conversa ao preço; mudar de assunto joga fora a informação." },
        { pergunta: "Por que 'você está satisfeito com a máquina atual?' é uma pergunta fraca no diagnóstico?", opcoes: [
          "Porque é fechada: 'sim' encerra a conversa e o cliente tende a defender a decisão que tomou",
          "Porque é invasiva e o cliente pode se ofender ao ter a própria escolha de máquina colocada em dúvida",
          "Porque revela desde o início que o vendedor quer vender uma máquina nova, e o cliente fecha a guarda",
          "Porque a satisfação atual não influencia a decisão de compra, que depende de números e não de opinião",
        ], correta: 0, explicacao: "Pergunta fechada dá ao cliente a saída fácil e, pior, ativa a defesa da compra anterior. 'O que você mudaria na máquina atual?' pressupõe que há algo e convida a listar. Invasão e intenção de venda não são o problema; a forma é." },
        { pergunta: "Qual é a função do resumo ('deixa eu ver se entendi…') antes de falar de solução?", opcoes: [
          "Ganhar tempo para organizar mentalmente a apresentação enquanto repete, com outras palavras, o que o cliente disse",
          "Demonstrar ao cliente que você prestou atenção e tem boa memória, o que constrói confiança para a proposta",
          "Confirmar a dor nas palavras dele, dar chance de correção e obter licença para apresentar só o que responde a ela",
          "Registrar oralmente os pontos da conversa para lançar no CRM com precisão logo depois da visita, sem esquecer nada",
        ], correta: 2, explicacao: "O resumo é o ponto de virada da visita: o cliente corrige ou confirma, e o que ele confirma vira o roteiro da apresentação e da proposta. Sem resumo, você apresenta para a dor que imaginou. Memória e CRM são efeitos colaterais, não o objetivo." },
        { pergunta: "Vendedores de alto desempenho falam cerca de 30% do tempo na visita de diagnóstico. Qual é a razão principal?", opcoes: [
          "Porque são naturalmente mais reservados e preferem ouvir, o que o cliente interpreta como respeito e maturidade",
          "Porque cada minuto do cliente é diagnóstico (dor, decisor, concorrente, prazo) e cada minuto do vendedor é apresentação antes da hora",
          "Porque clientes do interior desconfiam de vendedores falantes e valorizam quem fala pouco, ouve muito e não interrompe",
          "Porque o tempo de visita é curto e, quando o vendedor fala menos, sobra mais tempo para o cliente pensar e decidir",
        ], correta: 1, explicacao: "Não é temperamento, é método: a informação que fecha a venda está na cabeça do cliente e só sai quando ele fala. Apresentação precoce é a causa número um de proposta que não fecha. A regra 70/30 é uma decisão, medida com cronômetro." },
        { pergunta: "Qual pergunta tem mais chance de revelar o critério do sócio que você ainda não conheceu?", opcoes: [
          "'O que o seu sócio olha primeiro num investimento desse?'",
          "'Posso falar diretamente com o seu sócio sobre a proposta?'",
          "'O seu sócio também vai querer ver a máquina antes de decidir?'",
          "'O seu sócio costuma concordar com você nas compras da empresa?'",
        ], correta: 0, explicacao: "Pergunta aberta com 'o que' sobre o critério do outro decisor rende a resposta que orienta a proposta ('parcela', 'assistência'). Perguntas fechadas geram sim/não; pedir acesso direto de cara pode soar que você quer passar por cima do contato." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m4a5", titulo: "O mapa dos decisores: dono, sócio, financeiro, operador, engenheiro, pregoeiro", minutos: 14,
      resumo: "Máquina de R$ 600 mil raramente é decisão de uma pessoa. Cada conta tem um comprador econômico, usuários, técnicos, influenciadores e, às vezes, um bloqueador. Cada um precisa ouvir uma coisa diferente — e você precisa saber quem é quem antes da proposta.",
      blocos: [
        { tipo: "p", texto: "Na empreiteira familiar, o dono decide, o irmão aprova a parcela, o contador opina no financiamento e o operador dá o veredito depois do teste. Na prefeitura, o secretário de obras quer a máquina, o engenheiro escreve o termo de referência, o pregoeiro conduz o certame, o prefeito assina e o setor de compras cobra a documentação. Na pedreira, o gerente de produção sofre com a máquina parada, o dono olha o retorno e o mecânico da casa tem opinião sobre marca. Vender para uma pessoa e esperar que ela convença as outras é entregar a venda ao acaso." },
        { tipo: "framework", nome: "Cinco papéis de compra (e o que cada um precisa ouvir)", origem: "Miller & Heiman — Strategic Selling (papéis de compra), adaptado ao mercado de máquinas", passos: [
          "Comprador econômico: assina, libera o dinheiro. Quer retorno, parcela × faturamento, risco controlado. Material: gap × parcela em uma página.",
          "Usuário: opera ou gerencia a máquina no dia a dia (operador, encarregado, gerente de frota). Quer conforto, facilidade, assistência rápida. Material: teste com ele na máquina, contato do técnico.",
          "Técnico/avaliador: julga especificação e conformidade (engenheiro, mecânico, contador no financiamento). Quer dado, ficha, comparativo, memória de cálculo. Material: comparativo com fonte, especificação que atende ao termo.",
          "Campeão (coach): ganha com a compra e te orienta por dentro. Precisa de argumentos e material para vender por você. Cultive com informação e reconhecimento.",
          "Bloqueador: perde algo com a mudança (o mecânico que conhece só a marca antiga, o cunhado que vende a outra marca). Não confronte; neutralize com fato e dê a ele uma saída digna.",
        ] },
        { tipo: "tabela", titulo: "Mapa típico por tipo de cliente", colunas: ["Cliente", "Econômico", "Usuário", "Técnico", "Campeão provável", "Bloqueador provável"], linhas: [
          ["Empreiteira familiar", "Dono + sócio/irmão", "Operador, encarregado", "Contador (financiamento)", "Encarregado que sofre com parada", "Mecânico fiel à marca antiga"],
          ["Pedreira", "Dono", "Gerente de produção, operador", "Mecânico da casa", "Gerente de produção", "Comprador que quer só preço"],
          ["Prefeitura", "Prefeito / secretário de obras", "Operadores da frota", "Engenheiro (termo de referência)", "Secretário de obras", "Pregoeiro focado em menor preço; vereador ligado a outro fornecedor"],
          ["Cooperativa / café", "Presidente / produtor", "Tratorista, gerente da fazenda", "Agrônomo", "Gerente da fazenda", "Vizinho que vende outra marca"],
          ["Locadora", "Dono", "Mecânico, clientes locatários", "Gerente de frota", "Gerente de frota", "Dono que só compra usada"],
        ] },
        { tipo: "dialogo", titulo: "Neutralizando o bloqueador sem briga", falas: [
          { quem: "cliente", texto: "(mecânico da pedreira) Eu conheço a Cat de olho fechado. Essa New Holland aí eu nunca mexi. Vai dar dor de cabeça." },
          { quem: "vendedor", texto: "Faz todo sentido: ninguém quer aprender a mexer numa máquina nova no meio da produção. Deixa eu te perguntar: o que você precisaria ter na mão pra ficar tranquilo com uma máquina que você não conhece?" },
          { quem: "nota", texto: "Validação + pergunta calibrada. Sem 'mas a New Holland é fácil'. O bloqueador vira consultor do próprio medo." },
          { quem: "cliente", texto: "Manual decente, alguém pra ligar que atenda, e peça que não demore um mês." },
          { quem: "vendedor", texto: "Então eu faço o seguinte: treinamento de dois dias com o técnico da concessionária aqui na pedreira, o WhatsApp direto dele, e a lista de peças de desgaste que a gente deixa em estoque aqui. Se isso funcionar, você me ajuda a ajustar o que faltar?" },
          { quem: "nota", texto: "Cada medo virou uma entrega concreta e o bloqueador ganhou um papel (ajustar o que faltar). Ele tem uma saída digna: apoiou porque as condições dele foram atendidas." },
        ] },
        { tipo: "caso", titulo: "Caso: o operador que decidiu a licitação", situacao: "Prefeitura de um município da região ia licitar uma motoniveladora. O vendedor conversava só com o secretário de obras, que gostava da RG140B.", acao: "Mapeou os papéis: engenheiro (termo de referência), pregoeiro, prefeito e os dois operadores da frota. Descobriu que o operador mais antigo tinha operado uma concorrente por 15 anos e falava com o prefeito todo dia. Levou o operador para um dia de teste na RG140B em outra prefeitura.", resultado: "O operador virou campeão ('essa aqui tem o hidráulico mais macio que eu já vi'). O engenheiro especificou dentro do que a RG140B atendia com folga. Pregão vencido.", licao: "O usuário sem cargo pode ser o influenciador mais forte da conta. Quem mapeia todos os papéis descobre onde a venda realmente se decide." },
        { tipo: "checklist", titulo: "Mapa da conta antes da proposta", itens: [
          "Nome e papel de cada pessoa envolvida (econômico, usuário, técnico, campeão, bloqueador).",
          "O que cada um olha primeiro (parcela, assistência, especificação, conforto, preço).",
          "Com quem eu já falei pessoalmente? Com quem ainda não? Como chego lá?",
          "Quem ganha com a compra e sabe disso? Que material eu dei a ele para vender por mim?",
          "Quem perde algo com a mudança? O que eu ofereço como saída digna?",
          "Registrado no CRM: contatos vinculados ao cliente, com papel e critério nas observações.",
        ] },
        { tipo: "erros", titulo: "Erros de mapa", itens: [
          "Vender só para quem te recebe bem. Quem te recebe bem nem sempre decide.",
          "Ignorar o operador. Ele dá o veredito no teste e fala com o dono todo dia.",
          "Confrontar o bloqueador ('a Cat também quebra'). Ele endurece e vira inimigo.",
          "Pular o contato para chegar ao dono. Ele fica ofendido e vira bloqueador.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Desenhe o mapa de decisores das três maiores negociações do seu funil: nome, papel, critério principal, se você já falou com a pessoa. Marque em vermelho os papéis vazios. Para cada vazio, escreva como você chega lá sem passar por cima do seu contato." },
      ],
      missao: "Para cada negociação em proposta no CRM, cadastre os contatos com o papel de compra (econômico, usuário, técnico, campeão, bloqueador) e o critério de cada um nas observações. Marque uma ação para falar com o comprador econômico que você ainda não conheceu.",
      quiz: [
        { pergunta: "O mecânico da pedreira diz que só conhece a Cat e que a New Holland 'vai dar dor de cabeça'. Qual resposta neutraliza o bloqueador?", opcoes: [
          "Explicar que a New Holland é mais simples de manter do que a Cat, com menos eletrônica, e que ele vai se adaptar rápido",
          "Não gastar energia com ele, porque a decisão é do dono, o mecânico não assina nada e a assistência resolve o resto",
          "Sugerir ao dono, com tato, que contrate um mecânico com experiência na marca nova para acompanhar a transição",
          "Validar a preocupação, perguntar o que ele precisaria para ficar tranquilo e transformar cada medo em entrega concreta",
        ], correta: 3, explicacao: "O bloqueador perde algo (o domínio da marca antiga) e por isso resiste. Confrontar endurece; ignorar deixa um influenciador diário contra você; sugerir troca de mecânico o torna inimigo declarado. Atender às condições dele e dar um papel é a saída digna que o converte." },
        { pergunta: "Na licitação de uma motoniveladora, o vendedor só conversa com o secretário de obras, que gosta da máquina. Qual é o risco principal?", opcoes: [
          "Nenhum relevante, porque o secretário de obras é o comprador econômico na prefeitura e a comissão segue a indicação dele",
          "O pregoeiro pode desclassificar a proposta por detalhe de documentação, e o secretário não tem como interferir no certame",
          "O engenheiro escreve o termo e os operadores influenciam o prefeito; sem mapear esses papéis, a especificação pode favorecer outra máquina",
          "O prefeito pode vetar a compra por questões políticas ou orçamentárias, mesmo com o secretário e a comissão favoráveis",
        ], correta: 2, explicacao: "Na prefeitura o secretário quer, mas o engenheiro especifica, o operador opina com o prefeito e o pregoeiro conduz. No caso da aula, o operador que testou a máquina virou campeão e o engenheiro especificou dentro do que ela atendia. Vender só ao secretário é apostar." },
        { pergunta: "Qual material serve ao comprador econômico e qual serve ao técnico, respectivamente?", opcoes: [
          "Ficha técnica completa para o econômico, que precisa conhecer o produto; uma página com gap × parcela para o técnico avaliar",
          "Teste na máquina para o econômico, que decide pelo que vê; história de cliente parecido para o técnico se identificar",
          "Comparativo com fonte para o econômico, que compara investimentos; contato do operador de referência para o técnico",
          "Uma página com gap × parcela e risco controlado para o econômico; comparativo com fonte e especificação para o técnico",
        ], correta: 3, explicacao: "O econômico quer retorno e risco em uma folha; o técnico quer dado verificável e conformidade. Trocar os materiais (ficha para o dono, resumo para o engenheiro) é o erro clássico que faz um deles se sentir desrespeitado ou desinformado." },
        { pergunta: "Por que 'pular' o seu contato para falar direto com o dono costuma sair caro?", opcoes: [
          "Porque o dono raramente atende vendedores sem agendamento, e a tentativa costuma terminar na secretária",
          "Porque o contato se sente desrespeitado e vira bloqueador dentro da conta, minando a venda por dentro",
          "Porque a boa prática comercial recomenda respeitar a hierarquia do cliente para não gerar ruído interno",
          "Porque o dono costuma delegar a decisão de volta ao contato, e você volta ao ponto de partida com atraso",
        ], correta: 1, explicacao: "O contato que te recebeu tem acesso diário ao dono. Passado por cima, ele passa a falar contra você todos os dias. O caminho é pedir a ele a ponte ('vale os dois estarem na reunião?'), transformando-o em campeão em vez de inimigo." },
        { pergunta: "Qual afirmação sobre o 'usuário' (operador, encarregado) está correta?", opcoes: [
          "Pode ser o influenciador mais forte da conta: dá o veredito no teste e fala com o dono todos os dias",
          "Tem pouca relevância na decisão, porque não tem cargo, não assina nada e troca de empresa com frequência",
          "Só importa em empresas grandes com gerente de frota, onde a opinião técnica é ouvida de forma organizada",
          "Deve ser tratado com cautela, porque tende a defender a marca que já conhece e pode atrapalhar a comparação",
        ], correta: 0, explicacao: "No caso da aula, o operador sem cargo decidiu uma licitação. Ele testa, compara e comenta com quem decide diariamente. Levá-lo para um dia de teste com o operador de referência é uma das ações de maior retorno no mapa da conta." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m4a6", titulo: "Desqualificar é vender: a coragem de dizer 'ainda não'", minutos: 12,
      resumo: "O tempo é o único recurso que você não recupera. Negociação sem gap, sem dinheiro ou sem acesso ao decisor consome semanas e não fecha. Desqualificar cedo — com elegância e com data de retorno — é o que libera a agenda para as vendas reais.",
      blocos: [
        { tipo: "p", texto: "Todo funil tem negociações que ninguém tem coragem de encerrar: o cliente simpático que 'vai comprar quando a obra sair', a prefeitura que pede cotação toda semana e nunca licita, o produtor cujo gap não fecha. Elas inflam a cobertura, geram follow-ups inúteis e roubam as horas que deveriam ir para prospecção e para as contas maduras. Desqualificar não é desistir do cliente: é encerrar a NEGOCIAÇÃO atual com uma data e um gatilho para reabrir, e devolver o tempo para onde ele rende." },
        { tipo: "framework", nome: "Os 4 testes de desqualificação", origem: "Prática de gestão de pipeline (Sandler, MEDDICC) aplicada ao ciclo de máquinas", passos: [
          "Gap: existe dor com número? Se depois de duas conversas o cliente não consegue dizer o que perde por mês, não há negociação; há curiosidade.",
          "Dinheiro: existe caminho de pagamento realista (crédito, usada, consórcio, orçamento aprovado, licitação com dotação)? 'Se o banco aprovar' sem análise iniciada é esperança.",
          "Acesso: você chegou ou vai chegar ao comprador econômico? Se o contato bloqueia o acesso há 30 dias, a venda não é sua.",
          "Momento: há um evento que força a decisão (obra, safra, licitação, máquina que parou)? Sem evento, 'algum dia' vira nunca. Nutrição, não negociação.",
          "Regra: dois testes falhando = desqualifica agora, com data e gatilho de retorno registrados. Um falhando = a próxima ação é fechar esse buraco, com prazo de 14 dias.",
        ] },
        { tipo: "dialogo", titulo: "Encerrando com elegância e data", falas: [
          { quem: "vendedor", texto: "Seu Valdir, a gente conversa há dois meses e eu gosto do seu projeto. Mas eu quero ser honesto com você: enquanto a obra da BR não sair, a máquina nova não faz sentido pro seu caixa, e eu não quero ficar te mandando mensagem à toa." },
          { quem: "cliente", texto: "Eu entendo. Também não quero te enrolar." },
          { quem: "vendedor", texto: "Então vamos combinar assim: quando a ordem de serviço da BR sair, você me manda uma mensagem — ou eu te chamo em setembro, que é quando você disse que deve ter novidade. Até lá, se aparecer uma usada boa pra cobrir o começo, eu te aviso. Fechado?" },
          { quem: "cliente", texto: "Fechado. E obrigado pela franqueza, viu? Vendedor normalmente fica insistindo." },
          { quem: "nota", texto: "Sem ressentimento, com gatilho (ordem de serviço), data (setembro) e uma promessa leve de valor (a usada). A negociação sai do funil; o cliente fica na base, mais quente do que antes." },
        ] },
        { tipo: "tabela", titulo: "Sinais de que é hora de desqualificar", colunas: ["Sinal", "O que costuma significar", "Ação"], linhas: [
          ["Terceira proposta 'revisada' sem reunião com o decisor", "Você é referência de preço para outro fornecedor", "Pedir a reunião com o econômico ou encerrar"],
          ["'Vou comprar quando a obra sair' há mais de 60 dias", "Sem evento; esperança", "Gatilho + data; nutrição"],
          ["Prefeitura pede cotação toda semana e nunca publica", "Cotações para instruir processo sem dotação", "Perguntar sobre dotação e prazo; encerrar se não houver"],
          ["Gap abaixo da parcela e cliente sem alternativa", "A compra não se paga", "Dizer; oferecer usada/consórcio; data de reabertura"],
          ["Contato impede acesso ao sócio há 30 dias", "Ou não tem poder, ou está protegendo outro fornecedor", "Pedir a ponte diretamente; se recusada, encerrar"],
        ] },
        { tipo: "caso", titulo: "Caso: 31 negociações abertas, 9 reais", situacao: "O funil do vendedor tinha 31 negociações e cobertura de 6x a meta. Ele passava 60% da semana em follow-up e não prospectava 'porque estava cheio'.", acao: "Aplicou os quatro testes a todas. Desqualificou 22 com data e gatilho registrados (a maioria com mais de 60 dias sem próxima ação real). Ficaram 9, com cobertura de 2,8x.", resultado: "Com o tempo liberado, prospectou 40 contatos em duas semanas e abriu 7 negociações novas com sinal. No trimestre, fechou 8 máquinas contra 4 no anterior. Três das desqualificadas voltaram sozinhas quando o gatilho aconteceu.", licao: "Funil inflado dá sensação de segurança e rouba o tempo da prospecção. Nove reais valem mais que trinta e uma esperanças." },
        { tipo: "checklist", titulo: "Revisão mensal de desqualificação", itens: [
          "Toda negociação com mais de 30 dias sem avanço de etapa: aplicar os 4 testes.",
          "Toda negociação com 2 testes falhando: encerrar hoje com mensagem elegante, gatilho e data.",
          "Registrar o motivo real (sem gap, sem dinheiro, sem acesso, sem momento) para o win/loss.",
          "Cadastrar a próxima ação de nutrição (60 dias) no cliente, não na negociação.",
          "Conferir a cobertura depois da limpeza: entre 3x e 4x é o alvo.",
        ] },
        { tipo: "erros", titulo: "Erros de quem não desqualifica", itens: [
          "Manter negociação morta para 'não perder o cliente'. Você não perde o cliente; perde a negociação inflada.",
          "Sumir em vez de encerrar. Sumir queima; encerrar com data aquece.",
          "Desqualificar por preguiça, sem aplicar os testes. Há negociações difíceis que são reais.",
          "Não registrar o gatilho. Sem gatilho, a reabertura depende da sua memória — e ela falha.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste todas as negociações abertas há mais de 45 dias no CRM. Aplique os quatro testes a cada uma e marque quantos falham. Escreva a mensagem de encerramento com gatilho e data para as que falham em dois ou mais. Envie hoje." },
      ],
      missao: "Faça a limpeza do funil: aplique os quatro testes a toda negociação com mais de 30 dias sem avanço. Encerre as que falham em dois testes com mensagem elegante, gatilho e data registrados no CRM. Anote a cobertura antes e depois e o tempo que você liberou para prospecção.",
      quiz: [
        { pergunta: "Uma negociação está há 70 dias em 'proposta enviada'. O cliente é simpático, responde às mensagens, mas 'vai comprar quando a obra sair' e você nunca falou com o sócio. Quantos testes falham e qual é a ação?", opcoes: [
          "Nenhum: ele responde às mensagens e demonstra interesse; manter o follow-up semanal até a obra sair",
          "Um (momento): enviar uma proposta revisada com condição especial para acelerar a decisão antes da obra",
          "Dois ou mais (momento e acesso): encerrar com elegância, registrar gatilho (ordem de serviço) e data, mover para nutrição",
          "Todos os quatro: encerrar sem registro, porque uma negociação de 70 dias sem avanço não vale o gatilho",
        ], correta: 2, explicacao: "Sem evento que force a decisão e sem acesso ao comprador econômico, a negociação é esperança. A resposta não é sumir nem bloquear: é encerrar a negociação com gatilho e data, mantendo o cliente aquecido na base. Simpatia e respostas não são critério." },
        { pergunta: "Por que sumir de uma negociação morta é pior do que encerrá-la com uma mensagem?", opcoes: [
          "Porque o CRM exige um motivo de perda registrado e uma negociação abandonada sem justificativa distorce os relatórios",
          "Porque o gerente cobra o motivo real de cada perda no win/loss mensal e o sumiço não gera aprendizado",
          "Porque o cliente pode reclamar com a concessionária de que foi ignorado, e a reclamação chega ao gerente",
          "Porque sumir é lido como desinteresse e queima a relação; encerrar com gatilho e data é lido como franqueza e aquece o retorno",
        ], correta: 3, explicacao: "No diálogo da aula o cliente agradeceu a franqueza ('vendedor normalmente fica insistindo'). A mensagem de encerramento elegante é uma das melhores ferramentas de relacionamento: tira a pressão, mantém a porta aberta e define quando ela reabre." },
        { pergunta: "Qual é o efeito mais importante de um funil inflado com negociações mortas?", opcoes: [
          "A cobertura alta dá falsa segurança e o tempo vai para follow-ups inúteis em vez de prospecção, esvaziando o funil de verdade",
          "O gerente define metas mais altas com base na cobertura aparente, e o vendedor passa a ser cobrado por um número irreal",
          "O CRM fica lento e a Central de Alertas gera avisos demais, o que faz o vendedor ignorar os alertas importantes",
          "O cliente percebe que está sendo acompanhado sem motivo e passa a evitar o vendedor nas visitas seguintes",
        ], correta: 0, explicacao: "No caso da aula, 31 negociações e 6x de cobertura escondiam 9 reais e zero prospecção. A limpeza liberou o tempo que produziu 7 negociações novas com sinal e dobrou o resultado do trimestre. Funil é ferramenta de decisão, não de conforto." },
        { pergunta: "Uma prefeitura pede cotação da mesma motoniveladora pela quarta vez em três meses e nunca publicou o pregão. Qual pergunta e ação são corretas?", opcoes: [
          "Enviar a cotação de novo com o preço atualizado, porque prefeitura sempre demora e o processo um dia vira pregão",
          "Perguntar sobre dotação e prazo de publicação; sem resposta concreta, encerrar com gatilho (edital) e manter a relação com o engenheiro",
          "Recusar novas cotações até que o edital seja publicado, para não servir de referência de preço a um processo sem dinheiro",
          "Reduzir o preço da cotação a cada pedido, para a prefeitura perceber a vantagem e acelerar a publicação",
        ], correta: 1, explicacao: "Cotações repetidas sem dotação costumam instruir processos que não têm dinheiro ainda. A pergunta sobre dotação e prazo revela isso sem confronto. Recusar cotar ofende; cotar eternamente consome tempo; reduzir preço vira referência para o edital de outro." },
        { pergunta: "Qual é a diferença entre desqualificar uma negociação e abandonar um cliente?", opcoes: [
          "Não há diferença prática: desqualificar significa retirar o cliente da carteira ativa e parar de investir tempo nele",
          "Desqualificar é reduzir a prioridade da conta no CRM; abandonar é excluir o cadastro do cliente do sistema",
          "Desqualificar é encerrar a negociação atual com gatilho e data, mantendo o cliente na base em nutrição; abandonar é sumir sem registro",
          "Desqualificar se aplica a prefeituras e processos públicos; abandonar, a clientes privados que não responderam",
        ], correta: 2, explicacao: "A negociação (a oportunidade específica) morre; o cliente continua na base, com nutrição a cada 60 dias e um gatilho registrado que, quando acontece, reabre a conversa (três das 22 desqualificadas no caso voltaram sozinhas). Abandonar é o que o vendedor faz quando não tem método." },
      ],
    },
  ],
  prova: [
    { pergunta: "Qual tipo de pergunta do SPIN deve ocupar a maior parte do tempo de uma visita de diagnóstico de alto valor?", opcoes: [
      "Situação, para entender a frota, as obras e o histórico da empresa",
      "Problema, para identificar com precisão o que dói na operação",
      "Necessidade de solução, para o cliente descrever e pedir a máquina",
      "Implicação, para o cliente sentir o custo em cadeia do problema",
    ], correta: 3, explicacao: "Rackham mediu: implicação é o que separa os vendedores de alto valor. Situação se pesquisa antes; problema abre a porta; necessidade fecha; implicação é onde o buraco ganha tamanho na cabeça do cliente." },
    { pergunta: "O gap calculado é R$ 3 mil por mês e a parcela seria R$ 9 mil. Qual é a conduta correta?", opcoes: [
      "Dizer que a máquina nova não se paga com a produção atual, propor usada ou consórcio e marcar a reabertura quando surgir sinal",
      "Aumentar o prazo do financiamento de 48 para 72 meses, para a parcela cair abaixo do gap e a conta fechar",
      "Apresentar apenas o valor à vista com desconto, sem mostrar a parcela, para o cliente avaliar o investimento total",
      "Revisar as premissas de horas e paradas com o cliente até o gap superar a parcela, porque ele costuma subestimar",
    ], correta: 0, explicacao: "Gap abaixo de 1 vez a parcela significa que a compra não se paga. Forçar (alongar, esconder, inflar premissas) produz cliente arrependido e reputação queimada. A honestidade rende indicações e a venda futura quando o gap fechar." },
    { pergunta: "No MEDDICC, o que significa ter 'E' zerado numa negociação?", opcoes: [
      "Não há métrica de retorno calculada e aceita pelo cliente",
      "Você não identificou ou não falou com quem assina (comprador econômico)",
      "Não há concorrente conhecido nem informação sobre como o cliente compara",
      "O cliente não tem dor identificada nem frase registrada no CRM",
    ], correta: 1, explicacao: "E é Economic buyer. Sem contato com quem libera o dinheiro, a proposta chega a ele por terceiros e sem contexto, e morre em 'tá caro'. É o buraco mais comum nas negociações 'quase fechadas' que não fecham." },
    { pergunta: "Qual pergunta é calibrada (convida) e não acusatória nem fechada?", opcoes: [
      "'Por que vocês não compraram da gente da última vez?'",
      "'Vocês estão satisfeitos com o fornecedor atual?'",
      "'Como foi a decisão da última compra? O que pesou?'",
      "'Vocês têm orçamento aprovado para este ano?'",
    ], correta: 2, explicacao: "'Como' e 'o que' abrem; 'por que' acusa; perguntas fechadas ('estão satisfeitos?', 'têm orçamento?') dão a saída fácil e ativam a defesa. A calibrada rende história, critério e decisor." },
    { pergunta: "Depois da resposta do cliente, o consultor conta até quatro em silêncio. Qual é o objetivo?", opcoes: [
      "Demonstrar reflexão e seriedade, mostrando que a resposta do cliente merece ser pensada antes de qualquer réplica",
      "Dar tempo para anotar no caderno os pontos principais antes de fazer a próxima pergunta do roteiro de diagnóstico",
      "Evitar interromper por educação, porque o cliente pode não ter terminado o raciocínio e se sentir atropelado",
      "Deixar o cliente completar com a parte que importa (arrependimento, sócio, critério), que só sai se houver espaço",
    ], correta: 3, explicacao: "O que vem depois dos quatro segundos é a informação que fecha a venda ('…e me arrependi; meu irmão joga na minha cara'). Vendedor que preenche o silêncio troca essa revelação por um argumento que o cliente já ouviu." },
    { pergunta: "Qual é a função do resumo ('deixa eu ver se entendi') antes de apresentar?", opcoes: [
      "Confirmar a dor nas palavras do cliente e obter licença para apresentar só o que responde a ela",
      "Registrar formalmente o que foi dito para usar na proposta escrita e no histórico do CRM",
      "Ganhar tempo para preparar a apresentação e escolher os argumentos mais adequados ao perfil",
      "Mostrar ao cliente que você prestou atenção e valoriza o que ele disse, construindo confiança",
    ], correta: 0, explicacao: "O resumo é o ponto de virada: o cliente corrige ou confirma, e o confirmado vira roteiro da apresentação e da proposta. Sem ele, você apresenta para a dor que imaginou." },
    { pergunta: "Numa empreiteira familiar, o contador opina no financiamento e o operador dá o veredito no teste. Que papéis de compra eles ocupam?", opcoes: [
      "Ambos são compradores econômicos, porque influenciam diretamente a liberação do dinheiro",
      "Contador é técnico/avaliador; operador é usuário",
      "Contador é campeão, porque apoia o financiamento; operador é bloqueador, porque resiste à mudança",
      "Ambos são influenciadores secundários sem relevância na decisão final, que é do dono",
    ], correta: 1, explicacao: "O técnico julga conformidade e números (contador no financiamento, engenheiro na especificação); o usuário vive com a máquina e dá o veredito prático. Cada um precisa de material diferente: memória de cálculo para um, teste na máquina para o outro." },
    { pergunta: "O mecânico da casa resiste à marca nova. Qual é a estratégia correta?", opcoes: [
      "Confrontar com dados de confiabilidade da New Holland versus a marca que ele conhece, com fontes verificáveis",
      "Pedir ao dono, com tato, que não ouça o mecânico nessa decisão, porque a resistência dele é natural e passageira",
      "Validar a preocupação, perguntar o que ele precisaria para ficar tranquilo e transformar cada item em entrega concreta",
      "Prometer que a máquina não vai dar problema e que, se der, a assistência resolve em 24 horas sem custo",
    ], correta: 2, explicacao: "Bloqueador perde algo com a mudança e precisa de uma saída digna. Confronto endurece, isolar o mecânico o torna inimigo diário, promessa vazia não convence. Atender às condições dele e dar um papel o converte em apoiador." },
    { pergunta: "Um contato simpático responde rápido e elogia a marca, mas não tem influência na decisão. No MEDDICC, ele é:", opcoes: [
      "Campeão, porque apoia a solução e fala bem da marca dentro da empresa",
      "Comprador econômico informal, porque a proximidade com o dono lhe dá voz na decisão",
      "Bloqueador disfarçado, porque simpatia sem poder costuma esconder um interesse em outro fornecedor",
      "Um contato cordial, não um campeão: campeão precisa de poder e motivo",
    ], correta: 3, explicacao: "Campeão vende por você quando você não está na sala, e para isso precisa de influência e de ganho pessoal com a compra. Simpatia sem poder não muda a decisão; confundir os dois é uma das causas de 'quase fechou'." },
    { pergunta: "Quantos dos quatro testes de desqualificação (gap, dinheiro, acesso, momento) precisam falhar para encerrar a negociação agora?", opcoes: [
      "Um: qualquer teste falhando justifica encerrar, porque negociação com buraco não fecha",
      "Dois: com dois falhando, encerrar com gatilho e data; com um, a próxima ação fecha o buraco em 14 dias",
      "Três: só com a maioria dos testes falhando, para não desqualificar negociações difíceis mas reais",
      "Quatro: só quando nada existe (sem gap, sem dinheiro, sem acesso, sem momento) a negociação deve sair",
    ], correta: 1, explicacao: "Um buraco é uma ação; dois buracos são esperança. A regra evita tanto a preguiça (desqualificar negociações difíceis mas reais) quanto o apego (manter negociações mortas por 90 dias)." },
    { pergunta: "Qual é a forma correta de encerrar uma negociação sem momento?", opcoes: [
      "Mensagem franca: a máquina não faz sentido agora; combinar gatilho (evento) e data; prometer um valor leve até lá",
      "Transferir a negociação para outro vendedor ou para o gerente, que pode ter uma abordagem diferente",
      "Parar de responder e esperar o cliente voltar quando o momento chegar, para não parecer insistente",
      "Enviar a última proposta com desconto e prazo de validade, para forçar uma decisão antes de encerrar",
    ], correta: 0, explicacao: "O encerramento elegante tira a pressão, define quando reabre (ordem de serviço, safra, edital) e mantém uma promessa de valor (avisar de uma usada). O cliente sai da negociação e fica na base mais quente do que antes." },
    { pergunta: "Antes da visita de diagnóstico, o que o consultor deve ter pesquisado para não gastar a visita com perguntas de situação?", opcoes: [
      "O preço da concorrência na região e as condições que ela está oferecendo para o mesmo tipo de máquina",
      "A ficha técnica da máquina que pretende oferecer e os argumentos de cada característica para aquela aplicação",
      "As condições de financiamento vigentes, as taxas de cada banco e as linhas disponíveis para o perfil do cliente",
      "Frota, obras, cidade, quem decide e histórico no CRM, Diário Oficial e conversa com o encarregado",
    ], correta: 3, explicacao: "Situação se levanta antes; na visita, o tempo é para problema, implicação e necessidade. Chegar sabendo a frota e as obras também é sinal de autoridade e respeito ao tempo do cliente." },
    { pergunta: "Você mediu o gap e ele é três vezes a parcela. Qual é a leitura e a postura de negociação?", opcoes: [
      "Gap grande: o cliente perde dinheiro todo mês sem decidir; a urgência é real e a entrega rápida vale mais que desconto",
      "Gap grande: há espaço para subir o preço ou reduzir concessões, porque o cliente tem folga para pagar mais",
      "Gap grande: dar um desconto para fechar rápido, porque a oportunidade é boa demais para correr risco de perder",
      "Gap grande: sugerir uma máquina de classe maior, porque a produção atual justifica um investimento mais alto",
    ], correta: 0, explicacao: "Relação acima de 3 significa que cada mês de indecisão custa muito ao cliente. A conversa vira 'quanto custa esperar', não 'quanto custa a máquina'. Desconto é desnecessário; entrega e disponibilidade são o argumento." },
  ],
};
