import type { Modulo } from "./tipos";

export const M5: Modulo = {
  id: "m5", nivel: 5, titulo: "Diagnóstico: SPIN, custo-hora e a máquina certa", tema: "Diagnóstico", cor: "#ffd23f",
  descricao: "Perguntas certas fazem o cliente vender para si mesmo. Quantifique a dor em reais, qualifique quem vale seu tempo, leia a operação e dimensione a máquina certa.",
  objetivos: [
    "Conduzir uma conversa SPIN completa adaptada a máquinas pesadas.",
    "Calcular custo por hora e retorno do investimento com os números do cliente.",
    "Qualificar com BANT e classificar a temperatura no CRM.",
    "Fazer uma visita técnica de diagnóstico com checklist e observação da operação.",
    "Dimensionar a máquina certa para a aplicação (retro, escavadeira, pá, motoniveladora, rolo).",
    "Transformar o levantamento de frota em um plano de renovação de 3 anos.",
  ],
  leituras: [
    "Neil Rackham — SPIN Selling.",
    "Manuais de aplicação New Holland Construction e Dynapac (capacidades, ciclos, produtividade).",
    "Caterpillar Performance Handbook (referência de produtividade por classe de máquina).",
  ],
  aulas: [
    {
      id: "m5a1", titulo: "SPIN Selling aplicado a máquinas pesadas", minutos: 12,
      resumo: "Situação, Problema, Implicação, Necessidade: a sequência que faz o cliente pedir a máquina antes de você oferecer.",
      blocos: [
        { tipo: "tabela", titulo: "As quatro famílias de perguntas (com exemplos do seu mercado)", colunas: ["Tipo", "Objetivo", "Exemplos"], linhas: [
          ["Situação", "Entender o cenário", "“Qual a frota hoje? Ano, horas? Que tipo de obra/serviço? Quantas horas por mês roda? Aluga alguma?”"],
          ["Problema", "Achar a dor", "“Ela para com que frequência? O consumo está como? Tem dificuldade de peça? Perde serviço por falta de máquina?”"],
          ["Implicação", "Fazer a dor doer em reais", "“Quando ela para, o que acontece com a obra? Quanto custa alugar pra cobrir? Já perdeu medição ou contrato por isso? Quanto o operador parado custa por dia?”"],
          ["Necessidade (solução)", "Cliente verbaliza a solução", "“Se você tivesse uma máquina que não parasse e gastasse 20% menos, o que mudaria no seu mês? Quanto valeria isso por ano?”"],
        ] },
        { tipo: "p", titulo: "Por que funciona", texto: "Perguntas de implicação fazem o cliente sentir o custo do problema; perguntas de necessidade fazem ele verbalizar a solução. Quando você apresenta a máquina depois disso, está apenas confirmando o que ele mesmo disse. A resistência cai porque a ideia é dele." },
        { tipo: "script", titulo: "Sequência completa (retroescavadeira)", itens: [
          "S: “Fulano, que retro você usa hoje? De que ano? Quantas horas por mês?”",
          "P: “E como ela está se comportando? Quebra muito? O consumo está normal?”",
          "I: “Quando ela para, você aluga? Quanto sai a diária? E a obra, atrasa? Já teve problema com o cliente por causa disso? Então num mês ruim, entre aluguel, operador parado e atraso, dá quanto?”",
          "N: “Se a máquina não parasse e gastasse menos, esse dinheiro ficaria com você. O que mudaria na obra? Vale a pena a gente ver o que uma nova custaria por mês contra esse número?”",
        ] },
        { tipo: "script", titulo: "Sequência completa (escavadeira na pedreira)", itens: [
          "S: “Quantas toneladas por dia vocês carregam? Com qual escavadeira? Horas dela?”",
          "P: “O ciclo de carregamento está como? Quantas caçambas por caminhão? Consumo por hora? Peças demoram?”",
          "I: “Se ela ficar 2 dias parada, quantos caminhões deixam de sair? Isso é quanto em brita? O cliente grande aceita atraso?”",
          "N: “Se uma máquina carregasse em 6 caçambas em vez de 9 e não parasse, quanto a mais vocês faturariam por mês? Quer que eu faça essa conta com os seus números?”",
        ] },
        { tipo: "script", titulo: "Sequência completa (motoniveladora na prefeitura)", itens: [
          "S: “Secretário, quantos quilômetros de estrada de terra o município tem? Quantas patrol? Ano e estado?”",
          "P: “Na chuva, quanto tempo leva pra recuperar as estradas? A patrol atual dá conta? Quebra?”",
          "I: “Quando a estrada fica intransitável, o que acontece? Ônibus escolar, leite, café? Quantas reclamações chegam? Quanto a prefeitura gasta com hora-máquina terceirizada?”",
          "N: “Se o município tivesse uma motoniveladora nova com assistência em 24 h, dava pra manter as estradas o ano todo sem terceirizar? Quanto isso economizaria e quanto vale politicamente?”",
        ] },
        { tipo: "erros", titulo: "Erros no SPIN", itens: [
          "Pular a implicação e ir direto para a solução: a dor não doeu ainda.",
          "Perguntas de situação demais (vira interrogatório). Pesquise antes; pergunte só o que não sabe.",
          "Responder a própria pergunta. Faça a pergunta e cale a boca.",
          "Não anotar os números que o cliente dá. Eles são a base da proposta.",
        ] },
        { tipo: "destaque", titulo: "Registre no CRM", texto: "Os números de implicação (diária de aluguel, dias parados, custo do operador, toneladas perdidas) vão no resumo da negociação. A proposta e o fechamento usam exatamente esses números." },
      ],
      missao: "Prepare 8 perguntas SPIN para o seu próximo cliente quente (2 de cada tipo) e use-as na visita. Registre no CRM os números de implicação que ele deu.",
      quiz: [
        { pergunta: "Qual tipo de pergunta faz o cliente sentir o custo do problema?", opcoes: ["Situação", "Implicação", "Necessidade"], correta: 1, explicacao: "Implicação transforma um problema em prejuízo mensurável." },
        { pergunta: "“Se a máquina não parasse, o que mudaria no seu mês?” é pergunta de:", opcoes: ["Problema", "Necessidade de solução", "Situação"], correta: 1, explicacao: "O cliente verbaliza a solução — e passa a defendê-la." },
        { pergunta: "Você já sabe a frota do cliente pelo CRM. Nas perguntas de situação você:", opcoes: ["Pergunta tudo de novo", "Confirma rápido e vai para problema e implicação", "Pula tudo"], correta: 1, explicacao: "Situação demais cansa. Use o que já sabe e aprofunde a dor." },
      ],
    },
    {
      id: "m5a2", titulo: "A conta que vende: custo por hora e retorno do investimento", minutos: 12,
      resumo: "Cliente não compra preço, compra conta. Aprenda a montar o custo por hora e o retorno com os números dele, na frente dele.",
      blocos: [
        { tipo: "p", titulo: "Custo por hora de uma máquina", texto: "Parcela ou depreciação + combustível + manutenção + operador, dividido pelas horas trabalhadas no mês. Exemplo simplificado de uma retro: parcela R$ 9.000 + diesel R$ 4.500 (150 h × 5 L × R$ 6) + manutenção R$ 800 + operador R$ 4.000 = R$ 18.300 / 150 h ≈ R$ 122/hora. Uma máquina antiga com consumo maior e 30 h/mês paradas pode custar mais por hora produzida mesmo “sem parcela”." },
        { tipo: "tabela", titulo: "Retro antiga x retro nova (exemplo com 150 h/mês)", colunas: ["Item", "Antiga (2011)", "Nova B95C"], linhas: [
          ["Parcela", "R$ 0", "R$ 9.000"],
          ["Diesel (L/h × R$ 6)", "6,5 L/h → R$ 5.850", "5,0 L/h → R$ 4.500"],
          ["Manutenção média/mês", "R$ 3.500", "R$ 800 (garantia)"],
          ["Aluguel para cobrir paradas (3 dias/mês × R$ 1.100)", "R$ 3.300", "R$ 0"],
          ["Operador (parado ou não)", "R$ 4.000", "R$ 4.000"],
          ["Horas efetivas", "126 h (3 dias parados)", "150 h"],
          ["Total / hora produzida", "R$ 16.650 / 126 ≈ R$ 132/h", "R$ 18.300 / 150 ≈ R$ 122/h"],
          ["E ao fim de 5 anos", "Máquina de 19 anos, sem valor", "Ativo com ~55% de revenda"],
        ] },
        { tipo: "p", titulo: "Retorno", texto: "Se a máquina nova fatura R$ 250/hora em serviço (ou economiza aluguel de R$ 1.200/dia), o cliente vê em quantos meses o investimento se paga. Mostre a conta em uma folha, com os números DELE — não com os seus. A conta de padaria, feita na frente do cliente, convence mais que qualquer planilha." },
        { tipo: "lista", titulo: "Números que você deve ter na ponta da língua", itens: [
          "Consumo médio de cada modelo em L/h por aplicação (fichas do CRM).",
          "Diária de aluguel na região por tipo de máquina (retro, escavadeira, rolo).",
          "Custo de operador com encargos por dia.",
          "Custo médio de manutenção de máquina com 8+ anos por mês.",
          "Valor de revenda aproximado da New Holland/Dynapac em 3 e 5 anos.",
          "Produtividade: caçambas/hora, m³/hora, km de estrada/dia, m² compactados/hora.",
        ] },
        { tipo: "script", titulo: "Fazendo a conta na frente do cliente", itens: [
          "“Deixa eu anotar aqui com os seus números: você paga R$ 1.100 de diária quando aluga, uns 3 dias por mês — R$ 3.300. A manutenção da antiga deu quanto nos últimos 6 meses? [R$ 20 mil] Então R$ 3.300 por mês. Diesel, ela faz uns 6,5 litros? A nova faz 5. Diferença de uns R$ 1.300. Só aí são R$ 8 mil por mês que estão saindo do seu bolso — e a parcela da nova é R$ 9 mil. Ou seja: você já paga quase uma máquina nova sem ter ela.”",
        ] },
        { tipo: "destaque", titulo: "Frase-chave", texto: "“Não estou te pedindo pra gastar R$ 480 mil. Estou te mostrando como ganhar R$ 30 mil por mês a mais com a mesma equipe.”" },
        { tipo: "caso", titulo: "Caso: a conta na tampa do capô", situacao: "Empreiteiro em Itapemirim dizia que a retro antiga “já estava paga” e não fazia sentido trocar.", acao: "O vendedor fez a conta na tampa do capô da própria retro, com os números que o cliente ia dando: manutenção, aluguel para cobrir, diesel, dias parados.", resultado: "O custo por hora da antiga deu R$ 141 contra R$ 118 da nova. O cliente pediu a proposta ali. Fechou com a usada na entrada.", licao: "“Já está paga” é a ilusão mais cara do mercado. A conta feita junto desfaz." },
      ],
      missao: "Monte a conta de custo por hora para 3 clientes com máquina antiga, usando os números deles (pergunte). Apresente em uma folha manuscrita e registre a reação no CRM.",
      quiz: [
        { pergunta: "O que compõe o custo por hora de uma máquina?", opcoes: ["Só a parcela", "Parcela/depreciação + combustível + manutenção + operador, dividido pelas horas produzidas", "Preço de compra dividido por 12"], correta: 1, explicacao: "Custo por hora produzida é a conta que mostra que máquina velha “paga” pode ser a mais cara." },
        { pergunta: "Os números da conta devem vir de:", opcoes: ["Da fábrica", "Do cliente, na conversa", "Da sua experiência"], correta: 1, explicacao: "Número do cliente é verdade para ele. Número seu é argumento de vendedor." },
      ],
    },
    {
      id: "m5a3", titulo: "Qualificação: quem vale seu tempo (BANT do interior)", minutos: 8,
      resumo: "Orçamento, autoridade, necessidade e prazo. Quatro perguntas para não gastar visita e proposta com quem não vai comprar.",
      blocos: [
        { tipo: "tabela", titulo: "As quatro perguntas de qualificação", colunas: ["Critério", "Pergunta natural", "Sinal verde"], linhas: [
          ["Budget (orçamento)", "“Como você costuma pagar máquina: financiado, consórcio, à vista? Tem usada pra entrar?”", "Caminho de pagamento definido ou usada de valor"],
          ["Authority (decisor)", "“Quem mais participa da decisão?”", "Você fala com o decisor ou tem acesso a ele"],
          ["Need (necessidade)", "“O que te fez pensar em máquina agora?”", "Dor concreta e recente (parada, obra nova, aluguel caro)"],
          ["Timing (prazo)", "“Quando você precisaria dela trabalhando?”", "Data ou evento em até 60–90 dias"],
        ] },
        { tipo: "p", titulo: "Classificando", texto: "Quente: orçamento definido + decisor identificado + necessidade clara + prazo em até 60 dias. Morno: falta um dos quatro. Frio: falta dois ou mais — mantenha relacionamento leve e reengaje quando mudar. Registre a temperatura na negociação do CRM; o Orientador de Vendas também estima por IA." },
        { tipo: "lista", titulo: "Sinais de desqualificação (respeite o seu tempo)", itens: [
          "“Só estou pesquisando” + sem obra + sem prazo: contato a cada 60 dias, sem proposta.",
          "Pede proposta para “ter como referência” para negociar com o fornecedor atual: envie a versão de uma página, sem detalhar condição.",
          "Não revela quem decide nem como paga depois de duas conversas.",
          "Já foi negado no banco e não tem entrada nem usada: trabalhe consórcio; não faça visita de demonstração ainda.",
        ] },
        { tipo: "destaque", titulo: "Cuidado", texto: "O “interessado eterno” consome visitas e proposta e nunca fecha. Se depois de duas conversas ele não tem orçamento nem prazo, mude a frequência para contato mensal e invista em quem tem." },
        { tipo: "caso", titulo: "Caso: as 4 visitas que não eram", situacao: "Vendedor fez 4 visitas e 2 demonstrações para um cliente que “adorava a máquina”. Nunca fechou.", acao: "Ao revisar, viu que nunca tinha perguntado como o cliente pagaria. Na 5ª conversa perguntou: o cliente estava negativado e sem entrada.", resultado: "Passou a qualificar orçamento na primeira conversa. As demonstrações do trimestre seguinte tiveram 60% de conversão.", licao: "Pergunta de orçamento na primeira conversa economiza semanas. Não é indelicado: é profissional." },
      ],
      missao: "Reclassifique a temperatura de todas as negociações abertas no CRM usando BANT. Para as mornas, identifique o critério que falta e planeje uma ação para obtê-lo.",
      quiz: [
        { pergunta: "Cliente com dor clara e prazo, mas sem caminho de pagamento e sem usada. Classificação:", opcoes: ["Quente", "Morno — trabalhe o financiamento antes da demonstração", "Frio"], correta: 1, explicacao: "Falta um critério (orçamento). Resolva-o antes de investir demonstração." },
        { pergunta: "Como perguntar orçamento sem parecer invasivo?", opcoes: ["“Você tem dinheiro?”", "“Como você costuma pagar máquina: financiado, consórcio, à vista? Tem usada pra entrar?”", "Não perguntar"], correta: 1, explicacao: "Pergunta sobre o caminho de pagamento é natural e revela o orçamento." },
      ],
    },
    {
      id: "m5a4", titulo: "A visita técnica de diagnóstico: o que observar na operação", minutos: 11,
      resumo: "A obra, a pedreira e a lavoura contam o que o cliente não diz. Checklist de observação e como transformar o que viu em argumento.",
      blocos: [
        { tipo: "p", texto: "Antes de perguntar, olhe. A máquina com vazamento, o pneu careca, o operador sem ar-condicionado às 14h, o caminhão esperando a escavadeira, a pilha de material que não sai, a estrada interna esburacada: cada detalhe é uma pergunta de implicação pronta. Quem observa bem faz o diagnóstico em 20 minutos e apresenta a máquina certa na primeira tentativa." },
        { tipo: "checklist", titulo: "Checklist de observação (obra / pedreira / lavoura)", itens: [
          "Frota: modelos, ano, horímetro, estado geral (vazamentos, pneus/esteiras, pintura, cabine).",
          "Operação: quantas máquinas trabalhando x paradas; caminhões esperando; ciclo de carregamento (cronometre).",
          "Operador: idade, postura, conforto, EPI, como fala da máquina.",
          "Material: tipo de solo/rocha (argila, saibro, brita, granito), umidade, volume a mover.",
          "Logística: distância de transporte, acesso, rampas, espaço de manobra.",
          "Manutenção: onde é feita, quem faz, estoque de peças, sinais de gambiarra.",
          "Gargalo: qual etapa segura o resto (escavação, carregamento, compactação, transporte)?",
          "Sinais de crescimento: obra nova, placa de contrato, pilha maior, equipe nova.",
        ] },
        { tipo: "tabela", titulo: "Do que você viu para o que você pergunta", colunas: ["Observação", "Pergunta de implicação", "Máquina/argumento"], linhas: [
          ["Caminhão esperando a escavadeira", "“Quantos minutos o caminhão espera por ciclo? Isso é quanto de frete parado por dia?”", "Escavadeira maior ou pá para carregar; produtividade"],
          ["Retro com vazamento e operador sem ar", "“Quanto tempo ela para por mês? O operador rende à tarde?”", "Retro nova: disponibilidade e conforto"],
          ["Estrada interna esburacada", "“Quanto vocês perdem de tempo e pneu nessa estrada?”", "Motoniveladora ou retro para manutenção interna"],
          ["Aterro com marcas de máquina afundando", "“O fiscal já reprovou compactação? Quanto custou o retrabalho?”", "Rolo pé-de-carneiro / medidor de compactação"],
          ["Máquina alugada na obra", "“Quanto é a diária? Quantos meses por ano?”", "Conta aluguel x parcela"],
        ] },
        { tipo: "lista", titulo: "Roteiro da visita técnica (60 minutos)", itens: [
          "10 min: rapport e caminhada pela operação (olhe antes de falar).",
          "20 min: SPIN com os números (anote).",
          "10 min: avaliação da usada, se houver (fotos, horímetro, estado).",
          "10 min: primeira hipótese de solução (“pelo que vi, uma E215C resolve o carregamento; deixa eu confirmar os números e te trago a conta”).",
          "10 min: combinar próximo passo (data da apresentação da proposta, com o comitê).",
        ] },
        { tipo: "caso", titulo: "Caso: o gargalo errado", situacao: "Cliente pediu proposta de escavadeira maior porque “o carregamento estava lento”.", acao: "Na visita, o vendedor cronometrou: a escavadeira carregava em 4 minutos, mas o caminhão levava 25 para ir e voltar da pilha. O gargalo era transporte e distância, não a escavadeira.", resultado: "Recomendou uma pá-carregadeira W170B para carregar na pilha perto da britagem, mais barata que a escavadeira pedida. O cliente fechou e virou referência.", licao: "Diagnóstico honesto vende a máquina certa — e a próxima." },
      ],
      missao: "Faça 2 visitas técnicas esta semana usando o checklist completo. Fotografe (com permissão) e registre no CRM as observações e o gargalo de cada operação.",
      quiz: [
        { pergunta: "Caminhões esperam a escavadeira. Qual é a pergunta de implicação?", opcoes: ["“Você quer uma escavadeira nova?”", "“Quantos minutos o caminhão espera por ciclo e quanto isso custa em frete parado?”", "“Qual é o ano da escavadeira?”"], correta: 1, explicacao: "Transforme a observação em custo. Depois a máquina vira solução óbvia." },
        { pergunta: "O que fazer antes das perguntas na visita técnica?", opcoes: ["Apresentar a máquina", "Caminhar e observar a operação", "Entregar o catálogo"], correta: 1, explicacao: "Observação alimenta perguntas melhores e evita interrogatório." },
      ],
    },
    {
      id: "m5a5", titulo: "Dimensionando a máquina certa para a aplicação", minutos: 12,
      resumo: "Retro ou mini? Qual escavadeira? Pá de que porte? Rolo liso ou pé-de-carneiro? Vender a máquina certa é o que gera indicação.",
      blocos: [
        { tipo: "p", texto: "Máquina superdimensionada custa caro e o cliente se arrepende; subdimensionada não dá conta e o cliente culpa a marca. O vendedor que dimensiona certo vende com margem, fecha mais rápido (a decisão fica óbvia) e colhe indicações. Regra: parta da aplicação e do volume, não do que o cliente pediu ou do que está no pátio." },
        { tipo: "tabela", titulo: "Retroescavadeira x mini x escavadeira", colunas: ["Situação", "Máquina indicada", "Por quê"], linhas: [
          ["Obra pequena/média, vários serviços (vala, carregar, nivelar), deslocamento entre obras", "Retro B95C / B110B", "Versatilidade e mobilidade em pneu; uma máquina faz vários serviços"],
          ["Espaço apertado, área urbana, rede de água/esgoto, paisagismo", "Miniescavadeira", "Precisão e acesso; menor custo por hora em serviço leve"],
          ["Escavação de volume, fundação, lagoa, terraplenagem pesada, pedreira", "Escavadeira E145C (14 t) a E245C (24 t)", "Produção por hora e força de escavação; escolha a classe pelo volume diário"],
          ["Lavoura de café: terraceamento e estrada interna", "Retro com braço extensível ou E145C", "Alcance em terreno inclinado; E145C se o volume for grande"],
        ] },
        { tipo: "tabela", titulo: "Escavadeira: classe por volume (referência)", colunas: ["Classe", "Modelo", "Aplicação típica", "Produção aproximada"], linhas: [
          ["14 t", "E145C", "Terraplenagem leve, lagoas, café, prefeitura", "80–110 m³/h"],
          ["17 t", "E175C", "Fundação, drenagem, loteamento", "110–140 m³/h"],
          ["21 t", "E215C", "Pedreira média, terraplenagem pesada, carregamento", "140–190 m³/h"],
          ["24 t", "E245C", "Pedreira grande, rocha, mineração", "180–230 m³/h"],
        ] },
        { tipo: "tabela", titulo: "Pá-carregadeira: escolha pelo ciclo e pelo caminhão", colunas: ["Modelo", "Caçamba", "Caminhão típico", "Uso"], linhas: [
          ["W130B", "~2,0 m³", "Toco / truck", "Usina de asfalto, areia, prefeitura, agrícola"],
          ["W170B", "~2,7 m³", "Truck / bitruck (3–4 caçambas)", "Pedreira média, britagem, pátio"],
          ["W190B", "~3,3 m³", "Bitruck / carreta", "Pedreira grande, mineração, porto"],
        ] },
        { tipo: "tabela", titulo: "Rolo compactador Dynapac: pelo material", colunas: ["Material", "Rolo", "Detalhe"], linhas: [
          ["Solo granular (saibro, areia, brita graduada)", "CA1500 / CA2500 liso vibratório", "Amplitude e frequência para camadas de 30–50 cm"],
          ["Solo coesivo (argila, silte — comum no sul do ES)", "CA2500D / CA3500 pé-de-carneiro (padfoot)", "Amassa e homogeneíza; evita o “borrachudo”"],
          ["Asfalto (CBUQ) e acabamento", "CC1200 / CC2200 tandem", "Compactação e acabamento sem marca; pavimentação urbana e rodoviária"],
          ["Serviço leve, vala, calçada, pequeno reparo", "Rolo leve / compactador manual", "Quando o CA é grande demais"],
        ] },
        { tipo: "script", titulo: "Recomendando a máquina certa", itens: [
          "“Pelo volume que você move por dia (uns 800 m³) e pelo caminhão bitruck, a E215C carrega em 4 caçambas e mantém o ciclo. A E245C seria mais máquina do que você precisa agora — a menos que o contrato dobre no ano que vem. Quer que eu monte as duas contas?”",
          "“Seu solo é argiloso. Rolo liso vai deixar borrachudo e o fiscal vai reprovar. O CA2500 pé-de-carneiro resolve a base; pra capa asfáltica você usa o tandem. Faz sentido?”",
        ] },
        { tipo: "caso", titulo: "Caso: o rolo errado do concorrente", situacao: "Empreiteira de pavimentação comprou do concorrente um rolo liso para base argilosa. O fiscal reprovou 3 vezes a compactação; retrabalho de R$ 80 mil.", acao: "O vendedor visitou, explicou a diferença entre liso e pé-de-carneiro em solo coesivo, e levou o caso de outra empreiteira que resolveu.", resultado: "Venderam um CA2500 padfoot e, 8 meses depois, um CC2200 tandem para a capa. A empreiteira trocou de fornecedor.", licao: "Conhecer aplicação vale mais que preço. O erro do concorrente é a sua porta." },
      ],
      missao: "Para 3 clientes em negociação, escreva a aplicação, o volume diário e o caminhão/material. Confirme se a máquina proposta é a certa (classe e tipo). Ajuste a proposta se necessário.",
      quiz: [
        { pergunta: "Solo argiloso, compactação de base. Rolo indicado:", opcoes: ["Liso vibratório", "Pé-de-carneiro (padfoot)", "Tandem de asfalto"], correta: 1, explicacao: "Solo coesivo exige pé-de-carneiro para não formar borrachudo." },
        { pergunta: "Cliente move 800 m³/dia com bitruck e pede uma E245C. Você:", opcoes: ["Vende a E245C", "Mostra que a E215C atende e apresenta as duas contas", "Vende uma E145C"], correta: 1, explicacao: "Dimensionar certo protege o cliente e a sua credibilidade." },
        { pergunta: "Obra pequena com vala, carregamento e nivelamento, mudando de obra toda semana. Máquina:", opcoes: ["Escavadeira E175C", "Retroescavadeira", "Pá W190B"], correta: 1, explicacao: "Retro é versatilidade e mobilidade em pneu." },
      ],
    },
    {
      id: "m5a6", titulo: "Levantamento de frota e plano de renovação de 3 anos", minutos: 10,
      resumo: "Transforme um cliente em uma sequência de vendas: idade, horas e custo crescente de cada máquina viram um calendário de trocas que você conduz.",
      blocos: [
        { tipo: "p", texto: "Cliente com 5 máquinas não compra uma; compra uma por ano se você mostrar o plano. O custo de manutenção sobe com a idade e as horas, e existe um ponto onde manter custa mais que trocar. O vendedor que faz o levantamento da frota e apresenta o plano de renovação vira o consultor de frota do cliente — e o concorrente nem é chamado." },
        { tipo: "tabela", titulo: "Ficha de frota (uma linha por máquina)", colunas: ["Campo", "Exemplo"], linhas: [
          ["Máquina / modelo / ano", "Retro Case 580 / 2012"],
          ["Horímetro", "9.800 h"],
          ["Uso mensal", "160 h"],
          ["Manutenção últimos 12 meses", "R$ 38 mil"],
          ["Dias parados últimos 12 meses", "22"],
          ["Consumo real", "6,8 L/h"],
          ["Valor de mercado hoje", "R$ 95 mil"],
          ["Prioridade de troca (1–5)", "1 (custo crescente e parada frequente)"],
        ] },
        { tipo: "lista", titulo: "Sinais de que chegou a hora de trocar", itens: [
          "Manutenção anual acima de 10–12% do valor de uma máquina nova equivalente.",
          "Mais de 8.000–10.000 h numa retro ou 12.000 h numa escavadeira, com histórico de grandes reparos.",
          "Dias parados acima de 5% do tempo útil.",
          "Valor de revenda caindo rápido (cada ano a mais tira mais do que a parcela).",
          "Obra ou contrato novo que a máquina atual não atende.",
        ] },
        { tipo: "p", titulo: "O plano de 3 anos", texto: "Ordene pela prioridade. Ano 1: troca a de maior custo/parada, com a usada na entrada. Ano 2: a segunda, usando parte do ganho da primeira. Ano 3: a terceira. Apresente o plano numa página com o custo atual de manutenção da frota e o custo projetado com as trocas. Combine revisões semestrais do plano — isso te dá presença garantida e vendas previsíveis. Registre cada máquina no cadastro de máquinas do CRM com o ano previsto de troca." },
        { tipo: "script", titulo: "Apresentando o plano", itens: [
          "“Fulano, fiz o levantamento da sua frota. Hoje você gasta uns R$ 110 mil por ano de manutenção nas 5 máquinas, e a retro de 2012 e a escavadeira de 2010 respondem por 70% disso. Se a gente trocar a retro este ano e a escavadeira no ano que vem, a manutenção cai pra R$ 45 mil e você ganha 40 dias de máquina rodando. Quer que eu monte a condição da primeira com a usada na entrada?”",
        ] },
        { tipo: "caso", titulo: "Caso: 4 máquinas em 3 anos", situacao: "Empreiteira em Cachoeiro com frota de 6 máquinas, 4 delas com mais de 10 anos. Comprava uma máquina a cada 4–5 anos, de marcas variadas.", acao: "O vendedor fez o levantamento completo e apresentou o plano de renovação com prioridade e conta anual. Combinou revisão semestral.", resultado: "4 máquinas New Holland em 3 anos (2 retros, 1 escavadeira, 1 pá), sem concorrência em nenhuma delas.", licao: "Quem tem o plano do cliente tem o cliente." },
      ],
      missao: "Escolha 3 clientes com 3+ máquinas, faça o levantamento de frota completo e apresente um plano de renovação de 3 anos para cada um. Cadastre todas as máquinas no CRM com o ano previsto de troca.",
      quiz: [
        { pergunta: "Qual sinal indica que manter custa mais que trocar?", opcoes: ["Máquina com 3 anos", "Manutenção anual acima de 10–12% do valor de uma nova e paradas frequentes", "Cor desbotada"], correta: 1, explicacao: "Custo crescente e parada são a virada. Mostre a curva ao cliente." },
        { pergunta: "O plano de renovação serve para:", opcoes: ["Vender tudo de uma vez", "Sequenciar trocas por prioridade e garantir presença e vendas previsíveis", "Encher o CRM"], correta: 1, explicacao: "Uma máquina por ano, sem concorrência, com revisão semestral." },
      ],
    },
  ],
  prova: [
    { pergunta: "“Quando ela para, quanto você paga de aluguel pra cobrir?” é pergunta de:", opcoes: ["Situação", "Implicação", "Necessidade"], correta: 1, explicacao: "Implicação quantifica a dor." },
    { pergunta: "Na conta de custo por hora, o que faz a máquina antiga “paga” ficar cara?", opcoes: ["A parcela", "Manutenção, consumo maior, aluguel para cobrir paradas e menos horas produzidas", "A cor"], correta: 1, explicacao: "Custo por hora produzida, não preço de compra." },
    { pergunta: "Cliente sem caminho de pagamento definido é:", opcoes: ["Quente", "Morno — resolva o financiamento antes de investir demonstração", "Frio para sempre"], correta: 1, explicacao: "BANT: falta o B." },
    { pergunta: "Caminhão espera 20 min por ciclo e a escavadeira carrega em 4. O gargalo é:", opcoes: ["A escavadeira", "O transporte/distância — talvez uma pá na pilha resolva", "O operador"], correta: 1, explicacao: "Observe antes de aceitar o pedido do cliente." },
    { pergunta: "Base argilosa reprovada pelo fiscal. Solução:", opcoes: ["Rolo liso maior", "Rolo pé-de-carneiro", "Mais passadas com o mesmo rolo"], correta: 1, explicacao: "Solo coesivo exige padfoot." },
    { pergunta: "O plano de renovação de frota gera:", opcoes: ["Uma venda", "Uma sequência de vendas previsíveis e presença sem concorrência", "Desconto"], correta: 1, explicacao: "Quem tem o plano tem o cliente." },
  ],
};
