import type { Modulo } from "./tipos";

export const M5: Modulo = {
  id: "m5", nivel: 5, titulo: "Valor, apresentação e proposta", tema: "Convencer", cor: "#f472b6",
  descricao: "Depois do diagnóstico, a hora de ensinar: o método Challenger (ensinar, adaptar, controlar), a demonstração e a visita técnica com medição, a conta feita na frente do cliente, a proposta escrita que se defende sozinha, o comparativo com concorrente sem depreciar ninguém e a apresentação para grupo, sócios e prefeitura.",
  objetivos: [
    "Construir um insight comercial que muda o critério de decisão do cliente de preço para custo total e produção.",
    "Planejar e executar uma demonstração ou visita técnica com medição real na aplicação do cliente.",
    "Fazer a conta de custo por hora, TCO e payback na frente do cliente com os números dele, usando a Calculadora do CRM.",
    "Escrever uma proposta de uma página que o sócio entende sem você na sala.",
    "Comparar com a concorrência com fatos verificáveis, sem depreciar, usando battlecards por modelo.",
    "Apresentar para grupos (sócios, diretoria, comissão de prefeitura) com estrutura, tempo e material para cada papel.",
  ],
  leituras: [
    "Matthew Dixon e Brent Adamson — A Venda Desafiadora (The Challenger Sale): ensinar, adaptar, assumir o controle.",
    "Nancy Duarte — Resonate: estrutura de apresentação que move decisões.",
    "Tom Sant — Persuasive Business Proposals: proposta que responde à dor, não ao catálogo.",
    "Manuais de operação e boletins técnicos dos modelos que você vende (consumo medido, ciclos, capacidade): leia uma vez por ano.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m5a1", titulo: "Challenger: ensinar, adaptar, controlar", minutos: 14,
      resumo: "A pesquisa da CEB com 6 mil vendedores mostrou que o perfil que mais vende em soluções complexas não é o 'relacionador': é o Desafiador, que ensina algo novo ao cliente, adapta a mensagem a cada decisor e assume o controle da conversa comercial.",
      blocos: [
        { tipo: "p", texto: "Dixon e Adamson estudaram 6 mil vendedores em 90 empresas e encontraram cinco perfis. O que mais aparecia entre os de alto desempenho em vendas complexas era o Desafiador: 39% dos melhores, contra 7% dos 'construtores de relacionamento'. O Desafiador não é agressivo: ele traz um insight que o cliente não tinha, reenquadra o problema, mostra com número o que o cliente está perdendo e conduz a conversa para uma decisão. No seu mercado, o insight é quase sempre o mesmo e quase ninguém o entrega: o custo real da máquina não está no preço; está nas horas paradas, no diesel, na revenda e na obra que não se pega." },
        { tipo: "framework", nome: "Conversa comercial Challenger em 6 passos", origem: "Dixon & Adamson — The Challenger Sale (CEB/Gartner)", passos: [
          "Aquecimento: mostre que entende o negócio dele (o que você levantou antes: obras, frota, pressões). 'Vocês pegaram três obras de rede de água em 8 meses; o gargalo virou máquina, não gente.'",
          "Reenquadre: um insight que muda a forma de olhar. 'A maioria dos empreiteiros compara preço de máquina. Os que crescem comparam custo por metro de vala aberta.'",
          "Afogamento racional: a conta que mostra o tamanho do problema com o enquadre novo. 'Com a máquina que para 3 dias, o seu metro de vala custa R$ 31; com uma que não para, R$ 24. Em 2.000 m/mês, são R$ 14 mil.'",
          "Impacto emocional: história de cliente parecido que viveu isso. 'O Marcos, de Rio Novo, perdeu a obra de Alegre por não confiar na máquina.'",
          "Um jeito novo: descreva a solução sem marca ainda. 'O que resolve é disponibilidade acima de 95% com assistência a menos de 50 km e consumo abaixo de X L/h.'",
          "A sua solução: só agora a E145C/B110B, com a prova de que atende ao 'jeito novo'. E o próximo passo: medição na obra.",
        ] },
        { tipo: "tabela", titulo: "Relacionador × Desafiador na prática", colunas: ["Situação", "Relacionador", "Desafiador"], linhas: [
          ["Cliente compara preço", "Pede desconto ao gerente", "Reenquadra para custo por metro/tonelada e mostra a conta"],
          ["Cliente adia", "'Sem problema, te espero'", "'Cada mês de espera custa R$ 14 mil na sua conta; o que precisa para decidir?'"],
          ["Sócio cético", "Evita o sócio", "Adapta a mensagem: parcela × faturamento para ele, produção para o dono"],
          ["Objeção difícil", "Concorda para não criar atrito", "Discorda com respeito e dado: 'na sua aplicação, o número é diferente; deixa eu mostrar'"],
          ["Fim da reunião", "'Qualquer coisa me chama'", "'Quinta às 8h eu meço a vala com o seu operador. Fechado?'"],
        ] },
        { tipo: "dialogo", titulo: "O reenquadre", falas: [
          { quem: "cliente", texto: "Recebi três propostas. A sua é a mais cara. Me convence." },
          { quem: "vendedor", texto: "Antes de convencer, uma pergunta: as três propostas te disseram quanto custa o seu metro de vala hoje?" },
          { quem: "cliente", texto: "Não. Falaram de preço e parcela." },
          { quem: "vendedor", texto: "É que máquina não se compara por preço; se compara por quanto custa o que ela produz. Com a sua retro atual, somando parada, diesel e aluguel de cobertura, o metro sai a R$ 31. Fiz a conta com os números que você me passou na obra. Posso mostrar?" },
          { quem: "nota", texto: "O Desafiador não responde à pergunta 'me convence' com argumento. Ele muda a pergunta: de 'qual é mais barata' para 'qual produz o metro mais barato'." },
          { quem: "cliente", texto: "Mostra." },
          { quem: "vendedor", texto: "Com uma máquina que roda 95% do tempo e gasta 2 litros a menos, o metro vai a R$ 24. Em 2.000 metros por mês, R$ 14 mil de diferença. A proposta mais barata tem R$ 40 mil a menos no preço e, pelo histórico de assistência dela aqui na região, uns 4 dias parados por mês. Você recupera os R$ 40 mil em 3 meses de metro mais caro." },
        ] },
        { tipo: "caso", titulo: "Caso: o insight do custo por tonelada", situacao: "Dono de pedreira em Vargem Alta comparava pás-carregadeiras por preço e caçamba. A concorrente era R$ 60 mil mais barata com caçamba igual.", acao: "O vendedor trouxe um insight: custo por tonelada carregada, considerando ciclo, consumo e disponibilidade. Mediu na pedreira dele: a máquina atual carregava um basculante em 5,5 ciclos; a W170B, em 4,5. Em 800 toneladas/dia, a diferença era um caminhão a mais por hora.", resultado: "O dono refez a conta com o gerente de produção e fechou a W170B. Disse depois: 'você foi o único que me falou de tonelada; os outros só falaram de máquina'.", licao: "O insight que muda o critério de decisão vale mais que qualquer desconto. E quase sempre ele está na unidade de produção do cliente: metro, tonelada, hectare, quilômetro." },
        { tipo: "script", titulo: "Reenquadres prontos por nicho", itens: [
          "Terraplenagem: 'Máquina não se compara por preço; se compara por custo do metro de vala aberta, com parada e diesel dentro.'",
          "Pedreira: 'A pergunta não é quanto custa a pá. É quanto custa a tonelada carregada — e quantos caminhões por hora você deixa de carregar.'",
          "Prefeitura: 'A patrol mais barata no pregão costuma ser a mais cara em 5 anos: manutenção, disponibilidade e revenda entram na conta do município.'",
          "Café: 'O carreador terceirizado parece barato até você somar 5 safras e os dias em que o terceiro não veio na hora da colheita.'",
          "Locação: 'Locadora não vende máquina; vende disponibilidade. Cada dia parado é um contrato em risco.'",
        ] },
        { tipo: "erros", titulo: "Erros de quem tenta ser Desafiador", itens: [
          "Confundir desafiar com discutir. O Desafiador discorda com dado e respeito, nunca com teimosia.",
          "Ensinar o que o cliente já sabe ('a máquina nova consome menos'). Insight é o que ele NÃO tinha somado.",
          "Reenquadrar sem número. Sem a conta, o reenquadre é frase de efeito.",
          "Mostrar a marca no passo 2. A solução com marca é o passo 6; antes disso, o cliente precisa aceitar o critério novo.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para o seu principal nicho, escreva a conversa Challenger completa em 6 passos, com a conta do passo 3 usando números reais de um cliente. Ensaie em voz alta em menos de 6 minutos. O reenquadre (passo 2) tem que caber em uma frase." },
      ],
      missao: "Na próxima negociação com comparação de preço, use o reenquadre do seu nicho (custo por metro, tonelada, hectare ou dia disponível) antes de qualquer argumento sobre a máquina. Registre no CRM a reação do cliente e se ele pediu a conta.",
      quiz: [
        { pergunta: "O cliente diz 'recebi três propostas, a sua é a mais cara, me convence'. Qual resposta segue o método Challenger?", opcoes: [
          "Oferecer um desconto para igualar a segunda proposta mais barata, porque com três propostas na mesa a decisão é de preço",
          "Perguntar se alguma proposta disse quanto custa o metro de vala hoje e reenquadrar a comparação para o custo do que a máquina produz",
          "Listar os diferenciais da máquina (motor, hidráulico, cabine, garantia) que justificam a diferença de preço",
          "Pedir para ver as outras propostas, para identificar diferenças de configuração e comparar em condições iguais",
        ], correta: 1, explicacao: "O Desafiador não responde à pergunta como ela veio; muda o critério. 'Qual é mais barata' vira 'qual produz o metro mais barato', com a conta. Listar diferenciais aceita o jogo do preço; ver as outras propostas e descontar é o Relacionador cedendo." },
        { pergunta: "Segundo a pesquisa da CEB, qual perfil de vendedor tem o pior desempenho em vendas complexas, apesar de ser o mais comum?", opcoes: [
          "O Lobo solitário, que segue o próprio instinto e ignora o processo da concessionária",
          "O Solucionador reativo, que resolve todos os problemas do cliente mas não conduz a decisão",
          "O Construtor de relacionamento, que evita atrito e prioriza ser querido pelo cliente",
          "O Trabalhador esforçado, que faz mais visitas do que os outros mas sem método",
        ], correta: 2, explicacao: "Apenas 7% dos melhores em vendas complexas eram Relacionadores, contra 39% de Desafiadores. Relacionamento importa, mas quem só relaciona não traz insight, não discorda e não conduz. O cliente gosta dele e compra do outro." },
        { pergunta: "O que caracteriza um insight comercial de verdade no passo 'reenquadre'?", opcoes: [
          "Uma informação técnica sobre a máquina que o cliente desconhecia, apresentada com a fonte e o impacto na operação dele",
          "Um dado de mercado sobre a liderança da marca na categoria, que reposiciona a escolha como a mais segura",
          "Uma observação precisa sobre o crescimento da empresa do cliente, que mostra preparo e abre a conversa comercial",
          "Uma forma nova de olhar o problema que o cliente não tinha somado (custo por metro, custo da inação), sustentada por número",
        ], correta: 3, explicacao: "Insight muda o critério de decisão, não o conhecimento sobre a máquina. 'A nova consome menos' ele já sabe; 'o seu metro de vala custa R$ 31 e poderia custar R$ 24' ele nunca somou. Sem número, é frase de efeito." },
        { pergunta: "Em qual passo da conversa Challenger a marca e o modelo aparecem pela primeira vez?", opcoes: [
          "No último, depois que o cliente aceitou o critério novo e a descrição da solução sem marca",
          "No aquecimento, para posicionar a empresa e dar credibilidade ao que vem depois",
          "No reenquadre, para associar o insight ao produto enquanto a atenção está alta",
          "No afogamento racional, para a conta ser feita com os números do modelo específico",
        ], correta: 0, explicacao: "Se a marca aparece cedo, o cliente lê tudo o que vem depois como propaganda. Primeiro ele aceita o critério (custo por metro), depois a solução genérica (disponibilidade alta, consumo baixo, assistência perto) e só então o modelo que a cumpre." },
        { pergunta: "Qual é a diferença entre 'desafiar' e 'discutir' com o cliente?", opcoes: [
          "Não há diferença prática: em ambos o vendedor sustenta a própria posição, e o que decide é a qualidade do argumento",
          "Desafiar é elogiar antes de discordar, para suavizar; discutir é discordar de forma direta, sem preparar o terreno",
          "Desafiar é discordar com dado verificável e respeito, para mudar o critério; discutir é insistir na própria opinião sem prova",
          "Desafiar funciona com perfil D, que gosta de confronto; discutir é o que acontece quando se tenta o mesmo com perfil C",
        ], correta: 2, explicacao: "'Na sua aplicação o número é diferente; deixa eu mostrar' é desafio. 'Você está errado' é discussão. A diferença é o dado e o respeito, e ela define se o cliente ouve ou se defende." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m5a2", titulo: "Demonstração e visita técnica com medição", minutos: 14,
      resumo: "Demo sem objetivo é passeio. A demonstração que vende mede algo que o cliente definiu como critério — ciclos por caminhão, litros por hora, metros por hora — com o operador dele, na aplicação dele, e termina com um número que vai para a proposta.",
      blocos: [
        { tipo: "p", texto: "A demonstração é a prova mais forte que você tem: o cliente vê, o operador sente, o gerente mede. Mas a maioria das demos é desperdiçada: a máquina chega, roda meia hora, todo mundo elogia a cabine e ninguém anota nada. Resultado: 'gostei' sem número, e o 'gostei' morre no sócio. A demo que vende tem hipótese ('a W170B carrega um basculante em 4,5 ciclos contra 5,5 da atual'), método (mesmo caminhão, mesmo operador, mesmo material), medição (cronômetro, contador de ciclos, medição de diesel) e um fechamento: o número na proposta e o próximo passo." },
        { tipo: "framework", nome: "Demo com método: HMMF", origem: "Prática de demonstração técnica em bens de capital (equipment demo best practices)", passos: [
          "Hipótese: o que você quer provar, ligado ao critério do cliente. 'Você disse que o gargalo é caminhão esperando na pá. A hipótese é: 4,5 ciclos por basculante contra 5,5.'",
          "Método: condições iguais. Mesmo material, mesmo caminhão, operador do cliente (com 30 minutos de adaptação), mesmo horário. Combine antes o que será medido e como.",
          "Medição: cronômetro e planilha na mão do gerente de produção do cliente (não na sua). Consumo pelo telemetria ou pelo tanque cheio antes/depois. Registre com foto.",
          "Fechamento: o número lido em voz alta pelo cliente, transcrito para a proposta no mesmo dia, e o próximo passo marcado ('quinta trago a proposta com esse número').",
        ] },
        { tipo: "tabela", titulo: "O que medir em cada aplicação", colunas: ["Aplicação", "Métrica principal", "Como medir", "Métrica secundária"], linhas: [
          ["Pá-carregadeira em pedreira", "Ciclos por basculante / caminhões por hora", "Cronômetro, 10 caminhões seguidos", "Consumo (L/h) via tanque ou telemetria"],
          ["Escavadeira em vala", "Metros de vala por hora (largura e profundidade fixas)", "Trena e cronômetro, 1 hora", "Consumo; ciclos de carga em caminhão"],
          ["Retroescavadeira em rede", "Tempo de vala + reaterro por trecho de 20 m", "Cronômetro por trecho", "Estabilidade, alcance, facilidade de operação (nota do operador)"],
          ["Motoniveladora em estrada", "Km de patrolamento por hora com acabamento aprovado", "Odômetro/GPS e inspeção do encarregado", "Consumo; conforto do operador em 4 horas"],
          ["Rolo compactador", "Passadas para atingir grau de compactação (ensaio)", "Densímetro ou frasco de areia da obra", "Largura de cobertura, produtividade m²/h"],
        ] },
        { tipo: "dialogo", titulo: "Combinando a demo antes de a máquina chegar", falas: [
          { quem: "vendedor", texto: "Seu Roberto, antes de eu trazer a W170B: o que precisa acontecer na demo pra você ter certeza de que ela resolve o gargalo da pá?" },
          { quem: "cliente", texto: "Ela tem que carregar meu basculante em menos de 5 ciclos, com o meu operador, no meu material." },
          { quem: "vendedor", texto: "Então vamos medir exatamente isso: 10 caminhões seguidos, o Jonas operando depois de meia hora de adaptação, cronômetro na mão do seu gerente. Se der 5 ou mais, eu levo a máquina embora e a gente não fala mais nisso. Se der menos, a gente senta com a proposta. Fechado?" },
          { quem: "nota", texto: "O critério é do cliente, o método é combinado, o risco é assumido pelo vendedor (se não der, vai embora). Isso é confiança — e é o que faz a demo virar decisão em vez de passeio." },
          { quem: "cliente", texto: "Fechado. Terça a pedreira tá cheia, faz na quarta." },
        ] },
        { tipo: "caso", titulo: "Caso: a demo que 'todo mundo gostou' e não vendeu", situacao: "Vendedor levou uma E215C para uma obra de barragem em Ibatiba. Rodou duas horas, operadores adoraram, o dono elogiou o conforto. Nada foi medido.", acao: "Duas semanas depois, o sócio perguntou 'e a diferença de produção?'. O vendedor não tinha número. A concorrente trouxe a demo dela com planilha de ciclos e ganhou.", resultado: "O mesmo vendedor, na demo seguinte, combinou hipótese e medição antes: 92 m³/h contra 71 da máquina atual, medidos pelo encarregado. Fechou em 10 dias.", licao: "Demo sem número é entretenimento. Número medido pelo cliente é argumento que sobrevive a quem não estava lá." },
        { tipo: "checklist", titulo: "Antes, durante e depois da demo", itens: [
          "Antes: hipótese escrita e aceita pelo cliente; método combinado; operador do cliente confirmado; técnico da concessionária presente; material e caminhão disponíveis.",
          "Antes: máquina revisada, limpa, abastecida; implemento correto para a aplicação (caçamba, dentes, sapata).",
          "Durante: 30 minutos de adaptação do operador ANTES de começar a medir; cronômetro na mão do cliente; fotos e vídeo curto.",
          "Durante: pergunte ao operador o que ele achou, na frente do dono — ele é o usuário e o influenciador.",
          "Depois: número lido pelo cliente, registrado no CRM e na proposta no mesmo dia; próximo passo com data.",
        ] },
        { tipo: "erros", titulo: "Erros de demo", itens: [
          "Demo sem hipótese: 'traz a máquina pra ele ver'. Ver não é medir.",
          "Operador da concessionária operando para 'mostrar melhor'. O cliente desconta: 'com o meu operador não dá isso'.",
          "Medir sem adaptação: os primeiros 30 minutos numa máquina nova são sempre piores. Combine o aquecimento.",
          "Deixar o número com você. A planilha tem que ser do cliente; ele é quem vai defender o número para o sócio.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escolha uma negociação em que a demo faria diferença. Escreva a hipótese (ligada ao critério do cliente), o método (condições iguais), a medição (quem, com quê) e o fechamento (número → proposta → próximo passo). Apresente ao cliente e combine a data." },
      ],
      missao: "Organize uma demonstração ou visita técnica com medição em uma negociação real, com a hipótese aceita pelo cliente antes, o operador dele na máquina e o cronômetro na mão do gerente dele. Registre o número medido no CRM e na proposta no mesmo dia.",
      quiz: [
        { pergunta: "Qual é o principal motivo de uma demo em que 'todo mundo gostou' não virar venda?", opcoes: [
          "O preço não foi apresentado no dia da demo, e o entusiasmo esfriou antes de a proposta chegar",
          "Nada foi medido: 'gostei' sem número não sobrevive à conversa com o sócio ou com o gerente que não estava lá",
          "A máquina demonstrada não era exatamente o modelo da proposta, e o cliente ficou com dúvida sobre a configuração",
          "O operador do cliente não estava presente, e a opinião de quem vai usar a máquina não foi ouvida no dia",
        ], correta: 1, explicacao: "A demo é prova quando gera um número medido pelo cliente. Sem hipótese e medição, ela produz entusiasmo que evapora em duas semanas, como no caso da aula, e a concorrente com planilha ganha." },
        { pergunta: "Quem deve operar a máquina durante a medição da demo?", opcoes: [
          "O operador do cliente, depois de um período de adaptação, para que o número seja dele e não seja descontado",
          "O demonstrador da concessionária, que conhece a máquina e extrai o máximo de produção em condições reais",
          "O vendedor, para mostrar domínio do produto e ganhar autoridade técnica diante do dono e do gerente",
          "Um operador contratado e neutro, para garantir imparcialidade e evitar que o resultado seja contestado",
        ], correta: 0, explicacao: "Se o demonstrador opera, o cliente pensa 'com o meu não dá isso'. O operador do cliente, com 30 minutos de adaptação, produz o número que o cliente acredita e que o operador defende internamente como usuário." },
        { pergunta: "Antes de levar a máquina, o vendedor pergunta ao dono da pedreira 'o que precisa acontecer na demo pra você ter certeza?'. Qual é a função dessa pergunta?", opcoes: [
          "Descobrir o preço que o cliente está disposto a pagar, porque a resposta revela o quanto ele valoriza o resultado",
          "Testar se o cliente está realmente interessado antes de gastar com transporte e mobilização da máquina",
          "Fazer o cliente definir o critério de sucesso, para que a medição seja dele e o resultado seja aceito sem discussão",
          "Reduzir a responsabilidade do vendedor caso a demo dê errado, porque o critério foi definido pelo cliente",
        ], correta: 2, explicacao: "Critério definido pelo cliente antes da demo elimina o 'mas eu queria ver outra coisa' depois. A demo passa a responder a uma pergunta dele. No diálogo da aula, o vendedor ainda assume o risco ('se der 5 ou mais eu levo embora'), o que constrói confiança." },
        { pergunta: "Por que a planilha de medição deve ficar na mão do gerente do cliente e não na do vendedor?", opcoes: [
          "Porque o vendedor precisa acompanhar a operação, conversar com o operador e não consegue anotar ao mesmo tempo",
          "Porque o número anotado pelo cliente é do cliente: ele vai defendê-lo para o sócio; o número do vendedor é 'número de vendedor'",
          "Porque o gerente conhece melhor os ciclos da pedreira e sabe identificar uma medição fora do padrão",
          "Porque o cliente pode desconfiar de que o vendedor manipule o cronômetro, e a planilha na mão dele evita a suspeita",
        ], correta: 1, explicacao: "Propriedade do número é propriedade da conclusão. É o mesmo princípio da conta do custo da inação: o que o cliente mede, ele acredita e repete. Desconfiança de manipulação é secundária; o ponto é quem vai defender o número quando você não estiver lá." },
        { pergunta: "Numa demo de escavadeira em vala, qual é a métrica principal e como medi-la?", opcoes: [
          "Conforto e fadiga do operador, por questionário ao fim do dia, porque é o que define a produção real ao longo do mês",
          "Consumo de diesel por hora, lido no painel da máquina, porque é o número que mais pesa no custo por hora",
          "Velocidade de deslocamento e tempo de posicionamento, por GPS, porque é onde a vala perde mais tempo",
          "Metros de vala por hora com largura e profundidade fixas, medidos com trena e cronômetro durante uma hora",
        ], correta: 3, explicacao: "A métrica principal é a unidade de produção do cliente (metro de vala). Consumo e conforto são secundárias e importantes, mas o que entra na conta do custo por metro é a produção medida em condições definidas." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m5a3", titulo: "A conta na frente do cliente: custo/hora, TCO e payback", minutos: 15,
      resumo: "A conta feita em casa e enviada por WhatsApp é um número de vendedor. A conta feita na obra, na Calculadora do CRM, com o cliente falando cada número, é uma decisão dele. Custo por hora, custo total de 5 anos e payback: três contas que você precisa fazer de cabeça e mostrar na tela.",
      blocos: [
        { tipo: "p", texto: "O Módulo 1 ensinou o custo por hora e o TCO. Aqui a habilidade é outra: fazer a conta AO VIVO, com o cliente, sem planilha de 14 abas, deixando ele preencher. A Calculadora de custo por hora do CRM existe para isso: você abre no celular ou no tablet, pergunta cada número, digita na frente dele e o resultado aparece grande na tela. A conta ao vivo tem três efeitos: os números são dele (credibilidade), ele vê a soma acontecer (compreensão) e o resultado é uma descoberta conjunta (propriedade). Nada disso acontece com um PDF." },
        { tipo: "conta", titulo: "TCO de 5 anos: E215C × concorrente 15% mais barata (8.000 h)", linhas: [
          ["Preço de aquisição", "R$ 890.000 × R$ 757.000"],
          ["Consumo: 18 L/h × 8.000 h × R$ 6,20 / 21 L/h", "R$ 892.800 × R$ 1.041.600"],
          ["Manutenção preventiva + peças de desgaste (5 anos)", "R$ 96.000 × R$ 118.000"],
          ["Paradas: 2 dias/mês × R$ 2.200 (aluguel + operador) / 5 dias/mês", "R$ 264.000 × R$ 660.000"],
          ["Valor de revenda em 5 anos (52% × 40%)", "− R$ 462.800 × − R$ 302.800"],
          ["Custo total de propriedade", "R$ 1.680.000 × R$ 2.273.800"],
          ["Custo por hora (÷ 8.000 h)", "R$ 210 × R$ 284"],
        ], conclusao: "A máquina 15% mais barata custa R$ 594 mil a mais em 5 anos — 35% a mais por hora. O preço é 1/3 do custo total; consumo, paradas e revenda são os outros 2/3. Quem compara só preço compara só um terço da conta." },
        { tipo: "framework", nome: "Conta ao vivo em 4 movimentos", origem: "Prática de venda baseada em valor (value selling) com a Calculadora do CRM", passos: [
          "Peça permissão e mostre a tela: 'Posso fazer uma conta rápida com você? Você me fala os números e eu digito.' A tela vira o centro da conversa; você sai do centro.",
          "Um número por vez, sempre dele: horas/mês, preço do diesel, dias parados, custo de cobertura, o que ele acha que revende. Se não souber, pergunte 'mais ou menos?' e marque como estimativa.",
          "Deixe o resultado aparecer e cale-se. O número grande na tela (custo/hora, economia mensal, payback) fala sozinho. Quatro segundos.",
          "Pergunte o que ele vê: 'O que esse número te diz?' Ele explica a própria conclusão. Depois: 'Quer que eu te mande isso pra você mostrar pro seu irmão?' — o print vai para o WhatsApp dele.",
        ] },
        { tipo: "dialogo", titulo: "A conta que o cliente fez", falas: [
          { quem: "vendedor", texto: "Quantas horas por mês ela roda?" },
          { quem: "cliente", texto: "Umas 180." },
          { quem: "vendedor", texto: "(digita) E o diesel, você paga quanto no posto?" },
          { quem: "cliente", texto: "Seis e trinta." },
          { quem: "vendedor", texto: "(digita) A atual gasta uns 21 por hora, você me disse. A E215C faz 18 medidos na obra do Marcos. Dias parados por mês, na média?" },
          { quem: "cliente", texto: "Uns três. E eu alugo pra cobrir, mil e oitocentos por dia." },
          { quem: "vendedor", texto: "(digita, vira a tela) Olha o que deu." },
          { quem: "nota", texto: "Silêncio. Na tela: economia de R$ 8.800 por mês, payback em 26 meses, custo por hora R$ 210 contra R$ 284." },
          { quem: "cliente", texto: "Oito mil e oitocentos por mês… é quase a parcela." },
          { quem: "vendedor", texto: "A parcela ficou em R$ 11.900 com a sua usada na entrada. Ou seja: a máquina nova custa R$ 3.100 líquidos por mês e você fica com o patrimônio no fim. Quer que eu te mande o print pro seu irmão ver?" },
        ] },
        { tipo: "caso", titulo: "Caso: PDF de 6 páginas × print de 1 tela", situacao: "Vendedor mandava simulações de TCO em PDF, bem feitas, de 6 páginas. Taxa de resposta: um em cada quatro clientes comentava.", acao: "Passou a fazer a conta na obra com a Calculadora, com os números ditos pelo cliente, e a mandar o print da tela de resultado com uma frase ('os números que você me passou hoje').", resultado: "Três em cada quatro clientes comentavam ou encaminhavam o print para o sócio. O tempo de decisão caiu de 6 para 3 semanas em média.", licao: "A conta não é um documento; é um momento. O PDF informa; a tela na obra convence." },
        { tipo: "tabela", titulo: "As três contas de cabeça (aproximações para a obra)", colunas: ["Conta", "Regra de bolso", "Exemplo"], linhas: [
          ["Custo por hora de diesel", "L/h × preço", "18 × 6,30 = R$ 113/h"],
          ["Diferença de consumo por mês", "ΔL/h × horas × preço", "3 × 180 × 6,30 = R$ 3.400/mês"],
          ["Custo de parada por mês", "dias × (aluguel + operador + atraso)", "3 × 2.200 = R$ 6.600/mês"],
          ["Payback aproximado", "diferença de preço ÷ economia mensal", "R$ 133 mil ÷ R$ 8.800 = 15 meses"],
          ["Parcela FINAME aproximada (60 m)", "valor financiado ÷ 60 × 1,25", "R$ 600 mil ÷ 60 × 1,25 = R$ 12.500"],
        ] },
        { tipo: "erros", titulo: "Erros na conta", itens: [
          "Digitar números seus. Um número seu errado derruba a conta inteira.",
          "Explicar o resultado antes de o cliente olhar. Deixe o número falar; depois pergunte o que ele vê.",
          "Inflar a economia. Use sempre o consumo medido e as paradas que ele relatou; se a conta não fechar, diga.",
          "Fazer a conta e não mandar o print. O print é o material do ratificador (sócio, contador).",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Abra a Calculadora do CRM e faça a conta de cabeça antes de digitar, para três cenários (retro em rede, escavadeira em vala, pá em pedreira). Compare o seu cálculo mental com o da tela. Treine até errar menos de 10%: na obra, você precisa saber o resultado antes de virar a tela." },
      ],
      missao: "Faça a conta ao vivo com dois clientes esta semana, na Calculadora do CRM, com todos os números ditos por eles. Envie o print da tela de resultado com a frase 'os números que você me passou hoje'. Registre no CRM se o cliente encaminhou para o sócio.",
      quiz: [
        { pergunta: "Por que a conta feita na obra, na tela, com o cliente dizendo os números, convence mais do que um PDF bem feito enviado depois?", opcoes: [
          "Porque os números são dele, ele vê a soma acontecer e o resultado é uma descoberta conjunta; o PDF é um número de vendedor",
          "Porque o cliente do interior raramente abre um PDF no celular, e a tela na obra garante que a conta seja vista",
          "Porque a Calculadora do CRM usa fórmulas mais completas e precisas do que uma planilha montada à mão",
          "Porque o PDF pode ser encaminhado à concorrência e virar referência de preço, enquanto a tela fica na conversa",
        ], correta: 0, explicacao: "Credibilidade (números dele), compreensão (soma ao vivo) e propriedade (descoberta conjunta). No caso da aula, a taxa de comentários triplicou e o tempo de decisão caiu pela metade sem mudar a matemática: mudou o momento." },
        { pergunta: "No TCO de 5 anos da aula, a máquina 15% mais barata no preço saiu 35% mais cara por hora. Qual fator pesou mais nessa diferença?", opcoes: [
          "A diferença de preço de aquisição, que acumula juros ao longo do financiamento",
          "A diferença de manutenção preventiva, que na máquina mais barata usa peças de menor vida útil",
          "As horas paradas (5 dias contra 2 por mês) e o consumo, somados à revenda menor",
          "O custo do financiamento, que é maior para a marca sem banco próprio",
        ], correta: 2, explicacao: "Paradas (R$ 396 mil a mais), consumo (R$ 149 mil) e revenda (R$ 160 mil a menos) superam de longe os R$ 133 mil de diferença de preço. O preço é um terço da conta; a operação é dois terços. É isso que o cliente descobre na tela." },
        { pergunta: "O resultado apareceu na tela: economia de R$ 8.800 por mês. Qual é a conduta correta do vendedor nesse instante?", opcoes: [
          "Explicar imediatamente como o número foi calculado, para evitar que o cliente desconfie da conta",
          "Apresentar a parcela na mesma hora, para aproveitar o impacto e mostrar que a máquina se paga",
          "Perguntar se ele quer fechar hoje, porque a conta fechou e o momento de decisão é esse",
          "Silêncio de alguns segundos e depois 'o que esse número te diz?', deixando o cliente formular a própria conclusão",
        ], correta: 3, explicacao: "O número grande fala sozinho; a explicação precoce rouba a descoberta. A pergunta calibrada faz o cliente verbalizar a conclusão ('é quase a parcela'), e conclusão verbalizada é conclusão defendida. A parcela vem logo depois, ao lado da economia." },
        { pergunta: "O cliente não sabe quantos dias por mês a máquina para. O que o consultor faz?", opcoes: [
          "Usa a média de mercado para máquinas daquela idade, sem comentar, porque o cliente não tem o dado e a média é confiável",
          "Pergunta 'mais ou menos? dois, três?' e marca o número como estimativa dele, oferecendo revisar com o histórico de manutenção",
          "Pula a linha das paradas para não inflar a conta, mantendo apenas o consumo, que é verificável, e a revenda",
          "Usa o pior cenário conhecido para máquinas daquela idade, porque o cliente tende a subestimar e a conta precisa ser convincente",
        ], correta: 1, explicacao: "A estimativa ainda é dele e fica marcada como tal; a oferta de revisar com o histórico mantém a honestidade. Média de mercado silenciosa é número seu; pular as paradas esconde o maior custo; pior cenário é inflar, e o cliente percebe." },
        { pergunta: "Qual é a regra de bolso para o payback aproximado da máquina mais cara?", opcoes: [
          "Preço total da máquina dividido pela economia anual",
          "Economia mensal multiplicada pelos 60 meses do financiamento",
          "Diferença de preço entre as máquinas dividida pela economia mensal",
          "Parcela mensal dividida pelo custo por hora da máquina",
        ], correta: 2, explicacao: "Payback responde 'em quantos meses a diferença de preço se paga com a economia'. R$ 133 mil de diferença ÷ R$ 8.800 de economia mensal = 15 meses. É a conta que o cliente entende de cabeça e repete para o sócio." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m5a4", titulo: "A proposta escrita que se defende sozinha", minutos: 13,
      resumo: "A proposta vai ser lida por quem não estava na visita: o sócio, o contador, o gerente do banco. Ela tem que contar a história inteira em uma página: a dor nas palavras do cliente, o gap, a solução, a conta, a prova e o próximo passo. Catálogo grampeado não é proposta.",
      blocos: [
        { tipo: "p", texto: "A maior parte das propostas de máquina é uma tabela de preço com a ficha técnica anexada. Elas respondem à pergunta 'quanto custa' e ignoram a pergunta que o ratificador faz: 'por que essa e por que agora?'. Tom Sant, que estudou milhares de propostas vencedoras, resume: proposta persuasiva começa pela necessidade do cliente, mostra o resultado esperado, apresenta a solução como caminho para esse resultado e prova que você consegue entregar. Preço vem no fim — e ao lado da conta." },
        { tipo: "framework", nome: "Proposta de uma página (estrutura NOSE + prova + passo)", origem: "Tom Sant — Persuasive Business Proposals (Needs, Outcomes, Solution, Evidence)", passos: [
          "Necessidade (2 linhas, nas palavras do cliente): 'A retro atual para 3 dias por mês; a obra de Alegre não foi assumida por falta de confiança na máquina.'",
          "Resultado esperado (2 linhas, com número): 'Disponibilidade acima de 95%, economia de R$ 8.800/mês em diesel e cobertura, capacidade de assumir a segunda frente.'",
          "Solução (3 linhas): modelo, configuração, o que resolve o quê. 'B110B com caçamba de X, 4x4, cabine fechada: assistência a 40 km (técnico Y), consumo medido de N L/h.'",
          "Evidência (3 linhas): número medido na demo, cliente de referência com contato, garantia e prazo confirmado por escrito.",
          "Investimento (4 linhas): valor, condição (usada na troca, FINAME, parcela) AO LADO da economia mensal e do payback; validade da proposta.",
          "Próximo passo (1 linha): 'Reunião de revisão com os sócios: quinta 17/10, 17h, na obra.' A proposta não termina em 'aguardo retorno'.",
        ] },
        { tipo: "tabela", titulo: "Proposta comum × proposta que se defende", colunas: ["Item", "Proposta comum", "Proposta que se defende"], linhas: [
          ["Abertura", "'Conforme solicitado, segue proposta…'", "A dor nas palavras do cliente"],
          ["Produto", "Ficha técnica completa em anexo", "Três características ligadas a três problemas dele"],
          ["Preço", "Tabela, desconto, condição", "Investimento ao lado da economia e do payback"],
          ["Prova", "Nenhuma", "Demo medida, referência com contato, garantia"],
          ["Fechamento", "'Ficamos à disposição'", "Reunião marcada com data e quem participa"],
          ["Tamanho", "6 a 12 páginas", "1 página + anexos opcionais para o técnico"],
        ] },
        { tipo: "dialogo", titulo: "Entregando a proposta (nunca só por WhatsApp)", falas: [
          { quem: "vendedor", texto: "Trouxe a proposta. É uma página; o resto é anexo pro seu contador. Deixa eu passar com você em 5 minutos e você me diz o que está faltando." },
          { quem: "cliente", texto: "Manda por WhatsApp que eu vejo depois." },
          { quem: "vendedor", texto: "Mando também. Mas 5 minutos agora evitam que ela chegue no seu irmão sem contexto e vire só um número. Olha aqui: comecei com o que você me disse na obra — 'não confio nela pra pegar Alegre'." },
          { quem: "cliente", texto: "É isso mesmo." },
          { quem: "vendedor", texto: "Aqui a economia que a gente somou juntos, aqui o que a demo mediu, aqui a parcela ao lado. E aqui a data que a gente combinou com o seu irmão. Falta alguma coisa que ele vai perguntar?" },
          { quem: "nota", texto: "Entrega presencial, curta, com a pergunta 'o que está faltando?' — que revela a objeção antes de a proposta ser lida sem você." },
        ] },
        { tipo: "caso", titulo: "Caso: a proposta lida pelo contador", situacao: "Vendedor enviou proposta de 9 páginas por WhatsApp para um empreiteiro, que encaminhou ao contador. O contador respondeu: 'muito caro, e nem sei pra que serve tanta página'. A negociação esfriou.", acao: "O vendedor reescreveu em uma página: dor (palavras do cliente), economia mensal somada com ele, parcela ao lado, payback de 15 meses, referência com telefone e uma linha para o contador: 'FINAME com carência de 6 meses; memória de cálculo em anexo'. Entregou pessoalmente e pediu 10 minutos com o contador.", resultado: "O contador aprovou em dois dias. Comentou: 'agora eu entendi o que está sendo comprado'.", licao: "A proposta é escrita para quem não estava na visita. Se ela precisa de você para ser entendida, ela não é uma proposta; é um roteiro." },
        { tipo: "checklist", titulo: "Antes de entregar", itens: [
          "A primeira frase é a dor nas palavras do cliente (registradas no CRM)?",
          "O resultado esperado tem número (economia/mês, produção, disponibilidade)?",
          "Cada característica citada resolve um problema que ele nomeou?",
          "Há prova: medição, referência com contato, garantia, prazo por escrito?",
          "O investimento está ao lado da economia e do payback, com a condição (usada, FINAME, parcela)?",
          "Há validade e o próximo passo com data e participantes?",
          "Cabe em uma página? Anexos separados para o técnico/contador?",
        ] },
        { tipo: "erros", titulo: "Erros de proposta", itens: [
          "Começar por 'conforme solicitado'. Ninguém solicitou; você diagnosticou.",
          "Preço sem a economia ao lado. Sozinho, preço é custo.",
          "Enviar só por WhatsApp. A proposta chega ao sócio sem contexto e vira número.",
          "Terminar com 'ficamos à disposição'. Proposta sem próximo passo datado é proposta que esfria.",
          "Validade indefinida. Sem validade, não há motivo para decidir esta semana.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Pegue a última proposta que você enviou. Reescreva em uma página com a estrutura NOSE + prova + passo, usando as palavras do cliente registradas no CRM. Compare: quantas vezes aparece 'nós/nossa' na antiga e quantas 'você/sua obra' na nova?" },
      ],
      missao: "Reescreva a proposta de uma negociação aberta no formato de uma página e entregue pessoalmente, com a pergunta 'o que está faltando que o seu sócio vai perguntar?'. Registre no CRM a resposta e a data da reunião de revisão marcada.",
      quiz: [
        { pergunta: "Qual deve ser a primeira frase de uma proposta que se defende sozinha?", opcoes: [
          "'Conforme solicitado, apresentamos nossa proposta comercial para a retroescavadeira B110B', para situar o leitor",
          "A apresentação da concessionária e da marca, para o sócio que não conhece o vendedor saber com quem está lidando",
          "O valor e as condições de pagamento, para ir direto ao ponto e respeitar o tempo de quem decide",
          "A dor do cliente nas palavras dele ('a retro atual para 3 dias por mês; a obra de Alegre não foi assumida')",
        ], correta: 3, explicacao: "Quem lê (sócio, contador) precisa saber em duas linhas por que a compra está sendo considerada. A dor nas palavras do cliente faz o dono se reconhecer e o ratificador entender. 'Conforme solicitado' e apresentação da empresa são sobre você." },
        { pergunta: "Por que a proposta não deve ser enviada apenas por WhatsApp?", opcoes: [
          "Porque o cliente pode encaminhá-la ao sócio sem contexto e ela vira só um número, sem a história que a justifica",
          "Porque arquivos enviados por WhatsApp perdem a formatação e a proposta chega com aparência amadora",
          "Porque a política comercial exige entrega presencial com assinatura de recebimento para a proposta ter validade",
          "Porque o cliente pode compartilhar a proposta com a concorrência, que passa a conhecer o seu preço e a sua condição",
        ], correta: 0, explicacao: "Cinco minutos de entrega presencial (ou por vídeo) garantem que a proposta seja lida com a história e revelam a objeção antes ('o que está faltando?'). Enviada solta, ela é lida pelo contador como 'muito caro' sem que ninguém explique o que está sendo comprado." },
        { pergunta: "Onde o investimento (preço, parcela) deve aparecer na proposta de uma página?", opcoes: [
          "No início, para o cliente saber logo se cabe no orçamento e ler o resto com essa referência",
          "No fim, ao lado da economia mensal e do payback, com a condição de pagamento e a validade",
          "Em anexo separado, para não contaminar a leitura do valor construído na página principal",
          "No meio, entre a solução e a prova, para o preço ser lido depois do que resolve e antes das garantias",
        ], correta: 1, explicacao: "Preço vem depois da necessidade, do resultado, da solução e da prova, e sempre com a economia ao lado, para ser lido como investimento com retorno. No início ele é lido como custo; em anexo, ele fica sem o enquadre." },
        { pergunta: "Qual é o problema de terminar a proposta com 'ficamos à disposição para esclarecimentos'?", opcoes: [
          "É formal demais para o cliente do interior, que prefere um fechamento mais pessoal e direto",
          "Sugere que a proposta tem pontos obscuros que precisarão ser esclarecidos, e enfraquece o documento",
          "Deixa o próximo passo indefinido; a proposta esfria porque ninguém tem uma data para decidir",
          "Não há problema: é a forma padrão e cortês de encerrar uma proposta comercial no mercado",
        ], correta: 2, explicacao: "Proposta sem próximo passo datado (reunião de revisão com os sócios, quinta 17h) depende de o cliente tomar a iniciativa, e cliente com obra não toma. O fechamento da proposta é a agenda, não a cortesia." },
        { pergunta: "O contador do cliente respondeu 'muito caro, e nem sei pra que serve tanta página'. Qual é o diagnóstico?", opcoes: [
          "O contador não é o decisor e a opinião dele deve ser tratada como ruído; o foco continua no dono",
          "O preço realmente está acima do que o mercado pratica e a proposta precisa ser revista antes de voltar",
          "O cliente não explicou a compra ao contador antes de encaminhar, o que não é responsabilidade do vendedor",
          "A proposta não se defende sozinha: falta a dor, o resultado com número e a economia ao lado do preço, e sobra ficha técnica",
        ], correta: 3, explicacao: "O contador é o técnico da conta e leu o que recebeu: páginas de catálogo e um preço. A reescrita em uma página (dor, economia, parcela ao lado, payback, linha para o contador) fez o mesmo contador aprovar em dois dias. A proposta falhou, não o contador." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m5a5", titulo: "Comparar sem depreciar: battlecards por modelo", minutos: 13,
      resumo: "Falar mal do concorrente perde venda no interior e ainda faz o cliente defender a outra marca. O consultor compara com fatos verificáveis, reconhece o que o concorrente faz bem e mostra onde a diferença importa para a aplicação daquele cliente.",
      blocos: [
        { tipo: "p", texto: "O cliente que está comparando já gostou de alguma coisa na outra marca. Quando você a ataca, ataca a escolha dele, e ele se defende. Quando você reconhece o ponto forte do concorrente e leva a comparação para o terreno onde a diferença é verificável e relevante para a aplicação dele, o cliente confia — porque você foi justo. Battlecard é a ficha de um lado só: para cada concorrente e modelo, o que ele faz bem, onde a diferença importa, a prova, e como responder às três objeções que ele gera." },
        { tipo: "framework", nome: "Battlecard (uma página por confronto de modelos)", origem: "Prática de competitive enablement em vendas B2B", passos: [
          "Confronto: 'E215C × Komatsu PC210 × Sany SY215' — sempre por modelo equivalente, nunca marca contra marca.",
          "O que eles fazem bem (honesto): preço, rede em outra região, financiamento próprio, prazo de entrega. Reconheça em voz alta na frente do cliente.",
          "Onde a diferença importa (3 itens, verificáveis): consumo medido, assistência a X km com técnico nomeado, disponibilidade, revenda em 5 anos com fonte (tabela de usadas), peças em estoque.",
          "Prova: medição de demo, cliente que trocou de marca com contato, boletim técnico, anúncio de usadas com preço.",
          "As 3 objeções que o concorrente gera e as respostas: 'é 15% mais barata' (TCO), 'tem financiamento próprio' (compare taxa total), 'entrega em 10 dias' (confirme e mostre custo de esperar × custo de parar).",
          "O que NÃO dizer: qualquer frase sobre qualidade sem prova, qualquer piada, qualquer 'todo mundo sabe que…'.",
        ] },
        { tipo: "dialogo", titulo: "Reconhecer e reposicionar", falas: [
          { quem: "cliente", texto: "A Sany é 90 mil mais barata e o vendedor deles disse que a New Holland é máquina de agricultura, não de pedreira." },
          { quem: "vendedor", texto: "Sobre o preço, é verdade: a Sany entra mais barata, e o financiamento próprio deles é competitivo. Sobre 'máquina de agricultura', eu prefiro te mostrar a pedreira do Roberto, em Vargem Alta, onde a W170B carrega 800 toneladas por dia há dois anos, e você pergunta pra ele. Posso te passar o telefone?" },
          { quem: "nota", texto: "Reconheceu o preço e o financiamento (honestidade), não rebateu a provocação com outra provocação (elegância), levou para prova verificável (pedreira do Roberto)." },
          { quem: "cliente", texto: "E os 90 mil?" },
          { quem: "vendedor", texto: "Na sua pedreira, 90 mil são uns 4 meses da diferença de consumo e paradas que a gente somou. O que eu não sei — e você deveria perguntar pra eles — é onde fica o técnico deles mais perto e quanto tempo leva uma peça. Aqui, é o Diego, em Cachoeiro, e peça de desgaste tem em estoque. Isso vale mais que 90 mil quando a máquina para na safra da pedreira." },
        ] },
        { tipo: "tabela", titulo: "Battlecard resumido: E215C × concorrentes (exemplo — atualize com dados da sua região)", colunas: ["Item", "E215C", "Concorrente A (japonesa)", "Concorrente B (chinesa)"], linhas: [
          ["Ponto forte deles", "—", "Marca forte, rede nacional, revenda alta", "Preço 15–20% menor, entrega rápida, financiamento próprio"],
          ["Consumo (medido em obra parecida)", "18 L/h", "18–19 L/h", "20–22 L/h"],
          ["Assistência mais próxima", "Cachoeiro, técnico nomeado", "Vitória (140 km)", "Vitória / Rio (dependendo do modelo)"],
          ["Revenda em 5 anos (tabela de usadas)", "50–55%", "55–60%", "35–40%"],
          ["Objeção típica gerada", "'É mais cara que a chinesa'", "'É a marca que todo mundo tem'", "'Vale o risco pelo preço'"],
          ["Resposta", "TCO e assistência", "Assistência local e prazo", "Custo de parada e revenda"],
        ] },
        { tipo: "caso", titulo: "Caso: a piada que custou uma frota", situacao: "Vendedor, em visita a uma locadora, fez piada com a marca chinesa que o cliente já tinha na frota: 'isso aí é descartável'. O dono tinha três delas.", acao: "O dono não respondeu na hora. Semanas depois, comprou mais duas da marca chinesa e comentou na associação: 'o vendedor da New Holland me chamou de burro sem saber'.", resultado: "A locadora nunca mais recebeu o vendedor. A história circulou em três cidades.", licao: "Depreciar a marca que o cliente tem é depreciar a decisão dele. No interior, o comentário volta em semanas e com juros." },
        { tipo: "script", titulo: "Frases para comparar com elegância", itens: [
          "'Eles fazem X bem, isso é verdade. Onde a diferença aparece na sua aplicação é em Y, e eu prefiro te mostrar do que falar: [prova].'",
          "'Não vou falar da máquina deles; vou te dar duas perguntas pra fazer pra eles: onde fica o técnico e quanto tempo leva a peça. Depois compara com a minha resposta.'",
          "'Se a sua prioridade for preço de entrada, a deles é uma boa opção. Se for custo por tonelada em 5 anos, a conta muda — e eu te mostro com os seus números.'",
          "'Você tem três delas e conhece melhor que eu. O que te faria trocar de marca na próxima?'",
        ] },
        { tipo: "erros", titulo: "Erros de comparação", itens: [
          "Atacar a marca que o cliente já tem. Ele defende a própria decisão e você vira inimigo.",
          "Comparar sem número. 'A nossa é melhor' é opinião; '18 contra 21 L/h medidos' é fato.",
          "Não reconhecer o ponto forte do concorrente. O cliente sabe que existe; se você nega, perde a credibilidade.",
          "Repetir boato ('a assistência deles fechou'). Se não puder provar, não diga.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte o battlecard dos dois confrontos mais frequentes na sua região (ex.: B110B × JCB 3CX × Case 580N; E215C × PC210 × SY215) com dados verificáveis: consumo medido, distância da assistência, revenda em anúncios de usadas. Atualize a cada semestre." },
      ],
      missao: "Crie o battlecard do seu confronto mais comum e use-o na próxima comparação: reconheça um ponto forte do concorrente em voz alta, leve para as três diferenças verificáveis e ofereça a prova. Registre no CRM como o cliente reagiu.",
      quiz: [
        { pergunta: "O cliente diz que o vendedor da concorrente chamou a New Holland de 'máquina de agricultura, não de pedreira'. Qual resposta preserva a credibilidade?", opcoes: [
          "Não rebater a provocação e oferecer a prova verificável: a pedreira de um cliente com a mesma máquina há dois anos e o telefone dele",
          "Responder que a concorrente é 'máquina descartável' e que todo mundo na região sabe, para neutralizar a provocação",
          "Explicar a história da New Holland Construction, a origem da linha de pedreira e os modelos vendidos em mineração",
          "Ignorar o comentário e voltar ao preço, que é o que o cliente quer discutir, sem dar importância à provocação",
        ], correta: 0, explicacao: "Provocação respondida com provocação vira briga de vendedor, e o cliente desconfia dos dois. Prova verificável (pedreira do Roberto, contato) responde sem discutir. História da marca é argumento seu; a pedreira do Roberto é fato dele." },
        { pergunta: "Por que reconhecer em voz alta o ponto forte do concorrente ('é verdade, a Sany entra mais barata') fortalece a sua posição?", opcoes: [
          "Porque mostra que você conhece a concorrência melhor do que o cliente e domina o mercado em que ele está comprando",
          "Porque o cliente já sabe disso e negar custaria sua credibilidade; a honestidade dá peso ao que você diz depois",
          "Porque as boas práticas do setor recomendam reconhecer o concorrente antes de qualquer comparação comercial",
          "Porque desarma o cliente e cria o clima para pedir um preço maior, já que a comparação passa a ser de valor",
        ], correta: 1, explicacao: "O cliente que está comparando conhece o ponto forte do outro. Se você o nega, tudo o que disser vira 'papo de vendedor'. Se o reconhece, o que vem depois (assistência, TCO) é ouvido como avaliação justa." },
        { pergunta: "Qual é a estrutura correta de um battlecard?", opcoes: [
          "Lista dos defeitos conhecidos do concorrente, com relatos de clientes, para usar na visita quando a comparação surgir",
          "Comparação marca contra marca em todos os modelos, com a posição de cada uma em consumo, preço e assistência",
          "Confronto por modelo equivalente, com o que eles fazem bem, 3 diferenças verificáveis, a prova, as 3 objeções geradas e o que não dizer",
          "Tabela de preços dos concorrentes atualizada mensalmente, com a diferença percentual para cada modelo da linha",
        ], correta: 2, explicacao: "Battlecard é ferramenta de comparação justa e preparada: por modelo (não por marca), honesta sobre o ponto forte deles, focada nas diferenças que importam para a aplicação, com prova e com as respostas prontas. Lista de defeitos vira depreciação; tabela de preço vira leilão." },
        { pergunta: "O vendedor fez piada com a marca chinesa que a locadora já tem na frota. Qual foi o erro de fundo?", opcoes: [
          "Falar de concorrente sem autorização da gerência, o que expõe a concessionária a reclamações da outra marca",
          "Usar humor numa visita comercial séria, o que passa falta de profissionalismo para um dono de locadora",
          "Não conhecer os dados técnicos da marca chinesa, o que tornou a piada uma opinião sem fundamento",
          "Depreciar a decisão de compra do cliente, que se sentiu chamado de burro e passou a defender a outra marca",
        ], correta: 3, explicacao: "A máquina na frota é uma decisão do dono. Atacar a máquina é atacar o dono. A reação (comprar mais duas e contar na associação) é a defesa da própria escolha. Humor e dados técnicos não são o ponto; respeito pela decisão dele é." },
        { pergunta: "O cliente pergunta 'e os 90 mil de diferença?'. Qual é a resposta com método?", opcoes: [
          "'Na sua pedreira, 90 mil são uns 4 meses da diferença de consumo e paradas que somamos; e pergunte a eles onde fica o técnico e quanto leva a peça'",
          "'A Sany desvaloriza muito na revenda; em cinco anos você perde esses 90 mil e mais um pouco na hora de trocar, é o que o mercado mostra'",
          "'Posso tentar chegar mais perto, deixa eu falar com o gerente hoje e te trago uma condição que diminua bastante essa diferença'",
          "'É o preço da qualidade e da tranquilidade; máquina boa custa mais, e quem já comprou barato sabe o que acontece depois'",
        ], correta: 0, explicacao: "Reenquadra a diferença de preço em meses de economia (com a conta já feita com ele) e devolve ao cliente duas perguntas verificáveis para fazer ao concorrente. 'Preço da qualidade' é frase vazia; falar de desvalorização sem fonte é boato; descontar é ceder sem valor." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m5a6", titulo: "Apresentar para grupo: sócios, diretoria e comissão da prefeitura", minutos: 14,
      resumo: "Na sala com três decisores, cada um veio com uma pergunta diferente. Apresentação de grupo tem estrutura de 15 minutos, material para cada papel, controle do tempo e um fechamento que pede a decisão — ou a próxima etapa com data.",
      blocos: [
        { tipo: "p", texto: "Quando o cliente diz 'vem apresentar pros sócios' ou 'a comissão quer ver', a venda muda de natureza: você não convence mais uma pessoa que já gostou de você; você equipa o seu campeão e neutraliza os céticos numa sala em que alguém sempre chega atrasado e alguém sempre olha o celular. Nancy Duarte estudou as apresentações que movem decisões e encontrou o padrão: alternar 'o que é' (a situação de hoje) com 'o que poderia ser' (o resultado), até o chamado à ação. Quinze minutos. Nunca 45." },
        { tipo: "framework", nome: "Apresentação de decisão em 15 minutos", origem: "Nancy Duarte — Resonate (o que é × o que poderia ser), adaptado a reuniões de compra de máquinas", passos: [
          "Minuto 0–2: quem está na sala e o que cada um quer saber (você perguntou antes ao campeão). 'Seu Marcos olha produção; seu irmão, a parcela; o contador, o FINAME. Vou passar pelos três.'",
          "Minuto 2–5: o que é hoje — a dor nas palavras do cliente e o custo da inação somado com ele (uma tela da Calculadora).",
          "Minuto 5–8: o que poderia ser — o resultado medido (demo), o cliente de referência, a foto da máquina na aplicação.",
          "Minuto 8–11: a solução e o investimento ao lado da economia; um slide/folha para cada papel (produção, parcela, financiamento).",
          "Minuto 11–13: riscos e como estão cobertos — prazo confirmado por escrito, garantia, assistência com nome, plano de treinamento do operador.",
          "Minuto 13–15: o pedido. 'O que falta para decidirmos hoje?' Se não for hoje: próxima etapa com data e responsável. Silêncio depois da pergunta.",
        ] },
        { tipo: "tabela", titulo: "Material por papel na sala", colunas: ["Quem", "Pergunta que trouxe", "Folha que recebe"], linhas: [
          ["Dono / secretário de obras", "Vai produzir? Vai resolver a parada?", "Número da demo, disponibilidade, referência"],
          ["Sócio 'pé no chão' / prefeito", "Cabe no caixa? E se der errado?", "Parcela × faturamento/dotação, garantia, revenda"],
          ["Contador / setor de compras", "Como paga? Está tudo documentado?", "FINAME/CDC com carência, memória de cálculo, documentação da licitação"],
          ["Engenheiro / gerente de frota", "Atende à especificação? Quem atende quando quebrar?", "Especificação × termo, técnico nomeado, peças em estoque"],
          ["Operador (se presente)", "É boa de operar?", "Voz na reunião: pergunte a opinião dele em público"],
        ] },
        { tipo: "dialogo", titulo: "Lidando com o cético na sala", falas: [
          { quem: "cliente", texto: "(sócio) Isso é tudo muito bonito, mas se a máquina der problema a gente fica com uma parcela de 12 mil e uma máquina parada." },
          { quem: "vendedor", texto: "É a pergunta certa, e é a que eu mais quero responder. Três coisas cobrem esse risco: garantia de fábrica de 12 meses ou 2.000 horas; o técnico Diego a 40 km, com peça de desgaste em estoque em Cachoeiro; e a cláusula de atendimento em até 24 horas que eu coloco por escrito. E se ainda assim quiser, a gente estrutura o FINAME com 6 meses de carência, pra máquina produzir antes de a parcela começar." },
          { quem: "nota", texto: "Validou a pergunta, respondeu com três coberturas concretas e ofereceu um mecanismo (carência) que reduz o medo. Não discutiu 'a máquina não dá problema'." },
          { quem: "cliente", texto: "(dono) Isso resolve, mano. Vamos?" },
          { quem: "vendedor", texto: "Então o que falta para decidirmos hoje?" },
        ] },
        { tipo: "caso", titulo: "Caso: a comissão da prefeitura e os 45 minutos", situacao: "Vendedor foi apresentar a RG140B para a comissão (secretário, engenheiro, pregoeiro, dois vereadores). Preparou 40 slides. Aos 20 minutos, dois vereadores saíram.", acao: "Na prefeitura seguinte, levou 6 folhas: uma por papel. Apresentou em 14 minutos, perguntou ao operador presente o que ele achou do teste e fechou com 'o que precisa constar no termo de referência para atender ao município?'.", resultado: "O engenheiro respondeu na hora, o secretário concordou, e o termo saiu em duas semanas com especificação que a RG140B atendia.", licao: "Reunião de grupo é uma reunião de 15 minutos com cinco conversas de 3 minutos dentro. Slide demais é falta de respeito com quem decide." },
        { tipo: "checklist", titulo: "Preparação da apresentação de grupo", itens: [
          "Lista de quem estará na sala, papel e pergunta de cada um (obtida com o campeão).",
          "Uma folha por papel, impressa; a tela só para a conta e a foto.",
          "Número da demo e nome da referência decorados; contato disponível.",
          "Riscos listados com a cobertura de cada um (prazo, garantia, assistência, treinamento).",
          "Pedido final ensaiado ('o que falta para decidirmos hoje?') e alternativa (próxima etapa com data).",
          "Cronômetro: 15 minutos, com 5 de folga para perguntas.",
        ] },
        { tipo: "erros", titulo: "Erros de apresentação", itens: [
          "Apresentar a empresa e a história da marca por 10 minutos. Ninguém veio para isso.",
          "Slide com ficha técnica completa. O engenheiro quer em anexo; o dono não quer.",
          "Responder ao cético com 'não vai dar problema'. Ele não acredita — e está certo.",
          "Não pedir a decisão. Terminar com 'dúvidas?' entrega a reunião ao acaso.",
          "Falar mais com o simpático da sala e ignorar o cético. O cético é quem decide não comprar.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Prepare a apresentação de 15 minutos de uma negociação real: roteiro por minuto, uma folha por papel, três riscos com cobertura e o pedido final. Apresente para um colega cronometrando; ele faz o papel do sócio cético. Refaça até caber em 15 minutos com a pergunta final no fim." },
      ],
      missao: "Na próxima reunião com mais de um decisor, use a estrutura de 15 minutos com uma folha por papel e termine com 'o que falta para decidirmos hoje?'. Registre no CRM quem estava na sala, a objeção do cético e o próximo passo com data.",
      quiz: [
        { pergunta: "O sócio cético diz: 'se a máquina der problema a gente fica com uma parcela de 12 mil e uma máquina parada'. Qual resposta funciona?", opcoes: [
          "'Por isso vale a pena pagar mais por uma marca de confiança: o risco de ficar parado é muito menor do que com a concorrente'",
          "Validar a pergunta e responder com coberturas concretas (garantia, técnico nomeado, atendimento por escrito) e um mecanismo (carência)",
          "'Fica tranquilo, essa máquina não dá problema; é a mais confiável da categoria e a fábrica tem os índices para provar'",
          "'Isso é muito raro; a grande maioria dos nossos clientes nunca teve problema, e quando teve a assistência resolveu rápido'",
        ], correta: 1, explicacao: "O cético não quer ouvir que o risco não existe; quer saber como está coberto. Coberturas nomeadas e um mecanismo financeiro (carência) respondem ao medo real. 'Não dá problema' e 'é raro' são promessas que ele já ouviu de outros vendedores." },
        { pergunta: "Qual é a duração e a estrutura recomendadas para uma apresentação de decisão com vários decisores?", opcoes: [
          "Cerca de 45 minutos, com a apresentação completa da empresa, do produto e das condições, para não faltar informação a ninguém",
          "Cerca de 30 minutos com foco técnico para o engenheiro, que é o mais exigente e cuja aprovação destrava os outros",
          "Em torno de 15 minutos, alternando 'o que é hoje' e 'o que poderia ser', com material por papel, riscos cobertos e o pedido no fim",
          "Cerca de 5 minutos, apenas com o preço e a condição, para respeitar o tempo dos decisores e evitar debate técnico",
        ], correta: 2, explicacao: "Duarte mostra que decisões se movem pela alternância entre situação atual e resultado possível, com chamado à ação. Quinze minutos respeitam a agenda de quem decide; 45 esvaziam a sala (caso da comissão); 5 minutos só com preço reduzem tudo a custo." },
        { pergunta: "Numa reunião com dono, sócio e contador, o vendedor entrega a mesma apresentação de 20 slides para todos. Qual é o problema?", opcoes: [
          "Cada papel veio com uma pergunta diferente (produção, parcela, financiamento) e uma apresentação única deixa dois dos três sem resposta",
          "Slides são inadequados para esse público; a apresentação deve ser só oral, com a folha da proposta como único material",
          "Vinte slides são poucos para cobrir todos os aspectos técnicos, financeiros e de assistência que três decisores vão questionar",
          "O contador não deveria participar da reunião de decisão, porque a presença dele desloca a conversa para o financiamento",
        ], correta: 0, explicacao: "A reunião de grupo é um conjunto de conversas curtas, uma por papel. Uma folha para cada um (produção para o dono, parcela × faturamento para o sócio, FINAME e memória para o contador) faz cada pessoa encontrar a própria resposta. O contador é o técnico da conta e precisa estar." },
        { pergunta: "Como a reunião de decisão com vários decisores deve terminar?", opcoes: [
          "Com 'alguma dúvida?' e a promessa de enviar a proposta por e-mail no mesmo dia, para os decisores analisarem com calma",
          "Com o pedido explícito ('o que falta para decidirmos hoje?'), silêncio, e, se não for hoje, a próxima etapa com data e responsável",
          "Com um resumo dos três diferenciais da máquina, para fixar a mensagem principal na memória de quem decide",
          "Com a entrega do material impresso e o agradecimento pelo tempo, deixando a decisão para o momento que eles escolherem",
        ], correta: 1, explicacao: "Reunião sem pedido é reunião entregue ao acaso. A pergunta calibrada revela o que ainda bloqueia; o silêncio faz alguém responder; a alternativa (próxima etapa com data) garante que a venda continua andando mesmo sem 'sim' hoje." },
        { pergunta: "O operador da prefeitura está na sala com a comissão. O que o vendedor faz?", opcoes: [
          "Evita envolvê-lo, porque a decisão é da comissão e uma opinião negativa em público poderia comprometer a reunião",
          "Entrega a ele a ficha técnica e o manual, para ele se sentir incluído sem tomar o tempo dos decisores formais",
          "Agradece a presença dele e segue com os decisores formais, tratando a opinião do operador em conversa separada",
          "Pede a opinião dele sobre o teste em público, porque ele é o usuário e influencia o prefeito e o secretário",
        ], correta: 3, explicacao: "O operador que testou a máquina é a prova viva na sala. Perguntar em público ('e o hidráulico, Jonas?') transforma o usuário em campeão diante dos decisores. Evitá-lo desperdiça a voz mais crível da reunião; e, se ele tiver algo negativo, é melhor ouvir agora do que depois." },
      ],
    },
  ],
  prova: [
    { pergunta: "Qual perfil de vendedor a pesquisa da CEB identificou como o mais frequente entre os de alto desempenho em vendas complexas?", opcoes: [
      "O Desafiador, que ensina, adapta a mensagem e assume o controle da conversa",
      "O Construtor de relacionamento, que prioriza a confiança pessoal e a proximidade",
      "O Trabalhador esforçado, que faz mais visitas e mais ligações que os demais",
      "O Solucionador reativo, que resolve tudo o que o cliente pede com rapidez",
    ], correta: 0, explicacao: "39% dos melhores eram Desafiadores; só 7% eram Relacionadores. Em vendas complexas, o insight e a condução valem mais que a simpatia. Relacionamento é base, não estratégia." },
    { pergunta: "Qual é o insight comercial mais poderoso para reenquadrar uma comparação de preço de máquinas?", opcoes: [
      "A marca é líder de mercado, tem a maior rede de concessionárias e a melhor revenda da categoria, o que reduz o risco",
      "A máquina nova consome menos combustível e para menos, o que reduz o custo operacional ao longo dos anos de uso",
      "A garantia é maior que a da concorrência e cobre os componentes que mais falham nas máquinas mais baratas do mercado",
      "O custo real está na unidade de produção do cliente (metro, tonelada), com parada, diesel e revenda; o preço é um terço",
    ], correta: 3, explicacao: "Insight muda o critério, não o produto. 'Custo por metro de vala' faz o cliente comparar o que importa para ele, com número. Liderança, consumo e garantia são argumentos que ele já ouviu de todos." },
    { pergunta: "Numa demonstração, quem deve segurar o cronômetro e a planilha?", opcoes: [
      "O vendedor, para garantir a precisão da medição e a consistência do método",
      "O demonstrador da concessionária, que conhece os ciclos da máquina",
      "O gerente ou encarregado do cliente, para que o número seja dele",
      "Um terceiro neutro contratado para a demo, para evitar contestação",
    ], correta: 2, explicacao: "O número medido pelo cliente é o número que ele defende para o sócio. Medido pelo vendedor, é 'número de vendedor'. A demo que vende é a que o cliente conduz com o método combinado antes." },
    { pergunta: "O que a demo precisa ter antes de a máquina chegar à obra?", opcoes: [
      "Autorização da fábrica para o transporte e a cobertura de seguro da máquina em operação no cliente",
      "Hipótese ligada ao critério do cliente, método com condições iguais e o operador dele confirmado",
      "Proposta comercial já apresentada, para a demo confirmar um número que o cliente já conhece",
      "Aprovação de crédito do cliente, para a demo não ser feita para quem não tem como comprar",
    ], correta: 1, explicacao: "Demo sem hipótese aceita e método combinado vira passeio: 'todo mundo gostou' e ninguém mediu. A pergunta 'o que precisa acontecer na demo pra você ter certeza?' define o critério do cliente e o compromisso de decidir com o resultado." },
    { pergunta: "No TCO de 5 anos, o que costuma pesar mais do que a diferença de preço de aquisição?", opcoes: [
      "O custo do seguro, que cresce com o valor da máquina",
      "O valor dos implementos, que muda conforme a aplicação",
      "O custo de transporte entre obras, que se repete a cada mobilização",
      "As horas paradas, o consumo e o valor de revenda",
    ], correta: 3, explicacao: "Na conta da aula, paradas, consumo e revenda somaram mais de R$ 700 mil de diferença em 5 anos, contra R$ 133 mil de preço. O preço é um terço da conta; a operação é dois terços." },
    { pergunta: "O cliente diz um número que parece errado (paradas muito baixas). Como o consultor procede na conta ao vivo?", opcoes: [
      "Corrige silenciosamente para a média de mercado, porque a conta precisa ser realista para convencer o sócio",
      "Usa o número dele, marca como estimativa e oferece revisar com o histórico de manutenção",
      "Insiste que o número real é maior, com exemplos de outros clientes, até ele concordar com uma média",
      "Pula a linha para não constranger o cliente e compensa com uma premissa mais conservadora em outra linha",
    ], correta: 1, explicacao: "A conta é dele. Trocar o número por conta própria destrói a credibilidade; discutir vira embate; pular esconde o maior custo. Marcar como estimativa e oferecer a revisão mantém a honestidade e o convida a checar." },
    { pergunta: "Qual é a estrutura de uma proposta de uma página que se defende sozinha?", opcoes: [
      "Necessidade (palavras do cliente), resultado com número, solução, evidência, investimento ao lado da economia e próximo passo datado",
      "Apresentação da empresa, ficha técnica completa, tabela de preço e condições de pagamento, nessa ordem, com anexos",
      "Preço, desconto aplicado, validade e espaço para assinatura, em uma página, para o cliente decidir sem distração",
      "Carta de apresentação, catálogo do modelo e proposta financeira em anexo, com a memória de cálculo do TCO",
    ], correta: 0, explicacao: "A proposta é lida por quem não estava na visita e precisa contar a história: por que essa máquina, por que agora, com que prova e com que retorno. Catálogo e tabela respondem 'quanto' e ignoram 'por quê'." },
    { pergunta: "Por que a proposta deve ter validade definida?", opcoes: [
      "Porque a fábrica exige validade em toda proposta formal, para controlar a tabela e as condições vigentes",
      "Porque protege o vendedor contra reajuste de tabela durante a análise do cliente e evita prejuízo na entrega",
      "Porque dá um motivo real para decidir dentro de um prazo, evitando que a proposta esfrie sem data",
      "Porque permite renegociar as condições depois do vencimento, com uma nova proposta e um novo prazo",
    ], correta: 2, explicacao: "Validade honesta (ligada a tabela, fila de produção ou condição de financiamento) é escassez verdadeira: cria um prazo para a decisão sem pressão artificial. Sem validade, 'depois' não custa nada." },
    { pergunta: "O cliente já tem três máquinas da marca concorrente na frota. Qual postura ao compará-las com a sua?", opcoes: [
      "Mostrar os defeitos conhecidos da marca dele, com relatos de outros clientes, para justificar a troca de fornecedor",
      "Evitar qualquer comparação para não ofender, e concentrar a conversa apenas nas qualidades da sua máquina",
      "Dizer, com tato, que ele fez um mau negócio e que a sua marca é superior, apresentando dados de mercado",
      "Respeitar a decisão dele, perguntar o que o faria trocar na próxima e comparar com fatos verificáveis na aplicação dele",
    ], correta: 3, explicacao: "As máquinas na frota são decisões do dono; atacá-las é atacá-lo (caso da piada que custou a locadora). A pergunta 'o que te faria trocar?' abre a comparação no terreno dele, com fatos e sem depreciação." },
    { pergunta: "O que um battlecard NÃO deve conter?", opcoes: [
      "Comparação marca contra marca, opiniões sobre qualidade sem prova e boatos sobre o concorrente",
      "O ponto forte do concorrente, porque reconhecê-lo enfraquece a sua posição na comparação",
      "As objeções que o concorrente gera, porque antecipá-las sugere que a sua máquina tem fragilidades",
      "A prova das diferenças (medição, referência), porque a prova deve ficar com o vendedor e não no material",
    ], correta: 0, explicacao: "Battlecard é por modelo equivalente, honesto sobre o que eles fazem bem, com diferenças verificáveis e prova. Opinião sem número e boato ('a assistência deles fechou') destroem a credibilidade se o cliente checar, e ele checa." },
    { pergunta: "Na apresentação para vários decisores, qual é o erro mais comum?", opcoes: [
      "Pedir a decisão no fim da reunião, porque decisores em grupo preferem deliberar sem o vendedor presente",
      "Apresentar 40 slides sobre a empresa e o produto, sem material por papel e sem pedido de decisão",
      "Perguntar a opinião do operador em público, porque expõe os decisores a um comentário que não controlam",
      "Entregar uma folha por papel, porque fragmenta a mensagem e cada decisor deixa de ver o conjunto",
    ], correta: 1, explicacao: "Reunião de grupo é um conjunto de conversas de três minutos, uma por papel, em 15 minutos, terminando com 'o que falta para decidirmos hoje?'. Slide demais esvazia a sala e falta de pedido entrega a reunião ao acaso." },
    { pergunta: "O sócio cético pergunta 'e se der errado?'. O que o consultor precisa ter preparado?", opcoes: [
      "A estatística de falhas da concorrência, para mostrar que o risco de ficar parado é maior com a outra marca",
      "A afirmação firme de que a máquina não dá problema, com os índices de confiabilidade publicados pela fábrica",
      "Uma lista de coberturas concretas: garantia, técnico nomeado, atendimento por escrito, treinamento e carência",
      "Um desconto de emergência para compensar o risco percebido e destravar a decisão do sócio ainda na reunião",
    ], correta: 2, explicacao: "O cético decide não comprar; ele precisa ver o risco coberto, não negado. Coberturas nomeadas e um mecanismo financeiro respondem ao medo real. Desconto não cobre risco; estatística da concorrência é depreciação." },
    { pergunta: "Como o vendedor deve entregar a proposta?", opcoes: [
      "Por WhatsApp, para o cliente ler com calma e encaminhar ao sócio no momento que achar melhor",
      "Por e-mail com confirmação de leitura, para ter o registro formal de que a proposta foi recebida",
      "Pessoalmente (ou por vídeo), em 5 minutos, terminando com 'o que está faltando que o seu sócio vai perguntar?'",
      "Pelo setor administrativo da concessionária, com protocolo, para separar a proposta formal da relação comercial",
    ], correta: 2, explicacao: "A entrega curta e presencial garante que a proposta seja lida com a história e antecipa a objeção do ratificador. Enviada solta, ela chega ao contador como 'muito caro' e ninguém explica o que está sendo comprado." },
    { pergunta: "O que a conta ao vivo, na Calculadora do CRM, produz que uma planilha enviada depois não produz?", opcoes: [
      "Números do cliente, soma vista acontecer e conclusão descoberta em conjunto, que ele repete para o sócio",
      "Fórmulas mais precisas e atualizadas, com as taxas de financiamento e os preços de diesel do dia",
      "Um documento formal que serve de base para o financiamento e para a análise do banco",
      "Uma cópia automática para o gerente da concessionária, que acompanha a negociação em tempo real",
    ], correta: 0, explicacao: "A conta ao vivo é um momento, não um documento: credibilidade, compreensão e propriedade. O print enviado depois é a memória do momento, e é o que o cliente encaminha ao sócio com a frase 'os números que eu passei'." },
  ],
};
