import type { Modulo } from "./tipos";

export const M6: Modulo = {
  id: "m6", nivel: 6, titulo: "Negociação", tema: "Margem", cor: "#22d3ee",
  descricao: "Negociar não é dar desconto devagar. É preparar BATNA e ZOPA, ancorar com critério, trocar concessões por contrapartidas, usar a usada e o financiamento como alavancas em vez de sangrar o preço, negociar com compras e com a prefeitura sem perder a margem e reconhecer táticas duras sem cair nelas — nem usá-las.",
  objetivos: [
    "Preparar cada negociação com BATNA, ZOPA, âncora e a lista de variáveis além do preço.",
    "Ancorar com critério objetivo e responder à âncora do cliente sem ceder no primeiro pedido.",
    "Conceder só com contrapartida: 'se… então…', em ordem de custo crescente para você.",
    "Negociar o preço protegendo a margem: reenquadre, troca de variáveis e o desconto como último recurso e pequeno.",
    "Usar a avaliação da usada, o prazo, a carência e a estrutura do financiamento como alavancas de fechamento.",
    "Negociar com setor de compras, licitação e prefeitura conhecendo as regras do jogo (menor preço, especificação, empenho).",
    "Reconhecer táticas duras (bom/mau, prazo falso, 'o outro cobriu') e responder com calma e método.",
  ],
  leituras: [
    "Roger Fisher e William Ury — Como Chegar ao Sim: interesses, critérios objetivos e BATNA.",
    "Chris Voss — Negocie como se sua vida dependesse disso: âncora, 'como é que eu faço isso?', o 'não' e a regra do 65-85-95-100.",
    "G. Richard Shell — Bargaining for Advantage: estilos de negociação e preparação.",
    "Lei 14.133/2021 (nova Lei de Licitações) — leia os artigos sobre modalidades, critérios de julgamento e termo de referência.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m6a1", titulo: "Preparação: BATNA, ZOPA, âncora e variáveis", minutos: 15,
      resumo: "Quem chega à mesa sem saber a própria alternativa, a faixa possível de acordo e a lista do que pode trocar negocia no escuro e cede no preço. Trinta minutos de preparação valem mais que qualquer frase de efeito.",
      blocos: [
        { tipo: "p", texto: "Fisher e Ury, no projeto de negociação de Harvard, definiram o conceito que mais protege margem: BATNA, a melhor alternativa caso não haja acordo. Quem tem alternativa negocia com calma; quem não tem, implora. A sua BATNA numa negociação de E215C é o que você faz com o seu tempo e a máquina se este cliente não fechar: outra negociação madura, a fila de produção, o estoque. A BATNA do cliente é o que ele faz sem a sua máquina: comprar do concorrente (com o custo de assistência dele), ficar com a velha (com o custo da inação que você somou), alugar. Conhecer as duas BATNAs é saber quem precisa mais do acordo — e isso raramente é quem parece." },
        { tipo: "framework", nome: "Ficha de preparação (30 minutos antes de qualquer negociação)", origem: "Fisher & Ury (Como Chegar ao Sim) + prática de negociação B2B", passos: [
          "Minha BATNA: o que faço se não fechar? (outras negociações no funil, fila da fábrica, meta do mês). Quanto mais forte, menos eu cedo.",
          "BATNA dele: o que ele faz sem mim? Custo real da alternativa (concorrente + assistência longe; máquina velha + custo da inação; aluguel × 18 meses).",
          "ZOPA: faixa entre o meu mínimo aceitável (preço piso + margem mínima) e o máximo que ele pagaria (o valor que a conta do gap justifica). Se não há sobreposição, não há negociação: volte ao diagnóstico.",
          "Âncora: minha primeira oferta, com critério que a justifica (tabela, TCO, referência de mercado). Ambiciosa e defensável.",
          "Variáveis além do preço (mínimo 8): prazo de entrega, avaliação da usada, implementos, garantia estendida, treinamento, revisões, carência, entrada, frete, peças de desgaste, pagamento do sinal, data de faturamento.",
          "Ordem de concessão: do que custa menos para mim e vale mais para ele (treinamento, revisão, frete) até o que custa mais (preço). Preço é o último.",
        ] },
        { tipo: "tabela", titulo: "Variáveis de negociação: custo para você × valor para o cliente", colunas: ["Variável", "Custo para você", "Valor percebido pelo cliente", "Quando usar"], linhas: [
          ["Treinamento do operador (2 dias)", "Baixo", "Alto (segurança, produção)", "Primeira concessão"],
          ["Primeira revisão inclusa", "Baixo", "Médio-alto", "Segunda concessão"],
          ["Frete / entrega na obra", "Baixo-médio", "Médio", "Junto com prazo"],
          ["Prazo de entrega prioritário", "Depende da fila", "Alto quando há obra", "Em troca de decisão rápida"],
          ["Avaliação da usada (+R$ 5–15 mil)", "Médio (risco de revenda)", "Alto (sente como desconto)", "Em troca de fechamento e documentação rápida"],
          ["Kit de peças de desgaste", "Baixo-médio", "Alto (medo de parar)", "Para perfil S e cético"],
          ["Carência / estrutura do FINAME", "Zero (é do banco)", "Alto (caixa)", "Sempre que 'não cabe na parcela'"],
          ["Desconto no preço", "Alto (margem direta)", "Alto, mas esquecido em uma semana", "Último recurso, pequeno, com contrapartida"],
        ] },
        { tipo: "dialogo", titulo: "A BATNA do cliente é mais fraca do que parece", falas: [
          { quem: "cliente", texto: "Se você não chegar em 820, eu fecho com a Komatsu amanhã." },
          { quem: "vendedor", texto: "Entendo. Deixa eu te perguntar uma coisa antes: a proposta deles inclui a entrega em 20 dias que a sua obra precisa?" },
          { quem: "cliente", texto: "Eles falaram 45." },
          { quem: "vendedor", texto: "E o técnico deles mais perto continua em Vitória?" },
          { quem: "cliente", texto: "É, mas eles dizem que atendem em 48 horas." },
          { quem: "nota", texto: "O vendedor conhece a BATNA do cliente (Komatsu a 45 dias, assistência a 140 km) e a testa com perguntas, sem discutir o preço. O 'fecho amanhã' perde força na frente dos dois." },
          { quem: "vendedor", texto: "Então a diferença entre a gente é: 25 dias de obra e um técnico a 40 km contra 140. Você me disse que a medição atrasada custa R$ 6 mil. Vamos olhar o número inteiro, não só o preço? Eu consigo trabalhar a usada e a carência; o preço eu vou te explicar por que fica onde está." },
        ] },
        { tipo: "caso", titulo: "Caso: a negociação sem ficha", situacao: "Vendedor entrou na negociação de uma W130B sem saber as outras propostas, sem lista de variáveis e com a meta do mês apertada (BATNA fraca e visível).", acao: "O cliente pediu 8% e o vendedor cedeu 5% na primeira rodada, sem pedir nada. O cliente pediu mais 3% 'para fechar' e ganhou 2%. Total: 7% de desconto, e o cliente ainda pediu a primeira revisão de graça — e levou.", resultado: "Margem da venda caiu para menos da metade. Na negociação seguinte, com ficha preparada, o mesmo vendedor fechou uma W130B com 1,5% de desconto, treinamento e revisão inclusos (custo baixo) e usada bem avaliada. O cliente ficou mais satisfeito que o primeiro.", licao: "Sem preparação você negocia só uma variável (preço) e a única direção é para baixo. Com oito variáveis, você troca — e o cliente sente que ganhou mais." },
        { tipo: "checklist", titulo: "Antes de sentar para negociar", itens: [
          "Sei a minha BATNA e ela está no papel (não na ansiedade da meta)?",
          "Sei a BATNA dele com custo real (prazo, assistência, custo da inação)?",
          "Tenho o preço piso e a margem mínima aprovados com o gerente?",
          "Tenho a âncora com critério que a justifica?",
          "Tenho a lista de 8 variáveis com custo para mim e valor para ele, em ordem de concessão?",
          "Sei quem decide do lado dele e se essa pessoa estará na mesa?",
        ] },
        { tipo: "erros", titulo: "Erros de preparação", itens: [
          "Deixar a meta do mês virar BATNA: o cliente sente a pressa e usa contra você.",
          "Aceitar a BATNA do cliente como ele apresenta ('fecho amanhã com a Komatsu'). Teste com perguntas: prazo, assistência, condição.",
          "Ter só o preço como variável. Uma variável = desconto; oito variáveis = negociação.",
          "Não combinar o piso com o gerente antes. Negociar 'vou ver com o gerente' toda hora enfraquece você e ancora o cliente em mais uma rodada.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Preencha a ficha de preparação para a maior negociação aberta do seu funil: BATNA sua e dele (com custo), ZOPA, âncora com critério e as 8 variáveis em ordem. Se não conseguir preencher a BATNA dele, é sinal de que o diagnóstico ficou raso — volte ao MEDDICC." },
      ],
      missao: "Prepare a ficha completa (BATNA, ZOPA, âncora, 8 variáveis em ordem) para as duas próximas negociações e registre-a nas observações da negociação no CRM antes da reunião. Depois, anote o que foi concedido e o que foi obtido em troca.",
      quiz: [
        { pergunta: "O cliente diz 'se você não chegar em 820, fecho com a Komatsu amanhã'. Qual é a primeira ação do consultor preparado?", opcoes: [
          "Responder que a Komatsu não tem assistência na região e que ele vai se arrepender quando a máquina parar na primeira obra",
          "Testar a BATNA dele com perguntas sobre prazo de entrega, assistência e condição, antes de falar em preço",
          "Ligar para o gerente na frente do cliente e pedir autorização para chegar em 820, mostrando esforço para fechar",
          "Aceitar os 820 com contrapartida de fechamento hoje, porque perder a venda para a Komatsu custa mais do que a margem",
        ], correta: 1, explicacao: "A alternativa do cliente raramente é tão boa quanto ele apresenta: 45 dias de entrega e técnico a 140 km mudam a conta. Testar a BATNA com perguntas calibradas revela isso sem confronto. Ceder ou ligar para o gerente ancora o cliente em mais uma rodada; depreciar a Komatsu ativa a defesa." },
        { pergunta: "O que é a ZOPA e o que fazer se ela não existir?", opcoes: [
          "É a diferença entre a sua proposta e a do concorrente; se não existir, o caminho é igualar a condição dele",
          "É o prazo em que o acordo precisa ser fechado; se não existir, o vendedor cria urgência com a fila da fábrica",
          "É o desconto máximo autorizado pelo gerente; se não existir margem, é preciso pedir uma exceção antes da reunião",
          "É a faixa entre o seu mínimo aceitável e o máximo que o cliente pagaria; sem sobreposição, não há negociação e é preciso voltar ao valor",
    ], correta: 3, explicacao: "Sem sobreposição entre o que você pode aceitar e o que ele está disposto a pagar, nenhuma técnica resolve: o problema é de valor percebido (gap mal quantificado, decisor errado), não de preço. Negociar nesse caso é sangrar margem à toa." },
        { pergunta: "Qual variável tem custo baixo para o vendedor e valor alto para o cliente, sendo a candidata natural à primeira concessão?", opcoes: [
          "Desconto de 3% no preço, dado logo no início",
          "Avaliação da usada 15 mil acima do mercado",
          "Prazo de entrega prioritário, pulando a fila",
          "Treinamento de dois dias do operador na obra",
        ], correta: 3, explicacao: "Treinamento custa pouco (tempo do técnico) e vale muito para quem tem medo de máquina parada e operador inexperiente. Desconto custa margem direta; usada acima do mercado é risco de revenda; pular fila depende da fábrica. A ordem de concessão vai do barato-para-você ao caro." },
        { pergunta: "Um vendedor cedeu 5% na primeira rodada sem pedir contrapartida, depois mais 2% e a revisão grátis. Qual foi o erro de fundo?", opcoes: [
          "Ter cedido a revisão gratuita, que custa mais à concessionária do que os dois pontos de desconto somados",
          "Não ter chamado o gerente para a negociação, que teria segurado a segunda rodada com a autoridade do cargo",
          "Entrar sem ficha: sem BATNA, sem variáveis e com a meta do mês visível, a única variável era o preço e a única direção era para baixo",
          "Ter negociado com o cliente errado, que não era o decisor final e usou o desconto obtido como âncora para o sócio",
        ], correta: 2, explicacao: "Quem tem uma variável só desconta; quem tem oito troca. Sem preparação, cada pedido do cliente vira uma nova rodada de desconto, e a pressa da meta faz o vendedor ceder rápido. A revisão em si é uma boa concessão, quando trocada por algo." },
        { pergunta: "Por que a meta do mês não pode funcionar como BATNA na cabeça do vendedor?", opcoes: [
          "Porque a pressa da meta é percebida pelo cliente e usada contra você; a BATNA real são as outras negociações maduras e a fila da fábrica",
          "Porque a meta é informação confidencial da concessionária e não pode influenciar a condição oferecida a nenhum cliente",
          "Porque a meta se mede por trimestre e não por mês, e a pressão do fim do mês distorce a leitura do funil",
          "Porque a BATNA deve ser definida pelo gerente antes da negociação, com o piso aprovado, e não pelo vendedor sozinho",
        ], correta: 0, explicacao: "BATNA é a alternativa concreta ao acordo. 'Preciso fechar este mês' não é alternativa, é ansiedade, e ansiedade transparece na voz e nas concessões rápidas. Quem tem outras negociações maduras no funil negocia com calma, e a calma protege a margem." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m6a2", titulo: "Ancoragem e concessões condicionadas", minutos: 14,
      resumo: "O primeiro número na mesa puxa toda a negociação. Ancore com critério, nunca responda à âncora do cliente com um contra-número imediato, e toda concessão vem com 'se… então…'. Quem cede sem pedir ensina o cliente a pedir mais.",
      blocos: [
        { tipo: "p", texto: "Kahneman e Tversky mostraram que qualquer número apresentado primeiro vira referência, mesmo quando é arbitrário. Na negociação, isso significa: quem ancora primeiro, com um número ambicioso e justificado, define o terreno. O amador tem medo de ancorar alto ('vai assustar') e apresenta o preço já com desconto embutido, e aí o cliente pede desconto sobre o desconto. O consultor ancora na tabela ou no TCO, explica o critério, e quando o cliente ancora baixo ('820'), não responde com um número: responde com uma pergunta ou com um rótulo e devolve ao critério." },
        { tipo: "framework", nome: "Regras de concessão", origem: "Prática de negociação (Shell, Voss) e teoria da ancoragem (Tversky & Kahneman)", passos: [
          "Ancore primeiro e alto, com critério: 'O valor é R$ 890 mil, que é a tabela com a configuração que a sua aplicação exige. Isso corresponde a R$ 210 por hora em 5 anos, contra R$ 284 da alternativa.'",
          "Nunca conceda no primeiro pedido. 'Entendo o pedido. Antes de falar de valor, o que mais além do preço faria a proposta funcionar pra você?' Descubra os interesses.",
          "Toda concessão é condicionada: 'Se você fechar até sexta com a documentação do FINAME, então eu incluo o treinamento e a primeira revisão.' Nunca 'eu incluo o treinamento' e ponto.",
          "Concessões decrescentes: a primeira é a maior; as seguintes, cada vez menores. 3%, depois 1%, depois 0,5%. Isso sinaliza que o limite está perto. Concessões iguais ou crescentes ensinam a pedir mais.",
          "Devagar. Concessão rápida é lida como 'tinha mais'. Peça tempo, consulte, volte com contrapartida.",
          "Feche a rodada: 'Então ficou assim: X, Y e Z. Tem mais alguma coisa? Porque depois disso eu não tenho mais pra onde ir.' — e cumpra.",
        ] },
        { tipo: "dialogo", titulo: "Respondendo à âncora baixa sem contra-número", falas: [
          { quem: "cliente", texto: "Eu pago 800 e fechamos hoje." },
          { quem: "vendedor", texto: "Oitocentos?" },
          { quem: "nota", texto: "Espelhamento. Sem contra-oferta, sem 'impossível'. Silêncio." },
          { quem: "cliente", texto: "É. O outro me passou 810, então 800 pra você é justo." },
          { quem: "vendedor", texto: "Parece que o que você quer é ter certeza de que está fazendo o melhor negócio, não só o menor número. Faz sentido. Deixa eu te mostrar de onde vem o 890: é a configuração com caçamba de rocha e cabine climatizada que você pediu. Com a caçamba padrão, o número é outro — mas não é o que a sua pedreira precisa. Como é que eu faço para chegar em 800 sem tirar o que você precisa?" },
          { quem: "nota", texto: "Rótulo + critério + pergunta calibrada de Voss ('como é que eu faço isso?'). O cliente agora tem que resolver o problema junto — e costuma revelar o que realmente quer (parcela, prazo, usada)." },
          { quem: "cliente", texto: "Se a parcela ficasse abaixo de 12 e a minha usada entrasse bem, eu não precisava dos 800." },
          { quem: "vendedor", texto: "Então vamos trabalhar a usada e a carência. Se eu conseguir parcela abaixo de 12 com a sua usada e a documentação sair essa semana, a gente fecha em 890?" },
        ] },
        { tipo: "tabela", titulo: "Sequência de concessões: o que sinaliza cada padrão", colunas: ["Padrão", "O que o cliente lê", "Resultado"], linhas: [
          ["5% → 5% → 5%", "'Sempre tem mais'", "Ele pede até você dizer não; margem destruída"],
          ["1% → 3% → 5%", "'Quanto mais eu aperto, mais sai'", "Pior de todos: incentiva pressão"],
          ["3% → 1% → 0,5%", "'Está chegando no limite'", "Ele para de pedir; percebe que ganhou o máximo"],
          ["0% com troca de variáveis", "'Ele não mexe no preço, mas resolve o que eu preciso'", "Margem intacta; cliente satisfeito com valor"],
        ] },
        { tipo: "caso", titulo: "Caso: os R$ 30 mil que ninguém pediu", situacao: "Vendedor apresentou uma E145C já com 4% de desconto 'para não perder tempo'. O cliente, que não tinha pedido nada, ancorou 6% abaixo do já descontado.", acao: "Na negociação seguinte, o mesmo vendedor ancorou na tabela com o critério do TCO e só concedeu com contrapartida (documentação rápida, fechamento até sexta, indicação de um vizinho).", resultado: "Na primeira, 9% de desconto total. Na segunda, 2% mais treinamento incluso, e o cliente indicou o vizinho na mesma semana. Diferença de margem: R$ 30 mil numa máquina.", licao: "Desconto que você dá antes de pedirem não é gentileza; é âncora nova para o cliente pedir mais. Ancore no valor, conceda com troca." },
        { tipo: "script", titulo: "Frases de concessão condicionada", itens: [
          "'Se você fechar até sexta com a documentação, então eu incluo o treinamento e a primeira revisão.'",
          "'Se a sua usada entrar na troca e a gente faturar este mês, então eu consigo trabalhar a avaliação dela.'",
          "'Se você me apresentar para o seu vizinho da pedreira, então eu incluo o kit de peças de desgaste.'",
          "'Posso olhar o prazo de entrega, mas preciso da decisão hoje pra segurar a máquina da fila.'",
          "'Esse é o meu limite. Se houver mais alguma coisa que eu possa fazer que não seja preço, me diz.'",
        ] },
        { tipo: "erros", titulo: "Erros de ancoragem e concessão", itens: [
          "Apresentar preço já com desconto 'para agilizar': você ancora baixo e ainda recebe pedido de desconto.",
          "Responder à âncora do cliente com um contra-número imediato: a negociação vira 'dividir a diferença'.",
          "Conceder sem pedir nada: ensina que pedir funciona.",
          "Concessões crescentes: quanto mais ele aperta, mais sai — e ele aprende.",
          "Dizer 'é o meu limite' e ceder depois: você nunca mais será acreditado por esse cliente.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Reveja as três últimas negociações fechadas no CRM: qual foi a sua âncora, quantas concessões você fez, em que ordem e o que obteve em troca de cada uma. Reescreva cada concessão no formato 'se… então…' e calcule quanto de margem teria sobrado." },
      ],
      missao: "Na próxima negociação, ancore na tabela com o critério (TCO ou configuração), não responda à âncora do cliente com número e faça toda concessão com 'se… então…', em ordem decrescente. Registre no CRM a sequência de concessões e as contrapartidas obtidas.",
      quiz: [
        { pergunta: "O cliente ancora: 'pago 800 e fechamos hoje' (sua âncora foi 890). Qual é a melhor resposta imediata?", opcoes: [
          "'Impossível; abaixo de 870 eu não fecho, e esse número já está com tudo o que eu consigo fazer por você'",
          "'Oitocentos?', espelhamento e silêncio, depois rótulo, critério do valor e a pergunta 'como é que eu faço isso sem tirar o que você precisa?'",
          "'Deixa eu ligar para o gerente e ver o que ele consegue; se ele autorizar alguma coisa perto disso, a gente fecha hoje'",
          "'Consigo 850, e é o meu limite; abaixo disso eu prefiro não vender, porque a máquina não entrega o que você precisa'",
        ], correta: 1, explicacao: "Contra-número imediato transforma a negociação em 'dividir a diferença' a partir de uma âncora baixa. Espelhar, rotular e devolver ao critério faz o cliente explicar o que realmente quer (parcela, usada) e abre a troca de variáveis. Ligar para o gerente sinaliza que há mais." },
        { pergunta: "Por que apresentar o preço já com 4% de desconto 'para agilizar' costuma custar mais margem no fim?", opcoes: [
          "Porque o desconto embutido vira a nova âncora e o cliente pede desconto sobre ele, como se nada tivesse sido dado",
          "Porque a fábrica não autoriza desconto sem justificativa registrada, e a concessionária arca com a diferença na margem",
          "Porque o cliente desconfia de preço apresentado já abaixo da tabela e passa a checar tudo o que vem depois",
          "Porque o gerente precisa aprovar cada desconto e a apresentação antecipada compromete a negociação da concessionária",
        ], correta: 0, explicacao: "Concessão não pedida não é lida como gentileza; é lida como ponto de partida. No caso da aula, 4% viraram 9%. Ancore no valor com critério e guarde as concessões para trocar por algo." },
        { pergunta: "Qual padrão de concessões sinaliza ao cliente que o limite está próximo e faz ele parar de pedir?", opcoes: [
          "Concessões iguais e regulares (3%, 3%, 3%), que mostram consistência e previsibilidade ao cliente",
          "Concessões crescentes (1%, 3%, 5%), que demonstram boa vontade progressiva e evitam a ruptura",
          "Uma única concessão grande no início, que resolve a negociação de uma vez e evita rodadas desgastantes",
          "Concessões decrescentes (3%, 1%, 0,5%), cada uma com contrapartida e mais lentas que a anterior",
        ], correta: 3, explicacao: "O tamanho decrescente comunica 'estou chegando no fim' sem precisar dizer. Iguais dizem 'sempre tem mais'; crescentes recompensam a pressão; uma grande no início ancora baixo e ainda deixa o cliente pedindo." },
        { pergunta: "O que caracteriza uma concessão condicionada?", opcoes: [
          "Uma concessão dada apenas ao decisor final, depois de confirmar que ele tem poder para fechar na hora",
          "Uma concessão que depende de aprovação do gerente e é apresentada como exceção obtida com esforço",
          "Uma concessão feita com 'se… então…', trocada por algo concreto (fechar até sexta, documentação, usada, indicação)",
          "Uma concessão válida só até o fim do mês, que cria um prazo real para a decisão do cliente",
        ], correta: 2, explicacao: "Concessão condicionada obtém algo em troca e comunica que nada é de graça. 'Se você fechar até sexta com a documentação, então incluo o treinamento' é negociação; 'incluo o treinamento' é doação, e doação ensina a pedir mais." },
        { pergunta: "Você disse 'esse é o meu limite' e, sob pressão, cedeu mais 1%. Qual é a consequência mais grave?", opcoes: [
          "O cliente vai contar aos vizinhos que conseguiu mais depois do 'limite', e a região inteira passa a pedir o mesmo",
          "Sua palavra perde valor com esse cliente para sempre: todo 'limite' futuro será testado, nesta e nas próximas compras",
          "A margem da venda cai 1%, o que em uma máquina de R$ 890 mil representa quase R$ 9 mil de resultado perdido",
          "O gerente questiona a autorização da concessão extra e o vendedor perde autonomia nas negociações seguintes",
        ], correta: 1, explicacao: "O 1% é o menor dos custos. O dano é à credibilidade: 'limite' vira 'ponto de partida' na cabeça do cliente, e ele comprará outras máquinas ao longo dos anos. Diga 'limite' só quando for, e sustente." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m6a3", titulo: "Negociando preço: proteger a margem sem perder a venda", minutos: 14,
      resumo: "Quando o cliente pede desconto, ele quase nunca está pedindo desconto: está pedindo certeza de que fez um bom negócio. Reenquadre, isole, troque variáveis e, se ainda assim precisar mexer no preço, que seja pequeno, lento e trocado.",
      blocos: [
        { tipo: "p", texto: "Um por cento de desconto numa máquina de R$ 890 mil é R$ 8.900. Em dez máquinas por ano, um ponto percentual a menos de desconto é quase R$ 90 mil de margem — que é o que separa o vendedor mediano do que a concessionária não quer perder. A pressão por preço é constante e a resposta não pode ser reflexo. Ela tem sequência: primeiro entender o que está por trás do pedido; depois reenquadrar no valor; depois isolar ('se o preço fosse resolvido, fecharíamos?'); depois trocar variáveis; e só por último, se a ZOPA exigir, mexer no preço — pequeno, devagar e com contrapartida." },
        { tipo: "framework", nome: "Sequência de resposta ao pedido de desconto (5 degraus)", origem: "Prática de venda baseada em valor e negociação (Shell, Voss), adaptada ao mercado de máquinas", passos: [
          "Degrau 1 — Entender: 'Entendo. O que está por trás do pedido: cabe no caixa, comparação com outra proposta ou é o jeito de ter certeza de que está fazendo um bom negócio?' A maioria responde a terceira.",
          "Degrau 2 — Reenquadrar: volte à conta feita com ele. 'Os 3% que você pede são R$ 27 mil; a diferença de consumo e parada que a gente somou é R$ 8.800 por mês. Em três meses a máquina já devolveu isso.'",
          "Degrau 3 — Isolar: 'Se a gente resolver a questão do valor, tem mais alguma coisa que impede de fechar?' Se sim, resolva o outro primeiro; desconto não resolve objeção de assistência.",
          "Degrau 4 — Trocar variáveis: 'Não mexo no preço, mas resolvo o que você precisa': usada, carência, treinamento, revisão, prazo, peças.",
          "Degrau 5 — Preço, se necessário: pequeno (0,5–1,5%), lento, com contrapartida (fechamento hoje, documentação, indicação) e apresentado como exceção com motivo.",
        ] },
        { tipo: "conta", titulo: "O que 1% de desconto custa e o que ele compra", linhas: [
          ["Máquina", "R$ 890.000"],
          ["1% de desconto", "R$ 8.900"],
          ["10 máquinas/ano × 1%", "R$ 89.000 de margem por ano"],
          ["Custo para você de 2 dias de treinamento do operador", "≈ R$ 1.500"],
          ["Custo de 1ª revisão inclusa", "≈ R$ 2.500"],
          ["Custo de kit de peças de desgaste", "≈ R$ 3.000"],
          ["As três concessões acima somadas", "≈ R$ 7.000 (menos que 1% de desconto) e valor percebido maior"],
        ], conclusao: "Treinamento, revisão e kit de peças custam menos que 1% de desconto e o cliente lembra deles por meses. O desconto ele esquece na semana seguinte e usa como âncora na próxima compra." },
        { tipo: "dialogo", titulo: "Isolando a objeção de preço", falas: [
          { quem: "cliente", texto: "Preciso de 5% pra fechar." },
          { quem: "vendedor", texto: "Cinco por cento é um pedido grande. Me ajuda: é porque a parcela não cabe, porque tem outra proposta na mesa, ou é o jeito de ter certeza de que está fazendo o melhor negócio?" },
          { quem: "cliente", texto: "Um pouco de cada. Mas principalmente eu não quero pagar mais do que o vizinho pagou." },
          { quem: "nota", texto: "A objeção real: medo de pagar mais que o vizinho. Não é caixa. Desconto de 5% não resolveria isso; informação resolve." },
          { quem: "vendedor", texto: "Faz todo sentido. O seu vizinho comprou em março, com a tabela de março e sem a caçamba de rocha. Eu te mostro o comparativo das duas configurações e você vê que está pagando o mesmo pela mesma coisa. Se isso ficar claro, tem mais alguma coisa que impede de fechar?" },
          { quem: "cliente", texto: "Não. Aí só a parcela mesmo." },
          { quem: "vendedor", texto: "Parcela a gente resolve com a usada e 6 meses de carência, sem mexer no preço. Vamos montar?" },
        ] },
        { tipo: "caso", titulo: "Caso: o desconto que não resolveu nada", situacao: "Cliente pediu 4% numa B110B. O vendedor deu 3% na hora. O cliente agradeceu e não fechou: duas semanas depois, comprou uma usada de outra marca.", acao: "No win/loss, o vendedor descobriu que a objeção real era o medo de a máquina nova não ter serviço suficiente para pagar a parcela: gap apertado. O desconto de 3% não mudava isso; uma usada de R$ 300 mil mudava.", resultado: "Perdeu a venda e 3% de margem que nem foi usada. Na negociação seguinte parecida, ofereceu uma B95C seminova certificada como alternativa e fechou.", licao: "Desconto só resolve objeção de preço — e a maioria dos pedidos de desconto não é objeção de preço. Degrau 1 antes de tudo." },
        { tipo: "tabela", titulo: "Por trás do pedido de desconto", colunas: ["O que o cliente diz", "O que costuma estar por trás", "O que resolve"], linhas: [
          ["'Tá caro'", "Não viu o valor; conta não foi feita com ele", "Reenquadre com a conta do gap"],
          ["'Preciso de 5%'", "Ritual: quer sentir que negociou bem", "Concessão pequena com contrapartida; variáveis de valor"],
          ["'A parcela não cabe'", "Caixa; problema real de estrutura", "Carência, prazo, usada, entrada menor; não desconto"],
          ["'O outro me deu X'", "Comparação; às vezes blefe", "Teste a BATNA; compare configuração; TCO"],
          ["'Não quero pagar mais que o vizinho'", "Medo de ser feito de bobo", "Informação: tabela, configuração, transparência"],
          ["'Meu sócio só fecha com desconto'", "Sócio ausente precisa de troféu", "Concessão de valor visível (treinamento, revisão) para ele mostrar"],
        ] },
        { tipo: "erros", titulo: "Erros com preço", itens: [
          "Responder 'quanto você precisa?' — convida a âncora baixa.",
          "Dar desconto para 'compensar' um problema de assistência ou prazo. Resolva o problema; o desconto não o resolve e ainda custa.",
          "Descontar rápido. Rápido = tinha mais.",
          "Descontar sem motivo declarado. Todo desconto tem que ter um 'porque' (fechamento hoje, documentação, volume, indicação) — senão vira regra.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Calcule: quantas máquinas você vendeu nos últimos 12 meses e qual foi o desconto médio. Multiplique. Esse número é a sua margem perdida. Depois, para cada venda, escreva qual variável de valor (treinamento, revisão, carência, usada) poderia ter substituído o desconto." },
      ],
      missao: "No próximo pedido de desconto, suba os cinco degraus antes de mexer no preço: entender, reenquadrar, isolar, trocar variáveis, e só então (se a ZOPA exigir) preço pequeno com contrapartida. Registre no CRM o que estava por trás do pedido e como foi resolvido.",
      quiz: [
        { pergunta: "O cliente diz 'preciso de 5% pra fechar'. Qual é o primeiro degrau da resposta?", opcoes: [
          "Entender o que está por trás: caixa, outra proposta ou a necessidade de sentir que fez um bom negócio",
          "Oferecer 2% de imediato e observar a reação, porque a resposta a uma concessão parcial revela quanto ele realmente precisa",
          "Explicar que a margem da concessionária não permite 5% e que o preço apresentado já é o de tabela com a configuração dele",
          "Isolar de imediato ('se eu der os 5%, fechamos hoje?'), para descobrir se o desconto é a única coisa que falta",
        ], correta: 0, explicacao: "A maioria dos pedidos de desconto não é objeção de preço. Sem entender o motivo (medo de pagar mais que o vizinho, parcela, ritual), qualquer resposta é chute. O isolamento vem depois do reenquadre, e a contra-oferta é o último degrau." },
        { pergunta: "O cliente revela que o pedido de desconto é porque 'não quer pagar mais que o vizinho'. O que resolve?", opcoes: [
          "Um desconto que iguale o preço pago pelo vizinho, porque a comparação é real e o cliente vai checar",
          "Prometer que o preço dele é o menor da região e que nenhum vizinho pagou menos pela mesma configuração",
          "Informação: mostrar a tabela da época, a configuração diferente e a transparência de que ele paga o mesmo pela mesma coisa",
          "Explicar, com tato, que o vizinho não deveria ter contado o preço e que cada negociação tem condições próprias",
        ], correta: 2, explicacao: "A objeção é medo de ser feito de bobo, não caixa. Desconto não cura medo; transparência cura. Comparar configuração e tabela da época devolve a sensação de justiça, e a conversa volta para a parcela, que se resolve com estrutura, não com preço." },
        { pergunta: "Qual é a lógica da conta que compara 1% de desconto com treinamento, revisão e kit de peças?", opcoes: [
          "As três concessões custam mais que o desconto, mas fidelizam o cliente e geram indicação, o que compensa no longo prazo",
          "O desconto é preferível porque é mais simples de aplicar, não depende da assistência e o cliente entende na hora",
          "As três concessões são obrigatórias em toda venda de máquina nova e por isso não podem ser usadas como moeda",
          "As três concessões custam menos que 1% de desconto, têm valor percebido maior e são lembradas; o desconto é esquecido e vira âncora",
        ], correta: 3, explicacao: "R$ 7 mil de custo real contra R$ 8.900 de desconto, com valor percebido maior (segurança, produção) e sem efeito de âncora na próxima compra. É por isso que preço é o último degrau: as variáveis de valor resolvem mais barato." },
        { pergunta: "O vendedor deu 3% na hora e o cliente não fechou: comprou uma usada de outra marca. O que o caso ensina?", opcoes: [
          "Que usadas de outras marcas são concorrência imbatível para máquinas novas quando o cliente tem caixa apertado",
          "Que o pedido de desconto escondia outra objeção (gap apertado, medo da parcela) e o desconto não a resolvia; era preciso entender antes",
          "Que 3% foi pouco para a situação; o cliente precisava de 5% para a parcela caber e o vendedor perdeu por dois pontos",
          "Que o cliente não era sério desde o início e usou o pedido de desconto para obter referência de preço para a usada",
        ], correta: 1, explicacao: "A objeção real era estrutural: a máquina nova não tinha serviço suficiente para pagar a parcela. A resposta certa era uma usada certificada ou consórcio, não desconto. Ceder sem entender custou 3% de margem que nem foi usada e a venda." },
        { pergunta: "Se, depois dos quatro primeiros degraus, ainda for necessário mexer no preço, como deve ser a concessão?", opcoes: [
          "Grande o suficiente para encerrar a negociação de vez, porque rodadas sucessivas de desconto pequeno desgastam a relação",
          "Pequena (0,5–1,5%), lenta, com contrapartida concreta e apresentada como exceção com motivo declarado",
          "Igual à diferença para a proposta do concorrente, porque é o único número que o cliente aceita como justo",
          "Condicionada à aprovação do gerente em uma reunião posterior, para o cliente perceber que foi uma exceção difícil",
        ], correta: 1, explicacao: "Pequena protege a margem; lenta sinaliza limite; contrapartida mantém a troca; motivo declarado (fechamento hoje, documentação, indicação) impede que vire regra na próxima compra. Igualar o concorrente ignora a diferença de configuração e assistência." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m6a4", titulo: "Usada e financiamento como alavancas de fechamento", minutos: 14,
      resumo: "A avaliação da usada e a estrutura do financiamento mexem mais na decisão do cliente do que o preço, e custam menos para você. Carência, prazo, entrada com a usada, taxa: é aqui que a parcela cabe no caixa sem sangrar a margem.",
      blocos: [
        { tipo: "p", texto: "O cliente não compra o preço; compra a parcela e a entrada. Uma máquina de R$ 890 mil com a usada avaliada em R$ 280 mil, FINAME em 60 meses com 6 de carência, é uma parcela de R$ 12 mil que começa quando a máquina já produziu por meio ano. A mesma máquina com 3% de desconto e sem estrutura é R$ 863 mil à vista e um cliente que não fecha. A avaliação da usada é a variável de maior alavancagem que você tem: R$ 10 mil a mais na usada custam à concessionária menos que R$ 10 mil de desconto (a usada será revendida) e o cliente sente como ganho direto. E a estrutura do financiamento custa zero: é do banco." },
        { tipo: "framework", nome: "As 6 alavancas de estrutura (antes de qualquer desconto)", origem: "Prática de financiamento de bens de capital (FINAME/BNDES, CDC, consórcio) aplicada ao fechamento", passos: [
          "Avaliação da usada: avalie com critério (horas, estado, mercado), apresente a avaliação com o laudo e a referência de anúncios, e use a margem de avaliação como concessão condicionada.",
          "Carência: 3 a 6 meses no FINAME/CDC para a máquina produzir antes de a parcela começar. Custa zero para você; vale muito para quem tem obra começando.",
          "Prazo: 48, 60 ou 72 meses mudam a parcela em 20–30%. Prazo mais longo com a revenda em 5 anos costuma ser melhor para o caixa do cliente do que desconto.",
          "Entrada: a usada como entrada, ou entrada menor com parcela maior, conforme o caixa.",
          "Taxa e linha: FINAME × CDC × Banco CNH × consórcio × Plano Safra (para produtor rural). A linha certa pode valer 5% no custo total, muito mais que qualquer desconto.",
          "Data de faturamento e primeira parcela: alinhar com a medição, a safra ou o empenho. 'Primeira parcela em março, depois da colheita' fecha vendas que 'desconto' não fecha.",
        ] },
        { tipo: "conta", titulo: "Mesma máquina, três estruturas (R$ 890 mil, usada avaliada em R$ 280 mil)", linhas: [
          ["A) Sem usada, CDC 48 meses, sem carência", "Parcela ≈ R$ 24.900 desde o mês 1"],
          ["B) Usada na entrada, FINAME 60 meses, sem carência", "Parcela ≈ R$ 12.700 desde o mês 1"],
          ["C) Usada na entrada, FINAME 60 meses, 6 de carência", "Parcela ≈ R$ 13.900 a partir do mês 7"],
          ["Economia mensal que a conta do gap mostrou", "R$ 8.800"],
          ["Estrutura C: máquina produz 6 meses antes da 1ª parcela", "≈ R$ 52.800 de economia acumulada antes de pagar"],
          ["Custo para a concessionária das estruturas B e C", "Zero (a estrutura é do banco); a usada é revendida"],
        ], conclusao: "A diferença entre A e C é de R$ 11 mil por mês na parcela e meio ano de fôlego — sem um real de desconto. É a estrutura que faz a máquina caber, não o preço." },
        { tipo: "dialogo", titulo: "A usada como concessão condicionada", falas: [
          { quem: "cliente", texto: "A minha 580 vale mais do que os 260 que você avaliou. O cara da OLX pediu 300 numa igual." },
          { quem: "vendedor", texto: "Pediu 300 e vendeu por quanto? Anúncio é pedido, não venda. Eu te trago três anúncios e o valor que as últimas duas 580 do ano dela saíram aqui na região: 245 e 265. Os 260 estão em cima disso." },
          { quem: "nota", texto: "Critério objetivo (Fisher & Ury): a avaliação se defende com mercado, não com opinião." },
          { quem: "cliente", texto: "Mesmo assim, eu queria 280." },
          { quem: "vendedor", texto: "Eu consigo chegar em 275 se a gente fechar essa semana com a documentação do FINAME, porque aí eu já tenho comprador pra ela em Guaçuí e não fico com ela no pátio. Se passar da semana, volta para 260. Faz sentido?" },
          { quem: "nota", texto: "R$ 15 mil na usada (com motivo real: revenda já encaminhada) em troca de fechamento e documentação. Para o cliente, é 'ganhei 15 mil'; para a concessionária, custa menos que 1% de desconto." },
        ] },
        { tipo: "caso", titulo: "Caso: 'não cabe' que virou 'quando entrega?'", situacao: "Empreiteiro de Castelo gostou da E145C, mas travou: 'a parcela de 19 mil não cabe agora, a obra só começa a medir em abril'. O vendedor da concorrente ofereceu 4% de desconto. Nada mudou: R$ 18.200 continuava não cabendo em fevereiro.", acao: "Nosso vendedor montou: usada na entrada, FINAME 60 meses, carência de 4 meses (primeira parcela em junho, duas medições depois do início), parcela de R$ 13.600.", resultado: "Fechou no mesmo dia, sem desconto. O cliente disse: 'ninguém tinha me perguntado quando a obra começava a pagar'.", licao: "Quando o cliente diz 'não cabe', ele está falando de fluxo de caixa, não de preço. Desconto muda o preço; estrutura muda o fluxo." },
        { tipo: "tabela", titulo: "Qual linha para qual cliente (referência — confirme taxas vigentes)", colunas: ["Cliente", "Linha típica", "Por quê", "Atenção"], linhas: [
          ["Empreiteira com CNPJ e balanço", "FINAME (BNDES) via banco", "Menor taxa, prazo longo, carência", "Exige análise e documentação; leva 2–4 semanas"],
          ["Produtor rural / cooperativa", "Plano Safra / Pronamp / Moderfrota", "Juros subsidiados, calendário da safra", "Janela anual; limite por produtor"],
          ["Cliente com pressa e crédito bom", "CDC do banco ou Banco CNH", "Aprovação em dias", "Taxa maior; negocie prazo"],
          ["Cliente sem urgência ou com crédito restrito", "Consórcio com lance", "Sem juros; usada como lance", "Contemplação incerta; explicar bem"],
          ["Prefeitura", "Recursos próprios, convênio, FINAME municípios (PMAT/outros)", "Depende de dotação e empenho", "Calendário do empenho; documentação"],
        ] },
        { tipo: "erros", titulo: "Erros com usada e financiamento", itens: [
          "Avaliar a usada 'de olho' e depois recuar: perde a confiança. Avalie com laudo e referência de mercado.",
          "Oferecer desconto para quem disse 'não cabe a parcela'. Ele não pediu preço; pediu fôlego.",
          "Não conhecer as linhas: o vendedor que sabe a diferença entre FINAME e CDC fecha o que o outro perde.",
          "Prometer aprovação de crédito. Diga 'vou encaminhar hoje e te dou retorno em 48 h' e cumpra.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para uma negociação aberta, monte as três estruturas (A, B, C) com os números reais do cliente e da usada dele. Calcule a parcela de cada uma e a economia acumulada na carência. Apresente as três ao cliente e deixe ele escolher — a escolha é o fechamento." },
      ],
      missao: "Em uma negociação em que o cliente disse 'não cabe' ou pediu desconto, monte e apresente três estruturas (usada, prazo, carência, linha) sem mexer no preço. Registre no CRM qual estrutura ele escolheu e quanto de desconto foi evitado.",
      quiz: [
        { pergunta: "O cliente diz 'a parcela de 19 mil não cabe, a obra só começa a medir em abril'. Qual é a resposta com método?", opcoes: [
          "Montar a estrutura: usada na entrada, prazo mais longo e carência para a primeira parcela cair depois das primeiras medições",
          "Sugerir uma máquina de classe abaixo, mais barata, cuja parcela caiba no caixa atual sem depender da obra de abril",
          "Propor que ele alugue até abril, com opção de compra, e feche a nova quando a medição começar a entrar",
          "Oferecer 4% de desconto para reduzir a parcela e aproximá-la do que o caixa de fevereiro consegue pagar",
        ], correta: 0, explicacao: "'Não cabe' é fluxo de caixa, não preço. Desconto de 4% deixa a parcela em R$ 18.200, que continua não cabendo em fevereiro. Carência e usada mudam o fluxo, custam zero para a concessionária e fecharam no mesmo dia no caso da aula." },
        { pergunta: "Por que R$ 15 mil a mais na avaliação da usada costuma custar menos à concessionária do que R$ 15 mil de desconto?", opcoes: [
          "Porque o cliente não percebe a diferença na avaliação com a mesma clareza com que percebe um desconto no preço",
          "Porque a usada entra na contabilidade como estoque e não como custo, e por isso não afeta a margem da venda",
          "Porque a usada será revendida e a diferença pode ser parcial ou totalmente recuperada, enquanto o desconto é margem perdida",
          "Porque a fábrica subsidia parte das avaliações de usadas em programas de troca, reduzindo o custo para a concessionária",
        ], correta: 2, explicacao: "A usada é um ativo que volta ao mercado; o desconto é dinheiro que não volta. E para o cliente, a avaliação maior é sentida como ganho direto ('ganhei 15 mil'). Por isso ela é a variável de maior alavancagem, desde que usada com critério e contrapartida." },
        { pergunta: "O cliente contesta a avaliação da usada citando um anúncio da OLX com preço maior. Como o consultor responde?", opcoes: [
          "Sugere que ele venda a usada por conta própria pelo valor do anúncio e compre a nova à vista com o dinheiro da venda",
          "Aceita o valor do anúncio como base da avaliação para não perder a venda, compensando na condição de pagamento da nova",
          "Explica que a concessionária tem a própria tabela de avaliação, baseada em leilões, e que ela não é negociável caso a caso",
          "Diferencia pedido de venda, traz vendas reais da região como critério objetivo e usa a margem de avaliação como concessão condicionada",
        ], correta: 3, explicacao: "Anúncio é pedido, não venda: o critério objetivo (Fisher & Ury) são as vendas reais. Com isso a avaliação se defende, e a margem que você tem para subir vira concessão trocada por fechamento e documentação, com motivo real (revenda encaminhada)." },
        { pergunta: "Qual afirmação sobre carência no financiamento está correta?", opcoes: [
          "Custa caro à concessionária, porque os juros do período são absorvidos na venda, e deve ser usada só em último caso",
          "Reduz o preço final da máquina, porque o cliente paga menos parcelas ao longo do contrato de financiamento",
          "Só está disponível para prefeituras e órgãos públicos, por causa do calendário de empenho e do orçamento anual",
          "Custa zero para a concessionária (é do banco), permite que a máquina produza antes da primeira parcela e resolve 'não cabe agora'",
        ], correta: 3, explicacao: "Carência é estrutura, não preço: seis meses de produção antes de pagar podem significar R$ 50 mil de economia acumulada na conta do gap. Está disponível em FINAME e CDC para empresas e produtores; para a concessionária, não custa nada." },
        { pergunta: "Um produtor de café com crédito rural disponível e um empreiteiro com pressa e crédito bom pedem financiamento. Quais linhas são as mais adequadas, respectivamente?", opcoes: [
          "CDC para o produtor, pela rapidez; Plano Safra para o empreiteiro, pelas taxas menores das linhas de investimento",
          "Consórcio para ambos, porque não tem juros e permite usar a usada como lance para antecipar a contemplação",
          "Plano Safra/Moderfrota para o produtor (juros subsidiados, calendário da safra); CDC ou Banco CNH para o empreiteiro (aprovação em dias)",
          "FINAME para o produtor, pelo prazo longo; consórcio para o empreiteiro, para não comprometer o limite bancário da empresa",
        ], correta: 2, explicacao: "Cada perfil tem a linha certa: o produtor rural tem acesso a juros subsidiados com janela anual; o empreiteiro com pressa precisa de aprovação rápida, mesmo com taxa maior. Consórcio não serve a quem tem pressa; FINAME leva semanas e não é a linha rural." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m6a5", titulo: "Compras, licitação e prefeitura: as regras do jogo", minutos: 15,
      resumo: "Com o setor de compras de uma construtora ou com o pregoeiro da prefeitura, a negociação tem regras diferentes: menor preço, especificação, prazo de empenho, garantia. Quem entende o processo influencia antes do pregão; quem só aparece no dia disputa centavos.",
      blocos: [
        { tipo: "p", texto: "Na venda para prefeitura, a negociação acontece antes de o edital sair: no termo de referência, que define a especificação, o prazo de entrega, a garantia e a assistência exigida. Quem ajuda o engenheiro a escrever um termo tecnicamente correto (não direcionado, mas exigente) chega ao pregão com uma máquina que atende com folga enquanto a concorrente mais barata fica de fora por não cumprir a especificação. No pregão, a disputa é de lances; a sua margem é decidida na preparação: preço piso, custo de entrega, prazo. No setor de compras de uma construtora, o comprador é medido pelo desconto que consegue; dê a ele uma vitória visível que não seja o seu preço." },
        { tipo: "framework", nome: "Ciclo da venda pública (Lei 14.133/2021) e onde você atua", origem: "Lei 14.133/2021 (Nova Lei de Licitações) e prática de venda a municípios", passos: [
          "Necessidade e dotação: a secretaria identifica a necessidade e o orçamento (LOA, convênio, emenda). Sua atuação: sinal (Diário, visita ao secretário), custo/hora e TCO para justificar a compra de frota própria × locação.",
          "Estudo técnico preliminar e termo de referência: o engenheiro define especificação, garantia, assistência (distância, prazo de atendimento), treinamento, prazo de entrega. Sua atuação: material técnico com fontes, visita técnica, referência de outros municípios. Nunca 'direcione'; ajude a exigir o que a lei permite (desempenho, garantia, assistência).",
          "Pesquisa de preço: cotações para o valor de referência. Sua atuação: cotação coerente com a especificação completa (não a mais barata, não a mais cara).",
          "Edital e pregão (eletrônico na maioria): lances em tempo real; critério normalmente é menor preço com especificação mínima. Sua atuação: preço piso definido com o gerente, documentação impecável, atenção ao prazo de entrega e às amostras/catálogos exigidos.",
          "Habilitação, homologação, empenho e entrega: documentação, prazo, entrega técnica, treinamento. Sua atuação: cumprir à risca; a próxima licitação é ganha na entrega desta.",
          "Atas de registro de preço e adesão ('carona'): um município vencido pode gerar adesões de outros. Sua atuação: ofereça a ata a municípios vizinhos.",
        ] },
        { tipo: "tabela", titulo: "Termo de referência: exigências legítimas que separam máquinas", colunas: ["Item", "Exigência legítima (desempenho/assistência)", "Efeito"], linhas: [
          ["Assistência técnica", "Concessionária autorizada a até X km ou atendimento em até 48 h", "Elimina quem não tem rede na região"],
          ["Garantia", "12 meses sem limite de horas, ou 2.000 h", "Elimina garantia curta"],
          ["Treinamento", "Operadores e mecânicos do município, X horas, na entrega", "Valoriza quem entrega técnica"],
          ["Peso operacional / potência / capacidade", "Faixa mínima compatível com o serviço (ex.: patrol ≥ 140 hp para estradas vicinais)", "Especificação por desempenho, não por marca"],
          ["Prazo de entrega", "Compatível com a necessidade (ex.: 45 dias)", "Elimina quem importa sob encomenda"],
          ["Peças", "Disponibilidade de peças de desgaste em estoque regional", "Reforça assistência"],
        ] },
        { tipo: "dialogo", titulo: "Com o comprador da construtora", falas: [
          { quem: "cliente", texto: "(comprador) O engenheiro aprovou a E215C, mas o meu trabalho é conseguir preço. Preciso de 6%." },
          { quem: "vendedor", texto: "Entendo, e eu sei que você é cobrado por isso. Deixa eu te ajudar a mostrar uma vitória de verdade pra diretoria, que não seja só um número que a gente inventa pra você riscar. Três coisas: treinamento de dois operadores, kit de peças de desgaste e primeira revisão, que somam R$ 11 mil de valor que a empresa vai gastar de qualquer jeito. E no preço, 1% com fechamento até sexta, pra eu segurar a máquina da fila." },
          { quem: "nota", texto: "O comprador precisa de um troféu; o vendedor dá um troféu com valor real e custo baixo, mais uma concessão pequena e condicionada. Sem sangrar 6%." },
          { quem: "cliente", texto: "Isso eu consigo mostrar. Fecha com 1,5% que eu aprovo hoje." },
          { quem: "vendedor", texto: "1,5% com a documentação hoje e o faturamento este mês. Fechado." },
        ] },
        { tipo: "caso", titulo: "Caso: o termo de referência bem escrito", situacao: "Prefeitura da região ia licitar uma retroescavadeira. O engenheiro, sem apoio, copiou um termo genérico de outro município: só potência mínima e 'garantia de fábrica'.", acao: "O vendedor levou ao engenheiro um termo modelo com exigências de desempenho e assistência (concessionária a até 80 km, atendimento em 48 h, garantia de 12 meses, treinamento na entrega, peças em estoque regional), todas legais e justificáveis pela necessidade do município.", resultado: "O edital saiu com as exigências. Duas marcas sem rede na região não se habilitaram. A disputa ficou entre três com assistência local, e a New Holland venceu com margem preservada. O município, dois anos depois, ainda não teve máquina parada por falta de peça.", licao: "Licitação não se ganha no pregão; se ganha no termo de referência. Ajudar o engenheiro a exigir o que o município precisa é venda consultiva pública." },
        { tipo: "checklist", titulo: "Antes do pregão", itens: [
          "Preço piso definido com o gerente, incluindo custo de entrega, treinamento e garantia exigidos.",
          "Documentação de habilitação conferida (certidões, atestados de capacidade técnica, catálogo, declarações).",
          "Especificação lida linha a linha: a máquina atende a tudo? Onde está a folga?",
          "Prazo de entrega confirmado com a fábrica por escrito.",
          "Concorrentes prováveis e histórico de lances deles em pregões anteriores (portais públicos).",
          "Plano para atas de registro de preço: quais municípios vizinhos podem aderir?",
        ] },
        { tipo: "erros", titulo: "Erros em vendas públicas", itens: [
          "Tentar 'direcionar' o edital com marca ou detalhe irrelevante: ilegal, e o pregoeiro impugna. Exija desempenho e assistência, que são legítimos.",
          "Aparecer só no dia do pregão. Sem trabalho no termo, você disputa centavos com quem não tem assistência.",
          "Dar lance abaixo do piso 'para ganhar'. Entrega com prejuízo e assistência ruim — e perde a próxima.",
          "Entregar mal. Prefeitura lembra, e o secretário conversa com o secretário vizinho.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Leia um edital recente de máquina pesada de um município da sua região (portal de compras). Marque cada exigência do termo de referência e classifique: desempenho, assistência, garantia, genérica. Escreva quais exigências legítimas faltaram e que teriam beneficiado o município — e você." },
      ],
      missao: "Identifique uma prefeitura da carteira com necessidade de máquina nos próximos 12 meses e marque uma visita técnica ao engenheiro levando um termo de referência modelo com exigências de desempenho e assistência. Registre no CRM a etapa do processo (dotação, ETP, termo, edital) e a data prevista.",
      quiz: [
        { pergunta: "Em qual etapa da venda para prefeitura a negociação de fato se decide?", opcoes: [
          "No termo de referência, quando o engenheiro define especificação, assistência, garantia e prazo",
          "Na entrega, quando a máquina chega e o município avalia se a próxima compra será da mesma marca",
          "No pregão, pelos lances, porque é o único momento em que o preço realmente é disputado",
          "Na homologação, quando o prefeito assina e confirma o vencedor do certame",
        ], correta: 0, explicacao: "O pregão é disputa de centavos entre quem se habilitou. Quem se habilita é definido pelo termo de referência. Exigências legítimas de desempenho e assistência (não de marca) fazem a disputa acontecer entre máquinas comparáveis, e a margem se preserva." },
        { pergunta: "O comprador da construtora diz que 'o engenheiro aprovou, mas meu trabalho é conseguir preço; preciso de 6%'. Qual resposta atende ao comprador sem sangrar a margem?", opcoes: [
          "Oferecer 3% como meio-termo, porque o comprador precisa de um número redondo e a metade do pedido preserva a margem",
          "Dar a ele uma vitória visível com valor real e custo baixo (treinamento, kit de peças, revisão) mais uma concessão pequena e condicionada",
          "Dar os 6%, porque o comprador tem poder de veto sobre a compra e a aprovação do engenheiro não basta sem ele",
          "Recusar com educação e pedir para falar diretamente com o engenheiro, que aprovou a máquina e pode sustentar o preço",
        ], correta: 1, explicacao: "O comprador é medido pelo que consegue; ele precisa de um troféu para a diretoria. Valor real (R$ 11 mil de itens que a empresa gastaria) mais 1–1,5% condicionado a fechamento e faturamento dão o troféu e preservam a margem. Pular o comprador cria um bloqueador." },
        { pergunta: "Qual das exigências abaixo é legítima em um termo de referência e qual é ilegal?", opcoes: [
          "Legítima: 'marca New Holland ou similar', porque a lei permite indicar marca de referência; ilegal: 'assistência a até 80 km'",
          "Legítima: 'concessionária autorizada a até 80 km com atendimento em 48 h'; ilegal: exigir marca ou detalhe que só um fabricante tem",
          "Ambas são legítimas desde que o engenheiro assine a justificativa técnica e o termo passe pela assessoria jurídica",
          "Ambas são ilegais; o termo de referência só pode conter potência, peso operacional e capacidade, sem exigências de assistência",
        ], correta: 1, explicacao: "A Lei 14.133 permite exigências de desempenho, garantia e assistência justificadas pela necessidade do município. Direcionar por marca ou por característica irrelevante que só um atende é ilegal e impugnável. Ajudar a exigir o que o município precisa é consultivo; direcionar é crime." },
        { pergunta: "Por que dar lance abaixo do preço piso 'para ganhar o pregão' é um erro grave?", opcoes: [
          "Porque entrega com prejuízo, pressiona a assistência (que fica ruim) e o município lembra na próxima licitação e conta ao vizinho",
          "Porque a fábrica não aceita pedidos faturados abaixo da tabela e a concessionária fica sem cobertura de garantia",
          "Porque os concorrentes podem denunciar o preço inexequível ao tribunal de contas e anular o certame",
          "Porque o pregoeiro pode desclassificar o lance por inexequibilidade, e a concessionária perde a chance de disputar",
        ], correta: 0, explicacao: "Vitória com prejuízo obriga a cortar o que o município mais precisa depois (assistência, treinamento). A reputação entre prefeituras circula, e a ata de registro de preço vencida com prejuízo ainda pode gerar adesões de outros municípios no mesmo preço ruim." },
        { pergunta: "O que é uma ata de registro de preço e por que ela interessa ao vendedor?", opcoes: [
          "É o contrato de fornecimento da máquina vencida no pregão, com prazo de entrega, garantia e condições de pagamento do município",
          "É a lista de preços de referência usada pelo pregoeiro para julgar se os lances são exequíveis e se cabem na dotação",
          "É o registro do preço vencedor que permite ao município (e a outros, por adesão) comprar no prazo da ata; gera vendas vizinhas",
          "É o documento de empenho do orçamento, que reserva o valor da compra e autoriza o faturamento da máquina pela concessionária",
        ], correta: 2, explicacao: "A ata vale por um prazo e permite adesões ('carona') de outros órgãos dentro de limites legais. Um pregão vencido com margem preservada vira canal de vendas para a região; um vencido com prejuízo vira prejuízo multiplicado." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m6a6", titulo: "Táticas duras e ética: reconhecer, responder, não usar", minutos: 13,
      resumo: "Bom policial/mau policial, prazo falso, 'o outro cobriu', ultimato, silêncio hostil, a mordida final. Você vai encontrar todas. Reconhecer a tática tira o poder dela; responder com calma e critério mantém a relação. E não usar nenhuma é o que faz você durar 20 anos no mesmo território.",
      blocos: [
        { tipo: "p", texto: "Negociação dura não é negociação desonesta, mas algumas táticas cruzam a linha: a pressão fabricada, a informação falsa, a mordida de última hora. Elas funcionam contra quem não as reconhece e contra quem tem BATNA fraca. O consultor preparado identifica a tática, nomeia (com elegância) o que está acontecendo, volta ao critério objetivo e mantém a calma. E entende que, no interior, cada tática que ele mesmo usar vai ser contada na associação, no sindicato e no grupo da cooperativa. A ética aqui não é só valor: é estratégia de sobrevivência." },
        { tipo: "tabela", titulo: "Táticas duras e a resposta do consultor", colunas: ["Tática", "Como reconhecer", "Resposta"], linhas: [
          ["Bom policial / mau policial", "Sócio 'razoável' e sócio 'intransigente' alternam; o razoável pede para você ceder 'para acalmar o outro'", "Trate os dois como um só: 'Vocês dois precisam concordar; o que faria sentido para os dois?' Não negocie com o 'bom' contra o 'mau'"],
          ["'O outro cobriu / me deu X'", "Número redondo, sem proposta escrita, urgência", "'Ótimo, me mostra a proposta que eu vejo o que está incluso' — teste a BATNA; compare configuração, prazo, assistência"],
          ["Prazo falso / ultimato", "'Decido hoje ou vou embora'", "Calma; 'entendo o prazo; o que muda amanhã?' Se for blefe, cai; se for real, negocie com contrapartida"],
          ["Mordida final (nibbling)", "Depois de tudo acordado: 'ah, e coloca o frete'", "'Posso incluir o frete se a gente retirar a primeira revisão' — toda mordida custa algo; ou reabra o acordo"],
          ["Silêncio hostil", "Depois da sua proposta, ele cala e encara", "Cale também. Quem fala primeiro cede. Ou: 'parece que algo não fechou pra você; o que é?'"],
          ["Autoridade limitada", "'Eu adoraria, mas o meu sócio não deixa'", "'Então vamos marcar com o seu sócio' — leve a negociação a quem decide"],
          ["Ancoragem absurda", "'Pago 600' para uma máquina de 890", "Não responda com número; 'seiscentos?' e volte ao critério (tabela, TCO, mercado)"],
        ] },
        { tipo: "dialogo", titulo: "A mordida final", falas: [
          { quem: "cliente", texto: "Fechado então em 880, com a usada em 275 e a carência. Ah, e você inclui o frete e a caçamba de limpeza, né?" },
          { quem: "vendedor", texto: "(sorrindo) Frete e caçamba… a caçamba de limpeza é R$ 14 mil. Eu topo incluir o frete se a gente ficar com a primeira revisão fora — ou mantemos o que combinamos, que já está no limite. O que você prefere?" },
          { quem: "nota", texto: "Nomeia a mordida com leveza, dá uma escolha em que toda inclusão tem custo. O cliente percebe que o acordo era o acordo." },
          { quem: "cliente", texto: "Deixa como estava. Só o frete então?" },
          { quem: "vendedor", texto: "Frete pela revisão. Ou nada disso e mantemos a revisão. Você escolhe." },
          { quem: "cliente", texto: "Mantém a revisão. Fechado." },
        ] },
        { tipo: "framework", nome: "Os 4 passos diante de uma tática dura", origem: "Ury (Supere o Não) e Voss", passos: [
          "Reconheça: nomeie mentalmente a tática ('isso é prazo falso'). Reconhecer tira metade do poder.",
          "Não reaja: respire, cale 4 segundos, não ceda nem ataque. A reação emocional é o que a tática busca.",
          "Nomeie com elegância (rótulo): 'Parece que a gente está chegando num ponto em que cada coisa nova que entra tira outra', 'Parece que tem um prazo que eu não conheço; me conta'.",
          "Volte ao critério: tabela, TCO, mercado, acordo já feito. Critério objetivo é o terreno onde tática não funciona.",
        ] },
        { tipo: "caso", titulo: "Caso: o prazo que não existia", situacao: "Cliente afirmou que 'a Volvo entrega em 15 dias e o contrato dele começa em 20; se a gente não cobrir o preço deles até amanhã, ele fecha lá'.", acao: "O vendedor manteve a calma, rotulou ('parece que o prazo da obra está apertando e você precisa de segurança de entrega') e perguntou: 'o que muda se a gente conversar na quinta em vez de amanhã?'. O cliente hesitou. O vendedor ligou para a Volvo como cliente: entrega em 60 dias.", resultado: "Voltou com o dado ('a informação que você tem sobre 15 dias pode estar desatualizada') sem acusar. O cliente fechou com a New Holland em 30 dias de entrega, sem desconto adicional.", licao: "Ultimato e 'o outro cobriu' são testáveis. Quem testa com calma raramente cede; quem reage, cede sempre." },
        { tipo: "destaque", titulo: "O que você nunca faz", texto: "Não inventa proposta de concorrente, não cria prazo falso, não usa 'último da fábrica' toda semana, não muda a avaliação da usada depois de combinada, não promete o que não confirmou, não faz mordida final no cliente. No interior, cada uma dessas é descoberta em dias e custa a região inteira. A sua reputação é a única BATNA que você leva de uma concessionária para outra." },
        { tipo: "erros", titulo: "Erros diante de táticas duras", itens: [
          "Reagir com raiva ou com submissão. As duas entregam o controle.",
          "Ceder ao bom policial 'para acalmar' o mau. Você negocia com os dois como um.",
          "Aceitar a mordida final 'porque é pequena'. A próxima é maior, e o cliente aprendeu.",
          "Retaliar com a mesma tática. Você vira o vendedor de quem contam a história no sindicato.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Lembre das três negociações mais difíceis do ano. Identifique qual tática foi usada em cada uma (tabela acima), como você reagiu e o que teria feito com os quatro passos. Escreva a resposta ideal para cada uma e ensaie em voz alta." },
      ],
      missao: "Na próxima negociação em que uma tática dura aparecer (prazo, 'o outro cobriu', mordida), aplique os quatro passos e registre no CRM qual era a tática, como você respondeu e o resultado. Compare com uma negociação anterior em que cedeu.",
      quiz: [
        { pergunta: "Depois de tudo acordado, o cliente diz: 'ah, e inclui o frete e a caçamba de limpeza, né?'. Qual é a resposta correta?", opcoes: [
          "Aceitar os dois para não estragar o clima do fechamento, porque frete e caçamba custam pouco diante da venda",
          "Cancelar o acordo e reabrir a negociação do zero, porque a mordida mostra que o cliente não considera nada fechado",
          "Aceitar o frete, que é pequeno, e negar a caçamba, que é cara, mostrando flexibilidade sem ceder no que importa",
          "Nomear com leveza e oferecer a escolha: toda inclusão tira algo já acordado (frete pela revisão) ou mantém-se o combinado",
        ], correta: 3, explicacao: "A mordida final testa se o acordo era o acordo. Aceitar 'o pequeno' ensina que sempre cabe mais; recusar com raiva estraga; reabrir tudo é desproporcional. A escolha com custo ('frete pela revisão') mantém a troca e o cliente costuma manter o combinado." },
        { pergunta: "O cliente afirma que 'a Volvo entrega em 15 dias e cobre o preço; decido amanhã'. O que o consultor faz?", opcoes: [
          "Cobre o preço da Volvo com contrapartida de fechamento hoje, porque perder por prazo e preço juntos é o pior cenário",
          "Diz que a Volvo não tem assistência na região e que o prazo de 15 dias é conversa de vendedor, para desmontar o blefe",
          "Mantém a calma, rotula, pergunta o que muda se conversarem na quinta e testa a informação (prazo real da Volvo) antes de conceder",
          "Aceita perder a venda com elegância, porque cliente que blefa com prazo e preço não vale a margem nem o desgaste",
        ], correta: 2, explicacao: "Ultimato e 'o outro cobriu' são testáveis. No caso da aula, o prazo real era 60 dias. Testar sem acusar preserva a relação e a margem. Cobrir cede sem informação; depreciar ativa a defesa; desistir joga fora uma venda boa." },
        { pergunta: "Dois sócios alternam: um é 'razoável' e pede para você ceder 'para acalmar' o outro, 'intransigente'. Qual é a resposta?", opcoes: [
          "Negociar com o razoável e deixar que ele convença o outro, porque um aliado dentro da empresa vale mais que um argumento",
          "Ceder um pouco para o razoável, que está do seu lado, para dar a ele munição para vencer o intransigente por dentro",
          "Pedir para negociar apenas com o intransigente, que é o verdadeiro decisor, e tratar o razoável como intermediário",
          "Tratar os dois como um só ('o que faria sentido para os dois?') e não negociar com um contra o outro",
        ], correta: 3, explicacao: "Bom/mau policial funciona porque você passa a ver o 'bom' como aliado e cede a ele. Os dois são a mesma parte. A pergunta calibrada dirigida aos dois desmonta a divisão de papéis e devolve a negociação ao critério." },
        { pergunta: "Qual é o primeiro passo diante de qualquer tática dura?", opcoes: [
          "Reconhecer mentalmente a tática, porque nomeá-la tira metade do poder dela",
          "Responder com a mesma tática para equilibrar a mesa e mostrar que você conhece o jogo",
          "Chamar o gerente para a negociação, porque a presença de uma autoridade neutraliza a pressão",
          "Encerrar a reunião com elegância e retomar por escrito, onde a tática não tem efeito",
        ], correta: 0, explicacao: "Tática funciona no automático emocional. Reconhecer ('isso é prazo falso') ativa o pensamento lento e impede a reação. Depois vêm o silêncio, o rótulo elegante e a volta ao critério. Retaliar ou fugir entregam o controle." },
        { pergunta: "Por que a ética nas táticas de negociação é também uma estratégia comercial no interior, e não só um valor?", opcoes: [
          "Porque a fábrica audita as negociações das concessionárias e penaliza práticas de pressão identificadas nos relatórios",
          "Porque as táticas desonestas são descobertas em dias, contadas na associação e no sindicato, e a reputação é a única BATNA que você leva",
          "Porque os clientes do interior são mais desconfiados que os da capital e percebem qualquer manobra na primeira conversa",
          "Porque a legislação de defesa do consumidor pune táticas de pressão em vendas de alto valor, com multas para a concessionária",
        ], correta: 1, explicacao: "Um território pequeno tem memória longa. Prazo falso, proposta de concorrente inventada, usada reavaliada para baixo depois de combinada: cada uma custa a região. O vendedor que dura 20 anos no mesmo território é o que nunca precisou dessas táticas." },
      ],
    },
  ],
  prova: [
    { pergunta: "O que é BATNA e por que ela protege a margem?", opcoes: [
      "A melhor alternativa caso não haja acordo; quem tem alternativa concreta negocia com calma e cede menos",
      "O desconto máximo autorizado pelo gerente; quem o conhece sabe até onde pode ir sem comprometer a margem",
      "A proposta do concorrente que serve de referência; quem a conhece pode posicionar a própria oferta com precisão",
      "O valor mínimo da usada na troca; quem o define antes evita ceder na avaliação durante a pressão da mesa",
    ], correta: 0, explicacao: "Quem sabe o que faz se não fechar (outras negociações maduras, fila da fábrica) não implora. E quem conhece a BATNA real do cliente (concorrente a 45 dias e 140 km) sabe que ela é mais fraca do que ele apresenta." },
    { pergunta: "O cliente ancora em 800 para uma máquina de 890. Qual é o erro mais comum e o que fazer?", opcoes: [
      "O erro é aceitar sem discutir; deve-se recusar com firmeza e encerrar a reunião para o cliente sentir onde está o limite",
      "O erro é responder com contra-número imediato; deve-se espelhar, rotular, voltar ao critério e perguntar 'como faço isso?'",
      "O erro é não chamar o gerente na hora; deve-se pedir autorização para uma condição intermediária e fechar no mesmo dia",
      "O erro é não ter ancorado mais alto desde o início; deve-se subir a âncora para 950 na próxima rodada e negociar a partir dela",
    ], correta: 1, explicacao: "Contra-número transforma a negociação em divisão da diferença a partir de uma âncora baixa. A pergunta calibrada faz o cliente revelar o interesse real (parcela, usada) e abre a troca de variáveis." },
    { pergunta: "Qual sequência de concessões sinaliza limite e faz o cliente parar de pedir?", opcoes: [
      "5%, depois 5%, depois 5%, com regularidade",
      "1%, depois 3%, depois 5%, em progressão",
      "3%, 1%, 0,5%, cada uma com contrapartida",
      "Uma única concessão de 10% logo no início",
    ], correta: 2, explicacao: "Concessões decrescentes e condicionadas comunicam 'estou chegando no fim' sem palavras. Iguais dizem 'sempre tem mais'; crescentes recompensam a pressão; a grande inicial ancora baixo." },
    { pergunta: "Qual variável tem custo baixo para o vendedor e alto valor percebido, e deve vir antes de qualquer desconto?", opcoes: [
      "Redução de 2% no preço, apresentada como exceção obtida com o gerente",
      "Entrega antes da fila, negociada com a fábrica para a obra começar no prazo",
      "Avaliação da usada 20 mil acima do mercado, como gesto de boa vontade",
      "Treinamento do operador, primeira revisão e kit de peças de desgaste",
    ], correta: 3, explicacao: "As três somadas custam menos que 1% de desconto e são lembradas por meses. Desconto é esquecido em uma semana e vira âncora na próxima compra. Preço é o último degrau." },
    { pergunta: "O cliente diz 'a parcela não cabe agora; a obra só começa a medir em abril'. O que resolve?", opcoes: [
      "Desconto de 4% para reduzir a parcela ao que o caixa atual suporta, mantendo o prazo e a entrada originais",
      "Máquina de classe menor, com parcela compatível com fevereiro, mesmo que produza menos na obra de abril",
      "Estrutura do financiamento: usada na entrada, prazo mais longo e carência até depois das primeiras medições",
      "Aluguel de uma máquina até abril, com compra da nova depois da primeira medição e abatimento do aluguel pago",
    ], correta: 2, explicacao: "'Não cabe' é fluxo de caixa. Carência e usada mudam o fluxo, custam zero para a concessionária e fecharam no mesmo dia no caso da aula. Desconto de 4% deixa a parcela quase igual e não resolve fevereiro." },
    { pergunta: "Por que a avaliação da usada é a variável de maior alavancagem na negociação?", opcoes: [
      "Porque a fábrica subsidia a diferença entre a avaliação e o valor de mercado nos programas oficiais de troca de frota",
      "Porque o cliente sente a avaliação maior como ganho direto e a concessionária revende a usada, recuperando parte ou tudo",
      "Porque a usada não afeta a margem contábil da venda nova, que é calculada apenas sobre o preço da máquina faturada",
      "Porque o banco financia a usada junto com a nova, o que dilui o valor da avaliação ao longo das parcelas do contrato",
    ], correta: 1, explicacao: "R$ 15 mil na usada, com critério e contrapartida, valem para o cliente como R$ 15 mil de desconto e custam à concessionária muito menos, porque o ativo volta ao mercado." },
    { pergunta: "Em vendas para prefeitura, qual etapa define quem disputa o pregão?", opcoes: [
      "O termo de referência, com exigências legítimas de desempenho, assistência e garantia",
      "A sessão de lances, onde o menor preço decide quem leva a máquina e a ata",
      "A homologação pelo prefeito, que confirma o vencedor e autoriza o contrato",
      "O empenho do orçamento, que reserva o valor da compra e libera o faturamento",
    ], correta: 0, explicacao: "Exigências legais de assistência a X km, atendimento em 48 h, garantia e treinamento eliminam quem não tem rede na região, e a disputa fica entre máquinas comparáveis. Direcionar por marca é ilegal; exigir desempenho é consultivo." },
    { pergunta: "O comprador da construtora precisa 'mostrar desconto' à diretoria. Qual é a melhor estratégia?", opcoes: [
      "Aumentar o preço na proposta inicial para depois 'descontar' o que ele pede, entregando o número que ele precisa mostrar",
      "Dar o desconto pedido para manter o comprador como aliado, porque ele vai influenciar as próximas compras da construtora",
      "Dar uma vitória visível de valor real e custo baixo (treinamento, kit, revisão) mais uma concessão pequena e condicionada no preço",
      "Ignorar o comprador e fechar diretamente com o engenheiro, que aprovou a máquina e tem mais peso na decisão técnica",
    ], correta: 2, explicacao: "O comprador é medido pelo que consegue; dê a ele um troféu real que a empresa usaria de qualquer forma, mais 1–1,5% condicionado a fechamento e faturamento. Ignorá-lo cria um bloqueador; inflar o preço é desonesto e descoberto." },
    { pergunta: "Qual é a resposta correta a 'o outro me deu X, cobre até amanhã'?", opcoes: [
      "Cobrir imediatamente com contrapartida de fechamento, para não perder a venda por um número que o cliente já tem na mão",
      "Recusar e encerrar com elegância, porque 'o outro me deu X' sem proposta escrita é quase sempre blefe",
      "Manter a calma, pedir para ver a proposta e comparar configuração, prazo e assistência; testar o prazo antes de qualquer concessão",
      "Oferecer metade da diferença como gesto de boa-fé, mostrando flexibilidade sem igualar o concorrente",
    ], correta: 2, explicacao: "'O outro cobriu' é testável. Proposta escrita, configuração e prazo real costumam mudar a comparação. Cobrir ou dividir a diferença cede sem informação; recusar sem testar pode perder uma venda real." },
    { pergunta: "O que o vendedor NUNCA deve fazer, mesmo que 'funcione' uma vez?", opcoes: [
      "Ancorar na tabela cheia com a configuração completa, mesmo sabendo que o cliente vai pedir desconto",
      "Condicionar toda concessão a uma contrapartida, mesmo quando o cliente parece ofendido com a troca",
      "Testar a BATNA do cliente com perguntas sobre prazo e assistência do concorrente, mesmo que pareça desconfiança",
      "Inventar proposta de concorrente, criar prazo falso ou reduzir a avaliação da usada depois de combinada",
    ], correta: 3, explicacao: "Táticas desonestas são descobertas em dias num território pequeno e custam a região inteira. Ancorar, condicionar e testar a BATNA são negociação legítima; mentir é o fim da carreira local." },
    { pergunta: "Numa negociação sem sobreposição entre o seu piso e o máximo que o cliente pagaria (sem ZOPA), o que fazer?", opcoes: [
      "Pedir ao gerente para baixar o piso, porque uma venda com margem menor é melhor do que nenhuma venda",
      "Voltar ao diagnóstico do valor: o problema é gap mal quantificado ou decisor errado, não preço",
      "Igualar a condição do concorrente, porque sem sobreposição a única forma de fechar é pelo preço dele",
      "Encerrar a negociação e não voltar, porque cliente sem ZOPA não compra e consome tempo de follow-up",
    ], correta: 1, explicacao: "Sem ZOPA, técnica de negociação só sangra margem. O valor percebido está baixo: refaça a conta do gap com o cliente, cheque o comprador econômico, teste a BATNA dele. Se ainda assim não houver ZOPA, encerre com data e gatilho." },
    { pergunta: "Qual é a função da carência no financiamento como ferramenta de fechamento?", opcoes: [
      "Reduzir o preço total da máquina, porque as parcelas em carência não acumulam juros e o custo final cai",
      "Permitir que a máquina produza meses antes da primeira parcela, resolvendo 'não cabe agora' a custo zero para a concessionária",
      "Compensar uma avaliação baixa da usada, dando ao cliente fôlego de caixa equivalente à diferença de valor",
      "Substituir a garantia de fábrica nos primeiros meses, porque a máquina roda antes de o cliente começar a pagar",
    ], correta: 1, explicacao: "Seis meses de carência podem significar R$ 50 mil de economia acumulada na conta do gap antes de pagar a primeira parcela. É estrutura do banco, não custo seu, e resolve mais que desconto para quem tem obra começando." },
    { pergunta: "Qual é o quarto passo diante de uma tática dura, depois de reconhecer, não reagir e nomear com elegância?", opcoes: [
      "Ceder um pouco para mostrar boa vontade e desarmar a tática com generosidade",
      "Encerrar a reunião e retomar em outro dia, quando a pressão tiver diminuído",
      "Voltar ao critério objetivo: tabela, TCO, mercado, acordo já feito",
      "Usar a mesma tática de volta, para o cliente perceber que você conhece o jogo",
    ], correta: 2, explicacao: "Critério objetivo (Fisher & Ury) é o terreno onde a tática não funciona: 'a avaliação é 260 porque as duas últimas vendas na região foram 245 e 265'. Ceder recompensa a tática; retaliar vira briga; encerrar perde a venda." },
    { pergunta: "Por que 'dizer que é o limite e ceder depois' é o pior erro de concessão?", opcoes: [
      "Porque custa margem em uma venda que já estava fechada e o desconto extra não gera nenhuma contrapartida",
      "Porque o gerente reprova concessões feitas depois do limite declarado e o vendedor perde autonomia",
      "Porque a palavra do vendedor perde valor com aquele cliente para sempre, e todo limite futuro será testado nas próximas compras",
      "Porque o cliente conta aos vizinhos que o 'limite' cede sob pressão, e a região inteira passa a pressionar",
    ], correta: 2, explicacao: "O custo em margem é pequeno; o custo em credibilidade é permanente. Cliente de máquina compra várias vezes ao longo dos anos, e cada negociação futura começará do 'limite' que você não sustentou." },
  ],
};
