import type { Modulo } from "./tipos";

export const M6: Modulo = {
  id: "m6", nivel: 6, titulo: "Apresentação de valor e demonstração", tema: "Valor", cor: "#ff9f43",
  descricao: "Como apresentar a máquina certa, montar a proposta que vende sozinha, comparar com a concorrência com ética, usar a demonstração e vender compactação como especialista.",
  objetivos: [
    "Montar uma proposta de uma página com retorno em reais e validade real.",
    "Comparar com Caterpillar, Komatsu, JCB, Case, Volvo, XCMG e Sany sem depreciar.",
    "Planejar e conduzir uma demonstração que termina em fechamento.",
    "Fazer uma apresentação presencial de 15 minutos com estrutura de alto impacto.",
    "Montar e apresentar o custo total de propriedade (TCO) de 5 anos.",
    "Vender rolos Dynapac como consultor técnico de compactação.",
  ],
  leituras: [
    "Matthew Dixon — A Venda Desafiadora (ensinar, personalizar, assumir o controle).",
    "Oren Klaff — Pitch Anything (estrutura de apresentação).",
    "Dynapac — Compaction and Paving Handbook (referência de compactação).",
  ],
  aulas: [
    {
      id: "m6a1", titulo: "A proposta que vende sozinha", minutos: 10,
      resumo: "Proposta não é lista de preço. É o resumo do diagnóstico, o retorno em reais e a condição — em uma página que o sócio entende sem você.",
      blocos: [
        { tipo: "lista", titulo: "Estrutura da proposta (nesta ordem)", itens: [
          "1. O problema dele, nas palavras dele: “Retro de 2011 parando 3 dias/mês, aluguel de R$ 3.300/mês, manutenção de R$ 38 mil/ano.”",
          "2. A solução: modelo, configuração, por que essa máquina para essa aplicação (2 linhas).",
          "3. O retorno em reais: custo por hora atual x novo; ganho mensal; em quantos meses se paga.",
          "4. A condição: valor, entrada (usada), parcela, prazo, carência, entrega, garantia, treinamento.",
          "5. Prova: 1 caso de cliente parecido, com número.",
          "6. Validade real e próximo passo com data.",
        ] },
        { tipo: "p", titulo: "Erros que matam proposta", texto: "Começar pelo preço; enviar só a ficha técnica; mandar PDF genérico da fábrica; sem validade (o cliente deixa para depois); sem o retorno em reais (vira comparação de preço). Envie sempre com uma mensagem pessoal e marque a hora de revisar juntos — proposta enviada sem conversa marcada tem metade da chance." },
        { tipo: "tabela", titulo: "Modelo de página única", colunas: ["Bloco", "Conteúdo (exemplo)"], linhas: [
          ["Título", "Proposta de renovação — Retroescavadeira B95C — Construtora Fulano — 12/09"],
          ["Situação atual", "Retro 2011, 9.800 h, R$ 3.300/mês de aluguel para cobrir paradas, R$ 38 mil/ano de manutenção"],
          ["Solução", "B95C 4x4, caçamba 4 em 1, braço extensível. Atende vala, carregamento e nivelamento do loteamento."],
          ["Retorno", "Custo/hora: R$ 141 → R$ 118. Economia estimada: R$ 8.200/mês. Investimento se paga em ~4 anos, com máquina valendo ~55% ao fim."],
          ["Condição", "R$ 4xx mil. Usada avaliada em R$ 95 mil na entrada. Saldo em 60x de R$ x.xxx (Finame), carência 90 dias. Entrega 15 dias. Garantia 12 meses. Treinamento do operador incluso."],
          ["Prova", "Construtora X (Cachoeiro) trocou em 2025 e zerou aluguel: R$ 40 mil/ano."],
          ["Validade / próximo passo", "Válida até 30/09 (campanha de taxa). Revisão juntos: quinta 10h, com o Sr. Beltrano (sócio)."],
        ] },
        { tipo: "destaque", titulo: "Validade real", texto: "Toda proposta com validade curta e verdadeira (tabela, estoque, condição do banco). Sem validade não há urgência; com validade falsa não há confiança." },
        { tipo: "script", titulo: "Mensagem que acompanha a proposta", itens: [
          "“Fulano, segue a proposta em uma página, com a conta que fizemos na obra (aluguel + manutenção + diesel). O detalhe técnico vai em anexo pro seu engenheiro. A condição de taxa vale até dia 30. Quinta às 10h a gente revisa junto com o Beltrano? Assim vocês decidem com a mesma informação.”",
        ] },
        { tipo: "erros", titulo: "Erros comuns", itens: [
          "Proposta com 10 páginas e o preço na página 8.",
          "Mandar sem marcar a revisão. O cliente lê sozinho, entende errado, compara com a chinesa.",
          "Deixar de incluir a usada na entrada quando ela existe. A parcela parece maior do que é.",
          "Prometer prazo de entrega sem confirmar com a concessionária.",
        ] },
      ],
      missao: "Refaça a sua última proposta enviada no formato de uma página. Envie de novo ao cliente com a mensagem modelo e a reunião marcada. Registre no CRM.",
      quiz: [
        { pergunta: "O que vem primeiro na proposta?", opcoes: ["O preço", "O problema do cliente nas palavras dele", "A ficha técnica"], correta: 1, explicacao: "O cliente precisa se ver na proposta antes de ver o número." },
        { pergunta: "Proposta enviada sem reunião marcada:", opcoes: ["É normal", "Tem metade da chance — o cliente lê sozinho e compara preço", "É melhor, dá tempo pra ele pensar"], correta: 1, explicacao: "Sem você, a proposta vira lista de preço." },
      ],
    },
    {
      id: "m6a2", titulo: "Comparando com a concorrência sem depreciar", minutos: 11,
      resumo: "Cat, Komatsu, Volvo, JCB, Case, XCMG, Sany: pontos fortes reais de cada um e como posicionar New Holland e Dynapac com respeito e vantagem.",
      blocos: [
        { tipo: "p", texto: "Falar mal do concorrente faz o cliente defender o concorrente. Reconhecer o ponto forte dele e mudar o critério de comparação faz o cliente confiar em você. O comparativo do CRM tem os dados; aqui está a postura." },
        { tipo: "tabela", titulo: "Concorrentes: reconhecer e reposicionar", colunas: ["Concorrente", "Ponto forte reconhecido", "Onde New Holland/Dynapac ganha", "Como dizer"], linhas: [
          ["Caterpillar", "Marca forte, revenda alta, rede", "Preço de entrada, custo de peças, proximidade da assistência na região", "“A Cat é excelente. A diferença de preço e de peça, num ciclo de 5 anos, paga um implemento. E a assistência aqui do lado é nossa.”"],
          ["Komatsu", "Escavadeira robusta, tecnologia", "Preço, rede local, disponibilidade de peça no interior", "“Komatsu é forte em escavadeira grande. Na sua classe, a E215C entrega o mesmo ciclo com peça em Cachoeiro em 24 h.”"],
          ["JCB", "Retro tradicional, muito conhecida", "Consumo, conforto de cabine, condição de financiamento, rede", "“A JCB é uma referência em retro. Compare consumo por hora e o pacote de garantia — a conta de 5 anos decide.”"],
          ["Case", "Mesmo grupo (CNH), qualidade equivalente", "Atendimento local, campanhas, o vendedor (você)", "“Case e New Holland são irmãs de fábrica. A diferença é quem vai cuidar de você depois — e a condição de hoje.”"],
          ["Volvo", "Conforto, segurança, escavadeira premium", "Preço, custo de peça, simplicidade de manutenção no campo", "“Volvo é premium. Pra sua operação, a E215C entrega a produção com custo de propriedade menor.”"],
          ["XCMG / Sany (chinesas)", "Preço de entrada baixo, financiamento agressivo", "Revenda, assistência, peça, consumo, histórico na região, valor em 5 anos", "“O preço de entrada é menor mesmo. Vamos olhar os 5 anos: revenda, parada por peça, consumo. Na maioria dos casos a diferença some no segundo ano.”"],
        ] },
        { tipo: "lista", titulo: "Argumentos por concorrente (com ética)", itens: [
          "Nunca diga que o concorrente é ruim. Diga onde a sua é melhor para aquela aplicação e deixe a conta falar.",
          "Mude o critério: de preço para custo por hora, de potência para produção, de marca para assistência local.",
          "Use o comparativo do CRM (dados verificados). Não invente dado do concorrente.",
          "Traga prova local: cliente da região que trocou e por quê.",
          "Peça igualdade: “compare de igual para igual: mesma configuração, mesmo prazo, mesma garantia”.",
        ] },
        { tipo: "script", titulo: "Quando o cliente diz “a marca X é melhor”", itens: [
          "“Pode ser — em que ponto você acha ela melhor? [ouça] Entendo. Nesse ponto ela é forte mesmo. Posso te mostrar como fica a comparação no custo por hora e na assistência aqui na região? Aí você decide com os dois lados.”",
          "“A chinesa tem financiamento agressivo, verdade. Faz o seguinte: pega a proposta deles e a minha e compara revenda em 5 anos, prazo de peça e consumo. Se a deles fechar melhor, eu te digo.”",
        ] },
        { tipo: "caso", titulo: "Caso: a Cat que virou New Holland", situacao: "Pedreira em Cachoeiro tinha frota Cat e “não trocava de marca”.", acao: "O vendedor reconheceu a Cat, pediu para comparar apenas o custo de peças de maior giro e o prazo de atendimento da assistência na região. Levou o mecânico da concessionária para a visita.", resultado: "Primeira E215C entrou como “teste” ao lado das Cat. Dois anos depois, 3 New Holland na frota.", licao: "Não peça para o cliente trocar de marca. Peça para comparar um item de cada vez." },
      ],
      missao: "Abra o Comparativo do CRM e prepare o argumento de 3 frases para cada um dos 3 concorrentes que mais aparecem nas suas negociações. Registre no CRM qual concorrente está em cada negociação aberta.",
      quiz: [
        { pergunta: "Cliente diz que a Caterpillar é melhor. Você:", opcoes: ["Diz que a Cat é cara e ultrapassada", "Reconhece o ponto forte e propõe comparar custo por hora e assistência local", "Muda de assunto"], correta: 1, explicacao: "Reconhecer e reposicionar. Depreciar faz o cliente defender o concorrente." },
        { pergunta: "Contra a chinesa mais barata, o argumento central é:", opcoes: ["Ela é ruim", "A conta de 5 anos: revenda, peça, consumo, parada", "Desconto"], correta: 1, explicacao: "Custo total de propriedade. Deixe a conta falar." },
      ],
    },
    {
      id: "m6a3", titulo: "Demonstração e entrega técnica como ferramenta de venda", minutos: 9,
      resumo: "A máquina trabalhando na obra do cliente vende mais que qualquer argumento. Planeje a demonstração para terminar em fechamento.",
      blocos: [
        { tipo: "lista", titulo: "Roteiro da demonstração", itens: [
          "Combine o serviço real que ele faz (não uma “voltinha”): carregar caminhão, abrir vala, acabar um trecho de estrada, compactar uma camada.",
          "Operador dele na cabine, com você orientando. Ele precisa sentir a máquina.",
          "Meça algo: caçambas por hora, tempo de ciclo, consumo em 1 hora, passadas até o grau. Anote na frente do cliente.",
          "Compare com a máquina atual dele (que está ali do lado).",
          "Chame o comitê: sócio, operador, encarregado. Todos veem ao mesmo tempo.",
          "Encerre com pergunta de fechamento: “Você viu o que ela faz. O que falta pra ela ficar aqui?”.",
        ] },
        { tipo: "checklist", titulo: "Antes da demonstração", itens: [
          "Cliente qualificado (BANT) — demonstração é para quem pode fechar.",
          "Serviço e local definidos com o cliente; máquina atual disponível para comparar.",
          "Máquina certa para a aplicação (não a que está no pátio).",
          "Transporte, seguro e operador de apoio confirmados.",
          "Comitê convidado (sócio, operador).",
          "Proposta pronta no carro, com os números da demonstração em branco para preencher.",
        ] },
        { tipo: "p", titulo: "Entrega técnica", texto: "Depois da venda, a entrega técnica (treinamento do operador, revisão dos itens de manutenção, contato de assistência) é o primeiro passo do pós-venda e a maior fonte de indicação. Tire foto com a equipe. Registre no Pós-venda do CRM que foi feita; cliente bem entregue indica vizinho." },
        { tipo: "caso", titulo: "Caso: 6 caçambas contra 9", situacao: "Pedreira em Vargem Alta hesitava entre a E215C e manter a escavadeira antiga.", acao: "Demonstração com o operador deles: o vendedor cronometrou o carregamento de 5 caminhões. A antiga: 9 caçambas, 6 min. A E215C: 6 caçambas, 3,5 min.", resultado: "O dono fez a conta de caminhões a mais por dia na hora. Fechou antes de a máquina sair da pedreira.", licao: "Número medido na frente do cliente é o argumento mais forte que existe." },
      ],
      missao: "Agende uma demonstração real na obra de um cliente qualificado. Meça produtividade na frente dele, chame o comitê, e termine com a pergunta de fechamento. Registre o número medido no CRM.",
      quiz: [
        { pergunta: "Como terminar uma demonstração?", opcoes: ["Agradecendo e indo embora", "Com uma pergunta de fechamento", "Entregando o catálogo"], correta: 1, explicacao: "O pico de desejo é ali. Pergunte o que falta para a máquina ficar." },
        { pergunta: "Demonstração é para:", opcoes: ["Qualquer interessado", "Cliente qualificado, com o comitê presente e serviço real", "Feira"], correta: 1, explicacao: "Demonstração custa. Use para fechar, não para entreter." },
      ],
    },
    {
      id: "m6a4", titulo: "A apresentação presencial de 15 minutos", minutos: 10,
      resumo: "Reunião com o dono e o sócio: estrutura, ordem, o que mostrar e o que não mostrar para sair com decisão.",
      blocos: [
        { tipo: "p", texto: "A atenção de um dono de empresa dura 15 minutos. Depois disso, ele está pensando na obra. Uma apresentação de valor precisa de estrutura: abrir com a dor dele, mostrar a solução com uma imagem, provar com um número, pedir a decisão. Sem slide de história da empresa. Sem 40 páginas." },
        { tipo: "tabela", titulo: "Estrutura de 15 minutos", colunas: ["Minuto", "Bloco", "Conteúdo"], linhas: [
          ["0–2", "Abertura", "Recapitule o diagnóstico nas palavras dele: “você me disse que a retro para 3 dias por mês e você aluga pra cobrir”. Ele confirma. Combine o objetivo: “no fim, quero que você decida se faz sentido”."],
          ["2–5", "A dor em reais", "A conta de custo por hora com os números dele. Uma folha. Deixe ele conferir."],
          ["5–9", "A solução", "A máquina certa e por quê (3 razões ligadas à dor). Vídeo de 40 s dela trabalhando em aplicação igual. Imagem: “segunda-feira ela chega aqui e…”."],
          ["9–11", "Prova", "Um caso de cliente parecido com número. Foto. Se tiver o telefone com permissão, ofereça."],
          ["11–13", "Condição", "Uma página: valor, usada, parcela, carência, entrega, garantia. Compare a parcela com o ganho mensal."],
          ["13–15", "Fechamento", "Resumo de valor + pergunta: “fazendo sentido, vamos reservar a unidade e mandar os documentos pro banco hoje?” Silêncio."],
        ] },
        { tipo: "lista", titulo: "Regras", itens: [
          "Sem laptop se puder evitar. Folha, tablet ou o celular com o vídeo. Olho no olho.",
          "Três razões, não dez. O cérebro guarda três.",
          "Cada dado ligado à dor dele. Dado solto é ruído.",
          "Deixe o cliente segurar a folha da conta. Posse física gera posse psicológica.",
          "Tenha as respostas às 3 objeções mais prováveis preparadas (módulo 7).",
          "Termine sempre com pergunta de fechamento e silêncio. Nunca com “qualquer coisa me chama”.",
        ] },
        { tipo: "erros", titulo: "Erros de apresentação", itens: [
          "Começar pela história da New Holland e da concessionária.",
          "Ler slides. Apresentação é conversa dirigida.",
          "Mostrar 4 modelos. Mostre o certo (e o de contraste, se for o caso).",
          "Falar da condição antes da conta de retorno.",
          "Passar de 20 minutos sem pedir a decisão.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte a sua apresentação de 15 minutos para a negociação mais quente do CRM seguindo a tabela. Cronometre em voz alta. Corte tudo o que passar de 15 minutos." },
      ],
      missao: "Faça a próxima apresentação de proposta com a estrutura de 15 minutos, com o comitê presente, e termine com a pergunta de fechamento. Registre no CRM a resposta exata do cliente.",
      quiz: [
        { pergunta: "Como abrir a apresentação?", opcoes: ["Com a história da empresa", "Recapitulando o diagnóstico nas palavras do cliente", "Com o preço"], correta: 1, explicacao: "O cliente precisa confirmar a dor antes de ver a solução." },
        { pergunta: "Quantas razões apresentar para a máquina?", opcoes: ["Todas da ficha", "Três, ligadas à dor dele", "Uma"], correta: 1, explicacao: "Regra de 3: o cérebro guarda e repete para o sócio." },
      ],
    },
    {
      id: "m6a5", titulo: "Custo total de propriedade (TCO): a conta de 5 anos", minutos: 11,
      resumo: "Preço de entrada é 40% da história. Como montar o TCO com aquisição, combustível, manutenção, paradas, revenda — e apresentar para vencer a marca mais barata.",
      blocos: [
        { tipo: "p", texto: "O custo total de propriedade soma tudo o que a máquina custa do dia da compra ao dia da revenda. A marca mais barata na entrada costuma ser a mais cara no fim: consome mais, para mais, tem peça mais demorada e vale menos na revenda. Quem apresenta o TCO tira a conversa do preço e leva para o único número que importa: quanto custa por hora produzida ao longo da vida." },
        { tipo: "tabela", titulo: "TCO de 5 anos — escavadeira 21 t (exemplo ilustrativo, 2.000 h/ano)", colunas: ["Item", "New Holland E215C", "Marca de entrada baixa"], linhas: [
          ["Aquisição", "R$ 900 mil", "R$ 760 mil"],
          ["Combustível (5 anos)", "18 L/h × 10.000 h × R$ 6 = R$ 1.080 mil", "20 L/h × 10.000 h × R$ 6 = R$ 1.200 mil"],
          ["Manutenção e peças", "R$ 180 mil", "R$ 240 mil"],
          ["Paradas (dias × custo/dia)", "15 dias × R$ 4 mil = R$ 60 mil", "45 dias × R$ 4 mil = R$ 180 mil"],
          ["Revenda ao fim (entra como crédito)", "− R$ 450 mil (50%)", "− R$ 230 mil (30%)"],
          ["Custo total 5 anos", "R$ 1.770 mil", "R$ 2.150 mil"],
          ["Custo por hora", "R$ 177/h", "R$ 215/h"],
        ] },
        { tipo: "lista", titulo: "Como montar com os números do cliente", itens: [
          "Horas por ano: pergunte ou tire do horímetro da atual.",
          "Consumo: ficha do CRM para a nova; medição do cliente para a atual ou a concorrente (peça a ele).",
          "Manutenção: histórico dele para a atual; plano de revisões para a nova.",
          "Paradas: dias parados no último ano (ele sabe) × custo por dia (aluguel + operador + atraso).",
          "Revenda: valores de mercado de usadas (o Máquinas Usadas do CRM ajuda) por marca e idade.",
          "Financiamento: inclua juros se for comparar à vista x financiado; senão, compare o ativo.",
        ] },
        { tipo: "script", titulo: "Apresentando o TCO", itens: [
          "“Fulano, a chinesa é R$ 140 mil mais barata hoje. Mas olha a linha de baixo: em 5 anos, entre diesel, parada e revenda, ela custa R$ 380 mil a mais. Ou seja, o desconto de hoje custa R$ 76 mil por ano. Você prefere economizar hoje ou nos 5 anos?”",
        ] },
        { tipo: "destaque", titulo: "Honestidade nos números", texto: "Use dados verificáveis e diga quando é estimativa. Se o cliente pegar um número inflado, o TCO inteiro perde a credibilidade. Melhor um TCO conservador que vence por R$ 200 mil do que um agressivo que ele não acredita." },
        { tipo: "caso", titulo: "Caso: o TCO que a esposa aprovou", situacao: "Empreiteiro queria a New Holland; a esposa (financeiro) achava a chinesa “muito mais em conta”.", acao: "O vendedor montou o TCO conservador com os números deles (horas, diesel, dias parados da máquina atual) e apresentou para os dois.", resultado: "Ela viu que a diferença de entrada voltava em 2 anos e que a revenda protegia o patrimônio. Aprovou a New Holland.", licao: "TCO é a linguagem de quem cuida do caixa." },
      ],
      missao: "Monte o TCO de 5 anos para uma negociação em que o concorrente é uma marca de entrada baixa. Use os números do cliente e apresente para quem cuida do financeiro. Registre no CRM.",
      quiz: [
        { pergunta: "O que o TCO inclui além do preço de compra?", opcoes: ["Só combustível", "Combustível, manutenção, paradas e revenda ao longo da vida", "Só a parcela"], correta: 1, explicacao: "Tudo o que a máquina custa até a revenda." },
        { pergunta: "Por que usar números conservadores no TCO?", opcoes: ["Para perder a comparação", "Para manter a credibilidade — um número inflado derruba a conta inteira", "Não importa"], correta: 1, explicacao: "Credibilidade vale mais que uma diferença maior." },
      ],
    },
    {
      id: "m6a6", titulo: "Vendendo Dynapac: compactação como venda técnica", minutos: 12,
      resumo: "Rolo não se vende por peso. Se vende por energia de compactação, tipo de solo, número de passadas, grau de compactação e o ensaio que o fiscal aprova.",
      blocos: [
        { tipo: "p", texto: "O cliente de pavimentação e terraplenagem vive de ensaio aprovado: se a compactação não atinge o grau exigido (geralmente 95–100% do Proctor), o fiscal reprova, o trecho é refeito e o prazo estoura. Quem entende de compactação vende o rolo certo e vira o consultor da empreiteira. Quem vende “rolo de 10 toneladas” compete por preço." },
        { tipo: "lista", titulo: "Conceitos que você precisa dominar", itens: [
          "Tipo de solo: granular (areia, saibro, brita) compacta por vibração; coesivo (argila, silte) compacta por amassamento e impacto (pé-de-carneiro).",
          "Amplitude e frequência: amplitude alta para camadas espessas e solo grosso; baixa para acabamento e camadas finas. Dupla amplitude é argumento.",
          "Energia de compactação: peso estático + força centrífuga. Mais energia = menos passadas = menos hora-máquina e diesel.",
          "Espessura da camada: cada rolo tem espessura máxima eficiente; camada grossa demais não compacta embaixo.",
          "Umidade ótima: solo seco ou encharcado não compacta. Oriente o cliente — ele te vê como técnico.",
          "Grau de compactação e ensaios: Proctor, frasco de areia, densímetro. Rolos com medidor de compactação mostram o resultado na cabine e reduzem ensaios reprovados.",
          "Asfalto: rolagem de ruptura, intermediária e acabamento; temperatura da massa; tandem CC1200/CC2200 e pneumático.",
        ] },
        { tipo: "tabela", titulo: "Argumento por cliente", colunas: ["Cliente", "Dor", "Rolo", "Argumento"], linhas: [
          ["Empreiteira de terraplenagem", "Ensaio reprovado, retrabalho, prazo", "CA2500 / CA3500 (liso ou padfoot)", "“Menos passadas, grau atingido e comprovado na cabine. Retrabalho zero é prazo e margem.”"],
          ["Pavimentação urbana", "Acabamento com marca, trinca precoce", "CC1200 / CC2200 tandem", "“Acabamento sem marca e capa que não trinca em 6 meses. A prefeitura aceita na primeira medição.”"],
          ["Prefeitura (estradas vicinais)", "Estrada que vira lama na chuva", "CA1500 + motoniveladora", "“Estrada compactada dura o inverno. Menos patrolamento, menos reclamação.”"],
          ["Locadora", "Retorno por hora, revenda", "CA1500 / CA2500", "“Rolo que mais gira em locação, com revenda forte e peça na região.”"],
          ["Pedreira / aterro industrial", "Camadas espessas de rejeito", "CA3500 / CA4000 padfoot", "“Energia pra camada grossa e produção por hora.”"],
        ] },
        { tipo: "script", titulo: "Vendendo como técnico", itens: [
          "“Qual é o solo da base? Argiloso? Então rolo liso vai deixar borrachudo e o fiscal reprova. Você precisa de pé-de-carneiro na base e tandem na capa. Deixa eu te mostrar quantas passadas o CA2500 leva pra atingir 100% do Proctor numa camada de 30 cm.”",
          "“Com o medidor de compactação, o operador vê na tela quando a camada chegou. Menos ensaio, menos parada esperando o laboratório, menos discussão com o fiscal.”",
        ] },
        { tipo: "caso", titulo: "Caso: as 12 passadas", situacao: "Empreiteira em Anchieta compactava base com rolo antigo em 12 passadas e ainda reprovava 1 em 4 ensaios.", acao: "Demonstração do CA2500 na mesma camada: 6 passadas, ensaio aprovado, com o laboratório da obra medindo.", resultado: "Metade da hora-máquina e diesel por trecho. Fechou o CA2500 e, no ano seguinte, o CC2200 para asfalto.", licao: "Compactação se prova com ensaio na frente do fiscal. Leve o laboratório para a demonstração." },
      ],
      missao: "Estude a ficha técnica dos rolos Dynapac no CRM (amplitude, frequência, força centrífuga, espessura de camada) e prepare o argumento técnico para os 2 clientes de pavimentação/terraplenagem mais próximos. Agende uma visita técnica com o laboratorista da obra.",
      quiz: [
        { pergunta: "Base argilosa. Qual rolo?", opcoes: ["Liso vibratório", "Pé-de-carneiro (padfoot)", "Pneumático"], correta: 1, explicacao: "Solo coesivo compacta por amassamento e impacto." },
        { pergunta: "Qual é o argumento mais forte para a empreiteira de terraplenagem?", opcoes: ["Peso do rolo", "Menos passadas e grau de compactação comprovado — retrabalho zero", "Cor"], correta: 1, explicacao: "Ensaio aprovado é prazo, margem e paz com o fiscal." },
        { pergunta: "Para acabamento de capa asfáltica você indica:", opcoes: ["CA3500 padfoot", "Tandem CC1200/CC2200", "Motoniveladora"], correta: 1, explicacao: "Tandem liso para asfalto; padfoot é para solo coesivo." },
      ],
    },
  ],
  prova: [
    { pergunta: "A proposta de uma página começa com:", opcoes: ["Preço", "O problema do cliente nas palavras dele", "A história da marca"], correta: 1, explicacao: "Diagnóstico → solução → retorno → condição → prova → validade." },
    { pergunta: "Contra a Caterpillar, o critério que você muda a comparação para:", opcoes: ["Marca", "Custo de peça, preço de entrada e assistência local", "Cor"], correta: 1, explicacao: "Reconheça o forte, mude o critério." },
    { pergunta: "A demonstração termina com:", opcoes: ["Catálogo", "Pergunta de fechamento", "Convite para almoço"], correta: 1, explicacao: "Pico de desejo é para fechar." },
    { pergunta: "Na apresentação de 15 minutos, a condição comercial vem:", opcoes: ["No início", "Depois da conta de retorno e da prova", "Nunca"], correta: 1, explicacao: "Valor antes do preço." },
    { pergunta: "No TCO, o que costuma virar a comparação a favor da New Holland?", opcoes: ["Só o preço", "Consumo, paradas e revenda ao longo de 5 anos", "A parcela"], correta: 1, explicacao: "Custo por hora produzida ao longo da vida." },
    { pergunta: "Rolo com medidor de compactação vende porque:", opcoes: ["É mais pesado", "Mostra o grau na cabine e reduz ensaio reprovado", "É mais bonito"], correta: 1, explicacao: "Menos retrabalho e menos discussão com o fiscal." },
  ],
};
