import type { Modulo } from "./tipos";

export const M7: Modulo = {
  id: "m7", nivel: 7, titulo: "Objeções", tema: "Resistência", cor: "#ff5c7a",
  descricao: "Objeção não é rejeição: é o cliente pedindo ajuda para decidir. O método LAER-C para qualquer objeção, e as respostas trabalhadas para as seis que aparecem toda semana no seu mercado: preço e 'a chinesa', timing, confiança e marca, crédito e 'vou alugar', o 'vou pensar' por WhatsApp e o sumiço.",
  objetivos: [
    "Aplicar o método LAER-C (ouvir, reconhecer, explorar, responder, confirmar) a qualquer objeção sem discutir.",
    "Distinguir objeção real de cortina de fumaça e isolar a que decide.",
    "Responder a 'está caro' e 'a chinesa é mais barata' com TCO, custo da inação e prova, sem depreciar.",
    "Tratar 'não é o momento' e 'depois da safra/obra' com o custo de esperar e um plano com data.",
    "Construir confiança quando a objeção é 'não conheço a marca/assistência' ou 'já fui queimado'.",
    "Resolver 'o banco não aprova', 'não tenho caixa' e 'vou alugar' com estrutura e conta.",
    "Reabrir o 'vou pensar' e o sumiço por WhatsApp sem parecer cobrança.",
  ],
  leituras: [
    "Jeb Blount — Objections: a ciência e a arte de superar o 'não' (o método de prevenção e resposta).",
    "Neil Rackham — SPIN Selling, capítulo sobre prevenção de objeções: a maioria delas é criada pelo vendedor que apresentou cedo.",
    "Chris Voss — Negocie como se sua vida dependesse disso: rótulos e o 'não' como início.",
    "Keenan — Gap Selling: objeção como sintoma de gap mal quantificado.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m7a1", titulo: "LAER-C: o método para qualquer objeção", minutos: 14,
      resumo: "Ouvir até o fim, reconhecer sem concordar, explorar para achar a objeção real, responder com prova e confirmar se resolveu. Cinco passos que substituem o reflexo de rebater — e que funcionam para preço, prazo, marca, crédito e 'vou pensar'.",
      blocos: [
        { tipo: "p", texto: "Rackham descobriu, nas 35 mil visitas, que a maioria das objeções é criada pelo próprio vendedor: ele apresenta a solução antes de o cliente sentir o problema, e o cliente reage com 'está caro' ou 'não preciso'. A prevenção é o diagnóstico bem feito (Módulo 4). Mas mesmo com o melhor diagnóstico, objeções aparecem — e o reflexo de rebater ('mas a nossa máquina…') transforma a conversa em disputa. O LAER-C é a alternativa: um método que respeita o cliente, encontra a objeção real e responde a ela, não à frase que ele disse." },
        { tipo: "framework", nome: "LAER-C", origem: "Síntese de Listen-Acknowledge-Explore-Respond (Carew International) com a confirmação da venda consultiva", passos: [
          "L — Ouvir (Listen): até o fim, sem interromper, com o corpo (caderno, olho). Anote as palavras exatas. Muitas objeções se dissolvem enquanto o cliente as explica.",
          "A — Reconhecer (Acknowledge): valide sem concordar. 'Faz sentido você olhar isso com cuidado', 'É uma preocupação justa'. Nunca 'entendo, mas…' — o 'mas' apaga o 'entendo'.",
          "E — Explorar (Explore): descubra o que está por trás. 'Quando você diz caro, é em relação a quê?' 'O que precisaria acontecer para o prazo funcionar?' 'Além disso, tem mais alguma coisa?' Aqui você isola a objeção real.",
          "R — Responder (Respond): só agora, e só à objeção real, com prova: conta, referência, demo, documento, estrutura. Curto.",
          "C — Confirmar (Confirm): 'Isso resolve a questão do prazo pra você?' Se sim, avance ao próximo passo. Se não, volte ao E: há outra objeção por trás.",
        ] },
        { tipo: "tabela", titulo: "Objeção real × cortina de fumaça", colunas: ["O cliente diz", "Pode ser real se…", "Pode ser cortina se…", "Como isolar"], linhas: [
          ["'Está caro'", "Ele comparou com outra proposta igual ou o gap não fecha", "Ele não viu a conta ou tem medo de pagar mais que o vizinho", "'Se o valor fosse resolvido, fecharíamos?'"],
          ["'Vou pensar'", "Há um decisor ausente ou uma informação faltando", "Ele não quer dizer 'não' na sua cara", "'O que exatamente você precisa pensar? Me ajuda a entender'"],
          ["'Não é o momento'", "Obra ou safra ainda não começou; caixa real", "Ele não sentiu o custo de esperar", "'O que muda daqui a 3 meses?'"],
          ["'Preciso ver com meu sócio'", "O sócio decide de verdade", "Ele quer sair da reunião", "'Vamos marcar com o seu sócio? Quinta?'"],
          ["'Já tenho fornecedor'", "Relação antiga e satisfatória", "Ele não quer o trabalho de comparar", "'O que o fornecedor atual faz que você não abriria mão?'"],
        ] },
        { tipo: "dialogo", titulo: "LAER-C em 90 segundos", falas: [
          { quem: "cliente", texto: "Olha, gostei da máquina, mas a proposta ficou acima do que eu esperava. Não sei se vale a diferença." },
          { quem: "vendedor", texto: "(ouve até o fim, anota) Faz sentido olhar a diferença com cuidado; é muito dinheiro." },
          { quem: "nota", texto: "L e A. Sem 'mas'." },
          { quem: "vendedor", texto: "Quando você diz acima do esperado: é em relação a outra proposta que você tem, ou ao que você tinha na cabeça antes de a gente fazer a conta?" },
          { quem: "cliente", texto: "Ao que eu tinha na cabeça. Eu pensava em 700 e ficou 820." },
          { quem: "vendedor", texto: "E além dessa diferença, tem mais alguma coisa que pesa?" },
          { quem: "cliente", texto: "Não, é isso." },
          { quem: "nota", texto: "E: a objeção é a âncora mental de 700, não outra proposta. Isolada." },
          { quem: "vendedor", texto: "Então deixa eu voltar num número que a gente fez juntos: a diferença de 120 mil, com os R$ 8.800 por mês que a máquina economiza, se paga em 14 meses — e você fica com a máquina por 10 anos. O 700 que você tinha na cabeça era da máquina sem a caçamba de rocha e sem cabine climatizada, que a sua pedreira precisa. Isso resolve a dúvida do 'vale a diferença'?" },
          { quem: "cliente", texto: "Resolve. Vamos ver a parcela então." },
          { quem: "nota", texto: "R com prova (conta feita antes) e C. A conversa avança." },
        ] },
        { tipo: "caso", titulo: "Caso: a objeção respondida errada três vezes", situacao: "Cliente disse 'está caro'. O vendedor respondeu com a lista de diferenciais. O cliente repetiu. O vendedor ofereceu desconto. O cliente disse 'vou pensar'. Perdeu.", acao: "No win/loss, descobriu-se que o 'caro' era medo de o sócio (que não estava na visita) reprovar: o cliente queria material para convencê-lo. Nenhum diferencial nem desconto resolvia isso.", resultado: "O vendedor adotou o E antes do R: 'caro em relação a quê?', 'tem mais alguma coisa?'. Nos três meses seguintes, dois 'está caro' viraram 'preciso mostrar pro meu sócio' e foram fechados com a folha de uma página e a reunião com o sócio.", licao: "Responder à frase em vez de à objeção é como dar remédio para o sintoma errado. O E é o diagnóstico da objeção." },
        { tipo: "script", titulo: "Frases de cada passo", itens: [
          "A: 'É uma preocupação justa.' / 'Faz sentido você olhar isso.' / 'Muita gente na sua situação pergunta isso.'",
          "E: 'Em relação a quê?' / 'O que precisaria acontecer para funcionar?' / 'Além disso, tem mais alguma coisa?' / 'Se isso fosse resolvido, a gente avançaria?'",
          "R: 'Deixa eu te mostrar um número que a gente fez juntos…' / 'O Marcos passou pela mesma dúvida; posso te contar o que ele viu?' / 'Tenho isso por escrito.'",
          "C: 'Isso resolve a questão pra você?' / 'Ficou claro ou ainda tem uma ponta solta?'",
        ] },
        { tipo: "erros", titulo: "Erros com objeções", itens: [
          "Interromper. A objeção mal dita cresce; a objeção ouvida até o fim encolhe.",
          "'Entendo, mas…'. O 'mas' anula o reconhecimento e sinaliza que você não ouviu.",
          "Responder antes de explorar. Você responde à frase e a objeção real fica intacta.",
          "Não confirmar. Você acha que resolveu; o cliente não. A objeção volta na assinatura.",
          "Tratar a objeção como ataque. Cliente que objeta está engajado; quem não objeta já decidiu não comprar.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Escreva as cinco objeções que você mais ouve. Para cada uma, redija o A (uma frase de reconhecimento sem 'mas'), três perguntas de E e a prova que você usaria no R. Ensaie em voz alta com um colega fazendo o cliente." },
      ],
      missao: "Nas próximas cinco objeções que ouvir (WhatsApp ou visita), aplique o LAER-C e registre no CRM: a frase do cliente, a objeção real descoberta no E, a prova usada no R e se o C confirmou. Compare com o seu reflexo anterior.",
      quiz: [
        { pergunta: "O cliente diz 'gostei da máquina, mas a proposta ficou acima do que eu esperava'. Qual é o passo correto imediatamente após ouvir até o fim?", opcoes: [
          "Apresentar os diferenciais que justificam o valor (assistência, consumo, revenda), porque ele gostou da máquina e falta convencer",
          "Perguntar quanto ele esperava pagar e oferecer chegar perto, porque a diferença entre expectativa e proposta é o que decide",
          "Explicar que o preço é de tabela para a configuração dele e que não há margem, para tirar a expectativa de desconto",
          "Reconhecer sem 'mas' ('faz sentido olhar com cuidado') e explorar: 'acima do esperado em relação a quê?'",
        ], correta: 3, explicacao: "Reconhecer valida sem concordar; explorar revela se é outra proposta, uma âncora mental ou medo do sócio. Só depois de isolar a objeção real a resposta faz sentido. Diferenciais, preço e negociação são respostas à frase, não à objeção." },
        { pergunta: "Por que 'entendo, mas…' é um erro no passo de reconhecimento?", opcoes: [
          "Porque 'entendo' é uma palavra informal demais para uma negociação de alto valor e soa condescendente",
          "Porque o 'mas' anula o reconhecimento e comunica que você não ouviu, só esperou a sua vez de falar",
          "Porque o cliente pode interpretar 'entendo' como concordância com a objeção e endurecer a posição",
          "Porque prolonga a conversa sem avançar, quando o cliente quer uma resposta objetiva à objeção que levantou",
        ], correta: 1, explicacao: "O cérebro do cliente apaga tudo antes do 'mas'. 'Entendo, mas' é o reflexo de rebater disfarçado. Reconhecimento verdadeiro é uma frase completa que valida ('é uma preocupação justa') seguida de uma pergunta, não de um contra-argumento." },
        { pergunta: "O cliente diz 'está caro' e, depois de explorar, você descobre que ele tem medo de o sócio reprovar. O que resolve essa objeção?", opcoes: [
          "Um desconto que o sócio aprove, apresentado como condição especial obtida para a empresa deles",
          "A lista completa de diferenciais da máquina, para o cliente ter argumentos técnicos ao conversar com o sócio",
          "Material de uma página para o sócio (gap × parcela, referência) e uma reunião com o sócio presente",
          "Explicar que o preço é o mesmo para todos os clientes e que o sócio pode confirmar com qualquer outro comprador",
        ], correta: 2, explicacao: "A objeção real é o ratificador ausente. Nenhum argumento para o cliente resolve o medo dele em relação ao sócio; o que resolve é equipá-lo (folha de uma página) e trazer o sócio para a mesa. Desconto e diferenciais tratam a frase, não a objeção." },
        { pergunta: "Qual é a função da pergunta 'além disso, tem mais alguma coisa?' no passo Explorar?", opcoes: [
          "Isolar a objeção: garantir que, resolvida esta, não haverá outra escondida atrás",
          "Mostrar ao cliente que você tem paciência e disposição para ouvir tudo o que ele tem a dizer",
          "Ganhar tempo para organizar a resposta enquanto o cliente reformula a objeção principal",
          "Levantar todas as objeções possíveis para tratá-las de uma vez e encerrar a fase de resistência",
        ], correta: 0, explicacao: "Se há duas objeções e você responde só à primeira, o cliente diz 'vou pensar'. Isolar ('se isso for resolvido, avançamos?') garante que a resposta vai para a objeção que decide, e o C confirma. Não é para levantar objeções novas: é para saber quais existem." },
        { pergunta: "Segundo Rackham, qual é a principal causa de objeções em vendas de alto valor?", opcoes: [
          "Preços acima do mercado, que obrigam o vendedor a justificar a diferença em toda negociação",
          "O vendedor apresentar a solução antes de o cliente sentir o tamanho do problema",
          "Concorrentes agressivos, que plantam dúvidas sobre assistência e revenda antes da visita",
          "Clientes indecisos por natureza, que usam objeções para adiar uma decisão que temem",
        ], correta: 1, explicacao: "A pesquisa mostrou que a apresentação precoce gera 'está caro' e 'não preciso' porque o valor ainda não foi construído. A melhor técnica de objeção é a prevenção: implicação e necessidade antes da solução (Módulo 4)." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m7a2", titulo: "'Está caro' e 'a chinesa é 100 mil mais barata'", minutos: 15,
      resumo: "A objeção mais frequente e a mais mal respondida. Preço se responde com custo total, custo da inação e prova — nunca com desconto reflexo, nunca depreciando a outra marca. E às vezes a resposta honesta é: para o seu caso, a mais barata serve.",
      blocos: [
        { tipo: "p", texto: "'Está caro' tem pelo menos cinco significados diferentes (Módulo 6): não viu o valor, comparou com outra proposta, medo de pagar mais que o vizinho, ritual de negociação, ou o gap não fecha. 'A chinesa é 100 mil mais barata' é a versão com concorrente: o cliente viu um número menor e quer saber por que pagaria mais. A resposta tem três camadas, na ordem: custo total de propriedade (a conta), custo da inação (o que ele já perde), prova (cliente que passou por isso, medição). Sem essas três, você está discutindo preço; com elas, está comparando investimentos." },
        { tipo: "conta", titulo: "'100 mil mais barata': o que a diferença compra e o que custa (retro, 5 anos, 1.800 h/ano)", linhas: [
          ["Diferença de preço a favor da concorrente", "R$ 100.000"],
          ["Consumo: 2 L/h a mais × 9.000 h × R$ 6,30", "− R$ 113.400"],
          ["Paradas: 2 dias/mês a mais × 60 meses × R$ 1.900 (aluguel + operador)", "− R$ 228.000"],
          ["Assistência a 140 km: deslocamento por chamado (R$ 900 × 12 chamados/ano × 5)", "− R$ 54.000"],
          ["Revenda em 5 anos: 50% de R$ 480 mil × 38% de R$ 380 mil", "− R$ 95.600"],
          ["Resultado líquido da 'economia' de R$ 100 mil", "− R$ 391.000"],
        ], conclusao: "Os R$ 100 mil de diferença se transformam em R$ 391 mil a mais de custo em 5 anos, com as premissas do cliente. A pergunta deixa de ser 'por que pagar 100 mil a mais?' e vira 'por que pagar 391 mil a mais para economizar 100 na entrada?'. Se as premissas do cliente (uso baixo, assistência perto, revenda irrelevante) mudarem a conta, diga: para esse caso, a mais barata pode servir." },
        { tipo: "framework", nome: "Três camadas de resposta a 'está caro'", origem: "Value selling aplicado a bens de capital (TCO, custo da inação, prova social)", passos: [
          "Camada 1 — TCO: 'Máquina se compara pelo custo total de 5 anos, não pelo preço. Posso te mostrar com os seus números?' A conta na tela, um número por vez, dele.",
          "Camada 2 — Custo da inação: 'E enquanto você decide, a máquina atual custa R$ X por mês em parada e diesel. Cada mês de dúvida é esse valor.'",
          "Camada 3 — Prova: 'O Roberto, da pedreira de Vargem Alta, comprou a mais barata em 2022. Posso te contar o que aconteceu e te passar o telefone dele.'",
          "Fechamento da objeção: 'Com isso, a diferença de preço ainda parece grande?' (C). Se sim, é caixa: vá para estrutura (usada, carência). Se não, avance.",
        ] },
        { tipo: "dialogo", titulo: "Sem depreciar a chinesa", falas: [
          { quem: "cliente", texto: "A XCMG é 100 mil mais barata. Cem mil! Você me dá um motivo pra não comprar ela?" },
          { quem: "vendedor", texto: "Cem mil é muito dinheiro, e a XCMG melhorou bastante nos últimos anos — não vou te dizer que é máquina ruim. O que eu posso te mostrar é o que esses 100 mil viram em 5 anos na sua obra. Posso fazer a conta com você? Ela roda 150 horas por mês, né?" },
          { quem: "nota", texto: "Reconhece o valor (100 mil é muito) e a concorrente (melhorou). Zero depreciação. Pede permissão para a conta e já pega o primeiro número dele." },
          { quem: "cliente", texto: "Isso. Faz aí." },
          { quem: "vendedor", texto: "(faz a conta na Calculadora, número a número) Deu isso: os 100 mil a menos viram 391 mil a mais em 5 anos, principalmente em parada e assistência. Agora, se a sua obra fosse de 50 horas por mês e o técnico deles ficasse aqui em Cachoeiro, a conta mudaria e eu te diria. O que esse número te diz?" },
          { quem: "cliente", texto: "Que eu tava olhando só a entrada." },
        ] },
        { tipo: "caso", titulo: "Caso: a resposta honesta que 'perdeu' a venda", situacao: "Produtor pequeno de Ibitirama queria uma retro para 40 horas por mês de serviço no sítio. Comparava a B95C com uma chinesa 90 mil mais barata.", acao: "O vendedor fez a conta: com 40 horas por mês, a diferença de consumo e paradas não pagava os 90 mil em 5 anos. Disse: 'para o seu uso, a mais barata serve; se você for prestar serviço para os vizinhos e passar de 120 horas, a conta vira'.", resultado: "O produtor comprou a chinesa. Dois anos depois, começou a prestar serviço, passou de 150 horas, a chinesa parou duas vezes na safra e ele comprou a B95C do mesmo vendedor, à vista, e indicou três vizinhos: 'esse aí me falou a verdade quando não tinha nada a ganhar'.", licao: "A conta honesta às vezes manda o cliente comprar do concorrente. Esse cliente volta e traz gente. O que finge que a conta fecha perde os dois." },
        { tipo: "tabela", titulo: "Respostas por significado de 'está caro'", colunas: ["Por trás", "Sinal", "Resposta"], linhas: [
          ["Não viu o valor", "Não houve conta junto; ele fala de 'preço' e não de 'parcela'", "Camada 1: TCO ao vivo"],
          ["Outra proposta na mesa", "Cita marca e número", "Compare configuração; camadas 1 e 3; teste a BATNA"],
          ["Medo do vizinho/ritual", "'Preciso de um desconto', sem justificar", "Transparência; concessão pequena condicionada (Módulo 6)"],
          ["Caixa", "Fala de 'parcela', 'agora', 'esse mês'", "Estrutura: usada, carência, prazo; não desconto"],
          ["Gap não fecha", "Uso baixo, sem sinal de crescimento", "Honestidade: usada, consórcio, ou a mais barata"],
        ] },
        { tipo: "erros", titulo: "Erros com 'está caro'", itens: [
          "Desconto reflexo. Confirma que estava caro e ancora a próxima compra.",
          "Depreciar a marca chinesa. O cliente que a considerou se sente ofendido, e muitas melhoraram de verdade.",
          "Conta com números seus. Um número errado e a conta inteira vira 'papo de vendedor'.",
          "Fingir que a conta fecha quando não fecha. O cliente descobre em um ano e conta para a região.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte a conta '100 mil mais barata' para os dois confrontos mais comuns da sua carteira, com premissas conservadoras e fonte (consumo medido, distância da assistência, anúncios de usadas). Guarde no celular. Depois calcule o ponto de virada: com quantas horas por mês a mais barata passa a compensar? Esse número é a sua honestidade pronta." },
      ],
      missao: "Na próxima objeção de preço com concorrente, responda nas três camadas (TCO ao vivo, custo da inação, prova) sem nenhuma frase negativa sobre a outra marca. Registre no CRM o resultado da conta e a resposta do cliente ao 'o que esse número te diz?'.",
      quiz: [
        { pergunta: "O cliente diz 'a XCMG é 100 mil mais barata, me dá um motivo'. Qual é a primeira frase mais eficaz?", opcoes: [
          "'Posso chegar em 60 mil de diferença se você fechar hoje; mais do que isso eu não consigo, mas esses 40 mil a New Holland devolve em revenda.'",
          "'A New Holland tem 50 anos de história e a maior rede do Brasil; a XCMG entrou no mercado ontem e ninguém sabe onde vai estar daqui a cinco anos.'",
          "'A XCMG é máquina para quem troca em dois anos; se você quer uma máquina para dez anos, a comparação de preço não faz sentido.'",
          "'Cem mil é muito dinheiro, e a XCMG melhorou. O que eu posso te mostrar é o que esses 100 mil viram em 5 anos na sua obra. Posso fazer a conta com você?'",
        ], correta: 3, explicacao: "Reconhece o valor e a concorrente (credibilidade), pede permissão para a conta e traz o cliente para dentro dela. Depreciar ofende quem considerou a marca; desconto confirma que estava caro; história da marca é argumento seu, não conta dele." },
        { pergunta: "Na conta da aula, os R$ 100 mil de diferença viram R$ 391 mil a mais em 5 anos. Qual componente pesou mais?", opcoes: [
          "O consumo de combustível, 2 litros por hora a mais",
          "A revenda menor, 38% contra 50% em cinco anos",
          "O deslocamento da assistência, a 140 km",
          "As paradas, 2 dias a mais por mês com aluguel e operador",
        ], correta: 3, explicacao: "R$ 228 mil em paradas, contra R$ 113 mil de consumo, R$ 96 mil de revenda e R$ 54 mil de assistência. É por isso que a disponibilidade e a distância do técnico são o centro da comparação, e é por isso que o cliente com uso baixo (poucas paradas relevantes) pode ter outra resposta." },
        { pergunta: "Para um produtor que usa a retro 40 horas por mês no sítio, a conta mostra que a máquina mais barata compensa. O que o consultor faz?", opcoes: [
          "Ajusta as premissas de horas e paradas, porque o produtor tende a subestimar o uso e a conta precisa refletir a realidade futura",
          "Insiste na revenda e na garantia para justificar a diferença, porque são vantagens reais que a conta de curto prazo não captura",
          "Diz que, para esse uso, a mais barata serve, e explica em que ponto (horas/mês) a conta vira",
          "Sugere que ele compre a New Holland e preste serviço para os vizinhos, aumentando as horas até a conta fechar",
        ], correta: 2, explicacao: "A conta honesta às vezes manda o cliente para o concorrente. No caso da aula, esse cliente voltou dois anos depois, comprou à vista e indicou três vizinhos. Forçar a conta gera um cliente arrependido que conta para a região; o ponto de virada (horas/mês) é informação útil que ele guarda." },
        { pergunta: "O cliente fala de 'parcela', 'agora' e 'esse mês' ao dizer que está caro. Qual é o significado provável e a resposta?", opcoes: [
          "Caixa: a resposta é estrutura (usada, carência, prazo), não desconto",
          "Ritual: a resposta é uma concessão pequena e condicionada, para ele sentir que negociou",
          "Não viu o valor: a resposta é o TCO ao vivo, com os números dele na tela",
          "Outra proposta na mesa: a resposta é comparar configuração e testar a BATNA",
        ], correta: 0, explicacao: "O vocabulário revela a objeção: quem fala de parcela e de 'agora' está falando de fluxo de caixa. Desconto de 3% não muda a parcela de forma relevante; carência de 6 meses e usada na entrada mudam. A tabela de significados existe para escolher a resposta certa." },
        { pergunta: "Qual é a terceira camada da resposta a 'está caro' e por que ela importa mesmo depois da conta?", opcoes: [
          "O desconto final, porque depois da conta o cliente precisa sentir que negociou para assinar sem arrependimento",
          "A prova (cliente parecido que viveu a escolha, medição), porque a conta convence a razão e a história convence a decisão",
          "A garantia estendida, porque cobre o risco que a conta não elimina e tranquiliza o sócio na hora de assinar",
          "A ficha técnica com fontes, porque valida as premissas da conta e dá ao contador o que ele precisa para aprovar",
        ], correta: 1, explicacao: "A conta fala com o Sistema 2; a prova social fala com o Sistema 1 (Módulo 2). 'O Roberto comprou a mais barata em 2022 e…' com telefone é o que faz o cliente decidir e defender a decisão. Sem prova, a conta fica como 'número de vendedor'." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m7a3", titulo: "'Não é o momento', 'depois da safra', 'quando a obra sair'", minutos: 13,
      resumo: "Timing é a objeção mais educada e a mais perigosa: ninguém discute com 'agora não'. A resposta é o custo de esperar em reais, a pergunta 'o que muda daqui a 3 meses?' e, quando o momento é real, um plano com data e uma estrutura que faça o 'depois' começar agora.",
      blocos: [
        { tipo: "p", texto: "'Depois da safra' pode ser verdade (caixa entra em agosto) ou pode ser o jeito gentil de dizer que o custo da inação não doeu o suficiente. O consultor separa os dois com uma pergunta: 'o que muda daqui a três meses?'. Se a resposta for concreta (safra, ordem de serviço, empenho), o momento é real e o trabalho é fazer a compra caber no calendário do cliente (carência, primeira parcela pós-safra, reserva da máquina). Se a resposta for vaga ('aí eu vejo'), o momento é cortina, e o trabalho é voltar ao custo de esperar." },
        { tipo: "framework", nome: "Resposta ao timing em 4 movimentos", origem: "Gap Selling (custo da inação) + estrutura de financiamento como resposta ao calendário", passos: [
          "Reconhecer e explorar: 'Faz sentido esperar a safra. O que muda, concretamente, depois dela?' Ouça: caixa? decisão do sócio? obra confirmada?",
          "Custo de esperar em reais: 'Enquanto isso, a máquina atual custa R$ 9 mil por mês em parada e diesel. Esperar 4 meses são R$ 36 mil — mais do que a entrada.' Com os números dele.",
          "Fazer o 'depois' começar agora: 'E se a primeira parcela cair em setembro, depois da colheita, e a máquina já estivesse trabalhando na safra?' Carência, primeira parcela pós-safra, faturamento alinhado ao empenho.",
          "Se o momento é real mesmo assim: plano com data, gatilho e reserva ('deixo a máquina reservada até 15 de agosto sem compromisso; te chamo dia 1º'). Registro no CRM. Nutrição com valor até lá.",
        ] },
        { tipo: "conta", titulo: "Custo de esperar 4 meses (empreiteiro com retro velha)", linhas: [
          ["Paradas: 3 dias/mês × R$ 1.900", "R$ 5.700/mês"],
          ["Consumo extra: 2,5 L/h × 160 h × R$ 6,30", "R$ 2.520/mês"],
          ["Corretivas médias", "R$ 1.800/mês"],
          ["Custo da inação por mês", "R$ 10.020"],
          ["4 meses de espera", "R$ 40.080"],
          ["Entrada da máquina nova (sem usada)", "R$ 35.000"],
        ], conclusao: "Esperar 4 meses custa mais do que a entrada. Se a razão da espera é 'juntar dinheiro para a entrada', a espera consome a própria entrada. Com carência, a máquina trabalha os 4 meses e a primeira parcela cai depois da safra." },
        { tipo: "dialogo", titulo: "'Depois da safra'", falas: [
          { quem: "cliente", texto: "Gostei, mas vamos deixar pra depois da safra. Agora não dá." },
          { quem: "vendedor", texto: "Faz sentido: safra é quando o caixa entra. Me ajuda a entender: o que muda depois dela? É o dinheiro da colheita, ou tem outra coisa?" },
          { quem: "cliente", texto: "O dinheiro. Em agosto eu tenho caixa pra entrada." },
          { quem: "vendedor", texto: "Entendi. Posso te mostrar uma coisa? A sua retro parou 3 dias no mês passado e você alugou pra cobrir. Somando parada, diesel e corretiva, dá uns 10 mil por mês. Esperar até agosto são 40 mil — que é mais do que a entrada que você quer juntar." },
          { quem: "nota", texto: "Custo de esperar com os números dele. Sem pressão: é uma conta." },
          { quem: "cliente", texto: "Nunca tinha pensado assim. Mas eu não tenho a entrada agora." },
          { quem: "vendedor", texto: "Por isso a estrutura: a sua usada é a entrada, e eu coloco 4 meses de carência. A máquina trabalha a safra inteira e a primeira parcela cai em setembro, com o dinheiro da colheita na conta. O 'depois da safra' continua — só a máquina que chega antes. Faz sentido?" },
        ] },
        { tipo: "caso", titulo: "Caso: 'quando a obra sair' que nunca saiu — e a que saiu", situacao: "Dois clientes, mesma frase: 'quando a obra sair eu compro'. O vendedor tratou os dois igual: 'te espero'.", acao: "Depois do módulo, passou a explorar. Cliente A: 'o que muda?' — 'aí eu vejo'; sem ordem de serviço, sem edital. Desqualificou com gatilho. Cliente B: 'a ordem de serviço sai dia 20'; edital publicado, empenho previsto. Reservou a máquina, alinhou o faturamento à primeira medição.", resultado: "Cliente A nunca comprou (a obra não existia). Cliente B fechou no dia 22 com a máquina entregue em 15 dias, porque estava reservada. O vendedor parou de gastar follow-up com o A e ganhou o B pela antecipação.", licao: "'Quando a obra sair' pode ser nada ou pode ser a venda mais fácil do mês. A pergunta 'o que muda, concretamente?' é o que distingue." },
        { tipo: "script", titulo: "Perguntas para o timing", itens: [
          "'O que muda, concretamente, depois da safra/obra?'",
          "'Se a primeira parcela caísse depois da safra, o momento ainda seria um problema?'",
          "'Enquanto a gente espera, o que a máquina atual está custando por mês?'",
          "'Se eu deixar a máquina reservada até a data que você me disse, sem compromisso, te ajuda?'",
          "'O que precisaria acontecer para valer a pena antecipar em dois meses?'",
        ] },
        { tipo: "erros", titulo: "Erros com timing", itens: [
          "'Te espero'. Sem explorar, sem custo de esperar, sem plano: o cliente some e compra do vendedor que ligou em agosto.",
          "Pressionar com prazo falso ('a tabela sobe mês que vem'). O cliente de safra conhece o calendário; a mentira aparece.",
          "Não registrar a data e o gatilho. Agosto chega e você não lembra.",
          "Sumir até a data. Nutrição com valor a cada 30 dias mantém a preferência; silêncio abre espaço para o concorrente.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste as negociações do CRM paradas com objeção de timing. Para cada uma, escreva a resposta ao 'o que muda?' que você conhece (ou marque como desconhecida), calcule o custo de esperar até a data e escreva a estrutura que faria o 'depois' começar agora. Ligue para as três maiores hoje." },
      ],
      missao: "Em uma negociação com 'não é o momento', faça os quatro movimentos: explorar o que muda, custo de esperar com os números dele, estrutura que antecipa (carência, parcela pós-safra) e, se o momento for real, reserva com data e gatilho registrados no CRM.",
      quiz: [
        { pergunta: "O cliente diz 'vamos deixar para depois da safra'. Qual é a pergunta que separa o timing real da cortina de fumaça?", opcoes: [
          "'Qual é a data exata da safra? Assim eu já deixo a proposta pronta para esse mês.'",
          "'O que muda, concretamente, depois da safra?'",
          "'Você tem certeza de que quer esperar? A tabela pode mudar até lá.'",
          "'E se eu conseguir um desconto para fechar antes da safra?'",
        ], correta: 1, explicacao: "Resposta concreta (caixa da colheita, ordem de serviço, empenho) indica momento real, e o trabalho vira estrutura e plano. Resposta vaga ('aí eu vejo') indica que o custo de esperar não doeu, e o trabalho volta ao custo da inação. Desconto e pressão erram o alvo." },
        { pergunta: "O cliente quer esperar 4 meses para juntar a entrada de R$ 35 mil, e a máquina atual custa R$ 10 mil por mês em paradas e diesel. O que a conta mostra?", opcoes: [
          "Que a espera custa R$ 40 mil, mais do que a entrada que ele quer juntar: esperar consome a própria entrada",
          "Que ele deve comprar uma máquina de classe menor, com entrada de R$ 20 mil, para não precisar esperar os 4 meses",
          "Que um desconto de R$ 35 mil no preço resolveria a espera, porque eliminaria a necessidade de juntar a entrada",
          "Que a espera é razoável, porque a entrada de R$ 35 mil é maior do que um mês de custo da máquina atual",
        ], correta: 0, explicacao: "O custo da inação acumulado supera a entrada. Com a usada como entrada e carência, a máquina trabalha os 4 meses e a primeira parcela cai depois da safra. O 'depois' continua valendo para a parcela; só a máquina chega antes." },
        { pergunta: "Dois clientes dizem 'quando a obra sair eu compro'. Um responde 'aí eu vejo' e o outro 'a ordem de serviço sai dia 20, edital publicado'. Qual é a conduta correta para cada um?", opcoes: [
          "Follow-up semanal com os dois até a obra sair, porque ambos declararam intenção de compra ligada a um evento",
          "Desqualificar os dois até haver ordem de serviço assinada, porque intenção sem documento é esperança",
          "Cliente vago: desqualificar com gatilho e nutrição; cliente concreto: reservar a máquina, alinhar faturamento à medição e acompanhar",
          "Oferecer desconto ao vago para criar urgência e esperar o concreto, que vai comprar de qualquer forma",
        ], correta: 2, explicacao: "O mesmo texto esconde dois casos opostos. O vago consome follow-up e não compra (a obra pode não existir); o concreto é a venda mais fácil do mês se a máquina estiver reservada e a estrutura alinhada ao empenho. A pergunta 'o que muda?' distingue." },
        { pergunta: "O momento é real: o cliente só tem caixa em setembro. Qual é o erro mais comum do vendedor nessa situação?", opcoes: [
          "Propor carência para antecipar a máquina, porque isso pressiona um cliente que já disse que só tem caixa em setembro",
          "Reservar a máquina sem compromisso, porque a reserva bloqueia uma unidade que outro cliente poderia comprar antes",
          "Registrar a data no CRM e nada mais, porque setembro está longe e qualquer contato antes disso é cobrança",
          "Dizer 'te espero' e sumir até setembro, sem plano, reserva ou nutrição, abrindo espaço para o concorrente que ligar em agosto",
        ], correta: 3, explicacao: "Timing real exige plano: reserva com data, gatilho registrado, nutrição mensal com valor (Plano Safra, caso de vizinho) e a estrutura pronta para setembro. 'Te espero' entrega o cliente ao concorrente mais disciplinado." },
        { pergunta: "Qual estrutura faz o 'depois da safra' continuar válido para o cliente e ainda assim antecipa a máquina?", opcoes: [
          "Desconto à vista para compra imediata, que compensa financeiramente a antecipação do caixa da safra",
          "Consórcio com contemplação prevista para depois da safra, que respeita o calendário sem comprometer o caixa",
          "Aluguel da máquina até a safra, com opção de compra e abatimento do que foi pago no valor final",
          "Usada como entrada e carência com a primeira parcela caindo depois da colheita, com a máquina trabalhando na safra",
        ], correta: 3, explicacao: "A objeção era 'não tenho caixa agora'; a estrutura respeita isso (parcela só quando o caixa entra) e resolve o custo da inação (a máquina trabalha antes). Custo zero para a concessionária. Desconto não resolve caixa; consórcio não antecipa; aluguel soma custo." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m7a4", titulo: "'Não conheço a assistência', 'já fui queimado', 'sempre comprei da outra'", minutos: 14,
      resumo: "Objeções de confiança não se respondem com argumento; se respondem com prova, nomes, compromissos por escrito e tempo. Quem tenta convencer um cliente queimado com 'nossa assistência é ótima' confirma o medo dele.",
      blocos: [
        { tipo: "p", texto: "O cliente que diz 'não conheço a assistência de vocês' ou 'já comprei máquina nova e fiquei 40 dias parado' está falando de risco, não de máquina. E risco se reduz com evidência e com compromisso verificável, nunca com adjetivo. O consultor tem um kit de confiança: nomes (o técnico, o gerente de peças), números (tempo médio de atendimento, distância, peças em estoque), contatos (clientes que tiveram chamado e podem contar), documentos (cláusula de atendimento, garantia por escrito) e tempo (pequenos compromissos cumpridos antes da venda). 'Sempre comprei da outra' é uma variação: o risco de trocar o conhecido pelo desconhecido." },
        { tipo: "framework", nome: "Kit de confiança (5 provas)", origem: "Prática de redução de risco percebido em vendas B2B (Cialdini: autoridade e prova social; Voss: rótulos)", passos: [
          "Nomes: 'O técnico que atende a sua região é o Diego; o gerente de peças é o Fábio. Aqui está o WhatsApp dos dois.' Pessoa nomeada é compromisso; 'nossa equipe' é abstração.",
          "Números: 'Tempo médio de atendimento nos últimos 12 meses na sua região: 26 horas. Peças de desgaste da B110B em estoque em Cachoeiro: 94% dos itens.' Se não tiver os números, levante-os com a assistência antes da visita.",
          "Contatos: 'O Ari, de Iúna, teve um chamado em março. Liga pra ele e pergunta quanto tempo levou.' Cliente que passou por problema e foi bem atendido é a melhor prova que existe.",
          "Documentos: cláusula de atendimento em X horas na proposta; garantia por escrito; plano de manutenção com preços. Papel reduz medo.",
          "Tempo: cumpra três pequenos compromissos antes da venda (a ligação às 14h, o laudo da usada na quinta, a visita do técnico). Confiança se constrói em atos pequenos e verificáveis, não em promessas grandes.",
        ] },
        { tipo: "dialogo", titulo: "Cliente queimado", falas: [
          { quem: "cliente", texto: "Já comprei máquina nova. Ficou 40 dias parada esperando uma bomba. Nunca mais compro de ninguém sem ter certeza." },
          { quem: "vendedor", texto: "Quarenta dias parada, e ninguém dava resposta. Parece que o que ficou não foi a máquina; foi a sensação de ter ficado sozinho." },
          { quem: "nota", texto: "Espelhamento e rótulo (Módulo 2). Sem defender a categoria 'máquina nova', sem 'com a gente é diferente'." },
          { quem: "cliente", texto: "Exatamente. Ninguém ligava." },
          { quem: "vendedor", texto: "Então eu não vou te pedir para acreditar em mim. Vou te dar três coisas para você checar: o WhatsApp do Diego, que é o técnico da sua região; o telefone do Ari, de Iúna, que teve um chamado em março e pode te dizer quanto tempo levou; e uma cláusula por escrito na proposta com prazo de atendimento. Se depois de checar isso ainda ficar dúvida, a gente conversa de novo. Justo?" },
          { quem: "nota", texto: "Nomes, contato, documento. 'Não vou te pedir para acreditar' é a frase que o cliente queimado precisa ouvir." },
        ] },
        { tipo: "tabela", titulo: "Três objeções de confiança e a resposta", colunas: ["Objeção", "O risco que ela expressa", "Prova principal", "Erro comum"], linhas: [
          ["'Não conheço a assistência de vocês'", "Ficar parado sem resposta", "Nomes + números + contato de cliente com chamado + cláusula", "'Nossa assistência é a melhor da região'"],
          ["'Já fui queimado com máquina nova'", "Repetir o trauma", "Rótulo + 'não vou pedir para acreditar' + provas verificáveis + pequenos compromissos cumpridos", "Defender a marca anterior ou a categoria"],
          ["'Sempre comprei da outra marca'", "Perder a relação/conhecimento acumulado", "Validar a lealdade; não pedir troca total; uma máquina de teste; assistência comparada com fatos", "Atacar a marca antiga; 'só até sexta'"],
        ] },
        { tipo: "caso", titulo: "Caso: os três compromissos pequenos", situacao: "Empreiteiro de Guaçuí, queimado por outra marca, disse que 'não acreditava em vendedor'. O vendedor não discutiu.", acao: "Combinou três coisas pequenas: laudo da usada na quinta às 10h, ligação do técnico Diego na sexta às 14h, comparativo de peças em estoque por e-mail na segunda. Cumpriu as três na hora exata. Só na quarta visita falou de proposta.", resultado: "O cliente disse: 'você é o primeiro que fez o que disse três vezes seguidas'. Fechou uma B110B e, oito meses depois, uma E145C. Passou a ser referência para outros clientes queimados.", licao: "Confiança não se argumenta; se demonstra em atos pequenos e verificáveis. Três horários cumpridos valem mais que qualquer discurso sobre assistência." },
        { tipo: "script", titulo: "Frases para objeções de confiança", itens: [
          "'Não vou te pedir para acreditar em mim. Vou te dar o que checar.'",
          "'O técnico da sua região é o Diego. Esse é o WhatsApp dele. Manda uma mensagem agora, se quiser.'",
          "'O Ari, de Iúna, teve chamado em março. Liga pra ele; eu não vou estar na ligação.'",
          "'Vinte anos com a mesma marca é uma relação séria. Não estou pedindo para trocar tudo; estou pedindo para comparar uma máquina com fatos.'",
          "'Coloco o prazo de atendimento por escrito na proposta. Se não cumprir, você tem o papel.'",
        ] },
        { tipo: "erros", titulo: "Erros com confiança", itens: [
          "Adjetivos: 'ótima', 'a melhor', 'excelente'. Cliente queimado ouviu isso do vendedor anterior.",
          "Defender a categoria ('toda máquina quebra') ou a marca anterior. Ele quer ser ouvido, não corrigido.",
          "Prometer o que a assistência não confirmou. Cheque o tempo médio e o estoque antes de falar.",
          "Pedir a decisão cedo. Confiança precisa de tempo: pequenos compromissos, depois a proposta.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte o seu kit de confiança: nome e WhatsApp do técnico e do gerente de peças da sua região; tempo médio de atendimento dos últimos 12 meses (peça à assistência); percentual de peças de desgaste em estoque por modelo; três clientes que tiveram chamado bem resolvido e autorizam contato; a cláusula de atendimento padrão para a proposta. Cadastre no CRM." },
      ],
      missao: "Levante com a assistência os números reais (tempo médio de atendimento, estoque de peças) e monte o kit de confiança. Na próxima objeção de assistência ou de cliente queimado, entregue as cinco provas e combine três pequenos compromissos com hora. Registre no CRM o cumprimento de cada um.",
      quiz: [
        { pergunta: "O cliente diz 'já comprei máquina nova e fiquei 40 dias parado; nunca mais'. Qual resposta reduz o risco percebido?", opcoes: [
          "'Com a gente é diferente; nossa assistência é a melhor da região, o técnico mora aqui em Cachoeiro e atende em 24 horas.'",
          "'Isso acontece com toda máquina em algum momento; o importante é ter garantia, contrato de atendimento e peças em estoque.'",
          "Rotular o abandono, dizer que não vai pedir para acreditar e entregar provas verificáveis: técnico nomeado, cliente com chamado, cláusula",
          "'Qual marca era? Essa realmente tem problema de assistência na região; com a New Holland isso não acontece, pode perguntar.'",
        ], correta: 2, explicacao: "Cliente queimado desconfia de adjetivos e de promessas. O que reduz risco é o verificável: nomes, contatos, documentos, e a frase 'não vou te pedir para acreditar'. Defender a categoria minimiza a dor dele; atacar a marca anterior é depreciação." },
        { pergunta: "Por que 'nossa assistência é ótima' costuma piorar a objeção de confiança?", opcoes: [
          "Porque o cliente prefere ouvir sobre a máquina em si (consumo, produção), e assistência é assunto para depois da venda",
          "Porque adjetivos são exatamente o que o vendedor anterior disse antes de deixar o cliente 40 dias parado; sem prova, confirmam o padrão",
          "Porque a assistência é responsabilidade da fábrica e da concessionária, e o vendedor não deveria prometer em nome delas",
          "Porque elogiar a própria empresa é lido como falta de modéstia pelo cliente do interior, que valoriza discrição",
        ], correta: 1, explicacao: "O cliente queimado tem um filtro: promessa sem evidência é sinal de risco. Nome do técnico, tempo médio de atendimento e cliente com chamado resolvido são a linguagem que atravessa o filtro. Adjetivos são ruído que reforça o medo." },
        { pergunta: "O que o caso dos 'três compromissos pequenos' demonstra?", opcoes: [
          "Que a confiança se constrói em atos pequenos e verificáveis cumpridos na hora exata, antes de pedir a decisão",
          "Que o técnico da assistência deve participar de todas as visitas a clientes queimados, para dar segurança",
          "Que clientes queimados precisam de mais visitas do que os outros, e a frequência é o que reconstrói a relação",
          "Que a proposta deve ser adiada o máximo possível com clientes desconfiados, para não parecer pressa",
        ], correta: 0, explicacao: "Laudo na quinta às 10h, ligação do técnico na sexta às 14h, e-mail na segunda: três promessas cumpridas mudaram 'não acredito em vendedor' para 'você é o primeiro que fez o que disse'. Não é quantidade de visitas nem atraso da proposta: é palavra cumprida, repetidamente." },
        { pergunta: "O cliente diz 'sempre comprei da outra marca, 20 anos'. Qual resposta preserva a relação e abre a comparação?", opcoes: [
          "Validar a lealdade, não pedir troca total, propor comparar uma máquina com fatos (assistência, consumo) e dar tempo",
          "Mostrar, com dados de mercado, que a outra marca perdeu qualidade e participação nos últimos anos na região",
          "Oferecer uma condição especial válida só esta semana, para compensar o custo emocional de mudar de fornecedor",
          "Perguntar, com curiosidade, por que ele nunca considerou outras marcas em vinte anos de compras",
        ], correta: 0, explicacao: "Lealdade é valor para o cliente (e geralmente ele é perfil S). Atacar a marca ataca a decisão dele; 'só esta semana' é pressão que o afasta; 'por que nunca' acusa. Validar, pedir pouco (uma máquina, uma comparação) e dar tempo é o caminho." },
        { pergunta: "Qual das provas do kit de confiança costuma ter mais peso para um cliente com medo de ficar parado?", opcoes: [
          "O vídeo institucional da rede de assistência, com a estrutura de oficinas e o estoque central de peças",
          "A garantia estendida paga, que cobre os componentes principais por mais tempo e reduz o risco financeiro",
          "A afirmação do vendedor de que a assistência atende em 24 horas, registrada por escrito na proposta",
          "O contato de um cliente vizinho que teve um chamado e pode contar quanto tempo levou",
        ], correta: 3, explicacao: "Cliente que passou pelo problema e foi bem atendido é prova social do tipo mais forte (parecido, verificável, sem interesse). Vídeo é propaganda; garantia paga não responde ao tempo de atendimento; afirmação do vendedor é o que ele já não acredita." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m7a5", titulo: "'O banco não aprova', 'não tenho caixa', 'vou alugar'", minutos: 14,
      resumo: "Três objeções de dinheiro que o vendedor mediano aceita como fim. O consultor conhece os caminhos alternativos de crédito, faz a conta do aluguel acumulado e mostra que 'não tenho caixa' quase sempre é 'não tenho a estrutura certa'.",
      blocos: [
        { tipo: "p", texto: "Quando o banco nega, o cliente fica constrangido e o vendedor mediano se despede. Mas 'o banco negou' quase sempre é 'este banco, nesta linha, com esta documentação, negou'. Há outros bancos, outras linhas (FINAME por outro agente, CDC, Banco CNH, consórcio com lance, Plano Safra), outras estruturas (usada como entrada, avalista, garantia adicional, máquina de classe abaixo, seminova certificada). 'Não tenho caixa' é problema de fluxo, não de preço. E 'vou alugar' é uma conta que o cliente não fez: 18 meses de aluguel costumam pagar uma usada inteira." },
        { tipo: "framework", nome: "Árvore de decisão para 'o banco negou'", origem: "Prática de financiamento de bens de capital", passos: [
          "Descubra o motivo: restrição cadastral (CPF/CNPJ), faturamento insuficiente, tempo de empresa, documentação, limite tomado? Cada motivo tem um caminho diferente.",
          "Restrição: regularizar (às vezes é uma pendência pequena) ou avalista/sócio com cadastro limpo; consórcio (análise só na contemplação).",
          "Faturamento/limite: outro banco (cada um tem política), FINAME por outro agente, entrada maior com a usada, máquina de classe abaixo ou seminova certificada (valor menor, aprovação mais fácil).",
          "Tempo de empresa: CDC no CPF do sócio; Banco CNH (política própria para o setor); consórcio.",
          "Produtor rural: Pronamp/Moderfrota via cooperativa de crédito (Sicoob/Cresol), que costuma aprovar onde o banco grande nega.",
          "Sempre: 'Não desisti; vou abrir outro caminho e te dou retorno em 48 horas.' Nunca 'então não dá'.",
        ] },
        { tipo: "conta", titulo: "'Vou alugar': 18 meses de aluguel × usada certificada (retro)", linhas: [
          ["Aluguel mensal de retroescavadeira (200 h)", "R$ 14.000"],
          ["18 meses de aluguel", "R$ 252.000"],
          ["Usada certificada B95C, 3 anos, 3.000 h", "R$ 240.000"],
          ["Ao fim de 18 meses de aluguel", "R$ 0 de patrimônio"],
          ["Ao fim de 18 meses com a usada (parcela ≈ R$ 5.900 no CDC 48 m)", "Máquina própria com ≈ 60% de valor de revenda (R$ 145 mil)"],
          ["Diferença patrimonial em 18 meses", "≈ R$ 145.000 a favor da compra"],
        ], conclusao: "Alugar 18 meses paga uma usada inteira e sobra nada. Comprar a usada com parcela menor que o aluguel deixa R$ 145 mil de patrimônio. O aluguel é certo para obra curta (menos de 6 meses) ou pico sazonal; para uso contínuo, é o caminho mais caro." },
        { tipo: "dialogo", titulo: "'O banco negou'", falas: [
          { quem: "cliente", texto: "O Banco do Brasil negou o FINAME. Então esquece, não vai dar." },
          { quem: "vendedor", texto: "Que chato, sei que você contava com isso. Antes de esquecer: te disseram o motivo? Cadastro, faturamento, documentação?" },
          { quem: "cliente", texto: "Disseram que o faturamento não comporta a parcela." },
          { quem: "vendedor", texto: "Então não é 'não'; é 'não nesse tamanho'. Três caminhos: com a sua usada na entrada, a parcela cai 35% e eu peço reanálise no mesmo banco; ou o Sicoob, que olha o faturamento de outro jeito; ou uma seminova certificada com 2.800 horas, que tem parcela que o faturamento comporta com folga. Qual desses você quer que eu abra primeiro? Te dou retorno em 48 horas." },
          { quem: "nota", texto: "Descobriu o motivo, reenquadrou ('não nesse tamanho'), abriu três caminhos e comprometeu-se com prazo. O cliente sai do constrangimento e volta a decidir." },
        ] },
        { tipo: "caso", titulo: "Caso: a locadora que virou compradora", situacao: "Empreiteiro de Mimoso alugava uma retro há 26 meses da mesma locadora, R$ 13.500 por mês, 'porque não tenho caixa para comprar'.", acao: "O vendedor somou: R$ 351 mil pagos em aluguel, patrimônio zero. Mostrou uma B95C seminova certificada por R$ 235 mil com parcela de R$ 5.800 no CDC — menos da metade do aluguel — e a usada da locadora nem entrava, porque não era dele.", resultado: "Fechou a seminova no mesmo dia. Um ano depois, comprou uma B110B nova com a seminova na entrada. 'Eu tinha pago duas máquinas em aluguel e não tinha nenhuma.'", licao: "'Não tenho caixa para comprar' e 'pago R$ 13.500 de aluguel' são a mesma frase dita por alguém que não somou. A conta é o remédio." },
        { tipo: "tabela", titulo: "Quando o aluguel é a resposta certa (e quando não é)", colunas: ["Situação", "Aluguel", "Compra"], linhas: [
          ["Obra de 3 a 6 meses sem continuidade", "Certo", "Errado (máquina parada depois)"],
          ["Pico sazonal (2 meses/ano) além da frota própria", "Certo", "Errado"],
          ["Uso contínuo acima de 12 meses", "Errado (paga a máquina e não tem)", "Certo (usada ou nova, conforme o gap)"],
          ["Teste de novo serviço (3 meses)", "Certo, com opção de compra", "Depois de validado"],
          ["Sem crédito de nenhum tipo", "Única opção temporária", "Trabalhar o cadastro; consórcio"],
        ] },
        { tipo: "erros", titulo: "Erros com dinheiro", itens: [
          "'Então não dá' quando o banco nega. É o momento em que o consultor mais vale.",
          "Não perguntar o motivo da negativa. Sem o motivo, não há caminho.",
          "Discutir com quem aluga sem fazer a conta. 'Comprar é melhor' é opinião; R$ 351 mil pagos sem patrimônio é fato.",
          "Prometer aprovação. 'Vou abrir o caminho e te dou retorno em 48 h' é o que você controla.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste os cinco agentes de crédito da sua região (bancos, cooperativas, Banco CNH, administradoras de consórcio) com o gerente de cada um e o que cada um costuma aprovar ou negar. Para cada motivo de negativa (cadastro, faturamento, tempo, documentação), escreva o caminho alternativo. Cadastre como observação no CRM." },
      ],
      missao: "Identifique no CRM uma negociação perdida por 'banco negou' ou 'não tenho caixa' e uma conta que aluga há mais de 12 meses. Reabra as duas: para a primeira, descubra o motivo e abra um caminho alternativo; para a segunda, faça a conta do aluguel acumulado. Registre os resultados.",
      quiz: [
        { pergunta: "O cliente diz 'o Banco do Brasil negou o FINAME, então esquece'. Qual é a primeira ação do consultor?", opcoes: [
          "Sugerir que ele tente de novo no mesmo banco em 6 meses, com o balanço do próximo semestre, que costuma ser melhor",
          "Perguntar o motivo da negativa (cadastro, faturamento, tempo de empresa, documentação), porque cada motivo tem um caminho diferente",
          "Encaminhar imediatamente para o consórcio, que não faz análise de crédito na entrada e resolve a maioria das negativas",
          "Aceitar com elegância e registrar a negociação como perdida por crédito, mantendo o cliente na base para o futuro",
        ], correta: 1, explicacao: "'Negou' não diz nada sem o motivo. Faturamento insuficiente pede usada na entrada, outro agente ou seminova; restrição pede regularização ou avalista; tempo de empresa pede CDC no CPF ou Banco CNH. Consórcio é um caminho, não o único." },
        { pergunta: "Um empreiteiro aluga uma retro há 26 meses por R$ 13.500 mensais 'porque não tem caixa para comprar'. O que a conta revela?", opcoes: [
          "Que o problema real é o cadastro dele, não o caixa: quem paga R$ 13.500 por mês tem caixa, mas não tem crédito aprovado",
          "Que o aluguel é a opção correta para quem não tem caixa para a entrada, porque não exige capital nem análise de crédito",
          "Que ele pagou R$ 351 mil sem patrimônio, e uma seminova certificada teria parcela abaixo da metade do aluguel",
          "Que ele deveria negociar um desconto de longo prazo com a locadora, porque 26 meses de fidelidade justificam uma redução",
        ], correta: 2, explicacao: "'Não tenho caixa' e 'pago R$ 13.500 por mês' são incompatíveis: o caixa existe, está indo para a locadora. A seminova com parcela de R$ 5.800 sobra R$ 7.700 por mês e ainda gera patrimônio. A conta é o que faz o cliente enxergar." },
        { pergunta: "Em qual situação o aluguel é de fato a resposta certa e o consultor deve dizer isso?", opcoes: [
          "Uso contínuo acima de 12 meses, porque a flexibilidade de devolver a máquina compensa o custo maior do aluguel",
          "Cliente que não gosta de dívida e prefere pagar mais para não ter financiamento no nome da empresa",
          "Cliente perfil S com medo de comprar, porque o aluguel permite testar a marca sem compromisso antes da decisão",
          "Obra de 3 a 6 meses sem continuidade ou pico sazonal de 2 meses além da frota própria",
        ], correta: 3, explicacao: "Máquina comprada para obra curta fica parada depois; aluguel resolve. Para uso contínuo, o aluguel paga a máquina e não deixa nada. Dizer quando o aluguel é certo é o que torna a conta do aluguel acumulado crível quando ele é errado." },
        { pergunta: "O banco negou por 'faturamento não comporta a parcela'. Qual resposta abre caminhos em vez de encerrar?", opcoes: [
          "'Então vamos esperar o faturamento crescer com a obra nova e voltamos ao banco no próximo semestre com números melhores e mais histórico.'",
          "'Não é não; é não nesse tamanho. Usada na entrada e reanálise; ou cooperativa de crédito; ou seminova certificada. Qual abro primeiro? Retorno em 48 h.'",
          "'Vou pedir para o gerente da concessionária falar com o gerente do banco; entre eles a análise costuma ser mais flexível e mais rápida.'",
          "'Posso conseguir um desconto para reduzir o valor financiado; com 5% a menos a parcela talvez caiba no que o banco aceita para o seu faturamento.'",
        ], correta: 1, explicacao: "Reenquadre ('não nesse tamanho'), três caminhos concretos, escolha do cliente e prazo de retorno: o cliente sai do constrangimento e volta a decidir. Desconto pequeno não muda a parcela o suficiente; esperar o faturamento crescer é desistir com educação." },
        { pergunta: "Para um produtor rural cujo banco grande negou o crédito, qual caminho costuma funcionar?", opcoes: [
          "CDC no CPF do produtor com taxa de mercado, que dispensa a análise da atividade rural e aprova em dias",
          "Aluguel da máquina até o crédito ser aprovado na próxima safra, quando o faturamento entra e o banco reavalia",
          "Pronamp/Moderfrota via cooperativa de crédito (Sicoob/Cresol), que costuma aprovar onde o banco grande nega, com juros subsidiados",
          "Compra à vista com a venda antecipada de parte da safra a uma trading, que elimina a dependência do banco",
        ], correta: 2, explicacao: "Cooperativas de crédito conhecem o produtor, avaliam a safra e operam as linhas rurais subsidiadas. É o caminho que o vendedor que conhece o mercado abre e o que só conhece o FINAME não abre. CDC no CPF é caro; aluguel adia; vender safra é decisão do produtor, não do vendedor." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m7a6", titulo: "'Vou pensar', o silêncio e o sumiço por WhatsApp", minutos: 13,
      resumo: "'Vou pensar' é a objeção que não diz nada. E o sumiço é a objeção que não diz nem isso. As duas se tratam com a mesma lógica: descobrir o que falta, tirar a pressão, oferecer algo novo e dar ao cliente um jeito fácil de responder — inclusive 'não'.",
      blocos: [
        { tipo: "p", texto: "'Vou pensar' é, na maioria das vezes, uma de três coisas: falta uma informação (o cliente não sabe o que precisa saber), falta uma pessoa (o decisor que não estava) ou falta coragem de dizer 'não'. O vendedor que responde 'claro, me avisa' entrega a venda ao acaso. O consultor pergunta, com leveza, o que exatamente precisa ser pensado, e oferece ajudar a pensar. Quando o cliente some, o erro é cobrar ('e aí, viu a proposta?'); o acerto é reaparecer com valor novo e uma pergunta que se responde com 'não' sem constrangimento." },
        { tipo: "framework", nome: "Resposta ao 'vou pensar' em 3 passos", origem: "Blount (Objections) e Voss (perguntas orientadas a 'não')", passos: [
          "Concordar e explorar: 'Claro, é uma decisão grande. Só pra eu te ajudar a pensar: o que exatamente ainda não está claro? É a parcela, a entrega, a comparação com a outra, ou tem alguém que você precisa consultar?' Dê opções: facilita a resposta.",
          "Resolver ou marcar: se é informação, resolva agora (ou em 24 h com data). Se é pessoa, marque a reunião com ela. Se é 'não' disfarçado, dê permissão: 'Se a resposta for não, me diz que eu entendo; prefiro um não hoje a um talvez por três meses.'",
          "Data e próximo passo: 'Então eu te chamo quinta às 10h com a simulação da parcela; até lá você fala com o seu sócio. Combinado?' Nunca 'me avisa'.",
        ] },
        { tipo: "tabela", titulo: "Reabrindo o sumiço: mensagens que funcionam e as que não", colunas: ["Não funciona (cobrança)", "Funciona (valor novo + pergunta fácil)"], linhas: [
          ["'E aí, conseguiu ver a proposta?'", "'Seu Jorge, saiu a linha nova do Plano Safra com juros menores. Vale eu refazer a parcela? Responde só sim ou não.'"],
          ["'Só passando pra saber se tem novidade'", "'O Marcos, de Rio Novo, fez 3.000 horas com a B110B sem parar; foto aqui. Ainda faz sentido a gente conversar ou a obra mudou?'"],
          ["'Última tentativa de contato'", "'Seria loucura pensar nisso antes da safra? Se for, me diz que eu volto em agosto.'"],
          ["'Você desistiu?'", "'Desisti de te perturbar sobre a proposta. Mas o rolo que você viu ficou disponível para entrega em 15 dias; se ainda servir, me avisa. Se não, tudo certo.'"],
          ["Áudio de 2 minutos explicando tudo de novo", "Três linhas, um fato novo, uma pergunta de sim/não"],
        ] },
        { tipo: "dialogo", titulo: "Dando permissão para o 'não'", falas: [
          { quem: "cliente", texto: "Deixa eu pensar e te falo." },
          { quem: "vendedor", texto: "Claro, é uma decisão grande. Só pra eu te ajudar a pensar: o que ainda não está claro? A parcela, a entrega, a comparação com a outra proposta, ou tem alguém que precisa opinar?" },
          { quem: "cliente", texto: "Acho que é mais… não sei se é o momento mesmo." },
          { quem: "vendedor", texto: "Entendi. Vou te dizer uma coisa: se a resposta for 'não', pode me dizer, que eu entendo e prefiro um não agora a um talvez por três meses. E se for 'ainda não', me diz o que precisaria mudar." },
          { quem: "nota", texto: "Permissão para o 'não' tira a pressão e força a clareza. O cliente que ia sumir agora diz a verdade." },
          { quem: "cliente", texto: "Não é não. É que o meu irmão acha que a gente devia esperar a obra da BR confirmar." },
          { quem: "vendedor", texto: "Então o que falta é o seu irmão e a BR. Posso passar aí quinta com vocês dois e mostrar a estrutura em que a parcela só começa quando a BR começar a medir? Se ele ainda achar cedo, tudo bem." },
        ] },
        { tipo: "caso", titulo: "Caso: 14 sumidos, 6 respostas, 2 vendas", situacao: "O vendedor tinha 14 negociações em silêncio há mais de 20 dias. Todas tinham recebido 'e aí, viu a proposta?' pelo menos duas vezes.", acao: "Enviou a cada uma uma mensagem de três linhas com um fato novo real (linha de crédito, caso de cliente com foto, disponibilidade de entrega, edital) e uma pergunta orientada a 'não'.", resultado: "Seis responderam em 48 horas: dois fecharam em 3 semanas, três disseram 'não' ou 'depois' com data (e saíram do funil com gatilho), um pediu nova reunião com o sócio. Oito continuaram em silêncio e foram desqualificados.", licao: "Cobrança gera silêncio; valor novo com pergunta fácil gera resposta — inclusive o 'não' que libera o seu tempo." },
        { tipo: "script", titulo: "Mensagens de reabertura prontas", itens: [
          "'Seu Jorge, saiu [fato novo: linha de crédito / entrega em 15 dias / edital]. Vale eu refazer a conta? Sim ou não basta.'",
          "'Não quero ser inconveniente. Seria loucura retomar a conversa da E145C antes da obra da BR? Se for, me diz e eu volto quando ela sair.'",
          "'Deixei de te chamar sobre a proposta. Só um dado: o Ari fez 1.200 horas com a B110B em 8 meses, sem parada. Se ainda fizer sentido, me chama; se não, tudo certo.'",
          "'Uma pergunta honesta: a proposta ficou fora do que você esperava, mudou o momento, ou faltou alguma coisa que eu deveria ter mandado? Qualquer das três me ajuda.'",
        ] },
        { tipo: "erros", titulo: "Erros com 'vou pensar' e sumiço", itens: [
          "'Claro, me avisa.' Entrega o controle e a venda.",
          "Cobrar ('viu a proposta?'). Gera culpa, e culpa gera silêncio.",
          "Áudio longo reexplicando. Ele não ouviu da primeira vez; não vai ouvir agora.",
          "Insistir sem fato novo. Sete mensagens iguais é perseguição; sete com valor é cadência.",
          "Não dar permissão para o 'não'. Sem permissão, o cliente some para não te magoar.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste as negociações em silêncio há mais de 15 dias. Para cada uma, escreva uma mensagem de três linhas com um fato novo real e uma pergunta orientada a 'não'. Envie todas hoje. Em 48 horas, registre: respondeu? o quê? próximo passo ou desqualificação." },
      ],
      missao: "Na próxima vez que ouvir 'vou pensar', explore com opções (parcela, entrega, comparação, alguém) e dê permissão para o 'não'. Para as negociações em silêncio, envie mensagens com fato novo e pergunta fácil; registre no CRM as respostas e limpe o funil com as que não voltarem.",
      quiz: [
        { pergunta: "O cliente diz 'deixa eu pensar e te falo'. Qual resposta mantém a venda viva?", opcoes: [
          "'Claro, é uma decisão grande. Só para eu te ajudar a pensar: o que ainda não está claro? Parcela, entrega, comparação, ou tem alguém que precisa opinar?'",
          "'Posso te dar até sexta com a condição atual; depois disso a tabela muda e eu não consigo segurar o valor. Assim você pensa com um prazo.'",
          "'Claro, fico no aguardo. Qualquer coisa me chama, estou à disposição para tirar qualquer dúvida quando você quiser.'",
          "'O que tem para pensar? A conta fechou, a máquina está reservada e a entrega pega a sua obra. Falta só a sua assinatura.'",
        ], correta: 0, explicacao: "Concordar tira a pressão; as opções facilitam a resposta e revelam se falta informação, pessoa ou coragem de dizer não. 'Me chama' entrega o controle; confrontar ('o que tem para pensar?') fecha o cliente; prazo artificial é pressão que gera sumiço." },
        { pergunta: "Por que dar permissão explícita para o 'não' ('se for não, me diz, prefiro um não hoje a um talvez por três meses') funciona?", opcoes: [
          "Porque o cliente se sente desafiado pela permissão e responde 'sim' para provar que não é do tipo que desiste",
          "Porque tira a pressão e o constrangimento; o cliente que ia sumir para não magoar diz a verdade, que muitas vezes é 'falta meu irmão'",
          "Porque encerra negociações ruins rapidamente e libera o funil para as que têm chance real de fechar",
          "Porque demonstra confiança e o cliente respeita quem não implora, o que aumenta o valor percebido da proposta",
        ], correta: 1, explicacao: "O sumiço costuma ser o 'não' que o cliente não teve coragem de dizer, ou um 'ainda não' com uma condição. A permissão libera a verdade: no diálogo da aula, apareceram o irmão e a obra da BR. Liberar o funil é consequência, não o mecanismo." },
        { pergunta: "Qual mensagem tem mais chance de reabrir uma negociação em silêncio há 20 dias?", opcoes: [
          "'E aí, conseguiu ver a proposta que te mandei? Ficou alguma dúvida que eu possa esclarecer?'",
          "'Só passando para saber se tem alguma novidade sobre a máquina. Estou à disposição.'",
          "Um áudio de dois minutos reexplicando a proposta com calma, para o cliente ouvir no carro",
          "'Seu Jorge, saiu a linha nova com juros menores. Vale eu refazer a parcela? Responde só sim ou não'",
        ], correta: 3, explicacao: "Fato novo real (valor) e pergunta que se responde com uma palavra. Cobrança ('viu?', 'novidade?') gera culpa e culpa gera silêncio; áudio longo pede atenção que ele não deu à primeira. No caso da aula, seis de 14 responderam em 48 h com esse formato." },
        { pergunta: "Dos 14 sumidos do caso, 3 responderam 'não' ou 'depois' com data. Como o consultor deve ler esse resultado?", opcoes: [
          "Como sucesso parcial: o 'não' claro libera tempo e o 'depois' com data vira gatilho registrado; ambos valem mais que o silêncio",
          "Como sinal de que a mensagem foi agressiva demais e assustou clientes que ainda estavam avaliando a proposta",
          "Como indicação de que uma condição especial na mensagem teria convertido pelo menos dois dos três em fechamento",
          "Como fracasso: três negociações perdidas de uma vez, que poderiam ter sido mantidas vivas com follow-up regular",
        ], correta: 0, explicacao: "Silêncio consome follow-up e infla o funil; 'não' e 'depois com data' são informação. Três negociações saíram do funil com gatilho, dois fecharam e um marcou reunião. A mensagem funcionou justamente porque permitiu o 'não'." },
        { pergunta: "O cliente revela que 'vou pensar' significa 'meu irmão acha que devemos esperar a obra da BR confirmar'. Qual é o próximo passo?", opcoes: [
          "Esperar a obra da BR confirmar e retomar depois, porque o irmão tem um motivo real e pressionar agora queima a relação",
          "Convencer o cliente a decidir sem o irmão, porque ele é o dono, assina sozinho e a obra da BR não depende da máquina",
          "Marcar reunião com os dois e apresentar a estrutura em que a parcela só começa quando a BR começar a medir, aceitando 'ainda cedo'",
          "Enviar a proposta por WhatsApp para o irmão ler com calma, com a conta do gap e a referência de cliente parecido",
        ], correta: 2, explicacao: "Faltavam uma pessoa (o irmão) e uma condição (a BR). O passo é trazer a pessoa e resolver a condição com estrutura (carência alinhada à medição), sem pressão. Esperar entrega ao concorrente; pular o irmão cria um bloqueador; proposta solta chega sem contexto." },
      ],
    },
  ],
  prova: [
    { pergunta: "Qual é a ordem correta do método LAER-C?", opcoes: [
      "Ouvir, reconhecer, explorar, responder, confirmar",
      "Responder, ouvir, explorar, reconhecer, confirmar",
      "Reconhecer, responder, ouvir, confirmar, explorar",
      "Explorar, ouvir, responder, reconhecer, confirmar",
    ], correta: 0, explicacao: "A resposta vem só depois de ouvir até o fim, validar sem 'mas' e explorar até isolar a objeção real. A confirmação fecha o ciclo e revela se há outra objeção escondida." },
    { pergunta: "Por que a maioria das objeções, segundo Rackham, é criada pelo próprio vendedor?", opcoes: [
      "Porque ele fala mal da concorrência e o cliente reage defendendo a marca que estava considerando",
      "Porque apresenta a solução antes de o cliente sentir o tamanho do problema, gerando 'está caro' e 'não preciso'",
      "Porque não conhece a ficha técnica em profundidade e o cliente percebe insegurança nas respostas",
      "Porque não oferece desconto cedo o suficiente, e o cliente usa a objeção para forçar a concessão",
    ], correta: 1, explicacao: "Sem implicação e necessidade construídas, o valor ainda não existe na cabeça do cliente e qualquer preço parece alto. A melhor técnica de objeção é o diagnóstico bem feito." },
    { pergunta: "O que faz a pergunta 'se isso for resolvido, a gente avança?' no tratamento de objeção?", opcoes: [
      "Pressiona o cliente a fechar, criando um compromisso verbal antes de a objeção ser resolvida",
      "Testa se o cliente é o decisor, porque só quem decide pode responder 'sim' a essa pergunta",
      "Isola a objeção: garante que a resposta vai para a que decide e que não há outra escondida",
      "Encerra a negociação se a resposta for 'não', poupando tempo com quem não vai comprar",
    ], correta: 2, explicacao: "Responder a uma objeção enquanto outra fica escondida gera 'vou pensar'. Isolar antes de responder é o passo que a maioria pula." },
    { pergunta: "Na conta 'a chinesa é 100 mil mais barata', o componente de maior peso em 5 anos costuma ser:", opcoes: [
      "O consumo de combustível, acumulado em 9.000 horas",
      "A revenda menor, de 38% contra 50% do valor",
      "O custo do financiamento, sem banco próprio da marca",
      "As horas paradas e o custo de cobri-las com aluguel",
    ], correta: 3, explicacao: "Dois dias a mais de parada por mês, com aluguel de cobertura e operador parado, somam mais do que consumo, revenda e assistência. Disponibilidade e distância do técnico são o centro da comparação." },
    { pergunta: "Para um cliente com 40 horas por mês de uso, a conta mostra que a máquina mais barata compensa. O que o consultor faz?", opcoes: [
      "Diz a verdade, explica o ponto de virada em horas e mantém a relação para quando o uso crescer",
      "Ajusta as premissas de horas e paradas até a conta favorecer a New Holland, porque o uso vai crescer",
      "Enfatiza garantia e revenda para justificar a diferença, que a conta de curto prazo não captura",
      "Sugere prestar serviço para vizinhos e aumentar as horas até a máquina mais cara compensar",
    ], correta: 0, explicacao: "O cliente que ouve a verdade quando o vendedor não ganha nada volta e indica. Forçar a conta gera cliente arrependido e reputação queimada." },
    { pergunta: "Qual pergunta distingue timing real de cortina de fumaça em 'depois da safra'?", opcoes: [
      "'Quando é a safra? Deixo a proposta pronta para esse mês.'",
      "'Você tem certeza? A tabela pode subir até lá.'",
      "'O que muda, concretamente, depois da safra?'",
      "'E se eu der um desconto para fechar antes?'",
    ], correta: 2, explicacao: "Resposta concreta (caixa, ordem de serviço, empenho) = momento real, trabalho de estrutura e plano. Resposta vaga = custo de esperar não doeu, trabalho de custo da inação." },
    { pergunta: "O cliente quer esperar 4 meses para juntar R$ 35 mil de entrada; a máquina atual custa R$ 10 mil por mês em paradas e diesel. Qual é a leitura?", opcoes: [
      "Esperar é razoável, porque a entrada é maior que um mês de custo e ele decide com o próprio dinheiro",
      "Esperar custa R$ 40 mil e consome a própria entrada; usada na entrada mais carência resolve",
      "Uma máquina de classe menor resolve, porque a entrada cai para R$ 20 mil e ele não precisa esperar",
      "Um desconto de R$ 35 mil resolve, porque elimina a entrada e a máquina pode ser entregue agora",
    ], correta: 1, explicacao: "O custo da inação acumulado supera a entrada. A estrutura (usada na entrada, primeira parcela depois da safra) respeita o 'depois' e antecipa a máquina." },
    { pergunta: "Qual é a prova mais forte para um cliente com medo de ficar parado sem assistência?", opcoes: [
      "O vídeo da rede de assistência, com a estrutura de oficinas e o estoque central de peças",
      "A afirmação 'atendemos em 24 horas', registrada por escrito na proposta comercial",
      "A garantia estendida, que cobre por mais tempo os componentes que mais falham",
      "O contato de um cliente vizinho que teve um chamado resolvido e pode contar quanto tempo levou",
    ], correta: 3, explicacao: "Prova social parecida, verificável e sem interesse. Adjetivos e vídeos são o que o cliente queimado já ouviu. Nomes, números, contatos, documentos e compromissos cumpridos formam o kit de confiança." },
    { pergunta: "'Sempre comprei da outra marca, 20 anos.' Qual resposta é correta?", opcoes: [
      "Validar a lealdade, pedir pouco (comparar uma máquina com fatos) e dar tempo",
      "Mostrar, com dados, que a outra marca decaiu em qualidade e assistência nos últimos anos",
      "Oferecer 'condição especial só esta semana' para compensar o custo de trocar de fornecedor",
      "Perguntar 'por que nunca considerou outras?' para entender a origem da lealdade",
    ], correta: 0, explicacao: "Lealdade é valor para o cliente; atacar a marca é atacar a decisão dele; pressão o afasta; 'por que nunca' acusa. Uma máquina, uma comparação, tempo." },
    { pergunta: "O banco negou por faturamento. Qual conduta abre caminhos?", opcoes: [
      "'Então não dá', registrando a perda por crédito e mantendo o cliente na base para o futuro, quando o faturamento crescer",
      "Reenquadrar ('não nesse tamanho'), oferecer usada na entrada com reanálise, cooperativa ou seminova, e prometer retorno em 48 h",
      "Esperar o faturamento crescer com a obra nova e voltar ao mesmo banco no próximo semestre com números melhores e mais histórico",
      "Pedir ao gerente da concessionária que ligue para o gerente do banco, porque entre gerentes a análise costuma ser mais flexível",
    ], correta: 1, explicacao: "Cada motivo de negativa tem um caminho. Faturamento insuficiente responde a parcela menor (usada, seminova) ou a outro agente com política diferente. O consultor abre o caminho e cumpre o prazo de retorno." },
    { pergunta: "Um cliente aluga há 26 meses por R$ 13.500 mensais 'porque não tem caixa para comprar'. Qual é a resposta?", opcoes: [
      "Respeitar a decisão dele, porque aluguel sem dívida é uma escolha legítima de quem não quer financiamento",
      "Oferecer desconto na compra da nova, para a parcela ficar mais próxima do aluguel que ele já paga",
      "Fazer a conta: R$ 351 mil pagos sem patrimônio; uma seminova certificada tem parcela abaixo da metade do aluguel",
      "Sugerir que ele negocie com a locadora, porque 26 meses de fidelidade justificam uma redução no valor mensal",
    ], correta: 2, explicacao: "'Não tenho caixa' e 'pago R$ 13.500 por mês' são a mesma frase dita por quem não somou. A conta do aluguel acumulado é o remédio, e o aluguel só é certo para obra curta ou pico sazonal." },
    { pergunta: "O cliente diz 'vou pensar'. Qual é a resposta com método?", opcoes: [
      "'Tenho até sexta com essa condição; depois a tabela muda e eu não consigo segurar o valor. Assim você pensa com um prazo.'",
      "'Claro, me avisa quando decidir. Estou à disposição para qualquer dúvida, sem pressa nenhuma da minha parte.'",
      "'O que tem para pensar? A conta fechou, a máquina está reservada e a entrega pega a obra. Falta só a sua assinatura.'",
      "'Claro, é decisão grande. O que ainda não está claro: parcela, entrega, comparação ou alguém que precisa opinar?'",
    ], correta: 3, explicacao: "Concordar, explorar com opções, resolver ou marcar, e dar permissão para o 'não'. 'Me avisa' entrega o controle; confronto e prazo artificial geram sumiço." },
    { pergunta: "Qual mensagem reabre um sumiço de 20 dias?", opcoes: [
      "'E aí, viu a proposta? Ficou alguma dúvida que eu possa esclarecer? Estou por aqui.'",
      "'Só passando para saber se tem novidade. Estou à disposição para o que precisar.'",
      "Um áudio longo reexplicando a proposta com calma, para o cliente ouvir no carro sem pressa",
      "Três linhas com um fato novo real e uma pergunta orientada a 'não' ('seria loucura retomar antes da safra?')",
    ], correta: 3, explicacao: "Cobrança gera culpa e culpa gera silêncio. Valor novo com pergunta fácil gera resposta, inclusive o 'não' que libera o funil. No caso da aula, 6 de 14 responderam em 48 h." },
    { pergunta: "Por que 'entendo, mas…' anula o passo de reconhecimento?", opcoes: [
      "Porque é uma expressão informal demais para uma conversa de negócios de alto valor",
      "Porque o 'mas' apaga o 'entendo' e comunica que o vendedor só esperou a vez de rebater",
      "Porque o cliente pode achar que você concordou com a objeção e endurecer a posição",
      "Porque alonga a conversa sem avançar, quando o cliente quer uma resposta objetiva",
    ], correta: 1, explicacao: "O reconhecimento verdadeiro é uma frase completa que valida, seguida de uma pergunta de exploração, não de um contra-argumento. O 'mas' é o reflexo de rebater disfarçado." },
  ],
};
