import type { Modulo } from "./tipos";

export const M8: Modulo = {
  id: "m8", nivel: 8, titulo: "Fechamento e follow-up", tema: "Decisão", cor: "#f97316",
  descricao: "Fechar não é uma frase mágica no fim: é a consequência de um processo bem conduzido. Ler os sinais de compra, pedir a decisão de forma ética, fazer follow-up que traz valor em vez de cobrar, lidar com o 'vou pensar' e o silêncio no fechamento, cuidar do intervalo entre assinatura e faturamento (onde o arrependimento mora) e aprender com cada venda ganha ou perdida.",
  objetivos: [
    "Reconhecer sinais de compra verbais e não verbais e agir no momento certo, nem antes nem depois.",
    "Pedir a decisão com técnicas éticas (resumo, alternativa, próximo passo, pergunta direta) sem truques de pressão.",
    "Planejar o follow-up com valor em cada contato e com data combinada, nunca 'me avisa'.",
    "Conduzir o intervalo entre o 'sim' e o faturamento para evitar arrependimento e cancelamento.",
    "Fazer higiene de funil semanal: etapas reais, próximas ações datadas, negociações mortas fora.",
    "Registrar win/loss de toda negociação e transformar o padrão em ajuste de método.",
  ],
  leituras: [
    "Neil Rackham — SPIN Selling, capítulo sobre fechamento: por que técnicas de pressão reduzem o sucesso em vendas grandes.",
    "Jeb Blount — Fanatical Prospecting e Objections: follow-up com valor e a psicologia do 'sim'.",
    "Robert Cialdini — As Armas da Persuasão: coerência e compromisso no fechamento.",
    "Daniel Kahneman — Rápido e Devagar: arrependimento do comprador e como o Sistema 2 revisa decisões.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m8a1", titulo: "Sinais de compra: quando o cliente já decidiu e você ainda está apresentando", minutos: 13,
      resumo: "O cliente que pergunta 'quando entrega?' já comprou na cabeça. O vendedor que continua apresentando depois disso reabre a dúvida. Sinais verbais, sinais de corpo, sinais de processo: aprenda a ler e a parar de falar.",
      blocos: [
        { tipo: "p", texto: "Existe um momento em toda negociação em que o cliente passa de 'se' para 'como': ele para de perguntar se a máquina serve e começa a perguntar como vai ser (prazo, cor, treinamento, parcela). Esse é o sinal de compra. Rackham observou que os vendedores de alto valor fecham menos vezes e no momento certo; os medianos tentam fechar cedo (e criam resistência) ou tarde (e dão tempo para o Sistema 2 do sócio reabrir). A habilidade é reconhecer o sinal, calar a apresentação e conduzir para a ação." },
        { tipo: "tabela", titulo: "Sinais de compra no seu mercado", colunas: ["Tipo", "Sinal", "O que fazer"], linhas: [
          ["Verbal — pergunta de 'como'", "'Quando entrega?' 'Vem com o kit de dentes?' 'A parcela cai em que dia?' 'O operador treina onde?'", "Responder curto e propor o próximo passo: 'Entrega em 20 dias. Se a gente assinar até sexta, ela chega antes da chuva. Fechamos?'"],
          ["Verbal — posse", "'Essa máquina vai ficar na obra de Alegre' 'Meu operador vai gostar'", "Reforçar a posse e pedir: 'Então vamos colocar o nome da sua obra no pedido?'"],
          ["Verbal — objeção pequena", "'Só acho que a cabine podia ser mais alta' (depois de todas as grandes resolvidas)", "Não discutir; validar e avançar: 'Justo. Fora isso, o que falta para fecharmos?'"],
          ["Corpo", "Inclina-se, pega a proposta e relê, chama o sócio, sobe na máquina de novo, faz contas no papel", "Parar de falar. Silêncio. Deixar ele terminar a conta"],
          ["Processo", "Pede documentação, pergunta de assinatura, apresenta o contador, pede o laudo da usada", "Entregar tudo no mesmo dia e marcar a assinatura com hora"],
          ["Terceiros", "'Meu irmão viu a proposta e achou boa'", "Trazer o irmão para a assinatura; pedir a decisão com os dois"],
        ] },
        { tipo: "framework", nome: "Regra dos 3 sinais → pedido", origem: "Prática de fechamento consultivo (Rackham; Weinberg)", passos: [
          "Um sinal isolado pode ser curiosidade; dois começam a indicar decisão; ao terceiro sinal (verbal de 'como', posse ou processo), pare de apresentar.",
          "Confirme o terreno com um resumo curto: 'Então: a E145C resolve a parada, a parcela de 11.900 cabe com a usada, e a entrega em 20 dias pega a obra de Alegre.'",
          "Peça o próximo passo concreto: assinatura com dia e hora, documentação hoje, reserva da máquina. Uma pergunta, depois silêncio.",
          "Se ele recuar ('calma'), você aprendeu que faltava algo: volte ao E do LAER-C ('o que ainda falta?'). Pedir cedo demais custa pouco se você recua com elegância; não pedir custa a venda.",
        ] },
        { tipo: "dialogo", titulo: "Parar de apresentar", falas: [
          { quem: "cliente", texto: "E o treinamento do operador, é aqui na obra ou lá na concessionária?" },
          { quem: "vendedor", texto: "Aqui na obra, dois dias, com o técnico. E a máquina chega em 20 dias." },
          { quem: "nota", texto: "Pergunta de 'como' = sinal. Resposta curta, sem reabrir apresentação." },
          { quem: "cliente", texto: "Vinte dias… pega a obra de Alegre então. O Jonas vai gostar dessa cabine." },
          { quem: "nota", texto: "Posse ('o Jonas vai gostar') e cálculo de prazo. Segundo e terceiro sinal." },
          { quem: "vendedor", texto: "Então vamos fazer assim: eu preparo o pedido com o nome da obra de Alegre e o treinamento do Jonas. Você me manda a documentação do FINAME hoje e a gente assina quinta às 9h aqui na obra. Fechado?" },
          { quem: "cliente", texto: "Fechado." },
          { quem: "nota", texto: "Sem 'você gostaria de…', sem lista de diferenciais. Resumo, próximo passo concreto, silêncio." },
        ] },
        { tipo: "caso", titulo: "Caso: os 15 minutos a mais", situacao: "Dono de locadora perguntou 'a parcela cai em que dia?' aos 20 minutos de reunião. O vendedor respondeu e continuou apresentando: garantia, rede, histórico da marca, por mais 15 minutos.", acao: "Aos 35 minutos o cliente disse 'deixa eu ver com calma e te falo'. A apresentação extra deu tempo para a dúvida voltar. Duas semanas depois, comprou de outro.", resultado: "Na venda seguinte, o vendedor parou na primeira pergunta de 'como', resumiu em três frases e pediu a assinatura. Fechou em 25 minutos.", licao: "Depois do sinal de compra, cada minuto de apresentação é um minuto para o cliente reconsiderar. Quem fala depois do 'sim' está vendendo de volta." },
        { tipo: "checklist", titulo: "O que levar para toda reunião de fechamento", itens: [
          "Pedido preenchido (modelo, configuração, preço, condição) faltando só assinatura.",
          "Lista de documentos do financiamento com prazo de cada um.",
          "Laudo da usada assinado.",
          "Prazo de entrega confirmado por escrito com a fábrica.",
          "Agenda aberta para marcar a assinatura, a entrega técnica e o treinamento.",
          "Resumo de três frases ensaiado: dor → solução → condição.",
        ] },
        { tipo: "erros", titulo: "Erros de leitura de sinal", itens: [
          "Continuar apresentando depois da pergunta de 'como'. Você reabre a dúvida.",
          "Interpretar silêncio de cálculo como desinteresse e preencher com argumento.",
          "Tratar a objeção pequena no fim como grande. Ela é o último ajuste antes do sim; valide e avance.",
          "Pedir cedo demais, antes de qualquer sinal, com técnica de pressão. Cria resistência em venda grande.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Reveja as três últimas reuniões que fecharam e as três que não: em que minuto apareceu o primeiro sinal de compra? Você parou de apresentar? Quanto tempo passou entre o sinal e o pedido? Anote o padrão: você tende a pedir cedo, tarde ou na hora?" },
      ],
      missao: "Na próxima reunião de proposta, conte os sinais de compra. No terceiro, pare de apresentar, resuma em três frases e peça o próximo passo com dia e hora. Registre no CRM o minuto do sinal, o pedido e a resposta.",
      quiz: [
        { pergunta: "Aos 20 minutos de reunião, o cliente pergunta 'a parcela cai em que dia?'. O que isso significa e o que fazer?", opcoes: [
          "É uma pergunta de 'como' (sinal de compra); responder curto, resumir em três frases e pedir o próximo passo concreto",
          "É cedo para fechar aos 20 minutos; anotar a pergunta e responder no fim da apresentação, com o resto das condições",
          "É um sinal de que ele quer negociar a parcela; oferecer prazo maior ou carência antes que ele peça desconto",
          "É uma dúvida financeira legítima; apresentar as opções de vencimento e continuar a apresentação até o fim",
        ], correta: 0, explicacao: "Pergunta de 'como' significa que o cliente passou de 'se' para 'como'. Continuar apresentando dá tempo à dúvida (caso dos 15 minutos a mais). Responder curto e pedir a decisão com passo concreto é o que a leitura de sinal exige." },
        { pergunta: "O cliente pega a proposta, relê em silêncio e começa a fazer contas no papel. Qual é a conduta correta?", opcoes: [
          "Aproveitar o silêncio para reforçar os dois diferenciais principais, enquanto ele está concentrado na proposta",
          "Perguntar se ficou alguma dúvida, para ajudar no raciocínio e mostrar disponibilidade sem interromper demais",
          "Ficar em silêncio e deixar ele terminar; o cálculo é sinal de compra e a interrupção reabre a dúvida",
          "Explicar a conta para ele antes que termine, porque pode estar fazendo errado e chegar a um número desfavorável",
        ], correta: 2, explicacao: "Silêncio de cálculo é o cliente vendendo para si mesmo. Qualquer interrupção (explicar, reforçar, perguntar) devolve a conversa ao vendedor e tira o cliente do processo de decisão. Espere ele levantar os olhos." },
        { pergunta: "Depois de todas as objeções grandes resolvidas, o cliente diz 'só acho que a cabine podia ser um pouco mais alta'. Qual é a leitura?", opcoes: [
          "Objeção nova e séria sobre ergonomia; oferecer outro modelo com cabine maior antes que ela cresça",
          "Sinal de que ele está procurando motivo para não comprar; recuar e perguntar o que realmente o incomoda",
          "Objeção pequena no fim, típica de quem já decidiu; validar sem discutir e avançar ('fora isso, o que falta para fecharmos?')",
          "Pedido de desconto disfarçado; oferecer uma concessão pequena para compensar o detalhe da cabine",
        ], correta: 2, explicacao: "A objeção pequena no fim é o último ajuste mental antes do sim. Discutir ou trocar de modelo reabre o processo; recuar desperdiça o momento. Validar e pedir o que falta conduz ao fechamento." },
        { pergunta: "Por que Rackham observou que técnicas de fechamento por pressão reduzem o sucesso em vendas grandes?", opcoes: [
          "Porque o cliente de alto valor decide com mais gente e mais tempo, e a pressão cria resistência e desconfiança em vez de decisão",
          "Porque técnicas de pressão em contratos acima de certo valor podem ser questionadas juridicamente e anular a venda",
          "Porque o vendedor que pressiona perde a comissão quando o cliente reclama à concessionária ou à fábrica",
          "Porque os clientes de alto valor já conhecem todas as técnicas de fechamento e reagem mal a qualquer uma delas",
        ], correta: 0, explicacao: "Em venda pequena, a pressão pode funcionar porque o custo do erro é baixo. Em venda de R$ 600 mil, com sócio e banco envolvidos, a pressão gera 'vou pensar' e quebra a confiança que sustenta o resto. Fechar é pedir no momento certo, não forçar." },
        { pergunta: "Qual é o pedido de fechamento correto depois de três sinais de compra?", opcoes: [
          "'Se eu der mais 1% você assina agora? Assim a gente fecha hoje, eu seguro a máquina da fila e você garante a entrega para a obra.'",
          "'Então: a máquina resolve a parada, a parcela cabe com a usada e a entrega pega a obra. Documentação hoje e assinamos quinta às 9h. Fechado?'",
          "'Deixa eu te mostrar mais uma coisa antes de você decidir: o plano de manutenção, o kit de peças e a garantia estendida que vêm com ela.'",
          "'Você gostaria de fechar hoje ou prefere pensar mais um pouco com calma? A gente pode conversar na semana que vem, sem pressa.'",
        ], correta: 1, explicacao: "Resumo curto (dor, solução, condição), próximo passo concreto com dia e hora, uma pergunta e silêncio. 'Ou prefere pensar' oferece a saída; desconto para assinar é pressão barata; 'mais uma coisa' reabre a apresentação." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m8a2", titulo: "Pedir a decisão: técnicas éticas de fechamento", minutos: 14,
      resumo: "Fechar sem truque: o resumo, o próximo passo, a alternativa real, a pergunta direta, o teste de temperatura. Cada uma serve a um momento e a um perfil. Nenhuma delas engana; todas pedem.",
      blocos: [
        { tipo: "p", texto: "A maioria das técnicas de fechamento dos livros de 1980 ('fechamento do filhote', 'fechamento Ben Franklin', 'fechamento da suposição') foi desenhada para venda pequena e cliente sozinho. Na venda de máquina, elas soam a truque e custam a confiança. As técnicas que funcionam são as que tornam a decisão clara e fácil: resumir o que foi acordado, propor o próximo passo concreto, oferecer uma alternativa real (não uma falsa escolha), perguntar diretamente e, quando não há sinal claro, testar a temperatura. O vendedor que domina cinco formas honestas de pedir não precisa de nenhuma desonesta." },
        { tipo: "framework", nome: "Cinco pedidos éticos", origem: "Síntese de fechamento consultivo (Rackham, Weinberg, Blount), sem técnicas de pressão", passos: [
          "Resumo: 'Então: dor X, resolvida por Y, com condição Z. É isso?' → 'Sim' → 'Então vamos assinar.' Serve para todos os perfis; obrigatório antes de qualquer outro.",
          "Próximo passo: 'O próximo passo é a documentação do FINAME. Você me manda hoje e eu protocolo amanhã.' Pede ação, não 'sim'. Bom para S e C (pequeno compromisso).",
          "Alternativa real: 'Entrega em 20 dias com a caçamba padrão ou em 35 com a de rocha. Qual serve a obra?' As duas opções são reais e ambas fecham. Bom para D (controle).",
          "Pergunta direta: 'Fechamos?' / 'Vamos fazer?' Uma palavra, e silêncio. Bom para D e I; exige sinais claros.",
          "Teste de temperatura: 'De 0 a 10, quanto isso faz sentido pra você hoje?' → '7' → 'O que falta pros 3 que faltam?' Bom quando não há sinal claro; revela a objeção sem confronto.",
        ] },
        { tipo: "tabela", titulo: "Técnica × perfil × momento", colunas: ["Técnica", "Melhor perfil", "Quando", "Evitar quando"], linhas: [
          ["Resumo + 'vamos?'", "Todos", "Sempre, antes de qualquer outro pedido", "—"],
          ["Próximo passo", "S, C", "Cliente cauteloso, decisão em etapas", "Cliente D impaciente (soa a enrolação)"],
          ["Alternativa real", "D, I", "Duas configurações/prazos realmente possíveis", "Quando só há uma opção (vira falsa escolha)"],
          ["Pergunta direta", "D, I", "Três sinais claros", "Sem sinais (cria resistência); com S (pressão)"],
          ["Temperatura 0–10", "C, S", "Sem sinal claro; reunião morna", "Quando já houve sinais fortes (parece insegurança)"],
        ] },
        { tipo: "dialogo", titulo: "Temperatura e próximo passo com um perfil S", falas: [
          { quem: "vendedor", texto: "Seu Antônio, de 0 a 10, quanto essa máquina faz sentido pra vocês hoje?" },
          { quem: "cliente", texto: "Uns 8." },
          { quem: "vendedor", texto: "Oito é bom. O que falta pros outros dois?" },
          { quem: "cliente", texto: "Minha mulher quer entender melhor a parcela; ela cuida do financeiro." },
          { quem: "nota", texto: "A temperatura revelou o ratificador (a esposa) sem confronto. Agora o próximo passo é com ela." },
          { quem: "vendedor", texto: "Então o próximo passo é esse: eu passo aqui quinta às 16h com a simulação da parcela ao lado do que vocês gastam hoje, e explico pra ela com calma. Se ela ficar tranquila, a gente assina na semana que vem. Faz sentido?" },
          { quem: "cliente", texto: "Faz. Quinta às 16h ela está." },
        ] },
        { tipo: "caso", titulo: "Caso: a falsa alternativa", situacao: "Vendedor tentou o 'fechamento alternativo' de livro: 'você prefere a máquina amarela ou a amarela com o adesivo da sua empresa?'. O empreiteiro (perfil D) riu e disse: 'não tenta isso comigo'.", acao: "O vendedor pediu desculpas com humor ('foi o livro, não fui eu'), resumiu em três frases e perguntou 'fechamos?'.", resultado: "Fechou. O cliente comentou depois: 'quando você parou de fazer joguinho e perguntou direto, eu respondi'.", licao: "Alternativa só funciona se as duas opções forem reais e relevantes. Falsa escolha é truque, e cliente de máquina reconhece truque de longe." },
        { tipo: "script", titulo: "Frases de fechamento por técnica", itens: [
          "Resumo: 'Deixa eu resumir: a retro para 3 dias por mês e isso custa 10 mil; a B110B resolve com assistência a 40 km; a parcela fica em 8.700 com a sua usada. É isso? Então vamos fazer.'",
          "Próximo passo: 'O próximo passo é o laudo da usada e a documentação. Quinta eu venho fazer o laudo às 10h; você separa os documentos até lá?'",
          "Alternativa: 'Consigo a máquina da fila com entrega em 20 dias com a caçamba padrão, ou em 35 com a caçamba de rocha. Qual serve melhor a obra?'",
          "Direta: 'Fechamos?' (silêncio)",
          "Temperatura: 'De 0 a 10, quanto faz sentido hoje?' → 'O que falta para os que faltam?'",
        ] },
        { tipo: "erros", titulo: "Truques que custam a confiança", itens: [
          "Falsa alternativa ('amarela ou amarela com adesivo'): o cliente percebe e ri de você.",
          "Fechamento por suposição ('então vou preencher o pedido') sem sinal: parece atropelo.",
          "Escassez falsa ('só tenho uma na fábrica') como pedido: descoberta em dias.",
          "'Se eu conseguir X, você fecha agora?' como primeira frase: transforma a decisão em barganha.",
          "Pedir e continuar falando. Depois do pedido, silêncio absoluto.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para cada um dos seus 5 principais clientes em negociação, escolha a técnica de fechamento adequada ao perfil e ao momento, e escreva a frase exata. Ensaie em voz alta com o silêncio depois: conte até 8 sem falar." },
      ],
      missao: "Feche (ou tente fechar) duas negociações esta semana usando o resumo seguido de uma das outras quatro técnicas, adequada ao perfil. Faça silêncio depois do pedido. Registre no CRM a técnica, a resposta e o próximo passo com data.",
      quiz: [
        { pergunta: "Qual técnica de fechamento deve preceder qualquer outra, para todos os perfis?", opcoes: [
          "A pergunta direta ('fechamos?'), porque é a mais honesta e funciona com qualquer perfil",
          "A alternativa real entre duas configurações, porque dá controle ao cliente sobre a decisão",
          "O teste de temperatura de 0 a 10, porque revela o que falta antes de qualquer pedido",
          "O resumo do acordado (dor, solução, condição) confirmado pelo cliente",
        ], correta: 3, explicacao: "O resumo alinha o que foi construído e obtém um 'sim' de confirmação, que torna natural o pedido seguinte. Sem ele, a pergunta direta parece atropelo e a alternativa parece truque." },
        { pergunta: "Você propõe 'prefere a amarela ou a amarela com o adesivo da sua empresa?'. Por que isso falha com um empreiteiro perfil D?", opcoes: [
          "Porque ele prefere escolher a cor e os detalhes sozinho, e a pergunta tira dele o controle da configuração",
          "Porque é uma falsa escolha: as opções não são relevantes e o cliente reconhece o truque, perdendo a confiança",
          "Porque adesivo não faz parte da proposta padrão, e oferecer algo fora do escopo confunde a negociação",
          "Porque perfil D não gosta de decidir detalhes pequenos e a pergunta o irrita por parecer perda de tempo",
        ], correta: 1, explicacao: "Alternativa funciona quando as duas opções são reais e importam (20 dias com caçamba padrão ou 35 com caçamba de rocha). Falsa alternativa é técnica de 1980 para venda pequena; em máquina, soa a joguinho e custa o respeito." },
        { pergunta: "O cliente perfil S responde '8' ao teste de temperatura. Qual é a pergunta seguinte?", opcoes: [
          "'Ótimo, então vamos assinar; 8 já mostra que faz sentido.'",
          "'Por que não 10? O que a máquina deixou a desejar?'",
          "'O que falta pros outros dois?'",
          "'Posso melhorar a condição para chegar a 10?'",
        ], correta: 2, explicacao: "A pergunta calibrada revela o que falta (no diálogo, a esposa que cuida do financeiro) sem confronto. 'Por que não 10' acusa; 'vamos assinar' ignora os 2 pontos; melhorar condição assume que é preço quando quase nunca é." },
        { pergunta: "Depois de fazer o pedido de fechamento, qual é a regra?", opcoes: [
          "Silêncio absoluto até o cliente responder; quem fala primeiro cede",
          "Perguntar se ele precisa de mais alguma informação para decidir com segurança",
          "Reforçar os dois principais benefícios para ajudar na decisão enquanto ele pensa",
          "Oferecer um incentivo de última hora (frete, revisão) para facilitar o sim",
        ], correta: 0, explicacao: "Pedir e continuar falando anula o pedido: o cliente lê como insegurança e usa o tempo para reconsiderar. O silêncio, desconfortável para o vendedor, é o espaço em que o cliente decide." },
        { pergunta: "Qual técnica é mais adequada para um cliente cauteloso (perfil S ou C) que decide em etapas?", opcoes: [
          "Pergunta direta 'fechamos?', porque a clareza tranquiliza quem é cauteloso",
          "Alternativa entre dois prazos de entrega, porque dá ao cliente a sensação de controle",
          "Escassez real da fila de produção, porque cria um motivo externo para decidir",
          "Próximo passo concreto e pequeno (laudo da usada quinta às 10h; documentos até lá)",
        ], correta: 3, explicacao: "S e C decidem devagar e se sentem seguros com compromissos pequenos e verificáveis. Cada passo cumprido constrói o sim. A pergunta direta soa a pressão; a escassez o faz recuar." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m8a3", titulo: "Follow-up com valor: nunca 'só passando'", minutos: 13,
      resumo: "O follow-up é onde 80% das vendas de máquina se decidem e onde 80% dos vendedores cobram em vez de ajudar. Cada contato leva algo: um dado, um caso, uma simulação, um documento. E toda conversa termina com a próxima data combinada, nunca com 'me avisa'.",
      blocos: [
        { tipo: "p", texto: "Entre a proposta e a assinatura há, em média, 3 a 6 semanas e 4 a 8 contatos. É nesse intervalo que a maioria das vendas é perdida, não para o concorrente, mas para a inércia: o cliente se ocupa com a obra, o vendedor manda 'e aí?' duas vezes, o silêncio se instala e a proposta esfria. O follow-up que funciona tem três regras: valor em cada contato (o cliente ganha algo por atender), data combinada no fim de cada conversa (o próximo contato é esperado, não invasivo) e ritmo adequado ao ciclo (nem sufocar, nem sumir)." },
        { tipo: "framework", nome: "Follow-up VDR: Valor, Data, Ritmo", origem: "Blount (Fanatical Prospecting) e prática de gestão de oportunidades", passos: [
          "Valor: antes de qualquer contato, responda 'o que ele ganha por me atender?'. Simulação nova, edital, caso de cliente, prazo confirmado, resposta a uma dúvida do sócio, foto da máquina na fila. Sem valor, não ligue.",
          "Data: toda conversa termina com o próximo contato combinado e registrado. 'Te ligo quinta às 10h com a resposta do banco.' O cliente espera a ligação; não é invasão.",
          "Ritmo: proposta quente (sinais de compra): a cada 2–3 dias. Proposta em análise (banco, sócio): semanal, com fato novo. Proposta parada: cadência 7×21 (Módulo 3) e depois nutrição.",
          "Registro: cada follow-up no CRM com o valor entregue e a próxima ação datada. Negociação sem próxima ação datada é negociação morrendo.",
        ] },
        { tipo: "tabela", titulo: "Banco de valor para follow-up", colunas: ["Fase", "Valor que você pode levar"], linhas: [
          ["Depois da proposta", "Simulação com outra estrutura (carência, prazo); resposta a uma pergunta que ele fez; foto/vídeo da máquina na fila; contato de referência"],
          ["Em análise de crédito", "Status do banco; lista de documentos que aceleram; alternativa se demorar; caso de cliente que passou pelo mesmo banco"],
          ["Esperando o sócio", "Folha de uma página para o sócio; oferta de reunião com os dois; história de cliente parecido"],
          ["Esperando obra/edital", "Edital publicado; notícia da obra; conta atualizada com nova data; reserva da máquina"],
          ["Silêncio", "Fato novo real + pergunta orientada a 'não' (Módulo 7)"],
        ] },
        { tipo: "dialogo", titulo: "Terminando a conversa com data", falas: [
          { quem: "cliente", texto: "Beleza, vou olhar a proposta com calma." },
          { quem: "vendedor", texto: "Combinado. Enquanto isso, eu vou pedir ao banco a simulação com 6 meses de carência, que você comentou. Te ligo quinta às 10h com o número. Quinta está bom, ou prefere sexta?" },
          { quem: "cliente", texto: "Quinta tá bom." },
          { quem: "nota", texto: "Valor (simulação nova), data (quinta 10h) e alternativa de horário. Na quinta, a ligação é esperada — o cliente atende." },
          { quem: "vendedor", texto: "(quinta, 10h) Seu Nelson, Edy. Saiu a simulação com carência: parcela de 12.400 começando em março. Mando o print agora. Você chegou a olhar a proposta? Ficou alguma ponta solta?" },
          { quem: "cliente", texto: "Olhei. Só quero ver se a entrega segura mesmo os 20 dias." },
          { quem: "vendedor", texto: "Confirmo com a fábrica por escrito e te mando até amanhã 12h. Se confirmar, a gente assina segunda?" },
        ] },
        { tipo: "caso", titulo: "Caso: 'só passando' × 'trouxe uma coisa'", situacao: "Dois vendedores da mesma concessionária com propostas parecidas paradas há 10 dias. O primeiro mandou 'só passando pra saber se viu a proposta' três vezes. O segundo levou, a cada contato, algo: a simulação com carência, o edital da obra vizinha, o telefone do Ari.", acao: "O gerente comparou as taxas de resposta em 60 dias: 15% para o primeiro, 62% para o segundo.", resultado: "O segundo fechou 4 das 9 propostas em follow-up; o primeiro, 1 de 11. Mesmo produto, mesma região, mesmo preço.", licao: "'Só passando' pede; 'trouxe uma coisa' dá. O cliente atende quem dá." },
        { tipo: "checklist", titulo: "Antes de cada follow-up", itens: [
          "O que ele ganha por me atender hoje? (se a resposta for 'nada', busque um valor antes de ligar)",
          "Qual é a pergunta que eu quero responder nesta conversa (status do banco, sócio, prazo)?",
          "Qual é o próximo passo que vou propor, com data?",
          "A conversa anterior está registrada no CRM com o que ele disse?",
          "Estou no ritmo certo (nem 3 contatos na semana sem fato novo, nem 3 semanas de silêncio)?",
        ] },
        { tipo: "erros", titulo: "Erros de follow-up", itens: [
          "'Me avisa quando decidir.' Você nunca mais vai saber.",
          "'Só passando' / 'alguma novidade?' Cobrança disfarçada; gera silêncio.",
          "Ligar sem motivo três vezes na semana. Sufoca e desvaloriza o seu tempo.",
          "Sumir três semanas 'para não incomodar'. O concorrente incomodou e levou.",
          "Não registrar. Na quarta conversa você não lembra o que ele disse na segunda.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Abra o funil de Negociações: para cada uma em proposta/negociação, escreva o valor que você vai levar no próximo contato e a data. Se alguma não tiver próxima ação datada, resolva agora. Se para alguma você não conseguir pensar em nenhum valor, é sinal de que ela está morta (Módulo 4)." },
      ],
      missao: "Durante uma semana, nenhum follow-up sem valor e nenhuma conversa sem data combinada. Registre no CRM o valor levado em cada contato. No fim, compare a taxa de resposta com a semana anterior.",
      quiz: [
        { pergunta: "Qual é a diferença essencial entre 'só passando para saber se viu a proposta' e 'saiu a simulação com carência, te mando o print'?", opcoes: [
          "A primeira é mais educada e respeita o tempo do cliente; a segunda é mais direta e funciona melhor com perfil D",
          "A primeira pede (cobrança disfarçada) e a segunda dá (valor); o cliente atende quem dá",
          "Não há diferença relevante entre as duas; o que importa é a frequência e a regularidade do contato",
          "A segunda funciona só com clientes que pediram carência; para os outros, a primeira é a forma correta",
        ], correta: 1, explicacao: "No caso da aula, a taxa de resposta foi 15% contra 62% com a mesma proposta e o mesmo preço. Follow-up é troca: o cliente atende porque ganha algo. Cobrança, por mais educada, gera culpa e silêncio." },
        { pergunta: "Como toda conversa de follow-up deve terminar?", opcoes: [
          "Com 'qualquer coisa me avisa', para o cliente sentir liberdade e não se sentir pressionado",
          "Com o pedido de fechamento, para não perder a oportunidade enquanto o cliente está atento",
          "Com o próximo contato combinado (dia e hora) e o valor que você vai trazer nele",
          "Com um resumo dos três principais benefícios da máquina, para fixar a mensagem",
        ], correta: 2, explicacao: "'Te ligo quinta às 10h com a simulação' transforma o próximo contato em compromisso esperado, não em invasão. 'Me avisa' entrega o controle; pedir fechamento sem sinal cria resistência; resumo de benefícios é apresentação repetida." },
        { pergunta: "Uma proposta está em análise de crédito no banco há 10 dias. Qual é o ritmo e o valor adequados de follow-up?", opcoes: [
          "Semanal, com fato novo: status do banco, documentos que aceleram, alternativa se demorar",
          "Nenhum contato até o banco responder, para não pressionar o cliente nem parecer ansioso",
          "A cada 2 dias, com lembretes da validade da proposta, para manter a urgência viva",
          "Diário, perguntando se o banco respondeu, para o cliente saber que você está acompanhando",
        ], correta: 0, explicacao: "Em análise, o ritmo semanal com informação útil mantém a relação sem sufocar. Diário sem fato novo é cobrança; silêncio total abre espaço ao concorrente; lembrar a validade a cada 2 dias é pressão que o cliente não controla." },
        { pergunta: "Antes de ligar para um cliente em follow-up, você percebe que não tem nada de novo para levar. O que fazer?", opcoes: [
          "Esperar o cliente ligar, porque quem tem interesse procura e o contato sem motivo parece ansiedade do vendedor",
          "Ligar mesmo assim, porque manter contato regular é o que impede o concorrente de ocupar o espaço na cabeça do cliente",
          "Mandar uma mensagem curta de 'bom dia' para manter presença sem pedir nada, sem incomodar e sem parecer cobrança",
          "Buscar um valor antes de ligar (simulação, edital, referência, prazo) ou reconhecer que a negociação pode estar morta",
        ], correta: 3, explicacao: "Contato sem valor treina o cliente a não atender. Se depois de procurar você não encontra nada que ele ganhe por atender, a negociação provavelmente falhou nos testes de qualificação (Módulo 4) e merece encerramento com gatilho, não mais follow-up." },
        { pergunta: "Por que o registro de cada follow-up no CRM é parte do método, e não burocracia?", opcoes: [
          "Porque o gerente acompanha o preenchimento e usa os registros para avaliar o desempenho do vendedor na reunião semanal",
          "Porque sem registro você não lembra o que o cliente disse, repete perguntas, perde o fio e a negociação sem ação datada morre",
          "Porque o CRM gera os relatórios de funil e de cobertura a partir dos registros, e sem eles os números da semana ficam errados",
          "Porque o cliente pode pedir o histórico da negociação e o registro completo demonstra profissionalismo e organização",
        ], correta: 1, explicacao: "Com 15 negociações abertas e 4 a 8 contatos cada, a memória não dá conta. O registro com 'o que ele disse' e 'próxima ação datada' é o que faz a quarta conversa continuar a terceira, e é o que a Central de Alertas usa para avisar o que parou." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m8a4", titulo: "Entre o 'sim' e o faturamento: onde o arrependimento mora", minutos: 13,
      resumo: "A venda não termina na assinatura. Entre o sim e a máquina na obra passam 15 a 45 dias em que o cliente ouve o cunhado, recebe a ligação do concorrente e revê a decisão com o Sistema 2 frio. Quem conduz esse intervalo com fatos e presença entrega; quem some perde vendas assinadas.",
      blocos: [
        { tipo: "p", texto: "Kahneman descreve o arrependimento do comprador: depois de uma decisão emocional grande, o cérebro analítico revisita a escolha e procura razões para se preocupar. Na compra de uma máquina, esse período coincide com a análise do banco, a espera da fábrica e a conversa com todo mundo que tem opinião. É quando o concorrente liga 'só para saber se ainda dá tempo', o cunhado diz que 'a Cat é melhor' e o sócio pergunta 'você tem certeza?'. Vendas assinadas são canceladas nesse intervalo com mais frequência do que se admite. A resposta é um plano de acompanhamento com contatos previstos, fatos que reforçam a decisão e presença nos momentos críticos." },
        { tipo: "framework", nome: "Plano pós-assinatura (do sim à entrega)", origem: "Gestão de risco de cancelamento em bens de capital; Kahneman (arrependimento) e Cialdini (coerência)", passos: [
          "Dia 0 (assinatura): agradeça, reforce a decisão com um fato ('a máquina entrou na fila hoje; número do pedido X') e entregue o calendário: documentação, banco, faturamento, entrega, treinamento. Cliente com calendário não fica ansioso.",
          "Dia 1–3: ligação de confirmação com o contador/sócio se houver; envio da lista de documentos com prazos; contato do técnico apresentado por mensagem.",
          "Semanal: status do banco e da fábrica por mensagem curta, mesmo que 'sem mudança, dentro do prazo'. O silêncio é lido como problema.",
          "Momentos críticos: aprovação do banco (ligue você antes de o banco ligar), qualquer atraso (avise antes de o cliente perguntar; traga a alternativa), 48 h antes da entrega (confirme hora, local, quem recebe, operador para o treinamento).",
          "Reforço da decisão: ao longo do intervalo, mande um fato que confirme a escolha (foto da máquina saindo da fábrica, caso de cliente com a mesma máquina, notícia da obra dele). Cialdini: quem já decidiu quer coerência; dê a ele motivos para manter.",
          "Entrega técnica (Módulo 9): o fim do intervalo de risco e o começo da conta.",
        ] },
        { tipo: "tabela", titulo: "Sinais de arrependimento e resposta", colunas: ["Sinal", "O que está acontecendo", "Resposta"], linhas: [
          ["Cliente frio, respostas curtas depois do sim", "Sistema 2 revisitando; alguém opinou", "Ligue com um fato: prazo confirmado, número do pedido, contato do técnico. Pergunte: 'alguma coisa te deixou em dúvida desde a assinatura?'"],
          ["'Meu cunhado disse que a Cat…'", "Influência externa pós-decisão", "Não ataque o cunhado; reforce o critério dele ('você decidiu por assistência a 40 km; isso não mudou')"],
          ["Pede para 'segurar um pouco' a documentação", "Medo do compromisso financeiro", "Revisite a conta do gap; ofereça reunião com o sócio; mostre o calendário de parcelas × medições"],
          ["Concorrente ligou com preço menor", "Teste de coerência", "Compare configuração e prazo; reforce que o preço não era o critério; se preciso, cliente de referência"],
          ["Banco demora", "Ansiedade; espaço para desistência", "Ligue você com status e alternativa (outro agente) antes de ele perguntar"],
        ] },
        { tipo: "dialogo", titulo: "O cunhado", falas: [
          { quem: "cliente", texto: "Assinei, mas meu cunhado, que trabalhou com máquina a vida toda, disse que eu devia ter pego a Cat. Fiquei com uma pulga atrás da orelha." },
          { quem: "vendedor", texto: "Faz sentido ouvir quem tem experiência. Deixa eu te perguntar: quando você decidiu, o que pesou mais? Você me disse que era a assistência a 40 km, porque a última máquina ficou 40 dias parada." },
          { quem: "cliente", texto: "Foi isso." },
          { quem: "vendedor", texto: "Isso mudou? O técnico continua sendo o Diego, a 40 km; a Cat mais perta continua em Vitória. O seu cunhado provavelmente trabalhou com Cat em obra grande, onde a assistência deles é forte; aqui na região, a conta é outra. Se quiser, liga pro Ari, de Iúna, que tem a mesma máquina há dois anos, e pergunta a ele. E na semana que vem eu te mando a foto dela saindo da fábrica." },
          { quem: "nota", texto: "Sem atacar o cunhado nem a Cat. Reforço do critério que o próprio cliente definiu (coerência), fato verificável, prova social e um marco à frente." },
        ] },
        { tipo: "caso", titulo: "Caso: a E145C cancelada no dia 22", situacao: "Vendedor fechou uma E145C, comemorou e passou a cuidar de outras negociações. Não ligou por três semanas. O banco demorou, o cliente ficou ansioso, um concorrente ligou com 'entrega em 10 dias' e o cliente cancelou no dia 22.", acao: "Depois disso, o vendedor criou o plano pós-assinatura: contato semanal com status, ligação antes do banco, foto da máquina na fábrica, apresentação do técnico por mensagem.", resultado: "Nos 18 meses seguintes, zero cancelamentos em 23 vendas. Dois clientes disseram que 'quase' desistiram e a ligação semanal foi o que segurou.", licao: "A assinatura não é o fim da venda; é o começo do período de maior risco. Quem some depois do sim perde vendas que já tinha." },
        { tipo: "checklist", titulo: "Calendário entregue ao cliente no dia da assinatura", itens: [
          "Documentos do financiamento: lista, quem envia, até quando.",
          "Prazo de análise do banco e o que acontece se demorar (alternativa).",
          "Data prevista de faturamento e de entrega, confirmadas com a fábrica por escrito.",
          "Nome e WhatsApp do técnico e do gerente de peças.",
          "Data e local do treinamento do operador.",
          "Os meus contatos semanais: 'toda quinta eu te mando o status, mesmo que seja só para dizer que está tudo no prazo'.",
        ] },
        { tipo: "erros", titulo: "Erros pós-assinatura", itens: [
          "Sumir depois do sim. É o erro que mais cancela vendas.",
          "Atacar quem influenciou (cunhado, mecânico). O cliente defende a família e você vira o problema.",
          "Esconder atraso. Avise antes, com alternativa; o cliente perdoa atraso avisado e não perdoa surpresa.",
          "Deixar o banco ligar antes de você. Você deve ser a fonte da informação, boa ou ruim.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para cada venda assinada e não faturada no CRM, escreva o plano pós-assinatura: próximos três contatos com data e o fato que vai levar em cada um; os momentos críticos previstos (banco, fábrica, entrega); e o nome de quem pode influenciar o cliente nesse período (sócio, contador, cunhado, mecânico). Cadastre as ações." },
      ],
      missao: "Para toda venda assinada este mês, entregue o calendário no dia da assinatura e faça o contato semanal com status até a entrega técnica. Registre no CRM cada contato e qualquer sinal de arrependimento e como foi tratado.",
      quiz: [
        { pergunta: "Por que o intervalo entre a assinatura e o faturamento é o de maior risco de cancelamento?", opcoes: [
          "Porque o Sistema 2 do cliente revisita a decisão, ouve opiniões externas e recebe ligações de concorrentes, enquanto o vendedor some",
          "Porque a fábrica atrasa a maioria das entregas nesse período e o cliente perde a confiança no prazo prometido na assinatura",
          "Porque o contrato de compra permite desistência sem multa até o faturamento, e o cliente sabe disso e usa como margem",
          "Porque o banco costuma negar o crédito nessa fase, depois de o cliente já ter se comprometido emocionalmente com a compra",
        ], correta: 0, explicacao: "Arrependimento do comprador (Kahneman) é previsível e coincide com espera, ansiedade e influências externas. O antídoto é presença planejada com fatos que reforçam a decisão. No caso da aula, o plano pós-assinatura zerou os cancelamentos." },
        { pergunta: "O cliente diz, depois de assinar, que o cunhado experiente acha que ele devia ter comprado a Cat. Qual resposta preserva a venda?", opcoes: [
          "Explicar por que a Cat é inferior na categoria dele, com dados de consumo e assistência, para desmontar a opinião do cunhado",
          "Sugerir, com tato, que o cunhado trabalhou em obra grande e não conhece a realidade da assistência na região",
          "Oferecer um desconto ou um benefício extra para tranquilizar o cliente e reforçar que ele fez um bom negócio",
          "Validar a opinião, relembrar o critério que o próprio cliente definiu (assistência a 40 km), mostrar que ele não mudou e oferecer prova verificável",
        ], correta: 3, explicacao: "Cialdini: quem decidiu quer ser coerente. Reforçar o critério que o cliente escolheu ('você decidiu por assistência') ativa a coerência sem confronto. Atacar a Cat ou o cunhado faz o cliente defender a família; desconto sugere que ele fez mau negócio." },
        { pergunta: "O banco está demorando a aprovar. Qual é a conduta correta do vendedor?", opcoes: [
          "Enviar um lembrete da validade da proposta para acelerar a documentação e pressionar o banco por meio do cliente",
          "Esperar o banco responder para não gerar ansiedade com informações parciais que podem mudar",
          "Ligar para o cliente com o status e uma alternativa (outro agente) antes de ele perguntar, sendo a fonte da informação",
          "Pedir ao cliente que pressione o gerente do banco, porque a relação dele com a agência pesa mais que a sua",
        ], correta: 2, explicacao: "Silêncio é lido como problema; informação (mesmo 'sem mudança, dentro do prazo') é lida como controle. Ser a fonte da notícia, boa ou ruim, é o que mantém a confiança no intervalo de risco. Pressionar o cliente ou usar a validade aumenta a ansiedade." },
        { pergunta: "O que o calendário entregue no dia da assinatura faz pelo cliente?", opcoes: [
          "Reduz a ansiedade: ele sabe o que acontece, quando, com quem, e que receberá status semanal, então não precisa imaginar problemas",
          "Formaliza o compromisso e dificulta o cancelamento, porque o cliente assina o cronograma junto com o pedido",
          "Transfere para o cliente a responsabilidade pelos prazos de documentação, protegendo o vendedor de atrasos",
          "Substitui a necessidade de contatos durante a espera, porque o cliente tem tudo o que precisa por escrito",
        ], correta: 0, explicacao: "Ansiedade vem da incerteza. Documentos, prazos, nomes e o compromisso de status semanal dão ao cliente um mapa. Não impede juridicamente nada nem substitui os contatos: é o que os torna esperados." },
        { pergunta: "Um concorrente liga para o cliente depois da assinatura com preço menor e 'entrega em 10 dias'. Qual é a resposta do consultor?", opcoes: [
          "Igualar o preço com contrapartida de manter a assinatura, para não perder uma venda já fechada por uma diferença pequena",
          "Dizer que o concorrente está desesperado e que a proposta tardia mostra que ele não tem clientes",
          "Comparar configuração e prazo real, relembrar que o preço não foi o critério da decisão e, se preciso, oferecer o cliente de referência",
          "Ignorar a ligação do concorrente, porque o contrato já está assinado e qualquer reação valoriza a proposta dele",
        ], correta: 2, explicacao: "É um teste de coerência. Fatos (configuração, prazo real, critério original) e prova social respondem sem baixar o preço nem depreciar. Ignorar deixa o cliente sozinho com a dúvida; igualar preço diz que a proposta original estava errada." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m8a5", titulo: "Higiene do funil: etapas reais e próximas ações", minutos: 12,
      resumo: "O funil do CRM só serve se disser a verdade. Etapa é onde a negociação está de fato (não onde você gostaria), toda negociação tem próxima ação datada, e o que está morto sai. Trinta minutos toda segunda-feira.",
      blocos: [
        { tipo: "p", texto: "O funil de Negociações é o instrumento de voo do vendedor: cobertura, ritmo, gargalo, previsão. Mas ele mente quando a etapa é otimista ('proposta' sem proposta entregue), quando a próxima ação é 'acompanhar' (sem data, sem verbo) e quando negociações mortas ficam para o número parecer bonito. Um funil que mente dá sensação de segurança e esconde o mês ruim até o dia 25. Higiene de funil é a rotina que o mantém verdadeiro: toda segunda, 30 minutos, com critérios objetivos para cada etapa e a coragem de mover para trás e para fora." },
        { tipo: "tabela", titulo: "Critérios objetivos por etapa (o que precisa ter acontecido)", colunas: ["Etapa", "Critério de entrada", "Próxima ação típica"], linhas: [
          ["Contato / Qualificação", "Conversa com o decisor ou influenciador; ICP ≥ 5; sinal identificado", "Visita de diagnóstico marcada"],
          ["Diagnóstico / Visita", "Visita feita; dor com número; gap calculado; decisores mapeados", "Demo, medição ou proposta com data"],
          ["Proposta", "Proposta ENTREGUE (não enviada solta); reunião de revisão marcada", "Reunião de revisão / resposta ao sócio"],
          ["Negociação", "Crédito em análise ou aprovado; usada avaliada; objeções tratadas; MEDDICC ≥ 10", "Fechamento com data"],
          ["Fechamento / Assinado", "Pedido assinado; documentação em curso", "Contatos pós-assinatura semanais"],
          ["Faturado / Entregue", "Nota emitida; entrega técnica agendada", "Marcos de pós-venda (Módulo 9)"],
          ["Perdida / Desqualificada", "Motivo real registrado; gatilho e data de reabertura", "Nutrição a cada 60 dias"],
        ] },
        { tipo: "framework", nome: "Higiene semanal em 5 passos (segunda, 30 min)", origem: "Prática de pipeline review em vendas B2B", passos: [
          "Etapa verdadeira: para cada negociação, o critério de entrada da etapa aconteceu? Se não, mova para trás. Proposta enviada por WhatsApp sem reunião é 'Diagnóstico', não 'Proposta'.",
          "Próxima ação com verbo e data: 'ligar quinta 10h com simulação'; 'visitar terça 8h com laudo'. 'Acompanhar' não é ação. Sem ação datada: resolva agora ou encerre.",
          "Parados há 14+ dias sem avanço: aplicar os 4 testes de desqualificação (Módulo 4). Dois falhando: fora, com gatilho.",
          "Cobertura real: valor ponderado ÷ meta. Entre 3x e 4x é saudável. Abaixo: prospecção hoje. Acima de 5x: tem morto inflando.",
          "Gargalo: em que etapa as negociações acumulam? Muitas em diagnóstico: falta proposta (gap mal quantificado?). Muitas em proposta: falta reunião de revisão. Muitas em negociação: crédito ou fechamento. O gargalo diz o que estudar esta semana.",
        ] },
        { tipo: "dialogo", titulo: "Revisão com o gerente", falas: [
          { quem: "cliente", texto: "(gerente) Essa E215C do Vale Verde está em 'Negociação' há 40 dias. O que falta?" },
          { quem: "vendedor", texto: "Ele gostou, mas eu ainda não falei com o sócio e o banco não começou a análise." },
          { quem: "cliente", texto: "Então ela não está em Negociação. Está em Proposta, no máximo. E a próxima ação?" },
          { quem: "vendedor", texto: "'Acompanhar'." },
          { quem: "cliente", texto: "Isso não é ação. O que você vai fazer, quando?" },
          { quem: "vendedor", texto: "Marcar reunião com os dois sócios. Ligo hoje e proponho quinta às 17h com a folha de uma página." },
          { quem: "nota", texto: "A etapa otimista escondia dois buracos do MEDDICC (E e processo). A higiene os revelou em dois minutos. Sem ela, mais 40 dias de 'acompanhar'." },
        ] },
        { tipo: "caso", titulo: "Caso: cobertura de 5,8x e o mês zerado", situacao: "O funil mostrava 5,8x a meta em valor ponderado. O vendedor sentia-se seguro e reduziu a prospecção. Fechou zero naquele mês.", acao: "Na revisão, 60% do valor estava em negociações com mais de 45 dias sem avanço, etapas otimistas e 'acompanhar' como próxima ação. Depois da limpeza, a cobertura real era 1,9x.", resultado: "Com o número verdadeiro na frente, o vendedor voltou a prospectar 20 contatos por semana. Dois meses depois, cobertura real de 3,4x e três máquinas fechadas.", licao: "Funil otimista é o pior inimigo do vendedor: ele desliga o alarme exatamente quando o alarme deveria tocar." },
        { tipo: "checklist", titulo: "Checklist de segunda-feira", itens: [
          "Toda negociação tem etapa que passa no critério de entrada?",
          "Toda negociação tem próxima ação com verbo e data nos próximos 7 dias?",
          "Negociações paradas há 14+ dias: testadas e resolvidas (ação ou encerramento)?",
          "Cobertura real entre 3x e 4x? Se não, o que eu faço HOJE?",
          "Qual é o gargalo da semana e qual módulo da Academia trata dele?",
          "Perdas da semana registradas com motivo real e gatilho?",
        ] },
        { tipo: "erros", titulo: "Erros de funil", itens: [
          "Etapa pelo desejo. 'Proposta' porque você mandou um número por WhatsApp.",
          "'Acompanhar', 'aguardar', 'ver' como próxima ação. Sem verbo de ação e data, não existe.",
          "Manter morto para a cobertura. Você está mentindo para si mesmo.",
          "Pular a revisão na semana boa. É na semana boa que o funil esvazia sem você ver.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Faça a higiene completa agora: etapa verdadeira para cada negociação (mova para trás o que precisar), próxima ação com verbo e data, testes nas paradas há 14+ dias, cobertura real. Anote a cobertura antes e depois. A diferença é o tamanho da sua ilusão." },
      ],
      missao: "Institua a revisão de segunda-feira: 30 minutos, checklist da aula, todas as semanas. Registre a cobertura real de cada semana num lugar visível e a ação de prospecção decidida quando ela ficar abaixo de 3x.",
      quiz: [
        { pergunta: "Uma negociação está em 'Proposta' porque você enviou o valor por WhatsApp. Não houve reunião de revisão nem contato com o sócio. Qual é a etapa verdadeira?", opcoes: [
          "Negociação, porque o cliente já tem o preço na mão e a próxima conversa será sobre condições",
          "Diagnóstico ou Qualificação: proposta só conta quando entregue com reunião marcada e decisores mapeados",
          "Fechamento, porque falta só a resposta do cliente ao valor que ele já recebeu e analisou",
          "Proposta, porque o número foi enviado e o cliente está de posse das condições comerciais",
        ], correta: 1, explicacao: "Etapa é o que aconteceu, não o que foi enviado. Sem entrega presencial e reunião de revisão, o número por WhatsApp é um preço solto, e a negociação ainda está construindo valor e acesso. Etapa otimista infla a cobertura e esconde o buraco." },
        { pergunta: "Qual das opções é uma próxima ação válida para a higiene do funil?", opcoes: [
          "'Acompanhar a negociação semanalmente até o cliente se posicionar'",
          "'Aguardar retorno do cliente sobre a proposta enviada na semana passada'",
          "'Ver com o banco o andamento da análise de crédito do cliente'",
          "'Ligar quinta 10h com a simulação de carência e propor reunião com o sócio'",
        ], correta: 3, explicacao: "Ação tem verbo, data e conteúdo. 'Acompanhar' e 'aguardar' são a ausência de ação disfarçada; 'ver com o banco' não tem data nem resultado esperado. Negociação sem ação datada é negociação morrendo, e a Central de Alertas só ajuda se a ação existir." },
        { pergunta: "A cobertura do funil mostra 5,8x a meta. O que isso provavelmente indica?", opcoes: [
          "Que o mês está garantido e a prospecção pode diminuir para concentrar o tempo em fechar o que está aberto",
          "Que há negociações mortas ou em etapas otimistas inflando o número; a cobertura real deve ser verificada",
          "Que o vendedor está com excesso de negociações abertas e precisa de apoio para dar conta do follow-up",
          "Que a meta está baixa para o tamanho da carteira e deve ser revista para cima na próxima reunião",
        ], correta: 1, explicacao: "Cobertura saudável fica entre 3x e 4x. Acima de 5x, quase sempre há morto e otimismo. No caso da aula, a cobertura real era 1,9x e o mês fechou zerado. O número alto desliga o alarme exatamente quando ele deveria tocar." },
        { pergunta: "Muitas negociações acumulam na etapa 'Proposta' e poucas avançam. Qual é a leitura de gargalo e o que estudar?", opcoes: [
          "Falta reunião de revisão e acesso ao decisor depois da proposta; estudar diagnóstico/qualificação (Módulo 4) e proposta (Módulo 5)",
          "O preço está alto para o mercado e as propostas não avançam; estudar negociação e estrutura de financiamento (Módulo 6)",
          "Falta pós-venda e prova social para sustentar as propostas; estudar indicação e referências (Módulo 9)",
          "Falta prospecção de qualidade, e as propostas nascem de leads fracos; estudar radar e cadência (Módulo 3)",
        ], correta: 0, explicacao: "O funil diz onde estudar: acúmulo em Proposta indica propostas entregues sem reunião marcada, sem o comprador econômico ou sem valor construído. O gargalo é diagnóstico e entrega da proposta, não preço nem prospecção." },
        { pergunta: "Por que a revisão de funil não pode ser pulada na semana boa?", opcoes: [
          "Porque a semana boa é quando há mais tempo livre e a revisão pode ser feita com mais calma e profundidade",
          "Porque o gerente exige o relatório semanal independentemente do resultado, e pular gera cobrança",
          "Porque na semana boa o vendedor está fechando e não prospectando, e o funil esvazia sem que ele perceba; o resultado aparece em 60 dias",
          "Porque as negociações fechadas precisam ser arquivadas e as próximas ações de pós-venda cadastradas no mesmo dia",
        ], correta: 2, explicacao: "O mês recorde do Módulo 1 foi seguido de um mês zerado pelo mesmo motivo. A revisão semanal é o que mostra a cobertura caindo enquanto a comissão sobe, e obriga a prospecção contínua, inclusive na semana de fechamento." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m8a6", titulo: "Win/loss: aprender com cada venda ganha e perdida", minutos: 12,
      resumo: "Toda negociação encerrada é uma aula grátis, se você fizer as perguntas certas. Motivo real (não 'preço'), o que teria mudado, o que repetir. Trinta minutos por mês transformam padrão em método.",
      blocos: [
        { tipo: "p", texto: "Pergunte a um vendedor por que perdeu e ele dirá 'preço' em 80% das vezes. Pergunte ao cliente que não comprou e ele dirá preço em 20%: o resto é 'não confiei', 'o outro entendeu melhor a minha obra', 'demorou a responder', 'nunca falou com o meu sócio'. A diferença entre as duas respostas é o que você precisa aprender. O win/loss é a rotina de perguntar ao cliente (ganho ou perdido) e a si mesmo, com honestidade, o que decidiu, e depois procurar o padrão entre várias negociações. Uma perda por preço é ruído; cinco perdas 'sem falar com o sócio' é o seu próximo módulo de estudo." },
        { tipo: "framework", nome: "Win/loss em 3 camadas", origem: "Prática de win/loss analysis em vendas B2B, adaptada ao vendedor individual", passos: [
          "Camada 1 — o cliente (ligação de 5 minutos, até 7 dias depois): 'Seu Jorge, não é para reabrir nada. Quero aprender. O que pesou mais na decisão? O que eu poderia ter feito diferente?' Nas ganhas também: 'o que fez você escolher a gente?'.",
          "Camada 2 — você (10 minutos, no CRM): motivo real (não 'preço'): diagnóstico raso? decisor não mapeado? proposta sem valor? follow-up sem data? timing mal lido? concorrente com prova melhor? Marque o módulo da Academia correspondente.",
          "Camada 3 — o padrão (mensal, 30 minutos): as perdas e ganhos do mês agrupados por motivo. O motivo mais frequente de perda é o que você estuda e treina no mês seguinte (inclusive no Treino com IA do módulo). O motivo mais frequente de ganho é o que você faz mais.",
        ] },
        { tipo: "tabela", titulo: "Motivo declarado × motivo real (exemplos)", colunas: ["O que o vendedor registra", "O que o cliente diz depois", "Motivo real", "Módulo"], linhas: [
          ["Preço", "'O outro me mostrou quanto eu perdia por mês; você só mandou a tabela'", "Diagnóstico e valor", "4 e 5"],
          ["Preço", "'Meu sócio nunca conheceu você e achou caro'", "Decisor não mapeado", "4"],
          ["Concorrente", "'Ele trouxe um cliente pra eu ligar; você falou que a assistência era boa'", "Prova social", "2 e 7"],
          ["Timing", "'Ele me ligou em agosto como prometeu; você sumiu'", "Follow-up com data", "8"],
          ["Crédito", "'O outro vendedor achou um jeito no Sicoob'", "Conhecimento de financiamento", "6 e 7"],
          ["Ganha: 'preço bom'", "'Você foi o único que veio na obra e fez a conta comigo'", "Diagnóstico e conta ao vivo", "4 e 5 (repetir)"],
        ] },
        { tipo: "dialogo", titulo: "A ligação de perda", falas: [
          { quem: "vendedor", texto: "Seu Jorge, é o Edy. Não estou ligando para reabrir nada; sei que você fechou com a outra marca e desejo que dê tudo certo. Estou ligando para aprender: o que pesou mais na decisão?" },
          { quem: "cliente", texto: "Olha, o preço deles foi um pouco menor, mas não foi isso. O vendedor deles trouxe o gerente da pedreira do Zé pra conversar comigo. Eu vi a máquina funcionando lá. Você me falou da máquina, mas eu não vi." },
          { quem: "vendedor", texto: "Entendi. Se eu tivesse levado você na pedreira do Roberto, em Vargem Alta, teria mudado alguma coisa?" },
          { quem: "cliente", texto: "Provavelmente. Eu queria ver." },
          { quem: "nota", texto: "Motivo registrado: 'preço'. Motivo real: prova (visita a cliente). Módulo 5, demo e referência. Se isso aparecer três vezes no mês, é o que treinar." },
          { quem: "vendedor", texto: "Obrigado pela franqueza. Quando for trocar a retro, me chama que eu te levo pra ver antes de falar de preço." },
        ] },
        { tipo: "caso", titulo: "Caso: o padrão das seis perdas", situacao: "Vendedor registrava 'preço' em quase todas as perdas. O gerente pediu que ligasse para os últimos seis clientes perdidos.", acao: "Resultado das ligações: dois 'não confiei na assistência', dois 'nunca falou com o meu sócio', um 'demorou pra responder a proposta', um preço de verdade.", resultado: "O vendedor estudou os módulos de confiança e de mapa de decisores e passou a levar o técnico na visita e a pedir a reunião com o sócio antes da proposta. No trimestre seguinte, a conversão proposta → fechamento subiu de 22% para 41%.", licao: "'Preço' é o motivo que não dói registrar e que não ensina nada. O motivo real dói e é o único que faz você melhorar." },
        { tipo: "checklist", titulo: "Registro de win/loss no CRM (motivo de perda em lista + observação)", itens: [
          "Motivo real escolhido na lista (não 'preço' por reflexo).",
          "Frase do cliente na ligação de win/loss.",
          "O que eu teria feito diferente (uma frase).",
          "Módulo da Academia correspondente.",
          "Gatilho e data de reabertura (troca da próxima máquina, obra nova).",
          "Nas ganhas: o que o cliente disse que decidiu (para repetir).",
        ] },
        { tipo: "erros", titulo: "Erros de win/loss", itens: [
          "Não ligar para o cliente perdido 'porque é constrangedor'. É a informação mais valiosa e mais barata que existe.",
          "Registrar 'preço' sem ter perguntado. Autoengano.",
          "Ligar para reabrir a venda disfarçado de aprendizado. O cliente percebe e não fala a verdade.",
          "Fazer o win/loss e não mudar nada. Padrão identificado sem treino é diagnóstico sem remédio.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Ligue hoje para os três últimos clientes perdidos com a pergunta 'o que pesou mais?'. Registre a frase de cada um. Compare com o motivo que você tinha registrado no CRM. Em quantos o motivo real era diferente do registrado?" },
      ],
      missao: "Faça a ligação de win/loss para toda negociação encerrada nos próximos 30 dias (ganha ou perdida), registre o motivo real e o módulo correspondente, e no fim do mês identifique o padrão. Escolha o módulo do padrão e faça o Treino com IA dele três vezes.",
      quiz: [
        { pergunta: "Por que o motivo 'preço' registrado pelo vendedor raramente coincide com o que o cliente diz?", opcoes: [
          "Porque o cliente não sabe exatamente por que decidiu e cita o motivo mais fácil de explicar na ligação",
          "Porque o vendedor não tem acesso ao preço real do concorrente e registra 'preço' por falta de informação melhor",
          "Porque o cliente mente para não magoar o vendedor e cita confiança ou sócio para suavizar a decisão",
          "Porque 'preço' é o motivo que não dói registrar e não exige mudança; o cliente cita confiança, diagnóstico, sócio e follow-up",
        ], correta: 3, explicacao: "Vendedores atribuem 80% das perdas a preço; clientes, cerca de 20%. A diferença é autoproteção. No caso da aula, seis perdas 'por preço' eram cinco de método e uma de preço, e o ajuste dobrou a conversão." },
        { pergunta: "Como deve começar a ligação de win/loss para um cliente perdido?", opcoes: [
          "'Vi que você fechou com a outra marca. Posso saber quanto eles cobraram, para eu entender onde ficou a diferença?'",
          "'Ainda dá tempo de reconsiderar; consegui uma condição nova que talvez mude a sua conta. Posso te mostrar?'",
          "'Não estou ligando para reabrir nada; quero aprender: o que pesou mais na decisão?'",
          "'Acho que você tomou a decisão errada e eu queria entender por quê, para te mostrar o que ficou de fora.'",
        ], correta: 2, explicacao: "Sem intenção de reabrir, o cliente fala a verdade. Perguntar o preço do outro ou tentar reverter transforma a ligação em venda disfarçada, e a resposta vira 'preço'. Julgar a decisão fecha a porta para sempre." },
        { pergunta: "O cliente perdido diz: 'o outro vendedor trouxe o gerente da pedreira do Zé e eu vi a máquina funcionando; você só falou'. Qual é o motivo real e o módulo?", opcoes: [
          "Preço; Módulo 6, negociação, estrutura e alavancas de fechamento",
          "Prova e demonstração (referência, visita a cliente); Módulos 5 e 7",
          "Prospecção; Módulo 3, cadência, primeira mensagem e radar de sinais",
          "Pós-venda; Módulo 9, marcos, indicação e defesa da carteira",
        ], correta: 1, explicacao: "O cliente comprou o que viu. A falta foi de prova verificável: demo, visita a cliente de referência, kit de confiança. É exatamente o que os módulos de apresentação e objeções de confiança ensinam. Registrar 'preço' aqui esconderia a lição." },
        { pergunta: "Qual é a função da terceira camada do win/loss (o padrão mensal)?", opcoes: [
          "Justificar as perdas para o gerente com motivos consistentes, evitando cobranças sobre negociações isoladas do mês",
          "Calcular a taxa de conversão do mês e compará-la com a meta, para ajustar o volume de prospecção da semana seguinte",
          "Comparar o desempenho com outros vendedores da concessionária e identificar quem tem o melhor método para copiar",
          "Agrupar ganhos e perdas por motivo real e escolher o que estudar no mês seguinte; uma perda é ruído, cinco iguais são padrão",
        ], correta: 3, explicacao: "Uma perda isolada pode ser azar. O padrão (dois 'assistência', dois 'sócio') é diagnóstico do método, e o remédio é estudo e Treino com IA no módulo correspondente. Win/loss sem mudança é diagnóstico sem tratamento." },
        { pergunta: "Por que fazer win/loss também nas vendas ganhas?", opcoes: [
          "Para descobrir o que o cliente diz que decidiu ('você fez a conta comigo') e repetir de propósito o que hoje você faz por acaso",
          "Para confirmar que o preço estava correto e que a margem praticada pode ser mantida nas próximas negociações do mesmo nicho",
          "Para registrar a satisfação do cliente no CRM e enviar à fábrica como parte do programa de qualidade da concessionária",
          "Para agradecer ao cliente pela confiança e aproveitar a ligação para pedir uma indicação no momento de maior entusiasmo",
        ], correta: 0, explicacao: "O que faz você ganhar muitas vezes não é o que você acha. 'Veio na obra e fez a conta comigo' é um comportamento que dá para sistematizar. Indicação e satisfação têm seus próprios momentos (Módulo 9); a ligação de win/loss é para aprender." },
      ],
    },
  ],
  prova: [
    { pergunta: "O cliente pergunta 'quando entrega?' no meio da apresentação. Qual é a leitura e a ação?", opcoes: [
      "Sinal de compra (pergunta de 'como'); responder curto, resumir e pedir o próximo passo concreto",
      "Curiosidade natural; responder e continuar a apresentação até o fim, para não deixar nada de fora",
      "Pressão por prazo; oferecer entrega prioritária com desconto para garantir a decisão",
      "Sinal de que ele quer comparar prazos com o concorrente; perguntar o que o outro ofereceu",
    ], correta: 0, explicacao: "Pergunta de 'como' significa que o cliente passou de 'se' para 'como'. Cada minuto de apresentação depois disso é tempo para a dúvida voltar. Resumo e pedido com dia e hora." },
    { pergunta: "Qual técnica de fechamento é um truque que custa a confiança em venda de máquina?", opcoes: [
      "Resumo do acordado seguido de 'vamos?', porque induz um sim automático",
      "Alternativa entre duas configurações reais, porque limita as opções do cliente",
      "Falsa alternativa ('amarela ou amarela com adesivo') e fechamento por suposição sem sinal",
      "Teste de temperatura de 0 a 10, porque transforma a decisão em nota",
    ], correta: 2, explicacao: "Técnicas de pressão e de falsa escolha foram desenhadas para venda pequena. Cliente de máquina reconhece truque e perde o respeito. As cinco técnicas éticas pedem sem enganar." },
    { pergunta: "Depois do pedido de fechamento, o vendedor deve:", opcoes: [
      "Reforçar os benefícios principais para sustentar a decisão",
      "Oferecer um incentivo de última hora para facilitar o sim",
      "Perguntar se falta alguma informação para decidir",
      "Ficar em silêncio até o cliente responder",
    ], correta: 3, explicacao: "Quem fala depois do pedido anula o pedido. O silêncio é o espaço em que o cliente decide, e quem fala primeiro cede." },
    { pergunta: "Qual é a diferença entre follow-up com valor e cobrança?", opcoes: [
      "A cobrança é mais frequente e o follow-up com valor é mais espaçado, para não incomodar o cliente",
      "O follow-up com valor leva algo que o cliente ganha por atender (simulação, edital, referência); a cobrança pede e gera silêncio",
      "O follow-up com valor é feito por visita presencial; a cobrança é feita por WhatsApp e por isso irrita",
      "Não há diferença se a proposta for boa, porque o cliente decide pelo conteúdo e não pela forma do contato",
    ], correta: 1, explicacao: "No caso da aula, 62% contra 15% de resposta com a mesma proposta. O cliente atende quem dá. E toda conversa termina com a próxima data combinada." },
    { pergunta: "Você acabou de conversar com um cliente sobre a proposta e ele disse que vai analisar. Como você encerra essa conversa?", opcoes: [
      "Com o próximo contato combinado, com dia, hora e o valor que você vai trazer",
      "Com 'me avisa quando decidir', para o cliente ter liberdade e não se sentir pressionado",
      "Com o pedido de fechamento, para aproveitar a atenção do cliente naquele momento",
      "Com o envio da proposta de novo, para o cliente ter o documento à mão ao decidir",
    ], correta: 0, explicacao: "'Te ligo quinta às 10h com a simulação' faz o próximo contato ser esperado. 'Me avisa' entrega o controle e a venda ao acaso." },
    { pergunta: "Por que o intervalo entre assinatura e faturamento é de alto risco?", opcoes: [
      "Porque o banco nega a maioria dos créditos nessa fase e o cliente desiste antes de tentar outro caminho",
      "Porque o arrependimento do comprador, as opiniões externas e a ligação do concorrente agem enquanto o vendedor some",
      "Porque a fábrica atrasa sempre e o cliente perde a paciência com o prazo prometido na assinatura",
      "Porque o contrato não é vinculante até o faturamento e o cliente sabe que pode desistir sem custo",
    ], correta: 1, explicacao: "Kahneman: o Sistema 2 revisita decisões emocionais grandes. O plano pós-assinatura (calendário, status semanal, fatos que reforçam, presença nos momentos críticos) zerou cancelamentos no caso da aula." },
    { pergunta: "Depois de assinar, o cliente diz que o cunhado acha que ele devia ter comprado outra marca. O que fazer?", opcoes: [
      "Explicar os defeitos da outra marca com dados técnicos, para o cliente ter argumentos contra o cunhado na próxima conversa",
      "Oferecer um desconto ou benefício extra para tranquilizar o cliente e reforçar que ele fez um bom negócio, apesar da opinião",
      "Validar, relembrar o critério que o próprio cliente definiu e oferecer prova verificável (cliente de referência, foto na fábrica)",
      "Dizer que o cunhado não entende da região e que a experiência dele em obra grande não vale para a realidade do interior",
    ], correta: 2, explicacao: "Coerência (Cialdini): quem decidiu quer manter. Reforçar o critério dele ('assistência a 40 km') sem atacar ninguém. Desconto sugere mau negócio; atacar o cunhado faz o cliente defender a família." },
    { pergunta: "O banco demora a aprovar. Qual é a conduta?", opcoes: [
      "Esperar o banco responder, para não passar informação parcial que pode mudar",
      "Pedir ao cliente que pressione o gerente do banco, porque a relação dele com a agência pesa mais",
      "Enviar um lembrete da validade da proposta, para acelerar a documentação e o banco",
      "Ligar antes de o cliente perguntar, com status e alternativa (outro agente), sendo a fonte da informação",
    ], correta: 3, explicacao: "Silêncio é lido como problema. Ser a fonte da notícia, mesmo 'sem mudança, dentro do prazo', mantém a confiança no intervalo de risco." },
    { pergunta: "Uma negociação tem 'acompanhar' como próxima ação. O que a higiene do funil manda fazer?", opcoes: [
      "Manter, porque a negociação está em andamento e 'acompanhar' descreve o que de fato está sendo feito toda semana",
      "Substituir por ação com verbo, data e conteúdo ('ligar quinta 10h com simulação') ou aplicar os testes de desqualificação",
      "Mover para 'Perdida' com o motivo 'sem retorno', porque negociação sem ação concreta não tem futuro e infla o funil",
      "Delegar ao gerente a definição da próxima ação, porque ele tem visão do funil inteiro e das prioridades da concessionária",
    ], correta: 1, explicacao: "'Acompanhar' é ausência de ação disfarçada. Negociação sem ação datada morre. Se não há nada a fazer, é sinal de que ela falhou nos testes de gap, dinheiro, acesso ou momento." },
    { pergunta: "Cobertura de 5,8x a meta indica provavelmente:", opcoes: [
      "Mês garantido, com folga para reduzir a prospecção e concentrar o tempo em fechar",
      "Meta baixa para o tamanho da carteira, a ser revista para cima com o gerente",
      "Negociações mortas e etapas otimistas inflando o número; verificar a cobertura real",
      "Necessidade de mais vendedores na região, porque a demanda supera a capacidade",
    ], correta: 2, explicacao: "Saudável é entre 3x e 4x. Acima de 5x, há morto. No caso da aula, a real era 1,9x e o mês fechou zerado. O número otimista desliga o alarme." },
    { pergunta: "Muitas negociações acumulam em 'Proposta'. Qual é o diagnóstico?", opcoes: [
      "Falta pós-venda e prova social, e as propostas não têm referência de cliente para sustentar o valor apresentado",
      "Falta prospecção de qualidade, e as propostas nascem de leads sem sinal nem momento, que não têm por que decidir",
      "Propostas entregues sem reunião de revisão, sem o comprador econômico ou sem valor construído; estudar diagnóstico e proposta",
      "Preço alto para o mercado da região, e as propostas param na comparação com a concorrência mais barata",
    ], correta: 2, explicacao: "O gargalo diz onde estudar. Acúmulo em Proposta é problema de acesso ao decisor e de proposta que não se defende sozinha, não de prospecção nem de preço." },
    { pergunta: "Um cliente fechou com a concorrência. Como deve começar a sua ligação de aprendizado (win/loss) para ele?", opcoes: [
      "'Não estou ligando para reabrir nada; quero aprender: o que pesou mais?'",
      "'Quanto o concorrente cobrou? Quero entender onde ficou a diferença.'",
      "'Tenho uma condição nova, ainda dá tempo de reconsiderar.'",
      "'Você tomou a decisão errada e eu queria entender por quê.'",
    ], correta: 0, explicacao: "Sem intenção de reverter, o cliente diz a verdade, e a verdade raramente é 'preço'. A ligação disfarçada de venda gera a resposta que não ensina nada." },
    { pergunta: "Cinco perdas no mês tiveram como motivo real 'nunca falou com o sócio'. O que fazer?", opcoes: [
      "Registrar as cinco como perda por preço, porque em todas o sócio achou caro e essa foi a objeção final",
      "Estudar o mapa de decisores (Módulo 4), treinar no Treino com IA e passar a pedir a reunião com o sócio antes da proposta",
      "Aceitar que sócios ausentes são imprevisíveis e concentrar a prospecção em empresas de um único dono",
      "Reduzir o preço nas próximas propostas, para a parcela passar pelo sócio sem precisar de reunião",
    ], correta: 1, explicacao: "Um caso é ruído; cinco são padrão, e padrão é o próximo módulo de estudo. Win/loss sem mudança de método é diagnóstico sem remédio." },
    { pergunta: "Qual pedido de fechamento é adequado a um cliente perfil S depois de um '8' no teste de temperatura?", opcoes: [
      "'Fechamos agora?', porque a pergunta direta dá clareza e o perfil S precisa de segurança para decidir sem dúvida",
      "'Se eu der 1% você assina hoje?', porque a concessão pequena empurra o 8 para 10 e resolve a hesitação",
      "'O que falta pros outros dois?' e, descoberto o que falta (a esposa do financeiro), o próximo passo pequeno e datado com ela",
      "'Só tenho uma máquina na fila', porque a escassez real cria um motivo externo para o cliente cauteloso decidir",
    ], correta: 2, explicacao: "S decide em etapas e sem pressão. A pergunta calibrada revela o ratificador; o próximo passo concreto e pequeno constrói o sim. Pergunta direta, barganha e escassez fazem o S recuar." },
  ],
};
