import type { Modulo } from "./tipos";

export const M8: Modulo = {
  id: "m8", nivel: 8, titulo: "Fechamentos agressivos (com ética)", tema: "Fechamento", cor: "#ff3ea5",
  descricao: "Postura, sinais de compra, as técnicas de fechamento de alta pressão que funcionam em máquinas pesadas, concessões, fechamento por perfil e por nicho, e o roteiro completo da reunião de fechamento.",
  objetivos: [
    "Pedir a venda três vezes na mesma conversa, com técnicas diferentes, sem medo.",
    "Ler sinais de compra e usar fechamentos de teste ao longo da conversa.",
    "Dominar 12 técnicas de fechamento e saber quando usar cada uma.",
    "Conceder apenas com contrapartida e proteger a margem.",
    "Adaptar o fechamento ao perfil DISC e ao nicho do cliente.",
    "Conduzir a reunião de fechamento do início ao pós-assinatura.",
  ],
  leituras: [
    "Zig Ziglar — Secrets of Closing the Sale.",
    "Brian Tracy — The Art of Closing the Sale.",
    "Grant Cardone — The Closer's Survival Guide.",
  ],
  aulas: [
    {
      id: "m8a1", titulo: "Postura de fechador: pedir a venda sem medo", minutos: 9,
      resumo: "A maioria das vendas se perde porque o vendedor não pede. Aprenda a pedir de forma direta, calma e repetida.",
      blocos: [
        { tipo: "p", texto: "Fechar agressivamente não é gritar nem enganar — é ter a coragem de pedir a decisão, sustentar o silêncio e pedir de novo quando a resposta é “deixa eu ver”. O cliente de máquina pesada respeita quem conduz. Pedir a venda três vezes na mesma conversa, de formas diferentes, é normal e esperado neste mercado." },
        { tipo: "lista", titulo: "Princípios", itens: [
          "Assuma que vai fechar: fale de entrega, cor e treinamento como se já estivesse decidido.",
          "Pergunte e cale a boca: depois da pergunta de fechamento, quem fala primeiro perde. Sustente o silêncio.",
          "Tenha sempre um “sim pequeno” disponível: reservar a máquina, assinar a proposta, mandar os documentos pro banco.",
          "Cada “não” recebe uma pergunta: “o que precisa acontecer pra virar sim?”.",
          "Registre o compromisso: data, valor, próximo passo — no CRM e na frente do cliente.",
          "Separe a pessoa da decisão: o “não” é para a proposta, não para você. Isso tira o medo de pedir.",
        ] },
        { tipo: "script", titulo: "Sequência de 3 pedidos na mesma conversa", itens: [
          "1º (assumido): “Então, pra entregar dia 25, eu preciso dos documentos até quinta. Manda hoje pra eu adiantar?”",
          "2º (alternativo, após hesitação): “Prefere a parcela em 60 com entrada da usada ou em 48 sem entrada? Qualquer uma eu fecho hoje.”",
          "3º (condicional): “Se eu segurar a tabela de hoje e conseguir a carência de 90 dias, você assina agora?”",
        ] },
        { tipo: "p", titulo: "O medo de pedir", texto: "Vendedor não pede porque tem medo do “não” e de parecer chato. Mas o cliente que passou por diagnóstico, demonstração e proposta ESPERA que você peça — e interpreta a falta de pedido como insegurança no produto. Pedir é serviço: ajuda o cliente a decidir o que ele já quer." },
        { tipo: "caso", titulo: "Caso: a terceira pergunta", situacao: "Cliente hesitou na primeira pergunta de fechamento (“vou ver com o banco”) e na segunda (“deixa eu pensar na parcela”).", acao: "O vendedor manteve a calma e fez a terceira: “se eu conseguir a carência de 90 dias pra parcela cair depois da obra começar, você assina hoje?”.", resultado: "“Aí sim.” Assinou a proposta na mesa; documentos no banco no mesmo dia.", licao: "A venda estava na terceira pergunta. A maioria para na primeira." },
      ],
      missao: "Na próxima negociação quente, peça a venda 3 vezes na mesma conversa, com técnicas diferentes. Registre no CRM qual pedido destravou.",
      quiz: [
        { pergunta: "Depois de fazer a pergunta de fechamento, o que fazer?", opcoes: ["Explicar mais benefícios", "Ficar em silêncio e esperar a resposta", "Oferecer desconto"], correta: 1, explicacao: "O silêncio pressiona sem agredir. Quem fala primeiro entrega a decisão ao outro." },
        { pergunta: "O cliente diz “deixa eu ver”. Você:", opcoes: ["Encerra a reunião", "Faz o segundo pedido com outra técnica (alternativo)", "Repete a mesma pergunta"], correta: 1, explicacao: "Hesitação pede outra forma de perguntar, não desistência." },
      ],
    },
    {
      id: "m8a2", titulo: "Sinais de compra e fechamentos de teste", minutos: 9,
      resumo: "O cliente avisa quando está pronto — com perguntas, gestos e mudanças de tom. Use fechamentos de teste para medir a temperatura sem pressão.",
      blocos: [
        { tipo: "tabela", titulo: "Sinais de compra", colunas: ["Sinal", "O que significa", "Sua ação"], linhas: [
          ["Pergunta de entrega, prazo, cor, treinamento", "Já se vê dono", "Pergunta de fechamento na hora"],
          ["Pede desconto ou condição melhor", "Quer comprar; está negociando", "Condicional: “se eu conseguir X, fecha hoje?”"],
          ["Chama sócio/operador para ver", "Quer validação para decidir", "Apresente para o grupo e feche com o grupo"],
          ["Fala da máquina como dele (“ela vai ficar ali”)", "Posse psicológica", "Assumido: “vamos combinar a data que ela chega?”"],
          ["Relaxa, sorri, brinca sobre a compra", "Tensão caiu, decisão perto", "Resumo de valor + pergunta"],
          ["Pergunta “e se der problema?”", "Quer segurança para dizer sim", "Responda com garantia/assistência e feche"],
          ["Pega a proposta e relê a condição", "Está decidindo", "Silêncio; depois: “o que falta?”"],
        ] },
        { tipo: "p", titulo: "Fechamento de teste (trial close)", texto: "Pergunta de opinião que mede a temperatura sem pedir a decisão: “como você está vendo essa máquina pra sua operação?”, “se fosse fechar, seria a de 60 ou 48?”, “o que o Zé achou dela?”. Resposta positiva = feche. Resposta negativa = objeção descoberta cedo, antes de pedir. Use 2 ou 3 ao longo da conversa." },
        { tipo: "script", titulo: "Fechamentos de teste", itens: [
          "“Numa escala de 0 a 10, quanto essa máquina resolve o seu problema? [8] O que falta pra virar 10?”",
          "“Se a parcela couber no que ela produz, o que mais te impediria?”",
          "“Pensando na obra de segunda: com ela aqui, como ficaria?”",
        ] },
        { tipo: "erros", titulo: "Erros", itens: [
          "Ignorar o sinal e continuar apresentando. Você fala o cliente para fora da compra.",
          "Responder à pergunta de entrega com só a informação (“15 dias”) sem pedir o fechamento.",
          "Confundir pedido de desconto com objeção. Quem pede desconto quer comprar.",
        ] },
      ],
      missao: "Na próxima visita quente, use 3 fechamentos de teste ao longo da conversa e feche no primeiro sinal claro. Registre no CRM os sinais que apareceram.",
      quiz: [
        { pergunta: "Cliente pede desconto. Isso é:", opcoes: ["Objeção de preço", "Sinal de compra — ele quer comprar e está negociando", "Sinal de que vai desistir"], correta: 1, explicacao: "Quem não quer comprar não negocia. Responda com condicional." },
        { pergunta: "“De 0 a 10, quanto ela resolve o seu problema?” é:", opcoes: ["Pergunta de situação", "Fechamento de teste", "Fechamento assumido"], correta: 1, explicacao: "Mede a temperatura e revela o que falta." },
      ],
    },
    {
      id: "m8a3", titulo: "As 12 técnicas de fechamento de alta pressão", minutos: 14,
      resumo: "Assumido, alternativo, condicional, urgência real, resumo de valor, takeaway, Colombo, balanço, escada de sins, cachorrinho, ponta afiada e o fechamento do “não”. Quando usar cada uma.",
      blocos: [
        { tipo: "tabela", titulo: "Técnicas, frases e quando usar", colunas: ["Técnica", "Frase", "Quando"], linhas: [
          ["1. Assumido", "“Vou reservar a azul do pátio no seu nome e agendar a entrega técnica pra segunda. Certo?”", "Sinais de compra claros"],
          ["2. Alternativo", "“Finame em 60 ou consórcio com lance? Qual fica melhor no seu caixa?”", "Perfil D; falta só decidir a forma"],
          ["3. Condicional (“se… então”)", "“Se eu conseguir incluir o rompedor, fecha hoje?”", "Cliente pede algo; cobre o sim antes de conceder"],
          ["4. Urgência real", "“Essa condição do banco vale até dia 30 e tenho uma unidade no pátio; depois disso é 45 dias de fábrica.”", "Só com fatos verdadeiros"],
          ["5. Resumo de valor", "“Recapitulando: menos R$ 4 mil de diesel, assistência em 24 h, garantia, parcela dentro do que você produz. Sobrou algum motivo pra não fechar?”", "Antes do pedido principal; perfil C e S"],
          ["6. Takeaway (retirada)", "“Se não é o momento, sem problema — tenho outro cliente interessado nessa unidade. Prefere que eu libere pra ele?”", "Cliente enrola; a perda desperta decisão"],
          ["7. Colombo (“só mais uma coisa”)", "Na saída: “Ah, só mais uma coisa: se eu conseguir entregar antes do começo da obra, resolve?”", "Depois de um “não” suave, quando ele relaxou"],
          ["8. Balanço (Ben Franklin)", "Prós e contras no papel, com ele", "Perfil C; decisão racional travada"],
          ["9. Escada de sins", "“A aplicação está certa? A parcela cabe? A assistência resolve? Então o que falta?”", "Construir consistência antes do pedido"],
          ["10. Cachorrinho (teste)", "“Fica com ela na obra essa semana. Se não convencer, eu busco.”", "Máquina disponível; cliente S com medo de errar"],
          ["11. Ponta afiada", "Cliente: “consegue entregar até dia 20?” → “Se eu conseguir, fechamos agora?”", "Sempre que o cliente pedir algo específico"],
          ["12. Fechamento do “não”", "“Você teria alguma objeção a reservar a unidade hoje?”", "Perfil que prefere dizer não a dizer sim (Chris Voss)"],
        ] },
        { tipo: "destaque", titulo: "Agressivo ≠ desonesto", texto: "Pressão é sobre ritmo e clareza, nunca sobre mentira. Urgência inventada e concessão fingida quebram a confiança — e no interior a notícia corre. Seja duro no processo e correto nos fatos." },
        { tipo: "p", titulo: "Combinando técnicas", texto: "A sequência clássica em máquina pesada: escada de sins → resumo de valor → assumido → (hesitação) alternativo → (hesitação) condicional/ponta afiada → (enrolação) takeaway → (na saída) Colombo. Cada passo eleva a pressão um degrau. Pare quando o cliente der um “sim pequeno” e execute-o imediatamente (documentos, assinatura, reserva)." },
        { tipo: "script", titulo: "Sequência completa em uma conversa", itens: [
          "Escada: “A B95C atende a obra? [sim] A parcela de R$ 8.900 cabe no que ela vai gerar? [sim] Assistência em Cachoeiro resolve o seu medo de parar? [sim]”",
          "Resumo: “Então: máquina certa, parcela que cabe, assistência do lado. Sobrou algum motivo pra não fechar?”",
          "Assumido: “Vou reservar a do pátio e agendar a entrega pro dia 25. Manda os documentos hoje?”",
          "Hesitação → Alternativo: “Prefere 60 meses com a usada na entrada ou 48 sem entrada?”",
          "Hesitação → Condicional: “Se eu conseguir a carência de 90 dias, assina agora?”",
          "Enrolação → Takeaway: “Se não é agora, tudo bem. Tenho outro cliente na unidade — libero pra ele?”",
        ] },
        { tipo: "caso", titulo: "Caso: o takeaway que fechou em 10 minutos", situacao: "Locador em Piúma enrolava há 3 semanas com a proposta de 2 retros, sempre “semana que vem”.", acao: "O vendedor ligou: “tenho uma locadora de Guarapari querendo as duas unidades. Como você falou primeiro, te dou até amanhã meio-dia. Depois eu libero.” Era verdade.", resultado: "Ligou de volta em 10 minutos: “manda o contrato”.", licao: "Quem enrola precisa de um motivo real para decidir. A possibilidade de perder é o mais forte." },
      ],
      missao: "Escolha 3 técnicas que você nunca usou e aplique cada uma em uma negociação diferente esta semana. Anote no CRM o resultado de cada tentativa.",
      quiz: [
        { pergunta: "O cliente enrola há semanas e você tem outro interessado na unidade. Técnica indicada:", opcoes: ["Resumo de valor", "Takeaway (retirada)", "Balanço"], correta: 1, explicacao: "A possibilidade real de perder a máquina desperta a decisão em quem enrola." },
        { pergunta: "O que torna o fechamento por urgência ético?", opcoes: ["Ser dito com firmeza", "A urgência ser verdadeira (estoque, tabela, banco)", "Repetir três vezes"], correta: 1, explicacao: "Urgência falsa destrói a confiança. Verdadeira é ferramenta legítima." },
        { pergunta: "Cliente pergunta “consegue entregar até dia 20?”. Você:", opcoes: ["“Consigo”", "“Se eu conseguir, fechamos agora?” (ponta afiada)", "“Vou ver”"], correta: 1, explicacao: "Todo pedido específico do cliente é uma chance de fechar condicionalmente." },
      ],
    },
    {
      id: "m8a4", titulo: "Concessões e o fechamento do valor", minutos: 9,
      resumo: "Desconto sem contrapartida ensina o cliente a pedir mais. Como negociar mantendo margem e fechando mais rápido.",
      blocos: [
        { tipo: "lista", titulo: "Regras de concessão", itens: [
          "Nunca dê desconto sem pedir algo em troca: fechar hoje, entrada maior, indicação, a usada na troca, pagamento à vista, segunda máquina.",
          "Conceda em coisas que custam pouco e valem muito: entrega técnica reforçada, treinamento extra, prazo de entrega, primeira revisão, implemento de baixo custo.",
          "Diminua as concessões: a primeira maior, as seguintes menores — o cliente sente que chegou no limite.",
          "Tenha o “não” pronto: “Esse já é o melhor que consigo; o que posso fazer é X”.",
          "Nunca conceda rápido. Concessão fácil parece que ainda tem mais.",
          "Registre cada concessão no CRM: o cliente vai lembrar na próxima compra.",
        ] },
        { tipo: "tabela", titulo: "Moedas de troca (do mais barato para você ao mais caro)", colunas: ["Moeda", "Custo para você", "Valor percebido"], linhas: [
          ["Treinamento extra do operador", "Baixo", "Alto (segurança)"],
          ["Primeira revisão / kit de filtros", "Baixo", "Alto (“cuidado”)"],
          ["Prioridade de entrega", "Baixo", "Alto (prazo da obra)"],
          ["Implemento simples (caçamba extra, dentes)", "Médio", "Alto"],
          ["Avaliação melhor da usada", "Médio", "Muito alto (entrada)"],
          ["Carência / prazo maior (via banco)", "Baixo para você", "Muito alto (caixa)"],
          ["Desconto no preço", "Alto (margem, comissão)", "Médio (esquece rápido)"],
        ] },
        { tipo: "script", titulo: "Trocando concessão por fechamento", itens: [
          "“Consigo melhorar em R$ 8 mil se fecharmos hoje e a usada entrar na troca. Fechado?”",
          "“Desconto não tenho, mas coloco a primeira revisão e o treinamento do operador. Isso resolve?”",
          "“Se você me indicar dois empreiteiros da sua região com máquina cansada, eu incluo a caçamba extra. Combinado?”",
          "“Esse já é o meu limite. O que posso fazer é priorizar a sua entrega e garantir a carência de 90 dias. Fechamos assim?”",
        ] },
        { tipo: "destaque", titulo: "Margem é seu salário", texto: "Cada R$ 10 mil de desconto desnecessário é comissão sua indo embora e cliente aprendendo que basta insistir. Negocie valor, não preço." },
        { tipo: "caso", titulo: "Caso: os R$ 15 mil que viraram R$ 2 mil", situacao: "Cliente pediu R$ 15 mil de desconto na E215C “porque a Sany deu”.", acao: "O vendedor não deu desconto. Ofereceu primeira revisão, treinamento de 2 operadores e prioridade de entrega (custo real de ~R$ 2 mil) em troca de fechar naquele dia com a usada na entrada.", resultado: "Fechou. O cliente relatou depois que “o pacote foi o que decidiu”.", licao: "Valor percebido vence desconto. Troque moedas baratas por fechamento." },
      ],
      missao: "Na próxima negociação de valor, faça uma concessão apenas com contrapartida explícita e registre no CRM o que você recebeu em troca.",
      quiz: [
        { pergunta: "O cliente pede desconto. Melhor resposta:", opcoes: ["“Posso dar 5%.”", "“Consigo melhorar se fecharmos hoje com a usada na troca.”", "“Não dou desconto.”"], correta: 1, explicacao: "Concessão sempre com contrapartida. Assim o desconto vira ferramenta de fechamento, não de erosão." },
        { pergunta: "Qual moeda tem custo baixo para você e valor alto para o cliente?", opcoes: ["Desconto no preço", "Treinamento extra e primeira revisão", "Nada"], correta: 1, explicacao: "Concessões de serviço protegem margem e são lembradas." },
      ],
    },
    {
      id: "m8a5", titulo: "Fechamento por perfil DISC e por nicho", minutos: 10,
      resumo: "O mesmo fechamento que funciona com a pedreira assusta o produtor de café. Adapte técnica, ritmo e moeda ao perfil e ao nicho.",
      blocos: [
        { tipo: "tabela", titulo: "Fechamento por perfil DISC", colunas: ["Perfil", "Técnicas que funcionam", "Evite", "Frase"], linhas: [
          ["D", "Alternativo, assumido, ponta afiada, takeaway", "Resumo longo, balanço", "“60 ou 48? Fecho agora.”"],
          ["I", "Assumido com prova social, urgência real, Colombo", "Planilha, frieza", "“Vou reservar a sua e agendar a foto da entrega com a equipe.”"],
          ["S", "Escada de sins, resumo de segurança, cachorrinho, passo pequeno", "Takeaway, urgência forte", "“Vamos só mandar os documentos pro banco, sem compromisso, pra ver a condição?”"],
          ["C", "Balanço, resumo de valor com dados, condicional documentado", "Assumido cedo, pressão emocional", "“Com esses dados, faz sentido avançarmos para a análise de crédito?”"],
        ] },
        { tipo: "tabela", titulo: "Fechamento por nicho", colunas: ["Nicho", "Momento", "Técnica", "Moeda"], linhas: [
          ["Construtora / empreiteira", "Antes do início da obra", "Urgência real (prazo da obra), condicional de entrega", "Prioridade de entrega, treinamento"],
          ["Pedreira", "Após demonstração medida", "Resumo de valor com número medido, assumido", "Peças de giro, atendimento 24 h"],
          ["Prefeitura", "Após pesquisa de preços / antes do prazo legal", "Resumo de valor institucional, urgência real (prazo do processo)", "Garantia estendida, treinamento da garagem"],
          ["Produtor de café", "Entre colheita e plantio", "Escada de sins, passo pequeno, consórcio/crédito rural com carência", "Carência até a safra, avaliação da usada"],
          ["Locadora", "Quando há fila de locação", "Alternativo (1 ou 2 unidades), takeaway (unidade disputada)", "Condição de frota, revenda"],
          ["Pequeno terraplenador", "Quando fecha serviço novo", "Condicional com a usada, cachorrinho", "Usada na entrada, primeira parcela alongada"],
        ] },
        { tipo: "script", titulo: "Três fechamentos, três nichos", itens: [
          "Pedreira (D): “Você mediu: 6 caçambas contra 9. São 4 caminhões a mais por dia. Reservo a E215C e mando os documentos hoje ou prefere que eu traga o contrato amanhã cedo?”",
          "Café (S): “Sem pressa. Vamos só fazer o seguinte: eu monto o consórcio com lance na safra e a carência. Você olha com calma com a Dona Maria, e semana que vem, se estiver tudo certo, a gente assina. Pode ser?”",
          "Prefeitura (C): “Secretário, com a ata e o prazo do processo, a entrega fica antes da chuva se o empenho sair até dia 15. Posso deixar a documentação com o setor de compras hoje?”",
        ] },
        { tipo: "caso", titulo: "Caso: o takeaway errado", situacao: "Vendedor usou takeaway (“tenho outro cliente na unidade”) com um produtor de café perfil S.", acao: "O cliente se sentiu pressionado, disse “então vende pra ele” e sumiu por 6 meses.", resultado: "A venda saiu só no ano seguinte, com outro vendedor, em consórcio.", licao: "Técnica certa no perfil errado é a forma mais rápida de perder uma venda quente." },
      ],
      missao: "Para as 5 negociações mais quentes do CRM, anote o perfil DISC e o nicho e escolha a técnica e a moeda de fechamento de cada uma antes da próxima conversa.",
      quiz: [
        { pergunta: "Produtor de café perfil S hesitando. Fechamento indicado:", opcoes: ["Takeaway", "Passo pequeno com segurança (documentos sem compromisso, carência)", "Urgência forte"], correta: 1, explicacao: "S precisa de segurança e tempo. Pressão espanta." },
        { pergunta: "Dono de pedreira perfil D depois da demonstração medida:", opcoes: ["Balanço de prós e contras", "Resumo com o número medido + alternativo", "Esperar ele pensar"], correta: 1, explicacao: "D quer resultado e decisão rápida." },
      ],
    },
    {
      id: "m8a6", titulo: "A reunião de fechamento: roteiro completo", minutos: 11,
      resumo: "Preparação, ambiente, documentos na mão, ordem de fala, planos B e o que fazer nos 10 minutos depois do sim (ou do não).",
      blocos: [
        { tipo: "checklist", titulo: "Antes da reunião", itens: [
          "Comitê completo confirmado (decisor, financeiro, operador se relevante).",
          "Pré-análise de crédito feita; alternativas (consórcio, outro banco) mapeadas.",
          "Usada avaliada e valor fechado com a concessionária.",
          "Proposta de uma página impressa em 2 vias + contrato/pedido pronto para assinar.",
          "Lista de documentos do banco impressa.",
          "Respostas às 3 objeções mais prováveis preparadas.",
          "Moedas de troca definidas (o que posso conceder e em troca de quê).",
          "Meu limite e meu plano B (o que faço se ele disser não).",
          "Horário de manhã, ambiente calmo (não na obra com barulho, não às 18h).",
        ] },
        { tipo: "tabela", titulo: "Ordem da reunião (30 minutos)", colunas: ["Minuto", "O que fazer"], linhas: [
          ["0–3", "Rapport curto e objetivo declarado: “hoje a ideia é decidir. Se for sim, saímos com os documentos encaminhados; se for não, sem problema.”"],
          ["3–8", "Escada de sins: aplicação, parcela, assistência, prazo — confirmações rápidas."],
          ["8–12", "Resumo de valor com a conta (uma folha nas mãos deles)."],
          ["12–15", "Condição final e pedido assumido. Silêncio."],
          ["15–25", "Objeções/pedidos → condicional e concessões com contrapartida. Segundo e terceiro pedidos."],
          ["25–30", "Sim: assinatura, documentos, data de entrega, foto. Não: motivo real, data de retorno, próximo passo registrado."],
        ] },
        { tipo: "lista", titulo: "Nos 10 minutos depois do sim", itens: [
          "Assine ali. Sim sem assinatura é intenção; intenção esfria.",
          "Peça os documentos do banco na hora (foto pelo celular serve para começar).",
          "Agende a entrega técnica com data e quem vai receber.",
          "Mova a negociação no CRM para a etapa correta e registre o valor e as condições.",
          "Reduza o arrependimento: “você fez a escolha certa; vou te mandar hoje o cronograma até a entrega”.",
          "Peça a indicação suave: “conhece alguém que esteja na mesma situação que você estava?”.",
        ] },
        { tipo: "lista", titulo: "Se for não", itens: [
          "Agradeça sem drama. “Entendo. Posso perguntar o que pesou? Quero aprender.”",
          "Isole a última vez: “se X mudasse, faria sentido?”. Às vezes o não vira sim aqui.",
          "Combine data de retorno concreta e registre no CRM como perdida com motivo e a data de retorno na próxima ação.",
          "Mantenha a porta aberta: contato de valor a cada 60 dias.",
          "Analise depois: qual módulo desta trilha teria mudado o resultado?",
        ] },
        { tipo: "caso", titulo: "Caso: o contrato no carro", situacao: "Cliente disse sim na obra, às 17h. O vendedor não tinha o pedido impresso e combinou “passo amanhã com o contrato”.", acao: "À noite o cunhado do cliente falou que a marca X era mais barata. No dia seguinte, “deixa eu pensar mais um pouco”.", resultado: "Fechou 3 semanas depois, com R$ 6 mil de desconto que não precisaria dar.", licao: "Contrato e lista de documentos ficam sempre no carro. Sim é para assinar na hora." },
      ],
      missao: "Prepare a próxima reunião de fechamento com o checklist completo (comitê, pré-análise, usada, contrato impresso, moedas, plano B). Conduza pela ordem de 30 minutos e registre o resultado e o motivo no CRM.",
      quiz: [
        { pergunta: "O cliente disse sim na obra e você não tem o pedido em mãos. Você:", opcoes: ["Combina de voltar amanhã", "Formaliza na hora (assinatura na proposta, foto dos documentos) — contrato fica sempre no carro", "Manda por e-mail à noite"], correta: 1, explicacao: "Sim sem assinatura esfria. Formalize no ato." },
        { pergunta: "Como abrir a reunião de fechamento?", opcoes: ["Com a ficha técnica", "Declarando o objetivo: decidir hoje, sim ou não", "Com uma piada"], correta: 1, explicacao: "Objetivo declarado cria compromisso e evita o “vou pensar”." },
        { pergunta: "Cliente disse não. Primeira coisa:", opcoes: ["Dar desconto", "Perguntar o que pesou e isolar (“se X mudasse, faria sentido?”)", "Ir embora"], correta: 1, explicacao: "O motivo real e o isolamento podem virar o não — ou dar a data certa de retorno." },
      ],
    },
  ],
  prova: [
    { pergunta: "Quantas vezes é normal pedir a venda na mesma conversa em máquinas pesadas?", opcoes: ["Uma", "Três, com técnicas diferentes", "Nenhuma, o cliente pede"], correta: 1, explicacao: "Pedir é serviço; a maioria fecha no segundo ou terceiro pedido." },
    { pergunta: "Cliente pergunta a cor disponível. Isso é:", opcoes: ["Curiosidade", "Sinal de compra — feche", "Objeção"], correta: 1, explicacao: "Já se vê dono." },
    { pergunta: "“Se eu incluir a primeira revisão, fecha hoje?” é:", opcoes: ["Assumido", "Condicional", "Takeaway"], correta: 1, explicacao: "Se… então: cobra o sim antes de conceder." },
    { pergunta: "Regra de ouro das concessões:", opcoes: ["Dar rápido para fechar", "Sempre com contrapartida e em ordem decrescente", "Nunca conceder"], correta: 1, explicacao: "Concessão sem contrapartida ensina a pedir mais." },
    { pergunta: "Takeaway em cliente perfil S costuma:", opcoes: ["Fechar rápido", "Espantar — use passo pequeno e segurança", "Não ter efeito"], correta: 1, explicacao: "Técnica certa no perfil errado perde a venda." },
    { pergunta: "O que fica sempre no carro?", opcoes: ["Catálogo", "Pedido/contrato e lista de documentos do banco", "Brindes"], correta: 1, explicacao: "Sim é para assinar na hora." },
  ],
};
