import type { Modulo } from "./tipos";

export const M9: Modulo = {
  id: "m9", nivel: 9, titulo: "Pós-venda, expansão e indicação", tema: "Carteira", cor: "#10b981",
  descricao: "A primeira venda custa caro; a segunda, a terceira e as indicações pagam a carreira. Entrega técnica que vira referência, marcos de 30/60/180/365 dias com NPS, upsell e cross-sell no momento certo, defesa da conta contra o concorrente, indicação e prova social como sistema, e a construção de autoridade na região.",
  objetivos: [
    "Executar uma entrega técnica que gere satisfação medida e o primeiro pedido de indicação.",
    "Cumprir os marcos de pós-venda (30/60/180/365 dias) com pergunta de NPS e ação sobre a resposta.",
    "Identificar e propor upsell (máquina maior, segunda unidade) e cross-sell (implementos, rolo, peças, plano de manutenção) no gatilho certo.",
    "Defender a conta contra o concorrente com presença, dados de operação e antecipação da troca.",
    "Transformar clientes satisfeitos em provas sociais organizadas (lista de referências por nicho, depoimentos, visitas).",
    "Construir autoridade regional: associações, cooperativas, grupos, conteúdo útil e dias de campo.",
  ],
  leituras: [
    "Fred Reichheld — A Pergunta Definitiva (NPS): uma pergunta que prevê crescimento.",
    "Bill Cates — Get More Referrals Now: indicação como processo, não como sorte.",
    "Lincoln Murphy — Customer Success: o cliente que atinge o resultado dele é o que compra de novo.",
    "Jill Konrath — Selling to Big Companies, capítulo sobre expansão de conta: crescer dentro de quem já confia.",
  ],
  aulas: [
    // ───────────────────────────── AULA 1 ─────────────────────────────
    {
      id: "m9a1", titulo: "Entrega técnica: o dia que define a conta", minutos: 13,
      resumo: "A entrega é a primeira prova de que tudo o que você prometeu era verdade. Operador treinado, dono presente, técnico apresentado, números de partida registrados. Feita com capricho, ela vira referência; feita às pressas, vira o primeiro chamado de assistência.",
      blocos: [
        { tipo: "p", texto: "O cliente lembra de duas coisas: o dia em que a máquina chegou e o primeiro problema. Se a entrega for um caminhão que descarrega e vai embora, o primeiro problema vem em uma semana (operador que não conhece os comandos, óleo errado, ajuste não feito) e a conta começa com desconfiança. Se a entrega for um evento (o dono, o operador, o técnico, a primeira hora de operação acompanhada, os números de partida anotados), o cliente sente que comprou uma relação, não um equipamento, e é nesse dia que ele conta para o vizinho." },
        { tipo: "framework", nome: "Entrega técnica em 7 passos", origem: "Prática de entrega de bens de capital (commissioning) adaptada à obra", passos: [
          "Antes (48 h): confirme hora, local, quem recebe, operador presente, implementos corretos, óleo e combustível, documentos (nota, manual, garantia, plano de manutenção).",
          "Chegada: dono e operador presentes; técnico da concessionária apresentado pelo nome e com WhatsApp entregue. Foto da máquina com o dono (com autorização) para o CRM e, se ele quiser, para a prova social.",
          "Inspeção conjunta: checklist com o cliente: níveis, filtros, horímetro (anote as horas de partida), acessórios. Ele assina o checklist.",
          "Treinamento do operador: 2 a 4 horas na aplicação real: comandos, modos de trabalho, manutenção diária (níveis, graxa, filtros), o que nunca fazer. O operador assina a lista de presença.",
          "Primeira hora de operação acompanhada: o técnico observa e ajusta. Meça e registre o consumo da primeira hora (é o número de partida para o marco de 30 dias).",
          "Plano de manutenção explicado: 50 h, 250 h, 500 h; quem faz, quanto custa, como agendar. Cadastre a próxima revisão no CRM.",
          "Fechamento: 'Qualquer coisa, primeiro me chama; depois o Diego.' Combine o contato de 7 dias. Pergunte, de forma leve: 'Quem mais da sua turma está com máquina pra trocar?' (primeiro pedido de indicação, no momento de maior satisfação).",
        ] },
        { tipo: "dialogo", titulo: "Entrega que vira referência", falas: [
          { quem: "vendedor", texto: "Seu Ari, essa é a sua E145C. Antes de ligar, vamos conferir juntos: horímetro em 3,2 horas, que é o teste de fábrica; óleo e filtros conferidos; caçamba de 0,8 m³ como no pedido. Assina aqui pra mim que está tudo certo?" },
          { quem: "cliente", texto: "Tudo certo. Só quero ver o Jonas operando." },
          { quem: "vendedor", texto: "Esse é o Diego, técnico da região, ele vai passar a manhã com o Jonas. Diego, esse é o Ari; o WhatsApp dele já está no seu celular. E a primeira hora a gente mede o consumo, pra ter o número de partida." },
          { quem: "nota", texto: "Checklist assinado, técnico apresentado pelo nome, operador treinado na aplicação, número de partida registrado. O cliente vê método." },
          { quem: "cliente", texto: "(fim da manhã) O Jonas já tá carregando caminhão. Consumo deu 13 e pouco." },
          { quem: "vendedor", texto: "13,4 na primeira hora, vai melhorar com o operador acostumado. Em 30 dias eu volto pra conferir. Aproveitando o dia bom: quem mais da sua turma está com máquina pra trocar?" },
          { quem: "cliente", texto: "O Paulinho, de Castelo, reclama toda semana da Hyundai dele." },
        ] },
        { tipo: "caso", titulo: "Caso: a entrega de 15 minutos", situacao: "Vendedor entregou uma B110B 'rapidinho' porque tinha outra visita: o caminhão descarregou, o vendedor entregou a chave e foi embora. O operador não conhecia o modo de trabalho da retro.", acao: "Em 5 dias: operador quebrou um cilindro por uso indevido, o cliente ligou irritado, a garantia não cobria e a relação começou com uma briga sobre R$ 9 mil.", resultado: "O cliente nunca indicou ninguém e comprou a máquina seguinte de outra marca. No win/loss disse: 'a entrega mostrou que, depois de vender, vocês somem'.", licao: "A entrega é a primeira promessa cumprida ou a primeira quebrada. Duas horas a mais no dia da entrega valem anos de conta." },
        { tipo: "checklist", titulo: "Checklist de entrega (assinado pelo cliente)", itens: [
          "Modelo, série, configuração e implementos conferidos com o pedido.",
          "Horímetro de partida anotado; níveis e filtros verificados.",
          "Manual, garantia, plano de manutenção e nota entregues e explicados.",
          "Técnico e gerente de peças apresentados com contato.",
          "Operador treinado (lista de presença): comandos, modos, manutenção diária, o que nunca fazer.",
          "Consumo da primeira hora medido e registrado.",
          "Próxima revisão cadastrada; contato de 7 dias combinado; foto (com autorização).",
        ] },
        { tipo: "destaque", titulo: "A regra das duas horas", texto: "A entrega técnica leva, no mínimo, duas horas a mais do que 'descarregar e ir embora'. Essas duas horas são o investimento com maior retorno de toda a venda: definem o primeiro chamado (ou a ausência dele), a nota do marco de 30 dias, a primeira indicação e se o cliente vai contar do dia da máquina para o vizinho com orgulho ou com raiva. Nunca marque outra visita para o dia da entrega." },
        { tipo: "erros", titulo: "Erros de entrega", itens: [
          "Entregar sem o operador presente. Ele vai aprender sozinho, errado.",
          "Não apresentar o técnico. Na primeira dúvida o cliente liga para você, e você não é a assistência.",
          "Não anotar os números de partida (horas, consumo). Sem eles, o marco de 30 dias não tem comparação.",
          "Pular o pedido de indicação no dia da entrega. É o momento de maior satisfação do ciclo.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Reveja as três últimas entregas que você fez: quantos dos sete passos aconteceram? Para a próxima entrega no CRM, monte o roteiro completo com horários e responsáveis (você, técnico, operador, dono) e o pedido de indicação escrito." },
      ],
      missao: "Na próxima entrega, execute os sete passos com checklist assinado, operador treinado na aplicação, técnico apresentado e consumo da primeira hora registrado no CRM. Faça o pedido de indicação específico ao fim e cadastre o lead indicado.",
      quiz: [
        { pergunta: "Qual é o principal risco de uma entrega técnica feita em 15 minutos, sem operador presente e sem apresentar o técnico?", opcoes: [
          "O primeiro problema surge em dias (uso indevido, ajuste não feito) e a conta começa com desconfiança; o cliente conclui que 'depois de vender, vocês somem'",
          "A garantia de fábrica pode ser questionada, porque a entrega técnica com checklist assinado é exigência formal para a cobertura",
          "O vendedor perde a comissão da entrega, que na maioria das concessionárias só é paga com o checklist e a lista de presença",
          "O cliente reclama da falta de cortesia com o gerente da concessionária, e a relação começa com um desgaste desnecessário",
        ], correta: 0, explicacao: "No caso da aula, um cilindro quebrado em 5 dias e uma briga de R$ 9 mil definiram a conta: zero indicações e a próxima máquina de outra marca. A entrega é a primeira promessa cumprida ou quebrada." },
        { pergunta: "Por que registrar o consumo da primeira hora e o horímetro de partida na entrega?", opcoes: [
          "Porque o cliente pode pedir reembolso do combustível usado na primeira hora, e o registro serve de comprovante",
          "Porque o CRM só permite fechar a entrega técnica com os campos de horímetro e consumo preenchidos",
          "Porque a fábrica exige os dados de partida para ativar a garantia e registrar o início da vida útil da máquina",
          "Porque são os números de partida que permitem comparar no marco de 30 dias e provar que o resultado calculado na venda está acontecendo",
        ], correta: 3, explicacao: "O marco de 30 dias pergunta 'o consumo ficou dentro do que calculamos?'. Sem número de partida, não há comparação, e sem comparação não há satisfação medida, que é o gatilho da indicação e da prova social." },
        { pergunta: "Qual é o melhor momento do ciclo para o primeiro pedido de indicação?", opcoes: [
          "Na assinatura do contrato, quando o entusiasmo é máximo e o cliente ainda não teve tempo de encontrar defeitos",
          "No primeiro chamado de assistência resolvido, quando o cliente sente alívio e gratidão pelo atendimento rápido",
          "No dia da entrega técnica bem feita, com o operador já produzindo e o dono satisfeito",
          "Seis meses depois da compra, quando o cliente já esqueceu o preço pago e a máquina virou parte da rotina",
        ], correta: 2, explicacao: "A entrega é o pico de satisfação: máquina nova, operador treinado, dono orgulhoso. Um pedido específico ('quem da sua turma está com máquina pra trocar?') rende nome na hora. Na assinatura ainda não há resultado; no chamado há problema." },
        { pergunta: "O que o checklist de entrega assinado pelo cliente representa?", opcoes: [
          "Um método visível: o cliente vê que a entrega tem processo, confere cada item e registra o estado inicial, o que gera confiança",
          "Uma exigência do financiamento, porque o banco precisa da comprovação de entrega para liberar o pagamento à concessionária",
          "Uma proteção jurídica contra reclamações futuras, porque o cliente assinou que recebeu a máquina em ordem",
          "Um documento interno da concessionária, usado pela assistência para registrar o início da garantia e das revisões",
        ], correta: 0, explicacao: "A assinatura formaliza, mas o valor principal é a percepção de método e o registro conjunto do estado inicial (horímetro, níveis, implementos). Cliente que confere junto sente que comprou uma relação, não um equipamento." },
        { pergunta: "O operador não pode estar presente no dia agendado da entrega. O que o consultor faz?", opcoes: [
          "Entrega mesmo assim, deixa o manual e um vídeo de operação para o operador estudar antes de começar a trabalhar",
          "Reagenda a entrega ou combina o treinamento do operador com o técnico em até 48 horas, antes de a máquina entrar em produção plena",
          "Treina o dono ou o encarregado no lugar do operador, para alguém da empresa poder repassar os comandos depois",
          "Cancela a entrega até o operador estar disponível, mesmo que leve semanas, porque máquina sem treinamento é risco",
        ], correta: 1, explicacao: "Máquina operada por quem não foi treinado é o caminho mais curto para o primeiro chamado. Reagendar ou garantir o treinamento em 48 h protege a máquina e a conta. Manual não substitui 2 a 4 horas na aplicação; semanas de atraso custam produção ao cliente." },
      ],
    },
    // ───────────────────────────── AULA 2 ─────────────────────────────
    {
      id: "m9a2", titulo: "Marcos 30/60/180/365 e a pergunta do NPS", minutos: 13,
      resumo: "Pós-venda não é 'passar para dar um oi'. É uma sequência de marcos com objetivo, pergunta e ação: 30 dias (resultado de partida), 60 (primeira revisão e operador), 180 (custo real e expansão), 365 (renovação da relação e planejamento da próxima máquina). E em cada um, a pergunta de 0 a 10.",
      blocos: [
        { tipo: "p", texto: "Fred Reichheld descobriu que uma única pergunta ('de 0 a 10, quanto você recomendaria a gente para um amigo?') prevê o crescimento de uma empresa melhor do que pesquisas longas. Para o vendedor, o NPS é ainda mais útil: quem responde 9 ou 10 é promotor (peça indicação agora); 7 ou 8 é neutro (pergunte o que faltou para 10 e resolva); 0 a 6 é detrator (pare tudo e resolva antes que ele conte para a região). Os marcos de pós-venda são os momentos certos de perguntar, e a Central de Alertas do CRM avisa quando cada um vence." },
        { tipo: "tabela", titulo: "Os quatro marcos", colunas: ["Marco", "Objetivo", "O que checar", "Pergunta", "Ação típica"], linhas: [
          ["30 dias", "Resultado de partida", "Consumo × calculado; horas; operador adaptado; algum chamado?", "'De 0 a 10?' + 'o consumo ficou como calculamos?'", "Promotor: indicação específica. Neutro: resolver o que faltou"],
          ["60 dias", "Primeira revisão (50 h) e operação", "Revisão feita? Custo? Operador com dúvida? Peças de desgaste?", "'A revisão foi como esperava?'", "Agendar 250 h; cross-sell de kit de desgaste"],
          ["180 dias", "Custo real e expansão", "Custo/hora real × TCO da venda; produção; obras novas; frota", "'A conta que fizemos está batendo?' + 'e a próxima obra?'", "Upsell/cross-sell no gatilho; depoimento com número"],
          ["365 dias", "Renovação e planejamento", "Horas acumuladas; revenda estimada; plano do cliente para o ano", "'Como foi o ano com ela?' + 'o que vem em 2027?'", "Plano de troca em 3–5 anos; segunda máquina; referência oficial"],
        ] },
        { tipo: "framework", nome: "Roteiro de marco em 4 tempos (20 minutos)", origem: "Customer Success (Murphy) e NPS (Reichheld) adaptados ao vendedor de campo", passos: [
          "Dado antes da opinião: chegue com os números (horas no horímetro, consumo medido, chamados registrados) e compare com a venda. 'Calculamos 14 L/h; está dando 13,6.' Satisfação medida é a que vira prova.",
          "Pergunta do NPS e o porquê: 'De 0 a 10, quanto você recomendaria a gente?' e, qualquer que seja a nota, 'o que faria virar 10?'.",
          "Ação conforme a nota: 9–10, pedido de indicação específico e autorização para usar como referência. 7–8, resolver o que faltou com data. 0–6, escutar tudo, não se defender, plano de correção em 24 h e retorno pessoal.",
          "Olhar para a frente: 'e a próxima obra?', 'a frota vai crescer?', 'quando a outra máquina vai precisar de troca?'. É aqui que a expansão nasce.",
        ] },
        { tipo: "dialogo", titulo: "Marco de 30 dias com um neutro", falas: [
          { quem: "vendedor", texto: "Seu Ari, 30 dias: 212 horas no horímetro, consumo médio de 13,6 contra os 14 que calculamos. Um chamado, resolvido em 20 horas. De 0 a 10, quanto você recomendaria a gente?" },
          { quem: "cliente", texto: "Uns 7. A máquina é ótima. Mas o chamado demorou mais do que eu esperava; o Diego só veio no dia seguinte." },
          { quem: "vendedor", texto: "Justo. Vinte horas foi dentro do prazo por escrito, mas eu entendo que na hora parece uma eternidade. O que faria virar 10?" },
          { quem: "cliente", texto: "Saber na hora quando o técnico vem. Eu fiquei no escuro até ele chegar." },
          { quem: "vendedor", texto: "Isso eu resolvo hoje: vou combinar com a assistência que todo chamado seu recebe uma mensagem com a previsão de chegada em até 1 hora. E te ligo na sexta pra confirmar que ficou combinado." },
          { quem: "nota", texto: "Dado antes, pergunta, porquê, ação com data. O 7 tem chance real de virar 9 no marco de 60 dias. E o problema (falta de previsão) vai melhorar o processo para todos os clientes." },
        ] },
        { tipo: "caso", titulo: "Caso: o detrator que virou promotor", situacao: "No marco de 60 dias, cliente de Iúna deu nota 4: a primeira revisão custou mais do que ele entendeu na venda e o operador reclamava do ar-condicionado.", acao: "O vendedor não se defendeu. Ouviu tudo, anotou, e em 24 horas voltou com: detalhamento da revisão (parte era peça de desgaste por uso em pedra, explicada), ajuste do ar-condicionado pelo técnico (regulagem, não defeito) e uma revisão de 250 h com o preço fechado por escrito.", resultado: "No marco de 180 dias, nota 9. O cliente indicou dois vizinhos e aceitou ser referência para a região. Disse: 'o que me convenceu foi você voltar em um dia com tudo resolvido'.", licao: "Detrator bem tratado vira o promotor mais convicto, porque ele viu o que acontece quando dá errado. Detrator ignorado vira o pior vendedor do concorrente." },
        { tipo: "checklist", titulo: "Antes de cada marco", itens: [
          "Horas no horímetro (pergunte ao operador por mensagem no dia anterior).",
          "Consumo medido (telemetria ou abastecimento) e o número calculado na venda.",
          "Chamados abertos e tempo de resposta (peça à assistência).",
          "Revisões feitas e próximas, com custo.",
          "Obras, frota e planos do cliente (o que ele contou da última vez, registrado no CRM).",
          "Pergunta do NPS pronta e as três ações possíveis conforme a nota.",
        ] },
        { tipo: "erros", titulo: "Erros de marco", itens: [
          "'Passar para dar um oi.' Sem dado, sem pergunta, sem ação: é visita social, não pós-venda.",
          "Se defender diante de um detrator. Ele quer ser ouvido; a defesa confirma que você não ouve.",
          "Perguntar o NPS e não agir. Perguntar cria expectativa; não agir é pior do que não perguntar.",
          "Deixar a Central de Alertas avisar e ignorar. Marco vencido há 20 dias é sinal de que a conta está à venda para o concorrente.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Abra a Central de Alertas e liste os marcos de pós-venda vencidos. Para cada um, levante os dados (horas, consumo, chamados) antes de ligar. Faça três marcos esta semana com a pergunta do NPS e registre a nota e a ação no CRM." },
      ],
      missao: "Cumpra todos os marcos de pós-venda vencidos na Central de Alertas com o roteiro de 4 tempos. Registre no CRM a nota de 0 a 10, o 'o que faria virar 10' e a ação com data. Para cada 9 ou 10, faça o pedido de indicação específico.",
      quiz: [
        { pergunta: "No marco de 30 dias, o cliente dá nota 7 e diz que o chamado demorou. Qual é a sequência correta?", opcoes: [
          "Oferecer um desconto na próxima revisão para compensar a demora do chamado e recuperar a nota no marco seguinte",
          "Anotar a nota, agradecer a franqueza e perguntar de novo no marco de 60 dias, quando a impressão do chamado já passou",
          "Explicar que 20 horas estava dentro do prazo contratual de atendimento e seguir para os dados de consumo e produção",
          "Reconhecer, perguntar o que faria virar 10, resolver o que ele pediu com data e retornar para confirmar",
        ], correta: 3, explicacao: "O neutro tem um motivo concreto e quase sempre resolúvel (falta de previsão de chegada). 'O que faria virar 10?' revela; a ação com data e o retorno transformam. Defender o prazo confirma que você não ouve; desconto não resolve o problema; esperar 30 dias é deixar a insatisfação envelhecer." },
        { pergunta: "Por que chegar ao marco com os dados (horas, consumo, chamados) antes de perguntar a opinião?", opcoes: [
          "Para demonstrar controle da conta e impressionar o cliente com a quantidade de informação que você tem sobre a máquina dele",
          "Porque a satisfação medida ('calculamos 14, está dando 13,6') é a que vira prova social e indicação; opinião sem dado é impressão do dia",
          "Porque o CRM exige os dados de horas, consumo e chamados para registrar o marco como cumprido na Central de Alertas",
          "Para evitar que o cliente reclame de coisas que não pode provar, porque os números mostram que a máquina está entregando",
        ], correta: 1, explicacao: "O marco existe para confirmar que o resultado prometido na venda está acontecendo. Com dado, a nota 9 vem acompanhada de um número que o cliente vai repetir para o vizinho. Sem dado, o marco vira visita social." },
        { pergunta: "Um cliente dá nota 4 no marco de 60 dias. Qual é a conduta correta?", opcoes: [
          "Ouvir tudo sem se defender, anotar, voltar em 24 horas com plano de correção e retorno pessoal",
          "Explicar ponto a ponto por que cada reclamação não procede, com os dados de atendimento e o contrato de garantia em mãos",
          "Encaminhar as reclamações para a assistência técnica e acompanhar a resolução por mensagem, sem se envolver diretamente",
          "Registrar a nota, reduzir a frequência do contato para não irritar mais e retomar a relação no marco de 180 dias",
        ], correta: 0, explicacao: "O detrator bem tratado vira o promotor mais convicto (nota 4 virou 9 e duas indicações no caso da aula). Defesa confirma o problema; delegar sem presença é abandono; reduzir contato entrega o cliente ao concorrente e à antipropaganda." },
        { pergunta: "O que o marco de 180 dias tem de diferente dos anteriores?", opcoes: [
          "É o único marco em que se pergunta o NPS, porque a máquina já tem histórico suficiente para uma nota justa",
          "É quando a garantia de fábrica termina e o plano de manutenção passa a ser a principal oferta da visita",
          "É o marco do custo real (custo/hora × TCO da venda) e da expansão: 'e a próxima obra?', depoimento com número, upsell e cross-sell",
          "É apenas uma visita de cortesia, porque nos 180 dias a máquina já está estabilizada e o cliente não precisa de acompanhamento",
        ], correta: 2, explicacao: "Aos 180 dias há histórico suficiente para comparar custo real com o calculado, e o cliente já tem visão do ano: obras novas, frota, sócio. É o momento em que a segunda venda nasce, e em que o depoimento tem número." },
        { pergunta: "Qual é o erro mais grave relacionado à pergunta do NPS?", opcoes: [
          "Perguntar o NPS antes de apresentar os dados de horas e consumo, porque a nota fica contaminada pela impressão do dia",
          "Perguntar por mensagem em vez de pessoalmente, porque o cliente responde com menos sinceridade quando não está cara a cara",
          "Perguntar em todos os marcos, porque a repetição cansa o cliente e a nota deixa de refletir a satisfação real",
          "Perguntar e não agir sobre a resposta: cria expectativa e a frustra, o que é pior do que não perguntar",
        ], correta: 3, explicacao: "A pergunta é um compromisso implícito: 'sua opinião vai mudar algo'. Nota registrada sem ação é o sinal mais claro de que o pós-venda é burocracia. Perguntar em todos os marcos é correto; a ordem (dado antes) é preferível, mas o erro fatal é não agir." },
      ],
    },
    // ───────────────────────────── AULA 3 ─────────────────────────────
    {
      id: "m9a3", titulo: "Upsell e cross-sell: crescer dentro de quem já confia", minutos: 13,
      resumo: "Vender a segunda máquina para quem já comprou custa um quinto de vender a primeira para quem não conhece. Máquina maior, segunda unidade, implementos, rolo para complementar, plano de manutenção, peças: cada um tem um gatilho e uma conta. O erro é empurrar; o método é ouvir o gatilho.",
      blocos: [
        { tipo: "p", texto: "Estudos de vendas B2B repetem o mesmo número: conquistar um cliente novo custa de 5 a 7 vezes mais do que vender de novo para um existente, e a conversão em conta existente fica entre 60% e 70%, contra 5% a 20% em conta nova. No seu mercado isso significa: o empreiteiro que comprou a E145C vai precisar de um rolo quando pegar pavimentação, de uma segunda escavadeira quando a frente dobrar, de implementos quando o serviço mudar, e de trocar a E145C em 4 anos. Quem está presente nos marcos ouve os gatilhos antes de qualquer concorrente saber que existem." },
        { tipo: "tabela", titulo: "Gatilhos de expansão e a oferta certa", colunas: ["Gatilho (o que você ouve no marco)", "Oferta", "A conta que sustenta"], linhas: [
          ["'Peguei a pavimentação de X km'", "Cross-sell: rolo compactador (CA2500/CC1200)", "Aluguel de rolo × parcela; disponibilidade na própria obra"],
          ["'Abri uma segunda frente / dobrou o serviço'", "Upsell: segunda máquina (igual ou maior)", "Produção da frente nova × custo de não pegar / de terceirizar"],
          ["'Estou usando ela em rocha / demolição'", "Cross-sell: caçamba de rocha, rompedor, garra", "Desgaste da caçamba padrão × vida útil; produção por hora"],
          ["'A máquina antiga está dando trabalho'", "Troca da antiga (usada na entrada) + padronização da frota", "Custo da inação da antiga; peças e operador comuns"],
          ["'Não tenho tempo de cuidar da manutenção'", "Plano de manutenção / contrato de revisões", "Custo de corretiva × preventiva; disponibilidade"],
          ["'A revisão de 500 h vem aí'", "Kit de peças de desgaste, filtros, óleo original", "Parada evitada; garantia preservada"],
          ["'Estou sem espaço pra estocar peça'", "Estoque consignado de desgaste (para frotas)", "Tempo de parada × custo de estoque"],
        ] },
        { tipo: "framework", nome: "Expansão em 4 passos (sem empurrar)", origem: "Land and expand (vendas B2B) adaptado a frotas de máquinas", passos: [
          "Ouça o gatilho no marco: obra nova, frente nova, serviço novo, máquina antiga reclamando, revisão chegando. Anote no CRM como oportunidade, não como pedido.",
          "Faça a conta do gatilho com o cliente, como na primeira venda: aluguel do rolo × parcela; produção da segunda frente × custo de não pegar. A expansão tem que se pagar sozinha.",
          "Proponha no ritmo dele: 'quando você fechar a pavimentação, me chama que eu trago a conta do rolo' é melhor do que 'já que você vai pavimentar, compra um rolo'. Cliente que confia chama.",
          "Use a relação como alavanca de condição, não de pressão: 'como você já é cliente, a segunda tem entrega prioritária e o técnico já conhece a sua obra'. Padronização (mesma marca, mesmas peças, mesmo operador) é o argumento de frota.",
        ] },
        { tipo: "dialogo", titulo: "O gatilho no marco de 180 dias", falas: [
          { quem: "vendedor", texto: "E a próxima obra, seu Marcos? Como está a fila?" },
          { quem: "cliente", texto: "Ganhei a pavimentação de Alegre, 9 km. Vou ter que alugar um rolo." },
          { quem: "vendedor", texto: "Nove quilômetros, uns 5 meses de obra? Quanto está o aluguel de rolo por mês?" },
          { quem: "cliente", texto: "Uns 9 mil." },
          { quem: "vendedor", texto: "Cinco meses, 45 mil de aluguel, e no fim você devolve. Um CA2500 fica em parcela de 7.800 e é seu; e pavimentação vai aparecer de novo, porque agora você tem a referência de Alegre. Quando a ordem de serviço sair, eu trago a conta completa e a disponibilidade. Te chamo ou você me chama?" },
          { quem: "nota", texto: "Ouviu o gatilho, fez a conta rápida com os números dele, propôs no ritmo dele. Nenhum 'aproveita que'. O cliente que confia vai chamar." },
          { quem: "cliente", texto: "Me chama quando sair. Deve ser em 20 dias." },
        ] },
        { tipo: "caso", titulo: "Caso: a pedreira que virou frota", situacao: "Pedreira em Vargem Alta comprou uma W170B em 2023. O vendedor cumpriu todos os marcos e ouviu, aos 180 dias, que a produção ia dobrar com um contrato novo.", acao: "Fez a conta da segunda pá com o gerente de produção (caminhões por hora × margem), propôs padronização (mesma máquina, peças e operadores intercambiáveis) e entrega prioritária. Aos 365 dias, ouviu que a escavadeira antiga da pedreira 'estava dando trabalho' e trouxe a conta da E245C com a antiga na entrada.", resultado: "Em 24 meses: duas W170B, uma E245C, um plano de manutenção para as três e estoque consignado de desgaste. Cinco vendas com uma prospecção. O custo de venda dessas quatro últimas foi o das visitas de marco.", licao: "A conta se expande no ritmo em que você está presente. Cada marco cumprido é uma prospecção dentro de quem já confia." },
        { tipo: "checklist", titulo: "Mapa de expansão da conta (revisar a cada marco)", itens: [
          "Frota atual: modelo, ano, horas, quem opera, quando vence a vida útil de cada uma.",
          "Serviços atuais e novos (obras, contratos, licitações em curso).",
          "Implementos que faltam para o serviço atual.",
          "Manutenção: quem faz, custo de corretivas nos últimos 6 meses.",
          "Oportunidades ouvidas, com gatilho e data prevista.",
          "Próximo marco e o que perguntar nele.",
        ] },
        { tipo: "erros", titulo: "Erros de expansão", itens: [
          "'Aproveita que…': empurrar no marco transforma pós-venda em venda e o cliente passa a evitar a visita.",
          "Não fazer a conta. A segunda venda também precisa se pagar; a confiança não substitui o número.",
          "Ignorar cross-sell pequeno (kit, implemento, plano). É margem boa e fideliza; e abre a porta da máquina seguinte.",
          "Não registrar o gatilho com data. 'Deve ser em 20 dias' sem lembrete é oportunidade perdida para quem ligar primeiro.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Para os seus 10 maiores clientes, preencha o mapa de expansão: frota com horas e vida útil, serviços, implementos, manutenção. Marque em cada um a oportunidade mais provável nos próximos 12 meses e o gatilho que a dispara. Cadastre como oportunidade no CRM com data de revisão." },
      ],
      missao: "Em três marcos de pós-venda esta semana, pergunte 'e a próxima obra?' e ouça o gatilho. Para cada gatilho, faça a conta rápida com o cliente e registre a oportunidade no CRM com a data prevista e a oferta (upsell ou cross-sell). Não empurre nada; combine quem chama quem.",
      quiz: [
        { pergunta: "No marco de 180 dias, o cliente diz que ganhou uma pavimentação de 9 km e vai alugar um rolo. Qual é a conduta com método?", opcoes: [
          "Dizer 'aproveita que você vai pavimentar e compra um rolo, tenho um na fila para entrega em 15 dias e condição de cliente'",
          "Perguntar prazo da obra e valor do aluguel, fazer a conta rápida (aluguel × parcela) e propor a conta completa quando a ordem sair",
          "Enviar a proposta do rolo por WhatsApp no mesmo dia, com a conta do aluguel acumulado e a condição especial de cliente da casa",
          "Anotar a informação e esperar ele pedir, porque pós-venda não é hora de vender e o cliente sabe onde encontrar você quando precisar",
        ], correta: 1, explicacao: "Ouvir o gatilho, fazer a conta com os números dele e propor no ritmo dele. 'Aproveita que' transforma o marco em venda e o cliente passa a evitar a visita; proposta imediata pula a conta; esperar sem registrar entrega o gatilho ao concorrente." },
        { pergunta: "Por que a venda para conta existente tem conversão muito maior e custo muito menor do que para conta nova?", opcoes: [
          "Porque a confiança já existe, você conhece a operação e ouve os gatilhos antes do concorrente; o custo é o das visitas de marco",
          "Porque a fábrica dá desconto de fidelidade na segunda máquina, o que torna a proposta imbatível para quem já tem a marca na frota",
          "Porque o cliente existente não compara preços com a mesma intensidade, já que conhece a assistência e confia no vendedor que o atende",
          "Porque o cliente existente tem um compromisso implícito de manter a frota padronizada, o que praticamente garante a segunda compra",
        ], correta: 0, explicacao: "Não há obrigação nem desconto automático: há relação e informação. O cliente existente compara, sim, mas chama você primeiro. No caso da pedreira, quatro vendas seguiram uma prospecção, ao custo das visitas de marco." },
        { pergunta: "Qual é o argumento específico de frota que a expansão dentro da mesma marca oferece?", opcoes: [
          "Preço menor por volume, negociado com a fábrica para frotas acima de duas máquinas da mesma marca",
          "Garantia estendida automática para a segunda máquina, como reconhecimento pela fidelidade do cliente",
          "Padronização: mesmas peças, mesmo técnico, operadores intercambiáveis, estoque de desgaste comum, menos parada",
          "Revenda garantida pela concessionária ao fim do financiamento, o que reduz o risco da segunda compra",
        ], correta: 2, explicacao: "Frota padronizada reduz estoque, treinamento e tempo de parada. É a conta que o gerente de produção entende e o argumento que o concorrente com uma máquina isolada não tem. Desconto por volume pode existir, mas não é o argumento central." },
        { pergunta: "Qual é o erro mais comum com cross-sell pequeno (kit de peças, implemento, plano de manutenção)?", opcoes: [
          "Cobrar preço acima da tabela, porque o cliente de máquina nova não compara o valor de peças e implementos",
          "Oferecer sem consultar o técnico, porque o kit ou o implemento errado gera problema e desgasta a relação",
          "Oferecer em todos os marcos, porque a repetição transforma a visita de pós-venda em visita de venda",
          "Ignorá-lo por parecer pouco, perdendo margem boa, fidelização e a porta de entrada da máquina seguinte",
        ], correta: 3, explicacao: "Kit de desgaste antes da revisão de 500 h, caçamba de rocha quando o serviço muda, plano de manutenção para quem não tem tempo: cada um resolve um problema real, tem margem e mantém você presente. É o cross-sell que faz o cliente pensar em você quando a máquina grande vier." },
        { pergunta: "A confiança da conta substitui a necessidade de fazer a conta na segunda venda?", opcoes: [
          "Sim; cliente que confia compra pelo relacionamento, e a conta detalhada pode até soar como desconfiança",
          "Sim, para cross-sell pequeno (kit, implemento); não, para máquina, porque o valor exige análise do sócio",
          "Não; a expansão também precisa se pagar sozinha, e a conta com os números dele é o que mantém a confiança para a terceira venda",
          "Não, porque o sócio ou o financeiro exige a conta mesmo quando o dono já decidiu pela relação",
        ], correta: 2, explicacao: "Relação abre a porta; a conta fecha e mantém a porta aberta. Uma segunda máquina vendida 'na confiança' que não se paga é a última venda para aquela conta. Mesmo o kit de peças tem uma conta (parada evitada × custo)." },
      ],
    },
    // ───────────────────────────── AULA 4 ─────────────────────────────
    {
      id: "m9a4", titulo: "Defesa da conta: o concorrente também visita o seu cliente", minutos: 12,
      resumo: "O cliente que você conquistou é o alvo preferido do concorrente: já tem máquina, já tem crédito, já compra. Defender a conta é presença nos marcos, dados de operação que ninguém mais tem, antecipação da troca e uma relação com mais gente do que só o dono.",
      blocos: [
        { tipo: "p", texto: "Os clientes da sua carteira estão na lista de prospecção de todos os concorrentes, com um sinal muito forte: 'já compra máquina nova'. Eles vão visitar, oferecer avaliação da sua máquina para troca, prometer entrega rápida e preço menor. A defesa não é falar mal deles nem pedir lealdade: é ser tão presente e tão útil que a visita do concorrente pareça um incômodo. Quem tem os números da operação do cliente (horas, consumo, custo real), quem antecipa a troca antes de a máquina dar problema e quem conhece o operador, o mecânico e o sócio é quem fica com a próxima compra." },
        { tipo: "framework", nome: "As 5 camadas de defesa", origem: "Account management defensivo (Konrath; prática de key accounts)", passos: [
          "Presença nos marcos: 30/60/180/365 cumpridos sem falha. Cliente visitado quatro vezes ao ano por você e uma vez pelo concorrente não muda.",
          "Dados que só você tem: custo/hora real, consumo medido, histórico de chamados e revisões, valor de revenda estimado. Ao concorrente, o cliente diz 'o Edy tem a conta inteira da minha máquina'.",
          "Antecipação da troca: a partir de 6.000–8.000 horas (ou 4 anos), traga o plano de troca antes de a máquina dar problema, com a usada valendo o máximo. Concorrente chega quando ela já está quebrando; você chega antes.",
          "Relação em rede: operador, mecânico, sócio, contador, encarregado. Se você só conhece o dono, uma mudança de humor perde a conta. Se conhece cinco pessoas, a conta tem cinco defensores.",
          "Reação rápida a problema: a conta se perde no chamado mal atendido, não na visita do concorrente. Cada problema resolvido com presença é uma camada a mais.",
        ] },
        { tipo: "tabela", titulo: "Sinais de conta em risco", colunas: ["Sinal", "O que costuma significar", "Ação em 48 h"], linhas: [
          ["Cliente menciona 'vendedor da outra marca passou aqui'", "Prospecção ativa do concorrente", "Marco extra com dados; pergunta aberta: 'o que ele te ofereceu?' sem depreciar"],
          ["Marco vencido há 20+ dias sem contato", "Você abriu a porta", "Visita esta semana com dado e pergunta do NPS"],
          ["Chamado mal resolvido ou reclamação sem retorno", "Insatisfação crescendo", "Resolver pessoalmente; plano em 24 h; retorno"],
          ["Pede avaliação da máquina 'só para saber'", "Está cotando troca, talvez com outro", "Avaliar com laudo e trazer o plano de troca com você"],
          ["Sócio novo, gerente novo, mecânico novo", "Relação precisa ser reconstruída", "Apresentar-se, ouvir, mapear de novo"],
          ["Comprou implemento ou peça de outro fornecedor", "Sua presença diminuiu", "Marco com o gerente de frota; cross-sell com conta"],
        ] },
        { tipo: "dialogo", titulo: "'O vendedor da Cat passou aqui'", falas: [
          { quem: "cliente", texto: "O vendedor da Cat passou aqui semana passada. Ofereceu avaliar a E145C pra troca e disse que entrega em 15 dias." },
          { quem: "vendedor", texto: "Que bom que você me contou. O que ele te ofereceu de concreto?" },
          { quem: "nota", texto: "Sem 'a Cat é cara' nem 'ele só quer te tirar de mim'. Pergunta aberta." },
          { quem: "cliente", texto: "Nada fechado. Avaliar a máquina e mostrar uma 320." },
          { quem: "vendedor", texto: "Faz sentido ouvir. Deixa eu te dar o que você vai precisar pra comparar: a sua E145C tem 5.800 horas, custo por hora real de R$ 168 nos últimos 12 meses (eu tenho o histórico), e vale entre 380 e 400 mil na troca hoje. Se a ideia é trocar em 2027, vale trocar antes de passar de 8.000 horas, com ela no valor máximo. Quer que eu monte o plano de troca com a E175C, pra você ter a comparação na mão quando ele voltar?" },
          { quem: "nota", texto: "Dados que só ele tem, antecipação da troca e a oferta de montar a comparação. O concorrente vai encontrar um cliente com a conta pronta." },
        ] },
        { tipo: "caso", titulo: "Caso: a conta perdida no chamado", situacao: "Cliente antigo, três máquinas, nunca visitado pelo concorrente com sucesso. Um chamado de assistência ficou 4 dias sem retorno num feriado prolongado; o vendedor estava de férias e ninguém cobriu.", acao: "Nada foi feito até o vendedor voltar. O cliente, com máquina parada na safra da pedreira, aceitou a visita do concorrente que 'apareceu na hora certa' e alugou uma máquina dele para cobrir.", resultado: "A máquina seguinte foi do concorrente. Doze anos de conta perdidos em quatro dias de silêncio.", licao: "A conta se perde no problema mal atendido, não na visita do concorrente. Cobertura de férias, técnico com contato direto e reação em 24 horas são a defesa que importa." },
        { tipo: "checklist", titulo: "Defesa da carteira (revisão mensal)", itens: [
          "Todos os marcos do mês cumpridos? Algum vencido?",
          "Para cada máquina da carteira: horas atuais e previsão de troca (6.000–8.000 h ou 4 anos).",
          "Contas com sinal de risco na tabela: ação registrada?",
          "Para cada conta grande: quantas pessoas eu conheço além do dono?",
          "Chamados do mês: algum sem retorno em 24 h? Resolvido pessoalmente?",
          "Quem cobre a minha carteira nas minhas férias? O cliente sabe o nome?",
        ] },
        { tipo: "erros", titulo: "Erros de defesa", itens: [
          "Pedir lealdade ('depois de tudo que eu fiz…'). Lealdade se merece nos marcos, não se cobra.",
          "Depreciar o concorrente que visitou. O cliente passa a esconder as visitas de você.",
          "Achar que conta antiga está segura. É a mais visada.",
          "Conhecer só o dono. Mudança de humor, sócio novo ou gerente novo derrubam a conta.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste as 10 maiores contas da carteira. Para cada uma: última visita, próximo marco, horas da máquina mais antiga e previsão de troca, número de pessoas que você conhece na empresa, sinais de risco. Marque as três mais vulneráveis e cadastre uma ação de defesa para cada uma esta semana." },
      ],
      missao: "Identifique as três contas mais vulneráveis (marco vencido, máquina acima de 6.000 horas, só o dono conhecido) e faça uma ação de defesa em cada uma esta semana: marco com dados, plano de troca antecipado ou apresentação a outra pessoa da empresa. Registre no CRM.",
      quiz: [
        { pergunta: "O cliente conta que o vendedor da concorrente passou e ofereceu avaliar a máquina para troca. Qual é a resposta que defende a conta?", opcoes: [
          "Agradecer por contar, perguntar o que foi oferecido e trazer os dados que só você tem (custo/hora, horas, valor de troca) com o plano de troca",
          "Oferecer imediatamente uma condição especial para a próxima máquina, antes que o concorrente volte com uma proposta formal e escrita",
          "Lembrar o cliente de tudo que você fez por ele nos últimos anos, para reforçar a lealdade antes de o concorrente avançar na conta",
          "Explicar por que a concorrente não é boa opção para a região, com dados de assistência e revenda que o cliente ainda não conhece",
        ], correta: 0, explicacao: "Defesa é utilidade, não cobrança nem depreciação. Os dados de operação e a antecipação da troca fazem o cliente chegar à comparação com a conta pronta. Pedir lealdade e falar mal fazem ele esconder as próximas visitas; condição especial antes da hora é desconto sem venda." },
        { pergunta: "Onde a maioria das contas antigas é perdida?", opcoes: [
          "Na visita do concorrente com preço menor, porque o cliente antigo já conhece a máquina e decide só pelo valor",
          "Num problema (chamado, reclamação) mal atendido, que abre a porta para o concorrente 'aparecer na hora certa'",
          "Na renovação do contrato de manutenção, quando o cliente compara o custo do plano com o de outras marcas",
          "Na troca de gerente ou de vendedor da concessionária, quando a relação pessoal se perde e a conta fica órfã",
        ], correta: 1, explicacao: "No caso da aula, 12 anos de conta se perderam em 4 dias de chamado sem retorno. O concorrente não tira a conta; a conta se abre quando você falha no momento crítico. Cobertura de férias e reação em 24 h valem mais que qualquer argumento." },
        { pergunta: "Por que antecipar o plano de troca a partir de 6.000–8.000 horas é uma camada de defesa?", opcoes: [
          "Porque a garantia acaba nessa faixa de horas e o cliente passa a pagar as corretivas, o que abre espaço para a troca",
          "Porque a fábrica recomenda a renovação da frota nessa faixa e oferece condições especiais de troca para quem antecipa",
          "Porque o cliente com máquina nova não precisa de assistência por dois anos, o que libera a equipe para outras contas",
          "Porque você chega antes de a máquina dar problema, com a usada no valor máximo, enquanto o concorrente chega quando ela já quebra",
        ], correta: 3, explicacao: "Máquina velha quebrando é o sinal que todos os concorrentes leem. Quem traz o plano antes transforma a troca numa decisão planejada dentro da relação. E a usada com menos horas vale mais na entrada, o que melhora a conta para o cliente." },
        { pergunta: "Qual afirmação sobre 'relação em rede' está correta?", opcoes: [
          "Conhecer só o dono é suficiente, porque ele decide sozinho e os outros seguem a orientação dele na compra",
          "Conhecer operador, mecânico, sócio, contador e encarregado dá à conta vários defensores; uma mudança de humor ou de pessoa não a derruba",
          "A relação com o operador é irrelevante para a defesa, porque ele não participa da decisão nem tem acesso ao dono",
          "Quanto mais pessoas você conhece na empresa, mais opiniões divergentes surgem e mais difícil fica a negociação",
        ], correta: 1, explicacao: "Contas se perdem quando o único elo muda (sócio novo, dono de mau humor, gerente trocado). Cinco relações são cinco fontes de informação e cinco vozes a seu favor quando o concorrente aparece. O operador, em especial, opina todos os dias." },
        { pergunta: "Um marco de pós-venda está vencido há 25 dias. Qual é a leitura correta?", opcoes: [
          "Sinal de que você abriu a porta da conta ao concorrente; visitar esta semana com dados e a pergunta do NPS",
          "Sinal de que o cliente não sentiu falta do contato, o que indica que o marco era desnecessário para essa conta",
          "Atraso a ser compensado no marco seguinte, que deve ser feito no prazo com os dados dos dois períodos",
          "Atraso administrativo sem consequência prática, a ser resolvido quando a rota passar pela cidade do cliente",
        ], correta: 0, explicacao: "Marco vencido é ausência, e ausência é o que o concorrente preenche. A Central de Alertas avisa exatamente para isso. Pular ou adiar transforma o cliente em conta em risco sem que você perceba." },
      ],
    },
    // ───────────────────────────── AULA 5 ─────────────────────────────
    {
      id: "m9a5", titulo: "Indicação e prova social como sistema da carteira", minutos: 13,
      resumo: "O Módulo 3 ensinou a pedir indicação. Aqui a escala: uma carteira organizada como fonte de provas, com referências por nicho, depoimentos com número, visitas de prospects a clientes e a rotina que mantém tudo vivo. Sua carteira é o seu melhor material de venda.",
      blocos: [
        { tipo: "p", texto: "Cada cliente satisfeito é três coisas ao mesmo tempo: uma fonte de indicações, uma referência para prospects do mesmo nicho e uma história com número para contar. A maioria dos vendedores usa isso de forma aleatória: lembra de um cliente quando precisa, pede indicação quando dá vontade. O consultor organiza: lista de referências por nicho e cidade (com autorização), depoimentos curtos com número e nome, calendário de visitas de prospects a clientes, e um pedido de indicação em cada marco de nota 9 ou 10. A carteira vira uma máquina de prova social." },
        { tipo: "framework", nome: "Sistema de prova social em 4 peças", origem: "Cialdini (prova social por semelhança) e Cates (referral system)", passos: [
          "Lista de referências: por nicho (café, pedreira, prefeitura, locação, terraplenagem, construtora) e cidade, com máquina, ano, horas, telefone e autorização registrada no CRM. Meta: 2 por nicho, atualizada a cada marco de 365 dias.",
          "Depoimentos com número: uma frase do cliente com dado ('3.400 horas em dois anos sem parar; consumo de 13,6 L/h'), nome e cidade, autorizado. Coletado no marco de 180 ou 365 dias de quem deu 9 ou 10.",
          "Visitas de prospect a cliente: o argumento mais forte para um prospect cético é passar uma hora na obra de um cliente parecido. Combine com o cliente (ele ganha reconhecimento e, às vezes, um jantar), leve o prospect, não fale: deixe o cliente falar.",
          "Rotina: em todo marco com nota 9–10, pedido de indicação específico (nicho + cidade + sinal) e pergunta de autorização para referência. Retorno ao indicador em 7 dias. Cuidado especial com quem indica: eles são a sua rede de vendas.",
        ] },
        { tipo: "tabela", titulo: "Prova social por perfil de prospect", colunas: ["Prospect", "Prova mais eficaz", "Como entregar"], linhas: [
          ["Perfil C (engenheiro, gerente de frota)", "Depoimento com número + contato para checar + dados de operação", "Por escrito, com fonte"],
          ["Perfil D (dono de pedreira, empreiteiro grande)", "Visita rápida a cliente parecido; 'liga pro Roberto'", "Telefone na hora; visita de 1 hora"],
          ["Perfil S (empreiteiro familiar, cooperativa)", "Visita ao cliente com tempo; história de quem também tinha medo de trocar", "Conversa entre pares, sem o vendedor no meio"],
          ["Perfil I (locador, produtor expansivo)", "Nomes conhecidos dele que compraram; apresentação em grupo", "Grupo de WhatsApp, associação, evento"],
          ["Prefeitura", "Outro município com a mesma máquina há 2+ anos; visita do engenheiro e do operador", "Visita técnica intermunicipal"],
        ] },
        { tipo: "dialogo", titulo: "Combinando a visita de prospect", falas: [
          { quem: "vendedor", texto: "Seu Roberto, o Paulinho, de Castelo, está pensando numa W170B e tem a mesma dúvida que você tinha: se aguenta a rocha da região. Posso trazer ele aqui uma hora na terça pra ver a sua trabalhando e conversar com você? Eu fico quieto, é entre vocês." },
          { quem: "cliente", texto: "Pode trazer. Eu conto pra ele o que eu passei com a outra." },
          { quem: "nota", texto: "O cliente ganha reconhecimento (é a referência) e o prospect ouve de um par, sem filtro de vendedor. Depois: agradecimento proporcional e registro no CRM." },
          { quem: "vendedor", texto: "(na terça, para o prospect) Vou deixar vocês dois. Pergunta tudo o que quiser pra ele, principalmente o que deu errado." },
          { quem: "nota", texto: "'Principalmente o que deu errado' é o que torna a prova crível: história sem obstáculo é propaganda." },
        ] },
        { tipo: "caso", titulo: "Caso: a lista que faltava", situacao: "Vendedor experiente, 80 clientes na carteira, nenhuma lista de referências. Quando um prospect de prefeitura pediu 'outro município com essa patrol', ele levou três dias para lembrar e conseguir autorização. O prospect fechou com quem respondeu na hora.", acao: "Montou a lista: 14 referências em 6 nichos, com autorização, máquina, horas e telefone, no CRM. Coletou 9 depoimentos com número nos marcos seguintes.", resultado: "Nos 12 meses seguintes, a lista foi usada em 31 negociações; em 11 delas o prospect ligou para a referência; 8 fecharam. O tempo de resposta a 'quem mais tem?' caiu de dias para segundos.", licao: "Prova social não é memória; é sistema. A lista no CRM, atualizada nos marcos, é o material de venda mais barato e mais forte que existe." },
        { tipo: "checklist", titulo: "Manutenção da rede de prova social", itens: [
          "Lista de referências com 2 por nicho e autorização registrada; revisada no marco de 365 dias.",
          "Depoimentos com número coletados em cada marco de nota 9–10 (frase, nome, cidade, autorização).",
          "Referências avisadas antes de serem citadas ('vou passar seu contato para o Paulinho, tudo bem?').",
          "Retorno e agradecimento a cada referência usada (o que aconteceu com o prospect).",
          "Visitas de prospect a cliente combinadas com antecedência e com reconhecimento ao anfitrião.",
          "Referências cuidadas com prioridade no pós-venda: referência mal atendida vira antipropaganda.",
        ] },
        { tipo: "erros", titulo: "Erros de prova social", itens: [
          "Citar cliente sem autorização. Ele descobre e você perde a referência e a conta.",
          "Usar a mesma referência para tudo. Ela cansa; e prova precisa ser parecida com o prospect.",
          "Ficar na sala durante a conversa entre prospect e cliente. A presença do vendedor filtra a verdade.",
          "Não dar retorno à referência. Ela deixa de atender o próximo prospect.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Monte hoje a sua lista de referências no CRM: para cada nicho, dois clientes com máquina, ano, horas, telefone e status da autorização (pedir nos próximos marcos). Escreva os três depoimentos com número que você já poderia coletar e de quem." },
      ],
      missao: "Complete a lista de referências (2 por nicho, com autorização) e colete dois depoimentos com número nos marcos desta semana. Combine uma visita de prospect a cliente. Registre tudo no CRM e dê retorno a cada referência usada.",
      quiz: [
        { pergunta: "Um prospect cético de pedreira duvida que a máquina aguente rocha. Qual é a prova mais forte?", opcoes: [
          "A garantia estendida para aplicação severa, que cobre a estrutura e o hidráulico por mais tempo em rocha",
          "O boletim técnico da fábrica sobre a estrutura reforçada, com os testes de fadiga e as especificações de material",
          "Uma hora na pedreira de um cliente parecido, conversando com ele sem o vendedor no meio, inclusive sobre o que deu errado",
          "O vídeo institucional da máquina operando em mineração, com dados de produção e depoimentos de operadores",
        ], correta: 2, explicacao: "Prova social por semelhança (Cialdini) em sua forma mais direta: par com par, sem filtro. 'Principalmente o que deu errado' é o que torna a conversa crível. Boletim e vídeo são argumentos do vendedor; garantia cobre risco mas não convence." },
        { pergunta: "Por que o vendedor deve sair da sala durante a conversa entre o prospect e o cliente de referência?", opcoes: [
          "Porque é regra de etiqueta comercial não interferir na conversa entre dois clientes da mesma concessionária",
          "Para aproveitar o tempo em outra visita da rota, já que a conversa entre os dois pode levar mais de uma hora",
          "Para não ouvir eventuais críticas à máquina ou à assistência que o cliente não faria na frente do vendedor",
          "Porque a presença do vendedor filtra a verdade: o cliente modera o que diz e o prospect não pergunta o que realmente quer saber",
        ], correta: 3, explicacao: "A força da referência está na ausência de interesse. Com o vendedor presente, a conversa vira apresentação; sem ele, vira conselho entre pares, incluindo o que deu errado e como foi resolvido, que é o que convence." },
        { pergunta: "Qual é o formato correto de um depoimento para a lista de prova social?", opcoes: [
          "'Excelente máquina, recomendo', sem identificação, para preservar a privacidade do cliente",
          "'3.400 horas em dois anos sem parar; consumo de 13,6 L/h', com nome, cidade e autorização",
          "Um texto longo elogiando a concessionária, o vendedor e a assistência, assinado pelo cliente",
          "Uma nota de 0 a 10 sem comentário, coletada no marco de pós-venda e registrada no CRM",
        ], correta: 1, explicacao: "Depoimento com número, nome e cidade é verificável e fala ao Sistema 2 do prospect. 'Excelente, recomendo' anônimo é slogan; texto longo não é lido; nota sem comentário não conta história." },
        { pergunta: "O que o caso 'a lista que faltava' demonstra?", opcoes: [
          "Que prova social funciona apenas com prefeituras, porque o engenheiro exige referência de outro município",
          "Que 80 clientes na carteira são suficientes para vender sem lista, desde que o vendedor tenha boa memória",
          "Que prova social é sistema, não memória: a lista organizada no CRM respondeu 'quem mais tem?' em segundos e participou de 31 negociações",
          "Que depoimentos devem ser coletados apenas na entrega técnica, quando o cliente está mais disposto a autorizar",
        ], correta: 2, explicacao: "O vendedor perdeu um pregão por levar três dias para lembrar de uma referência. Com a lista, a prova social virou material de venda instantâneo: 11 ligações de prospects para referências e 8 fechamentos. Sistema vence memória." },
        { pergunta: "Qual cuidado é obrigatório antes de citar um cliente como referência?", opcoes: [
          "Ter a autorização registrada e avisar o cliente antes de cada uso ('vou passar seu contato para o Paulinho, tudo bem?')",
          "Enviar um brinde ou uma cortesia ao cliente, como reconhecimento pelo tempo que ele vai gastar com o prospect",
          "Verificar se o cliente ainda tem a máquina e se ela está em operação, para a referência ser atual e verificável",
          "Avisar o gerente da concessionária, que mantém o cadastro oficial de referências autorizadas pela fábrica",
        ], correta: 0, explicacao: "Citar sem autorização custa a referência e a conta quando o cliente descobre. Avisar antes de cada uso mantém o cliente no controle e preparado para a ligação. Retorno depois (o que aconteceu com o prospect) mantém a fonte viva." },
      ],
    },
    // ───────────────────────────── AULA 6 ─────────────────────────────
    {
      id: "m9a6", titulo: "Autoridade regional: ser a pessoa que a região consulta", minutos: 13,
      resumo: "O vendedor que a associação chama para falar de custo por hora, que a cooperativa convida para o dia de campo e que os empreiteiros consultam sobre o Plano Safra não prospecta: é procurado. Autoridade é a soma de utilidade repetida em público.",
      blocos: [
        { tipo: "p", texto: "Cialdini chama de autoridade o atalho pelo qual as pessoas seguem quem demonstra competência. No interior, autoridade regional é construída em público: a palestra de 20 minutos na associação dos empreiteiros sobre custo total de propriedade, o dia de campo na cooperativa, a mensagem útil no grupo de WhatsApp da pedreira (o edital, a mudança do FINAME), o artigo curto no jornal local sobre como escolher uma retro. Ninguém faz isso, porque parece 'não vender'. Mas o vendedor que ensina em público é o que recebe a ligação quando alguém decide comprar — e chega à negociação como consultor, não como um dos três orçamentos." },
        { tipo: "framework", nome: "Plano de autoridade em 12 meses", origem: "Challenger (ensinar) + Cialdini (autoridade) aplicados ao território", passos: [
          "Mapeie as comunidades: associação de empreiteiros, sindicato rural, cooperativas de café, associação de locadores, grupos de WhatsApp do setor, AMUNES/engenheiros municipais. Quem organiza cada uma?",
          "Um tema útil por trimestre: custo total de 5 anos (por que a mais barata custa mais), como ler o Plano Safra/FINAME do ano, como preparar uma máquina para revenda valer mais, o que exigir num termo de referência de frota. Sempre ensinar, nunca vender.",
          "Formatos: palestra de 20 minutos + perguntas; dia de campo com máquina e medição ao vivo; mensagem mensal útil no grupo (uma por mês, nunca propaganda); artigo de meia página no jornal/rádio local.",
          "Colete os contatos e as perguntas: cada pergunta feita em público é um diagnóstico grátis e um lead com sinal. Registre no CRM.",
          "Meça: convites recebidos, ligações espontâneas de prospects, 'me indicaram você' no primeiro contato. Autoridade aparece como redução do custo de prospecção.",
        ] },
        { tipo: "tabela", titulo: "Temas que a região quer ouvir (e o que cada um gera)", colunas: ["Tema", "Público", "O que gera"], linhas: [
          ["Custo total de propriedade: a conta de 5 anos", "Empreiteiros, pedreiras, locadores", "Prospects que chegam pedindo 'a conta' em vez de 'o preço'"],
          ["Plano Safra e crédito rural para máquinas", "Cooperativas, sindicato rural", "Produtores que descobrem que podem comprar; leads com momento"],
          ["Como preparar a usada para valer mais na troca", "Todos", "Avaliações de usadas → negociações de troca"],
          ["O que exigir num termo de referência de frota municipal", "Engenheiros e secretários de obras", "Termos bem escritos; convites para visita técnica"],
          ["Manutenção que evita parada: os 10 itens diários", "Operadores e mecânicos", "Relação com o usuário; cross-sell de plano e peças"],
        ] },
        { tipo: "dialogo", titulo: "Convite da associação", falas: [
          { quem: "cliente", texto: "(presidente da associação de empreiteiros) Edy, o pessoal vive reclamando de máquina parada. Você toparia falar na reunião do mês que vem? Mas não pode ser propaganda." },
          { quem: "vendedor", texto: "Topo, e concordo: nada de propaganda. Vou falar de como fazer a conta de custo por hora e o que olhar antes de comprar qualquer marca. Levo a calculadora e a gente faz a conta ao vivo com os números de quem quiser. Vinte minutos e depois perguntas." },
          { quem: "nota", texto: "Aceita a condição, define o formato de ensino, oferece a conta ao vivo. As perguntas do fim são os leads." },
          { quem: "cliente", texto: "Assim é bom. Vai ter uns 30 empreiteiros." },
          { quem: "vendedor", texto: "Deixo uma folha com a conta em branco pra cada um levar. Quem quiser que eu faça a dele depois, me chama." },
        ] },
        { tipo: "caso", titulo: "Caso: o dia de campo da cooperativa", situacao: "Vendedor propôs à cooperativa de café de Iúna um dia de campo: uma B95C usada revisada abrindo carreador numa fazenda de associado, com medição de metros por hora e consumo, mais 20 minutos sobre o Plano Safra do ano.", acao: "Quarenta produtores foram. Vinte fizeram perguntas; doze pediram a conta do próprio carreador; a cooperativa passou a convidar o vendedor todo ano.", resultado: "Seis vendas em 10 meses (três usadas, três novas via Plano Safra) e o vendedor virou 'o cara da máquina' da cooperativa: quando alguém pensa em comprar, o presidente manda ligar para ele.", licao: "Um dia de ensino em público vale meses de prospecção fria. E o custo foi o transporte de uma usada e um almoço." },
        { tipo: "checklist", titulo: "Antes de qualquer aparição pública", itens: [
          "O tema ensina algo útil mesmo para quem nunca vai comprar de mim?",
          "Zero slides de produto; se houver máquina, é para medir, não para exibir.",
          "Conta ao vivo preparada com a Calculadora e folha em branco para os presentes.",
          "Forma de coletar contatos e perguntas (folha, QR, 'me chama').",
          "Combinado com o organizador o formato (tempo, perguntas) e o que NÃO vai ter (propaganda).",
          "Registro no CRM depois: presentes conhecidos, perguntas feitas, leads com sinal.",
        ] },
        { tipo: "erros", titulo: "Erros de autoridade", itens: [
          "Transformar a palestra em propaganda. A associação não chama de novo e a plateia desconta tudo.",
          "Mandar mensagem no grupo toda semana. Uma útil por mês constrói; quatro por mês irritam e viram spam.",
          "Não coletar as perguntas. Cada uma é um diagnóstico grátis que você joga fora.",
          "Falar difícil para parecer expert. Autoridade no interior é clareza: a conta que o produtor entende.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Liste as cinco comunidades da sua região (associações, sindicatos, cooperativas, grupos) e quem organiza cada uma. Escolha um tema para os próximos 90 dias e escreva o roteiro de 20 minutos com a conta ao vivo. Ligue para o organizador esta semana e proponha." },
      ],
      missao: "Proponha uma aparição de ensino (palestra de 20 minutos, dia de campo ou mensagem mensal útil) a uma comunidade da região nos próximos 60 dias. Prepare o roteiro sem propaganda e com a conta ao vivo. Registre no CRM os contatos e as perguntas coletadas.",
      quiz: [
        { pergunta: "O presidente da associação convida você para falar, 'mas não pode ser propaganda'. Qual é a resposta que constrói autoridade?", opcoes: [
          "Aceitar e trazer o gerente da concessionária para apresentar a empresa e a estrutura de assistência da região",
          "Aceitar e apresentar a linha de produtos de forma discreta, sem preços, focando em tecnologia e assistência",
          "Recusar com elegância, porque sem falar de produto a palestra não gera vendas e consome uma noite de trabalho",
          "Aceitar e ensinar a conta de custo por hora e o que olhar antes de comprar qualquer marca, com a conta ao vivo e perguntas no fim",
        ], correta: 3, explicacao: "Autoridade é utilidade em público. Quem ensina a conta é procurado quando alguém decide comprar, e chega como consultor. Propaganda disfarçada é percebida e custa o convite seguinte; recusar joga fora 30 empreiteiros numa sala." },
        { pergunta: "Por que uma mensagem útil por mês no grupo de WhatsApp do setor constrói autoridade e quatro por mês destroem?", opcoes: [
          "Porque o grupo tem limite implícito de mensagens por membro, e quem excede é silenciado pelos administradores",
          "Porque a frequência alta é lida como spam e propaganda, e o valor de cada mensagem se dilui; a mensagem rara e útil é esperada e lida",
          "Porque os administradores removem quem posta muito, e o vendedor perde o acesso ao grupo e aos contatos dele",
          "Porque clientes do interior não usam grupos para negócios, e mensagens frequentes parecem invasão de um espaço social",
        ], correta: 1, explicacao: "Autoridade se apoia em escassez de ruído: a mensagem que sempre traz algo (edital, mudança do FINAME, dica de revenda) é aberta; a enxurrada é silenciada. Uma por mês, sempre útil, é a regra." },
        { pergunta: "O que as perguntas feitas pela plateia ao fim de uma palestra representam?", opcoes: [
          "Diagnósticos grátis e leads com sinal, que devem ser registrados no CRM com o nome de quem perguntou",
          "Objeções públicas que devem ser rebatidas na hora, porque a plateia inteira ouve a resposta e forma opinião",
          "Indicadores de que a palestra foi confusa em alguns pontos, que devem ser revistos para a próxima apresentação",
          "Uma formalidade do evento, porque quem realmente tem interesse procura o vendedor em particular depois",
        ], correta: 0, explicacao: "Quem pergunta 'e se a minha máquina tem 9.000 horas?' acabou de dizer que está pensando em trocar. A pergunta pública é o primeiro contato de uma negociação. Coletar nome e pergunta é o que transforma a palestra em funil." },
        { pergunta: "O dia de campo da cooperativa gerou seis vendas em 10 meses. Qual foi o elemento decisivo do formato?", opcoes: [
          "O almoço oferecido aos produtores, que criou o clima de confraternização e reciprocidade com a cooperativa",
          "A apresentação dos modelos disponíveis e das condições de fim de ano, que deu aos produtores opções concretas",
          "A máquina trabalhando de verdade (carreador de um associado) com medição ao vivo e 20 minutos de ensino sobre crédito, sem propaganda",
          "O desconto anunciado para quem fechasse no dia, que transformou o interesse em decisão para seis produtores",
        ], correta: 2, explicacao: "Máquina medindo na aplicação real do público, mais informação útil sobre como pagar (Plano Safra), é ensino com prova. Não houve desconto nem apresentação de linha; houve utilidade, e a cooperativa passou a convidar todo ano." },
        { pergunta: "Como se mede se a construção de autoridade está funcionando?", opcoes: [
          "Pelo número de seguidores nas redes sociais e pelo alcance das publicações sobre máquinas e obras da região",
          "Pela quantidade de palestras e dias de campo realizados no ano, que mostra a presença do vendedor nas comunidades",
          "Pelo número de materiais e apresentações aprovados pela fábrica para uso em eventos regionais",
          "Por convites recebidos, ligações espontâneas de prospects e 'me indicaram você' no primeiro contato: a redução do custo de prospecção",
        ], correta: 3, explicacao: "Autoridade se manifesta como demanda que chega sozinha e como negociações que começam no nível de consultor. Seguidores e número de palestras são atividade, não resultado; a fábrica não aprova autoridade, a região reconhece." },
      ],
    },
  ],
  prova: [
    { pergunta: "Qual é o momento de maior satisfação do ciclo, ideal para o primeiro pedido de indicação?", opcoes: [
      "A entrega técnica bem feita, com operador treinado e dono presente",
      "A assinatura do contrato, quando o entusiasmo da decisão é máximo",
      "A aprovação do crédito, quando o cliente sente alívio pela compra viabilizada",
      "O primeiro chamado resolvido, quando o cliente sente gratidão pelo atendimento",
    ], correta: 0, explicacao: "Máquina nova na obra, operador produzindo, dono orgulhoso. Um pedido específico nesse momento rende nome na hora. Na assinatura ainda não há resultado; o chamado resolvido é o segundo gatilho, não o primeiro." },
    { pergunta: "Por que registrar horímetro e consumo da primeira hora na entrega?", opcoes: [
      "Para ativar a garantia de fábrica, que exige o registro do horímetro inicial e do primeiro abastecimento",
      "Para ter os números de partida que permitem comparar no marco de 30 dias e provar o resultado calculado",
      "Para calcular a comissão da entrega técnica, paga sobre a máquina em operação e com horas registradas",
      "Porque o cliente pode pedir reembolso do combustível da primeira hora, e o registro serve de comprovante",
    ], correta: 1, explicacao: "Satisfação medida ('calculamos 14, deu 13,6') é a que vira prova social e indicação. Sem número de partida, o marco é visita social." },
    { pergunta: "Cliente dá nota 7 no marco. Qual é a ação?", opcoes: [
      "Registrar a nota e perguntar de novo em 60 dias, quando a impressão do chamado passou",
      "Defender o serviço com os dados de atendimento, porque o prazo contratual foi cumprido",
      "Perguntar 'o que faria virar 10?', resolver com data e retornar",
      "Oferecer desconto na próxima revisão, como compensação pela demora do chamado",
    ], correta: 2, explicacao: "O neutro tem motivo concreto e resolúvel. A pergunta revela, a ação com data e o retorno transformam. Perguntar o NPS e não agir é pior que não perguntar." },
    { pergunta: "Um detrator (nota 4) bem tratado tende a:", opcoes: [
      "Continuar detrator por muito tempo, porque a primeira impressão negativa raramente se apaga",
      "Virar neutro, no máximo, porque a correção elimina a insatisfação mas não gera entusiasmo",
      "Sair da carteira na próxima troca, porque a experiência ruim pesa mais do que a solução",
      "Virar o promotor mais convicto, porque viu o que acontece quando dá errado",
    ], correta: 3, explicacao: "No caso da aula, nota 4 virou 9, duas indicações e referência regional, porque o vendedor ouviu sem se defender e voltou em 24 h com tudo resolvido. Detrator ignorado vira o melhor vendedor do concorrente." },
    { pergunta: "No marco de 180 dias, o cliente diz que ganhou uma pavimentação e vai alugar um rolo. Qual é a conduta?", opcoes: [
      "'Aproveita e compra um rolo, tenho um na fila para entrega rápida e condição de cliente da casa'",
      "Proposta do rolo por WhatsApp no mesmo dia, com a conta do aluguel acumulado e a condição de cliente",
      "Conta rápida com os números dele (aluguel × parcela), propor a conta completa quando a ordem de serviço sair",
      "Esperar ele pedir, porque pós-venda não é hora de vender e ele sabe onde encontrar você quando precisar",
    ], correta: 2, explicacao: "Ouvir o gatilho, fazer a conta e propor no ritmo do cliente. Empurrar transforma pós-venda em venda e o cliente evita a visita; esperar sem registrar entrega o gatilho ao concorrente." },
    { pergunta: "Qual é o argumento de frota da expansão dentro da mesma marca?", opcoes: [
      "Desconto por volume negociado com a fábrica para frotas da mesma marca",
      "Padronização: peças, técnico, operadores e estoque comuns, menos parada",
      "Revenda garantida pela concessionária ao fim do financiamento da segunda máquina",
      "Garantia estendida automática na segunda máquina, como reconhecimento pela fidelidade",
    ], correta: 1, explicacao: "É a conta que o gerente de produção entende e que o concorrente com uma máquina isolada não tem. Desconto pode existir, mas não é o centro." },
    { pergunta: "Onde a maioria das contas antigas se perde?", opcoes: [
      "Na visita do concorrente com preço menor, quando o cliente antigo decide só pelo valor",
      "Na troca de gerente ou vendedor da concessionária, quando a relação pessoal se perde",
      "Num chamado ou reclamação mal atendidos, que abrem a porta para o concorrente aparecer na hora certa",
      "Na renovação do plano de manutenção, quando o cliente compara o custo com outras marcas",
    ], correta: 2, explicacao: "Doze anos de conta perdidos em quatro dias de chamado sem retorno. Cobertura de férias e reação em 24 h são a defesa que importa." },
    { pergunta: "O cliente conta que o concorrente ofereceu avaliar a máquina para troca. Qual resposta defende a conta?", opcoes: [
      "Pedir lealdade, lembrando tudo o que foi feito pela conta nos últimos anos e o quanto a relação vale",
      "Depreciar o concorrente, mostrando por que a avaliação dele não é confiável e a assistência é distante",
      "Condição especial imediata para a próxima máquina, antes que o concorrente volte com uma proposta escrita",
      "Agradecer, perguntar o que foi oferecido e trazer os dados de operação que só você tem, com o plano de troca",
    ], correta: 3, explicacao: "Defesa é utilidade. Custo/hora real, horas e valor de troca fazem o cliente chegar à comparação com a conta pronta. Lealdade cobrada e depreciação fazem ele esconder as próximas visitas." },
    { pergunta: "Por que antecipar o plano de troca entre 6.000 e 8.000 horas?", opcoes: [
      "Porque a garantia acaba nessa faixa e o cliente passa a pagar as corretivas, o que abre espaço natural para a troca",
      "Porque você chega antes de a máquina dar problema, com a usada no valor máximo, enquanto o concorrente chega quando ela quebra",
      "Porque a fábrica recomenda a renovação da frota nessa faixa e oferece condições especiais de troca para quem antecipa",
      "Porque o financiamento da máquina atual termina nessa faixa e o cliente tem crédito livre para assumir a próxima parcela",
    ], correta: 1, explicacao: "Máquina velha quebrando é sinal para todos os concorrentes. Planejar antes transforma a troca em decisão dentro da relação e melhora a conta do cliente (usada com menos horas vale mais)." },
    { pergunta: "Qual é o formato correto de depoimento para prova social?", opcoes: [
      "'Ótima máquina', sem identificação, para preservar a privacidade do cliente",
      "Texto longo sobre a concessionária, o vendedor e a assistência, assinado pelo cliente",
      "Frase com número, nome e cidade, autorizada ('3.400 horas em dois anos sem parar')",
      "Nota de 0 a 10 sem comentário, coletada no marco de pós-venda e registrada no CRM",
    ], correta: 2, explicacao: "Verificável e específico. Slogan anônimo não é prova; texto longo não é lido; nota sem história não convence." },
    { pergunta: "Durante a visita de um prospect a um cliente de referência, o vendedor deve:", opcoes: [
      "Conduzir a conversa para os pontos fortes da máquina, para o prospect ouvir o que importa",
      "Sair de perto e deixar os dois conversarem, inclusive sobre o que deu errado",
      "Apresentar a ficha técnica ao prospect enquanto o cliente opera, aproveitando o tempo",
      "Gravar a conversa com autorização, para usar como depoimento com outros prospects",
    ], correta: 1, explicacao: "A força da referência está na ausência de interesse. Sem o vendedor, a conversa vira conselho entre pares, e 'o que deu errado e como foi resolvido' é o que convence." },
    { pergunta: "A associação convida você para falar 'sem propaganda'. O que fazer?", opcoes: [
      "Recusar com elegância, porque sem produto a palestra não gera vendas e consome uma noite de trabalho sem retorno",
      "Apresentar a linha discretamente, sem preços, focando em tecnologia e assistência para não parecer propaganda",
      "Trazer o gerente para falar da empresa e da estrutura de assistência, que é um assunto institucional e não comercial",
      "Ensinar a conta de custo por hora e o que olhar antes de comprar qualquer marca, com a conta ao vivo e perguntas",
    ], correta: 3, explicacao: "Autoridade é utilidade em público. Quem ensina é procurado quando alguém decide comprar. As perguntas do fim são leads com sinal." },
    { pergunta: "Qual é a frequência correta de mensagens úteis num grupo de WhatsApp do setor?", opcoes: [
      "Diária, para manter presença constante e ser lembrado quando alguém pensar em máquina",
      "Semanal, com novidades da marca, lançamentos e condições comerciais da concessionária",
      "Uma por mês, sempre útil (edital, crédito, dica de revenda), nunca propaganda",
      "Apenas quando houver promoção ou condição especial, para a mensagem ter motivo concreto",
    ], correta: 2, explicacao: "Escassez de ruído constrói autoridade: a mensagem rara e útil é aberta; a enxurrada é silenciada e lida como spam." },
    { pergunta: "Como se mede a autoridade regional?", opcoes: [
      "Por convites recebidos, ligações espontâneas de prospects e 'me indicaram você' no primeiro contato",
      "Por seguidores nas redes sociais e alcance das publicações sobre máquinas e obras",
      "Por número de palestras e dias de campo realizados no ano nas comunidades da região",
      "Por materiais e apresentações aprovados pela fábrica para uso em eventos regionais",
    ], correta: 0, explicacao: "Autoridade aparece como redução do custo de prospecção: a demanda chega sozinha e as negociações começam no nível de consultor." },
  ],
};
