import type { Modulo } from "./tipos";

export const M9: Modulo = {
  id: "m9", nivel: 9, titulo: "Negociação, financiamento e velocidade", tema: "Negociação", cor: "#9d6bff",
  descricao: "O financiamento é onde a maioria das vendas de máquina morre ou nasce. Domine os instrumentos, negocie valor sem ceder, use as táticas de negociadores de elite, transforme a usada em fechamento e proteja margem contra compradores profissionais.",
  objetivos: [
    "Escolher o instrumento de financiamento certo para cada cliente e acelerar a aprovação.",
    "Negociar em pacote com BATNA, ancoragem e o poder do não.",
    "Aplicar as táticas de Chris Voss: espelho, rótulo, perguntas calibradas, ancoragem e acusação preventiva.",
    "Avaliar e negociar a usada na troca sem cair nas armadilhas.",
    "Enfrentar departamentos de compras e leilões reversos protegendo a margem.",
    "Levar o sim ao faturamento com velocidade e sem arrependimento.",
  ],
  leituras: [
    "Chris Voss — Negocie como se sua vida dependesse disso.",
    "Roger Fisher e William Ury — Como chegar ao sim.",
    "Cartilhas do BNDES Finame e manuais de crédito rural (Pronaf, Pronamp, Moderfrota).",
  ],
  aulas: [
    {
      id: "m9a1", titulo: "Financiamento como ferramenta de fechamento", minutos: 12,
      resumo: "Finame/BNDES, bancos parceiros, consórcio, CRD, crédito rural: cada instrumento fecha um tipo de cliente. Documentação é velocidade.",
      blocos: [
        { tipo: "tabela", titulo: "Instrumentos e quando usar", colunas: ["Instrumento", "Perfil ideal", "Pontos fortes", "Atenção"], linhas: [
          ["Finame / BNDES via banco", "Empresa com CNPJ ativo, faturamento e documentação em dia (construtoras, empreiteiras, pedreiras)", "Prazo longo, taxa competitiva, carência", "Exige certidões e balanço; análise de 7–20 dias"],
          ["Banco parceiro da marca (CNH Capital / bancos comerciais)", "Cliente com relacionamento bancário", "Aprovação rápida, campanhas com taxa reduzida", "Use as campanhas como urgência real"],
          ["Consórcio (New Holland e outros)", "Quem planeja; produtor com safra futura; quem “não tem pressa”", "Sem juros, lance com a usada ou com a safra", "Contemplação não é garantida sem lance; explique com clareza"],
          ["CRD PME e linhas regionais (Bandes, cooperativas de crédito)", "Pequeno empreiteiro sem histórico bancário longo", "Acesso a quem o banco grande nega", "Limites menores; registre as parcelas no CRM"],
          ["Crédito rural (Pronaf, Pronamp, Moderfrota)", "Produtor de café", "Taxas subsidiadas, calendário de safra, carência", "Precisa de projeto técnico e enquadramento; trabalhe com agrônomo/cooperativa"],
          ["Leasing / CDC", "Locadoras e empresas que querem contabilidade específica", "Flexibilidade fiscal", "Custo pode ser maior; envolva o contador"],
          ["Usada na troca", "Todos", "Reduz entrada e resolve “o que faço com a antiga”", "Avalie com critério (aula 5 deste módulo)"],
        ] },
        { tipo: "p", titulo: "Documentação = velocidade", texto: "Peça a documentação no dia do “sim”, não depois. Tenha a lista pronta (contrato social, faturamento, IR, certidões, comprovantes, matrícula do imóvel para crédito rural) e ajude o cliente a reunir. Cada dia de atraso na análise esfria o desejo e abre espaço para o concorrente. Meta: proposta aprovada em até 7 dias." },
        { tipo: "checklist", titulo: "Lista de documentos (empresa)", itens: [
          "Contrato social e última alteração",
          "Cartão CNPJ e certidões (federal, estadual, municipal, FGTS, trabalhista)",
          "Faturamento dos últimos 12 meses (assinado pelo contador)",
          "Balanço / DRE do último exercício",
          "Documentos pessoais e IR dos sócios",
          "Comprovante de endereço da empresa e dos sócios",
          "Relação de bens / frota (para garantia complementar, se pedido)",
        ] },
        { tipo: "lista", titulo: "Acelerando a aprovação", itens: [
          "Pré-análise antes da proposta: você só apresenta condição que o banco vai aprovar.",
          "Dois bancos em paralelo quando o prazo é curto (com transparência com o cliente).",
          "Contato direto com o analista: ligue, não só e-mail. Pergunte o que falta.",
          "Cliente informado a cada 2 dias, mesmo sem novidade.",
          "Plano B pronto (consórcio, outra linha) para não perder o cliente se o A falhar.",
        ] },
        { tipo: "destaque", titulo: "Frase", texto: "“Não vendo máquina, vendo parcela que cabe no que a máquina produz.” Quando a parcela é menor que o ganho mensal, a decisão vira óbvia." },
        { tipo: "caso", titulo: "Caso: dois bancos, 5 dias", situacao: "Empreiteira precisava da retro em 3 semanas para obra com multa. O banco principal pedia 20 dias de análise.", acao: "O vendedor enviou a documentação para dois bancos parceiros em paralelo e ligou para os analistas diariamente.", resultado: "Aprovação em 5 dias no segundo banco. Entrega no prazo. O cliente virou referência para 2 outras empreiteiras.", licao: "Velocidade no financiamento é diferencial competitivo. Quem resolve, fecha." },
      ],
      missao: "Monte uma tabela com os 5 instrumentos que você mais usa: taxa aproximada, prazo, carência, documentos e perfil ideal. Cole no seu celular e no CRM (Configurações › notas).",
      quiz: [
        { pergunta: "Cliente produtor de café, safra em 4 meses, sem pressa. Instrumento mais indicado:", opcoes: ["Consórcio com lance / crédito rural", "À vista", "Nenhum, esperar"], correta: 0, explicacao: "Consórcio e crédito rural respeitam o calendário da safra e mantêm o cliente fechado com você." },
        { pergunta: "Quando pedir a documentação do banco?", opcoes: ["Depois da aprovação", "No dia do sim", "Quando o cliente lembrar"], correta: 1, explicacao: "Cada dia de atraso esfria o desejo e abre espaço para o concorrente." },
        { pergunta: "O que é pré-análise e por que fazer?", opcoes: ["Analisar o concorrente", "Verificar o crédito antes da proposta, para só apresentar condição aprovável", "Não é necessário"], correta: 1, explicacao: "Reduz o medo do cliente e evita proposta que morre no banco." },
      ],
    },
    {
      id: "m9a2", titulo: "Negociação de valor: ganhar sem ceder", minutos: 10,
      resumo: "Princípios de negociação de elite aplicados à mesa do cliente: BATNA, ancoragem, pacote e o poder do “não”.",
      blocos: [
        { tipo: "lista", titulo: "Antes de sentar", itens: [
          "Sua BATNA (melhor alternativa): outro cliente para a unidade, campanha que termina. Quem tem alternativa negocia calmo.",
          "A BATNA dele: alugar, comprar usada, esperar, o concorrente. Descubra e mostre o custo de cada alternativa.",
          "Seu limite real e o que você pode conceder (módulo 8).",
          "Pacote: negocie tudo junto (valor, entrada, prazo, entrega, implementos, revisão), nunca item por item.",
          "Os interesses por trás das posições: ele pede desconto (posição) porque a parcela não cabe no caixa (interesse). Resolva o interesse.",
        ] },
        { tipo: "p", titulo: "Na mesa", texto: "Ancore primeiro com a proposta cheia. Ouça o pedido e pergunte “o que precisa acontecer pra gente fechar hoje?” — faça o cliente dizer o preço dele. Responda com pacote, não com desconto seco. Use o silêncio. Quando chegar no limite, diga “não” com calma e ofereça o caminho alternativo. Cliente respeita quem sabe dizer não." },
        { tipo: "script", titulo: "Frases de mesa", itens: [
          "“Entendo o pedido. Se eu fizer isso, o que você faz por mim? Fecha hoje? Traz a usada?”",
          "“Esse valor não consigo. O que consigo é: entrega em 10 dias e primeira revisão inclusa. Fechamos assim?”",
          "“Vamos olhar o pacote inteiro em vez de cada item — assim eu consigo te ajudar de verdade.”",
          "“Qual é o número que fecha pra você? [ouça] Esse eu não alcanço. Mas se a parcela é o problema, carência de 90 dias e 60 meses resolvem?”",
        ] },
        { tipo: "tabela", titulo: "Posição x interesse", colunas: ["O que ele diz (posição)", "O que ele quer (interesse)", "Solução sem desconto"], linhas: [
          ["“Quero 10% de desconto”", "Parcela que caiba no caixa", "Prazo maior, carência, usada na entrada"],
          ["“A outra marca dá mais prazo de entrega”", "Não ter multa na obra", "Prioridade de entrega, máquina de pátio"],
          ["“Quero o rompedor de graça”", "Não ter que comprar depois", "Rompedor financiado junto, no mesmo contrato"],
          ["“Quero garantia de 2 anos”", "Medo de ficar na mão", "Garantia estendida (custo baixo) + revisão inclusa"],
        ] },
        { tipo: "caso", titulo: "Caso: o não que fechou", situacao: "Comprador de construtora exigia R$ 30 mil de desconto na E215C, “senão fecho com a Komatsu”.", acao: "O vendedor disse não com calma, mostrou que a Komatsu daquele porte custava mais, e ofereceu pacote: garantia estendida, revisão, prioridade de entrega e carência.", resultado: "O comprador aceitou o pacote sem desconto. A BATNA dele não existia.", licao: "Quem tem alternativa e sabe dizer não negocia de igual para igual." },
      ],
      missao: "Antes da próxima negociação de valor, escreva sua BATNA, a do cliente, o interesse por trás do pedido dele e o pacote completo que você vai propor. Leve no bolso.",
      quiz: [
        { pergunta: "O que é negociar em pacote?", opcoes: ["Dar vários descontos", "Negociar valor, prazo, entrega e implementos juntos, com trocas", "Vender dois equipamentos"], correta: 1, explicacao: "Item a item o cliente ganha em cada um. Em pacote você troca o que custa pouco pelo que vale muito." },
        { pergunta: "Cliente pede 10% de desconto. O interesse provável é:", opcoes: ["Ganhar de você", "Parcela que caiba no caixa — resolva com prazo, carência ou entrada", "Nenhum"], correta: 1, explicacao: "Resolva o interesse, não a posição." },
      ],
    },
    {
      id: "m9a3", titulo: "Táticas de negociadores de elite (Chris Voss) na mesa do cliente", minutos: 11,
      resumo: "Espelho, rótulo, “como eu faria isso?”, o não como início, ancoragem extrema, acusação preventiva e a regra do 7-38-55.",
      blocos: [
        { tipo: "p", texto: "Chris Voss negociou sequestros pelo FBI e ensinou que negociação é empatia tática: entender o outro tão bem que ele se sente compreendido e, por isso, colabora. As táticas dele funcionam na mesa de uma pedreira tanto quanto num sequestro — porque o cérebro é o mesmo." },
        { tipo: "tabela", titulo: "Táticas e aplicação", colunas: ["Tática", "O que é", "Na venda de máquina"], linhas: [
          ["Espelho", "Repetir as últimas 2–3 palavras em tom de pergunta", "Cliente: “Não posso pagar mais que 8 mil de parcela.” → “Mais que 8 mil?” → ele explica o caixa e abre caminho para carência."],
          ["Rótulo", "“Parece que…”, “Dá a impressão de que…”", "“Parece que o receio é a obra acabar antes de a máquina se pagar.” → ele confirma → você fala de revenda e locação."],
          ["Perguntas calibradas", "“Como…?”, “O que…?” em vez de “por quê?”", "“Como eu faria pra caber no seu caixa?” → o cliente resolve o problema com você."],
          ["O não como início", "Fazer perguntas que convidam o não", "“Seria absurdo a gente olhar o consórcio?” → “Não…” → conversa continua sem defesa."],
          ["Ancoragem extrema (do cliente)", "Reconheça a âncora, não reaja", "Cliente: “Quero por 600.” → “600… entendo. Como você chegou nesse número?”"],
          ["Acusação preventiva", "Nomear o negativo antes", "“Você deve achar que eu vou te empurrar a máquina mais cara.”"],
          ["Regra 7-38-55", "7% palavras, 38% tom, 55% corpo", "Voz calma e grave (“DJ de madrugada”) em objeção; sorriso ao telefone; postura aberta."],
          ["“Isso mesmo”", "O objetivo é ouvir “isso mesmo”, não “você tem razão”", "Resuma a situação dele até ele dizer “isso mesmo”. Aí ele está do seu lado."],
          ["Números não redondos", "Precisão passa credibilidade", "“R$ 8.740 de parcela” em vez de “uns 9 mil”."],
        ] },
        { tipo: "script", titulo: "Sequência Voss numa objeção de parcela", itens: [
          "Cliente: “Essa parcela não cabe.”",
          "Espelho: “Não cabe?”",
          "Cliente: “Não, meu caixa tá apertado até a obra da prefeitura pagar, em 3 meses.”",
          "Rótulo: “Parece que o problema não é a parcela, é o momento em que ela começa.”",
          "Cliente: “Isso mesmo.”",
          "Pergunta calibrada: “Como ficaria se a primeira parcela vencesse depois da medição, em 90 dias?”",
          "Cliente: “Aí resolve.”",
          "Fechamento: “Então vamos montar assim e mandar pro banco hoje?”",
        ] },
        { tipo: "erros", titulo: "Erros", itens: [
          "Perguntar “por quê?” — soa acusatório. Use “como” e “o que”.",
          "Reagir à âncora extrema com desconto. Pergunte como ele chegou lá.",
          "Buscar “você tem razão” (o cliente diz para você calar). Busque “isso mesmo”.",
          "Tom ansioso. Voz calma e lenta em objeção transmite controle.",
        ] },
        { tipo: "exercicio", titulo: "Exercício", texto: "Use o Treino com IA deste módulo com o objetivo de conseguir um “isso mesmo” do cliente fictício usando só espelho, rótulo e uma pergunta calibrada antes de propor qualquer condição." },
      ],
      missao: "Na próxima negociação de valor, use pelo menos um espelho, um rótulo e uma pergunta calibrada antes de responder ao pedido do cliente. Registre no CRM a frase exata que gerou o “isso mesmo”.",
      quiz: [
        { pergunta: "Cliente: “Não pago mais que 8 mil de parcela.” Espelho:", opcoes: ["“Por que 8 mil?”", "“Mais que 8 mil?”", "“Posso fazer 8 mil.”"], correta: 1, explicacao: "O espelho faz o cliente explicar — e o caixa aparece." },
        { pergunta: "Qual pergunta calibrada resolve a parcela junto com o cliente?", opcoes: ["“Você quer desconto?”", "“Como eu faria pra caber no seu caixa?”", "“Por que não cabe?”"], correta: 1, explicacao: "“Como” convida o cliente a resolver com você." },
        { pergunta: "O que você busca ouvir do cliente?", opcoes: ["“Você tem razão”", "“Isso mesmo”", "“Tá bom”"], correta: 1, explicacao: "“Isso mesmo” significa que ele se sentiu compreendido e está do seu lado." },
      ],
    },
    {
      id: "m9a4", titulo: "Usada na troca: avaliação, argumento e armadilhas", minutos: 10,
      resumo: "A usada resolve a entrada e o “o que faço com a antiga” — ou destrói a margem se for avaliada errado. Como avaliar, negociar e transformar em fechamento.",
      blocos: [
        { tipo: "p", texto: "Em máquinas pesadas, a maioria das vendas de renovação envolve a usada. Para o cliente, ela é a entrada e o fim da dor de vender por conta própria. Para você, é uma ferramenta de fechamento — desde que a avaliação seja realista. Avaliar alto para fechar é adiar o prejuízo para o estoque de usadas (e para a sua credibilidade)." },
        { tipo: "checklist", titulo: "Checklist de avaliação (fotos de tudo)", itens: [
          "Modelo, ano, número de série, horímetro (confira se o horímetro é original).",
          "Motor: partida a frio, fumaça, vazamentos, ruídos; histórico de retífica.",
          "Hidráulico: vazamentos em cilindros e mangueiras, tempo de ciclo, folgas.",
          "Transmissão / eixos / freios: ruídos, folgas, 4x4 funcionando.",
          "Material rodante: pneus (% de vida) ou esteiras, sapatas, roletes, rodas-guia.",
          "Estrutura: trincas em lança, braço, chassi; soldas de reparo.",
          "Cabine e elétrica: ar, painel, luzes, cabos.",
          "Implementos: caçambas, dentes, rompedor.",
          "Documentação: nota fiscal de origem, gravames, débitos.",
          "Histórico de manutenção (pergunte e peça notas).",
        ] },
        { tipo: "lista", titulo: "Como negociar a usada", itens: [
          "Avalie antes de falar de preço da nova. A usada é parte do pacote, não desconto disfarçado.",
          "Mostre como chegou ao valor: mercado (o Máquinas Usadas do CRM registra referências), estado, horas, custo de reparo para revenda.",
          "Se o cliente acha baixo: “entendo. Se você conseguir vender por mais, ótimo — a condição fica aberta. Mas com ela na entrada você fecha hoje e não gasta 3 meses anunciando.”",
          "Duas opções: usada na entrada (valor X) ou venda por conta própria (entrada em dinheiro maior). Deixe-o escolher.",
          "Nunca aceite a usada sem ver. Foto e vídeo de partida a frio no mínimo; visita para máquinas acima de R$ 80 mil.",
        ] },
        { tipo: "tabela", titulo: "Armadilhas", colunas: ["Armadilha", "Como evitar"], linhas: [
          ["Avaliar alto para fechar", "Avaliação pela referência de mercado + reparos. O prejuízo volta no estoque e na comissão."],
          ["Horímetro adulterado", "Compare desgaste de pedais, assento, pneus/esteiras com as horas declaradas."],
          ["Máquina com gravame/financiamento", "Consulte antes; combine a quitação no fluxo do negócio."],
          ["Cliente que quer “a usada por R$ X” como âncora", "“Como você chegou nesse valor? [ouça] Vamos olhar as referências juntos.”"],
          ["Usada que o cliente “vai entregar depois”", "Entrega e vistoria antes do faturamento da nova, ou valor condicionado à vistoria."],
        ] },
        { tipo: "caso", titulo: "Caso: a retro de 12 mil horas", situacao: "Cliente pedia R$ 120 mil pela retro antiga na troca. Referência de mercado: R$ 80 mil, com R$ 15 mil de reparo para revenda.", acao: "O vendedor mostrou 3 anúncios de retros equivalentes, o orçamento do reparo e ofereceu R$ 78 mil na entrada ou a opção de o cliente vender por conta própria.", resultado: "O cliente tentou vender por conta própria por 1 mês, não conseguiu e voltou: fechou com a usada por R$ 78 mil.", licao: "Avaliação transparente e a opção de escolha preservam a margem e a relação." },
      ],
      missao: "Avalie 3 usadas de clientes em negociação com o checklist completo (fotos, horímetro, partida a frio). Registre no Máquinas Usadas do CRM com o valor de mercado e o custo de reparo estimado.",
      quiz: [
        { pergunta: "Cliente quer R$ 120 mil pela usada que vale R$ 80 mil. Você:", opcoes: ["Aceita para fechar", "Mostra as referências e o custo de reparo, oferece o valor real e a opção de ele vender por conta própria", "Recusa a troca"], correta: 1, explicacao: "Transparência e escolha. Avaliar alto adia o prejuízo." },
        { pergunta: "Antes de aceitar uma usada na troca, é obrigatório:", opcoes: ["Confiar na palavra do cliente", "Ver a máquina (ou fotos/vídeo de partida a frio) e checar horímetro, gravame e estrutura", "Nada"], correta: 1, explicacao: "Usada sem vistoria é prejuízo certo." },
      ],
    },
    {
      id: "m9a5", titulo: "Compradores profissionais: departamento de compras, leilão reverso e “melhor e última oferta”", minutos: 10,
      resumo: "Construtoras grandes e mineradoras têm compradores treinados para espremer margem. Como manter valor, evitar o leilão e não cair no blefe.",
      blocos: [
        { tipo: "p", texto: "O comprador profissional não decide pela máquina; decide por preço e prazo dentro de uma especificação. Ele vai dizer que tem 3 cotações, que o concorrente está 10% abaixo e que precisa da “melhor e última” até sexta. Boa parte disso é tática. Sua defesa: relação com quem USA a máquina (engenheiro, operação), especificação que valoriza o que você tem e disciplina para não dar a última oferta duas vezes." },
        { tipo: "lista", titulo: "Antes de entrar no processo", itens: [
          "Chegue antes do departamento de compras: engenheiro, gerente de produção, mecânico. Eles escrevem a especificação e defendem a marca por dentro.",
          "Descubra o critério real: só preço? Prazo de entrega? Assistência? Pontuação técnica?",
          "Saiba sua BATNA e o seu limite antes da primeira rodada. Escreva.",
          "Coloque valor na especificação: assistência em 24 h, garantia, treinamento, consumo — coisas que a marca mais barata não atende.",
        ] },
        { tipo: "tabela", titulo: "Táticas do comprador e sua resposta", colunas: ["Tática", "Resposta"], linhas: [
          ["“Tenho 3 cotações e você é o mais caro”", "“Posso ver a especificação das outras? Quero garantir que estamos comparando a mesma configuração, garantia e prazo.” (raramente é igual)"],
          ["“Manda a melhor e última até sexta”", "Dê uma melhor e última — uma só. Se pedirem outra: “essa foi a última. O que mudou?”"],
          ["Leilão reverso / rodadas de desconto", "Entre com pacote de valor, não com margem para cair. Se o processo for só preço e você não tiver margem, saia com elegância e mantenha a relação com a operação."],
          ["“O diretor só aprova com X% a menos”", "“Entendo. O que o diretor precisa ver para aprovar no valor certo? Posso apresentar o custo de 5 anos para ele?”"],
          ["Silêncio depois da proposta", "Follow-up com valor (caso, TCO), não com desconto. Quem baixa preço no silêncio ensina o comprador."],
          ["Prazo de pagamento absurdo", "Troque: prazo maior por preço cheio; preço menor por pagamento à vista."],
        ] },
        { tipo: "script", titulo: "Frases", itens: [
          "“Eu consigo chegar nesse valor se mudarmos a configuração — mas aí a máquina não é a que o seu engenheiro especificou. Prefere que eu mantenha a especificação?”",
          "“Essa é a minha melhor e última. Se o critério for só preço e outra marca ficar abaixo, respeito a decisão. O que eu garanto é a assistência e o custo de 5 anos — e isso o engenheiro sabe.”",
        ] },
        { tipo: "caso", titulo: "Caso: a especificação que venceu o leilão", situacao: "Mineradora abriu cotação de 2 escavadeiras com 4 marcas. O departamento de compras só olhava preço.", acao: "O vendedor já tinha relação com o gerente de produção, que incluiu na especificação atendimento em 24 h com técnico residente na região e consumo máximo por hora medido.", resultado: "Duas marcas foram desclassificadas na especificação. A New Holland venceu com preço 6% acima da terceira.", licao: "A venda para comprador profissional se ganha na especificação, antes da cotação." },
      ],
      missao: "Liste as 3 empresas grandes da sua região com departamento de compras. Para cada uma, identifique quem usa a máquina (engenheiro/produção) e agende uma visita técnica com eles — antes de qualquer cotação.",
      quiz: [
        { pergunta: "Comprador diz que você é o mais caro entre 3 cotações. Você:", opcoes: ["Baixa 10%", "Pede para comparar a especificação, garantia e prazo — raramente é igual", "Desiste"], correta: 1, explicacao: "Compare de igual para igual antes de mexer no preço." },
        { pergunta: "Quantas vezes você dá a “melhor e última”?", opcoes: ["Quantas pedirem", "Uma", "Nenhuma"], correta: 1, explicacao: "A segunda “última” mostra que a primeira era blefe — e destrói sua credibilidade." },
      ],
    },
    {
      id: "m9a6", titulo: "Do “sim” ao faturamento: velocidade e follow-up", minutos: 8,
      resumo: "A venda só existe quando fatura. Processo, prazos e o acompanhamento que evita o arrependimento do comprador.",
      blocos: [
        { tipo: "lista", titulo: "Checklist pós-“sim”", itens: [
          "Mesmo dia: proposta assinada + lista de documentos enviada + negociação movida para a coluna correta no CRM.",
          "48 h: documentos no banco; cliente informado do prazo de análise.",
          "A cada 2 dias: um contato curto com novidade (“banco pediu X”, “aprovado, agora é a nota”). Silêncio gera arrependimento.",
          "Aprovação: agende a entrega técnica na hora e confirme com o operador.",
          "Faturamento: registre a data no CRM — é o que alimenta o Pós-venda e os marcos de 30/60/180/365 dias.",
          "Entrega: foto com a equipe, treinamento, contatos da assistência. Peça a indicação suave.",
        ] },
        { tipo: "p", titulo: "Arrependimento do comprador", texto: "Entre o “sim” e a entrega, o cliente ouve o cunhado, o concorrente liga, o banco demora. Sua presença constante nesse período — com informação e segurança — é o que garante que o “sim” vire faturamento. Um cliente bem acompanhado aqui vira indicação depois." },
        { tipo: "script", titulo: "Mensagens do período de análise", itens: [
          "Dia 1: “Fulano, documentos enviados ao banco às 14h. Prazo de análise: 5 dias úteis. Te aviso de cada passo.”",
          "Dia 3: “Banco pediu a certidão municipal atualizada. Consegue me mandar hoje? Assim não perde o prazo.”",
          "Aprovação: “Aprovado! Agora é nota e entrega. Já reservei a unidade do pátio. Dia 25 às 9h a entrega técnica com o Zé, pode ser?”",
          "Véspera da entrega: “Amanhã 9h a E215C chega. O técnico vai passar 3 horas com o Zé. Prepara o café que eu levo o bolo.”",
        ] },
        { tipo: "tabela", titulo: "Sinais de risco no período e ação", colunas: ["Sinal", "Ação"], linhas: [
          ["Cliente demora a mandar documento", "Ligue. Ofereça ir buscar. Documento parado é dúvida escondida."],
          ["“Deixa eu ver uma coisa antes”", "Pergunte o que. Provavelmente concorrente ou cunhado. Reforce a decisão com a conta e o plano B."],
          ["Banco pede garantia extra", "Traga a alternativa antes de o cliente desanimar (outro banco, consórcio, entrada maior com a usada)."],
          ["Atraso de fábrica", "Avise antes de o cliente perguntar; ofereça compensação (revisão, treinamento)."],
        ] },
        { tipo: "caso", titulo: "Caso: o silêncio de 9 dias", situacao: "Vendedor mandou os documentos ao banco e ficou 9 dias sem falar com o cliente, esperando a resposta.", acao: "No 8º dia o concorrente visitou o cliente com uma condição “urgente”. O cliente ligou perguntando se podia cancelar.", resultado: "Salvou a venda com a aprovação que saiu no 9º dia, mas por pouco. Passou a fazer contato a cada 2 dias.", licao: "Silêncio no período de análise é convite ao concorrente e ao arrependimento." },
      ],
      missao: "Para cada negociação em análise de crédito, defina hoje a data do próximo contato (máximo 2 dias) e registre no CRM. Confira a data de faturamento das ganhas do mês.",
      quiz: [
        { pergunta: "Quanto tempo no máximo entre contatos durante a análise de crédito?", opcoes: ["Uma semana", "Dois dias", "Só quando o banco responder"], correta: 1, explicacao: "Silêncio abre espaço para arrependimento e concorrente. Contato curto e frequente segura a venda." },
        { pergunta: "Cliente demora a mandar um documento. Provável significado:", opcoes: ["Esqueceu", "Dúvida escondida — ligue e resolva", "Nada"], correta: 1, explicacao: "Documento parado costuma ser hesitação. Traga à tona." },
      ],
    },
  ],
  prova: [
    { pergunta: "Pequeno empreiteiro sem histórico bancário longo. Instrumento a tentar:", opcoes: ["Só Finame", "CRD/linhas regionais, consórcio ou usada na entrada", "À vista"], correta: 1, explicacao: "Cada instrumento fecha um perfil." },
    { pergunta: "“Quero 10% de desconto” é posição. O interesse provável é:", opcoes: ["Vencer o vendedor", "Parcela que caiba no caixa", "Testar você"], correta: 1, explicacao: "Resolva o interesse com prazo e carência." },
    { pergunta: "Qual pergunta é calibrada?", opcoes: ["“Por que você não fecha?”", "“Como eu faria pra caber no seu caixa?”", "“Você vai fechar?”"], correta: 1, explicacao: "“Como” e “o que” convidam à colaboração." },
    { pergunta: "Usada avaliada acima do mercado para fechar:", opcoes: ["É estratégia válida", "Adia o prejuízo para o estoque e destrói credibilidade", "É obrigatório"], correta: 1, explicacao: "Avalie com referência e reparo; ofereça escolha." },
    { pergunta: "Comprador profissional pede a segunda “melhor e última”. Você:", opcoes: ["Dá outra", "“Essa foi a última. O que mudou?”", "Desiste"], correta: 1, explicacao: "A segunda última expõe o blefe da primeira." },
    { pergunta: "Entre o sim e o faturamento, o maior risco é:", opcoes: ["A máquina", "Silêncio e arrependimento", "O banco"], correta: 1, explicacao: "Presença a cada 2 dias segura a venda." },
  ],
};
